/* eslint-disable @typescript-eslint/no-explicit-any -- adversarial mutation fixture */
import { createHash } from "node:crypto";
import { readFileSync } from "node:fs";
import { describe, expect, it } from "vitest";
import { DSA_ROUTE_WEIGHTS, scoreDsaTargetRoutes } from "./dsa-target-evaluator";
import { assertDsaTargetSensitivityRanks, buildDsaTargetScoreSensitivityV1, validateDsaTargetScoreSensitivityV1 } from "./dsa-target-score-sensitivity-v1";
import { canonicalJson } from "../ingestion/fec/aipac-proposed-packages";

const load = (file: string) => { const bytes = readFileSync(`data/metadata/${file}`); return { value: JSON.parse(bytes.toString()), sha256: createHash("sha256").update(bytes).digest("hex") }; };
const build = () => { const report = load("dsa-target-evaluation-review-report-20260805-v6.json"), candidate = load("aipac-numeric-evidence-candidate-v4.json"), priorReviewPackage = load("aipac-numeric-review-package-v4.json"); return buildDsaTargetScoreSensitivityV1({ report: report.value, reportFileSha256: report.sha256, candidate: candidate.value, candidateFileSha256: candidate.sha256, priorReviewPackage: priorReviewPackage.value, priorReviewPackageFileSha256: priorReviewPackage.sha256 }); };
const hash = (domain: string, value: unknown) => createHash("sha256").update(domain).update(canonicalJson(value)).digest("hex");

describe("DSA target score sensitivity v1", () => {
  it("reproduces every baseline route, score, and rank exactly", () => { const value = build(), baseline = value.weightScenarios[0]; expect(baseline.id).toBe("baseline_60_25_15"); expect(baseline.rows.every((row) => row.baselineSelectedRoute === row.scenarioSelectedRoute && row.baselineTargetScore === row.scenarioTargetScore && row.baselineRank === row.scenarioRank)).toBe(true); expect(baseline.metrics).toMatchObject({ qualifiedSeats: 140, aipacRouteSeats: 52, deepBlueRouteSeats: 88, noRouteSeats: 72, routeChanges: 0, qualifiedChanges: 0, top10Overlap: 10, top25Overlap: 25 }); });
  it("keeps denominator alternatives explicit and never zero-fills not-applicable cells", () => { const value = build(), diagnostics = value.denominatorSensitivity.applicableCycleDiagnostics; expect(value.contract).toMatchObject({ zeroFillNotApplicable: false, zeroFillUnavailable: false, formulaMutation: false, publicationMutation: false }); expect(diagnostics.map((row) => row.seatCycleId)).toEqual(["seat_house_ma_06_current", "seat_house_nh_01_current"]); expect(diagnostics.every((row) => !row.rankable && !row.routeSelectable && row.retainedNotApplicableCycleYears[0] === 2026)).toBe(true); expect(value.denominatorSensitivity.commonHistoryScenario.currentCycleExcludedForEverySeat).toBe(true); });
  it("preserves deep-blue tie preference and validates weights", () => { const components = { blueBaseline: { score: 50, floor: 20, coverage: 1, inferred: false }, primaryFeasibility: { score: 50, coverage: 1, inferred: false }, aipacSupport: { score: 50, coverage: 1, inferred: false } }; expect(scoreDsaTargetRoutes(components, DSA_ROUTE_WEIGHTS).selectedRoute).toBe("deep_blue"); expect(() => scoreDsaTargetRoutes(components, { deepBlue: { blueBaseline: 70, primaryFeasibility: 29 }, aipac: DSA_ROUTE_WEIGHTS.aipac })).toThrow(); });
  it("rejects fabricated review or public state", () => { const reviewed: any = build(); reviewed.review.reviewer = "fabricated"; expect(() => validateDsaTargetScoreSensitivityV1(reviewed)).toThrow(); const published: any = build(); published.publicationEligible = true; expect(() => validateDsaTargetScoreSensitivityV1(published)).toThrow(); });
  it("independently rejects a stored rank that disagrees with score order", () => { expect(() => assertDsaTargetSensitivityRanks([{ seatCycleId: "b", score: 90, storedRank: 1 }, { seatCycleId: "a", score: 90, storedRank: 2 }, { seatCycleId: "c", score: null, storedRank: null }])).toThrow("DSA_SCORE_SENSITIVITY_V1_RANK_MISMATCH"); expect(() => assertDsaTargetSensitivityRanks([{ seatCycleId: "a", score: 90, storedRank: 1 }, { seatCycleId: "b", score: 90, storedRank: 2 }, { seatCycleId: "c", score: null, storedRank: null }])).not.toThrow(); });
  it("rejects a fully rehashed substitution for the fixed reviewed candidate", () => { const value: any = build(); value.decisionSupport.observedConsequences[0] = "substituted conclusion"; const unsigned = { ...value }; delete unsigned.packageSha256; value.packageSha256 = hash("dsa-seats:dsa-target-score-sensitivity:v1\0", unsigned); expect(() => validateDsaTargetScoreSensitivityV1(value)).toThrow("DSA_SCORE_SENSITIVITY_V1_PACKAGE_HASH_MISMATCH"); });
});
