import { createHash } from "node:crypto";
import { z } from "zod";
import { DSA_ROUTE_WEIGHTS, DSA_TARGET_FORMULA_VERSION, evaluateDsaTarget } from "./dsa-target-evaluator";
import { dsaTargetEvaluationSchema, validateDsaTargetFactualProjection } from "./dsa-target-review-report";
import { validateDsaTargetReviewReportV2 } from "./dsa-target-review-report-v2";
import { validateWashingtonHouseTopTwoResultsReceipt } from "../ingestion/elections/washington-house-top-two-results-receipt";
import { validateAipacNumericEvidenceCandidateV2 } from "../ingestion/fec/aipac-numeric-evidence-candidate-v2";
import { canonicalJson } from "../ingestion/fec/aipac-proposed-packages";
import { validateIncumbentTenureFactualCandidate } from "../ingestion/identity/incumbent-tenure-factual-candidate";

const SHA = z.string().regex(/^[a-f0-9]{64}$/);
const REPORT_SHA256 = "e428fc823ab5f6efa3eacd8f5191fabcb4580a7c4775b0bcae74518917523db9";
const aipacStatus = z.enum(["numeric_candidate_complete", "blocked_pending_mapping_review", "blocked_invalid_origin", "formula_incompatible_top_two"]);
const numericSeatStatus = z.enum(["complete", "blocked_pending_mapping", "partially_blocked_invalid_origin"]);

export const dsaTargetReviewReportV4Schema = z.strictObject({
  schema: z.literal("dsa-target-evaluation-review-report-v4"), version: z.literal(4), generatedAt: z.literal("2026-08-05T19:30:00.000Z"),
  reviewerOnly: z.literal(true), publicationEligible: z.literal(false), review: z.strictObject({ status: z.literal("proposed"), reviewer: z.null(), reviewedAt: z.null() }),
  scope: z.strictObject({ releaseId: z.literal("rel_full_20260804_v2"), sourceCutoff: z.literal("2026-08-04"), formulaVersion: z.literal(DSA_TARGET_FORMULA_VERSION), expectedSeats: z.literal(212), observedSeats: z.literal(212) }),
  inputClosure: z.strictObject({
    projectionFileSha256: z.literal("e1c2ab02cafb2ee438ec1a1c936f903e38cc19553d187b6b2d1dca55dc99d3ec"),
    tenureCandidateFileSha256: z.literal("18e8fc5a7496362efdb33d07a2012063c2a2062ddb14c5b8605dbbebb28db867"),
    priorReport: z.strictObject({ sourceLockId: z.literal("dsa-target-evaluation-review-report-20260804-v2"), fileSha256: z.literal("05d7d59ac91eb4987dc5784fb158e3b2501b3b41c9bba336523c4182a2a01e6e"), reportSha256: SHA, unchanged: z.literal(true) }),
    aipacCandidate: z.strictObject({ sourceLockId: z.literal("aipac-numeric-evidence-candidate-v2"), fileSha256: z.literal("a02fa77b1caefc3fbfeb99035d648f4fe9934b374797b524498530f03a2ea12d"), packageSha256: z.literal("c2e864ee17fe3c264c0a3e49ca2d24bc9fef2498ec998aae90b61920ebaf00ab"), reviewerOnly: z.literal(true), publicationEligible: z.literal(false), defaultUse: z.literal("use_in_reviewer_only_evaluation_exclude_from_publication") }),
    formulaEligibilityAuthority: z.strictObject({ sourceLockId: z.literal("washington-house-top-two-results-receipt-20220802-20240806-v1"), fileSha256: z.literal("eac5df760de11a6612c2e8a95374a8041b2debb94068e0d08afadecd775963da"), packageSha256: z.literal("a930a28888f3892f0b4459063b0d0a2c195bfada26960b705757124a403e5e13"), nominationSystem: z.literal("top_two"), formulaApplicability: z.literal("confirmed_incompatible") }),
  }),
  weights: z.strictObject({ deepBlue: z.strictObject({ blueBaseline: z.literal(70), primaryFeasibility: z.literal(30) }), aipac: z.strictObject({ aipacSupport: z.literal(60), blueBaseline: z.literal(25), primaryFeasibility: z.literal(15) }) }),
  summary: z.strictObject({
    seats: z.literal(212), aipacCandidateCompleteSeats: z.literal(206), aipacEvaluatorCompleteSeats: z.literal(198), aipacBlockedPendingSeats: z.literal(6), aipacBlockedInvalidOriginSeats: z.literal(0), aipacFormulaIncompatibleSeats: z.literal(8), aipacCandidateEvidenceRows: z.literal(274), aipacNumericEvidenceRowsUsed: z.literal(260), seatsWithAipacCandidateEvidence: z.literal(124), seatsWithAipacEvidenceUsed: z.literal(118),
    aipacRouteSelections: z.literal(52), routeChangesFromV2: z.literal(52), partialQualified: z.literal(140), partialNotQualified: z.literal(72),
  }),
  seats: z.array(z.strictObject({
    reviewRank: z.number().int().positive().nullable(), seatCycleId: z.string().min(1), stateCode: z.string().length(2), districtCode: z.string().min(1), status: z.enum(["partial_qualified", "partial_not_qualified"]),
    aipac: z.strictObject({ status: aipacStatus, numericSeatStatus, numericEvidenceUsed: z.boolean(), evidenceCount: z.number().int().nonnegative(), coverageComplete: z.boolean(), componentScore: z.number().min(0).max(100).nullable(), candidateSeatSha256: SHA, invalidOriginRejected: z.boolean(), proposedNoHouseCandidacyCycles: z.array(z.union([z.literal(2022), z.literal(2024), z.literal(2026)])) }),
    routeChangedFromV2: z.boolean(), priorSelectedRoute: z.enum(["deep_blue", "aipac_supported_blue"]).nullable(), evaluation: dsaTargetEvaluationSchema,
  })).length(212),
  reportSha256: SHA,
});
export type DsaTargetReviewReportV4 = z.infer<typeof dsaTargetReviewReportV4Schema>;

const digest = (domain: string, value: unknown): string => createHash("sha256").update(domain).update(canonicalJson(value)).digest("hex");
const order = (a: string, b: string): number => Buffer.compare(Buffer.from(a), Buffer.from(b));

export function buildDsaTargetReviewReportV4(input: Readonly<{ projection: unknown; projectionFileSha256: string; tenureCandidate: unknown; tenureFileSha256: string; priorReport: unknown; priorReportFileSha256: string; aipacCandidate: unknown; aipacCandidateFileSha256: string; formulaEligibilityAuthority: unknown; formulaEligibilityAuthorityFileSha256: string }>): DsaTargetReviewReportV4 {
  const projection = validateDsaTargetFactualProjection(input.projection), tenure = validateIncumbentTenureFactualCandidate(input.tenureCandidate), prior = validateDsaTargetReviewReportV2(input.priorReport), candidate = validateAipacNumericEvidenceCandidateV2(input.aipacCandidate), authority = validateWashingtonHouseTopTwoResultsReceipt(input.formulaEligibilityAuthority as never);
  const hashes = [input.projectionFileSha256, input.tenureFileSha256, input.priorReportFileSha256, input.aipacCandidateFileSha256, input.formulaEligibilityAuthorityFileSha256];
  if (canonicalJson(hashes) !== canonicalJson(["e1c2ab02cafb2ee438ec1a1c936f903e38cc19553d187b6b2d1dca55dc99d3ec", "18e8fc5a7496362efdb33d07a2012063c2a2062ddb14c5b8605dbbebb28db867", "05d7d59ac91eb4987dc5784fb158e3b2501b3b41c9bba336523c4182a2a01e6e", "a02fa77b1caefc3fbfeb99035d648f4fe9934b374797b524498530f03a2ea12d", "eac5df760de11a6612c2e8a95374a8041b2debb94068e0d08afadecd775963da"])) throw new Error("DSA_TARGET_REPORT_V4_INPUT_HASH_INVALID");
  if (projection.release.sourceCutoff !== candidate.sourceCutoff || tenure.sourceCutoff !== candidate.sourceCutoff || prior.scope.releaseId !== projection.release.id || !candidate.reviewerOnly || candidate.publicationEligible || candidate.defaultUse !== "use_in_reviewer_only_evaluation_exclude_from_publication") throw new Error("DSA_TARGET_REPORT_V4_INPUT_CLOSURE_INVALID");
  if (authority.packageSha256 !== "a930a28888f3892f0b4459063b0d0a2c195bfada26960b705757124a403e5e13" || authority.nominationSystem !== "top_two" || authority.formulaApplicability !== "confirmed_incompatible" || authority.summary.scoreEligibleContests !== 0) throw new Error("DSA_TARGET_REPORT_V4_FORMULA_AUTHORITY_INVALID");
  const tenureBySeat = new Map(tenure.facts.map((row) => [row.seatCycleId, row])), priorBySeat = new Map(prior.seats.map((row) => [row.seatCycleId, row])), aipacBySeat = new Map(candidate.seats.map((row) => [row.seatCycleId, row]));
  if (tenureBySeat.size !== 212 || priorBySeat.size !== 212 || aipacBySeat.size !== 212) throw new Error("DSA_TARGET_REPORT_V4_UNIVERSE_INVALID");
  const missing = { kind: "missing", reason: "not_collected" } as const;
  const rows = projection.seats.map((seat) => {
    const tenureFact = tenureBySeat.get(seat.seatCycleId), priorSeat = priorBySeat.get(seat.seatCycleId), aipacSeat = aipacBySeat.get(seat.seatCycleId);
    if (!tenureFact || !priorSeat || !aipacSeat) throw new Error("DSA_TARGET_REPORT_V4_SEAT_JOIN_MISSING");
    const numericComplete = aipacSeat.status === "complete", formulaCompatible = seat.stateCode !== "WA", complete = numericComplete && formulaCompatible;
    const coverage = [2022, 2024, 2026].map((cycleYear) => {
      const direct = aipacSeat.coverage.find((cell) => cell.cycleYear === cycleYear && cell.channel === "direct_aipac_pac")!, independent = aipacSeat.coverage.find((cell) => cell.cycleYear === cycleYear && cell.channel === "independent_udp")!;
      const directComplete = complete && direct.disposition.startsWith("complete_"), independentComplete = complete && independent.disposition.startsWith("complete_");
      return { cycleYear, directContributionsComplete: directComplete, independentExpendituresComplete: independentComplete, directContributionSnapshotIds: directComplete ? direct.sourceSnapshotIds : [], independentExpenditureSnapshotIds: independentComplete ? independent.sourceSnapshotIds : [], directContributionArtifactSha256s: directComplete ? direct.sourceArtifactSha256s : [], independentExpenditureArtifactSha256s: independentComplete ? independent.sourceArtifactSha256s : [] };
    });
    const closure = [...new Set([...seat.presidentialMargin2024.inputSnapshotIds, ...(seat.incumbentCashOnHand.kind === "value" ? seat.incumbentCashOnHand.inputSnapshotIds : []), ...tenureFact.selectedEvaluatorValue.inputSnapshotIds, ...(complete ? aipacSeat.evidence.flatMap((row) => [...row.inputSnapshotIds, ...(row.kind === "direct_contribution" ? [] : row.classificationSnapshotIds)]) : []), ...coverage.flatMap((row) => [...row.directContributionSnapshotIds, ...row.independentExpenditureSnapshotIds])])].sort(order);
    const evaluation = evaluateDsaTarget({ metadata: { seatCycleId: seat.seatCycleId, incumbentFecCandidateId: aipacSeat.incumbentCandidateId, sourceCutoff: projection.release.sourceCutoff, currentCycleYear: 2026, inputSnapshotIds: closure }, seat: { chamber: "house", officeKind: "house_voting", electionType: "regular", occupancy: "occupied", incumbentParty: "democratic" }, electoral: { presidentialDemocraticMargins: [{ year: 2024, marginPoints: seat.presidentialMargin2024.value, observedAt: seat.presidentialMargin2024.observedAt, inputSnapshotIds: seat.presidentialMargin2024.inputSnapshotIds, geographyCompatibility: seat.presidentialMargin2024.geographyCompatibility }] }, feasibility: { priorPrimaryMarginPoints: missing, incumbentCashOnHand: seat.incumbentCashOnHand.kind === "value" ? seat.incumbentCashOnHand : { kind: "missing", reason: seat.incumbentCashOnHand.reason }, incumbentTenureYears: { kind: "value", value: tenureFact.selectedEvaluatorValue.value, observedAt: tenureFact.selectedEvaluatorValue.observedAt, inputSnapshotIds: tenureFact.selectedEvaluatorValue.inputSnapshotIds, methodologyVersion: tenureFact.selectedEvaluatorValue.methodologyVersion }, filingRunwayDays: missing, priorDemocraticPrimaryVotes: missing, priorProgressivePrimaryShare: missing }, aipac: { evidence: complete ? aipacSeat.evidence : [], coverage } });
    if (complete !== (evaluation.components.aipacSupport.score !== null) || (!complete && evaluation.selectedRoute === "aipac_supported_blue")) throw new Error("DSA_TARGET_REPORT_V4_NONCOMPLETE_SCORING_FIREWALL_FAILED");
    const routeChangedFromV2 = evaluation.selectedRoute !== priorSeat.evaluation.selectedRoute;
    const status = !formulaCompatible ? "formula_incompatible_top_two" as const : aipacSeat.status === "complete" ? "numeric_candidate_complete" as const : aipacSeat.status === "blocked_pending_mapping" ? "blocked_pending_mapping_review" as const : "blocked_invalid_origin" as const;
    return { reviewRank: null as number | null, seatCycleId: seat.seatCycleId, stateCode: seat.stateCode, districtCode: seat.districtCode, status: evaluation.status === "qualified" ? "partial_qualified" as const : "partial_not_qualified" as const, aipac: { status, numericSeatStatus: aipacSeat.status, numericEvidenceUsed: complete, evidenceCount: aipacSeat.evidence.length, coverageComplete: complete, componentScore: evaluation.components.aipacSupport.score, candidateSeatSha256: aipacSeat.seatSha256, invalidOriginRejected: aipacSeat.resolutionContext.invalidOriginDispositionSha256s.length > 0, proposedNoHouseCandidacyCycles: aipacSeat.resolutionContext.proposedNoHouseCandidacyCycles }, routeChangedFromV2, priorSelectedRoute: priorSeat.evaluation.selectedRoute, evaluation };
  });
  rows.filter((row) => row.evaluation.targetScore !== null).sort((a, b) => b.evaluation.targetScore! - a.evaluation.targetScore! || order(a.seatCycleId, b.seatCycleId)).forEach((row, index) => { row.reviewRank = index + 1; });
  const seats = rows.sort((a, b) => order(a.seatCycleId, b.seatCycleId)), used = seats.filter((row) => row.aipac.numericEvidenceUsed), unsigned = {
    schema: "dsa-target-evaluation-review-report-v4" as const, version: 4 as const, generatedAt: "2026-08-05T19:30:00.000Z" as const, reviewerOnly: true as const, publicationEligible: false as const, review: { status: "proposed" as const, reviewer: null, reviewedAt: null }, scope: { releaseId: projection.release.id, sourceCutoff: projection.release.sourceCutoff, formulaVersion: DSA_TARGET_FORMULA_VERSION, expectedSeats: 212 as const, observedSeats: 212 as const },
    inputClosure: { projectionFileSha256: input.projectionFileSha256 as "e1c2ab02cafb2ee438ec1a1c936f903e38cc19553d187b6b2d1dca55dc99d3ec", tenureCandidateFileSha256: input.tenureFileSha256 as "18e8fc5a7496362efdb33d07a2012063c2a2062ddb14c5b8605dbbebb28db867", priorReport: { sourceLockId: "dsa-target-evaluation-review-report-20260804-v2" as const, fileSha256: input.priorReportFileSha256 as "05d7d59ac91eb4987dc5784fb158e3b2501b3b41c9bba336523c4182a2a01e6e", reportSha256: prior.reportSha256, unchanged: true as const }, aipacCandidate: { sourceLockId: "aipac-numeric-evidence-candidate-v2" as const, fileSha256: input.aipacCandidateFileSha256 as "a02fa77b1caefc3fbfeb99035d648f4fe9934b374797b524498530f03a2ea12d", packageSha256: candidate.packageSha256, reviewerOnly: true as const, publicationEligible: false as const, defaultUse: candidate.defaultUse }, formulaEligibilityAuthority: { sourceLockId: "washington-house-top-two-results-receipt-20220802-20240806-v1" as const, fileSha256: input.formulaEligibilityAuthorityFileSha256 as "eac5df760de11a6612c2e8a95374a8041b2debb94068e0d08afadecd775963da", packageSha256: authority.packageSha256 as "a930a28888f3892f0b4459063b0d0a2c195bfada26960b705757124a403e5e13", nominationSystem: authority.nominationSystem as "top_two", formulaApplicability: authority.formulaApplicability as "confirmed_incompatible" } }, weights: DSA_ROUTE_WEIGHTS,
    summary: { seats: 212 as const, aipacCandidateCompleteSeats: 206 as const, aipacEvaluatorCompleteSeats: used.length as 198, aipacBlockedPendingSeats: 6 as const, aipacBlockedInvalidOriginSeats: 0 as const, aipacFormulaIncompatibleSeats: 8 as const, aipacCandidateEvidenceRows: 274 as const, aipacNumericEvidenceRowsUsed: used.reduce((sum, row) => sum + row.aipac.evidenceCount, 0), seatsWithAipacCandidateEvidence: 124 as const, seatsWithAipacEvidenceUsed: used.filter((row) => row.aipac.evidenceCount > 0).length, aipacRouteSelections: seats.filter((row) => row.evaluation.selectedRoute === "aipac_supported_blue").length, routeChangesFromV2: seats.filter((row) => row.routeChangedFromV2).length, partialQualified: seats.filter((row) => row.status === "partial_qualified").length, partialNotQualified: seats.filter((row) => row.status === "partial_not_qualified").length }, seats,
  };
  const report = dsaTargetReviewReportV4Schema.parse({ ...unsigned, reportSha256: digest("dsa-seats:dsa-target-evaluation-review-report:v4\0", unsigned) });
  return validateDsaTargetReviewReportV4(report);
}

export function validateDsaTargetReviewReportV4(value: unknown): DsaTargetReviewReportV4 {
  const parsed = dsaTargetReviewReportV4Schema.parse(value), { reportSha256, ...unsigned } = parsed;
  if (reportSha256 !== digest("dsa-seats:dsa-target-evaluation-review-report:v4\0", unsigned)) throw new Error("DSA_TARGET_REPORT_V4_HASH_MISMATCH");
  if (reportSha256 !== REPORT_SHA256) throw new Error("DSA_TARGET_REPORT_V4_RELEASE_DERIVATION_MISMATCH");
  const ranked = parsed.seats.filter((row) => row.evaluation.targetScore !== null).sort((a, b) => a.reviewRank! - b.reviewRank!);
  const used = parsed.seats.filter((row) => row.aipac.numericEvidenceUsed);
  if (parsed.summary.partialQualified + parsed.summary.partialNotQualified !== 212 || parsed.summary.aipacNumericEvidenceRowsUsed !== used.reduce((sum, row) => sum + row.aipac.evidenceCount, 0) || parsed.summary.seatsWithAipacEvidenceUsed !== used.filter((row) => row.aipac.evidenceCount > 0).length || parsed.summary.aipacRouteSelections !== parsed.seats.filter((row) => row.evaluation.selectedRoute === "aipac_supported_blue").length || parsed.summary.routeChangesFromV2 !== parsed.seats.filter((row) => row.routeChangedFromV2).length || ranked.some((row, index) => row.reviewRank !== index + 1) || parsed.seats.some((row) => row.aipac.coverageComplete !== (row.evaluation.components.aipacSupport.score !== null) || row.aipac.numericEvidenceUsed !== row.aipac.coverageComplete || row.routeChangedFromV2 !== (row.priorSelectedRoute !== row.evaluation.selectedRoute) || (!row.aipac.coverageComplete && row.evaluation.selectedRoute === "aipac_supported_blue") || (row.stateCode === "WA") !== (row.aipac.status === "formula_incompatible_top_two"))) throw new Error("DSA_TARGET_REPORT_V4_INVARIANT_FAILED");
  return parsed;
}
