import { createHash } from "node:crypto";
import { z } from "zod";
import { DSA_ROUTE_WEIGHTS, dsaRouteWeightsSchema, scoreAipacEvidence, scoreDsaTargetRoutes, type DsaRouteWeights, type DsaTargetComponents } from "./dsa-target-evaluator";
import { validateDsaTargetReviewReportV6 } from "./dsa-target-review-report-v6";
import { validateAipacNumericEvidenceCandidateV4 } from "../ingestion/fec/aipac-numeric-evidence-candidate-v4";
import { validateAipacNumericReviewPackageV4 } from "../ingestion/fec/aipac-numeric-review-package-v4";
import { canonicalJson } from "../ingestion/fec/aipac-proposed-packages";

const SHA = z.string().regex(/^[a-f0-9]{64}$/);
const INPUTS = { reportFile: "cdce153e52cbfbcee669c64a6671b4d52cb11728f04c8a7bb2092c96b0063401", reportPackage: "9df5ab4cb08556aac9a5ff87aa33d8bdf2aeed3a374b9c7d46fdc60e1d7965b7", candidateFile: "4aae1342be0439f510f44bdb0b1d5d73066e6823599a186ab066cf7495eb9099", candidatePackage: "7dd647ac1937b2104aef91db249e9afa72867464035560590823ec57c08b8c28", reviewFile: "f47e499ac4aa3973ee186b87c46627495348684167ecc16927e0934cfd169d36", reviewPackage: "6fcef33a2cd0e6a744b62ae6ed12050107dbc8fc5ba9239644b1ecd1206e3110" } as const;
const EXPECTED = { baselineSeatSet: "03ad9f3156881601c080b588980b4b7de72082c678335f14efb43ddbe0191ae5", scenarioSet: "8585674546314f305bdd9a69145f4ecdaed158471efbf68792717ac150a5504f", commonRowSet: "300ee7d846f516c87b4b8c3289160fc5bbb2f569697af000effa219e6a5e9a93", commonScenario: "406b99319469916bf92cd6ab307d51658f7cefa256864a965025781131f3f703", package: "e609c49c0ae71bb79df50d373c70cbecd96cff1a4891ee7c8a9577c8c0dfba5e" } as const;
const order = (a: string, b: string): number => Buffer.compare(Buffer.from(a), Buffer.from(b));
const hash = (domain: string, value: unknown): string => createHash("sha256").update(domain).update(canonicalJson(value)).digest("hex");
const round1 = (value: number): number => Math.round(value * 10) / 10;

const scenarios = [
  { id: "baseline_60_25_15", purpose: "reproduction_control", weights: DSA_ROUTE_WEIGHTS },
  { id: "support_lower_40_40_20", purpose: "lower_aipac_influence_stress_test", weights: { deepBlue: DSA_ROUTE_WEIGHTS.deepBlue, aipac: { aipacSupport: 40, blueBaseline: 40, primaryFeasibility: 20 } } },
  { id: "support_higher_75_15_10", purpose: "upper_bound_aipac_influence_stress_test", weights: { deepBlue: DSA_ROUTE_WEIGHTS.deepBlue, aipac: { aipacSupport: 75, blueBaseline: 15, primaryFeasibility: 10 } } },
] as const;

const route = z.enum(["deep_blue", "aipac_supported_blue"]);
const components = z.strictObject({ blueBaseline: z.strictObject({ score: z.number(), floor: z.number(), coverage: z.number(), inferred: z.boolean() }), primaryFeasibility: z.strictObject({ score: z.number(), coverage: z.number(), inferred: z.boolean() }), aipacSupport: z.strictObject({ score: z.number().nullable(), coverage: z.number(), inferred: z.boolean(), missingReason: z.literal("not_collected").optional() }) });
const row = z.strictObject({ seatCycleId: z.string(), stateCode: z.string().length(2), baselineRank: z.number().int().positive().nullable(), scenarioRank: z.number().int().positive().nullable(), baselineSelectedRoute: route.nullable(), scenarioSelectedRoute: route.nullable(), baselineTargetScore: z.number().nullable(), scenarioTargetScore: z.number().nullable(), baselineAipacRouteScore: z.number().nullable(), scenarioAipacRouteScore: z.number().nullable(), components, routeChanged: z.boolean(), qualifiedChanged: z.boolean(), targetScoreDelta: z.number().nullable(), rankDelta: z.number().int().nullable(), rowSha256: SHA });
const metrics = z.strictObject({ qualifiedSeats: z.number().int(), aipacRouteSeats: z.number().int(), deepBlueRouteSeats: z.number().int(), noRouteSeats: z.number().int(), routeChanges: z.number().int(), qualifiedChanges: z.number().int(), scoreChangedSeats: z.number().int(), meanAbsoluteTargetScoreDelta: z.number(), maxAbsoluteTargetScoreDelta: z.number(), meanAbsoluteRankDelta: z.number(), maxAbsoluteRankDelta: z.number().int(), top10Overlap: z.number().int(), top25Overlap: z.number().int(), materialRankMovementsAtLeast10: z.number().int() });
const weightScenario = z.strictObject({ id: z.enum(["baseline_60_25_15", "support_lower_40_40_20", "support_higher_75_15_10"]), purpose: z.enum(["reproduction_control", "lower_aipac_influence_stress_test", "upper_bound_aipac_influence_stress_test"]), weights: dsaRouteWeightsSchema, rows: z.array(row).length(212), metrics, rowSetSha256: SHA, scenarioSha256: SHA });
const diagnostic = z.strictObject({ seatCycleId: z.enum(["seat_house_ma_06_current", "seat_house_nh_01_current"]), retainedNotApplicableCycleYears: z.tuple([z.literal(2026)]), denominatorCells: z.literal(4), historicalEvidenceCount: z.number().int(), historicalEvidenceSetSha256: SHA, diagnosticAipacScore: z.number(), rankable: z.literal(false), routeSelectable: z.literal(false), rationale: z.literal("shortened_window_is_not_cross_seat_comparable"), rowSha256: SHA });
const commonRow = z.strictObject({ seatCycleId: z.string(), stateCode: z.string().length(2), sourceSeatSha256: SHA, historicalEvidenceCount: z.number().int(), historicalEvidenceSetSha256: SHA, historicalAipacScore: z.number().nullable(), scenarioRank: z.number().int().positive().nullable(), selectedRoute: route.nullable(), targetScore: z.number().nullable(), aipacRouteScore: z.number().nullable(), exclusionReason: z.enum(["aipac_route_formula_incompatible_top_two", "four_cell_coverage_incomplete"]).nullable(), rowSha256: SHA });
type CommonUnsigned = Omit<z.infer<typeof commonRow>, "rowSha256">;

export const dsaTargetScoreSensitivityV1Schema = z.strictObject({
  schema: z.literal("dsa-target-score-sensitivity-candidate-v1"), version: z.literal(1), generatedAt: z.literal("2026-08-05T23:50:00.000Z"), reviewerOnly: z.literal(true), publicationEligible: z.literal(false), status: z.literal("proposed_robustness_analysis_not_formula_validation"), review: z.strictObject({ status: z.literal("proposed"), reviewer: z.null(), reviewedAt: z.null(), resolution: z.null() }),
  inputs: z.strictObject({ baselineReport: z.strictObject({ sourceLockId: z.literal("dsa-target-evaluation-review-report-20260805-v6"), fileSha256: z.literal(INPUTS.reportFile), reportSha256: z.literal(INPUTS.reportPackage) }), numericCandidate: z.strictObject({ sourceLockId: z.literal("aipac-numeric-evidence-candidate-v4"), fileSha256: z.literal(INPUTS.candidateFile), packageSha256: z.literal(INPUTS.candidatePackage) }), priorReviewPackage: z.strictObject({ sourceLockId: z.literal("aipac-numeric-review-package-v4"), fileSha256: z.literal(INPUTS.reviewFile), packageSha256: z.literal(INPUTS.reviewPackage), decisionId: z.literal("aipac-numeric:accept-v01-score-contract-v4"), decisionUnresolved: z.literal(true) }) }),
  contract: z.strictObject({ baselineFormulaVersion: z.literal("dsa-primary-target-v0.1"), formulaMutation: z.literal(false), publicationMutation: z.literal(false), qualificationGates: z.literal("preserve_v01_blue_floors_positive_aipac_and_deep_blue_tie_break"), zeroFillNotApplicable: z.literal(false), zeroFillUnavailable: z.literal(false), interpretation: z.literal("descriptive_robustness_not_causal_validation_or_recommendation") }),
  baselineSeatSetSha256: SHA, scenarioSetSha256: SHA, weightScenarios: z.tuple([weightScenario, weightScenario, weightScenario]),
  denominatorSensitivity: z.strictObject({ fixedSixCellDefault: z.literal("retain_null_for_any_required_not_applicable_or_unavailable_cell"), applicableCycleDiagnostics: z.tuple([diagnostic, diagnostic]), commonHistoryScenario: z.strictObject({ id: z.literal("common_history_2022_2024_four_cell"), formulaCandidateId: z.literal("dsa-primary-target-history-window-sensitivity-v1"), currentCycleExcludedForEverySeat: z.literal(true), evidenceRecencyReferenceCycleYear: z.literal(2026), evidenceRecencyContract: z.literal("retain_v01_2026_analysis_anchor_while_excluding_2026_evidence_and_coverage"), denominatorCells: z.literal(4), weights: dsaRouteWeightsSchema, rows: z.array(commonRow).length(212), metrics, rowSetSha256: SHA, scenarioSha256: SHA }) }),
  decisionSupport: z.strictObject({ informsDecisionId: z.literal("aipac-numeric:accept-v01-score-contract-v4"), analysisConclusion: z.literal("supports_bound_decision_recommendation_to_retain_60_25_15_and_fixed_six_cell_exclusion"), alternativeImplications: z.tuple([z.literal("different_weights_require_separately_versioned_formula_candidate"), z.literal("common_history_denominator_requires_separately_versioned_formula_candidate"), z.literal("no_methodology_approval_keeps_scores_reviewer_only")]), observedConsequences: z.array(z.string()).min(2), confidence: z.literal("high_for_reproducibility_medium_for_normative_weight_choice"), lifecycle: z.literal("evidence_for_bound_existing_decision_not_an_independent_decision") }),
  packageSha256: SHA,
});
export type DsaTargetScoreSensitivityV1 = z.infer<typeof dsaTargetScoreSensitivityV1Schema>;

type ScenarioRow = z.infer<typeof row>;
const rank = <T extends { seatCycleId: string; scenarioTargetScore: number | null; scenarioRank: number | null }>(rows: T[]): void => { rows.filter((value) => value.scenarioTargetScore !== null).sort((a, b) => b.scenarioTargetScore! - a.scenarioTargetScore! || order(a.seatCycleId, b.seatCycleId)).forEach((value, index) => { value.scenarioRank = index + 1; }); };
export function assertDsaTargetSensitivityRanks(rows: ReadonlyArray<{ seatCycleId: string; score: number | null; storedRank: number | null }>): void {
  const expected = new Map(rows.filter((value) => value.score !== null).sort((a, b) => b.score! - a.score! || order(a.seatCycleId, b.seatCycleId)).map((value, index) => [value.seatCycleId, index + 1]));
  if (rows.some((value) => value.storedRank !== (expected.get(value.seatCycleId) ?? null))) throw new Error("DSA_SCORE_SENSITIVITY_V1_RANK_MISMATCH");
}
const top = (rows: ScenarioRow[], key: "baselineRank" | "scenarioRank", count: number): Set<string> => new Set(rows.filter((value) => value[key] !== null && value[key]! <= count).map((value) => value.seatCycleId));
const overlap = (a: Set<string>, b: Set<string>): number => [...a].filter((id) => b.has(id)).length;
function scenarioMetrics(rows: ScenarioRow[]): z.infer<typeof metrics> { const comparableScores = rows.filter((value) => value.baselineTargetScore !== null && value.scenarioTargetScore !== null), comparableRanks = rows.filter((value) => value.baselineRank !== null && value.scenarioRank !== null), scoreDeltas = comparableScores.map((value) => Math.abs(value.scenarioTargetScore! - value.baselineTargetScore!)), rankDeltas = comparableRanks.map((value) => Math.abs(value.scenarioRank! - value.baselineRank!)); return { qualifiedSeats: rows.filter((value) => value.scenarioSelectedRoute !== null).length, aipacRouteSeats: rows.filter((value) => value.scenarioSelectedRoute === "aipac_supported_blue").length, deepBlueRouteSeats: rows.filter((value) => value.scenarioSelectedRoute === "deep_blue").length, noRouteSeats: rows.filter((value) => value.scenarioSelectedRoute === null).length, routeChanges: rows.filter((value) => value.routeChanged).length, qualifiedChanges: rows.filter((value) => value.qualifiedChanged).length, scoreChangedSeats: scoreDeltas.filter((value) => value > 0).length, meanAbsoluteTargetScoreDelta: round1(scoreDeltas.reduce((sum, value) => sum + value, 0) / Math.max(1, scoreDeltas.length)), maxAbsoluteTargetScoreDelta: round1(Math.max(0, ...scoreDeltas)), meanAbsoluteRankDelta: round1(rankDeltas.reduce((sum, value) => sum + value, 0) / Math.max(1, rankDeltas.length)), maxAbsoluteRankDelta: Math.max(0, ...rankDeltas), top10Overlap: overlap(top(rows, "baselineRank", 10), top(rows, "scenarioRank", 10)), top25Overlap: overlap(top(rows, "baselineRank", 25), top(rows, "scenarioRank", 25)), materialRankMovementsAtLeast10: rankDeltas.filter((value) => value >= 10).length }; }
const sealRows = (rows: Omit<ScenarioRow, "rowSha256">[]): ScenarioRow[] => rows.sort((a, b) => order(a.seatCycleId, b.seatCycleId)).map((value) => row.parse({ ...value, rowSha256: hash("dsa-seats:dsa-target-score-sensitivity-row:v1\0", value) }));

export function buildDsaTargetScoreSensitivityV1(input: Readonly<{ report: unknown; reportFileSha256: string; candidate: unknown; candidateFileSha256: string; priorReviewPackage: unknown; priorReviewPackageFileSha256: string }>): DsaTargetScoreSensitivityV1 {
  if (input.reportFileSha256 !== INPUTS.reportFile || input.candidateFileSha256 !== INPUTS.candidateFile || input.priorReviewPackageFileSha256 !== INPUTS.reviewFile) throw new Error("DSA_SCORE_SENSITIVITY_V1_INPUT_FILE_HASH_MISMATCH");
  const report = validateDsaTargetReviewReportV6(input.report), candidate = validateAipacNumericEvidenceCandidateV4(input.candidate), reviewPackage = validateAipacNumericReviewPackageV4(input.priorReviewPackage);
  const priorDecision = reviewPackage.decisions.find((value) => value.decisionId === "aipac-numeric:accept-v01-score-contract-v4");
  if (report.reportSha256 !== INPUTS.reportPackage || candidate.packageSha256 !== INPUTS.candidatePackage || reviewPackage.packageSha256 !== INPUTS.reviewPackage || !priorDecision || priorDecision.resolution !== null || priorDecision.reviewer !== null || priorDecision.reviewedAt !== null) throw new Error("DSA_SCORE_SENSITIVITY_V1_INPUT_PACKAGE_HASH_MISMATCH");
  const candidateBySeat = new Map(candidate.seats.map((value) => [value.seatCycleId, value]));
  const baselineProjection = report.seats.map((value) => ({ seatCycleId: value.seatCycleId, stateCode: value.stateCode, aipacStatus: value.aipac.status, numericEvidenceUsed: value.aipac.numericEvidenceUsed, coverageComplete: value.aipac.coverageComplete, pendingCycleYears: value.aipac.pendingCycleYears, notApplicableCycleYears: value.aipac.notApplicableCycleYears, reviewRank: value.reviewRank, evaluation: value.evaluation })).sort((a, b) => order(a.seatCycleId, b.seatCycleId));
  const weightScenarios = scenarios.map((scenario) => {
    const unsignedRows = report.seats.map((value) => { const calculated = scoreDsaTargetRoutes(value.evaluation.components as DsaTargetComponents, scenario.weights as DsaRouteWeights); return { seatCycleId: value.seatCycleId, stateCode: value.stateCode, baselineRank: value.reviewRank, scenarioRank: null, baselineSelectedRoute: value.evaluation.selectedRoute, scenarioSelectedRoute: calculated.selectedRoute, baselineTargetScore: value.evaluation.targetScore, scenarioTargetScore: calculated.targetScore, baselineAipacRouteScore: value.evaluation.routeScores.aipacSupportedBlue, scenarioAipacRouteScore: calculated.routeScores.aipacSupportedBlue, components: value.evaluation.components, routeChanged: value.evaluation.selectedRoute !== calculated.selectedRoute, qualifiedChanged: (value.evaluation.selectedRoute === null) !== (calculated.selectedRoute === null), targetScoreDelta: value.evaluation.targetScore !== null && calculated.targetScore !== null ? round1(calculated.targetScore - value.evaluation.targetScore) : null, rankDelta: null } as Omit<ScenarioRow, "rowSha256">; });
    rank(unsignedRows); for (const value of unsignedRows) value.rankDelta = value.baselineRank !== null && value.scenarioRank !== null ? value.scenarioRank - value.baselineRank : null;
    const rows = sealRows(unsignedRows), summary = scenarioMetrics(rows), rowSetSha256 = hash("dsa-seats:dsa-target-score-sensitivity-row-set:v1\0", rows), base = { ...scenario, rows, metrics: summary, rowSetSha256 }; return weightScenario.parse({ ...base, scenarioSha256: hash("dsa-seats:dsa-target-score-sensitivity-scenario:v1\0", base) });
  }) as [z.infer<typeof weightScenario>, z.infer<typeof weightScenario>, z.infer<typeof weightScenario>];
  const diagnosticIds = ["seat_house_ma_06_current", "seat_house_nh_01_current"] as const;
  const applicableCycleDiagnostics = diagnosticIds.map((seatCycleId) => { const source = candidateBySeat.get(seatCycleId)!; const evidence = source.evidence.filter((value) => value.cycleYear === 2022 || value.cycleYear === 2024); const unsigned = { seatCycleId, retainedNotApplicableCycleYears: [2026] as [2026], denominatorCells: 4 as const, historicalEvidenceCount: evidence.length, historicalEvidenceSetSha256: hash("dsa-seats:dsa-target-score-sensitivity-historical-evidence:v1\0", evidence), diagnosticAipacScore: scoreAipacEvidence(evidence, 2026), rankable: false as const, routeSelectable: false as const, rationale: "shortened_window_is_not_cross_seat_comparable" as const }; return diagnostic.parse({ ...unsigned, rowSha256: hash("dsa-seats:dsa-target-score-sensitivity-diagnostic:v1\0", unsigned) }); }) as [z.infer<typeof diagnostic>, z.infer<typeof diagnostic>];
  const commonUnsigned: CommonUnsigned[] = report.seats.map((value) => { const source = candidateBySeat.get(value.seatCycleId)!; const cells = source.coverage.filter((cell) => cell.cycleYear === 2022 || cell.cycleYear === 2024), complete = cells.length === 4 && cells.every((cell) => cell.disposition.startsWith("complete_")), evidence = source.evidence.filter((item) => item.cycleYear === 2022 || item.cycleYear === 2024), excluded = value.stateCode === "WA" ? "aipac_route_formula_incompatible_top_two" as const : !complete ? "four_cell_coverage_incomplete" as const : null, historicalAipacScore = excluded ? null : scoreAipacEvidence(evidence, 2026), calculated = scoreDsaTargetRoutes({ ...value.evaluation.components, aipacSupport: { score: historicalAipacScore, coverage: historicalAipacScore === null ? 0 : 1, inferred: historicalAipacScore === null } }, DSA_ROUTE_WEIGHTS); return { seatCycleId: value.seatCycleId, stateCode: value.stateCode, sourceSeatSha256: source.seatSha256, historicalEvidenceCount: evidence.length, historicalEvidenceSetSha256: hash("dsa-seats:dsa-target-score-sensitivity-historical-evidence:v1\0", evidence), historicalAipacScore, scenarioRank: null, selectedRoute: calculated.selectedRoute, targetScore: calculated.targetScore, aipacRouteScore: calculated.routeScores.aipacSupportedBlue, exclusionReason: excluded }; });
  const rankedCommon = commonUnsigned.filter((value) => value.targetScore !== null).sort((a, b) => b.targetScore! - a.targetScore! || order(a.seatCycleId, b.seatCycleId)); rankedCommon.forEach((value, index) => { value.scenarioRank = index + 1; });
  const commonRows = commonUnsigned.sort((a, b) => order(a.seatCycleId, b.seatCycleId)).map((value) => commonRow.parse({ ...value, rowSha256: hash("dsa-seats:dsa-target-score-sensitivity-common-history-row:v1\0", value) }));
  const commonAsScenario = commonRows.map((value) => { const baseline = report.seats.find((seat) => seat.seatCycleId === value.seatCycleId)!; return row.parse({ seatCycleId: value.seatCycleId, stateCode: value.stateCode, baselineRank: baseline.reviewRank, scenarioRank: value.scenarioRank, baselineSelectedRoute: baseline.evaluation.selectedRoute, scenarioSelectedRoute: value.selectedRoute, baselineTargetScore: baseline.evaluation.targetScore, scenarioTargetScore: value.targetScore, baselineAipacRouteScore: baseline.evaluation.routeScores.aipacSupportedBlue, scenarioAipacRouteScore: value.aipacRouteScore, components: baseline.evaluation.components, routeChanged: baseline.evaluation.selectedRoute !== value.selectedRoute, qualifiedChanged: (baseline.evaluation.selectedRoute === null) !== (value.selectedRoute === null), targetScoreDelta: baseline.evaluation.targetScore !== null && value.targetScore !== null ? round1(value.targetScore - baseline.evaluation.targetScore) : null, rankDelta: baseline.reviewRank !== null && value.scenarioRank !== null ? value.scenarioRank - baseline.reviewRank : null, rowSha256: hash("dsa-seats:dsa-target-score-sensitivity-common-comparison-row:v1\0", [baseline.seatCycleId, value.rowSha256]) }); });
  const commonBase = { id: "common_history_2022_2024_four_cell" as const, formulaCandidateId: "dsa-primary-target-history-window-sensitivity-v1" as const, currentCycleExcludedForEverySeat: true as const, evidenceRecencyReferenceCycleYear: 2026 as const, evidenceRecencyContract: "retain_v01_2026_analysis_anchor_while_excluding_2026_evidence_and_coverage" as const, denominatorCells: 4 as const, weights: DSA_ROUTE_WEIGHTS, rows: commonRows, metrics: scenarioMetrics(commonAsScenario), rowSetSha256: hash("dsa-seats:dsa-target-score-sensitivity-common-history-row-set:v1\0", commonRows) };
  const decisionSupport = { informsDecisionId: "aipac-numeric:accept-v01-score-contract-v4" as const, analysisConclusion: "supports_bound_decision_recommendation_to_retain_60_25_15_and_fixed_six_cell_exclusion" as const, alternativeImplications: ["different_weights_require_separately_versioned_formula_candidate", "common_history_denominator_requires_separately_versioned_formula_candidate", "no_methodology_approval_keeps_scores_reviewer_only"] as const, observedConsequences: ["The default preserves current-cycle comparability and keeps not-applicable values null.", "Alternative weights or denominator materially change ranks or eligibility and require a new formula candidate."], confidence: "high_for_reproducibility_medium_for_normative_weight_choice" as const, lifecycle: "evidence_for_bound_existing_decision_not_an_independent_decision" as const };
  const unsigned = { schema: "dsa-target-score-sensitivity-candidate-v1" as const, version: 1 as const, generatedAt: "2026-08-05T23:50:00.000Z" as const, reviewerOnly: true as const, publicationEligible: false as const, status: "proposed_robustness_analysis_not_formula_validation" as const, review: { status: "proposed" as const, reviewer: null, reviewedAt: null, resolution: null }, inputs: { baselineReport: { sourceLockId: "dsa-target-evaluation-review-report-20260805-v6" as const, fileSha256: INPUTS.reportFile, reportSha256: report.reportSha256 }, numericCandidate: { sourceLockId: "aipac-numeric-evidence-candidate-v4" as const, fileSha256: INPUTS.candidateFile, packageSha256: candidate.packageSha256 }, priorReviewPackage: { sourceLockId: "aipac-numeric-review-package-v4" as const, fileSha256: INPUTS.reviewFile, packageSha256: reviewPackage.packageSha256, decisionId: "aipac-numeric:accept-v01-score-contract-v4" as const, decisionUnresolved: true as const } }, contract: { baselineFormulaVersion: "dsa-primary-target-v0.1" as const, formulaMutation: false as const, publicationMutation: false as const, qualificationGates: "preserve_v01_blue_floors_positive_aipac_and_deep_blue_tie_break" as const, zeroFillNotApplicable: false as const, zeroFillUnavailable: false as const, interpretation: "descriptive_robustness_not_causal_validation_or_recommendation" as const }, baselineSeatSetSha256: hash("dsa-seats:dsa-target-score-sensitivity-baseline-seat-set:v1\0", baselineProjection), scenarioSetSha256: hash("dsa-seats:dsa-target-score-sensitivity-scenario-set:v1\0", weightScenarios), weightScenarios, denominatorSensitivity: { fixedSixCellDefault: "retain_null_for_any_required_not_applicable_or_unavailable_cell" as const, applicableCycleDiagnostics, commonHistoryScenario: { ...commonBase, scenarioSha256: hash("dsa-seats:dsa-target-score-sensitivity-common-history:v1\0", commonBase) } }, decisionSupport };
  return validateDsaTargetScoreSensitivityV1({ ...unsigned, packageSha256: hash("dsa-seats:dsa-target-score-sensitivity:v1\0", unsigned) });
}

export function validateDsaTargetScoreSensitivityV1(value: unknown): DsaTargetScoreSensitivityV1 {
  const parsed = dsaTargetScoreSensitivityV1Schema.parse(value), { packageSha256, ...unsigned } = parsed;
  if (packageSha256 !== EXPECTED.package || packageSha256 !== hash("dsa-seats:dsa-target-score-sensitivity:v1\0", unsigned) || parsed.baselineSeatSetSha256 !== EXPECTED.baselineSeatSet || parsed.scenarioSetSha256 !== EXPECTED.scenarioSet || parsed.scenarioSetSha256 !== hash("dsa-seats:dsa-target-score-sensitivity-scenario-set:v1\0", parsed.weightScenarios)) throw new Error("DSA_SCORE_SENSITIVITY_V1_PACKAGE_HASH_MISMATCH");
  for (const scenario of parsed.weightScenarios) { if (canonicalJson(scenario.weights) !== canonicalJson(scenarios.find((value) => value.id === scenario.id)!.weights) || scenario.rows.some((value, index) => index > 0 && order(scenario.rows[index - 1]!.seatCycleId, value.seatCycleId) >= 0)) throw new Error("DSA_SCORE_SENSITIVITY_V1_SCENARIO_CONTRACT_MISMATCH"); assertDsaTargetSensitivityRanks(scenario.rows.map((value) => ({ seatCycleId: value.seatCycleId, score: value.scenarioTargetScore, storedRank: value.scenarioRank }))); for (const value of scenario.rows) { const { rowSha256, ...rowUnsigned } = value; if (rowSha256 !== hash("dsa-seats:dsa-target-score-sensitivity-row:v1\0", rowUnsigned)) throw new Error("DSA_SCORE_SENSITIVITY_V1_ROW_HASH_MISMATCH"); const calculated = scoreDsaTargetRoutes(value.components as DsaTargetComponents, scenario.weights); if (calculated.selectedRoute !== value.scenarioSelectedRoute || calculated.targetScore !== value.scenarioTargetScore || calculated.routeScores.aipacSupportedBlue !== value.scenarioAipacRouteScore) throw new Error("DSA_SCORE_SENSITIVITY_V1_ROW_CALCULATION_MISMATCH"); } if (canonicalJson(scenario.metrics) !== canonicalJson(scenarioMetrics(scenario.rows)) || scenario.rowSetSha256 !== hash("dsa-seats:dsa-target-score-sensitivity-row-set:v1\0", scenario.rows)) throw new Error("DSA_SCORE_SENSITIVITY_V1_METRICS_MISMATCH"); }
  const baseline = parsed.weightScenarios[0], common = parsed.denominatorSensitivity.commonHistoryScenario;
  assertDsaTargetSensitivityRanks(common.rows.map((value) => ({ seatCycleId: value.seatCycleId, score: value.targetScore, storedRank: value.scenarioRank })));
  for (const [index, value] of common.rows.entries()) { const { rowSha256, ...rowUnsigned } = value; if ((index > 0 && order(common.rows[index - 1]!.seatCycleId, value.seatCycleId) >= 0) || rowSha256 !== hash("dsa-seats:dsa-target-score-sensitivity-common-history-row:v1\0", rowUnsigned)) throw new Error("DSA_SCORE_SENSITIVITY_V1_COMMON_ROW_MISMATCH"); const base = baseline.rows.find((candidate) => candidate.seatCycleId === value.seatCycleId)!; const calculated = scoreDsaTargetRoutes({ ...base.components, aipacSupport: { score: value.historicalAipacScore, coverage: value.historicalAipacScore === null ? 0 : 1, inferred: value.historicalAipacScore === null } }, DSA_ROUTE_WEIGHTS); if (calculated.selectedRoute !== value.selectedRoute || calculated.targetScore !== value.targetScore || calculated.routeScores.aipacSupportedBlue !== value.aipacRouteScore) throw new Error("DSA_SCORE_SENSITIVITY_V1_COMMON_CALCULATION_MISMATCH"); }
  if (common.rowSetSha256 !== EXPECTED.commonRowSet || common.rowSetSha256 !== hash("dsa-seats:dsa-target-score-sensitivity-common-history-row-set:v1\0", common.rows) || common.scenarioSha256 !== EXPECTED.commonScenario || common.scenarioSha256 !== hash("dsa-seats:dsa-target-score-sensitivity-common-history:v1\0", Object.fromEntries(Object.entries(common).filter(([key]) => key !== "scenarioSha256")))) throw new Error("DSA_SCORE_SENSITIVITY_V1_COMMON_HASH_MISMATCH");
  if (baseline.rows.some((value) => value.baselineSelectedRoute !== value.scenarioSelectedRoute || value.baselineTargetScore !== value.scenarioTargetScore || value.baselineAipacRouteScore !== value.scenarioAipacRouteScore || value.baselineRank !== value.scenarioRank) || parsed.denominatorSensitivity.applicableCycleDiagnostics.some((value) => value.rankable || value.routeSelectable)) throw new Error("DSA_SCORE_SENSITIVITY_V1_BASELINE_OR_DIAGNOSTIC_STATE_MISMATCH");
  return parsed;
}
