import { createHash } from "node:crypto";
import { z } from "zod";
import { DSA_ROUTE_WEIGHTS, DSA_TARGET_FORMULA_VERSION, evaluateDsaTarget } from "./dsa-target-evaluator";
import { dsaTargetEvaluationSchema, validateDsaTargetFactualProjection } from "./dsa-target-review-report";
import { validateDsaTargetReviewReportV2 } from "./dsa-target-review-report-v2";
import { validateWashingtonHouseTopTwoResultsReceipt } from "../ingestion/elections/washington-house-top-two-results-receipt";
import { validateAipacNumericEvidenceCandidateV4 } from "../ingestion/fec/aipac-numeric-evidence-candidate-v4";
import { canonicalJson } from "../ingestion/fec/aipac-proposed-packages";
import { validateIncumbentTenureFactualCandidate } from "../ingestion/identity/incumbent-tenure-factual-candidate";

const SHA = z.string().regex(/^[a-f0-9]{64}$/);
const INPUT_FILE_SHA256 = {
  projection: "e1c2ab02cafb2ee438ec1a1c936f903e38cc19553d187b6b2d1dca55dc99d3ec",
  tenure: "18e8fc5a7496362efdb33d07a2012063c2a2062ddb14c5b8605dbbebb28db867",
  prior: "05d7d59ac91eb4987dc5784fb158e3b2501b3b41c9bba336523c4182a2a01e6e",
  candidate: "4aae1342be0439f510f44bdb0b1d5d73066e6823599a186ab066cf7495eb9099",
  authority: "eac5df760de11a6612c2e8a95374a8041b2debb94068e0d08afadecd775963da",
} as const;
const NUMERIC_V4_PACKAGE_SHA256 = "7dd647ac1937b2104aef91db249e9afa72867464035560590823ec57c08b8c28";
const PRIOR_REPORT_SHA256 = "63a057b7832efd4c0bac4896dda94432996c9c04a95952084c631f32d8b0227d";
const WA_AUTHORITY_PACKAGE_SHA256 = "a930a28888f3892f0b4459063b0d0a2c195bfada26960b705757124a403e5e13";
const order = (a: string, b: string): number => Buffer.compare(Buffer.from(a), Buffer.from(b));
const digest = (domain: string, value: unknown): string => createHash("sha256").update(domain).update(canonicalJson(value)).digest("hex");
const numericStatus = z.enum(["complete", "partially_blocked_pending_mapping", "partially_blocked_invalid_origin"]);
const aipacStatus = z.enum(["numeric_candidate_complete", "blocked_pending_mapping_review", "not_applicable_current_cycle", "formula_incompatible_top_two"]);

export const dsaTargetReviewReportV6Schema = z.strictObject({
  schema: z.literal("dsa-target-evaluation-review-report-v6"), version: z.literal(6), generatedAt: z.literal("2026-08-05T23:15:00.000Z"),
  reviewerOnly: z.literal(true), publicationEligible: z.literal(false), review: z.strictObject({ status: z.literal("proposed"), reviewer: z.null(), reviewedAt: z.null() }),
  scope: z.strictObject({ releaseId: z.literal("rel_full_20260804_v2"), sourceCutoff: z.literal("2026-08-04"), formulaVersion: z.literal(DSA_TARGET_FORMULA_VERSION), expectedSeats: z.literal(212), observedSeats: z.literal(212) }),
  inputClosure: z.strictObject({ projectionFileSha256: z.literal(INPUT_FILE_SHA256.projection), tenureCandidateFileSha256: z.literal(INPUT_FILE_SHA256.tenure), priorReport: z.strictObject({ sourceLockId: z.literal("dsa-target-evaluation-review-report-20260804-v2"), fileSha256: z.literal(INPUT_FILE_SHA256.prior), reportSha256: z.literal(PRIOR_REPORT_SHA256), unchanged: z.literal(true) }), aipacCandidate: z.strictObject({ sourceLockId: z.literal("aipac-numeric-evidence-candidate-v4"), fileSha256: z.literal(INPUT_FILE_SHA256.candidate), packageSha256: z.literal(NUMERIC_V4_PACKAGE_SHA256), reviewerOnly: z.literal(true), publicationEligible: z.literal(false), defaultUse: z.literal("use_in_reviewer_only_evaluation_exclude_from_publication") }), formulaEligibilityAuthority: z.strictObject({ sourceLockId: z.literal("washington-house-top-two-results-receipt-20220802-20240806-v1"), fileSha256: z.literal(INPUT_FILE_SHA256.authority), packageSha256: z.literal(WA_AUTHORITY_PACKAGE_SHA256), nominationSystem: z.literal("top_two"), formulaApplicability: z.literal("confirmed_incompatible") }) }),
  weights: z.strictObject({ deepBlue: z.strictObject({ blueBaseline: z.literal(70), primaryFeasibility: z.literal(30) }), aipac: z.strictObject({ aipacSupport: z.literal(60), blueBaseline: z.literal(25), primaryFeasibility: z.literal(15) }) }),
  summary: z.strictObject({ seats: z.literal(212), aipacCandidateCompleteSeats: z.literal(212), aipacEvaluatorCompleteSeats: z.number().int(), aipacBlockedPendingSeats: z.literal(0), aipacNotApplicableCurrentCycleSeats: z.literal(2), aipacFormulaIncompatibleSeats: z.literal(8), aipacCandidateEvidenceRows: z.number().int(), aipacNumericEvidenceRowsUsed: z.number().int(), seatsWithAipacCandidateEvidence: z.number().int(), seatsWithAipacEvidenceUsed: z.number().int(), aipacRouteSelections: z.number().int(), routeChangesFromV2: z.number().int(), partialQualified: z.number().int(), partialNotQualified: z.number().int() }),
  seats: z.array(z.strictObject({ reviewRank: z.number().int().positive().nullable(), seatCycleId: z.string().min(1), stateCode: z.string().length(2), districtCode: z.string().min(1), status: z.enum(["partial_qualified", "partial_not_qualified"]), aipac: z.strictObject({ status: aipacStatus, numericSeatStatus: numericStatus, numericEvidenceUsed: z.boolean(), evidenceCount: z.number().int().nonnegative(), coverageComplete: z.boolean(), componentScore: z.number().min(0).max(100).nullable(), candidateSeatSha256: SHA, invalidOriginRejected: z.boolean(), pendingCycleYears: z.array(z.number().int()), notApplicableCycleYears: z.array(z.number().int()) }), routeChangedFromV2: z.boolean(), priorSelectedRoute: z.enum(["deep_blue", "aipac_supported_blue"]).nullable(), evaluation: dsaTargetEvaluationSchema })).length(212),
  reportSha256: SHA,
});
export type DsaTargetReviewReportV6 = z.infer<typeof dsaTargetReviewReportV6Schema>;

export function buildDsaTargetReviewReportV6(input: Readonly<{ projection: unknown; projectionFileSha256: string; tenureCandidate: unknown; tenureFileSha256: string; priorReport: unknown; priorReportFileSha256: string; aipacCandidate: unknown; aipacCandidateFileSha256: string; formulaEligibilityAuthority: unknown; formulaEligibilityAuthorityFileSha256: string }>): DsaTargetReviewReportV6 {
  const projection = validateDsaTargetFactualProjection(input.projection);
  const tenure = validateIncumbentTenureFactualCandidate(input.tenureCandidate);
  const prior = validateDsaTargetReviewReportV2(input.priorReport);
  const candidate = validateAipacNumericEvidenceCandidateV4(input.aipacCandidate);
  const authority = validateWashingtonHouseTopTwoResultsReceipt(input.formulaEligibilityAuthority as never);
  if (canonicalJson([input.projectionFileSha256, input.tenureFileSha256, input.priorReportFileSha256, input.aipacCandidateFileSha256, input.formulaEligibilityAuthorityFileSha256]) !== canonicalJson([INPUT_FILE_SHA256.projection, INPUT_FILE_SHA256.tenure, INPUT_FILE_SHA256.prior, INPUT_FILE_SHA256.candidate, INPUT_FILE_SHA256.authority]) || candidate.packageSha256 !== NUMERIC_V4_PACKAGE_SHA256 || prior.reportSha256 !== PRIOR_REPORT_SHA256 || authority.packageSha256 !== WA_AUTHORITY_PACKAGE_SHA256 || projection.release.sourceCutoff !== candidate.sourceCutoff || tenure.sourceCutoff !== candidate.sourceCutoff || prior.scope.releaseId !== projection.release.id || !candidate.reviewerOnly || candidate.publicationEligible || candidate.defaultUse !== "use_in_reviewer_only_evaluation_exclude_from_publication" || authority.nominationSystem !== "top_two" || authority.formulaApplicability !== "confirmed_incompatible" || authority.summary.scoreEligibleContests !== 0) throw new Error("DSA_TARGET_REPORT_V6_INPUT_CLOSURE_INVALID");
  const tenureBySeat = new Map(tenure.facts.map((row) => [row.seatCycleId, row]));
  const priorBySeat = new Map(prior.seats.map((row) => [row.seatCycleId, row]));
  const candidateBySeat = new Map(candidate.seats.map((row) => [row.seatCycleId, row]));
  if (tenureBySeat.size !== 212 || priorBySeat.size !== 212 || candidateBySeat.size !== 212) throw new Error("DSA_TARGET_REPORT_V6_UNIVERSE_INVALID");
  const missing = { kind: "missing", reason: "not_collected" } as const;
  const rows = projection.seats.map((seat) => {
    const tenureFact = tenureBySeat.get(seat.seatCycleId), priorSeat = priorBySeat.get(seat.seatCycleId), aipacSeat = candidateBySeat.get(seat.seatCycleId);
    if (!tenureFact || !priorSeat || !aipacSeat) throw new Error("DSA_TARGET_REPORT_V6_SEAT_JOIN_MISSING");
    const formulaCompatible = seat.stateCode !== "WA";
    const pending = aipacSeat.resolutionContext.pendingCycleYears.length > 0;
    const notApplicableCurrent = aipacSeat.resolutionContext.notApplicableCycleYears.includes(2026);
    const complete = formulaCompatible && !pending && !notApplicableCurrent && aipacSeat.status === "complete";
    const coverage = [2022, 2024, 2026].map((cycleYear) => {
      const direct = aipacSeat.coverage.find((cell) => cell.cycleYear === cycleYear && cell.channel === "direct_aipac_pac")!;
      const independent = aipacSeat.coverage.find((cell) => cell.cycleYear === cycleYear && cell.channel === "independent_udp")!;
      const directComplete = complete && direct.disposition.startsWith("complete_");
      const independentComplete = complete && independent.disposition.startsWith("complete_");
      return { cycleYear, directContributionsComplete: directComplete, independentExpendituresComplete: independentComplete, directContributionSnapshotIds: directComplete ? direct.sourceSnapshotIds : [], independentExpenditureSnapshotIds: independentComplete ? independent.sourceSnapshotIds : [], directContributionArtifactSha256s: directComplete ? direct.sourceArtifactSha256s : [], independentExpenditureArtifactSha256s: independentComplete ? independent.sourceArtifactSha256s : [] };
    });
    const closure = [...new Set([...seat.presidentialMargin2024.inputSnapshotIds, ...(seat.incumbentCashOnHand.kind === "value" ? seat.incumbentCashOnHand.inputSnapshotIds : []), ...tenureFact.selectedEvaluatorValue.inputSnapshotIds, ...(complete ? aipacSeat.evidence.flatMap((row) => [...row.inputSnapshotIds, ...(row.kind === "direct_contribution" ? [] : row.classificationSnapshotIds)]) : []), ...coverage.flatMap((row) => [...row.directContributionSnapshotIds, ...row.independentExpenditureSnapshotIds])])].sort(order);
    const evaluation = evaluateDsaTarget({ metadata: { seatCycleId: seat.seatCycleId, incumbentFecCandidateId: complete ? aipacSeat.incumbentCandidateId : null, sourceCutoff: projection.release.sourceCutoff, currentCycleYear: 2026, inputSnapshotIds: closure }, seat: { chamber: "house", officeKind: "house_voting", electionType: "regular", occupancy: "occupied", incumbentParty: "democratic" }, electoral: { presidentialDemocraticMargins: [{ year: 2024, marginPoints: seat.presidentialMargin2024.value, observedAt: seat.presidentialMargin2024.observedAt, inputSnapshotIds: seat.presidentialMargin2024.inputSnapshotIds, geographyCompatibility: seat.presidentialMargin2024.geographyCompatibility }] }, feasibility: { priorPrimaryMarginPoints: missing, incumbentCashOnHand: seat.incumbentCashOnHand.kind === "value" ? seat.incumbentCashOnHand : { kind: "missing", reason: seat.incumbentCashOnHand.reason }, incumbentTenureYears: { kind: "value", value: tenureFact.selectedEvaluatorValue.value, observedAt: tenureFact.selectedEvaluatorValue.observedAt, inputSnapshotIds: tenureFact.selectedEvaluatorValue.inputSnapshotIds, methodologyVersion: tenureFact.selectedEvaluatorValue.methodologyVersion }, filingRunwayDays: missing, priorDemocraticPrimaryVotes: missing, priorProgressivePrimaryShare: missing }, aipac: { evidence: complete ? aipacSeat.evidence : [], coverage } });
    if (complete !== (evaluation.components.aipacSupport.score !== null) || (!complete && evaluation.selectedRoute === "aipac_supported_blue")) throw new Error("DSA_TARGET_REPORT_V6_NONCOMPLETE_SCORING_FIREWALL_FAILED");
    const status = !formulaCompatible ? "formula_incompatible_top_two" as const : pending ? "blocked_pending_mapping_review" as const : notApplicableCurrent ? "not_applicable_current_cycle" as const : "numeric_candidate_complete" as const;
    return { reviewRank: null as number | null, seatCycleId: seat.seatCycleId, stateCode: seat.stateCode, districtCode: seat.districtCode, status: evaluation.status === "qualified" ? "partial_qualified" as const : "partial_not_qualified" as const, aipac: { status, numericSeatStatus: aipacSeat.status, numericEvidenceUsed: complete, evidenceCount: aipacSeat.evidence.length, coverageComplete: complete, componentScore: evaluation.components.aipacSupport.score, candidateSeatSha256: aipacSeat.seatSha256, invalidOriginRejected: aipacSeat.resolutionContext.invalidOriginDispositionSha256s.length > 0, pendingCycleYears: aipacSeat.resolutionContext.pendingCycleYears, notApplicableCycleYears: aipacSeat.resolutionContext.notApplicableCycleYears }, routeChangedFromV2: evaluation.selectedRoute !== priorSeat.evaluation.selectedRoute, priorSelectedRoute: priorSeat.evaluation.selectedRoute, evaluation };
  });
  rows.filter((row) => row.evaluation.targetScore !== null).sort((a, b) => b.evaluation.targetScore! - a.evaluation.targetScore! || order(a.seatCycleId, b.seatCycleId)).forEach((row, index) => { row.reviewRank = index + 1; });
  const seats = rows.sort((a, b) => order(a.seatCycleId, b.seatCycleId));
  const used = seats.filter((row) => row.aipac.numericEvidenceUsed);
  const unsigned = { schema: "dsa-target-evaluation-review-report-v6" as const, version: 6 as const, generatedAt: "2026-08-05T23:15:00.000Z" as const, reviewerOnly: true as const, publicationEligible: false as const, review: { status: "proposed" as const, reviewer: null, reviewedAt: null }, scope: { releaseId: projection.release.id, sourceCutoff: projection.release.sourceCutoff, formulaVersion: DSA_TARGET_FORMULA_VERSION, expectedSeats: 212 as const, observedSeats: 212 as const }, inputClosure: { projectionFileSha256: input.projectionFileSha256, tenureCandidateFileSha256: input.tenureFileSha256, priorReport: { sourceLockId: "dsa-target-evaluation-review-report-20260804-v2" as const, fileSha256: input.priorReportFileSha256, reportSha256: prior.reportSha256, unchanged: true as const }, aipacCandidate: { sourceLockId: "aipac-numeric-evidence-candidate-v4" as const, fileSha256: input.aipacCandidateFileSha256, packageSha256: candidate.packageSha256, reviewerOnly: true as const, publicationEligible: false as const, defaultUse: candidate.defaultUse }, formulaEligibilityAuthority: { sourceLockId: "washington-house-top-two-results-receipt-20220802-20240806-v1" as const, fileSha256: input.formulaEligibilityAuthorityFileSha256, packageSha256: authority.packageSha256, nominationSystem: authority.nominationSystem, formulaApplicability: authority.formulaApplicability } }, weights: DSA_ROUTE_WEIGHTS, summary: { seats: 212 as const, aipacCandidateCompleteSeats: candidate.summary.completeSeats, aipacEvaluatorCompleteSeats: used.length, aipacBlockedPendingSeats: seats.filter((row) => row.aipac.status === "blocked_pending_mapping_review").length, aipacNotApplicableCurrentCycleSeats: seats.filter((row) => row.aipac.status === "not_applicable_current_cycle").length, aipacFormulaIncompatibleSeats: seats.filter((row) => row.aipac.status === "formula_incompatible_top_two").length, aipacCandidateEvidenceRows: candidate.summary.evidenceRows, aipacNumericEvidenceRowsUsed: used.reduce((sum, row) => sum + row.aipac.evidenceCount, 0), seatsWithAipacCandidateEvidence: candidate.summary.seatsWithEvidence, seatsWithAipacEvidenceUsed: used.filter((row) => row.aipac.evidenceCount > 0).length, aipacRouteSelections: seats.filter((row) => row.evaluation.selectedRoute === "aipac_supported_blue").length, routeChangesFromV2: seats.filter((row) => row.routeChangedFromV2).length, partialQualified: seats.filter((row) => row.status === "partial_qualified").length, partialNotQualified: seats.filter((row) => row.status === "partial_not_qualified").length }, seats };
  return validateDsaTargetReviewReportV6({ ...unsigned, reportSha256: digest("dsa-seats:dsa-target-evaluation-review-report:v6\0", unsigned) });
}

export function validateDsaTargetReviewReportV6(value: unknown): DsaTargetReviewReportV6 {
  const parsed = dsaTargetReviewReportV6Schema.parse(value), { reportSha256, ...unsigned } = parsed;
  if (reportSha256 !== digest("dsa-seats:dsa-target-evaluation-review-report:v6\0", unsigned)) throw new Error("DSA_TARGET_REPORT_V6_HASH_MISMATCH");
  const used = parsed.seats.filter((row) => row.aipac.numericEvidenceUsed);
  const ranked = parsed.seats.filter((row) => row.evaluation.targetScore !== null).sort((a, b) => a.reviewRank! - b.reviewRank!);
  const ca = parsed.seats.find((row) => row.seatCycleId === "seat_house_ca_31_current");
  if (!ca || ca.aipac.status !== "numeric_candidate_complete" || !ca.aipac.coverageComplete || ca.aipac.pendingCycleYears.length || parsed.summary.partialQualified + parsed.summary.partialNotQualified !== 212 || parsed.summary.aipacCandidateCompleteSeats !== 212 || parsed.summary.aipacBlockedPendingSeats !== 0 || parsed.summary.aipacEvaluatorCompleteSeats !== used.length || parsed.summary.aipacNumericEvidenceRowsUsed !== used.reduce((sum, row) => sum + row.aipac.evidenceCount, 0) || parsed.summary.seatsWithAipacEvidenceUsed !== used.filter((row) => row.aipac.evidenceCount > 0).length || parsed.summary.aipacRouteSelections !== parsed.seats.filter((row) => row.evaluation.selectedRoute === "aipac_supported_blue").length || ranked.some((row, index) => row.reviewRank !== index + 1) || parsed.seats.some((row) => row.aipac.coverageComplete !== (row.evaluation.components.aipacSupport.score !== null) || row.aipac.numericEvidenceUsed !== row.aipac.coverageComplete || (!row.aipac.coverageComplete && row.evaluation.selectedRoute === "aipac_supported_blue") || (row.stateCode === "WA") !== (row.aipac.status === "formula_incompatible_top_two") || (row.aipac.status === "not_applicable_current_cycle" && row.aipac.componentScore !== null))) throw new Error("DSA_TARGET_REPORT_V6_INVARIANT_FAILED");
  return parsed;
}
