CREATE TABLE public.map_artifact_receipts (
  release_id text NOT NULL, map_artifact_id text NOT NULL, raw_store_kind raw_store_kind NOT NULL, store_identity text NOT NULL, object_key text NOT NULL, sha256 text NOT NULL, byte_size bigint NOT NULL, version_id text, etag text,
  CONSTRAINT map_artifact_receipts_release_id_map_artifact_id_pk PRIMARY KEY(release_id,map_artifact_id),
  CONSTRAINT map_artifact_receipts_store_identity_ck CHECK (length(store_identity) BETWEEN 1 AND 512),
  CONSTRAINT map_artifact_receipts_sha256_ck CHECK (sha256 ~ '^[a-f0-9]{64}$'), CONSTRAINT map_artifact_receipts_byte_size_ck CHECK (byte_size BETWEEN 1 AND 33554432),
  CONSTRAINT map_artifact_receipts_store_version_ck CHECK ((raw_store_kind='local' AND version_id IS NULL AND etag IS NULL) OR (raw_store_kind='s3' AND length(version_id)>0 AND length(etag)>0))
);
ALTER TABLE public.map_artifact_receipts ADD CONSTRAINT map_artifact_receipts_release_id_data_releases_id_fk FOREIGN KEY(release_id) REFERENCES public.data_releases(id);
ALTER TABLE public.map_artifact_receipts ADD CONSTRAINT map_artifact_receipts_release_id_map_artifact_id_map_artifacts_release_id_id_fk FOREIGN KEY(release_id,map_artifact_id) REFERENCES public.map_artifacts(release_id,id);
CREATE UNIQUE INDEX map_artifacts_release_artifact_uq ON public.map_artifacts(release_id,artifact_id);

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname='dsa_seats_migration_owner') THEN CREATE ROLE dsa_seats_migration_owner NOLOGIN; END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname='dsa_seats_web') THEN CREATE ROLE dsa_seats_web NOLOGIN; END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname='dsa_seats_ingest') THEN CREATE ROLE dsa_seats_ingest NOLOGIN; END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname='dsa_seats_release_preflight') THEN CREATE ROLE dsa_seats_release_preflight NOLOGIN NOINHERIT; END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname='dsa_seats_release_operator') THEN CREATE ROLE dsa_seats_release_operator NOLOGIN; END IF;
END $$;
GRANT USAGE ON SCHEMA public TO dsa_seats_migration_owner,dsa_seats_web,dsa_seats_ingest,dsa_seats_release_preflight,dsa_seats_release_operator;
GRANT CREATE ON SCHEMA public TO dsa_seats_migration_owner;
REVOKE CREATE ON SCHEMA public FROM PUBLIC;
DO $$ BEGIN EXECUTE format('REVOKE TEMPORARY ON DATABASE %I FROM PUBLIC,dsa_seats_web,dsa_seats_ingest,dsa_seats_release_preflight,dsa_seats_release_operator',current_database()); END $$;
GRANT SELECT,INSERT,UPDATE,DELETE ON ALL TABLES IN SCHEMA public TO dsa_seats_migration_owner;

CREATE OR REPLACE FUNCTION public.guard_map_artifact_receipt() RETURNS trigger LANGUAGE plpgsql SET search_path = pg_catalog, public, pg_temp AS $$
DECLARE geography_id text; BEGIN
 SELECT geography_version_id INTO geography_id FROM public.map_artifacts WHERE release_id=NEW.release_id AND id=NEW.map_artifact_id;
 IF NEW.release_id !~ '^[A-Za-z0-9_-]{1,128}$' OR geography_id IS NULL OR geography_id !~ '^[A-Za-z0-9_-]{1,128}$' OR NEW.object_key <> 'maps/'||NEW.release_id||'/'||geography_id||'.geojson' OR length(NEW.object_key) NOT BETWEEN 1 AND 384 OR NEW.object_key !~ '^[A-Za-z0-9_./-]+$' THEN RAISE EXCEPTION 'map receipt object key must be maps/{releaseId}/{geographyId}.geojson using bounded ASCII identifiers' USING ERRCODE='23514'; END IF; RETURN NEW; END $$;
CREATE TRIGGER map_artifact_receipts_shape_guard BEFORE INSERT OR UPDATE ON public.map_artifact_receipts FOR EACH ROW EXECUTE FUNCTION public.guard_map_artifact_receipt();
CREATE TRIGGER nationwide_content_map_artifact_receipts AFTER INSERT OR UPDATE OR DELETE ON public.map_artifact_receipts FOR EACH ROW EXECUTE FUNCTION public.guard_nationwide_content('maps');
CREATE OR REPLACE FUNCTION public.guard_release_insert() RETURNS trigger LANGUAGE plpgsql SET search_path = pg_catalog, public, pg_temp AS $$ BEGIN
 IF NEW.status<>'candidate' OR NEW.published_at IS NOT NULL OR (NEW.previous_release_id IS NOT NULL AND NOT EXISTS(SELECT 1 FROM public.data_releases p WHERE p.id=NEW.previous_release_id AND p.status IN('published','retired') AND p.source_cutoff=NEW.source_cutoff)) THEN RAISE EXCEPTION 'new releases must be candidate branches from a same-cutoff published or retired predecessor' USING ERRCODE='23514'; END IF; RETURN NEW; END $$;
CREATE TRIGGER data_releases_insert_guard BEFORE INSERT ON public.data_releases FOR EACH ROW EXECUTE FUNCTION public.guard_release_insert();
CREATE OR REPLACE FUNCTION public.guard_release_lifecycle() RETURNS trigger LANGUAGE plpgsql SET search_path = pg_catalog, public, pg_temp AS $$ BEGIN
 IF NEW.id IS DISTINCT FROM OLD.id OR NEW.label IS DISTINCT FROM OLD.label OR NEW.source_cutoff IS DISTINCT FROM OLD.source_cutoff OR NEW.created_at IS DISTINCT FROM OLD.created_at THEN RAISE EXCEPTION 'release identity metadata is immutable' USING ERRCODE='23514'; END IF;
 IF NEW.status=OLD.status AND (NEW.published_at,NEW.previous_release_id) IS DISTINCT FROM (OLD.published_at,OLD.previous_release_id) THEN RAISE EXCEPTION 'same-status release history is immutable' USING ERRCODE='23514'; END IF;
 IF (NEW.status,NEW.published_at,NEW.previous_release_id) IS DISTINCT FROM (OLD.status,OLD.published_at,OLD.previous_release_id) AND current_user<>'dsa_seats_migration_owner' THEN RAISE EXCEPTION 'lifecycle mutations require a lifecycle routine' USING ERRCODE='42501'; END IF; RETURN NEW; END $$;
CREATE TRIGGER data_releases_lifecycle_guard BEFORE UPDATE ON public.data_releases FOR EACH ROW EXECUTE FUNCTION public.guard_release_lifecycle();
ALTER FUNCTION public.guard_fec_amendment() SET search_path = pg_catalog, public, pg_temp;
ALTER FUNCTION public.guard_release_manifest() SET search_path = pg_catalog, public, pg_temp;
ALTER FUNCTION public.guard_candidate_release_content() SET search_path = pg_catalog, public, pg_temp;
ALTER FUNCTION public.guard_provenance_parent() SET search_path = pg_catalog, public, pg_temp;
ALTER FUNCTION public.guard_seat_finance_summary_lineage_parent() SET search_path = pg_catalog, public, pg_temp;
ALTER FUNCTION public.guard_seat_finance_summary_parent() SET search_path = pg_catalog, public, pg_temp;
ALTER FUNCTION public.guard_nationwide_content() SET search_path = pg_catalog, public, pg_temp;
ALTER FUNCTION public.guard_nationwide_validation() SET search_path = pg_catalog, public, pg_temp;
ALTER FUNCTION public.guard_ingest_run() SET search_path = pg_catalog, public, pg_temp;
ALTER FUNCTION public.guard_nationwide_operational() SET search_path = pg_catalog, public, pg_temp;
ALTER FUNCTION public.guard_fec_amendment() SECURITY DEFINER; ALTER FUNCTION public.guard_release_manifest() SECURITY DEFINER; ALTER FUNCTION public.guard_candidate_release_content() SECURITY DEFINER; ALTER FUNCTION public.guard_provenance_parent() SECURITY DEFINER; ALTER FUNCTION public.guard_seat_finance_summary_lineage_parent() SECURITY DEFINER; ALTER FUNCTION public.guard_seat_finance_summary_parent() SECURITY DEFINER; ALTER FUNCTION public.guard_nationwide_content() SECURITY DEFINER; ALTER FUNCTION public.guard_nationwide_validation() SECURITY DEFINER; ALTER FUNCTION public.guard_ingest_run() SECURITY DEFINER; ALTER FUNCTION public.guard_nationwide_operational() SECURITY DEFINER;
CREATE OR REPLACE FUNCTION public.guard_ingest_publication() RETURNS trigger LANGUAGE plpgsql SET search_path = pg_catalog, public, pg_temp AS $$ BEGIN
 IF OLD.status='candidate' AND NEW.status='published' AND EXISTS(SELECT 1 FROM public.ingest_runs WHERE release_id=NEW.id AND status='running') THEN RAISE EXCEPTION 'cannot publish a release with running ingestion' USING ERRCODE='23514'; END IF;
 RETURN NEW;
END $$;
REVOKE ALL ON FUNCTION public.guard_fec_amendment(),public.guard_release_manifest(),public.guard_candidate_release_content(),public.guard_provenance_parent(),public.guard_seat_finance_summary_lineage_parent(),public.guard_seat_finance_summary_parent(),public.guard_nationwide_content(),public.guard_nationwide_validation(),public.guard_ingest_run(),public.guard_nationwide_operational() FROM PUBLIC;

CREATE TABLE public.release_preflight_proofs (
 id text PRIMARY KEY NOT NULL, operation text NOT NULL, target_release_id text NOT NULL, current_release_id text, predecessor_release_id text,
 run_ids_fingerprint text NOT NULL, map_receipts_fingerprint text NOT NULL, manifest_fingerprint text NOT NULL, gate_fingerprint text NOT NULL, digest_fingerprint text NOT NULL,
 issued_by text NOT NULL, issued_at timestamptz NOT NULL DEFAULT clock_timestamp(), expires_at timestamptz NOT NULL, consumed_at timestamptz,
 CONSTRAINT release_preflight_proofs_id_ck CHECK(id ~ '^[a-f0-9-]{36}$'), CONSTRAINT release_preflight_proofs_operation_ck CHECK(operation IN('promote','roll_forward')),
 CONSTRAINT release_preflight_proofs_run_sha_ck CHECK(run_ids_fingerprint ~ '^[a-f0-9]{64}$'), CONSTRAINT release_preflight_proofs_map_sha_ck CHECK(map_receipts_fingerprint ~ '^[a-f0-9]{64}$'), CONSTRAINT release_preflight_proofs_manifest_sha_ck CHECK(manifest_fingerprint ~ '^[a-f0-9]{64}$'), CONSTRAINT release_preflight_proofs_gate_sha_ck CHECK(gate_fingerprint ~ '^[a-f0-9]{64}$'), CONSTRAINT release_preflight_proofs_digest_sha_ck CHECK(digest_fingerprint ~ '^[a-f0-9]{64}$'), CONSTRAINT release_preflight_proofs_expiry_ck CHECK(expires_at>issued_at AND expires_at<=issued_at+interval '5 minutes')
);
ALTER TABLE public.release_preflight_proofs ADD CONSTRAINT release_preflight_proofs_target_release_id_data_releases_id_fk FOREIGN KEY(target_release_id) REFERENCES public.data_releases(id);
ALTER TABLE public.release_preflight_proofs ADD CONSTRAINT release_preflight_proofs_current_release_id_data_releases_id_fk FOREIGN KEY(current_release_id) REFERENCES public.data_releases(id);
ALTER TABLE public.release_preflight_proofs ADD CONSTRAINT release_preflight_proofs_predecessor_release_id_data_releases_id_fk FOREIGN KEY(predecessor_release_id) REFERENCES public.data_releases(id);
CREATE EXTENSION IF NOT EXISTS pgcrypto;
DO $$ DECLARE t record; BEGIN FOR t IN SELECT tablename FROM pg_catalog.pg_tables WHERE schemaname='public' AND tablename<>'spatial_ref_sys' LOOP EXECUTE format('ALTER TABLE public.%I OWNER TO dsa_seats_migration_owner',t.tablename); END LOOP; END $$;

CREATE OR REPLACE FUNCTION public.assert_task9_publication_ready(p_release_id text) RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path = pg_catalog, public, pg_temp AS $$ BEGIN
 IF (SELECT count(*) FROM public.election_decisions WHERE release_id=p_release_id)<>158 OR EXISTS(SELECT 1 FROM public.election_decisions ed WHERE ed.release_id=p_release_id AND (ed.status='unassessed' OR (SELECT count(*) FROM public.election_decision_inputs i WHERE i.release_id=ed.release_id AND i.election_decision_id=ed.id)<>1)) OR EXISTS(SELECT 1 FROM public.election_decision_inputs i LEFT JOIN public.ingest_runs ir ON ir.release_id=i.release_id AND ir.snapshot_id=i.snapshot_id AND ir.status='loaded' WHERE i.release_id=p_release_id AND ir.id IS NULL) THEN RAISE EXCEPTION 'release lacks exact Task 9 publication closure'; END IF; END $$;
CREATE OR REPLACE FUNCTION public.assert_lifecycle_ready(p_target text,p_predecessor text) RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path = pg_catalog, public, pg_temp AS $$
DECLARE maps integer; BEGIN
 IF NOT EXISTS(SELECT 1 FROM public.release_manifests m WHERE m.release_id=p_target AND (m.schema_version=1 OR (m.schema_version=2 AND m.validated_at IS NOT NULL AND EXISTS(SELECT 1 FROM public.nationwide_validation_gates g WHERE g.release_id=m.release_id AND g.schema_version=2 AND (g.manifest_checksum_sha256,g.geometry_checksum_sha256,g.content_checksum_sha256)=(m.canonical_data_checksum_sha256,m.geometry_checksum_sha256,m.content_checksum_sha256) AND g.domain_count=7) AND (SELECT count(*) FROM public.release_content_digests d WHERE d.release_id=m.release_id AND d.validated_at IS NOT NULL)=7))) THEN RAISE EXCEPTION 'target lacks required v2 manifest, gate, or all-seven stored digests'; END IF;
 IF EXISTS(SELECT 1 FROM public.ingest_runs WHERE release_id=p_target AND status='running') THEN RAISE EXCEPTION 'target has running ingestion'; END IF; SELECT count(*) INTO maps FROM public.map_artifacts WHERE release_id=p_target;
 IF maps>0 THEN IF p_predecessor IS NULL THEN RAISE EXCEPTION 'map-bearing target requires a predecessor'; END IF; PERFORM public.assert_task9_publication_ready(p_predecessor);
 IF maps<>441 OR EXISTS(WITH active AS (SELECT DISTINCT sc.geography_version_id FROM public.release_profile_seats rp JOIN public.seat_cycles sc ON sc.release_id=rp.release_id AND sc.id=rp.seat_cycle_id JOIN public.offices o ON o.release_id=sc.release_id AND o.id=sc.office_id JOIN public.office_terms ot ON ot.release_id=sc.release_id AND ot.id=sc.office_term_id JOIN public.geography_versions gv ON gv.release_id=sc.release_id AND gv.id=sc.geography_version_id JOIN public.district_plans dp ON dp.release_id=gv.release_id AND dp.id=gv.district_plan_id JOIN public.data_releases r ON r.id=rp.release_id WHERE rp.release_id=p_target AND o.chamber='house' AND sc.occupancy_as_of <= (r.source_cutoff AT TIME ZONE 'UTC')::date AND ot.starts_at <= (r.source_cutoff AT TIME ZONE 'UTC')::date AND ot.ends_at > (r.source_cutoff AT TIME ZONE 'UTC')::date AND dp.effective_from <= (r.source_cutoff AT TIME ZONE 'UTC')::date AND (dp.effective_to IS NULL OR dp.effective_to > (r.source_cutoff AT TIME ZONE 'UTC')::date)) SELECT 1 WHERE (SELECT count(*) FROM active)<>441 OR EXISTS((SELECT geography_version_id FROM active EXCEPT SELECT geography_version_id FROM public.map_artifacts WHERE release_id=p_target) UNION ALL (SELECT geography_version_id FROM public.map_artifacts WHERE release_id=p_target EXCEPT SELECT geography_version_id FROM active))) THEN RAISE EXCEPTION 'maps must exactly cover 441 cutoff-active House geographies'; END IF;
 IF EXISTS(SELECT 1 FROM public.map_artifacts ma JOIN public.geography_versions gv ON gv.release_id=ma.release_id AND gv.id=ma.geography_version_id JOIN public.geometry_artifacts original_ga ON original_ga.release_id=gv.release_id AND original_ga.id=gv.geometry_artifact_id LEFT JOIN public.geometry_artifacts ga ON ga.release_id=ma.release_id AND ga.id=ma.artifact_id AND ga.format='geojson' AND ga.srid=4326 AND ga.object_key='maps/'||ma.release_id||'/'||ma.geography_version_id||'.geojson' LEFT JOIN public.source_snapshots s ON s.release_id=ga.release_id AND s.id=ga.snapshot_id AND s.usage_status='approved' AND s.license='public-domain' AND s.checksum_sha256=ga.checksum_sha256 AND s.parser_version='tiger-mapshaper-0.6.113-dp25m' LEFT JOIN public.sources src ON src.release_id=s.release_id AND src.id=s.source_id AND src.authority='derived' LEFT JOIN public.map_artifact_receipts r ON r.release_id=ma.release_id AND r.map_artifact_id=ma.id AND r.sha256=ga.checksum_sha256 AND r.object_key=ga.object_key LEFT JOIN public.map_artifact_inputs mi ON mi.release_id=ma.release_id AND mi.map_artifact_id=ma.id AND mi.snapshot_id=s.id LEFT JOIN public.snapshot_derivations sd ON sd.release_id=s.release_id AND sd.output_snapshot_id=s.id AND sd.methodology_version='tiger-mapshaper-0.6.113-dp25m' WHERE ma.release_id=p_target AND (ga.id IS NULL OR s.id IS NULL OR src.id IS NULL OR r.map_artifact_id IS NULL OR mi.map_artifact_id IS NULL OR sd.output_snapshot_id IS NULL OR (SELECT count(*) FROM public.snapshot_derivation_inputs di WHERE di.release_id=s.release_id AND di.output_snapshot_id=s.id)<>1 OR NOT EXISTS(SELECT 1 FROM public.snapshot_derivation_inputs di WHERE di.release_id=s.release_id AND di.output_snapshot_id=s.id AND di.input_snapshot_id=original_ga.snapshot_id))) OR (SELECT count(*) FROM public.coverage_records c WHERE c.release_id=p_target AND c.domain='maps' AND c.scope_kind='release' AND c.status='complete' AND c.expected_count=441 AND c.observed_count=441 AND c.quarantined_count=0 AND c.incompatible_count=0)<>1 OR EXISTS(SELECT 1 FROM public.coverage_missing_reasons m WHERE m.release_id=p_target AND m.domain='maps') OR NOT EXISTS(SELECT 1 FROM public.release_content_digests t JOIN public.release_content_digests p ON p.release_id=p_predecessor AND p.domain='elections' WHERE t.release_id=p_target AND t.domain='elections' AND (t.row_count,t.sha256)=(p.row_count,p.sha256)) THEN RAISE EXCEPTION 'map artifact closure is incomplete'; END IF;
 ELSIF EXISTS(SELECT 1 FROM public.election_decisions WHERE release_id=p_target AND status<>'unassessed') THEN PERFORM public.assert_task9_publication_ready(p_target); END IF; END $$;
CREATE OR REPLACE FUNCTION public.assert_lifecycle_run_ids(p_target text,p_predecessor text,p_run_ids text[]) RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path = pg_catalog, public, pg_temp AS $$ DECLARE proof_release text; has_maps boolean; reviewed boolean; BEGIN
 SELECT EXISTS(SELECT 1 FROM public.map_artifacts WHERE release_id=p_target),EXISTS(SELECT 1 FROM public.election_decisions WHERE release_id=p_target AND status<>'unassessed') INTO has_maps,reviewed; IF NOT has_maps AND NOT reviewed THEN IF p_run_ids IS NOT NULL AND cardinality(p_run_ids)<>0 THEN RAISE EXCEPTION 'all-unassessed mapless transition requires no election run IDs'; END IF; RETURN; END IF;
 proof_release:=CASE WHEN has_maps THEN p_predecessor ELSE p_target END; IF proof_release IS NULL OR p_run_ids IS NULL OR cardinality(p_run_ids)<>158 OR (SELECT count(DISTINCT x) FROM unnest(p_run_ids) x)<>158 OR EXISTS(SELECT 1 FROM unnest(p_run_ids) x LEFT JOIN public.ingest_runs r ON r.id=x AND r.release_id=proof_release AND r.status='loaded' WHERE r.id IS NULL) OR EXISTS((SELECT i.snapshot_id FROM public.election_decisions d JOIN public.election_decision_inputs i ON i.release_id=d.release_id AND i.election_decision_id=d.id WHERE d.release_id=proof_release EXCEPT SELECT r.snapshot_id FROM public.ingest_runs r WHERE r.release_id=proof_release AND r.status='loaded' AND r.id=ANY(p_run_ids)) UNION ALL (SELECT r.snapshot_id FROM public.ingest_runs r WHERE r.release_id=proof_release AND r.status='loaded' AND r.id=ANY(p_run_ids) EXCEPT SELECT i.snapshot_id FROM public.election_decisions d JOIN public.election_decision_inputs i ON i.release_id=d.release_id AND i.election_decision_id=d.id WHERE d.release_id=proof_release)) THEN RAISE EXCEPTION 'transition requires exactly the reviewed-decision run set'; END IF; END $$;
CREATE OR REPLACE FUNCTION public.release_preflight_fingerprint(p_target text,p_runs text[]) RETURNS TABLE(run_ids_fingerprint text,map_receipts_fingerprint text,manifest_fingerprint text,gate_fingerprint text,digest_fingerprint text) LANGUAGE sql SECURITY DEFINER SET search_path = pg_catalog, public, pg_temp AS $$ SELECT encode(digest(coalesce((SELECT string_agg(x,',' ORDER BY x) FROM unnest(coalesce(p_runs,'{}'::text[])) x),''),'sha256'),'hex'),encode(digest(coalesce((SELECT string_agg(map_artifact_id||':'||raw_store_kind::text||':'||store_identity||':'||object_key||':'||sha256||':'||byte_size::text||':'||coalesce(version_id,'<null>')||':'||coalesce(etag,'<null>'),',' ORDER BY map_artifact_id) FROM public.map_artifact_receipts WHERE release_id=p_target),''),'sha256'),'hex'),encode(digest(coalesce((SELECT schema_version::text||':'||canonical_data_checksum_sha256||':'||geometry_checksum_sha256||':'||content_checksum_sha256 FROM public.release_manifests WHERE release_id=p_target),''),'sha256'),'hex'),encode(digest(coalesce((SELECT schema_version::text||':'||manifest_checksum_sha256||':'||geometry_checksum_sha256||':'||content_checksum_sha256||':'||domain_checksum_sha256 FROM public.nationwide_validation_gates WHERE release_id=p_target),''),'sha256'),'hex'),encode(digest(coalesce((SELECT string_agg(domain||':'||row_count::text||':'||sha256,',' ORDER BY domain) FROM public.release_content_digests WHERE release_id=p_target),''),'sha256'),'hex') $$;
CREATE OR REPLACE FUNCTION public.assert_preflight_branch(p_operation text,p_target text,p_current text,p_predecessor text) RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path = pg_catalog, public, pg_temp AS $$ DECLARE target_previous text; target_maps integer; BEGIN
 IF p_current IS DISTINCT FROM p_predecessor THEN RAISE EXCEPTION 'wrong promotion branch'; END IF;
 SELECT previous_release_id INTO target_previous FROM public.data_releases WHERE id=p_target AND status=(CASE WHEN p_operation='promote' THEN 'candidate' ELSE 'retired' END)::public.release_status FOR UPDATE; IF NOT FOUND THEN RAISE EXCEPTION 'wrong promotion branch'; END IF;
 IF p_operation='roll_forward' THEN IF NOT EXISTS(SELECT 1 FROM public.data_releases WHERE id=p_current AND status='published' FOR UPDATE) OR target_previous IS DISTINCT FROM p_current THEN RAISE EXCEPTION 'retired target is not direct successor'; END IF; RETURN; END IF;
 SELECT count(*) INTO target_maps FROM public.map_artifacts WHERE release_id=p_target;
 IF p_current IS NULL THEN IF target_previous IS NOT NULL OR EXISTS(SELECT 1 FROM public.data_releases WHERE status='published' FOR UPDATE) OR target_maps<>0 THEN RAISE EXCEPTION 'wrong initial promotion branch'; END IF;
 ELSIF NOT EXISTS(SELECT 1 FROM public.data_releases WHERE id=p_current AND status='published' FOR UPDATE) OR target_previous IS DISTINCT FROM p_current THEN RAISE EXCEPTION 'wrong promotion branch'; END IF;
END $$;
CREATE OR REPLACE FUNCTION public.guard_live_preflight_content() RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path = pg_catalog, public, pg_temp AS $$ DECLARE r text:=COALESCE(NEW.release_id,OLD.release_id); BEGIN PERFORM pg_advisory_xact_lock(hashtext('dsa_seats_release:'||r)); IF EXISTS(SELECT 1 FROM public.release_preflight_proofs WHERE target_release_id=r AND consumed_at IS NULL AND expires_at>=clock_timestamp()) THEN RAISE EXCEPTION 'candidate content is frozen while a live preflight proof exists' USING ERRCODE='55000'; END IF; RETURN COALESCE(NEW,OLD); END $$;
DO $$ DECLARE t record; BEGIN FOR t IN SELECT c.table_name FROM information_schema.columns c JOIN information_schema.tables x USING(table_schema,table_name) WHERE c.table_schema='public' AND c.column_name='release_id' AND x.table_type='BASE TABLE' AND c.table_name NOT IN('release_preflight_proofs','data_releases') LOOP EXECUTE format('CREATE TRIGGER preflight_content_freeze BEFORE INSERT OR UPDATE OR DELETE ON public.%I FOR EACH ROW EXECUTE FUNCTION public.guard_live_preflight_content()',t.table_name); END LOOP; END $$;
CREATE OR REPLACE FUNCTION public.issue_release_preflight(p_id text,p_operation text,p_target text,p_current text,p_predecessor text,p_run_ids text[],p_ttl_seconds integer DEFAULT 300) RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path = pg_catalog, public, pg_temp AS $$ DECLARE f record; issued timestamptz:=clock_timestamp(); BEGIN IF NOT pg_has_role(session_user,'dsa_seats_release_preflight','member') AND current_setting('is_superuser')<>'on' THEN RAISE EXCEPTION 'only preflight role may issue proofs' USING ERRCODE='42501'; END IF; IF p_id !~ '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$' OR p_operation NOT IN('promote','roll_forward') OR p_ttl_seconds NOT BETWEEN 1 AND 300 THEN RAISE EXCEPTION 'invalid preflight capability' USING ERRCODE='22023'; END IF; PERFORM pg_advisory_xact_lock(hashtext('dsa_seats_release_promotion')); PERFORM public.assert_preflight_branch(p_operation,p_target,p_current,p_predecessor); IF EXISTS(SELECT 1 FROM public.release_preflight_proofs WHERE consumed_at IS NULL AND expires_at>=issued AND (operation,target_release_id,current_release_id,predecessor_release_id) IS NOT DISTINCT FROM(p_operation,p_target,p_current,p_predecessor)) THEN RAISE EXCEPTION 'a live preflight proof already exists for this lifecycle state' USING ERRCODE='23505'; END IF; PERFORM public.assert_lifecycle_ready(p_target,p_predecessor); PERFORM public.assert_lifecycle_run_ids(p_target,p_predecessor,p_run_ids); SELECT * INTO f FROM public.release_preflight_fingerprint(p_target,p_run_ids); INSERT INTO public.release_preflight_proofs VALUES(p_id,p_operation,p_target,p_current,p_predecessor,f.run_ids_fingerprint,f.map_receipts_fingerprint,f.manifest_fingerprint,f.gate_fingerprint,f.digest_fingerprint,session_user,issued,issued+make_interval(secs=>p_ttl_seconds),NULL); END $$;
CREATE OR REPLACE FUNCTION public.consume_release_preflight(p_id text,p_operation text,p_target text,p_current text,p_predecessor text,p_run_ids text[]) RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path = pg_catalog, public, pg_temp AS $$ DECLARE p public.release_preflight_proofs%ROWTYPE; f record; BEGIN IF NOT pg_has_role(session_user,'dsa_seats_release_operator','member') AND current_setting('is_superuser')<>'on' THEN RAISE EXCEPTION 'only release operator may consume proofs' USING ERRCODE='42501'; END IF; SELECT * INTO p FROM public.release_preflight_proofs WHERE id=p_id FOR UPDATE; IF NOT FOUND OR p.consumed_at IS NOT NULL OR p.expires_at<clock_timestamp() OR (p.operation,p.target_release_id,p.current_release_id,p.predecessor_release_id) IS DISTINCT FROM(p_operation,p_target,p_current,p_predecessor) THEN RAISE EXCEPTION 'invalid, expired, or consumed preflight proof' USING ERRCODE='42501'; END IF; PERFORM public.assert_lifecycle_ready(p_target,p_predecessor); PERFORM public.assert_lifecycle_run_ids(p_target,p_predecessor,p_run_ids); SELECT * INTO f FROM public.release_preflight_fingerprint(p_target,p_run_ids); IF (p.run_ids_fingerprint,p.map_receipts_fingerprint,p.manifest_fingerprint,p.gate_fingerprint,p.digest_fingerprint) IS DISTINCT FROM(f.run_ids_fingerprint,f.map_receipts_fingerprint,f.manifest_fingerprint,f.gate_fingerprint,f.digest_fingerprint) THEN RAISE EXCEPTION 'preflight proof no longer matches release content' USING ERRCODE='23514'; END IF; UPDATE public.release_preflight_proofs SET consumed_at=clock_timestamp() WHERE id=p_id; END $$;
CREATE OR REPLACE FUNCTION public.lifecycle_promote_candidate(p_proof_id text,p_target text,p_expected_current text,p_expected_predecessor text,p_run_ids text[]) RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path = pg_catalog, public, pg_temp AS $$ BEGIN PERFORM pg_advisory_xact_lock(hashtext('dsa_seats_release_promotion')); PERFORM public.assert_preflight_branch('promote',p_target,p_expected_current,p_expected_predecessor); PERFORM public.consume_release_preflight(p_proof_id,'promote',p_target,p_expected_current,p_expected_predecessor,p_run_ids); IF p_expected_current IS NOT NULL THEN UPDATE public.data_releases SET status='retired' WHERE id=p_expected_current; END IF; UPDATE public.data_releases SET status='published',published_at=clock_timestamp() WHERE id=p_target; UPDATE public.release_preflight_proofs SET consumed_at=clock_timestamp() WHERE consumed_at IS NULL; END $$;
CREATE OR REPLACE FUNCTION public.lifecycle_roll_forward(p_proof_id text,p_target text,p_expected_current text,p_expected_predecessor text,p_run_ids text[]) RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path = pg_catalog, public, pg_temp AS $$ BEGIN PERFORM pg_advisory_xact_lock(hashtext('dsa_seats_release_promotion')); PERFORM public.assert_preflight_branch('roll_forward',p_target,p_expected_current,p_expected_predecessor); PERFORM public.consume_release_preflight(p_proof_id,'roll_forward',p_target,p_expected_current,p_expected_predecessor,p_run_ids); UPDATE public.data_releases SET status='retired' WHERE id=p_expected_current; UPDATE public.data_releases SET status='published' WHERE id=p_target; UPDATE public.release_preflight_proofs SET consumed_at=clock_timestamp() WHERE consumed_at IS NULL; END $$;
CREATE OR REPLACE FUNCTION public.lifecycle_rollback(p_expected_current text,p_expected_predecessor text) RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path = pg_catalog, public, pg_temp AS $$ DECLARE prior text; BEGIN PERFORM pg_advisory_xact_lock(hashtext('dsa_seats_release_promotion')); IF NOT EXISTS(SELECT 1 FROM public.data_releases WHERE id=p_expected_current AND status='published' AND previous_release_id=p_expected_predecessor FOR UPDATE) OR NOT EXISTS(SELECT 1 FROM public.data_releases WHERE id=p_expected_predecessor AND status='retired' FOR UPDATE) THEN RAISE EXCEPTION 'rollback requires direct immutable predecessor'; END IF; SELECT previous_release_id INTO prior FROM public.data_releases WHERE id=p_expected_predecessor; PERFORM public.assert_lifecycle_ready(p_expected_predecessor,prior); UPDATE public.data_releases SET status='retired' WHERE id=p_expected_current; UPDATE public.data_releases SET status='published' WHERE id=p_expected_predecessor; UPDATE public.release_preflight_proofs SET consumed_at=clock_timestamp() WHERE consumed_at IS NULL; END $$;

ALTER FUNCTION public.guard_map_artifact_receipt() OWNER TO dsa_seats_migration_owner; ALTER FUNCTION public.guard_release_insert() OWNER TO dsa_seats_migration_owner; ALTER FUNCTION public.guard_release_lifecycle() OWNER TO dsa_seats_migration_owner;
ALTER FUNCTION public.guard_fec_amendment() OWNER TO dsa_seats_migration_owner; ALTER FUNCTION public.guard_release_manifest() OWNER TO dsa_seats_migration_owner; ALTER FUNCTION public.guard_candidate_release_content() OWNER TO dsa_seats_migration_owner; ALTER FUNCTION public.guard_provenance_parent() OWNER TO dsa_seats_migration_owner; ALTER FUNCTION public.guard_seat_finance_summary_lineage_parent() OWNER TO dsa_seats_migration_owner; ALTER FUNCTION public.guard_seat_finance_summary_parent() OWNER TO dsa_seats_migration_owner; ALTER FUNCTION public.guard_nationwide_content() OWNER TO dsa_seats_migration_owner; ALTER FUNCTION public.guard_nationwide_validation() OWNER TO dsa_seats_migration_owner; ALTER FUNCTION public.guard_ingest_run() OWNER TO dsa_seats_migration_owner; ALTER FUNCTION public.guard_nationwide_operational() OWNER TO dsa_seats_migration_owner;
ALTER FUNCTION public.assert_task9_publication_ready(text) OWNER TO dsa_seats_migration_owner; ALTER FUNCTION public.assert_lifecycle_ready(text,text) OWNER TO dsa_seats_migration_owner; ALTER FUNCTION public.assert_lifecycle_run_ids(text,text,text[]) OWNER TO dsa_seats_migration_owner; ALTER FUNCTION public.release_preflight_fingerprint(text,text[]) OWNER TO dsa_seats_migration_owner; ALTER FUNCTION public.issue_release_preflight(text,text,text,text,text,text[],integer) OWNER TO dsa_seats_migration_owner; ALTER FUNCTION public.consume_release_preflight(text,text,text,text,text,text[]) OWNER TO dsa_seats_migration_owner; ALTER FUNCTION public.lifecycle_promote_candidate(text,text,text,text,text[]) OWNER TO dsa_seats_migration_owner; ALTER FUNCTION public.lifecycle_roll_forward(text,text,text,text,text[]) OWNER TO dsa_seats_migration_owner; ALTER FUNCTION public.lifecycle_rollback(text,text) OWNER TO dsa_seats_migration_owner;
REVOKE ALL ON ALL TABLES IN SCHEMA public FROM dsa_seats_web,dsa_seats_ingest,dsa_seats_release_operator,dsa_seats_release_preflight; REVOKE ALL ON FUNCTION public.guard_map_artifact_receipt(),public.guard_release_insert(),public.guard_release_lifecycle(),public.assert_task9_publication_ready(text),public.assert_lifecycle_ready(text,text),public.assert_lifecycle_run_ids(text,text,text[]),public.release_preflight_fingerprint(text,text[]),public.issue_release_preflight(text,text,text,text,text,text[],integer),public.consume_release_preflight(text,text,text,text,text,text[]),public.lifecycle_promote_candidate(text,text,text,text,text[]),public.lifecycle_roll_forward(text,text,text,text,text[]),public.lifecycle_rollback(text,text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.issue_release_preflight(text,text,text,text,text,text[],integer) TO dsa_seats_release_preflight; GRANT EXECUTE ON FUNCTION public.lifecycle_promote_candidate(text,text,text,text,text[]),public.lifecycle_roll_forward(text,text,text,text,text[]),public.lifecycle_rollback(text,text) TO dsa_seats_release_operator;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO dsa_seats_ingest,dsa_seats_release_preflight; DO $$ DECLARE t record; BEGIN FOR t IN SELECT c.table_name FROM information_schema.columns c JOIN information_schema.tables x USING(table_schema,table_name) WHERE c.table_schema='public' AND c.column_name='release_id' AND x.table_type='BASE TABLE' AND c.table_name NOT IN('release_preflight_proofs','data_releases') LOOP EXECUTE format('GRANT INSERT,UPDATE,DELETE ON public.%I TO dsa_seats_ingest',t.table_name); END LOOP; END $$; GRANT INSERT(id,label,status,source_cutoff,created_at,previous_release_id) ON public.data_releases TO dsa_seats_ingest; REVOKE ALL ON public.release_preflight_proofs FROM dsa_seats_ingest,dsa_seats_web,dsa_seats_release_operator,dsa_seats_release_preflight;
CREATE OR REPLACE VIEW public.public_map_artifacts WITH(security_barrier=true) AS SELECT r.id release_id,gv.id geography_id,mar.raw_store_kind,mar.store_identity,mar.object_key,mar.sha256,mar.byte_size,mar.version_id,mar.etag FROM public.data_releases r JOIN public.map_artifacts ma ON ma.release_id=r.id JOIN public.geography_versions gv ON gv.release_id=ma.release_id AND gv.id=ma.geography_version_id JOIN public.map_artifact_receipts mar ON mar.release_id=ma.release_id AND mar.map_artifact_id=ma.id WHERE r.status='published' OR(r.status='retired' AND r.published_at IS NOT NULL);
ALTER VIEW public.public_map_artifacts OWNER TO dsa_seats_migration_owner; GRANT SELECT ON public.public_map_artifacts TO dsa_seats_web;
DO $$ DECLARE t record; BEGIN
 FOR t IN SELECT c.table_name FROM information_schema.columns c JOIN information_schema.tables x USING(table_schema,table_name) WHERE c.table_schema='public' AND c.column_name='release_id' AND x.table_type='BASE TABLE' AND c.table_name NOT IN('release_preflight_proofs','data_releases') LOOP
  EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY',t.table_name); EXECUTE format('CREATE POLICY ingest_catalog_read ON public.%I FOR SELECT TO dsa_seats_ingest USING(true)',t.table_name); EXECUTE format('CREATE POLICY preflight_catalog_read ON public.%I FOR SELECT TO dsa_seats_release_preflight USING(true)',t.table_name); EXECUTE format('CREATE POLICY ingest_candidate_only ON public.%I FOR ALL TO dsa_seats_ingest USING(EXISTS(SELECT 1 FROM public.data_releases r WHERE r.id=release_id AND r.status=''candidate'')) WITH CHECK(EXISTS(SELECT 1 FROM public.data_releases r WHERE r.id=release_id AND r.status=''candidate''))',t.table_name); EXECUTE format('CREATE POLICY web_published_history ON public.%I FOR SELECT TO dsa_seats_web USING(EXISTS(SELECT 1 FROM public.data_releases r WHERE r.id=release_id AND (r.status=''published'' OR(r.status=''retired'' AND r.published_at IS NOT NULL))))',t.table_name);
 END LOOP; END $$;
ALTER TABLE public.data_releases ENABLE ROW LEVEL SECURITY; CREATE POLICY ingest_candidate_insert ON public.data_releases FOR INSERT TO dsa_seats_ingest WITH CHECK(status='candidate'); CREATE POLICY ingest_catalog_read ON public.data_releases FOR SELECT TO dsa_seats_ingest USING(true); CREATE POLICY preflight_catalog_read ON public.data_releases FOR SELECT TO dsa_seats_release_preflight USING(true); CREATE POLICY web_published_history ON public.data_releases FOR SELECT TO dsa_seats_web USING(status='published' OR(status='retired' AND published_at IS NOT NULL));
GRANT SELECT ON public.data_releases,public.release_manifests,public.sources,public.source_snapshots,public.district_plans,public.geometry_artifacts,public.geography_versions,public.jurisdictions,public.offices,public.people,public.office_terms,public.memberships,public.seat_cycles,public.release_profile_seats,public.coverage_records,public.coverage_missing_reasons,public.coverage_input_snapshots,public.biographical_facts,public.biographical_fact_provenance,public.committees,public.committee_assignments,public.committee_assignment_provenance,public.contests,public.candidacies,public.result_options,public.election_results,public.contest_lineage,public.election_result_lineage,public.acs_observations,public.acs_observation_lineage,public.acs_variables,public.acs_variable_inputs,public.acs_variable_dependencies,public.committee_relationships,public.fec_filing_summaries,public.fec_filing_lineage,public.seat_finance_summaries,public.seat_finance_summary_lineage,public.finance_aggregates,public.finance_aggregate_inputs,public.funding_category_aggregates,public.funding_category_input_snapshots,public.funding_organization_aggregates,public.funding_organization_input_snapshots,public.outside_spending_aggregates,public.outside_spending_input_snapshots,public.election_decisions,public.election_decision_inputs,public.map_artifacts,public.map_artifact_inputs,public.snapshot_derivations,public.snapshot_derivation_inputs,public.provenance TO dsa_seats_web;
REVOKE CREATE ON SCHEMA public FROM dsa_seats_web,dsa_seats_ingest,dsa_seats_release_preflight,dsa_seats_release_operator; GRANT CREATE ON SCHEMA public TO dsa_seats_migration_owner;
ALTER FUNCTION public.guard_ingest_publication() OWNER TO dsa_seats_migration_owner; ALTER FUNCTION public.guard_live_preflight_content() OWNER TO dsa_seats_migration_owner; ALTER FUNCTION public.assert_preflight_branch(text,text,text,text) OWNER TO dsa_seats_migration_owner;
REVOKE ALL ON FUNCTION public.guard_ingest_publication(),public.guard_live_preflight_content(),public.assert_preflight_branch(text,text,text,text) FROM PUBLIC;
