CREATE SCHEMA operations;
--> statement-breakpoint
CREATE TABLE operations.correction_submissions (id uuid PRIMARY KEY NOT NULL, release_id text NOT NULL, seat_cycle_id text, field_path text NOT NULL, explanation text NOT NULL, source_url text, submitted_at timestamptz NOT NULL DEFAULT clock_timestamp(), CONSTRAINT correction_submissions_release_id_data_releases_id_fk FOREIGN KEY(release_id) REFERENCES public.data_releases(id), CONSTRAINT correction_submissions_field_path_ck CHECK (field_path IN ('identity.current_holder','identity.party','identity.occupancy','biography.bioguide_id','biography.birth_date','biography.other','elections','finance','demographics','district_boundary','sources','other')), CONSTRAINT correction_submissions_release_id_ck CHECK (release_id ~ '^rel_[A-Za-z0-9_-]{1,128}$'), CONSTRAINT correction_submissions_seat_cycle_id_ck CHECK (seat_cycle_id IS NULL OR seat_cycle_id ~ '^seat_[A-Za-z0-9_-]{1,128}$'), CONSTRAINT correction_submissions_explanation_ck CHECK (char_length(explanation) BETWEEN 20 AND 4000 AND octet_length(explanation)<=16384 AND explanation=btrim(explanation,E' \n\t') AND regexp_replace(explanation,E'[\n\t]','','g') !~ '[[:cntrl:]]'));
ALTER TABLE operations.correction_submissions ADD CONSTRAINT correction_submissions_release_id_seat_cycle_id_seat_cycles_release_id_id_fk FOREIGN KEY(release_id,seat_cycle_id) REFERENCES public.seat_cycles(release_id,id);
CREATE TABLE operations.correction_review_events (submission_id uuid NOT NULL, sequence integer NOT NULL, from_status text, to_status text NOT NULL, reason_code text NOT NULL, candidate_release_id text, approved_snapshot_id text, approved_snapshot_checksum text, actor text NOT NULL, occurred_at timestamptz NOT NULL DEFAULT clock_timestamp(), PRIMARY KEY(submission_id,sequence), CONSTRAINT correction_review_events_submission_id_correction_submissions_id_fk FOREIGN KEY(submission_id) REFERENCES operations.correction_submissions(id), CONSTRAINT correction_review_events_sequence_ck CHECK(sequence>=1), CONSTRAINT correction_review_events_status_ck CHECK(to_status IN ('submitted','in_review','accepted','queued','rejected','incorporated')), CONSTRAINT correction_review_events_reason_ck CHECK(reason_code IN ('submitted','triaged','not_actionable','approved','needs_candidate','candidate_ready','withdrawn','incorporated')), CONSTRAINT correction_review_events_snapshot_checksum_ck CHECK ((to_status='incorporated')=(approved_snapshot_checksum IS NOT NULL) AND (approved_snapshot_checksum IS NULL OR approved_snapshot_checksum ~ '^[a-f0-9]{64}$')));
ALTER TABLE operations.correction_review_events ADD CONSTRAINT correction_review_events_candidate_release_id_data_releases_id_fk FOREIGN KEY(candidate_release_id) REFERENCES public.data_releases(id);
ALTER TABLE operations.correction_review_events ADD CONSTRAINT correction_review_events_candidate_release_id_approved_snapshot_id_source_snapshots_release_id_id_fk FOREIGN KEY(candidate_release_id,approved_snapshot_id) REFERENCES public.source_snapshots(release_id,id);
CREATE TABLE operations.correction_idempotency_keys (key_hash bytea PRIMARY KEY NOT NULL, payload_fingerprint bytea NOT NULL, correction_id uuid, outcome text NOT NULL, created_at timestamptz NOT NULL DEFAULT clock_timestamp(), expires_at timestamptz NOT NULL, CONSTRAINT correction_idempotency_keys_correction_id_correction_submissions_id_fk FOREIGN KEY(correction_id) REFERENCES operations.correction_submissions(id), CONSTRAINT correction_idempotency_keys_hash_ck CHECK(octet_length(key_hash)=32 AND octet_length(payload_fingerprint)=32), CONSTRAINT correction_idempotency_keys_outcome_ck CHECK((outcome='accepted' AND correction_id IS NOT NULL) OR (outcome='target_unavailable' AND correction_id IS NULL)), CONSTRAINT correction_idempotency_keys_expiry_ck CHECK(expires_at>created_at AND expires_at<=created_at+interval '24 hours'));
CREATE TABLE operations.correction_rate_limit_buckets (bucket_kind text NOT NULL, subject_hash bytea NOT NULL, window_started_at timestamptz NOT NULL, count integer NOT NULL, expires_at timestamptz NOT NULL, PRIMARY KEY(bucket_kind,subject_hash,window_started_at), CONSTRAINT correction_rate_limit_buckets_kind_ck CHECK(bucket_kind IN('attempt_minute','subject_hour','global_minute','global_day')), CONSTRAINT correction_rate_limit_buckets_hash_ck CHECK(octet_length(subject_hash)=32), CONSTRAINT correction_rate_limit_buckets_count_ck CHECK(count BETWEEN 1 AND CASE WHEN bucket_kind='attempt_minute' THEN 20 WHEN bucket_kind='subject_hour' THEN 5 WHEN bucket_kind='global_minute' THEN 100 ELSE 5000 END), CONSTRAINT correction_rate_limit_buckets_expiry_ck CHECK(expires_at>window_started_at AND expires_at<=window_started_at+interval '48 hours'));
CREATE UNIQUE INDEX correction_idempotency_keys_correction_uq ON operations.correction_idempotency_keys(correction_id) WHERE correction_id IS NOT NULL;
CREATE INDEX correction_controls_expiry_idx ON operations.correction_idempotency_keys(expires_at);
CREATE INDEX correction_rate_controls_expiry_idx ON operations.correction_rate_limit_buckets(expires_at);
CREATE INDEX correction_reviewer_queue_idx ON operations.correction_review_events(to_status,occurred_at,submission_id) WHERE to_status IN ('submitted','in_review','accepted','queued');
CREATE INDEX correction_submissions_release_seat_idx ON operations.correction_submissions(release_id,seat_cycle_id,id);
CREATE INDEX correction_submissions_submitted_at_id_idx ON operations.correction_submissions(submitted_at,id);
--> statement-breakpoint
CREATE OR REPLACE FUNCTION operations.canonical_correction_source_url(p_url text) RETURNS text LANGUAGE plpgsql IMMUTABLE STRICT SET search_path=pg_catalog,operations,pg_temp AS $$
DECLARE host text; route text; path text; query text; canonical text; previous text;
BEGIN
 IF octet_length(p_url) NOT BETWEEN 1 AND 8192 OR char_length(p_url)>2000 OR p_url<>btrim(p_url) OR p_url !~ '^[\x21-\x7e]+$' OR p_url ~ '[@#[:space:]]' OR p_url !~ '^https://[A-Za-z0-9.-]+([/?][A-Za-z0-9._~!$&''()*+,;=:/?%\-]*)?$' THEN RETURN NULL; END IF;
 host:=substring(p_url FROM '^https://([^/?]+)'); route:=substring(p_url FROM '^https://[^/?]+(.*)$');
 IF host IS NULL OR host !~ '^([A-Za-z0-9](?:[A-Za-z0-9-]{0,61}[A-Za-z0-9])?\.)+[A-Za-z]{2,63}$' OR lower(split_part(host,'.',array_length(string_to_array(host,'.'),1))) IN ('localhost','local','internal','test','invalid') OR host ~ '^([0-9]{1,3}\.){3}[0-9]{1,3}$' OR regexp_replace(p_url,'%[0-9A-F]{2}','','g') ~ '%' OR p_url ~ '/(\.|%2E){1,2}(/|\?|$)' THEN RETURN NULL; END IF;
 route:=CASE WHEN route LIKE '?' || '%' THEN '/' || route ELSE coalesce(nullif(route,''),'/') END; path:=split_part(route,'?',1); query:=CASE WHEN position('?' IN route)>0 THEN substring(route FROM position('?' IN route)) ELSE '' END;
 LOOP previous:=path; path:=regexp_replace(path,'/\./','/','g'); path:=regexp_replace(path,'/[^/]+/\.\./','/','g'); path:=regexp_replace(path,'^/\.\./','/','g'); EXIT WHEN path=previous; END LOOP;
 IF path='/.' THEN path:='/'; ELSIF path LIKE '%/.' THEN path:=left(path,char_length(path)-1); END IF;
 canonical:='https://' || lower(host) || replace(path || query,'''','%27');
 IF octet_length(canonical)>8192 OR char_length(canonical)>2000 THEN RETURN NULL; END IF;
 RETURN canonical;
END $$;
ALTER TABLE operations.correction_submissions ADD CONSTRAINT correction_submissions_source_url_ck CHECK(source_url IS NULL OR operations.canonical_correction_source_url(source_url)=source_url);
DO $$ BEGIN IF NOT EXISTS(SELECT 1 FROM pg_roles WHERE rolname='dsa_seats_correction_intake') THEN CREATE ROLE dsa_seats_correction_intake NOLOGIN; END IF; IF NOT EXISTS(SELECT 1 FROM pg_roles WHERE rolname='dsa_seats_correction_reviewer') THEN CREATE ROLE dsa_seats_correction_reviewer NOLOGIN; END IF; IF NOT EXISTS(SELECT 1 FROM pg_roles WHERE rolname='dsa_seats_correction_maintenance') THEN CREATE ROLE dsa_seats_correction_maintenance NOLOGIN; END IF; END $$;
DO $$
DECLARE correction_roles text[]:=ARRAY['dsa_seats_correction_intake','dsa_seats_correction_reviewer','dsa_seats_correction_maintenance']; other_roles text[]:=ARRAY['dsa_seats_web','dsa_seats_ingest','dsa_seats_release_preflight','dsa_seats_release_operator','dsa_seats_migration_owner'];
BEGIN
 IF EXISTS(SELECT 1 FROM pg_roles WHERE rolname=ANY(correction_roles) AND (rolcanlogin OR rolsuper OR rolcreatedb OR rolcreaterole OR rolreplication OR rolbypassrls)) THEN RAISE EXCEPTION 'correction roles must be constrained NOLOGIN roles'; END IF;
 IF EXISTS(SELECT 1 FROM pg_auth_members m JOIN pg_roles member ON member.oid=m.member JOIN pg_roles granted ON granted.oid=m.roleid WHERE (member.rolname=ANY(correction_roles) AND granted.rolname=ANY(correction_roles||other_roles)) OR (member.rolname=ANY(other_roles) AND granted.rolname=ANY(correction_roles))) THEN RAISE EXCEPTION 'correction roles must not have cross-memberships'; END IF;
END $$;
CREATE OR REPLACE FUNCTION operations.forbid_correction_mutation() RETURNS trigger LANGUAGE plpgsql SET search_path=pg_catalog,operations,pg_temp AS $$ BEGIN RAISE EXCEPTION 'correction records are immutable' USING ERRCODE='55000'; END $$;
CREATE TRIGGER correction_submissions_immutable BEFORE UPDATE OR DELETE ON operations.correction_submissions FOR EACH ROW EXECUTE FUNCTION operations.forbid_correction_mutation();
CREATE TRIGGER correction_review_events_append_only BEFORE UPDATE OR DELETE ON operations.correction_review_events FOR EACH ROW EXECUTE FUNCTION operations.forbid_correction_mutation();
ALTER TABLE operations.correction_submissions ENABLE ROW LEVEL SECURITY;
ALTER TABLE operations.correction_review_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE operations.correction_idempotency_keys ENABLE ROW LEVEL SECURITY;
ALTER TABLE operations.correction_rate_limit_buckets ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
CREATE OR REPLACE FUNCTION operations.consume_correction_attempt_v1(p_subject_hash bytea) RETURNS TABLE(allowed boolean,retry_after integer) LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,operations,pg_temp AS $$
DECLARE now_at timestamptz:=clock_timestamp(); n integer;
BEGIN
 IF NOT pg_has_role(session_user,'dsa_seats_correction_intake','member') OR pg_has_role(session_user,'dsa_seats_correction_reviewer','member') OR pg_has_role(session_user,'dsa_seats_correction_maintenance','member') OR pg_has_role(session_user,'dsa_seats_web','member') OR pg_has_role(session_user,'dsa_seats_ingest','member') OR pg_has_role(session_user,'dsa_seats_release_preflight','member') OR pg_has_role(session_user,'dsa_seats_release_operator','member') OR pg_has_role(session_user,'dsa_seats_migration_owner','member') THEN RAISE EXCEPTION 'intake role exclusively required' USING ERRCODE='42501'; END IF;
 IF p_subject_hash IS NULL OR octet_length(p_subject_hash)<>32 THEN RAISE EXCEPTION 'subject hash must be 32 bytes' USING ERRCODE='22023'; END IF;
 INSERT INTO operations.correction_rate_limit_buckets VALUES('attempt_minute',p_subject_hash,date_trunc('minute',now_at),1,date_trunc('minute',now_at)+interval '2 minutes') ON CONFLICT(bucket_kind,subject_hash,window_started_at) DO UPDATE SET count=operations.correction_rate_limit_buckets.count+1 WHERE operations.correction_rate_limit_buckets.count<20 RETURNING count INTO n;
 IF FOUND THEN RETURN QUERY SELECT true,NULL::integer; ELSE RETURN QUERY SELECT false,ceil(extract(epoch FROM(date_trunc('minute',now_at)+interval '1 minute'-now_at)))::integer; END IF;
END $$;
CREATE OR REPLACE FUNCTION operations.submit_correction_v1(p_key_hash bytea,p_subject_hash bytea,p_release_id text,p_seat_cycle_id text,p_field_path text,p_explanation text,p_source_url text) RETURNS TABLE(outcome text,correction_id uuid,created boolean,retry_after integer) LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,operations,public,pg_temp AS $$
DECLARE now_at timestamptz:=clock_timestamp(); normalized_explanation text:=btrim(replace(p_explanation,E'\r\n',E'\n'),E' \n\t'); normalized_url text:=operations.canonical_correction_source_url(p_source_url); fp bytea; existing operations.correction_idempotency_keys%ROWTYPE; new_id uuid; n integer; retry integer;
BEGIN
 IF NOT pg_has_role(session_user,'dsa_seats_correction_intake','member') OR pg_has_role(session_user,'dsa_seats_correction_reviewer','member') OR pg_has_role(session_user,'dsa_seats_correction_maintenance','member') OR pg_has_role(session_user,'dsa_seats_web','member') OR pg_has_role(session_user,'dsa_seats_ingest','member') OR pg_has_role(session_user,'dsa_seats_release_preflight','member') OR pg_has_role(session_user,'dsa_seats_release_operator','member') OR pg_has_role(session_user,'dsa_seats_migration_owner','member') THEN RAISE EXCEPTION 'intake role exclusively required' USING ERRCODE='42501'; END IF;
 IF p_key_hash IS NULL OR p_subject_hash IS NULL OR p_release_id IS NULL OR p_field_path IS NULL OR p_explanation IS NULL OR octet_length(p_key_hash)<>32 OR octet_length(p_subject_hash)<>32 OR p_release_id !~ '^rel_[A-Za-z0-9_-]{1,128}$' OR (p_seat_cycle_id IS NOT NULL AND p_seat_cycle_id !~ '^seat_[A-Za-z0-9_-]{1,128}$') OR p_field_path NOT IN('identity.current_holder','identity.party','identity.occupancy','biography.bioguide_id','biography.birth_date','biography.other','elections','finance','demographics','district_boundary','sources','other') OR char_length(normalized_explanation) NOT BETWEEN 20 AND 4000 OR octet_length(normalized_explanation)>16384 OR regexp_replace(normalized_explanation,E'[\n\t]','','g') ~ '[[:cntrl:]]' OR (p_source_url IS NOT NULL AND normalized_url IS NULL) THEN RETURN QUERY SELECT 'invalid_request',NULL::uuid,false,NULL::integer; RETURN; END IF;
 fp:=digest(jsonb_build_object('release_id',p_release_id,'seat_cycle_id',p_seat_cycle_id,'field_path',p_field_path,'explanation',normalized_explanation,'source_url',normalized_url)::text,'sha256'); PERFORM pg_advisory_xact_lock(hashtextextended(encode(p_key_hash,'hex'),0)); DELETE FROM operations.correction_idempotency_keys WHERE key_hash=p_key_hash AND expires_at<=now_at; SELECT * INTO existing FROM operations.correction_idempotency_keys WHERE key_hash=p_key_hash;
 IF FOUND THEN IF existing.payload_fingerprint=fp THEN RETURN QUERY SELECT existing.outcome,existing.correction_id,false,NULL::integer; ELSE RETURN QUERY SELECT 'idempotency_conflict',NULL::uuid,false,NULL::integer; END IF; RETURN; END IF;
 INSERT INTO operations.correction_rate_limit_buckets VALUES('global_minute',digest('global','sha256'),date_trunc('minute',now_at),1,date_trunc('minute',now_at)+interval '2 minutes') ON CONFLICT(bucket_kind,subject_hash,window_started_at) DO UPDATE SET count=operations.correction_rate_limit_buckets.count+1 WHERE operations.correction_rate_limit_buckets.count<100 RETURNING count INTO n; IF NOT FOUND THEN retry:=ceil(extract(epoch FROM(date_trunc('minute',now_at)+interval '1 minute'-now_at)))::integer; RETURN QUERY SELECT 'rate_limited',NULL::uuid,false,retry; RETURN; END IF;
 INSERT INTO operations.correction_rate_limit_buckets VALUES('global_day',digest('global','sha256'),date_trunc('day',now_at),1,date_trunc('day',now_at)+interval '2 days') ON CONFLICT(bucket_kind,subject_hash,window_started_at) DO UPDATE SET count=operations.correction_rate_limit_buckets.count+1 WHERE operations.correction_rate_limit_buckets.count<5000 RETURNING count INTO n; IF NOT FOUND THEN retry:=ceil(extract(epoch FROM(date_trunc('day',now_at)+interval '1 day'-now_at)))::integer; RETURN QUERY SELECT 'rate_limited',NULL::uuid,false,retry; RETURN; END IF;
 INSERT INTO operations.correction_rate_limit_buckets VALUES('subject_hour',p_subject_hash,date_trunc('hour',now_at),1,date_trunc('hour',now_at)+interval '2 hours') ON CONFLICT(bucket_kind,subject_hash,window_started_at) DO UPDATE SET count=operations.correction_rate_limit_buckets.count+1 WHERE operations.correction_rate_limit_buckets.count<5 RETURNING count INTO n; IF NOT FOUND THEN DELETE FROM operations.correction_rate_limit_buckets WHERE bucket_kind='global_day' AND subject_hash=digest('global','sha256') AND window_started_at=date_trunc('day',now_at) AND count=1; UPDATE operations.correction_rate_limit_buckets SET count=count-1 WHERE bucket_kind='global_day' AND subject_hash=digest('global','sha256') AND window_started_at=date_trunc('day',now_at) AND count>1; DELETE FROM operations.correction_rate_limit_buckets WHERE bucket_kind='global_minute' AND subject_hash=digest('global','sha256') AND window_started_at=date_trunc('minute',now_at) AND count=1; UPDATE operations.correction_rate_limit_buckets SET count=count-1 WHERE bucket_kind='global_minute' AND subject_hash=digest('global','sha256') AND window_started_at=date_trunc('minute',now_at) AND count>1; retry:=ceil(extract(epoch FROM(date_trunc('hour',now_at)+interval '1 hour'-now_at)))::integer; RETURN QUERY SELECT 'rate_limited',NULL::uuid,false,retry; RETURN; END IF;
 IF NOT EXISTS(SELECT 1 FROM public.data_releases WHERE id=p_release_id AND(status='published' OR(status='retired' AND published_at IS NOT NULL))) OR(p_seat_cycle_id IS NOT NULL AND NOT EXISTS(SELECT 1 FROM public.seat_cycles WHERE release_id=p_release_id AND id=p_seat_cycle_id)) THEN INSERT INTO operations.correction_idempotency_keys(key_hash,payload_fingerprint,correction_id,outcome,created_at,expires_at) VALUES(p_key_hash,fp,NULL,'target_unavailable',now_at,now_at+interval '24 hours'); RETURN QUERY SELECT 'target_unavailable',NULL::uuid,false,NULL::integer; RETURN; END IF;
 new_id:=gen_random_uuid(); INSERT INTO operations.correction_submissions(id,release_id,seat_cycle_id,field_path,explanation,source_url,submitted_at) VALUES(new_id,p_release_id,p_seat_cycle_id,p_field_path,normalized_explanation,normalized_url,now_at); INSERT INTO operations.correction_review_events(submission_id,sequence,from_status,to_status,reason_code,actor,occurred_at) VALUES(new_id,1,NULL,'submitted','submitted',session_user,now_at); INSERT INTO operations.correction_idempotency_keys(key_hash,payload_fingerprint,correction_id,outcome,created_at,expires_at) VALUES(p_key_hash,fp,new_id,'accepted',now_at,now_at+interval '24 hours'); RETURN QUERY SELECT 'accepted',new_id,true,NULL::integer;
END $$;
CREATE OR REPLACE FUNCTION operations.transition_correction_v1(p_correction_id uuid,p_expected_sequence integer,p_expected_status text,p_to_status text,p_reason_code text,p_candidate_release_id text,p_approved_snapshot_id text) RETURNS TABLE(outcome text,sequence integer) LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,operations,public,pg_temp AS $$
DECLARE s operations.correction_submissions%ROWTYPE; latest operations.correction_review_events%ROWTYPE; checksum text; next_seq integer;
BEGIN
 IF NOT pg_has_role(session_user,'dsa_seats_correction_reviewer','member') OR pg_has_role(session_user,'dsa_seats_correction_intake','member') OR pg_has_role(session_user,'dsa_seats_correction_maintenance','member') OR pg_has_role(session_user,'dsa_seats_web','member') OR pg_has_role(session_user,'dsa_seats_ingest','member') OR pg_has_role(session_user,'dsa_seats_release_preflight','member') OR pg_has_role(session_user,'dsa_seats_release_operator','member') OR pg_has_role(session_user,'dsa_seats_migration_owner','member') THEN RAISE EXCEPTION 'reviewer role exclusively required' USING ERRCODE='42501'; END IF;
 PERFORM pg_advisory_xact_lock(hashtext('dsa_seats_release_promotion')); IF p_candidate_release_id IS NOT NULL THEN PERFORM pg_advisory_xact_lock(hashtext('dsa_seats_release:'||p_candidate_release_id)); END IF; PERFORM pg_advisory_xact_lock(hashtextextended(p_correction_id::text,0)); SELECT * INTO s FROM operations.correction_submissions WHERE id=p_correction_id; SELECT * INTO latest FROM operations.correction_review_events WHERE submission_id=p_correction_id ORDER BY sequence DESC LIMIT 1;
 IF NOT FOUND OR latest.sequence<>p_expected_sequence OR latest.to_status<>p_expected_status THEN RETURN QUERY SELECT 'conflict',NULL::integer; RETURN; END IF;
 IF NOT ((p_expected_status='submitted' AND p_to_status='in_review' AND p_reason_code='triaged') OR(p_expected_status='submitted' AND p_to_status='rejected' AND p_reason_code IN('not_actionable','withdrawn')) OR(p_expected_status='in_review' AND p_to_status='accepted' AND p_reason_code='approved') OR(p_expected_status='in_review' AND p_to_status='rejected' AND p_reason_code IN('not_actionable','withdrawn')) OR(p_expected_status='accepted' AND p_to_status='queued' AND p_reason_code='needs_candidate') OR(p_expected_status='accepted' AND p_to_status='rejected' AND p_reason_code IN('not_actionable','withdrawn')) OR(p_expected_status='queued' AND p_to_status='accepted' AND p_reason_code='candidate_ready') OR(p_expected_status='queued' AND p_to_status='incorporated' AND p_reason_code='incorporated')) THEN RETURN QUERY SELECT 'invalid_transition',NULL::integer; RETURN; END IF;
 IF p_to_status NOT IN('queued','incorporated') AND(p_candidate_release_id IS NOT NULL OR p_approved_snapshot_id IS NOT NULL) THEN RETURN QUERY SELECT 'invalid_transition',NULL::integer; RETURN; END IF;
 IF p_to_status='queued' AND(p_candidate_release_id IS NULL OR p_approved_snapshot_id IS NOT NULL OR NOT EXISTS(WITH RECURSIVE lineage(id,previous_release_id,path) AS(SELECT id,previous_release_id,ARRAY[id] FROM public.data_releases WHERE id=p_candidate_release_id AND status='candidate' UNION ALL SELECT r.id,r.previous_release_id,l.path||r.id FROM public.data_releases r JOIN lineage l ON r.id=l.previous_release_id WHERE NOT r.id=ANY(l.path)) SELECT 1 FROM lineage WHERE id=s.release_id)) THEN RETURN QUERY SELECT 'invalid_transition',NULL::integer; RETURN; END IF;
 IF p_to_status='incorporated' AND(p_candidate_release_id IS DISTINCT FROM latest.candidate_release_id OR p_candidate_release_id IS NULL OR p_approved_snapshot_id IS NULL) THEN RETURN QUERY SELECT 'invalid_transition',NULL::integer; RETURN; END IF;
 IF p_to_status='incorporated' THEN SELECT checksum_sha256 INTO checksum FROM public.source_snapshots WHERE release_id=p_candidate_release_id AND id=p_approved_snapshot_id AND usage_status='approved'; IF checksum IS NULL OR NOT EXISTS(WITH RECURSIVE lineage(id,previous_release_id,path) AS(SELECT id,previous_release_id,ARRAY[id] FROM public.data_releases WHERE id=p_candidate_release_id AND status='candidate' UNION ALL SELECT r.id,r.previous_release_id,l.path||r.id FROM public.data_releases r JOIN lineage l ON r.id=l.previous_release_id WHERE NOT r.id=ANY(l.path)) SELECT 1 FROM lineage WHERE id=s.release_id) THEN RETURN QUERY SELECT 'invalid_transition',NULL::integer; RETURN; END IF; END IF;
 next_seq:=latest.sequence+1; INSERT INTO operations.correction_review_events(submission_id,sequence,from_status,to_status,reason_code,candidate_release_id,approved_snapshot_id,approved_snapshot_checksum,actor) VALUES(p_correction_id,next_seq,p_expected_status,p_to_status,p_reason_code,p_candidate_release_id,p_approved_snapshot_id,checksum,session_user); RETURN QUERY SELECT 'transitioned',next_seq;
END $$;
CREATE OR REPLACE FUNCTION operations.list_corrections_v1(p_after_submitted_at timestamptz DEFAULT NULL,p_after_id uuid DEFAULT NULL,p_limit integer DEFAULT 50) RETURNS TABLE(id uuid,release_id text,seat_cycle_id text,field_path text,explanation text,source_url text,submitted_at timestamptz,status text,sequence integer) LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path=pg_catalog,operations,pg_temp AS $$ BEGIN IF NOT pg_has_role(session_user,'dsa_seats_correction_reviewer','member') OR pg_has_role(session_user,'dsa_seats_correction_intake','member') OR pg_has_role(session_user,'dsa_seats_correction_maintenance','member') OR pg_has_role(session_user,'dsa_seats_web','member') OR pg_has_role(session_user,'dsa_seats_ingest','member') OR pg_has_role(session_user,'dsa_seats_release_preflight','member') OR pg_has_role(session_user,'dsa_seats_release_operator','member') OR pg_has_role(session_user,'dsa_seats_migration_owner','member') THEN RAISE EXCEPTION 'reviewer role exclusively required' USING ERRCODE='42501'; END IF; IF (p_after_submitted_at IS NULL) <> (p_after_id IS NULL) THEN RAISE EXCEPTION 'cursor timestamp and id must both be null or present' USING ERRCODE='22023'; END IF; IF p_limit NOT BETWEEN 1 AND 100 THEN RAISE EXCEPTION 'limit must be 1..100' USING ERRCODE='22023'; END IF; RETURN QUERY SELECT s.id,s.release_id,s.seat_cycle_id,s.field_path,s.explanation,s.source_url,s.submitted_at,e.to_status,e.sequence FROM operations.correction_submissions s CROSS JOIN LATERAL(SELECT cre.to_status,cre.sequence FROM operations.correction_review_events cre WHERE cre.submission_id=s.id ORDER BY cre.sequence DESC LIMIT 1)e WHERE p_after_submitted_at IS NULL OR(s.submitted_at,s.id)>(p_after_submitted_at,p_after_id) ORDER BY s.submitted_at,s.id LIMIT p_limit; END $$;
CREATE OR REPLACE FUNCTION operations.cleanup_correction_controls_v1() RETURNS TABLE(idempotency_deleted integer,rate_buckets_deleted integer) LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,operations,pg_temp AS $$ BEGIN IF NOT pg_has_role(session_user,'dsa_seats_correction_maintenance','member') OR pg_has_role(session_user,'dsa_seats_correction_intake','member') OR pg_has_role(session_user,'dsa_seats_correction_reviewer','member') OR pg_has_role(session_user,'dsa_seats_web','member') OR pg_has_role(session_user,'dsa_seats_ingest','member') OR pg_has_role(session_user,'dsa_seats_release_preflight','member') OR pg_has_role(session_user,'dsa_seats_release_operator','member') OR pg_has_role(session_user,'dsa_seats_migration_owner','member') THEN RAISE EXCEPTION 'maintenance role exclusively required' USING ERRCODE='42501'; END IF; DELETE FROM operations.correction_idempotency_keys WHERE expires_at<=clock_timestamp(); GET DIAGNOSTICS idempotency_deleted=ROW_COUNT; DELETE FROM operations.correction_rate_limit_buckets WHERE expires_at<=clock_timestamp(); GET DIAGNOSTICS rate_buckets_deleted=ROW_COUNT; RETURN NEXT; END $$;
DO $$ DECLARE f text; BEGIN FOR f IN SELECT unnest(ARRAY['canonical_correction_source_url(text)','forbid_correction_mutation()','consume_correction_attempt_v1(bytea)','submit_correction_v1(bytea,bytea,text,text,text,text,text)','transition_correction_v1(uuid,integer,text,text,text,text,text)','list_corrections_v1(timestamp with time zone,uuid,integer)','cleanup_correction_controls_v1()']) LOOP EXECUTE 'ALTER FUNCTION operations.'||f||' OWNER TO dsa_seats_migration_owner'; END LOOP; ALTER SCHEMA operations OWNER TO dsa_seats_migration_owner; ALTER TABLE operations.correction_submissions OWNER TO dsa_seats_migration_owner; ALTER TABLE operations.correction_review_events OWNER TO dsa_seats_migration_owner; ALTER TABLE operations.correction_idempotency_keys OWNER TO dsa_seats_migration_owner; ALTER TABLE operations.correction_rate_limit_buckets OWNER TO dsa_seats_migration_owner; END $$;
REVOKE ALL ON SCHEMA operations FROM PUBLIC,dsa_seats_web,dsa_seats_ingest,dsa_seats_release_preflight,dsa_seats_release_operator; REVOKE ALL ON ALL TABLES IN SCHEMA operations FROM PUBLIC,dsa_seats_web,dsa_seats_ingest,dsa_seats_release_preflight,dsa_seats_release_operator,dsa_seats_correction_intake,dsa_seats_correction_reviewer,dsa_seats_correction_maintenance; REVOKE ALL ON ALL FUNCTIONS IN SCHEMA operations FROM PUBLIC; GRANT USAGE ON SCHEMA operations TO dsa_seats_correction_intake,dsa_seats_correction_reviewer,dsa_seats_correction_maintenance; GRANT EXECUTE ON FUNCTION operations.consume_correction_attempt_v1(bytea),operations.submit_correction_v1(bytea,bytea,text,text,text,text,text) TO dsa_seats_correction_intake; GRANT EXECUTE ON FUNCTION operations.transition_correction_v1(uuid,integer,text,text,text,text,text),operations.list_corrections_v1(timestamptz,uuid,integer) TO dsa_seats_correction_reviewer; GRANT EXECUTE ON FUNCTION operations.cleanup_correction_controls_v1() TO dsa_seats_correction_maintenance;
