CREATE TABLE operations.address_quota_buckets (bucket_kind text NOT NULL,subject_hash bytea NOT NULL,window_started_at timestamptz NOT NULL,count integer NOT NULL,expires_at timestamptz NOT NULL,PRIMARY KEY(bucket_kind,subject_hash,window_started_at),CONSTRAINT address_quota_buckets_kind_ck CHECK(bucket_kind IN('metadata_subject_minute','metadata_global_minute','lookup_subject_hour','upstream_minute','upstream_day','canary_minute')),CONSTRAINT address_quota_buckets_hash_ck CHECK(octet_length(subject_hash)=32),CONSTRAINT address_quota_buckets_count_ck CHECK(count BETWEEN 1 AND CASE WHEN bucket_kind='metadata_subject_minute' THEN 20 WHEN bucket_kind='metadata_global_minute' THEN 300 WHEN bucket_kind='lookup_subject_hour' THEN 5 WHEN bucket_kind='upstream_minute' THEN 100 WHEN bucket_kind='upstream_day' THEN 5000 ELSE 5 END),CONSTRAINT address_quota_buckets_expiry_ck CHECK(expires_at>window_started_at AND expires_at<=window_started_at+interval '48 hours'));
CREATE TABLE operations.address_canary_nonces (nonce_hash bytea PRIMARY KEY NOT NULL,key_id text NOT NULL,signature_timestamp timestamptz NOT NULL,expires_at timestamptz NOT NULL,consumed_at timestamptz NOT NULL DEFAULT clock_timestamp(),CONSTRAINT address_canary_nonces_key_id_ck CHECK(length(key_id) BETWEEN 1 AND 128),CONSTRAINT address_canary_nonces_hash_ck CHECK(octet_length(nonce_hash)=32),CONSTRAINT address_canary_nonces_expiry_ck CHECK(expires_at=signature_timestamp+interval '10 minutes' AND expires_at>consumed_at AND expires_at<=consumed_at+interval '48 hours'));
CREATE INDEX address_quota_buckets_expiry_idx ON operations.address_quota_buckets(expires_at);
CREATE INDEX address_canary_nonces_expiry_idx ON operations.address_canary_nonces(expires_at);
--> statement-breakpoint
DO $$ BEGIN
 IF NOT EXISTS(SELECT 1 FROM pg_roles WHERE rolname='dsa_seats_address_lookup') THEN CREATE ROLE dsa_seats_address_lookup NOLOGIN NOINHERIT; END IF;
 IF NOT EXISTS(SELECT 1 FROM pg_roles WHERE rolname='dsa_seats_address_maintenance') THEN CREATE ROLE dsa_seats_address_maintenance NOLOGIN NOINHERIT; END IF;
END $$;
DO $$
DECLARE address_roles text[]:=ARRAY['dsa_seats_address_lookup','dsa_seats_address_maintenance']; app_roles text[]:=ARRAY['dsa_seats_web','dsa_seats_ingest','dsa_seats_release_preflight','dsa_seats_release_operator','dsa_seats_migration_owner','dsa_seats_correction_intake','dsa_seats_correction_reviewer','dsa_seats_correction_maintenance'];
BEGIN
 IF EXISTS(SELECT 1 FROM pg_roles WHERE rolname=ANY(address_roles) AND (rolcanlogin OR rolsuper OR rolcreatedb OR rolcreaterole OR rolreplication OR rolbypassrls)) THEN RAISE EXCEPTION 'address roles must be constrained NOLOGIN roles'; END IF;
 IF EXISTS(SELECT 1 FROM pg_auth_members m JOIN pg_roles member ON member.oid=m.member JOIN pg_roles granted ON granted.oid=m.roleid WHERE (member.rolname=ANY(address_roles) AND granted.rolname=ANY(address_roles||app_roles)) OR (member.rolname=ANY(app_roles) AND granted.rolname=ANY(address_roles))) THEN RAISE EXCEPTION 'address roles must not have cross-memberships'; END IF;
END $$;
ALTER TABLE operations.address_quota_buckets ENABLE ROW LEVEL SECURITY;
ALTER TABLE operations.address_canary_nonces ENABLE ROW LEVEL SECURITY;
CREATE OR REPLACE FUNCTION operations.consume_address_metadata_attempt_v1(p_subject_hash bytea) RETURNS TABLE(allowed boolean,retry_after integer) LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,operations,pg_temp AS $$
DECLARE now_at timestamptz:=clock_timestamp(); minute_at timestamptz:=date_trunc('minute',now_at); global_hash bytea:=public.digest('dsa-seats-address-upstream','sha256'); subject_count integer:=0; global_count integer:=0;
BEGIN
 IF NOT pg_has_role(session_user,'dsa_seats_address_lookup','member') OR pg_has_role(session_user,'dsa_seats_address_maintenance','member') OR pg_has_role(session_user,'dsa_seats_web','member') OR pg_has_role(session_user,'dsa_seats_ingest','member') OR pg_has_role(session_user,'dsa_seats_release_preflight','member') OR pg_has_role(session_user,'dsa_seats_release_operator','member') OR pg_has_role(session_user,'dsa_seats_migration_owner','member') OR pg_has_role(session_user,'dsa_seats_correction_intake','member') OR pg_has_role(session_user,'dsa_seats_correction_reviewer','member') OR pg_has_role(session_user,'dsa_seats_correction_maintenance','member') THEN RAISE EXCEPTION 'address lookup role exclusively required' USING ERRCODE='42501'; END IF;
 IF p_subject_hash IS NULL OR octet_length(p_subject_hash)<>32 THEN RAISE EXCEPTION 'subject hash must be 32 bytes' USING ERRCODE='22023'; END IF;
 PERFORM pg_advisory_xact_lock(hashtext('dsa_seats_address_admission'));
 SELECT count INTO subject_count FROM operations.address_quota_buckets WHERE bucket_kind='metadata_subject_minute' AND subject_hash=p_subject_hash AND window_started_at=minute_at; SELECT count INTO global_count FROM operations.address_quota_buckets WHERE bucket_kind='metadata_global_minute' AND subject_hash=global_hash AND window_started_at=minute_at;
 IF subject_count>=20 OR global_count>=300 THEN RETURN QUERY SELECT false,least(86400,ceil(extract(epoch FROM(minute_at+interval '1 minute'-now_at)))::integer); RETURN; END IF;
 INSERT INTO operations.address_quota_buckets VALUES('metadata_subject_minute',p_subject_hash,minute_at,1,minute_at+interval '2 minutes') ON CONFLICT(bucket_kind,subject_hash,window_started_at) DO UPDATE SET count=operations.address_quota_buckets.count+1;
 INSERT INTO operations.address_quota_buckets VALUES('metadata_global_minute',global_hash,minute_at,1,minute_at+interval '2 minutes') ON CONFLICT(bucket_kind,subject_hash,window_started_at) DO UPDATE SET count=operations.address_quota_buckets.count+1;
 RETURN QUERY SELECT true,NULL::integer;
END $$;
CREATE OR REPLACE FUNCTION operations.consume_address_lookup_v1(p_subject_hash bytea) RETURNS TABLE(allowed boolean,retry_after integer) LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,operations,pg_temp AS $$
DECLARE now_at timestamptz:=clock_timestamp(); hour_at timestamptz:=date_trunc('hour',now_at); minute_at timestamptz:=date_trunc('minute',now_at); day_at timestamptz:=date_trunc('day',now_at); global_hash bytea:=public.digest('dsa-seats-address-upstream','sha256'); subject_count integer:=0; minute_count integer:=0; day_count integer:=0; retry integer:=0;
BEGIN
 IF NOT pg_has_role(session_user,'dsa_seats_address_lookup','member') OR pg_has_role(session_user,'dsa_seats_address_maintenance','member') OR pg_has_role(session_user,'dsa_seats_web','member') OR pg_has_role(session_user,'dsa_seats_ingest','member') OR pg_has_role(session_user,'dsa_seats_release_preflight','member') OR pg_has_role(session_user,'dsa_seats_release_operator','member') OR pg_has_role(session_user,'dsa_seats_migration_owner','member') OR pg_has_role(session_user,'dsa_seats_correction_intake','member') OR pg_has_role(session_user,'dsa_seats_correction_reviewer','member') OR pg_has_role(session_user,'dsa_seats_correction_maintenance','member') THEN RAISE EXCEPTION 'address lookup role exclusively required' USING ERRCODE='42501'; END IF;
 IF p_subject_hash IS NULL OR octet_length(p_subject_hash)<>32 THEN RAISE EXCEPTION 'subject hash must be 32 bytes' USING ERRCODE='22023'; END IF; PERFORM pg_advisory_xact_lock(hashtext('dsa_seats_address_admission'));
 SELECT count INTO subject_count FROM operations.address_quota_buckets WHERE bucket_kind='lookup_subject_hour' AND subject_hash=p_subject_hash AND window_started_at=hour_at; SELECT count INTO minute_count FROM operations.address_quota_buckets WHERE bucket_kind='upstream_minute' AND subject_hash=global_hash AND window_started_at=minute_at; SELECT count INTO day_count FROM operations.address_quota_buckets WHERE bucket_kind='upstream_day' AND subject_hash=global_hash AND window_started_at=day_at;
 IF subject_count>=5 OR minute_count>=100 OR day_count>=5000 THEN retry:=greatest(CASE WHEN subject_count>=5 THEN ceil(extract(epoch FROM(hour_at+interval '1 hour'-now_at)))::integer ELSE 0 END,CASE WHEN minute_count>=100 THEN ceil(extract(epoch FROM(minute_at+interval '1 minute'-now_at)))::integer ELSE 0 END,CASE WHEN day_count>=5000 THEN ceil(extract(epoch FROM(day_at+interval '1 day'-now_at)))::integer ELSE 0 END); RETURN QUERY SELECT false,least(86400,retry); RETURN; END IF;
 INSERT INTO operations.address_quota_buckets VALUES('lookup_subject_hour',p_subject_hash,hour_at,1,hour_at+interval '2 hours') ON CONFLICT(bucket_kind,subject_hash,window_started_at) DO UPDATE SET count=operations.address_quota_buckets.count+1; INSERT INTO operations.address_quota_buckets VALUES('upstream_minute',global_hash,minute_at,1,minute_at+interval '2 minutes') ON CONFLICT(bucket_kind,subject_hash,window_started_at) DO UPDATE SET count=operations.address_quota_buckets.count+1; INSERT INTO operations.address_quota_buckets VALUES('upstream_day',global_hash,day_at,1,day_at+interval '2 days') ON CONFLICT(bucket_kind,subject_hash,window_started_at) DO UPDATE SET count=operations.address_quota_buckets.count+1; RETURN QUERY SELECT true,NULL::integer;
END $$;
CREATE OR REPLACE FUNCTION operations.consume_address_canary_v1(p_subject_hash bytea,p_nonce_hash bytea,p_key_id text,p_signature_timestamp timestamptz,p_expires_at timestamptz) RETURNS TABLE(allowed boolean,retry_after integer) LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,operations,pg_temp AS $$
DECLARE now_at timestamptz:=clock_timestamp(); minute_at timestamptz:=date_trunc('minute',now_at); day_at timestamptz:=date_trunc('day',now_at); global_hash bytea:=public.digest('dsa-seats-address-upstream','sha256'); canary_count integer:=0; minute_count integer:=0; day_count integer:=0; retry integer:=0;
BEGIN
 IF NOT pg_has_role(session_user,'dsa_seats_address_lookup','member') OR pg_has_role(session_user,'dsa_seats_address_maintenance','member') OR pg_has_role(session_user,'dsa_seats_web','member') OR pg_has_role(session_user,'dsa_seats_ingest','member') OR pg_has_role(session_user,'dsa_seats_release_preflight','member') OR pg_has_role(session_user,'dsa_seats_release_operator','member') OR pg_has_role(session_user,'dsa_seats_migration_owner','member') OR pg_has_role(session_user,'dsa_seats_correction_intake','member') OR pg_has_role(session_user,'dsa_seats_correction_reviewer','member') OR pg_has_role(session_user,'dsa_seats_correction_maintenance','member') THEN RAISE EXCEPTION 'address lookup role exclusively required' USING ERRCODE='42501'; END IF;
 IF p_subject_hash IS NULL OR p_nonce_hash IS NULL OR octet_length(p_subject_hash)<>32 OR octet_length(p_nonce_hash)<>32 OR p_key_id IS NULL OR length(p_key_id) NOT BETWEEN 1 AND 128 OR p_signature_timestamp IS NULL OR p_expires_at IS NULL OR p_expires_at<>p_signature_timestamp+interval '10 minutes' OR p_signature_timestamp>now_at+interval '30 seconds' OR p_expires_at<=now_at THEN RAISE EXCEPTION 'invalid canary capability' USING ERRCODE='22023'; END IF;
 INSERT INTO operations.address_canary_nonces(nonce_hash,key_id,signature_timestamp,expires_at,consumed_at) VALUES(p_nonce_hash,p_key_id,p_signature_timestamp,p_expires_at,now_at) ON CONFLICT DO NOTHING; IF NOT FOUND THEN RETURN QUERY SELECT false,600; RETURN; END IF;
 PERFORM pg_advisory_xact_lock(hashtext('dsa_seats_address_admission')); SELECT count INTO canary_count FROM operations.address_quota_buckets WHERE bucket_kind='canary_minute' AND subject_hash=p_subject_hash AND window_started_at=minute_at; SELECT count INTO minute_count FROM operations.address_quota_buckets WHERE bucket_kind='upstream_minute' AND subject_hash=global_hash AND window_started_at=minute_at; SELECT count INTO day_count FROM operations.address_quota_buckets WHERE bucket_kind='upstream_day' AND subject_hash=global_hash AND window_started_at=day_at;
 IF canary_count>=5 OR minute_count>=100 OR day_count>=5000 THEN retry:=greatest(CASE WHEN canary_count>=5 OR minute_count>=100 THEN ceil(extract(epoch FROM(minute_at+interval '1 minute'-now_at)))::integer ELSE 0 END,CASE WHEN day_count>=5000 THEN ceil(extract(epoch FROM(day_at+interval '1 day'-now_at)))::integer ELSE 0 END); RETURN QUERY SELECT false,least(86400,retry); RETURN; END IF;
 INSERT INTO operations.address_quota_buckets VALUES('canary_minute',p_subject_hash,minute_at,1,minute_at+interval '2 minutes') ON CONFLICT(bucket_kind,subject_hash,window_started_at) DO UPDATE SET count=operations.address_quota_buckets.count+1; INSERT INTO operations.address_quota_buckets VALUES('upstream_minute',global_hash,minute_at,1,minute_at+interval '2 minutes') ON CONFLICT(bucket_kind,subject_hash,window_started_at) DO UPDATE SET count=operations.address_quota_buckets.count+1; INSERT INTO operations.address_quota_buckets VALUES('upstream_day',global_hash,day_at,1,day_at+interval '2 days') ON CONFLICT(bucket_kind,subject_hash,window_started_at) DO UPDATE SET count=operations.address_quota_buckets.count+1; RETURN QUERY SELECT true,NULL::integer;
END $$;
CREATE OR REPLACE FUNCTION operations.cleanup_address_admission_v1() RETURNS TABLE(quota_buckets_deleted integer,canary_nonces_deleted integer) LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,operations,pg_temp AS $$
BEGIN
 IF NOT pg_has_role(session_user,'dsa_seats_address_maintenance','member') OR pg_has_role(session_user,'dsa_seats_address_lookup','member') OR pg_has_role(session_user,'dsa_seats_web','member') OR pg_has_role(session_user,'dsa_seats_ingest','member') OR pg_has_role(session_user,'dsa_seats_release_preflight','member') OR pg_has_role(session_user,'dsa_seats_release_operator','member') OR pg_has_role(session_user,'dsa_seats_migration_owner','member') OR pg_has_role(session_user,'dsa_seats_correction_intake','member') OR pg_has_role(session_user,'dsa_seats_correction_reviewer','member') OR pg_has_role(session_user,'dsa_seats_correction_maintenance','member') THEN RAISE EXCEPTION 'address maintenance role exclusively required' USING ERRCODE='42501'; END IF;
 WITH expired AS (SELECT ctid FROM operations.address_quota_buckets WHERE expires_at<=clock_timestamp() ORDER BY expires_at LIMIT 1000) DELETE FROM operations.address_quota_buckets WHERE ctid IN(SELECT ctid FROM expired); GET DIAGNOSTICS quota_buckets_deleted=ROW_COUNT;
 WITH expired AS (SELECT ctid FROM operations.address_canary_nonces WHERE expires_at<=clock_timestamp() ORDER BY expires_at LIMIT 1000) DELETE FROM operations.address_canary_nonces WHERE ctid IN(SELECT ctid FROM expired); GET DIAGNOSTICS canary_nonces_deleted=ROW_COUNT; RETURN NEXT;
END $$;
--> statement-breakpoint
DO $$ DECLARE f text; BEGIN FOR f IN SELECT unnest(ARRAY['consume_address_metadata_attempt_v1(bytea)','consume_address_lookup_v1(bytea)','consume_address_canary_v1(bytea,bytea,text,timestamp with time zone,timestamp with time zone)','cleanup_address_admission_v1()']) LOOP EXECUTE 'ALTER FUNCTION operations.'||f||' OWNER TO dsa_seats_migration_owner'; END LOOP; ALTER TABLE operations.address_quota_buckets OWNER TO dsa_seats_migration_owner; ALTER TABLE operations.address_canary_nonces OWNER TO dsa_seats_migration_owner; END $$;
REVOKE ALL ON operations.address_quota_buckets,operations.address_canary_nonces FROM PUBLIC,dsa_seats_address_lookup,dsa_seats_address_maintenance,dsa_seats_web,dsa_seats_ingest,dsa_seats_release_preflight,dsa_seats_release_operator;
REVOKE ALL ON FUNCTION operations.consume_address_metadata_attempt_v1(bytea),operations.consume_address_lookup_v1(bytea),operations.consume_address_canary_v1(bytea,bytea,text,timestamptz,timestamptz),operations.cleanup_address_admission_v1() FROM PUBLIC;
GRANT USAGE ON SCHEMA operations TO dsa_seats_address_lookup,dsa_seats_address_maintenance;
GRANT USAGE ON SCHEMA public TO dsa_seats_address_lookup;
GRANT EXECUTE ON FUNCTION operations.consume_address_metadata_attempt_v1(bytea),operations.consume_address_lookup_v1(bytea),operations.consume_address_canary_v1(bytea,bytea,text,timestamptz,timestamptz) TO dsa_seats_address_lookup;
GRANT EXECUTE ON FUNCTION operations.cleanup_address_admission_v1() TO dsa_seats_address_maintenance;
REVOKE ALL ON public.data_releases,public.geography_versions,public.release_profile_seats,public.seat_cycles,public.offices,public.office_terms,public.jurisdictions FROM dsa_seats_address_lookup;
GRANT SELECT ON public.data_releases,public.geography_versions,public.release_profile_seats,public.seat_cycles,public.offices,public.office_terms,public.jurisdictions TO dsa_seats_address_lookup;
CREATE POLICY address_lookup_current_published ON public.data_releases FOR SELECT TO dsa_seats_address_lookup USING(status='published');
CREATE POLICY address_lookup_current_published ON public.geography_versions FOR SELECT TO dsa_seats_address_lookup USING(EXISTS(SELECT 1 FROM public.data_releases r WHERE r.id=release_id AND r.status='published'));
CREATE POLICY address_lookup_current_published ON public.release_profile_seats FOR SELECT TO dsa_seats_address_lookup USING(EXISTS(SELECT 1 FROM public.data_releases r WHERE r.id=release_id AND r.status='published'));
CREATE POLICY address_lookup_current_published ON public.seat_cycles FOR SELECT TO dsa_seats_address_lookup USING(EXISTS(SELECT 1 FROM public.data_releases r WHERE r.id=release_id AND r.status='published'));
CREATE POLICY address_lookup_current_published ON public.offices FOR SELECT TO dsa_seats_address_lookup USING(EXISTS(SELECT 1 FROM public.data_releases r WHERE r.id=release_id AND r.status='published'));
CREATE POLICY address_lookup_current_published ON public.office_terms FOR SELECT TO dsa_seats_address_lookup USING(EXISTS(SELECT 1 FROM public.data_releases r WHERE r.id=release_id AND r.status='published'));
CREATE POLICY address_lookup_current_published ON public.jurisdictions FOR SELECT TO dsa_seats_address_lookup USING(EXISTS(SELECT 1 FROM public.data_releases r WHERE r.id=release_id AND r.status='published'));
