ALTER TABLE "fec_v2_runs" DROP CONSTRAINT "f2runs_id_ck";--> statement-breakpoint
ALTER TABLE "fec_v2_runs" ADD CONSTRAINT "f2runs_id_ck" CHECK (length("fec_v2_runs"."run_id") BETWEEN 1 AND 512 AND "fec_v2_runs"."run_id" ~ '^[A-Za-z0-9][A-Za-z0-9._:-]*$');
--> statement-breakpoint
CREATE OR REPLACE FUNCTION public.claim_fec_v2_run(p_release text,p_plan text,p_run text,p_owner_token text) RETURNS TABLE(release_id text,plan_sha256 text,run_id text,started_at timestamptz,heartbeat_at timestamptz,lease_expires_at timestamptz,run_deadline_at timestamptz)
LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public,pg_temp AS $$
DECLARE now_at timestamptz;
BEGIN
  IF NOT (length(p_run) BETWEEN 1 AND 512 AND p_run ~ '^[A-Za-z0-9][A-Za-z0-9._:-]*$') THEN RAISE EXCEPTION 'invalid FEC V2 run id' USING ERRCODE='22023'; END IF;
  PERFORM public.assert_fec_v2_acquisition_admission(); PERFORM pg_advisory_xact_lock(hashtext('dsa_seats_release_promotion')); PERFORM pg_advisory_xact_lock(hashtext('dsa_seats_release:'||p_release)); now_at:=clock_timestamp();
  IF NOT EXISTS (SELECT 1 FROM public.data_releases d JOIN public.fec_v2_plans p ON p.release_id=d.id WHERE d.id=p_release AND d.status='candidate' AND p.plan_sha256=p_plan AND p.sealed_at IS NOT NULL) THEN RAISE EXCEPTION 'candidate sealed plan required' USING ERRCODE='55000'; END IF;
  IF EXISTS (SELECT 1 FROM public.fec_v2_runs WHERE release_id=p_release AND plan_sha256=p_plan AND status IN ('running','completed')) THEN RAISE EXCEPTION 'active run exists' USING ERRCODE='23505'; END IF;
  INSERT INTO public.fec_v2_runs(run_id,release_id,plan_sha256,receipt_cutoff,started_at,status,owner_token_sha256,heartbeat_at,lease_expires_at,run_deadline_at) VALUES(p_run,p_release,p_plan,DATE '2026-07-18',now_at,'running',public.fec_v2_owner_token_sha256(p_owner_token),now_at,now_at+interval '300 seconds',now_at+interval '6 hours');
  RETURN QUERY SELECT r.release_id,r.plan_sha256,r.run_id,r.started_at,r.heartbeat_at,r.lease_expires_at,r.run_deadline_at FROM public.fec_v2_runs r WHERE r.release_id=p_release AND r.plan_sha256=p_plan AND r.run_id=p_run;
END $$;
--> statement-breakpoint
CREATE OR REPLACE FUNCTION public.reap_expired_fec_v2_run(p_release text,p_plan text,p_expired_run text,p_new_run text,p_new_raw_token text) RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public,pg_temp AS $$
DECLARE now_at timestamptz; scope text; subject_hash text; old_status text; new_status text; stored text; new_hash text;
BEGIN
 IF NOT (length(p_expired_run) BETWEEN 1 AND 512 AND p_expired_run ~ '^[A-Za-z0-9][A-Za-z0-9._:-]*$') OR NOT (length(p_new_run) BETWEEN 1 AND 512 AND p_new_run ~ '^[A-Za-z0-9][A-Za-z0-9._:-]*$') THEN RAISE EXCEPTION 'invalid FEC V2 run id' USING ERRCODE='22023'; END IF;
 new_hash:=public.fec_v2_owner_token_sha256(p_new_raw_token);
 PERFORM public.assert_fec_v2_acquisition_admission(); PERFORM pg_advisory_xact_lock(hashtext('dsa_seats_release_promotion')); PERFORM pg_advisory_xact_lock(hashtext('dsa_seats_release:'||p_release)); now_at:=clock_timestamp();
 IF NOT EXISTS(SELECT 1 FROM public.data_releases d JOIN public.fec_v2_plans p ON p.release_id=d.id WHERE d.id=p_release AND d.status='candidate' AND p.plan_sha256=p_plan AND p.sealed_at IS NOT NULL) THEN RAISE EXCEPTION 'candidate sealed plan required' USING ERRCODE='55000'; END IF;
 scope:=encode(digest(convert_to('fec-v2-run-lease-expired-v1','UTF8')||decode('00','hex')||convert_to(p_release,'UTF8')||decode('00','hex')||convert_to(p_plan,'UTF8')||decode('00','hex')||convert_to(p_expired_run,'UTF8'),'sha256'),'hex'); subject_hash:=encode(digest(convert_to('{"schemaVersion":1,"runId":'||to_json(p_expired_run::text)::text||',"failureCode":"lease_expired","scopeSha256":'||to_json(scope::text)::text||'}'||chr(10),'UTF8'),'sha256'),'hex');
 SELECT status INTO old_status FROM public.fec_v2_runs WHERE release_id=p_release AND plan_sha256=p_plan AND run_id=p_expired_run FOR UPDATE; SELECT status,owner_token_sha256 INTO new_status,stored FROM public.fec_v2_runs WHERE release_id=p_release AND plan_sha256=p_plan AND run_id=p_new_run FOR UPDATE;
 IF old_status='failed' AND new_status='running' AND stored IS NOT NULL AND public.fec_v2_constant_time_digest_eq(decode(stored,'hex'),decode(new_hash,'hex')) AND (SELECT count(*) FROM public.fec_v2_run_failures WHERE release_id=p_release AND plan_sha256=p_plan AND run_id=p_expired_run)=1 AND EXISTS(SELECT 1 FROM public.fec_v2_run_failures WHERE release_id=p_release AND plan_sha256=p_plan AND run_id=p_expired_run AND failure_code='lease_expired' AND scope_sha256=scope AND subject_sha256=subject_hash) THEN RETURN; END IF;
 IF old_status IS DISTINCT FROM 'running' OR NOT EXISTS(SELECT 1 FROM public.fec_v2_runs WHERE release_id=p_release AND plan_sha256=p_plan AND run_id=p_expired_run AND (lease_expires_at<now_at OR run_deadline_at<=now_at)) OR new_status IS NOT NULL THEN RAISE EXCEPTION 'exact expired old run and absent new run required' USING ERRCODE='55000'; END IF;
 DELETE FROM public.fec_v2_replay_attestations WHERE release_id=p_release AND plan_sha256=p_plan AND run_id=p_expired_run; DELETE FROM public.stg_fec_v2_acquisition_outcomes WHERE release_id=p_release AND plan_sha256=p_plan AND run_id=p_expired_run; DELETE FROM public.stg_fec_v2_amendment_links WHERE release_id=p_release AND plan_sha256=p_plan AND run_id=p_expired_run; DELETE FROM public.stg_fec_v2_page_lineage WHERE release_id=p_release AND plan_sha256=p_plan AND run_id=p_expired_run; DELETE FROM public.stg_fec_v2_sanitized_filings WHERE release_id=p_release AND plan_sha256=p_plan AND run_id=p_expired_run; DELETE FROM public.stg_fec_v2_filing_ledger_entries WHERE release_id=p_release AND plan_sha256=p_plan AND run_id=p_expired_run; DELETE FROM public.stg_fec_v2_filing_ledgers WHERE release_id=p_release AND plan_sha256=p_plan AND run_id=p_expired_run; DELETE FROM public.stg_fec_v2_enumeration_pages WHERE release_id=p_release AND plan_sha256=p_plan AND run_id=p_expired_run; DELETE FROM public.stg_fec_v2_artifact_receipts WHERE release_id=p_release AND plan_sha256=p_plan AND run_id=p_expired_run; DELETE FROM public.stg_fec_v2_artifacts WHERE release_id=p_release AND plan_sha256=p_plan AND run_id=p_expired_run; DELETE FROM public.stg_fec_v2_snapshots WHERE release_id=p_release AND plan_sha256=p_plan AND run_id=p_expired_run;
 INSERT INTO public.fec_v2_run_failures(release_id,plan_sha256,run_id,failure_code,scope_sha256,subject_sha256) VALUES(p_release,p_plan,p_expired_run,'lease_expired',scope,subject_hash); UPDATE public.fec_v2_runs SET status='failed',completed_at=now_at,owner_token_sha256=NULL,heartbeat_at=NULL,lease_expires_at=NULL WHERE release_id=p_release AND plan_sha256=p_plan AND run_id=p_expired_run; INSERT INTO public.fec_v2_runs(run_id,release_id,plan_sha256,receipt_cutoff,started_at,status,owner_token_sha256,heartbeat_at,lease_expires_at,run_deadline_at) SELECT p_new_run,p_release,p_plan,receipt_cutoff,now_at,'running',new_hash,now_at,now_at+interval '300 seconds',now_at+interval '6 hours' FROM public.fec_v2_runs WHERE release_id=p_release AND plan_sha256=p_plan AND run_id=p_expired_run;
END $$;
