import { constants } from "node:fs";
import { generateKeyPairSync, sign } from "node:crypto";
import { describe, expect, it } from "vitest";
import { canonicalFeatureGate, createFeatureGateReader, gatePath, type GateAuthority } from "./gates";

const now = Date.parse("2026-01-02T03:04:05.000Z"), keys = generateKeyPairSync("ed25519");
const stat = (directory: boolean, overrides = {}) => ({ isFile: () => !directory, isDirectory: () => directory, isSymbolicLink: () => false, uid: 0, gid: 42, mode: directory ? 0o750 : 0o640, ino: directory ? 1 : 2, dev: 1, ...overrides });
function signed(overrides: object = {}) { const value = { version: 2 as const, generatedAt: new Date(now).toISOString(), signerKeyId: "offline-1", correction: { mode: "enabled" as const, packageSha256: "a".repeat(64), expiresAt: new Date(now + 60_000).toISOString() }, address: { mode: "canary" as const, packageSha256: "b".repeat(64), expiresAt: new Date(now + 60_000).toISOString(), }, ...overrides }; return { ...value, signature: sign(null, canonicalFeatureGate(value), keys.privateKey).toString("base64") }; }
function authority(gate: unknown = signed(), key: unknown = { version: 1, keyId: "offline-1", publicKeyPem: keys.publicKey.export({ type: "spki", format: "pem" }).toString() }): GateAuthority { return { now: () => now, groupId: async () => 42, lstat: async path => stat(path.endsWith(".json") ? false : true), open: async path => ({ stat: async () => stat(false), readFile: async () => Buffer.from(JSON.stringify(path.includes("public-key") ? key : gate)), close: async () => undefined }) }; }
describe("feature gates", () => {
  it("accepts an exact fresh offline signature", async () => expect((await createFeatureGateReader(authority(), { NODE_ENV: "test" })()).address.mode).toBe("canary"));
  it("fails closed for tampering, expiry, wrong key, and separate-package violations", async () => { for (const value of [{ ...signed(), signature: "A".repeat(88) }, signed({ generatedAt: new Date(now - 60_001).toISOString() }), signed({ address: { mode: "enabled", packageSha256: "a".repeat(64), expiresAt: new Date(now + 60_000).toISOString() } })]) expect((await createFeatureGateReader(authority(value), { NODE_ENV: "test" })()).address.mode).toBe("disabled"); expect((await createFeatureGateReader(authority(signed(), { version: 1, keyId: "wrong", publicKeyPem: keys.publicKey.export({ type: "spki", format: "pem" }).toString() }), { NODE_ENV: "test" })()).correction.mode).toBe("disabled"); });
  it("uses O_NOFOLLOW and fixed production path", async () => { expect(gatePath({ NODE_ENV: "production", DSA_SEATS_FEATURE_GATES_PATH: "/evil" })).toBe("/run/dsa-seats/feature-gates.json"); let flags = 0; const source = authority(); const original = source.open; source.open = async (path, value) => { flags = value; return original(path, value); }; await createFeatureGateReader(source, { NODE_ENV: "test" })(); expect(flags).toBe(constants.O_RDONLY | constants.O_NOFOLLOW); });
});
