import { createHash } from "node:crypto";
import { z } from "zod";
import { canonicalJson } from "../fec/aipac-proposed-packages";
import { validateCaliforniaCurrentIncumbentPrimaryLinkageCandidate } from "./california-current-incumbent-primary-linkage-candidate";
import { validateCaliforniaPrimaryGeographyCompatibilityCandidate } from "./california-primary-geography-compatibility-candidate";
import { validateHouseDemocraticPrimarySourceSelectionProposal } from "./house-democratic-primary-source-selection-proposal";

const SHA = z.string().regex(/^[a-f0-9]{64}$/);
const INPUTS = {
  proposalFile: "85246e9adfd181e6f24606b6eaa29250c45c9e8e42a6dd5af5cb162de17f45b1", proposalPackage: "a090e0be03dc2b0fa5edd0c1132a8261eed0f98ceb4df090154d0b150d8721fb",
  identityFile: "3fe6f8d58d31c594410f8261d02b79ef64c0425cf5484be04247b86acc1893d3", identityPackage: "13949617d14185a6b9ad8edc6ae60a7cd013201adf28695361cafdfcac5ca8c3", identitySet: "775690d3d994509b1c79f63d41e14107f116fbbb082cda59cb01501fd233f2e1",
  geographyFile: "26bf6010c411d6895c6d307788ec203e75ad1e60f947773ac9ed6283ddccb8c6", geographyPackage: "59ee4593076e81829dbb576f70230b0c50744d473c80c57b050ce5e9884b3f94", geographySet: "ea829f1b57dc8f494676d9a9991546e9d08887eaf36cd06e422339d27519dcea",
} as const;
const EXPECTED_PACKAGE = "07c0935ab49783ae697ff7f7b395d16fccca00ee5f4bd688b6ac76fe677d0a2f";
const digest = (domain: string, value: unknown): string => createHash("sha256").update(domain).update(canonicalJson(value)).digest("hex");
const bytewise = (a: string, b: string): number => Buffer.compare(Buffer.from(a), Buffer.from(b));

const row = z.strictObject({
  reviewRecordId: z.string(), linkageId: z.string(), contestId: z.string(), contestSha256: SHA, seatCycleId: z.string(), districtCode: z.string().regex(/^\d{2}$/), cycleYear: z.union([z.literal(2022), z.literal(2024), z.literal(2026)]),
  identity: z.strictObject({ parentRowSha256: SHA, bioguideId: z.string(), officialHouseName: z.string(), sourceCandidateName: z.string().nullable(), sourcePartyPreference: z.string().nullable(), evidenceClass: z.enum(["exact_name_observation", "derived_name_relationship", "inferred_name_relationship", "unresolved"]), confidence: z.enum(["high", "medium", "none"]), relationshipDisposition: z.enum(["proposed_identity_link_pending_documented_review", "not_linked_no_unique_candidate"]), candidate: z.boolean(), approved: z.literal(false) }),
  geography: z.strictObject({ parentRowSha256: SHA, targetCd119Geoid: z.string(), historicalCongressSession: z.enum(["118", "119", "120"]), historicalGeoid: z.string().nullable(), evidenceClass: z.enum(["direct_official_plan_continuity_and_derived_key", "derived_exact_session_and_key", "authority_pending"]), confidence: z.enum(["high", "none"]), compatibilityDisposition: z.enum(["official_no_plan_change_declaration_same_geoid_key_candidate", "same_cd119_session_and_geoid_exact_key_candidate", "unassessed_cd120_authority_collection_pending"]), candidate: z.boolean(), approved: z.literal(false) }),
  reviewCategory: z.enum(["identity_and_geography_candidates", "geography_candidate_identity_unresolved", "identity_candidate_cd120_geography_pending", "identity_unresolved_cd120_geography_pending"]), jointApproved: z.literal(false), nominationSystem: z.literal("top_two_open_primary"), formulaApplicability: z.literal("confirmed_incompatible_with_party_primary_metrics"), evaluatorUse: z.literal("excluded_pending_authorized_identity_geography_and_top_two_review"), scoreEligible: z.literal(false), reviewerAction: z.string(), rowSha256: SHA,
});
export const californiaPrimaryIdentityGeographyReviewPackageSchema = z.strictObject({
  schema: z.literal("california-primary-identity-geography-review-package-v1"), version: z.literal(1), generatedAt: z.literal("2026-08-06T20:00:00.000Z"), sourceCutoff: z.literal("2026-08-05"), reviewerOnly: z.literal(true), publicationEligible: z.literal(false), defaultUse: z.literal("exclude_from_evaluator_until_independent_identity_geography_and_top_two_review"), review: z.strictObject({ status: z.literal("proposed"), reviewer: z.null(), reviewedAt: z.null(), resolution: z.null() }),
  inputs: z.strictObject({ sourceSelectionProposal: z.strictObject({ sourceLockId: z.literal("house-democratic-primary-source-selection-proposal-20260804-v1"), fileSha256: z.literal(INPUTS.proposalFile), packageSha256: z.literal(INPUTS.proposalPackage) }), identityCandidate: z.strictObject({ sourceLockId: z.literal("california-current-incumbent-primary-linkage-candidate-v1"), fileSha256: z.literal(INPUTS.identityFile), packageSha256: z.literal(INPUTS.identityPackage), linkSetSha256: z.literal(INPUTS.identitySet) }), geographyCandidate: z.strictObject({ sourceLockId: z.literal("california-primary-geography-compatibility-candidate-v1"), fileSha256: z.literal(INPUTS.geographyFile), packageSha256: z.literal(INPUTS.geographyPackage), rowSetSha256: z.literal(INPUTS.geographySet) }) }),
  methodology: z.strictObject({ scope: z.literal("exact_126_california_target_identity_rows_joined_to_matching_geography_rows"), identityAndGeographyReviewedIndependently: z.literal(true), jointPackageApprovesParents: z.literal(false), automaticApprovals: z.literal(0), evaluatorNumericValues: z.literal(0) }), summary: z.strictObject({ reviewRecords: z.literal(126), identityAndGeographyCandidates: z.literal(76), geographyCandidateIdentityUnresolved: z.literal(8), identityCandidateCd120GeographyPending: z.literal(38), identityUnresolvedCd120GeographyPending: z.literal(4), identityCandidates: z.literal(114), geographyCandidates: z.literal(84), jointApprovedRecords: z.literal(0), scoreEligibleRecords: z.literal(0) }), records: z.array(row).length(126), reviewRecordSetSha256: SHA,
  decisionSupport: z.strictObject({ identityDecisionId: z.literal("approve-historic-primary-candidate-identity-resolution-v1"), geographyDecisionId: z.literal("approve-historical-district-cd119-compatibility-v1"), topTwoDecisionId: z.literal("decide-nonstandard-primary-disposition-treatment-v1"), resolutions: z.strictObject({ identity: z.null(), geography: z.null(), topTwo: z.null() }), lifecycle: z.literal("review_queue_for_bound_existing_decisions_not_an_independent_decision") }), packageSha256: SHA,
});
export type CaliforniaPrimaryIdentityGeographyReviewPackage = z.infer<typeof californiaPrimaryIdentityGeographyReviewPackageSchema>;

type BuildInput = Readonly<{ proposal: unknown; proposalFileSha256: string; identity: unknown; identityFileSha256: string; geography: unknown; geographyFileSha256: string; sourceLock: unknown }>;
export function buildCaliforniaPrimaryIdentityGeographyReviewPackage(input: BuildInput): CaliforniaPrimaryIdentityGeographyReviewPackage {
  if (input.proposalFileSha256 !== INPUTS.proposalFile || input.identityFileSha256 !== INPUTS.identityFile || input.geographyFileSha256 !== INPUTS.geographyFile) throw new Error("CA_PRIMARY_JOINT_INPUT_HASH_MISMATCH");
  const proposal = validateHouseDemocraticPrimarySourceSelectionProposal(input.proposal), identity = validateCaliforniaCurrentIncumbentPrimaryLinkageCandidate(input.identity), geography = validateCaliforniaPrimaryGeographyCompatibilityCandidate(input.geography), decisions = { identity: proposal.decisions.find((value) => value.decisionId === "approve-historic-primary-candidate-identity-resolution-v1"), geography: proposal.decisions.find((value) => value.decisionId === "approve-historical-district-cd119-compatibility-v1"), topTwo: proposal.decisions.find((value) => value.decisionId === "decide-nonstandard-primary-disposition-treatment-v1") };
  if (proposal.packageSha256 !== INPUTS.proposalPackage || identity.packageSha256 !== INPUTS.identityPackage || identity.linkSetSha256 !== INPUTS.identitySet || geography.packageSha256 !== INPUTS.geographyPackage || geography.rowSetSha256 !== INPUTS.geographySet || Object.values(decisions).some((value) => !value || value.resolution !== null) || identity.review.resolution !== null || geography.review.resolution !== null) throw new Error("CA_PRIMARY_JOINT_PARENT_INVALID");
  const lock = z.object({ entries: z.array(z.object({ id: z.string(), retainedPath: z.string().nullable().optional(), retainedStatus: z.string(), sha256: SHA, kind: z.string() })) }).parse(input.sourceLock), required = [["house-democratic-primary-source-selection-proposal-20260804-v1", INPUTS.proposalFile, "data/metadata/house-democratic-primary-source-selection-proposal-20260804-v1.json", "review_proposal"], ["california-current-incumbent-primary-linkage-candidate-v1", INPUTS.identityFile, "data/metadata/california-current-incumbent-primary-linkage-candidate-v1.json", "review_candidate"], ["california-primary-geography-compatibility-candidate-v1", INPUTS.geographyFile, "data/metadata/california-primary-geography-compatibility-candidate-v1.json", "review_candidate"]] as const;
  if (required.some(([id, sha256, path, kind]) => { const matches = lock.entries.filter((entry) => entry.id === id); return matches.length !== 1 || matches[0]!.retainedStatus !== "retained" || matches[0]!.sha256 !== sha256 || matches[0]!.retainedPath !== path || matches[0]!.kind !== kind; })) throw new Error("CA_PRIMARY_JOINT_SOURCE_LOCK_MISMATCH");
  const geographyByContest = new Map(geography.rows.map((value) => [value.contestId, value]));
  const records = identity.links.map((identityRow) => {
    const geographyRow = geographyByContest.get(identityRow.contestId); if (!geographyRow || geographyRow.contestSha256 !== identityRow.contestSha256 || geographyRow.seatCycleId !== identityRow.seatCycleId || geographyRow.cycleYear !== identityRow.cycleYear) throw new Error("CA_PRIMARY_JOINT_ROW_JOIN_MISMATCH");
    const identityCandidate = identityRow.relationshipDisposition === "proposed_identity_link_pending_documented_review", geographyCandidate = geographyRow.compatibilityCandidate, reviewCategory = identityCandidate && geographyCandidate ? "identity_and_geography_candidates" as const : !identityCandidate && geographyCandidate ? "geography_candidate_identity_unresolved" as const : identityCandidate ? "identity_candidate_cd120_geography_pending" as const : "identity_unresolved_cd120_geography_pending" as const;
    const unsigned = { reviewRecordId: `ca-primary-joint:${identityRow.linkageId}`, linkageId: identityRow.linkageId, contestId: identityRow.contestId, contestSha256: identityRow.contestSha256, seatCycleId: identityRow.seatCycleId, districtCode: identityRow.districtCode, cycleYear: identityRow.cycleYear, identity: { parentRowSha256: identityRow.rowSha256, bioguideId: identityRow.rosterIdentity.bioguideId, officialHouseName: identityRow.rosterIdentity.officialHouseName, sourceCandidateName: identityRow.sourceCandidate?.sourceCandidateName ?? null, sourcePartyPreference: identityRow.sourceCandidate?.partyPreference ?? null, evidenceClass: identityRow.evidenceClass, confidence: identityRow.confidence, relationshipDisposition: identityRow.relationshipDisposition, candidate: identityCandidate, approved: false as const }, geography: { parentRowSha256: geographyRow.rowSha256, targetCd119Geoid: geographyRow.targetCd119Geoid, historicalCongressSession: geographyRow.historicalCongressSession, historicalGeoid: geographyRow.historicalGeoid, evidenceClass: geographyRow.evidenceClass, confidence: geographyRow.confidence, compatibilityDisposition: geographyRow.compatibilityDisposition, candidate: geographyCandidate, approved: false as const }, reviewCategory, jointApproved: false as const, nominationSystem: "top_two_open_primary" as const, formulaApplicability: "confirmed_incompatible_with_party_primary_metrics" as const, evaluatorUse: "excluded_pending_authorized_identity_geography_and_top_two_review" as const, scoreEligible: false as const, reviewerAction: reviewCategory === "identity_and_geography_candidates" ? "review_identity_and_geography_independently" : reviewCategory === "geography_candidate_identity_unresolved" ? "retain_geography_candidate_and_resolve_identity_nonappearance" : reviewCategory === "identity_candidate_cd120_geography_pending" ? "review_identity_and_retain_cd120_geography_pending" : "retain_identity_unresolved_and_cd120_geography_pending" };
    return { ...unsigned, rowSha256: digest("dsa-seats:ca-primary-joint-review-row:v1\0", unsigned) };
  }).sort((a, b) => bytewise(a.reviewRecordId, b.reviewRecordId));
  if (geographyByContest.size !== 156 || new Set(records.map((value) => value.contestId)).size !== 126) throw new Error("CA_PRIMARY_JOINT_CLOSURE_INVALID");
  const unsigned = { schema: "california-primary-identity-geography-review-package-v1" as const, version: 1 as const, generatedAt: "2026-08-06T20:00:00.000Z" as const, sourceCutoff: "2026-08-05" as const, reviewerOnly: true as const, publicationEligible: false as const, defaultUse: "exclude_from_evaluator_until_independent_identity_geography_and_top_two_review" as const, review: { status: "proposed" as const, reviewer: null, reviewedAt: null, resolution: null }, inputs: { sourceSelectionProposal: { sourceLockId: "house-democratic-primary-source-selection-proposal-20260804-v1" as const, fileSha256: INPUTS.proposalFile, packageSha256: INPUTS.proposalPackage }, identityCandidate: { sourceLockId: "california-current-incumbent-primary-linkage-candidate-v1" as const, fileSha256: INPUTS.identityFile, packageSha256: INPUTS.identityPackage, linkSetSha256: INPUTS.identitySet }, geographyCandidate: { sourceLockId: "california-primary-geography-compatibility-candidate-v1" as const, fileSha256: INPUTS.geographyFile, packageSha256: INPUTS.geographyPackage, rowSetSha256: INPUTS.geographySet } }, methodology: { scope: "exact_126_california_target_identity_rows_joined_to_matching_geography_rows" as const, identityAndGeographyReviewedIndependently: true as const, jointPackageApprovesParents: false as const, automaticApprovals: 0 as const, evaluatorNumericValues: 0 as const }, summary: { reviewRecords: 126 as const, identityAndGeographyCandidates: 76 as const, geographyCandidateIdentityUnresolved: 8 as const, identityCandidateCd120GeographyPending: 38 as const, identityUnresolvedCd120GeographyPending: 4 as const, identityCandidates: 114 as const, geographyCandidates: 84 as const, jointApprovedRecords: 0 as const, scoreEligibleRecords: 0 as const }, records, reviewRecordSetSha256: digest("dsa-seats:ca-primary-joint-review-row-set:v1\0", records), decisionSupport: { identityDecisionId: "approve-historic-primary-candidate-identity-resolution-v1" as const, geographyDecisionId: "approve-historical-district-cd119-compatibility-v1" as const, topTwoDecisionId: "decide-nonstandard-primary-disposition-treatment-v1" as const, resolutions: { identity: null, geography: null, topTwo: null }, lifecycle: "review_queue_for_bound_existing_decisions_not_an_independent_decision" as const } };
  return validateCaliforniaPrimaryIdentityGeographyReviewPackage({ ...unsigned, packageSha256: digest("dsa-seats:ca-primary-joint-review-package:v1\0", unsigned) });
}

export function validateCaliforniaPrimaryIdentityGeographyReviewPackage(value: unknown): CaliforniaPrimaryIdentityGeographyReviewPackage {
  const parsed = californiaPrimaryIdentityGeographyReviewPackageSchema.parse(value), { packageSha256, ...unsigned } = parsed;
  if (parsed.reviewRecordSetSha256 !== digest("dsa-seats:ca-primary-joint-review-row-set:v1\0", parsed.records) || packageSha256 !== digest("dsa-seats:ca-primary-joint-review-package:v1\0", unsigned) || (EXPECTED_PACKAGE && packageSha256 !== EXPECTED_PACKAGE)) throw new Error("CA_PRIMARY_JOINT_PACKAGE_HASH_MISMATCH");
  const counts = new Map<string, number>();
  if (parsed.records.some((value, index) => { const { rowSha256, ...rowUnsigned } = value; counts.set(value.reviewCategory, (counts.get(value.reviewCategory) ?? 0) + 1); return rowSha256 !== digest("dsa-seats:ca-primary-joint-review-row:v1\0", rowUnsigned) || (index > 0 && bytewise(parsed.records[index - 1]!.reviewRecordId, value.reviewRecordId) >= 0) || value.identity.approved || value.geography.approved || value.jointApproved || value.scoreEligible || value.nominationSystem !== "top_two_open_primary" || value.formulaApplicability !== "confirmed_incompatible_with_party_primary_metrics" || value.identity.candidate !== (value.identity.relationshipDisposition === "proposed_identity_link_pending_documented_review") || value.geography.candidate !== (value.geography.confidence === "high"); })) throw new Error("CA_PRIMARY_JOINT_ROW_INVALID");
  if (counts.get("identity_and_geography_candidates") !== 76 || counts.get("geography_candidate_identity_unresolved") !== 8 || counts.get("identity_candidate_cd120_geography_pending") !== 38 || counts.get("identity_unresolved_cd120_geography_pending") !== 4) throw new Error("CA_PRIMARY_JOINT_SUMMARY_INVALID"); return parsed;
}
