/* eslint-disable @typescript-eslint/no-explicit-any -- adversarial immutable-package mutations */
import { createHash } from "node:crypto";
import { readFileSync } from "node:fs";
import { describe, expect, it } from "vitest";
import { canonicalJson } from "../fec/aipac-proposed-packages";
import { buildCaliforniaPrimaryIdentityGeographyReviewPackage, validateCaliforniaPrimaryIdentityGeographyReviewPackage } from "./california-primary-identity-geography-review-package";

const read = (path: string) => { const bytes = readFileSync(path); return { bytes, sha256: createHash("sha256").update(bytes).digest("hex") }; };
const json = (path: string) => { const value = read(path); return { ...value, parsed: JSON.parse(value.bytes.toString("utf8")) }; };
const digest = (domain: string, value: unknown): string => createHash("sha256").update(domain).update(canonicalJson(value)).digest("hex");
const build = (sourceLockOverride?: unknown) => { const proposal = json("data/metadata/house-democratic-primary-source-selection-proposal-20260804-v1.json"), identity = json("data/metadata/california-current-incumbent-primary-linkage-candidate-v1.json"), geography = json("data/metadata/california-primary-geography-compatibility-candidate-v1.json"), lock = json("data/source-lock.json"); return buildCaliforniaPrimaryIdentityGeographyReviewPackage({ proposal: proposal.parsed, proposalFileSha256: proposal.sha256, identity: identity.parsed, identityFileSha256: identity.sha256, geography: geography.parsed, geographyFileSha256: geography.sha256, sourceLock: sourceLockOverride ?? lock.parsed }); };

describe("California primary identity-geography joint review package", () => {
  it("rebuilds the retained package exactly", () => { expect(build()).toEqual(json("data/metadata/california-primary-identity-geography-review-package-v1.json").parsed); });
  it("closes all reviewer categories without approval or scoring", () => { const value = build(); expect(value.summary).toEqual({ reviewRecords: 126, identityAndGeographyCandidates: 76, geographyCandidateIdentityUnresolved: 8, identityCandidateCd120GeographyPending: 38, identityUnresolvedCd120GeographyPending: 4, identityCandidates: 114, geographyCandidates: 84, jointApprovedRecords: 0, scoreEligibleRecords: 0 }); expect(value.records.every((row) => !row.identity.approved && !row.geography.approved && !row.jointApproved && !row.scoreEligible)).toBe(true); });
  it("keeps CD120 pending independently of identity evidence", () => { const value = build(), cd120 = value.records.filter((row) => row.cycleYear === 2026); expect(cd120).toHaveLength(42); expect(cd120.every((row) => !row.geography.candidate && row.geography.historicalGeoid === null)).toBe(true); expect(cd120.filter((row) => row.identity.candidate)).toHaveLength(38); expect(cd120.filter((row) => !row.identity.candidate)).toHaveLength(4); });
  it("keeps top-two formulas excluded across the joined queue", () => { expect(build().records.every((row) => row.nominationSystem === "top_two_open_primary" && row.formulaApplicability === "confirmed_incompatible_with_party_primary_metrics" && row.evaluatorUse === "excluded_pending_authorized_identity_geography_and_top_two_review")).toBe(true); });
  it("rejects parent source-lock substitution and fabricated review", () => { const lock: any = json("data/source-lock.json").parsed, wrong = structuredClone(lock); wrong.entries.find((entry: any) => entry.id === "california-primary-geography-compatibility-candidate-v1").kind = "published_release"; expect(() => build(wrong)).toThrow("CA_PRIMARY_JOINT_SOURCE_LOCK_MISMATCH"); const reviewed: any = build(); reviewed.review.reviewer = "fabricated"; expect(() => validateCaliforniaPrimaryIdentityGeographyReviewPackage(reviewed)).toThrow(); });
  it("rejects a fully rehashed review-category substitution", () => { const value: any = build(); value.records[0].reviewCategory = "identity_candidate_cd120_geography_pending"; const row = { ...value.records[0] }; delete row.rowSha256; value.records[0].rowSha256 = digest("dsa-seats:ca-primary-joint-review-row:v1\0", row); value.reviewRecordSetSha256 = digest("dsa-seats:ca-primary-joint-review-row-set:v1\0", value.records); const unsigned = { ...value }; delete unsigned.packageSha256; value.packageSha256 = digest("dsa-seats:ca-primary-joint-review-package:v1\0", unsigned); expect(() => validateCaliforniaPrimaryIdentityGeographyReviewPackage(value)).toThrow("CA_PRIMARY_JOINT_PACKAGE_HASH_MISMATCH"); });
});
