import { createHash } from "node:crypto";
import { z } from "zod";
import { canonicalJson } from "../fec/aipac-proposed-packages";
import { validateCaliforniaHouseTopTwoResultsReceipt, type CaliforniaHouseTopTwoResultsReceipt } from "./california-house-top-two-results-receipt";
import { validateHouseDemocraticPrimarySourceSelectionProposal } from "./house-democratic-primary-source-selection-proposal";

const SHA = z.string().regex(/^[a-f0-9]{64}$/);
const INPUTS = {
  proposalFile: "85246e9adfd181e6f24606b6eaa29250c45c9e8e42a6dd5af5cb162de17f45b1",
  proposalPackage: "a090e0be03dc2b0fa5edd0c1132a8261eed0f98ceb4df090154d0b150d8721fb",
  receiptFile: "43105ff6911374e0dd12dc2945ef8aa998681e08201de816c7926182a1a60963",
  receiptPackage: "554eaaa45f2fe80decbcb078579470e72e76673b2356c17bb8a6283af4460e72",
  receiptSet: "39c1fce31143fad62a01704ed6238b5493e460a6317075b6135b112e47524eb8",
  authorityFile: "66a0551a6c3c6432bff0a6a6db23f221fbe02ead1d15221d7050633898914670",
  ca118File: "7b53f26c7650090b75ef7af3d7087eaea2d62c4a3a3bd38b7dd2ac3a79c789b5",
  ca118Dbf: "d4508c22a6d58122a30b627cf79f65c577d6e3f75ef9464b1a57e4f5427e9819",
  ca119File: "107a5178d53c1c741b5e0fac48295a5f7a9424d516e246a44a34667c111c5481",
  ca119Dbf: "785cf34f86ee52089d4d60b8b7448e978bd1c92b9aa8e361fce16ba096c918a5",
} as const;
const EXPECTED_PACKAGE = "59ee4593076e81829dbb576f70230b0c50744d473c80c57b050ce5e9884b3f94";
const digest = (domain: string, value: unknown): string => createHash("sha256").update(domain).update(canonicalJson(value)).digest("hex");
const fileDigest = (value: Buffer | string): string => createHash("sha256").update(value).digest("hex");
const bytewise = (a: string, b: string): number => Buffer.compare(Buffer.from(a), Buffer.from(b));

function parseDbf(bytes: Buffer): ReadonlyArray<Readonly<Record<string, string>>> {
  if (bytes.length < 65 || bytes[0] !== 0x03) throw new Error("CA_PRIMARY_GEOGRAPHY_DBF_HEADER_INVALID");
  const count = bytes.readUInt32LE(4), headerLength = bytes.readUInt16LE(8), recordLength = bytes.readUInt16LE(10);
  if (count < 1 || headerLength < 65 || recordLength < 2 || headerLength + count * recordLength > bytes.length) throw new Error("CA_PRIMARY_GEOGRAPHY_DBF_LAYOUT_INVALID");
  const fields: { name: string; length: number; offset: number }[] = []; let offset = 1;
  for (let cursor = 32; cursor + 32 <= headerLength && bytes[cursor] !== 0x0d; cursor += 32) {
    const name = bytes.subarray(cursor, cursor + 11).toString("ascii").replace(/\0.*$/, "").trim(), length = bytes[cursor + 16]!;
    if (!name || length < 1) throw new Error("CA_PRIMARY_GEOGRAPHY_DBF_FIELD_INVALID");
    fields.push({ name, length, offset }); offset += length;
  }
  if (!fields.length || offset !== recordLength || bytes[headerLength - 1] !== 0x0d) throw new Error("CA_PRIMARY_GEOGRAPHY_DBF_FIELDS_INVALID");
  return Array.from({ length: count }, (_, index) => {
    const start = headerLength + index * recordLength;
    if (bytes[start] !== 0x20) throw new Error("CA_PRIMARY_GEOGRAPHY_DBF_DELETED_RECORD");
    return Object.fromEntries(fields.map((field) => [field.name, bytes.subarray(start + field.offset, start + field.offset + field.length).toString("ascii").trim()]));
  });
}

type InventoryRow = Readonly<{ geoid: string; districtCode: string; cdSession: "118" | "119"; landArea: number; waterArea: number }>;
export function parseCaliforniaTigerDistrictDbf(bytes: Buffer, cdSession: "118" | "119"): readonly InventoryRow[] {
  const historical = cdSession === "118", stateField = historical ? "STATEFP20" : "STATEFP", geoidField = historical ? "GEOID20" : "GEOID", districtField = historical ? "CD118FP" : "CD119FP", landField = historical ? "ALAND20" : "ALAND", waterField = historical ? "AWATER20" : "AWATER";
  const rows = parseDbf(bytes).map((value) => ({ geoid: value[geoidField]!, districtCode: value[districtField]!, cdSession: value.CDSESSN as "118" | "119", landArea: Number(value[landField]), waterArea: Number(value[waterField]), stateFips: value[stateField] })).sort((a, b) => bytewise(a.geoid, b.geoid));
  const codes = Array.from({ length: 52 }, (_, index) => String(index + 1).padStart(2, "0"));
  if (rows.length !== 52 || rows.some((value, index) => value.stateFips !== "06" || value.cdSession !== cdSession || value.districtCode !== codes[index] || value.geoid !== `06${value.districtCode}` || !Number.isSafeInteger(value.landArea) || value.landArea <= 0 || !Number.isSafeInteger(value.waterArea) || value.waterArea < 0)) throw new Error("CA_PRIMARY_GEOGRAPHY_TIGER_INVENTORY_INVALID");
  return rows.map((value) => ({ geoid: value.geoid, districtCode: value.districtCode, cdSession: value.cdSession, landArea: value.landArea, waterArea: value.waterArea }));
}

const layer = z.strictObject({ sourceLockId: z.string(), fileSha256: SHA, dbfMemberSha256: SHA, cdSession: z.enum(["118", "119"]), districtCount: z.literal(52), districtInventorySha256: SHA });
const row = z.strictObject({
  contestId: z.string(), contestSha256: SHA, seatCycleId: z.string(), districtCode: z.string().regex(/^\d{2}$/), cycleYear: z.union([z.literal(2022), z.literal(2024), z.literal(2026)]), targetCd119Geoid: z.string().regex(/^06\d{2}$/), historicalCongressSession: z.enum(["118", "119", "120"]), historicalGeoid: z.string().regex(/^06\d{2}$/).nullable(),
  compatibilityDisposition: z.enum(["official_no_plan_change_declaration_same_geoid_key_candidate", "same_cd119_session_and_geoid_exact_key_candidate", "unassessed_cd120_authority_collection_pending"]), evidenceClass: z.enum(["direct_official_plan_continuity_and_derived_key", "derived_exact_session_and_key", "authority_pending"]), confidence: z.enum(["high", "none"]), compatibilityCandidate: z.boolean(), compatibilityApproved: z.literal(false), identityApproved: z.literal(false), formulaApplicability: z.literal("confirmed_incompatible_with_party_primary_metrics"), evaluatorUse: z.literal("excluded_pending_authorized_identity_historical_geography_and_top_two_review"), scoreEligible: z.literal(false), rationaleCodes: z.array(z.string()).min(1), rowSha256: SHA,
});
export const californiaPrimaryGeographyCompatibilityCandidateSchema = z.strictObject({
  schema: z.literal("california-primary-geography-compatibility-candidate-v1"), version: z.literal(1), generatedAt: z.literal("2026-08-06T18:00:00.000Z"), sourceCutoff: z.literal("2026-08-05"), reviewerOnly: z.literal(true), publicationEligible: z.literal(false), defaultUse: z.literal("exclude_from_evaluator_until_authorized_identity_historical_geography_and_top_two_review"), review: z.strictObject({ status: z.literal("proposed"), reviewer: z.null(), reviewedAt: z.null(), resolution: z.null() }),
  inputs: z.strictObject({ sourceSelectionProposal: z.strictObject({ sourceLockId: z.literal("house-democratic-primary-source-selection-proposal-20260804-v1"), fileSha256: z.literal(INPUTS.proposalFile), packageSha256: z.literal(INPUTS.proposalPackage), informedDecisionId: z.literal("approve-historical-district-cd119-compatibility-v1"), decisionUnresolved: z.literal(true) }), californiaReceipt: z.strictObject({ sourceLockId: z.literal("california-house-top-two-results-2022-2026-v1"), fileSha256: z.literal(INPUTS.receiptFile), packageSha256: z.literal(INPUTS.receiptPackage), contestSetSha256: z.literal(INPUTS.receiptSet) }), censusPlanChangeAuthority: z.strictObject({ sourceLockId: z.literal("census-cd119-plan-change-authority-20260805"), fileSha256: z.literal(INPUTS.authorityFile), authorityClaim: z.literal("five_states_redrew_for_cd119_al_ga_la_ny_nc_ca_absent") }), tigerLayers: z.array(layer).length(2) }),
  methodology: z.strictObject({ targetSession: z.literal("119"), cycleSessionMapping: z.strictObject({ "2022": z.literal("118"), "2024": z.literal("119"), "2026": z.literal("120") }), planContinuityRule: z.literal("official_census_redraw_scope_declaration_plus_same_state_district_key"), exactSameSessionRule: z.literal("same_cd119_session_state_and_district_geoid"), cd120Rule: z.literal("remain_unassessed_until_authoritative_cd120_plan_evidence_is_retained"), rawTigerGeometryEqualityAssessed: z.literal(false), overlapThresholdUsed: z.literal(false), automaticDecisionClosure: z.literal(false), evaluatorNumericValues: z.literal(0) }),
  summary: z.strictObject({ contestCycleObservations: z.literal(156), cd118ToCd119PlanContinuityCandidates: z.literal(52), exactCd119SessionKeyCandidates: z.literal(52), cd120AuthorityPending: z.literal(52), compatibilityCandidates: z.literal(104), automaticallyApprovedRows: z.literal(0), scoreEligibleRows: z.literal(0) }), rows: z.array(row).length(156), rowSetSha256: SHA,
  decisionSupport: z.strictObject({ informsDecisionId: z.literal("approve-historical-district-cd119-compatibility-v1"), analysisConclusion: z.literal("official_evidence_supports_ca_cd118_to_cd119_plan_continuity_and_exact_cd119_keys_while_cd120_remains_unassessed"), lifecycle: z.literal("evidence_for_bound_existing_decision_not_an_independent_decision") }), packageSha256: SHA,
});
export type CaliforniaPrimaryGeographyCompatibilityCandidate = z.infer<typeof californiaPrimaryGeographyCompatibilityCandidateSchema>;

type BuildInput = Readonly<{ proposal: unknown; proposalFileSha256: string; receipt: unknown; receiptFileSha256: string; authorityHtml: string; authorityFileSha256: string; ca118Dbf: Buffer; ca118FileSha256: string; ca119Dbf: Buffer; ca119FileSha256: string; sourceLock: unknown }>;
export function buildCaliforniaPrimaryGeographyCompatibilityCandidate(input: BuildInput): CaliforniaPrimaryGeographyCompatibilityCandidate {
  const files = [input.proposalFileSha256, input.receiptFileSha256, input.authorityFileSha256, input.ca118FileSha256, input.ca119FileSha256], expected = [INPUTS.proposalFile, INPUTS.receiptFile, INPUTS.authorityFile, INPUTS.ca118File, INPUTS.ca119File];
  if (files.some((value, index) => value !== expected[index]) || fileDigest(input.authorityHtml) !== INPUTS.authorityFile || fileDigest(input.ca118Dbf) !== INPUTS.ca118Dbf || fileDigest(input.ca119Dbf) !== INPUTS.ca119Dbf) throw new Error("CA_PRIMARY_GEOGRAPHY_INPUT_HASH_MISMATCH");
  const proposal = validateHouseDemocraticPrimarySourceSelectionProposal(input.proposal), receipt = validateCaliforniaHouseTopTwoResultsReceipt(input.receipt as CaliforniaHouseTopTwoResultsReceipt), decision = proposal.decisions.find((value) => value.decisionId === "approve-historical-district-cd119-compatibility-v1");
  if (proposal.packageSha256 !== INPUTS.proposalPackage || receipt.packageSha256 !== INPUTS.receiptPackage || receipt.summary.contestSetSha256 !== INPUTS.receiptSet || !decision || decision.resolution !== null || receipt.review.resolution !== null) throw new Error("CA_PRIMARY_GEOGRAPHY_PARENT_INVALID");
  const phrase = "five states (Alabama, Georgia, Louisiana, New York, and North Carolina) that redrew their congressional district plans for the 119th Congress";
  if (!input.authorityHtml.includes(phrase) || input.authorityHtml.includes("five states (Alabama, California")) throw new Error("CA_PRIMARY_GEOGRAPHY_AUTHORITY_INVALID");
  const inventories = [parseCaliforniaTigerDistrictDbf(input.ca118Dbf, "118"), parseCaliforniaTigerDistrictDbf(input.ca119Dbf, "119")], layerSpecs = [["tiger-cd118-06", INPUTS.ca118File, INPUTS.ca118Dbf, "118"], ["tiger-cd119-06", INPUTS.ca119File, INPUTS.ca119Dbf, "119"]] as const;
  const tigerLayers = layerSpecs.map(([sourceLockId, fileSha256, dbfMemberSha256, cdSession], index) => ({ sourceLockId, fileSha256, dbfMemberSha256, cdSession, districtCount: 52 as const, districtInventorySha256: digest("dsa-seats:tiger-district-inventory:v1\0", inventories[index]) }));
  const lock = z.object({ entries: z.array(z.object({ id: z.string(), retainedPath: z.string().nullable().optional(), retainedStatus: z.string(), sha256: SHA, kind: z.string() })) }).parse(input.sourceLock), required = [["house-democratic-primary-source-selection-proposal-20260804-v1", INPUTS.proposalFile, "data/metadata/house-democratic-primary-source-selection-proposal-20260804-v1.json", "review_proposal"], ["california-house-top-two-results-2022-2026-v1", INPUTS.receiptFile, "data/metadata/california-house-top-two-results-2022-2026-v1.json", "review_candidate"], ["census-cd119-plan-change-authority-20260805", INPUTS.authorityFile, "data/source/elections/primary-results/geography/census-119-congressional-district-bef.html", "source"], ["tiger-cd118-06", INPUTS.ca118File, "data/source/tiger2022/tl_2022_06_cd118.zip", "source"], ["tiger-cd119-06", INPUTS.ca119File, "data/source/tiger2025/tl_2025_06_cd119.zip", "source"]] as const;
  if (required.some(([id, sha256, path, kind]) => { const matches = lock.entries.filter((entry) => entry.id === id); return matches.length !== 1 || matches[0]!.retainedStatus !== "retained" || matches[0]!.sha256 !== sha256 || matches[0]!.retainedPath !== path || matches[0]!.kind !== kind; })) throw new Error("CA_PRIMARY_GEOGRAPHY_SOURCE_LOCK_MISMATCH");
  const inventoryKeys = new Set(inventories.flatMap((values) => values.map((value) => `${value.cdSession}:${value.geoid}`)));
  const rows = receipt.contests.map((contest) => {
    const targetCd119Geoid = `06${contest.districtCode}`, historicalCongressSession = contest.cycleYear === 2022 ? "118" as const : contest.cycleYear === 2024 ? "119" as const : "120" as const, historicalGeoid = contest.cycleYear === 2026 ? null : targetCd119Geoid, compatible = contest.cycleYear !== 2026;
    if (!inventoryKeys.has(`119:${targetCd119Geoid}`) || (historicalGeoid && !inventoryKeys.has(`${historicalCongressSession}:${historicalGeoid}`))) throw new Error("CA_PRIMARY_GEOGRAPHY_CONTEST_OUTSIDE_TIGER_CLOSURE");
    const unsigned = { contestId: contest.contestId, contestSha256: contest.contestSha256, seatCycleId: `seat_house_ca_${contest.districtCode}_current`, districtCode: contest.districtCode, cycleYear: contest.cycleYear, targetCd119Geoid, historicalCongressSession, historicalGeoid, compatibilityDisposition: contest.cycleYear === 2022 ? "official_no_plan_change_declaration_same_geoid_key_candidate" as const : contest.cycleYear === 2024 ? "same_cd119_session_and_geoid_exact_key_candidate" as const : "unassessed_cd120_authority_collection_pending" as const, evidenceClass: contest.cycleYear === 2022 ? "direct_official_plan_continuity_and_derived_key" as const : contest.cycleYear === 2024 ? "derived_exact_session_and_key" as const : "authority_pending" as const, confidence: compatible ? "high" as const : "none" as const, compatibilityCandidate: compatible, compatibilityApproved: false as const, identityApproved: false as const, formulaApplicability: "confirmed_incompatible_with_party_primary_metrics" as const, evaluatorUse: "excluded_pending_authorized_identity_historical_geography_and_top_two_review" as const, scoreEligible: false as const, rationaleCodes: contest.cycleYear === 2022 ? ["official_census_cd119_redraw_list_excludes_ca", "same_state_district_geoid_in_cd118_and_cd119_inventory"] : contest.cycleYear === 2024 ? ["same_cd119_congressional_session", "same_state_district_geoid_in_cd119_inventory"] : ["cd120_authority_not_yet_retained", "do_not_assume_cd119_continuity_for_2026"] };
    return { ...unsigned, rowSha256: digest("dsa-seats:ca-primary-geography-row:v1\0", unsigned) };
  }).sort((a, b) => bytewise(a.contestId, b.contestId));
  const unsigned = { schema: "california-primary-geography-compatibility-candidate-v1" as const, version: 1 as const, generatedAt: "2026-08-06T18:00:00.000Z" as const, sourceCutoff: "2026-08-05" as const, reviewerOnly: true as const, publicationEligible: false as const, defaultUse: "exclude_from_evaluator_until_authorized_identity_historical_geography_and_top_two_review" as const, review: { status: "proposed" as const, reviewer: null, reviewedAt: null, resolution: null }, inputs: { sourceSelectionProposal: { sourceLockId: "house-democratic-primary-source-selection-proposal-20260804-v1" as const, fileSha256: INPUTS.proposalFile, packageSha256: INPUTS.proposalPackage, informedDecisionId: "approve-historical-district-cd119-compatibility-v1" as const, decisionUnresolved: true as const }, californiaReceipt: { sourceLockId: "california-house-top-two-results-2022-2026-v1" as const, fileSha256: INPUTS.receiptFile, packageSha256: INPUTS.receiptPackage, contestSetSha256: INPUTS.receiptSet }, censusPlanChangeAuthority: { sourceLockId: "census-cd119-plan-change-authority-20260805" as const, fileSha256: INPUTS.authorityFile, authorityClaim: "five_states_redrew_for_cd119_al_ga_la_ny_nc_ca_absent" as const }, tigerLayers }, methodology: { targetSession: "119" as const, cycleSessionMapping: { "2022": "118" as const, "2024": "119" as const, "2026": "120" as const }, planContinuityRule: "official_census_redraw_scope_declaration_plus_same_state_district_key" as const, exactSameSessionRule: "same_cd119_session_state_and_district_geoid" as const, cd120Rule: "remain_unassessed_until_authoritative_cd120_plan_evidence_is_retained" as const, rawTigerGeometryEqualityAssessed: false as const, overlapThresholdUsed: false as const, automaticDecisionClosure: false as const, evaluatorNumericValues: 0 as const }, summary: { contestCycleObservations: 156 as const, cd118ToCd119PlanContinuityCandidates: 52 as const, exactCd119SessionKeyCandidates: 52 as const, cd120AuthorityPending: 52 as const, compatibilityCandidates: 104 as const, automaticallyApprovedRows: 0 as const, scoreEligibleRows: 0 as const }, rows, rowSetSha256: digest("dsa-seats:ca-primary-geography-row-set:v1\0", rows), decisionSupport: { informsDecisionId: "approve-historical-district-cd119-compatibility-v1" as const, analysisConclusion: "official_evidence_supports_ca_cd118_to_cd119_plan_continuity_and_exact_cd119_keys_while_cd120_remains_unassessed" as const, lifecycle: "evidence_for_bound_existing_decision_not_an_independent_decision" as const } };
  return validateCaliforniaPrimaryGeographyCompatibilityCandidate({ ...unsigned, packageSha256: digest("dsa-seats:ca-primary-geography-candidate:v1\0", unsigned) });
}

export function validateCaliforniaPrimaryGeographyCompatibilityCandidate(value: unknown): CaliforniaPrimaryGeographyCompatibilityCandidate {
  const parsed = californiaPrimaryGeographyCompatibilityCandidateSchema.parse(value), { packageSha256, ...unsigned } = parsed;
  if (parsed.rowSetSha256 !== digest("dsa-seats:ca-primary-geography-row-set:v1\0", parsed.rows) || packageSha256 !== digest("dsa-seats:ca-primary-geography-candidate:v1\0", unsigned) || (EXPECTED_PACKAGE && packageSha256 !== EXPECTED_PACKAGE)) throw new Error("CA_PRIMARY_GEOGRAPHY_PACKAGE_HASH_MISMATCH");
  if (parsed.rows.some((value, index) => { const { rowSha256, ...rowUnsigned } = value; return rowSha256 !== digest("dsa-seats:ca-primary-geography-row:v1\0", rowUnsigned) || (index > 0 && bytewise(parsed.rows[index - 1]!.contestId, value.contestId) >= 0) || value.compatibilityApproved || value.identityApproved || value.scoreEligible || value.formulaApplicability !== "confirmed_incompatible_with_party_primary_metrics" || (value.cycleYear === 2026 ? value.historicalGeoid !== null || value.compatibilityCandidate || value.confidence !== "none" : value.historicalGeoid !== value.targetCd119Geoid || !value.compatibilityCandidate || value.confidence !== "high"); })) throw new Error("CA_PRIMARY_GEOGRAPHY_ROW_INVALID");
  return parsed;
}
