/* eslint-disable @typescript-eslint/no-explicit-any -- adversarial immutable-candidate mutations */
import { createHash } from "node:crypto";
import { execFileSync } from "node:child_process";
import { readFileSync } from "node:fs";
import { describe, expect, it } from "vitest";
import { canonicalJson } from "../fec/aipac-proposed-packages";
import { buildCaliforniaPrimaryGeographyCompatibilityCandidate, validateCaliforniaPrimaryGeographyCompatibilityCandidate } from "./california-primary-geography-compatibility-candidate";

const read = (path: string) => { const bytes = readFileSync(path); return { bytes, sha256: createHash("sha256").update(bytes).digest("hex") }; };
const json = (path: string) => { const value = read(path); return { ...value, parsed: JSON.parse(value.bytes.toString("utf8")) }; };
const dbf = (path: string): Buffer => execFileSync("unzip", ["-p", path, "*.dbf"], { maxBuffer: 4 * 1024 * 1024 });
const digest = (domain: string, value: unknown): string => createHash("sha256").update(domain).update(canonicalJson(value)).digest("hex");
const build = (sourceLockOverride?: unknown) => {
  const proposal = json("data/metadata/house-democratic-primary-source-selection-proposal-20260804-v1.json"), receipt = json("data/metadata/california-house-top-two-results-2022-2026-v1.json"), authority = read("data/source/elections/primary-results/geography/census-119-congressional-district-bef.html"), ca118 = read("data/source/tiger2022/tl_2022_06_cd118.zip"), ca119 = read("data/source/tiger2025/tl_2025_06_cd119.zip"), lock = json("data/source-lock.json");
  return buildCaliforniaPrimaryGeographyCompatibilityCandidate({ proposal: proposal.parsed, proposalFileSha256: proposal.sha256, receipt: receipt.parsed, receiptFileSha256: receipt.sha256, authorityHtml: authority.bytes.toString("utf8"), authorityFileSha256: authority.sha256, ca118Dbf: dbf("data/source/tiger2022/tl_2022_06_cd118.zip"), ca118FileSha256: ca118.sha256, ca119Dbf: dbf("data/source/tiger2025/tl_2025_06_cd119.zip"), ca119FileSha256: ca119.sha256, sourceLock: sourceLockOverride ?? lock.parsed });
};

describe("California primary geography compatibility candidate", () => {
  it("rebuilds the retained candidate exactly", () => { expect(build()).toEqual(json("data/metadata/california-primary-geography-compatibility-candidate-v1.json").parsed); });
  it("closes all cycles without approval, scoring, or top-two conversion", () => { const value = build(); expect(value.summary).toEqual({ contestCycleObservations: 156, cd118ToCd119PlanContinuityCandidates: 52, exactCd119SessionKeyCandidates: 52, cd120AuthorityPending: 52, compatibilityCandidates: 104, automaticallyApprovedRows: 0, scoreEligibleRows: 0 }); expect(value.rows.every((row) => !row.compatibilityApproved && !row.identityApproved && !row.scoreEligible && row.formulaApplicability === "confirmed_incompatible_with_party_primary_metrics")).toBe(true); });
  it("separates CD118 continuity, exact CD119 keys, and CD120 pending authority", () => { const value = build(); expect(value.rows.filter((row) => row.cycleYear === 2022 && row.compatibilityDisposition === "official_no_plan_change_declaration_same_geoid_key_candidate")).toHaveLength(52); expect(value.rows.filter((row) => row.cycleYear === 2024 && row.compatibilityDisposition === "same_cd119_session_and_geoid_exact_key_candidate")).toHaveLength(52); expect(value.rows.filter((row) => row.cycleYear === 2026 && row.historicalGeoid === null && !row.compatibilityCandidate)).toHaveLength(52); });
  it("rejects wrong source-lock kind and source bytes", () => { const lock: any = json("data/source-lock.json").parsed, wrong = structuredClone(lock); wrong.entries.find((entry: any) => entry.id === "tiger-cd118-06").kind = "derived_artifact"; expect(() => build(wrong)).toThrow("CA_PRIMARY_GEOGRAPHY_SOURCE_LOCK_MISMATCH"); const proposal = json("data/metadata/house-democratic-primary-source-selection-proposal-20260804-v1.json"); expect(() => buildCaliforniaPrimaryGeographyCompatibilityCandidate({ proposal: proposal.parsed, proposalFileSha256: "0".repeat(64), receipt: {}, receiptFileSha256: "0".repeat(64), authorityHtml: "", authorityFileSha256: "0".repeat(64), ca118Dbf: Buffer.alloc(0), ca118FileSha256: "0".repeat(64), ca119Dbf: Buffer.alloc(0), ca119FileSha256: "0".repeat(64), sourceLock: {} })).toThrow("CA_PRIMARY_GEOGRAPHY_INPUT_HASH_MISMATCH"); });
  it("rejects fabricated lifecycle state", () => { const value: any = build(); value.review.reviewer = "fabricated"; expect(() => validateCaliforniaPrimaryGeographyCompatibilityCandidate(value)).toThrow(); value.review.reviewer = null; value.publicationEligible = true; expect(() => validateCaliforniaPrimaryGeographyCompatibilityCandidate(value)).toThrow(); });
  it("rejects a fully rehashed compatibility substitution", () => { const value: any = build(); value.rows[0].compatibilityDisposition = "same_cd119_session_and_geoid_exact_key_candidate"; const row = { ...value.rows[0] }; delete row.rowSha256; value.rows[0].rowSha256 = digest("dsa-seats:ca-primary-geography-row:v1\0", row); value.rowSetSha256 = digest("dsa-seats:ca-primary-geography-row-set:v1\0", value.rows); const unsigned = { ...value }; delete unsigned.packageSha256; value.packageSha256 = digest("dsa-seats:ca-primary-geography-candidate:v1\0", unsigned); expect(() => validateCaliforniaPrimaryGeographyCompatibilityCandidate(value)).toThrow("CA_PRIMARY_GEOGRAPHY_PACKAGE_HASH_MISMATCH"); });
});
