/* eslint-disable @typescript-eslint/no-explicit-any -- adversarial immutable-candidate mutations */
import { createHash } from "node:crypto";
import { readFileSync } from "node:fs";
import { describe, expect, it } from "vitest";
import { canonicalJson } from "../fec/aipac-proposed-packages";
import { buildCaliforniaCurrentIncumbentPrimaryLinkageCandidate, normalizeCaliforniaCandidateName, validateCaliforniaCurrentIncumbentPrimaryLinkageCandidate } from "./california-current-incumbent-primary-linkage-candidate";

const read = (path: string) => { const bytes = readFileSync(path); return { bytes, sha256: createHash("sha256").update(bytes).digest("hex") }; };
const json = (path: string) => { const value = read(path); return { ...value, parsed: JSON.parse(value.bytes.toString("utf8")) }; };
const digest = (domain: string, value: unknown): string => createHash("sha256").update(domain).update(canonicalJson(value)).digest("hex");
const build = (sourceLockOverride?: unknown) => { const roster = json("data/metadata/dsa-target-incumbent-roster-20260804-v1.json"), proposal = json("data/metadata/house-democratic-primary-source-selection-proposal-20260804-v1.json"), clerk = read("data/source/identity/house-member-data.xml"), congress = json("data/source/identity/congress-legislators-current-20260804.json"), receipt = json("data/metadata/california-house-top-two-results-2022-2026-v1.json"), lock = json("data/source-lock.json"); return buildCaliforniaCurrentIncumbentPrimaryLinkageCandidate({ roster: roster.parsed, rosterFileSha256: roster.sha256, proposal: proposal.parsed, proposalFileSha256: proposal.sha256, clerkXml: clerk.bytes.toString("utf8"), clerkFileSha256: clerk.sha256, congressCurrent: congress.parsed, congressCurrentFileSha256: congress.sha256, receipt: receipt.parsed, receiptFileSha256: receipt.sha256, sourceLock: sourceLockOverride ?? lock.parsed }); };

describe("California current-incumbent primary linkage candidate", () => {
  it("rebuilds the retained candidate exactly", () => { expect(build()).toEqual(json("data/metadata/california-current-incumbent-primary-linkage-candidate-v1.json").parsed); });
  it("closes 126 observations without direct identifiers, approval, or scoring", () => { const value = build(); expect(value.summary).toEqual({ targetSeats: 42, seatCycleObservations: 126, proposedLinks: 114, exactNameLinks: 92, derivedNameLinks: 21, inferredNameLinks: 1, unresolvedObservations: 12, directIdentifierLinks: 0, sourceIncumbentMarkerObservationsOnLinks: 33, automaticallyApprovedLinks: 0, scoreEligibleLinks: 0 }); expect(value.links.every((row) => !row.directIdentifierBridgeAvailable && !row.identityApproved && !row.scoreEligible)).toBe(true); });
  it("normalizes accents without promoting the sole first-name inference", () => { expect(normalizeCaliforniaCandidateName("Nanette Diaz Barragán")).toBe(normalizeCaliforniaCandidateName("Nanette Diaz Barragan")); const value = build(), ca44 = value.links.filter((row) => row.districtCode === "44" && [2022, 2026].includes(row.cycleYear)); expect(ca44.every((row) => row.evidenceClass === "exact_name_observation")).toBe(true); expect(value.links.filter((row) => row.evidenceClass === "inferred_name_relationship")).toEqual([expect.objectContaining({ districtCode: "37", cycleYear: 2022, sourceCandidate: expect.objectContaining({ sourceCandidateName: "Sydney Kamlager" }) })]); });
  it("preserves top-two and nonappearance boundaries", () => { const value = build(); expect(value.links.filter((row) => row.relationshipDisposition === "not_linked_no_unique_candidate")).toHaveLength(12); expect(value.links.every((row) => row.nominationSystem === "top_two_open_primary" && row.partyFieldMeaning === "candidate_qualified_party_preference" && row.sourceWinnerStatus === "not_marked_or_derived" && row.advancementStatus === "not_derived" && row.formulaApplicability === "confirmed_incompatible_with_party_primary_metrics")).toBe(true); });
  it("rejects source-lock substitution and fabricated lifecycle state", () => { const lock: any = json("data/source-lock.json").parsed, wrong = structuredClone(lock); wrong.entries.find((entry: any) => entry.id === "house-xml").kind = "review_candidate"; expect(() => build(wrong)).toThrow("CA_PRIMARY_LINKAGE_SOURCE_LOCK_MISMATCH"); const reviewed: any = build(); reviewed.review.reviewer = "fabricated"; expect(() => validateCaliforniaCurrentIncumbentPrimaryLinkageCandidate(reviewed)).toThrow(); });
  it("rejects a fully rehashed name substitution", () => { const value: any = build(), target = value.links.find((row: any) => row.sourceCandidate); target.sourceCandidate.sourceCandidateName = "SUBSTITUTED"; const row = { ...target }; delete row.rowSha256; target.rowSha256 = digest("dsa-seats:ca-current-incumbent-primary-link:v1\0", row); value.linkSetSha256 = digest("dsa-seats:ca-current-incumbent-primary-link-set:v1\0", value.links); const unsigned = { ...value }; delete unsigned.packageSha256; value.packageSha256 = digest("dsa-seats:ca-current-incumbent-primary-linkage-candidate:v1\0", unsigned); expect(() => validateCaliforniaCurrentIncumbentPrimaryLinkageCandidate(value)).toThrow("CA_PRIMARY_LINKAGE_PACKAGE_HASH_MISMATCH"); });
});
