import { createHash } from "node:crypto";
import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { describe, expect, it } from "vitest";

import { canonicalJson } from "../fec/aipac-proposed-packages";
import { buildConnecticutEventDispositionsReceipt, validateConnecticutEventDispositionsReceipt, type ConnecticutEventDispositionsReceipt } from "./connecticut-house-democratic-primary-event-dispositions-receipt";
import type { NewYorkSourceEntry } from "./new-york-house-democratic-primary-reported-results-receipt";

const lock = JSON.parse(readFileSync(resolve("data/source-lock.json"), "utf8")) as { entries: NewYorkSourceEntry[] };
const inputs = () => lock.entries.filter((entry) => /^ct-202[24]-primary-event-(?:discovery|\d+-results)-response$/.test(entry.id)).map((entry) => ({ entry, bytes: readFileSync(resolve(entry.retainedPath)) }));
const stored = () => JSON.parse(readFileSync(resolve("data/metadata/connecticut-house-democratic-primary-event-dispositions-2022-2024-v1.json"), "utf8")) as ConnecticutEventDispositionsReceipt;

describe("Connecticut Democratic House primary event disposition corpus", () => {
  it("proves complete event enumeration and no reported Democratic House contest", () => { const receipt = validateConnecticutEventDispositionsReceipt(buildConnecticutEventDispositionsReceipt(inputs())); expect(receipt.events.map((event) => [event.eventId, event.eventName, event.advertisedResultCount, event.enumeratedResultCount, event.democraticHouseResultCount])).toEqual([[598, "2022 Aug 09 - Primary", 17, 17, 0], [583, "2024 Aug 13 - Primary", 22, 22, 0]]); expect(receipt.summary).toEqual(expect.objectContaining({ events: 2, enumeratedResults: 39, democraticHouseResults: 0, seatCycles: 10, noReportedContestRows: 10, evaluatorNumericValues: 0, scoreEligibleRows: 0 })); });
  it("keeps nomination, contest selection, votes, and evaluator values unresolved", () => { const receipt = stored(); expect(receipt.rows).toHaveLength(10); expect(receipt.rows.every((row) => row.disposition === "no_reported_democratic_house_primary_contest_in_complete_official_event" && row.nominationDisposition === null && row.selectedContestId === null && row.voteValues === null && !row.scoreEligible && Object.values(row.evaluatorValues).every((value) => value === null))).toBe(true); });
  it("binds the exact POST request receipts and page-one completeness query", () => { const receipt = stored(); expect(receipt.requests).toHaveLength(4); expect(receipt.requests.every((request) => request.method === "POST" && request.endpoint === "https://electionhistory.ct.gov/api/graphql_pr" && request.headers["X-Elstats-Tenant"] === "ct")).toBe(true); const resultRequests = receipt.requests.filter((request) => (request.requestBody as { operationName?: string }).operationName === "GetLatestResults"); expect(resultRequests.every((request) => canonicalJson((request.requestBody as { variables: { pagination: unknown } }).variables.pagination) === canonicalJson({ page: 1, size: 100 }))).toBe(true); });
  it("rejects source drift and fully rehashed disposition overclaim", () => { const source = inputs(), changed = Buffer.from(source[0]!.bytes); changed[100] = changed[100]! ^ 1; expect(() => buildConnecticutEventDispositionsReceipt([{ ...source[0]!, bytes: changed }, ...source.slice(1)])).toThrow("SOURCE_RECEIPT_INVALID"); const receipt = structuredClone(stored()), row = receipt.rows[0]!; (row as unknown as { disposition: string }).disposition = "certified_uncontested"; const unsignedRow = { ...row } as Record<string, unknown>; delete unsignedRow.rowSha256; (row as unknown as { rowSha256: string }).rowSha256 = createHash("sha256").update("dsa-seats:ct-house-democratic-primary-event-disposition:v1\0", "ascii").update(canonicalJson(unsignedRow), "utf8").digest("hex"); (receipt.summary as unknown as { dispositionSetSha256: string }).dispositionSetSha256 = createHash("sha256").update("dsa-seats:ct-house-democratic-primary-event-disposition-set:v1\0", "ascii").update(canonicalJson(receipt.rows.map(({ seatCycleId, rowSha256 }) => ({ seatCycleId, rowSha256 }))), "utf8").digest("hex"); const unsigned = { ...receipt } as Record<string, unknown>; delete unsigned.packageSha256; (receipt as unknown as { packageSha256: string }).packageSha256 = createHash("sha256").update("dsa-seats:ct-house-democratic-primary-event-disposition-package:v1\0", "ascii").update(canonicalJson(unsigned), "utf8").digest("hex"); expect(() => validateConnecticutEventDispositionsReceipt(receipt)).toThrow("PACKAGE_INVARIANT_INVALID"); });
  it("matches the canonical checked-in artifact", () => { expect(buildConnecticutEventDispositionsReceipt(inputs())).toEqual(stored()); });
});
