/* eslint-disable @typescript-eslint/no-explicit-any -- source-lock JSON is runtime validated */
import { createHash } from "node:crypto";
import { canonicalJson } from "../fec/aipac-proposed-packages";

type Input={pdf2022:Buffer;pdf2022Sha256:string;text2022:string;pdf2024:Buffer;pdf2024Sha256:string;text2024:string;sourceLock:any};
type Row={observationId:string;cycleYear:2022|2024;districtCode:string;electionDate:"2022-11-08"|"2024-11-05";office:"Representative in Congress";partyLabel:"Democratic"|"Democratic Party";candidateName:string;democraticColumnVotes:number;generalElectionAppearanceStatus:"party_labeled_vote_column_present";electedDeclarationStatus:"not_present_in_retained_instrument"|"declared_elected_in_exact_scope_canvass";primaryNominationStatus:null;approved:false;evaluatorUse:"excluded_pending_primary_nomination_authority_and_review";scoreEligible:false;sourceLockId:string;rowSha256:string};
export type ConnecticutGeneralElectionCrosscheckReceipt=ReturnType<typeof buildConnecticutGeneralElectionCrosscheckReceipt>;
const FILES={"2022":"1b6ca3708890241c387320e68b5e628f27a3bbc08b83b0d172e5d7bd9183664b","2024":"1043dc18895adcff95e227e136eb19ef1c65f2a452a4dc97105fb4738cf3751c"} as const;
const sourceIds=["ct-2022-general-statement-of-vote","ct-2024-general-statement-of-vote"],SOURCE_SET="844bbbee79fc30ed31c327aa9ffd82ab3ba0a2f1ece710fadf10bc4f9855d5c0";
const ROW_SET="7551d497051ed040a41cdb5d7d7a886de02597a0da2e6c4958e35a0640cd3dda",PACKAGE="abe14776b5a5ff38a8a5fcc3d6cd5714d72a40d7ab2b338fe5912465fee9a2bc";
const outputLockEntry={id:"connecticut-general-election-crosscheck-receipt-v1",url:"urn:dsa-seats:connecticut-general-election-crosscheck-receipt:v1:2022-2024",retainedPath:"data/metadata/connecticut-general-election-crosscheck-receipt-v1.json",retainedStatus:"retained",byteSize:10581,sha256:"70e40dbad3ec17a4d7e8998e37c98033768450c8722f70e16ca3c1754ca6d3e1",kind:"review_evidence_receipt",parentIds:sourceIds};
const facts=[
  [2022,"01","John B. Larson",144873],[2022,"02","Joe Courtney",165946],[2022,"03","Rosa L. DeLauro",137924],[2022,"04","Jim Himes",140262],[2022,"05","Jahana Hayes",123818],
  [2024,"01","John B. Larson",197788],[2024,"02","Joe Courtney",218294],[2024,"03","Rosa L. DeLauro",193684],[2024,"04","Jim Himes",200791],[2024,"05","Jahana Hayes",171362],
] as const;
const summary={districtCycleRows:10 as const,democraticGeneralElectionAppearances:10 as const,democraticColumnVotes2022:712823 as const,democraticColumnVotes2024:981919 as const,electedDeclarationsPresent:5 as const,electedDeclarationsNotPresentInInstrument:5 as const,primaryNominationConclusions:0 as const,automaticallyApprovedRows:0 as const,scoreEligibleRows:0 as const};
const review={status:"proposed" as const,reviewer:null,reviewedAt:null,resolution:null};
const sha=(value:Buffer)=>createHash("sha256").update(value).digest("hex"),digest=(domain:string,value:unknown)=>createHash("sha256").update(domain,"ascii").update(canonicalJson(value),"utf8").digest("hex");
const fail=(code:string):never=>{throw new Error(`Connecticut general-election cross-check rejected: ${code}`);};
function section(text:string,year:2022|2024,district:string){const heading=year===2022?`Representative in Congress - District ${Number(district)}`:`Congressional District ${Number(district)}`,start=text.indexOf(heading);if(start<0)fail("DISTRICT_HEADING_MISSING");const nextDistrict=Number(district)+1,next=nextDistrict<=5?text.indexOf(year===2022?`Representative in Congress - District ${nextDistrict}`:`Congressional District ${nextDistrict}`,start+heading.length):-1;return text.slice(start,next<0?text.length:next);}
export function buildConnecticutGeneralElectionCrosscheckReceipt(input:Input){
  if(input.pdf2022Sha256!==FILES["2022"]||input.pdf2024Sha256!==FILES["2024"]||sha(input.pdf2022)!==FILES["2022"]||sha(input.pdf2024)!==FILES["2024"])fail("INPUT_HASH_MISMATCH");
  const sources=sourceIds.map(id=>{const matches=input.sourceLock.entries?.filter((entry:any)=>entry.id===id)??[];if(matches.length!==1)fail("SOURCE_LOCK_MISMATCH");return matches[0];});const outputMatches=input.sourceLock.entries?.filter((entry:any)=>entry.id===outputLockEntry.id)??[];if(digest("dsa-seats:ct-general-crosscheck-source-set:v1\0",sources)!==SOURCE_SET||outputMatches.length!==1||canonicalJson(outputMatches[0])!==canonicalJson(outputLockEntry))fail("SOURCE_LOCK_MISMATCH");
  if(input.text2022.includes("declare the following named persons elected REPRESENTATIVES")||!input.text2024.includes("declare the following named persons elected REPRESENTATIVES in the ONE HUNDRED")||!input.text2024.includes("NINETEENTH CONGRESS"))fail("CANVASS_SCOPE_INVALID");
  const declaration=input.text2024.slice(input.text2024.indexOf("declare the following named persons elected REPRESENTATIVES"));
  const rows:Row[]=facts.map(([cycleYear,districtCode,candidateName,votes])=>{const text=cycleYear===2022?input.text2022:input.text2024,fragment=section(text,cycleYear,districtCode),partyLabel=cycleYear===2022?"Democratic" as const:"Democratic Party" as const;if(!fragment.includes(candidateName)||!fragment.includes(partyLabel)||!new RegExp(`Totals?\\s+${votes.toLocaleString("en-US")}`).test(fragment)||(cycleYear===2024&&!declaration.includes(candidateName)))fail("RETAINED_OBSERVATION_MISSING");const unsigned={observationId:`ct-general-crosscheck:${cycleYear}:${districtCode}`,cycleYear,districtCode,electionDate:cycleYear===2022?"2022-11-08" as const:"2024-11-05" as const,office:"Representative in Congress" as const,partyLabel,candidateName,democraticColumnVotes:votes,generalElectionAppearanceStatus:"party_labeled_vote_column_present" as const,electedDeclarationStatus:cycleYear===2022?"not_present_in_retained_instrument" as const:"declared_elected_in_exact_scope_canvass" as const,primaryNominationStatus:null,approved:false as const,evaluatorUse:"excluded_pending_primary_nomination_authority_and_review" as const,scoreEligible:false as const,sourceLockId:`ct-${cycleYear}-general-statement-of-vote`};return{...unsigned,rowSha256:digest("dsa-seats:ct-general-crosscheck-row:v1\0",unsigned)};});
  const unsigned={schema:"connecticut-general-election-crosscheck-receipt-v1" as const,version:1 as const,generatedAt:"2026-08-06T11:30:00.000Z" as const,sourceCutoff:"2026-08-06" as const,reviewerOnly:true as const,publicationEligible:false as const,review,originalPublisher:"Connecticut Secretary of the State" as const,status:"official_general_election_result_and_cycle_specific_canvass_candidate" as const,sources,extraction:{tool:"pdftotext" as const,layoutMode:true as const,rawPdfRetained:true as const},summary,rows,rowSetSha256:digest("dsa-seats:ct-general-crosscheck-row-set:v1\0",rows),limitations:["General-election party appearance is a nominee cross-check, not independent proof of the earlier primary nomination mechanism.","Only the 2024 retained instrument contains the exact-scope elected declaration used here; no 2022 elected declaration is inferred."] as const,unresolvedGates:["retain_complete_final_democratic_primary_ballot_or_candidacy_universe","retain_statutory_nomination_authority_and_cancellation_status","approve_general_election_crosscheck","complete_human_review_and_publication_approval"] as const};return{...unsigned,packageSha256:digest("dsa-seats:ct-general-crosscheck-package:v1\0",unsigned)};
}
export function validateConnecticutGeneralElectionCrosscheckReceipt(value:ConnecticutGeneralElectionCrosscheckReceipt){const{packageSha256,...unsigned}=value;if(packageSha256!==PACKAGE||packageSha256!==digest("dsa-seats:ct-general-crosscheck-package:v1\0",unsigned)||value.rowSetSha256!==ROW_SET||value.schema!=="connecticut-general-election-crosscheck-receipt-v1"||!value.reviewerOnly||value.publicationEligible||canonicalJson(value.review)!==canonicalJson(review)||canonicalJson(value.summary)!==canonicalJson(summary)||digest("dsa-seats:ct-general-crosscheck-source-set:v1\0",value.sources)!==SOURCE_SET||value.rows.length!==10||value.rowSetSha256!==digest("dsa-seats:ct-general-crosscheck-row-set:v1\0",value.rows))fail("PACKAGE_INVALID");if(value.rows.some((row,index)=>{const unsignedRow={...row} as Partial<Row>;delete unsignedRow.rowSha256;const [cycle,district,name,votes]=facts[index]!;return row.observationId!==`ct-general-crosscheck:${cycle}:${district}`||row.cycleYear!==cycle||row.districtCode!==district||row.candidateName!==name||row.democraticColumnVotes!==votes||row.generalElectionAppearanceStatus!=="party_labeled_vote_column_present"||row.electedDeclarationStatus!==(cycle===2022?"not_present_in_retained_instrument":"declared_elected_in_exact_scope_canvass")||row.primaryNominationStatus!==null||row.approved||row.scoreEligible||row.rowSha256!==digest("dsa-seats:ct-general-crosscheck-row:v1\0",unsignedRow);}))fail("ROW_INVALID");return value;}
