import { createHash } from "node:crypto";

import { canonicalJson } from "../fec/aipac-proposed-packages";
import type { NewYorkSourceEntry } from "./new-york-house-democratic-primary-reported-results-receipt";

export const CONNECTICUT_HOUSE_DEMOCRATIC_PRIMARY_EVENT_DISPOSITIONS_V1 = "connecticut-house-democratic-primary-event-dispositions-receipt-v1" as const;
export const CONNECTICUT_EVENT_DISPOSITION_SET_SHA256 = "5b2f083f3e693d78a7b4b232a7c677007e6c65eb9259109d59c8e45137cc3dcf" as const;
export const CONNECTICUT_EVENT_DISPOSITION_PACKAGE_SHA256 = "7dcaf4cea0d1a817ff863010bfc2c3fd45cafc1880f8ff2c3951cdf6b81cc257" as const;
type Cycle = 2022 | 2024;
type Bytes = Buffer | Uint8Array | string;
export type ConnecticutEventInput = Readonly<{ entry: NewYorkSourceEntry; bytes: Bytes }>;
type RequestReceipt = Readonly<{ sourceLockId: string; method: "POST"; endpoint: "https://electionhistory.ct.gov/api/graphql_pr"; headers: Readonly<{ "Content-Type": "application/json"; "X-Elstats-Tenant": "ct" }>; requestSha256: string; requestBody: unknown }>;
type EventEvidence = Readonly<{ cycleYear: Cycle; eventId: 598 | 583; eventName: "2022 Aug 09 - Primary" | "2024 Aug 13 - Primary"; eventGroup: "2022" | "2024"; advertisedResultCount: 17 | 22; enumeratedResultCount: 17 | 22; resultIds: readonly string[]; resultSetSha256: string; democraticHouseResultCount: 0; discoverySourceLockId: string; resultsSourceLockId: string }>;
type Row = Readonly<{ seatCycleId: string; cycleYear: Cycle; stateCode: "CT"; districtCode: string; party: "Democratic"; office: "U.S. Representative"; disposition: "no_reported_democratic_house_primary_contest_in_complete_official_event"; eventEvidenceId: string; nominationDisposition: null; selectedContestId: null; voteValues: null; scoreEligible: false; evaluatorValues: Readonly<{ priorPrimaryMargin: null; priorDemocraticPrimaryVotes: null; priorProgressivePrimaryShare: null }>; rowSha256: string }>;
export type ConnecticutEventDispositionsReceipt = Readonly<{ schema: typeof CONNECTICUT_HOUSE_DEMOCRATIC_PRIMARY_EVENT_DISPOSITIONS_V1; version: 1; generatedAt: "2026-08-05T19:00:00.000Z"; sourceCutoff: "2026-08-05"; reviewerOnly: true; publicationEligible: false; review: Readonly<{ status: "proposed"; reviewer: null; reviewedAt: null }>; originalPublisher: "Connecticut Secretary of the State historical election database"; status: "official_result_event_enumeration_candidate"; certificationStatus: "not_independently_retained"; licenseStatus: "unassessed"; authorityContextUrls: readonly ["https://portal.ct.gov/sots/election-services/election-results/election-results", "https://electionhistory.ct.gov/", "https://electionhistory.ct.gov/about"]; sources: readonly NewYorkSourceEntry[]; requests: readonly RequestReceipt[]; events: readonly EventEvidence[]; rows: readonly Row[]; summary: Readonly<{ events: 2; enumeratedResults: 39; democraticHouseResults: 0; seatCycles: 10; noReportedContestRows: 10; dispositionSetSha256: string; evaluatorNumericValues: 0; scoreEligibleRows: 0 }>; limitations: readonly string[]; unresolvedGates: readonly string[]; packageSha256: string }>;

const ENDPOINT = "https://electionhistory.ct.gov/api/graphql_pr" as const;
const SUGGESTION_QUERY = "query GetEventSuggestions($suggestionFilters: SearchFilters!) { searchSuggestions(filters:$suggestionFilters) { events { id name group count } } }";
const RESULTS_QUERY = "query GetLatestResults($searchFilters: SearchFilters!, $pagination: Pagination!) { search(filters:$searchFilters, pagination:$pagination) { results { id name candidates { displayName nVotes pctCandidateVotes candidate { pseudocandidate } isWinner } eventTypeDisplayName office { name } event { startDate } division { displayName } } } }";
const filters = (global: unknown) => ({ global, ballotQuestions: { text: "", types: [], number: "", divisions: [] }, contests: { candidates: [], divisions: [], offices: [] }, specialElectionsOnly: false, voterStats: false, stages: [] });
const REQUESTS = [
  { sourceLockId: "ct-2022-primary-event-discovery-response", method: "POST" as const, endpoint: ENDPOINT, headers: { "Content-Type": "application/json" as const, "X-Elstats-Tenant": "ct" as const }, requestSha256: "1ebf93dc499207082f277295162c70b229e89534020111bac5f642456931ad93", requestBody: { operationName: "GetEventSuggestions", variables: { suggestionFilters: filters({ years: { from: 2022, to: 2022 } }) }, query: SUGGESTION_QUERY } },
  { sourceLockId: "ct-2022-primary-event-598-results-response", method: "POST" as const, endpoint: ENDPOINT, headers: { "Content-Type": "application/json" as const, "X-Elstats-Tenant": "ct" as const }, requestSha256: "b115ea828dd3a82046a44fe2f15e88b1272b6ab59dbb573c0ea76b10ad356cc8", requestBody: { operationName: "GetLatestResults", variables: { searchFilters: filters({ events: [598] }), pagination: { page: 1, size: 100 } }, query: RESULTS_QUERY } },
  { sourceLockId: "ct-2024-primary-event-discovery-response", method: "POST" as const, endpoint: ENDPOINT, headers: { "Content-Type": "application/json" as const, "X-Elstats-Tenant": "ct" as const }, requestSha256: "43466a2db7cd49b9de79e82e303cd9a24a6bde29adcc166c49a8e1a2cd4923d3", requestBody: { operationName: "GetEventSuggestions", variables: { suggestionFilters: filters({ years: { from: 2024, to: 2024 } }) }, query: SUGGESTION_QUERY } },
  { sourceLockId: "ct-2024-primary-event-583-results-response", method: "POST" as const, endpoint: ENDPOINT, headers: { "Content-Type": "application/json" as const, "X-Elstats-Tenant": "ct" as const }, requestSha256: "c4051f3262bb07aa9aff733f519fb018c5c5de238df91749194b1109dcdd38f4", requestBody: { operationName: "GetLatestResults", variables: { searchFilters: filters({ events: [583] }), pagination: { page: 1, size: 100 } }, query: RESULTS_QUERY } },
] as const;
const EXPECTED = {
  "ct-2022-primary-event-discovery-response": { path: "data/source/elections/primary-results/connecticut/2022/event-discovery-response.json", size: 474, hash: "d58b5da59d3e55ee9b13034bc75ae19c4907c39a080fe7fdafa97a77b7564dfa", parents: [] },
  "ct-2022-primary-event-598-results-response": { path: "data/source/elections/primary-results/connecticut/2022/event-598-results-response.json", size: 13201, hash: "a7f887fe1de2379cb6a80fdd6437b8524eadec152dde8e883d586f64bc73430e", parents: ["ct-2022-primary-event-discovery-response"] },
  "ct-2024-primary-event-discovery-response": { path: "data/source/elections/primary-results/connecticut/2024/event-discovery-response.json", size: 381, hash: "27cdef87cfd86d8049097a9b0bb2a86ab377477c002b2d7c69c0a9997575e618", parents: [] },
  "ct-2024-primary-event-583-results-response": { path: "data/source/elections/primary-results/connecticut/2024/event-583-results-response.json", size: 17492, hash: "f87bef38061705dd986c9ffad05501f0b70858f3481796c3fa7ecc99b8101982", parents: ["ct-2024-primary-event-discovery-response"] },
} as const;
const LIMITATIONS = ["The retained event enumerations establish that no Democratic Representative in Congress result is reported in either complete August primary event; they do not establish no nominee, no primary ballot, an uncontested nomination, or zero votes.", "The public GraphQL endpoint is used by the official historical-results frontend but is undocumented; exact request and response bytes are retained because endpoint stability is not promised.", "The historical database says it derives from official source documents, but no separate final canvass or certification artifact is retained here and reuse licensing remains unassessed.", "No row is public, score eligible, identity reviewed, historical-geography approved, or progressively classified."] as const;
const GATES = ["retain_ballot_or_nomination_authority_for_per_district_disposition", "retain_independent_final_result_certification", "review_incumbent_candidate_identity", "review_historical_district_compatibility", "review_progressive_candidate_classification", "complete_human_data_review_and_publication_approval"] as const;
const fail = (code: string): never => { throw new Error(`Connecticut primary event dispositions rejected: ${code}`); };
const sha = (value: Uint8Array) => createHash("sha256").update(value).digest("hex");
const digest = (domain: string, value: unknown) => createHash("sha256").update(domain, "ascii").update(canonicalJson(value), "utf8").digest("hex");
const bytewise = (a: string, b: string) => Buffer.compare(Buffer.from(a), Buffer.from(b));
const bytes = (value: Bytes) => typeof value === "string" ? Buffer.from(value) : Buffer.from(value);

function checkedInputs(inputs: readonly ConnecticutEventInput[]): ReadonlyMap<string, Readonly<{ entry: NewYorkSourceEntry; parsed: Record<string, unknown> }>> {
  const map = new Map<string, Readonly<{ entry: NewYorkSourceEntry; parsed: Record<string, unknown> }>>(); for (const input of inputs) { const expected = EXPECTED[input.entry.id as keyof typeof EXPECTED]; if (!expected || map.has(input.entry.id)) fail("SOURCE_CLOSURE_INVALID"); const source = bytes(input.bytes); if (input.entry.url !== ENDPOINT || input.entry.retainedPath !== expected.path || input.entry.retainedStatus !== "retained" || input.entry.kind !== "source" || canonicalJson(input.entry.parentIds) !== canonicalJson(expected.parents) || input.entry.byteSize !== expected.size || input.entry.sha256 !== expected.hash || source.byteLength !== expected.size || sha(source) !== expected.hash) fail("SOURCE_RECEIPT_INVALID"); const parsed = JSON.parse(new TextDecoder("utf-8", { fatal: true }).decode(source)) as Record<string, unknown>; if (Object.keys(parsed).join() !== "data") fail("RESPONSE_ENVELOPE_INVALID"); map.set(input.entry.id, { entry: input.entry, parsed }); } if (map.size !== 4) fail("SOURCE_CLOSURE_INVALID"); return map;
}

export function buildConnecticutEventDispositionsReceipt(inputs: readonly ConnecticutEventInput[]): ConnecticutEventDispositionsReceipt {
  const inputMap = checkedInputs(inputs), events: EventEvidence[] = []; for (const cycleYear of [2022, 2024] as const) { const eventId = cycleYear === 2022 ? 598 : 583, eventName = cycleYear === 2022 ? "2022 Aug 09 - Primary" : "2024 Aug 13 - Primary", count = cycleYear === 2022 ? 17 : 22, discoveryId = `ct-${cycleYear}-primary-event-discovery-response`, resultsId = `ct-${cycleYear}-primary-event-${eventId}-results-response`; const discovery = inputMap.get(discoveryId)!.parsed as { data?: { searchSuggestions?: { events?: unknown[] } } }, resultResponse = inputMap.get(resultsId)!.parsed as { data?: { search?: { results?: unknown[] } } }; const discoveredValue = discovery.data?.searchSuggestions?.events; if (!Array.isArray(discoveredValue)) fail("DISCOVERY_SHAPE_INVALID"); const discovered = discoveredValue as unknown[], selected = discovered.filter((event) => { const row = event as Record<string, unknown>; return row.id === eventId && row.name === eventName && row.group === String(cycleYear) && row.count === count; }); if (selected.length !== 1) fail("EVENT_SELECTION_INVALID"); const resultsValue = resultResponse.data?.search?.results; if (!Array.isArray(resultsValue)) fail("EVENT_ENUMERATION_INCOMPLETE"); const results = resultsValue as unknown[]; if (results.length !== count || new Set(results.map((result) => (result as Record<string, unknown>).id)).size !== count) fail("EVENT_ENUMERATION_INCOMPLETE"); const demHouse = results.filter((result) => { const row = result as { eventTypeDisplayName?: unknown; office?: { name?: unknown } }; return row.eventTypeDisplayName === "Democratic Primary" && row.office?.name === "Representative in Congress"; }); if (demHouse.length !== 0) fail("DEMOCRATIC_HOUSE_RESULT_PRESENT"); const resultIds = results.map((result) => String((result as Record<string, unknown>).id)).sort(bytewise); events.push({ cycleYear, eventId, eventName, eventGroup: String(cycleYear) as "2022" | "2024", advertisedResultCount: count, enumeratedResultCount: count, resultIds, resultSetSha256: digest("dsa-seats:ct-primary-event-result-set:v1\0", results), democraticHouseResultCount: 0, discoverySourceLockId: discoveryId, resultsSourceLockId: resultsId }); }
  const rows: Row[] = []; for (const event of events) for (let district = 1; district <= 5; district++) { const districtCode = String(district).padStart(2, "0"), unsigned = { seatCycleId: `ct:${event.cycleYear}:us-house:${districtCode}:democratic`, cycleYear: event.cycleYear, stateCode: "CT" as const, districtCode, party: "Democratic" as const, office: "U.S. Representative" as const, disposition: "no_reported_democratic_house_primary_contest_in_complete_official_event" as const, eventEvidenceId: `ct:${event.cycleYear}:primary-event:${event.eventId}`, nominationDisposition: null, selectedContestId: null, voteValues: null, scoreEligible: false as const, evaluatorValues: { priorPrimaryMargin: null, priorDemocraticPrimaryVotes: null, priorProgressivePrimaryShare: null } }; rows.push({ ...unsigned, rowSha256: digest("dsa-seats:ct-house-democratic-primary-event-disposition:v1\0", unsigned) }); } rows.sort((a, b) => bytewise(a.seatCycleId, b.seatCycleId)); const dispositionSetSha256 = digest("dsa-seats:ct-house-democratic-primary-event-disposition-set:v1\0", rows.map(({ seatCycleId, rowSha256 }) => ({ seatCycleId, rowSha256 }))); const sources = [...inputMap.values()].map((value) => value.entry).sort((a, b) => bytewise(a.id, b.id)); const unsigned = { schema: CONNECTICUT_HOUSE_DEMOCRATIC_PRIMARY_EVENT_DISPOSITIONS_V1, version: 1 as const, generatedAt: "2026-08-05T19:00:00.000Z" as const, sourceCutoff: "2026-08-05" as const, reviewerOnly: true as const, publicationEligible: false as const, review: { status: "proposed" as const, reviewer: null, reviewedAt: null }, originalPublisher: "Connecticut Secretary of the State historical election database" as const, status: "official_result_event_enumeration_candidate" as const, certificationStatus: "not_independently_retained" as const, licenseStatus: "unassessed" as const, authorityContextUrls: ["https://portal.ct.gov/sots/election-services/election-results/election-results", "https://electionhistory.ct.gov/", "https://electionhistory.ct.gov/about"] as const, sources, requests: [...REQUESTS].sort((a, b) => bytewise(a.sourceLockId, b.sourceLockId)), events, rows, summary: { events: 2 as const, enumeratedResults: 39 as const, democraticHouseResults: 0 as const, seatCycles: 10 as const, noReportedContestRows: 10 as const, dispositionSetSha256, evaluatorNumericValues: 0 as const, scoreEligibleRows: 0 as const }, limitations: LIMITATIONS, unresolvedGates: GATES }; return { ...unsigned, packageSha256: digest("dsa-seats:ct-house-democratic-primary-event-disposition-package:v1\0", unsigned) };
}

export function validateConnecticutEventDispositionsReceipt(value: ConnecticutEventDispositionsReceipt): ConnecticutEventDispositionsReceipt {
  const { packageSha256, ...unsigned } = value; const setHash = digest("dsa-seats:ct-house-democratic-primary-event-disposition-set:v1\0", value.rows.map(({ seatCycleId, rowSha256 }) => ({ seatCycleId, rowSha256 }))); if (packageSha256 !== CONNECTICUT_EVENT_DISPOSITION_PACKAGE_SHA256 || packageSha256 !== digest("dsa-seats:ct-house-democratic-primary-event-disposition-package:v1\0", unsigned) || setHash !== CONNECTICUT_EVENT_DISPOSITION_SET_SHA256 || value.summary.dispositionSetSha256 !== setHash || value.events.length !== 2 || value.events.reduce((sum, event) => sum + event.enumeratedResultCount, 0) !== 39 || value.events.some((event) => event.enumeratedResultCount !== event.advertisedResultCount || event.democraticHouseResultCount !== 0) || value.rows.length !== 10 || new Set(value.rows.map((row) => row.seatCycleId)).size !== 10 || value.summary.evaluatorNumericValues !== 0 || value.summary.scoreEligibleRows !== 0 || value.reviewerOnly !== true || value.publicationEligible !== false || canonicalJson(value.requests) !== canonicalJson([...REQUESTS].sort((a, b) => bytewise(a.sourceLockId, b.sourceLockId))) || canonicalJson(value.limitations) !== canonicalJson(LIMITATIONS) || canonicalJson(value.unresolvedGates) !== canonicalJson(GATES) || value.rows.some((row) => { const { rowSha256, ...rest } = row; return rowSha256 !== digest("dsa-seats:ct-house-democratic-primary-event-disposition:v1\0", rest) || row.nominationDisposition !== null || row.selectedContestId !== null || row.voteValues !== null || row.scoreEligible || Object.values(row.evaluatorValues).some((item) => item !== null); })) fail("PACKAGE_INVARIANT_INVALID"); return value;
}
