import { createHash } from "node:crypto";
import { canonicalJson } from "../fec/aipac-proposed-packages";
import { validateConnecticutNominationIdentityCandidate } from "./connecticut-current-incumbent-nomination-linkage-candidate";
import { validateConnecticutPrimaryGeographyCandidate } from "./connecticut-primary-geography-compatibility-candidate";

type Input={proposalJson:string;identityJson:string;geographyJson:string;sourceLockJson:string};
type RecordRow={reviewRecordId:string;cycleYear:2022|2024;districtCode:string;seatCycleId:string;reviewCategory:"identity_and_geography_candidates_pending_nomination_closure";nominationStatus:null;resultStatus:null;identity:{observationId:string;parentRowSha256:string;evidenceClass:string;identityApproved:false};geography:{observationId:string;parentRowSha256:string;compatibilityDisposition:string;compatibilityApproved:false};jointApproved:false;evaluatorUse:"excluded_pending_independent_identity_geography_nonnomination_and_publication_review";scoreEligible:false;reviewRecordSha256:string};
export type ConnecticutPrimaryJointReviewPackage=ReturnType<typeof buildConnecticutPrimaryJointReviewPackage>;

const FILES={proposal:"85246e9adfd181e6f24606b6eaa29250c45c9e8e42a6dd5af5cb162de17f45b1",identity:"e4b461a364a31dae528d4099022f9417110c1aa5430c53b2076b7c09c5981644",geography:"0012e0c97b183f7f8e110f70e892b15488c6a1b0ddd202c4184c42153a17bd82"} as const;
const sourceIds=["house-democratic-primary-source-selection-proposal-20260804-v1","connecticut-current-incumbent-nomination-linkage-candidate-v1","connecticut-primary-geography-compatibility-candidate-v1"];
const SOURCE_SET="a8dbef13b60c989f089c53dee6e4dc98caf2093fad9c7160fdb8f0ea34f3cad3";
const RECORD_SET="c88eede71b533a6a07945d56eb592c4d0d7f4afba59dcb2761760982be7fb9e9";
const DECISION_SET="35d23ea2c7002e6215df29ccd36ea71833d302d65bbf6446f815138403c1f8e1";
const PACKAGE="093d6c3b95f6e4364d183c4c036dead44867cb52a4a417e2297df5f847c0954b";
const outputLockEntry={id:"connecticut-primary-identity-geography-review-package-v1",url:"urn:dsa-seats:connecticut-primary-identity-geography-review-package:v1:2022-2024",retainedPath:"data/metadata/connecticut-primary-identity-geography-review-package-v1.json",retainedStatus:"retained",byteSize:22928,sha256:"3865508fcce8b0712854f10d8831ab8608499ba692e48f0575d36b0eb2d15d1f",kind:"review_proposal",parentIds:sourceIds};
const review={status:"proposed" as const,reviewer:null,reviewedAt:null,resolution:null};
const summary={reviewRecords:10 as const,identityAndGeographyCandidates:10 as const,exactIdentityObservations:8 as const,derivedIdentityObservations:2 as const,uniqueDerivedIdentityRelationships:1 as const,cd118ContinuityCandidates:5 as const,exactCd119KeyCandidates:5 as const,nominationConclusions:0 as const,resultConclusions:0 as const,proposedDecisions:5 as const,jointApprovedRecords:0 as const,scoreEligibleRecords:0 as const};
const methodology={decisionsReviewedIndependently:true as const,jointPackageApprovesParents:false as const,endorsementObservationTreatedAsNomination:false as const,automaticApprovals:0 as const,evaluatorNumericValues:0 as const};
const sha=(value:string)=>createHash("sha256").update(value,"utf8").digest("hex");
const digest=(domain:string,value:unknown)=>createHash("sha256").update(domain,"ascii").update(canonicalJson(value),"utf8").digest("hex");
const fail=(code:string):never=>{throw new Error(`Connecticut primary joint review rejected: ${code}`);};

export function buildConnecticutPrimaryJointReviewPackage(input:Input){
  if(sha(input.proposalJson)!==FILES.proposal||sha(input.identityJson)!==FILES.identity||sha(input.geographyJson)!==FILES.geography)fail("INPUT_HASH_MISMATCH");
  const proposal=JSON.parse(input.proposalJson),identity=validateConnecticutNominationIdentityCandidate(JSON.parse(input.identityJson)),geography=validateConnecticutPrimaryGeographyCandidate(JSON.parse(input.geographyJson)),lock=JSON.parse(input.sourceLockJson);
  const sources=sourceIds.map(id=>{const matches=lock.entries?.filter((entry:{id:string})=>entry.id===id)??[];if(matches.length!==1)fail("SOURCE_LOCK_MISMATCH");return matches[0];});const outputMatches=lock.entries?.filter((entry:{id:string})=>entry.id===outputLockEntry.id)??[];if(digest("dsa-seats:ct-primary-joint-source-set:v1\0",sources)!==SOURCE_SET||outputMatches.length!==1||canonicalJson(outputMatches[0])!==canonicalJson(outputLockEntry))fail("SOURCE_LOCK_MISMATCH");
  if(proposal.packageSha256!=="a090e0be03dc2b0fa5edd0c1132a8261eed0f98ceb4df090154d0b150d8721fb"||proposal.decisions?.find((item:{decisionId:string})=>item.decisionId==="approve-historical-district-cd119-compatibility-v1")?.resolution!==null||identity.review.resolution!==null||geography.review.resolution!==null)fail("PARENT_LIFECYCLE_INVALID");
  const records:RecordRow[]=geography.rows.map(geographyRow=>{const matches=identity.observations.filter(identityRow=>identityRow.observationId===geographyRow.identityObservationId&&identityRow.rowSha256===geographyRow.identityObservationSha256);if(matches.length!==1)fail("JOIN_CLOSURE_INVALID");const identityRow=matches[0]!;if(identityRow.cycleYear!==geographyRow.cycleYear||identityRow.districtCode!==geographyRow.districtCode||identityRow.seatCycleId!==geographyRow.seatCycleId||identityRow.endorsementCandidate.nominationStatus!==null||identityRow.endorsementCandidate.resultStatus!==null)fail("JOIN_FACT_INVALID");const unsigned={reviewRecordId:`ct-primary:joint:${geographyRow.cycleYear}:${geographyRow.districtCode}`,cycleYear:geographyRow.cycleYear,districtCode:geographyRow.districtCode,seatCycleId:geographyRow.seatCycleId,reviewCategory:"identity_and_geography_candidates_pending_nomination_closure" as const,nominationStatus:null,resultStatus:null,identity:{observationId:identityRow.observationId,parentRowSha256:identityRow.rowSha256,evidenceClass:identityRow.evidenceClass,identityApproved:false as const},geography:{observationId:geographyRow.observationId,parentRowSha256:geographyRow.rowSha256,compatibilityDisposition:geographyRow.compatibilityDisposition,compatibilityApproved:false as const},jointApproved:false as const,evaluatorUse:"excluded_pending_independent_identity_geography_nonnomination_and_publication_review" as const,scoreEligible:false as const};return{...unsigned,reviewRecordSha256:digest("dsa-seats:ct-primary-joint-review-row:v1\0",unsigned)};});if(records.length!==10||new Set(records.map(row=>row.reviewRecordId)).size!==10)fail("JOIN_CLOSURE_INVALID");
  const recordIds=records.map(row=>row.reviewRecordId),decision=(decisionId:string,parentDecisionId:string,question:string,recommendedDecision:string)=>({decisionId,parentDecisionId,question,recommendedDecision,defaultReversibleAssumption:"exclude_affected_records_from_evaluator_and_publication" as const,alternatives:["Request additional retained evidence before deciding.","Reject the proposed relationship and preserve exclusion."],consequences:["Acceptance authorizes only this relationship after a separate promotion step.","Rejection preserves the parent evidence without evaluator or publication use."],confidence:"high" as const,evidenceRecordIds:recordIds,blocksAffectedPublication:true as const,blocksOtherWork:false as const,review});
  const decisions=[decision("ct-primary:accept-geography-compatibility-v1","approve-historical-district-cd119-compatibility-v1","Should the five CD118-to-CD119 continuity and five exact CD119-key relationships be accepted?","Accept all ten geography candidates without claiming raw geometry equality, overlap, or population equivalence."),decision("ct-primary:accept-identity-links-v1","approve-historic-primary-candidate-identity-resolution-v1","Should the ten endorsement-name to current-target identity relationships be accepted?","Accept eight exact-name and two finite Jim Himes to James A. Himes relationship observations while preserving the historical-incumbency boundary."),decision("ct-primary:retain-endorsement-nomination-result-certification-exclusion-v1","collect-official-state-primary-results-and-certification-v1","Should the ten endorsement observations remain retained while nomination, result, and certification stay unasserted?","Retain endorsement authority while preserving null nomination and result states and prohibiting certification inference."),decision("ct-primary:retain-nomination-disposition-selection-exclusion-v1","decide-nonstandard-primary-disposition-treatment-v1","Should endorsement forms remain nonauthorizing for nomination, primary disposition, winner, or selection?","Retain no-disposition and no-selection treatment until final candidacy, statutory cancellation, and nominee authority are reviewed."),decision("ct-primary:retain-progressive-classification-exclusion-v1","approve-progressive-candidate-classification-method-v1","Should progressive-primary factors remain excluded for these endorsement observations?","Retain progressive-classification exclusion because no complete candidate universe or reviewed contest-effective classification is present.")];
  const unsigned={schema:"connecticut-primary-identity-geography-review-package-v1" as const,version:1 as const,generatedAt:"2026-08-06T11:00:00.000Z" as const,sourceCutoff:"2026-08-06" as const,reviewerOnly:true as const,publicationEligible:false as const,defaultUse:"exclude_from_evaluator_until_independent_decisions_and_publication_review" as const,review,sources,methodology,summary,records,reviewRecordSetSha256:digest("dsa-seats:ct-primary-joint-review-row-set:v1\0",records),decisions,decisionSetSha256:digest("dsa-seats:ct-primary-joint-review-decision-set:v1\0",decisions)};return{...unsigned,packageSha256:digest("dsa-seats:ct-primary-joint-review-package:v1\0",unsigned)};
}

export function validateConnecticutPrimaryJointReviewPackage(value:ConnecticutPrimaryJointReviewPackage){
  const{packageSha256,...unsigned}=value;if(packageSha256!==PACKAGE||packageSha256!==digest("dsa-seats:ct-primary-joint-review-package:v1\0",unsigned)||value.reviewRecordSetSha256!==RECORD_SET||value.decisionSetSha256!==DECISION_SET||value.schema!=="connecticut-primary-identity-geography-review-package-v1"||value.version!==1||!value.reviewerOnly||value.publicationEligible||canonicalJson(value.review)!==canonicalJson(review)||canonicalJson(value.methodology)!==canonicalJson(methodology)||canonicalJson(value.summary)!==canonicalJson(summary)||digest("dsa-seats:ct-primary-joint-source-set:v1\0",value.sources)!==SOURCE_SET||value.reviewRecordSetSha256!==digest("dsa-seats:ct-primary-joint-review-row-set:v1\0",value.records)||value.decisionSetSha256!==digest("dsa-seats:ct-primary-joint-review-decision-set:v1\0",value.decisions))fail("PACKAGE_INVALID");
  if(value.records.length!==10||value.records.some((row,index)=>{const unsignedRow={...row} as Partial<RecordRow>;delete unsignedRow.reviewRecordSha256;const cycle=index<5?2022:2024,district=String(index%5+1).padStart(2,"0");return row.reviewRecordId!==`ct-primary:joint:${cycle}:${district}`||row.cycleYear!==cycle||row.districtCode!==district||row.seatCycleId!==`seat_house_ct_${district}_current`||row.reviewCategory!=="identity_and_geography_candidates_pending_nomination_closure"||row.nominationStatus!==null||row.resultStatus!==null||row.identity.observationId!==`ct:identity:${cycle}:${district}`||row.identity.identityApproved||row.geography.observationId!==`ct:geography:${cycle}:${district}`||row.geography.compatibilityApproved||row.jointApproved||row.scoreEligible||row.evaluatorUse!=="excluded_pending_independent_identity_geography_nonnomination_and_publication_review"||row.reviewRecordSha256!==digest("dsa-seats:ct-primary-joint-review-row:v1\0",unsignedRow);}))fail("RECORD_INVALID");
  const ids=value.records.map(row=>row.reviewRecordId);if(value.decisions.length!==5||canonicalJson(value.decisions.map(item=>item.decisionId))!==canonicalJson(["ct-primary:accept-geography-compatibility-v1","ct-primary:accept-identity-links-v1","ct-primary:retain-endorsement-nomination-result-certification-exclusion-v1","ct-primary:retain-nomination-disposition-selection-exclusion-v1","ct-primary:retain-progressive-classification-exclusion-v1"])||value.decisions.some(item=>item.review.resolution!==null||canonicalJson(item.evidenceRecordIds)!==canonicalJson(ids)||item.defaultReversibleAssumption!=="exclude_affected_records_from_evaluator_and_publication"||!item.blocksAffectedPublication||item.blocksOtherWork))fail("DECISION_INVALID");return value;
}
