/* eslint-disable @typescript-eslint/no-explicit-any -- adversarial immutable-candidate mutations */
import { createHash } from "node:crypto";
import { readFileSync } from "node:fs";
import { describe, expect, it } from "vitest";
import { canonicalJson } from "../fec/aipac-proposed-packages";
import { buildCurrentIncumbentPrimaryCandidateLinkageCandidate, validateCurrentIncumbentPrimaryCandidateLinkageCandidate } from "./current-incumbent-primary-candidate-linkage-candidate";

const read = (path: string) => { const bytes = readFileSync(path); return { bytes, sha256: createHash("sha256").update(bytes).digest("hex") }; };
const json = (path: string) => { const value = read(path); return { ...value, parsed: JSON.parse(value.bytes.toString("utf8")) }; };
const build = (sourceLockOverride?: unknown) => { const roster = json("data/metadata/dsa-target-incumbent-roster-20260804-v1.json"), proposal = json("data/metadata/house-democratic-primary-source-selection-proposal-20260804-v1.json"), clerk = read("data/source/identity/house-member-data.xml"), congress = json("data/source/identity/congress-legislators-current-20260804.json"), nj = json("data/metadata/new-jersey-house-democratic-primary-results-2022-2026-v1.json"), pa = json("data/metadata/pennsylvania-house-democratic-primary-results-2022-2024-v1.json"), lock = json("data/source-lock.json"); return buildCurrentIncumbentPrimaryCandidateLinkageCandidate({ roster: roster.parsed, rosterFileSha256: roster.sha256, proposal: proposal.parsed, proposalFileSha256: proposal.sha256, clerkXml: clerk.bytes.toString("utf8"), clerkFileSha256: clerk.sha256, congressCurrent: congress.parsed, congressCurrentFileSha256: congress.sha256, newJersey: nj.parsed, newJerseyFileSha256: nj.sha256, pennsylvania: pa.parsed, pennsylvaniaFileSha256: pa.sha256, sourceLock: sourceLockOverride ?? lock.parsed }); };
const digest = (domain: string, value: unknown) => createHash("sha256").update(domain).update(canonicalJson(value)).digest("hex");

describe("current incumbent primary candidate linkage candidate", () => {
  it("rebuilds the retained candidate exactly", () => { expect(build()).toEqual(json("data/metadata/current-incumbent-primary-candidate-linkage-candidate-v1.json").parsed); });
  it("closes the 41 observations without approving or scoring identity", () => { const value = build(); expect(value.summary).toEqual({ targetSeats: 16, seatCycleObservations: 41, proposedLinks: 33, exactNameLinks: 18, derivedNameLinks: 9, inferredNameLinks: 6, unresolvedObservations: 8, automaticallyApprovedLinks: 0, scoreEligibleLinks: 0 }); expect(value.links.every((row) => !row.scoreEligible && row.evaluatorUse === "excluded_pending_authorized_identity_review")).toBe(true); });
  it("preserves historical nonappearances and source markers as non-authoritative", () => { const value = build(); expect(value.links.filter((row) => row.relationshipDisposition === "not_linked_no_unique_candidate")).toHaveLength(8); expect(value.links.filter((row) => row.sourceCandidate?.incumbentMarker).every((row) => row.relationshipDisposition === "proposed_identity_link_pending_documented_review")).toBe(true); expect(value.methodology.sourceIncumbentMarkerIsIdentityApproval).toBe(false); });
  it("pins NJ-08 family-name risk and never conflates challenger IDs or PA winners", () => { const value = build(), nj082022 = value.links.find((row) => row.seatCycleId === "seat_house_nj_08_current" && row.cycleYear === 2022)!; expect(nj082022).toMatchObject({ evidenceClass: "inferred_name_relationship", confidence: "medium", sourceCandidate: { sourceCandidateName: "ROBERT J. MENENDEZ" } }); expect(value.links.filter((row) => row.stateCode === "PA").every((row) => row.sourceCandidate?.winnerMarker !== true)).toBe(true); expect(JSON.stringify(value)).not.toMatch(/H6NJ11245|H2PA18218/); });
  it("rejects wrong exact parent bytes", () => { const roster = json("data/metadata/dsa-target-incumbent-roster-20260804-v1.json"); expect(() => buildCurrentIncumbentPrimaryCandidateLinkageCandidate({ roster: roster.parsed, rosterFileSha256: "0".repeat(64), proposal: {}, proposalFileSha256: "0".repeat(64), clerkXml: "", clerkFileSha256: "0".repeat(64), congressCurrent: [], congressCurrentFileSha256: "0".repeat(64), newJersey: {}, newJerseyFileSha256: "0".repeat(64), pennsylvania: {}, pennsylvaniaFileSha256: "0".repeat(64), sourceLock: {} })).toThrow("PRIMARY_LINKAGE_INPUT_FILE_HASH_MISMATCH"); });
  it("rejects wrong source-lock kind or path", () => { const lock: any = json("data/source-lock.json").parsed, wrongKind = structuredClone(lock), kindTarget = wrongKind.entries.find((entry: any) => entry.id === "house-xml"); kindTarget.kind = "review_candidate"; expect(() => build(wrongKind)).toThrow("PRIMARY_LINKAGE_SOURCE_LOCK_MISMATCH"); const wrongPath = structuredClone(lock), pathTarget = wrongPath.entries.find((entry: any) => entry.id === "house-xml"); pathTarget.retainedPath = "data/source/identity/substituted.xml"; expect(() => build(wrongPath)).toThrow("PRIMARY_LINKAGE_SOURCE_LOCK_MISMATCH"); });
  it("rejects fabricated review and publication states", () => { const reviewed: any = build(); reviewed.review.reviewer = "fabricated"; expect(() => validateCurrentIncumbentPrimaryCandidateLinkageCandidate(reviewed)).toThrow(); const published: any = build(); published.publicationEligible = true; expect(() => validateCurrentIncumbentPrimaryCandidateLinkageCandidate(published)).toThrow(); });
  it("rejects a fully rehashed relationship substitution and excludes private row fields", () => { const value: any = build(); value.links[0].sourceCandidate.sourceCandidateName = "SUBSTITUTED"; const row = { ...value.links[0] }; delete row.rowSha256; value.links[0].rowSha256 = digest("dsa-seats:current-incumbent-primary-candidate-link:v1\0", row); value.linkSetSha256 = digest("dsa-seats:current-incumbent-primary-candidate-link-set:v1\0", value.links); const unsigned = { ...value }; delete unsigned.packageSha256; value.packageSha256 = digest("dsa-seats:current-incumbent-primary-candidate-link-candidate:v1\0", unsigned); expect(() => validateCurrentIncumbentPrimaryCandidateLinkageCandidate(value)).toThrow("PRIMARY_LINKAGE_PACKAGE_HASH_MISMATCH"); expect(JSON.stringify(build().links)).not.toMatch(/address|phone|email|dateOfBirth|donor/i); });
});
