import { describe, expect, it } from "vitest";
import { certifyOriginalBoundaryOptions } from "./certified";
import { decodeElectionDecisionSnapshotV1, deriveElectionDecisionStatus, encodeElectionDecisionSnapshotV1, MAX_ELECTION_DECISION_SNAPSHOT_BYTES, type ElectionGate, type ElectionGateName } from "./gate";
import { overlayApprovedSynthetic } from "./overlay";

const values: Record<ElectionGateName, object> = { sourceAuthority: { originalPublisher: { identity: "official", role: "original_publisher", evidenceKind: "record" }, intermediaries: [] }, license: { assessment: "approved" }, certification: { value: "certified", scope: "contest" }, reportingUnitGeometry: { release: "r", vintage: "v" }, nonGeographicPolicy: { policy: "excluded" }, allocation: { method: "none", crosswalkMethodology: "none", weightsMethodology: "none" }, reconciliation: { delta: 0, authorityTotal: 10 }, rounding: { rule: "largest_remainder" }, coverage: { expectedCount: 1, actualCount: 1 } };
const gates = (outcome: "unassessed" | "passed" | "failed"): Record<ElectionGateName, ElectionGate> => Object.fromEntries((Object.keys(values) as ElectionGateName[]).map(name => [name, { outcome, evidenceSnapshotIds: outcome === "unassessed" ? [] : ["snap_1"], value: outcome === "unassessed" ? null : values[name], failureReason: outcome === "failed" ? "coverage_incomplete" : null }])) as unknown as Record<ElectionGateName, ElectionGate>;
const snapshot = () => ({ schemaVersion: 1 as const, jurisdictionCode: "AL" as const, electionYear: 2024 as const, reviewDate: "2025-01-01", methodology: "v1", evidenceSnapshotIds: ["snap_1"], gates: gates("passed") });
describe("election decision gates", () => {
  it("requires structured evidence closure and dependencies", () => { expect(decodeElectionDecisionSnapshotV1(encodeElectionDecisionSnapshotV1(snapshot()))).toEqual(snapshot()); expect(() => encodeElectionDecisionSnapshotV1({ ...snapshot(), evidenceSnapshotIds: ["snap_1", "snap_orphan"] })).toThrow("ORPHAN_EVIDENCE"); expect(() => encodeElectionDecisionSnapshotV1({ ...snapshot(), gates: { ...snapshot().gates, license: { ...snapshot().gates.license, outcome: "failed", evidenceSnapshotIds: [] } } })).toThrow("GATE_VALUE_OR_EVIDENCE_REQUIRED"); const bad = snapshot(); bad.gates.sourceAuthority = { ...bad.gates.sourceAuthority, outcome: "unassessed", evidenceSnapshotIds: [], value: null, failureReason: null }; expect(() => encodeElectionDecisionSnapshotV1(bad)).toThrow("GATE_DEPENDENCY_VIOLATION"); });
  it("rejects landing-only authority and noncanonical permutations", () => { const landing = snapshot(); landing.gates.sourceAuthority = { ...landing.gates.sourceAuthority, value: { originalPublisher: { identity: "official", role: "original_publisher", evidenceKind: "landing_only" }, intermediaries: [] } }; expect(() => encodeElectionDecisionSnapshotV1(landing)).toThrow("LANDING_EVIDENCE_CANNOT_PASS"); const bytes = encodeElectionDecisionSnapshotV1(snapshot()); const permuted = Buffer.from(Buffer.from(bytes).toString().replace('"electionYear":2024,"evidenceSnapshotIds"', '"evidenceSnapshotIds"')); expect(() => decodeElectionDecisionSnapshotV1(permuted)).toThrow(); });
  it("rejects contradictory gate values and oversized bytes before parsing", () => { const badLicense = snapshot(); badLicense.gates.license = { ...badLicense.gates.license, outcome: "failed", failureReason: "license_unavailable" }; expect(() => encodeElectionDecisionSnapshotV1(badLicense)).toThrow("GATE_VALUE_OR_EVIDENCE_REQUIRED"); const badReconciliation = snapshot(); badReconciliation.gates.reconciliation = { ...badReconciliation.gates.reconciliation, outcome: "failed", failureReason: "reconciliation_mismatch" }; expect(() => encodeElectionDecisionSnapshotV1(badReconciliation)).toThrow("GATE_VALUE_OR_EVIDENCE_REQUIRED"); expect(() => decodeElectionDecisionSnapshotV1(new Uint8Array(MAX_ELECTION_DECISION_SNAPSHOT_BYTES + 1))).toThrow("SNAPSHOT_TOO_LARGE"); });
  it("allows honest downstream unassessment after an early failure", () => {
    const failed = snapshot();
    failed.gates.sourceAuthority = { ...failed.gates.sourceAuthority, outcome: "failed", failureReason: "source_not_authoritative" };
    for (const name of Object.keys(values).slice(1) as ElectionGateName[]) failed.gates[name] = { outcome: "unassessed", evidenceSnapshotIds: [], value: null, failureReason: null };
    expect(deriveElectionDecisionStatus(failed.gates)).toBe("unavailable");
    expect(decodeElectionDecisionSnapshotV1(encodeElectionDecisionSnapshotV1(failed))).toEqual(failed);
    const invalid = structuredClone(failed); invalid.gates.license = snapshot().gates.license;
    expect(() => encodeElectionDecisionSnapshotV1(invalid)).toThrow("GATE_DEPENDENCY_VIOLATION");
    const unassessed = { ...snapshot(), evidenceSnapshotIds: [] as string[] }; unassessed.gates.sourceAuthority = { outcome: "unassessed", evidenceSnapshotIds: [], value: null, failureReason: null };
    for (const name of Object.keys(values).slice(1) as ElectionGateName[]) unassessed.gates[name] = { outcome: "unassessed", evidenceSnapshotIds: [], value: null, failureReason: null };
    expect(deriveElectionDecisionStatus(unassessed.gates)).toBe("unassessed");
    expect(decodeElectionDecisionSnapshotV1(encodeElectionDecisionSnapshotV1(unassessed))).toEqual(unassessed);
  });
  it("permits 2022 nationwide jurisdictions but not presidential territories", () => {
    expect(decodeElectionDecisionSnapshotV1(encodeElectionDecisionSnapshotV1({ ...snapshot(), jurisdictionCode: "AS", electionYear: 2022 }))).toMatchObject({ jurisdictionCode: "AS", electionYear: 2022 });
    expect(() => encodeElectionDecisionSnapshotV1({ ...snapshot(), jurisdictionCode: "AS", electionYear: 2024 })).toThrow("INVALID_DECISION_HEADER");
  });
});
describe("certified and synthetic mechanics", () => {
  const decision = { status: "approved" as const, jurisdictionCode: "AL", electionYear: 2024, evidenceSnapshotIds: ["snap_s"] }; const descriptor = { jurisdictionCode: "AL", electionYear: 2024, contestKey: "c", sourceSnapshotId: "snap_s", electionTimeGeographyId: "geo_g", reportingUnitKeys: ["u"], optionKeys: ["a"], denominatorVotes: Number.MAX_SAFE_INTEGER };
  it("enforces exact certified closure using BigInt", () => { const options = [{ contestKey: "c", optionKey: "a", reportingUnitKey: "u", votes: Number.MAX_SAFE_INTEGER, sourceSnapshotId: "snap_s", electionTimeGeographyId: "geo_g" }]; const totals = [{ contestKey: "c", reportingUnitKey: "u", votes: Number.MAX_SAFE_INTEGER, sourceSnapshotId: "snap_s", electionTimeGeographyId: "geo_g" }]; expect(certifyOriginalBoundaryOptions(decision, descriptor, options, totals)).toHaveLength(1); expect(() => certifyOriginalBoundaryOptions({ ...decision, electionYear: 2020 }, descriptor, options, totals)).toThrow("DECISION_NOT_APPROVED"); expect(() => certifyOriginalBoundaryOptions({ ...decision, evidenceSnapshotIds: ["snap_else"] }, descriptor, options, totals)).toThrow("DECISION_NOT_APPROVED"); });
  it("certifies 2022 nationwide jurisdictions only", () => { const options = [{ contestKey: "c", optionKey: "a", reportingUnitKey: "u", votes: Number.MAX_SAFE_INTEGER, sourceSnapshotId: "snap_s", electionTimeGeographyId: "geo_g" }]; const totals = [{ contestKey: "c", reportingUnitKey: "u", votes: Number.MAX_SAFE_INTEGER, sourceSnapshotId: "snap_s", electionTimeGeographyId: "geo_g" }]; const territory = { ...decision, jurisdictionCode: "PR", electionYear: 2022 }; const territoryDescriptor = { ...descriptor, jurisdictionCode: "PR", electionYear: 2022 }; expect(certifyOriginalBoundaryOptions(territory, territoryDescriptor, options, totals)).toHaveLength(1); expect(() => certifyOriginalBoundaryOptions({ ...decision, jurisdictionCode: "PR" }, { ...descriptor, jurisdictionCode: "PR" }, options, totals)).toThrow("DECISION_NOT_APPROVED"); });
  it("has deterministic, permutation-invariant overlay ties", () => { const declaration = { sourceUnits: ["u"], optionKeys: ["a"], expectedOutputTotal: 5 }; const votes = [{ sourceUnit: "u", optionKey: "a", votes: 5 }]; const weights = [{ sourceUnit: "u", targetUnit: "x", numerator: 1, denominator: 2 }, { sourceUnit: "u", targetUnit: "y", numerator: 1, denominator: 2 }]; expect([...overlayApprovedSynthetic("approved", "policy", declaration, votes, weights)]).toEqual([...overlayApprovedSynthetic("approved", "policy", declaration, votes, [...weights].reverse())]); });
  it("conserves each option over mixed denominators and rejects duplicate weights", () => { const declaration = { sourceUnits: ["u", "v"], optionKeys: ["a", "b"], expectedOutputTotal: 10 }; const votes = [{ sourceUnit: "u", optionKey: "a", votes: 3 }, { sourceUnit: "u", optionKey: "b", votes: 2 }, { sourceUnit: "v", optionKey: "a", votes: 4 }, { sourceUnit: "v", optionKey: "b", votes: 1 }]; const weights = [{ sourceUnit: "u", targetUnit: "x", numerator: 1, denominator: 3 }, { sourceUnit: "u", targetUnit: "y", numerator: 2, denominator: 3 }, { sourceUnit: "v", targetUnit: "x", numerator: 1, denominator: 2 }, { sourceUnit: "v", targetUnit: "y", numerator: 1, denominator: 2 }]; const result = overlayApprovedSynthetic("approved", "policy", declaration, votes, weights); expect([...result.values()].reduce((a, b) => a + b, 0)).toBe(10); expect(() => overlayApprovedSynthetic("approved", "policy", declaration, votes, [...weights, weights[0]!])).toThrow("INVALID_OR_DUPLICATE_WEIGHT"); });
});
