import { createHash } from "node:crypto";
import { canonicalJson } from "../fec/aipac-proposed-packages";
import { validateHouseDemocraticPrimarySourceSelectionProposal } from "./house-democratic-primary-source-selection-proposal";
import { validateFloridaPrimaryIdentityCandidate, type FloridaPrimaryIdentityCandidate } from "./florida-current-incumbent-primary-linkage-candidate";
import { validateFloridaPrimaryGeographyCandidate, type FloridaPrimaryGeographyCandidate } from "./florida-primary-geography-compatibility-candidate";

export const FLORIDA_PRIMARY_JOINT_REVIEW_V1="florida-primary-identity-geography-review-package-v1" as const;
export const FLORIDA_PRIMARY_JOINT_PARENT_PROJECTION_SHA256="119601a3b2b4868618523f95671214c320b2b20a062997cffcc948d219895da0";
export const FLORIDA_PRIMARY_JOINT_RECORD_SET_SHA256="91d0dd537766e07f2aa0d444238fddf513cf71a60fc1e3251237161588922cb4";
export const FLORIDA_PRIMARY_JOINT_DECISION_SET_SHA256="95e941925864e43761d99e556f461f6dcbb4b1c517f16ee963e660be1bfabb44";
export const FLORIDA_PRIMARY_JOINT_PACKAGE_SHA256="0c7cbf69db30cbf6eb197873847d7f16967c7de471d23c9e2374a50388f82155";
const INPUTS={proposalFile:"85246e9adfd181e6f24606b6eaa29250c45c9e8e42a6dd5af5cb162de17f45b1",proposalPackage:"a090e0be03dc2b0fa5edd0c1132a8261eed0f98ceb4df090154d0b150d8721fb",identityFile:"c71e77ba87f073c967edffdc564ac5cdaee19a285c55c4b72afb08a537d21b83",identityPackage:"d92bbd35721c2fc40877c7a625bb4c1a85d23cd73fe6e3b0384dcb8dfae1fce3",identitySet:"220bdca66add6e79a35933ddc6ac918d169e24a47b8500daccb52c93f89c97fc",geographyFile:"52ebf482c7add0a3c408557e0a0b929851dc3e8796acd5e59b978b25a330920d",geographyPackage:"4f56b058d79eaa1d0fd0ea2f87c5b55e9c57126acf7a45b5707bcf19300268e8",geographySet:"2e9306e84241e7609a21887d9fe6fd3e20e0d374ef760ab7ba070a0dfd2818fe"} as const;
const PROPOSAL_PARENTS=["dsa-target-factual-projection-20260804-v1","dsa-target-incumbent-roster-20260804-v1","fec-2026-congressional-primary-dates","geo-national-cd119"] as const;
const IDENTITY_PARENTS=["dsa-target-incumbent-roster-20260804-v1","house-democratic-primary-source-selection-proposal-20260804-v1","house-xml","congress-legislators-current-20260804","florida-house-democratic-primary-results-2022-2026-v1"] as const;
const GEOGRAPHY_PARENTS=["house-democratic-primary-source-selection-proposal-20260804-v1","florida-house-democratic-primary-results-2022-2026-v1","florida-current-incumbent-primary-linkage-candidate-v1","census-cd119-plan-change-authority-20260805","tiger-cd118-12","tiger-fl"] as const;
const OUTPUT_PARENTS=["house-democratic-primary-source-selection-proposal-20260804-v1","florida-current-incumbent-primary-linkage-candidate-v1","florida-primary-geography-compatibility-candidate-v1"] as const;
const OUTPUT_FILE_SHA256="0e5082b077aed8b16e88731827b2eafdff633fba480ba2225d98604a096f5453",OUTPUT_BYTE_SIZE=43_234;
type Review=Readonly<{status:"proposed";reviewer:null;reviewedAt:null;resolution:null}>;
type RecordRow=Readonly<{reviewRecordId:string;identityObservationId:string;geographyObservationId:string;contestId:string|null;contestSha256:string|null;cycleYear:2022|2024;electionDate:"2022-08-23"|"2024-08-20";seatCycleId:string;districtCode:string;identity:Readonly<{parentRowSha256:string;status:"candidate"|"source_unobserved";identityStatus:"proposed_identity_link"|"source_unobserved_district_cycle_unresolved";bioguideId:string;officialHouseName:string;sourceCandidateName:string|null;evidenceClass:"exact_name_observation"|"derived_name_relationship"|null;confidence:"high"|null;candidate:boolean;approved:false}>;geography:Readonly<{parentRowSha256:string;status:"candidate";targetCd119Geoid:string;historicalCongressSession:"118"|"119";historicalGeoid:string;evidenceClass:"direct_official_plan_continuity_and_derived_key"|"derived_exact_session_and_key";confidence:"high";candidate:true;approved:false}>;reviewCategory:"identity_and_geography_candidates"|"geography_candidate_identity_source_unobserved";identityDispositionPreserved:true;dispositionDecisionStatus:"unresolved";resultAuthorityStatus:"division_official_results_extract_retained"|null;certificationStatus:"official_results_flag_retained_no_separate_signed_certificate"|null;sourceWinnerStatus:"not_marked_by_source"|"not_applicable_source_unobserved";progressiveClassificationStatus:"not_retained";jointApproved:false;evaluatorUse:"excluded_pending_certification_identity_historical_geography_disposition_classification_review_and_publication_approval";scoreEligible:false;reviewerAction:"review_identity_and_geography_independently"|"review_geography_while_preserving_source_unobserved_identity";rationaleCodes:readonly string[];reviewRecordSha256:string}>;
type DecisionId="fl-primary:accept-official-extract-authority-v1"|"fl-primary:accept-geography-compatibility-v1"|"fl-primary:accept-identity-links-v1"|"fl-primary:retain-primary-disposition-exclusion-v1"|"fl-primary:retain-progressive-classification-exclusion-v1";
type Decision=Readonly<{decisionId:DecisionId;affectedComponent:string;parentDecisionId:string;question:string;recommendedDecision:string;defaultReversibleAssumption:"exclude_affected_records_from_evaluator_and_publication";alternatives:readonly[string,string];consequences:readonly[string,string];confidence:"high";evidenceRecordIds:readonly string[];blocksAffectedPublication:true;blocksOtherWork:false;workCompletedWhileWaiting:string;review:Review}>;
export type FloridaPrimaryJointReviewPackage=Readonly<{schema:typeof FLORIDA_PRIMARY_JOINT_REVIEW_V1;version:1;generatedAt:"2026-08-06T09:00:00.000Z";sourceCutoff:"2026-08-05";reviewerOnly:true;publicationEligible:false;defaultUse:"exclude_from_evaluator_until_independent_certification_identity_geography_disposition_and_classification_review";review:Review;inputs:Readonly<Record<string,unknown>>;methodology:Readonly<Record<string,unknown>>;summary:Readonly<{reviewRecords:14;identityAndGeographyCandidates:7;geographyCandidateIdentitySourceUnobserved:7;identityCandidates:7;geographyCandidates:14;officialExtractAuthorityRecords:7;reportedContestRecords:7;sourceUnobservedRecords:7;proposedDecisions:5;jointApprovedRecords:0;scoreEligibleRecords:0}>;records:readonly RecordRow[];reviewRecordSetSha256:string;decisions:readonly Decision[];decisionSetSha256:string;inheritedDecisionResolutions:Readonly<{certification:null;identity:null;geography:null;disposition:null;progressiveClassification:null}>;packageSha256:string}>;
export type FloridaPrimaryJointReviewInput=Readonly<{proposalJson:string;identityJson:string;geographyJson:string;sourceLockJson:string}>;
const sha=(v:string):string=>createHash("sha256").update(v,"utf8").digest("hex"),digest=(d:string,v:unknown):string=>createHash("sha256").update(d,"ascii").update(canonicalJson(v),"utf8").digest("hex"),order=(a:string,b:string):number=>Buffer.compare(Buffer.from(a),Buffer.from(b)),fail=(c:string):never=>{throw new Error(`Florida primary joint review rejected: ${c}`)};
const parse=<T>(v:string,c:string):T=>{try{return JSON.parse(v) as T}catch{return fail(c)}};
const projection=(rows:readonly RecordRow[])=>rows.map(r=>({reviewRecordId:r.reviewRecordId,identityObservationId:r.identityObservationId,identityParentRowSha256:r.identity.parentRowSha256,geographyObservationId:r.geographyObservationId,geographyParentRowSha256:r.geography.parentRowSha256,contestId:r.contestId,contestSha256:r.contestSha256,identityStatus:r.identity.identityStatus,reviewCategory:r.reviewCategory,resultAuthorityStatus:r.resultAuthorityStatus,certificationStatus:r.certificationStatus}));

export function buildFloridaPrimaryJointReviewPackage(input:FloridaPrimaryJointReviewInput):FloridaPrimaryJointReviewPackage{
 if(sha(input.proposalJson)!==INPUTS.proposalFile||sha(input.identityJson)!==INPUTS.identityFile||sha(input.geographyJson)!==INPUTS.geographyFile)fail("INPUT_HASH_MISMATCH");
 const proposal=validateHouseDemocraticPrimarySourceSelectionProposal(parse(input.proposalJson,"PROPOSAL_JSON_INVALID")),identity=validateFloridaPrimaryIdentityCandidate(parse<FloridaPrimaryIdentityCandidate>(input.identityJson,"IDENTITY_JSON_INVALID")),geography=validateFloridaPrimaryGeographyCandidate(parse<FloridaPrimaryGeographyCandidate>(input.geographyJson,"GEOGRAPHY_JSON_INVALID"));
 const parentIds=["collect-official-state-primary-results-and-certification-v1","approve-historic-primary-candidate-identity-resolution-v1","approve-historical-district-cd119-compatibility-v1","decide-nonstandard-primary-disposition-treatment-v1","approve-progressive-candidate-classification-method-v1"];
 if(proposal.packageSha256!==INPUTS.proposalPackage||identity.packageSha256!==INPUTS.identityPackage||identity.observationSetSha256!==INPUTS.identitySet||geography.packageSha256!==INPUTS.geographyPackage||geography.rowSetSha256!==INPUTS.geographySet||parentIds.some(id=>proposal.decisions.find(d=>d.decisionId===id)?.resolution!==null))fail("PARENT_INVALID");
 const lock=parse<{entries?:Array<{id:string;retainedPath?:string;retainedStatus:string;byteSize?:number;sha256:string;kind:string;parentIds?:string[]}>}>(input.sourceLockJson,"SOURCE_LOCK_JSON_INVALID"),required=[["house-democratic-primary-source-selection-proposal-20260804-v1",INPUTS.proposalFile,"data/metadata/house-democratic-primary-source-selection-proposal-20260804-v1.json","review_proposal",PROPOSAL_PARENTS],["florida-current-incumbent-primary-linkage-candidate-v1",INPUTS.identityFile,"data/metadata/florida-current-incumbent-primary-linkage-candidate-v1.json","review_candidate",IDENTITY_PARENTS],["florida-primary-geography-compatibility-candidate-v1",INPUTS.geographyFile,"data/metadata/florida-primary-geography-compatibility-candidate-v1.json","review_candidate",GEOGRAPHY_PARENTS]] as const;
 if(!Array.isArray(lock.entries))fail("SOURCE_LOCK_MISMATCH");const entries=lock.entries as NonNullable<typeof lock.entries>;if(required.some(([id,file,path,kind,parents])=>{const m=entries.filter(e=>e.id===id);return m.length!==1||m[0]!.sha256!==file||m[0]!.retainedPath!==path||m[0]!.retainedStatus!=="retained"||m[0]!.kind!==kind||canonicalJson(m[0]!.parentIds)!==canonicalJson(parents)}))fail("SOURCE_LOCK_MISMATCH");const output=entries.filter(e=>e.id===FLORIDA_PRIMARY_JOINT_REVIEW_V1);if(String(OUTPUT_FILE_SHA256).length===0?output.length!==0:output.length!==1||output[0]!.sha256!==OUTPUT_FILE_SHA256||output[0]!.byteSize!==OUTPUT_BYTE_SIZE||output[0]!.retainedPath!=="data/metadata/florida-primary-identity-geography-review-package-v1.json"||output[0]!.retainedStatus!=="retained"||output[0]!.kind!=="review_proposal"||canonicalJson(output[0]!.parentIds)!==canonicalJson(OUTPUT_PARENTS))fail("SOURCE_LOCK_MISMATCH");
 const records:RecordRow[]=geography.rows.map(geo=>{const matches=identity.observations.filter(i=>i.observationId===geo.identityObservationId);if(matches.length!==1)fail("PARENT_JOIN_INVALID");const id=matches[0]!;if(geo.identityRowSha256!==id.rowSha256||geo.identityStatus!==id.identityStatus||geo.contestId!==id.contestId||geo.contestSha256!==id.contestSha256||geo.cycleYear!==id.cycleYear||geo.districtCode!==id.districtCode)fail("PARENT_JOIN_INVALID");const candidate=id.identityStatus==="proposed_identity_link";const unsigned={reviewRecordId:`fl-primary-joint:${id.cycleYear}:${id.districtCode}`,identityObservationId:id.observationId,geographyObservationId:geo.observationId,contestId:id.contestId,contestSha256:id.contestSha256,cycleYear:id.cycleYear,electionDate:id.electionDate,seatCycleId:id.seatCycleId,districtCode:id.districtCode,identity:{parentRowSha256:id.rowSha256,status:candidate?"candidate" as const:"source_unobserved" as const,identityStatus:id.identityStatus,bioguideId:id.rosterIdentity.bioguideId,officialHouseName:id.rosterIdentity.officialHouseName,sourceCandidateName:id.sourceCandidate?.sourceCandidateName??null,evidenceClass:id.evidenceClass,confidence:id.confidence,candidate,approved:false as const},geography:{parentRowSha256:geo.rowSha256,status:"candidate" as const,targetCd119Geoid:geo.targetCd119Geoid,historicalCongressSession:geo.historicalCongressSession,historicalGeoid:geo.historicalGeoid,evidenceClass:geo.evidenceClass,confidence:geo.confidence,candidate:true as const,approved:false as const},reviewCategory:candidate?"identity_and_geography_candidates" as const:"geography_candidate_identity_source_unobserved" as const,identityDispositionPreserved:true as const,dispositionDecisionStatus:"unresolved" as const,resultAuthorityStatus:id.resultAuthorityStatus,certificationStatus:id.certificationStatus,sourceWinnerStatus:id.sourceWinnerStatus,progressiveClassificationStatus:"not_retained" as const,jointApproved:false as const,evaluatorUse:"excluded_pending_certification_identity_historical_geography_disposition_classification_review_and_publication_approval" as const,scoreEligible:false as const,reviewerAction:candidate?"review_identity_and_geography_independently" as const:"review_geography_while_preserving_source_unobserved_identity" as const,rationaleCodes:candidate?["identity_candidate_and_geography_candidate_require_independent_review","official_extract_authority_not_identity_or_approval","progressive_classification_not_retained"]:["source_unobserved_identity_preserved","geography_candidate_does_not_create_contest_or_identity","progressive_classification_not_retained"]};return{...unsigned,reviewRecordSha256:digest("dsa-seats:fl-primary-joint-review-row:v1\0",unsigned)}}).sort((a,b)=>order(a.reviewRecordId,b.reviewRecordId));
 const ids=records.map(r=>r.reviewRecordId),reported=records.filter(r=>r.identity.candidate).map(r=>r.reviewRecordId);const review={status:"proposed" as const,reviewer:null,reviewedAt:null,resolution:null};const decision=(decisionId:DecisionId,component:string,parentDecisionId:string,evidenceRecordIds:string[],recommendedDecision:string,work:string):Decision=>({decisionId,affectedComponent:component,parentDecisionId,question:`Review ${component} independently for the scoped Florida records.`,recommendedDecision,defaultReversibleAssumption:"exclude_affected_records_from_evaluator_and_publication",alternatives:["accept_scoped_candidate_evidence","retain_exclusion_or_request_correction"],consequences:["accepted evidence remains separately gated from publication","nonacceptance preserves current exclusion without blocking other work"],confidence:"high",evidenceRecordIds,blocksAffectedPublication:true,blocksOtherWork:false,workCompletedWhileWaiting:work,review});
 const decisions=[decision("fl-primary:accept-official-extract-authority-v1","official extract authority","collect-official-state-primary-results-and-certification-v1",reported,"accept_official_results_flag_as_source_authority_without_claiming_separate_signed_certificate","Seven reported records are source-locked and reconciled; seven source-unobserved records are excluded from this evidence scope."),decision("fl-primary:accept-geography-compatibility-v1","historical geography compatibility","approve-historical-district-cd119-compatibility-v1",ids,"accept_fourteen_geography_candidates_without_geometry_equality_claim","Both complete official district inventories and Census plan-change authority are retained."),decision("fl-primary:accept-identity-links-v1","candidate identity links","approve-historic-primary-candidate-identity-resolution-v1",reported,"accept_seven_name_relationships_and_preserve_seven_source_unobserved_rows","Four exact and three narrowly derived relationships are retained; no generic fuzzy match exists."),decision("fl-primary:retain-primary-disposition-exclusion-v1","primary disposition treatment","decide-nonstandard-primary-disposition-treatment-v1",ids,"retain_reported_and_source_unobserved_distinctions_pending_review","Missing extract blocks remain unresolved and are not zeros or inferred no-primary dispositions."),decision("fl-primary:retain-progressive-classification-exclusion-v1","progressive classification","approve-progressive-candidate-classification-method-v1",ids,"retain_all_records_outside_progressive_classification_until_separate_evidence","No progressive classification evidence is introduced by identity or geography joins.")];
 const parentProjectionSha256=digest("dsa-seats:fl-primary-joint-parent-projection:v1\0",projection(records)),unsigned={schema:FLORIDA_PRIMARY_JOINT_REVIEW_V1,version:1 as const,generatedAt:"2026-08-06T09:00:00.000Z" as const,sourceCutoff:"2026-08-05" as const,reviewerOnly:true as const,publicationEligible:false as const,defaultUse:"exclude_from_evaluator_until_independent_certification_identity_geography_disposition_and_classification_review" as const,review,inputs:{sourceSelectionProposal:{sourceLockId:required[0][0],fileSha256:INPUTS.proposalFile,packageSha256:INPUTS.proposalPackage},identity:{sourceLockId:required[1][0],fileSha256:INPUTS.identityFile,packageSha256:INPUTS.identityPackage,observationSetSha256:INPUTS.identitySet},geography:{sourceLockId:required[2][0],fileSha256:INPUTS.geographyFile,packageSha256:INPUTS.geographyPackage,rowSetSha256:INPUTS.geographySet}},methodology:{joinKey:"identity_observation_id_and_parent_row_hash",decisionEvidenceScopesIndependent:true,automaticDecisionClosure:false,evaluatorNumericValues:0,parentProjectionSha256},summary:{reviewRecords:14 as const,identityAndGeographyCandidates:7 as const,geographyCandidateIdentitySourceUnobserved:7 as const,identityCandidates:7 as const,geographyCandidates:14 as const,officialExtractAuthorityRecords:7 as const,reportedContestRecords:7 as const,sourceUnobservedRecords:7 as const,proposedDecisions:5 as const,jointApprovedRecords:0 as const,scoreEligibleRecords:0 as const},records,reviewRecordSetSha256:digest("dsa-seats:fl-primary-joint-review-row-set:v1\0",records),decisions,decisionSetSha256:digest("dsa-seats:fl-primary-joint-decision-set:v1\0",decisions),inheritedDecisionResolutions:{certification:null,identity:null,geography:null,disposition:null,progressiveClassification:null}};return{...unsigned,packageSha256:digest("dsa-seats:fl-primary-joint-review-package:v1\0",unsigned)};
}

export function validateFloridaPrimaryJointReviewPackage(value:FloridaPrimaryJointReviewPackage):FloridaPrimaryJointReviewPackage{
 if(value.schema!==FLORIDA_PRIMARY_JOINT_REVIEW_V1||value.version!==1||value.generatedAt!=="2026-08-06T09:00:00.000Z"||!value.reviewerOnly||value.publicationEligible||value.review.status!=="proposed"||value.review.reviewer!==null||value.review.reviewedAt!==null||value.review.resolution!==null||value.records.length!==14||value.decisions.length!==5||value.decisions.some(d=>d.review.status!=="proposed"||d.review.reviewer!==null||d.review.reviewedAt!==null||d.review.resolution!==null)||value.records.some(r=>r.jointApproved||r.scoreEligible||r.identity.approved||r.geography.approved))fail("LIFECYCLE_INVALID");
 for(const [i,r]of value.records.entries()){const{reviewRecordSha256,...unsigned}=r,candidate=r.identity.identityStatus==="proposed_identity_link";if(reviewRecordSha256!==digest("dsa-seats:fl-primary-joint-review-row:v1\0",unsigned)||r.reviewRecordId!==`fl-primary-joint:${r.cycleYear}:${r.districtCode}`||r.identityObservationId!==`fl:identity:${r.cycleYear}:${r.districtCode}`||r.geographyObservationId!==`fl:geography:${r.cycleYear}:${r.districtCode}`||r.reviewCategory!==(candidate?"identity_and_geography_candidates":"geography_candidate_identity_source_unobserved")||r.identity.candidate!==candidate||(candidate?(r.contestId===null||r.contestSha256===null||r.resultAuthorityStatus!=="division_official_results_extract_retained"||r.certificationStatus!=="official_results_flag_retained_no_separate_signed_certificate"||r.sourceWinnerStatus!=="not_marked_by_source"):(r.contestId!==null||r.contestSha256!==null||r.resultAuthorityStatus!==null||r.certificationStatus!==null||r.sourceWinnerStatus!=="not_applicable_source_unobserved"))||(i>0&&order(value.records[i-1]!.reviewRecordId,r.reviewRecordId)>=0))fail("RECORD_INVALID");}
 const counts=value.decisions.map(d=>[d.decisionId,d.evidenceRecordIds.length]),expectedCounts=[["fl-primary:accept-official-extract-authority-v1",7],["fl-primary:accept-geography-compatibility-v1",14],["fl-primary:accept-identity-links-v1",7],["fl-primary:retain-primary-disposition-exclusion-v1",14],["fl-primary:retain-progressive-classification-exclusion-v1",14]],all=value.records.map(r=>r.reviewRecordId),reported=value.records.filter(r=>r.identity.candidate).map(r=>r.reviewRecordId);if(canonicalJson(counts)!==canonicalJson(expectedCounts)||value.decisions.some(d=>new Set(d.evidenceRecordIds).size!==d.evidenceRecordIds.length||d.evidenceRecordIds.some(id=>!all.includes(id)))||canonicalJson(value.decisions[0]!.evidenceRecordIds)!==canonicalJson(reported)||canonicalJson(value.decisions[2]!.evidenceRecordIds)!==canonicalJson(reported)||[value.decisions[1]!,value.decisions[3]!,value.decisions[4]!].some(d=>canonicalJson(d.evidenceRecordIds)!==canonicalJson(all)))fail("DECISION_SCOPE_INVALID");
 const summary={reviewRecords:14,identityAndGeographyCandidates:7,geographyCandidateIdentitySourceUnobserved:7,identityCandidates:7,geographyCandidates:14,officialExtractAuthorityRecords:7,reportedContestRecords:7,sourceUnobservedRecords:7,proposedDecisions:5,jointApprovedRecords:0,scoreEligibleRecords:0};if(canonicalJson(value.summary)!==canonicalJson(summary))fail("SUMMARY_INVALID");const{packageSha256,...unsigned}=value;if((FLORIDA_PRIMARY_JOINT_PARENT_PROJECTION_SHA256&&value.methodology.parentProjectionSha256!==FLORIDA_PRIMARY_JOINT_PARENT_PROJECTION_SHA256)||(FLORIDA_PRIMARY_JOINT_RECORD_SET_SHA256&&value.reviewRecordSetSha256!==FLORIDA_PRIMARY_JOINT_RECORD_SET_SHA256)||(FLORIDA_PRIMARY_JOINT_DECISION_SET_SHA256&&value.decisionSetSha256!==FLORIDA_PRIMARY_JOINT_DECISION_SET_SHA256)||(FLORIDA_PRIMARY_JOINT_PACKAGE_SHA256&&packageSha256!==FLORIDA_PRIMARY_JOINT_PACKAGE_SHA256)||value.reviewRecordSetSha256!==digest("dsa-seats:fl-primary-joint-review-row-set:v1\0",value.records)||value.decisionSetSha256!==digest("dsa-seats:fl-primary-joint-decision-set:v1\0",value.decisions)||packageSha256!==digest("dsa-seats:fl-primary-joint-review-package:v1\0",unsigned))fail("PACKAGE_INVALID");return value;
}
export const FLORIDA_PRIMARY_JOINT_OUTPUT_PARENTS=OUTPUT_PARENTS;
