import { createHash } from "node:crypto";

import { canonicalJson } from "../fec/aipac-proposed-packages";
import { validateGeorgiaPrimaryIdentityCandidate, type GeorgiaPrimaryIdentityCandidate } from "./georgia-current-incumbent-primary-linkage-candidate";
import { validateGeorgiaPrimaryGeographyCandidate, type GeorgiaPrimaryGeographyCandidate } from "./georgia-primary-geography-compatibility-candidate";
import { validateHouseDemocraticPrimarySourceSelectionProposal } from "./house-democratic-primary-source-selection-proposal";

export const GEORGIA_PRIMARY_JOINT_REVIEW_V1 = "georgia-primary-identity-geography-review-package-v1" as const;
export const GEORGIA_PRIMARY_JOINT_RECORD_SET_SHA256 = "5088a746de732a2e39fd981bce5afa5c963c9d927f08a1569417a3ad5056b93a";
export const GEORGIA_PRIMARY_JOINT_DECISION_SET_SHA256 = "4d79b4edf91538e21e6e7444996e7dc573f4d4fc981c9b44ca47d14623621f90";
export const GEORGIA_PRIMARY_JOINT_PACKAGE_SHA256 = "51e6177b4ffcb80a367590a5591ead57f5e1802e52543b824740057f6281c9f5";
export const GEORGIA_PRIMARY_JOINT_OUTPUT_FILE_SHA256 = "988b3fd039e74fa80a212460695c189419a8590ecd27c969192acff97565eddf";
export const GEORGIA_PRIMARY_JOINT_OUTPUT_BYTE_SIZE = 42170;
const INPUTS = { proposalFile: "85246e9adfd181e6f24606b6eaa29250c45c9e8e42a6dd5af5cb162de17f45b1", proposalPackage: "a090e0be03dc2b0fa5edd0c1132a8261eed0f98ceb4df090154d0b150d8721fb", identityFile: "1ded7ac81f648fc95259d1d07e967d9aaa59f533f1809e4e0be93a8fcd8a83ff", identityPackage: "00c7c11bd1e75cb5963eea3933d4b652e8ea2e3f4e3793056604e7634cdd25d5", identitySet: "b561d0f9d9c1f14f8cafb690bc40e2bc7742f9715fc419dcb6c75e286101741b", geographyFile: "dda2fc91a18de2ccfac09e5604089d9ec72338be4699b50988f325d7f80c8d8e", geographyPackage: "ec9ec6661e280c370705835c1b4aeb552ed3710a7ee373abbb5105389fb7b206", geographySet: "1aa4005af1d92db89fc31ee16376ed188674c29a088017ecabd9c2e9c790cbcb" } as const;
const PARENTS = ["house-democratic-primary-source-selection-proposal-20260804-v1", "georgia-current-incumbent-primary-linkage-candidate-v1", "georgia-primary-geography-compatibility-candidate-v1"] as const;
const REQUIRED = [
  [PARENTS[0], "urn:dsa-seats:house-democratic-primary-source-selection-proposal:v1:2026-08-04", "data/metadata/house-democratic-primary-source-selection-proposal-20260804-v1.json", 411793, INPUTS.proposalFile, "review_proposal", ["dsa-target-factual-projection-20260804-v1", "dsa-target-incumbent-roster-20260804-v1", "fec-2026-congressional-primary-dates", "geo-national-cd119"]],
  [PARENTS[1], "urn:dsa-seats:georgia-current-incumbent-primary-linkage-candidate:v1:2022-2026", "data/metadata/georgia-current-incumbent-primary-linkage-candidate-v1.json", 30782, INPUTS.identityFile, "review_candidate", ["dsa-target-incumbent-roster-20260804-v1", "house-democratic-primary-source-selection-proposal-20260804-v1", "house-xml", "congress-legislators-current-20260804", "georgia-house-democratic-primary-results-2022-2026-v1"]],
  [PARENTS[2], "urn:dsa-seats:georgia-primary-geography-compatibility-candidate:v1:2022-2026", "data/metadata/georgia-primary-geography-compatibility-candidate-v1.json", 26094, INPUTS.geographyFile, "review_candidate", ["house-democratic-primary-source-selection-proposal-20260804-v1", "georgia-house-democratic-primary-results-2022-2026-v1", "georgia-current-incumbent-primary-linkage-candidate-v1", "tiger-cd119-13", "georgia-cd118-cd119-block-crosswalk-candidate-v1"]],
] as const;
const CONTROL = ["collect-official-state-primary-results-and-certification-v1", "approve-historic-primary-candidate-identity-resolution-v1", "approve-historical-district-cd119-compatibility-v1", "decide-nonstandard-primary-disposition-treatment-v1", "approve-progressive-candidate-classification-method-v1"] as const;
const review = { status: "proposed" as const, reviewer: null, reviewedAt: null, resolution: null };
type Input = { proposalJson: string; identityJson: string; geographyJson: string; sourceLockJson: string };
type LockEntry = { id?: string; url?: string; retainedPath?: string; retainedStatus?: string; byteSize?: number; sha256?: string; kind?: string; parentIds?: readonly string[] };
const sha = (value: string): string => createHash("sha256").update(value).digest("hex");
const digest = (domain: string, value: unknown): string => createHash("sha256").update(domain, "ascii").update(canonicalJson(value), "utf8").digest("hex");
const fail = (code: string): never => { throw new Error(`Georgia primary joint review rejected: ${code}`); };
const parse = <T>(value: string): T => { try { return JSON.parse(value) as T; } catch { return fail("JSON_INVALID"); } };
const exactKeys = (value: unknown, keys: readonly string[]): boolean => typeof value === "object" && value !== null && !Array.isArray(value) && canonicalJson(Object.keys(value).sort()) === canonicalJson([...keys].sort());

export function buildGeorgiaPrimaryJointReviewPackage(input: Input) {
  if (sha(input.proposalJson) !== INPUTS.proposalFile || sha(input.identityJson) !== INPUTS.identityFile || sha(input.geographyJson) !== INPUTS.geographyFile) fail("INPUT_HASH_MISMATCH");
  const proposal = validateHouseDemocraticPrimarySourceSelectionProposal(parse(input.proposalJson)), identity = validateGeorgiaPrimaryIdentityCandidate(parse<GeorgiaPrimaryIdentityCandidate>(input.identityJson)), geography = validateGeorgiaPrimaryGeographyCandidate(parse<GeorgiaPrimaryGeographyCandidate>(input.geographyJson));
  if (proposal.packageSha256 !== INPUTS.proposalPackage || identity.packageSha256 !== INPUTS.identityPackage || identity.observationSetSha256 !== INPUTS.identitySet || geography.packageSha256 !== INPUTS.geographyPackage || geography.rowSetSha256 !== INPUTS.geographySet || identity.review.resolution !== null || geography.review.resolution !== null || CONTROL.some((id) => proposal.decisions.find((row) => row.decisionId === id)?.resolution !== null)) fail("PARENT_INVALID");
  const lock = parse<{ entries?: LockEntry[] }>(input.sourceLockJson), entries = lock.entries ?? fail("SOURCE_LOCK_MISMATCH"); if (!Array.isArray(entries)) fail("SOURCE_LOCK_MISMATCH");
  for (const [id, url, path, bytes, hash, kind, parents] of REQUIRED) { const matches = entries.filter((entry) => entry.id === id), entry = matches[0]; if (matches.length !== 1 || entry?.url !== url || entry.retainedPath !== path || entry.retainedStatus !== "retained" || entry.byteSize !== bytes || entry.sha256 !== hash || entry.kind !== kind || canonicalJson(entry.parentIds) !== canonicalJson(parents)) fail("SOURCE_LOCK_MISMATCH"); }
  const output = entries.filter((entry) => entry.id === GEORGIA_PRIMARY_JOINT_REVIEW_V1); if (GEORGIA_PRIMARY_JOINT_OUTPUT_FILE_SHA256) { const entry = output[0]; if (output.length !== 1 || entry?.url !== "urn:dsa-seats:georgia-primary-identity-geography-review-package:v1:2022-2026" || entry.retainedPath !== "data/metadata/georgia-primary-identity-geography-review-package-v1.json" || entry.retainedStatus !== "retained" || entry.byteSize !== GEORGIA_PRIMARY_JOINT_OUTPUT_BYTE_SIZE || entry.sha256 !== GEORGIA_PRIMARY_JOINT_OUTPUT_FILE_SHA256 || entry.kind !== "review_proposal" || canonicalJson(entry.parentIds) !== canonicalJson(PARENTS)) fail("SOURCE_LOCK_MISMATCH"); } else if (output.length) fail("SOURCE_LOCK_MISMATCH");
  const records = geography.rows.map((geo) => {
    const matches = identity.observations.filter((row) => row.observationId === geo.identityObservationId), person = matches[0]; if (matches.length !== 1 || !person || geo.identityRowSha256 !== person.rowSha256 || geo.sourceContestId !== person.sourceContestId || geo.sourceContestSha256 !== person.sourceContestSha256 || geo.currentTargetDistrictCode !== person.currentTargetDistrictCode || geo.sourceDistrictCode !== person.sourceDistrictCode || geo.cycleYear !== person.cycleYear) fail("JOIN_INVALID");
    const category = geo.compatibilityCandidate ? "identity_and_geography_candidates" as const : geo.compatibilityDisposition === "crosswalk_review_required" ? "identity_candidate_crosswalk_review" as const : geo.compatibilityDisposition === "no_same_block_membership_no_geography_candidate" ? "identity_candidate_no_same_block_geography" as const : "identity_candidate_cd120_geography_pending" as const;
    const unsigned = { reviewRecordId: `ga-primary-joint:${person.cycleYear}:${person.currentTargetDistrictCode}`, identityObservationId: person.observationId, geographyObservationId: geo.geographyObservationId, sourceContestId: person.sourceContestId, sourceContestSha256: person.sourceContestSha256, cycleYear: person.cycleYear, electionDate: person.electionDate, targetSeatId: person.targetSeatId, currentTargetDistrictCode: person.currentTargetDistrictCode, sourceDistrictCode: person.sourceDistrictCode, bioguideId: person.bioguideId, officialHouseName: person.officialHouseName, sourceCandidateName: person.sourceCandidateName, sourceCandidateVotes: person.sourceCandidateVotes, identityParentRowSha256: person.rowSha256, identityStatus: person.identityStatus, identityEvidenceClass: person.evidenceClass, identityConfidence: person.confidence, identityCandidate: true as const, identityApproved: false as const, geographyParentRowSha256: geo.rowSha256, targetCd119Geoid: geo.targetCd119Geoid, historicalCongressSession: geo.historicalCongressSession, historicalGeoid: geo.historicalGeoid, sameBlockCountForTarget: geo.sameBlockCountForTarget, compatibilityDisposition: geo.compatibilityDisposition, geographyEvidenceClass: geo.evidenceClass, geographyConfidence: geo.confidence, geographyCandidate: geo.compatibilityCandidate, geographyApproved: false as const, resultAuthorityStatus: person.resultAuthorityStatus, certificationStatus: person.certificationStatus, sourceWinnerStatus: person.sourceWinnerStatus, nominationConclusion: null, resultConclusion: null, runoffAdvancementConclusion: null, reviewCategory: category, identityDispositionPreserved: true as const, dispositionDecisionStatus: "unresolved" as const, jointApproved: false as const, progressiveClassificationStatus: "not_retained" as const, evaluatorUse: "excluded_pending_authority_identity_historical_geography_disposition_classification_and_publication_review" as const, scoreEligible: false as const, reviewerAction: category === "identity_and_geography_candidates" ? "review_identity_and_geography_independently" as const : category === "identity_candidate_crosswalk_review" ? "review_identity_while_retaining_geography_crosswalk_review" as const : category === "identity_candidate_no_same_block_geography" ? "review_identity_without_creating_geography_candidate" as const : "review_identity_while_retaining_cd120_geography_authority_pending" as const };
    return { ...unsigned, reviewRecordSha256: digest("dsa-seats:ga-primary-joint-row:v1\0", unsigned) };
  }).sort((a, b) => a.reviewRecordId.localeCompare(b.reviewRecordId));
  if (records.length !== 12 || new Set(records.map((row) => row.identityObservationId)).size !== 12 || new Set(records.map((row) => row.geographyObservationId)).size !== 12) fail("CLOSURE_INVALID");
  const ids = records.map((row) => row.reviewRecordId), decision = (decisionId: string, parentDecisionId: string, affectedComponent: string, recommendedDecision: string) => ({ decisionId, parentDecisionId, affectedComponent, question: `Review ${affectedComponent} independently for all twelve Georgia records.`, recommendedDecision, defaultReversibleAssumption: "exclude_affected_records_from_evaluator_and_publication" as const, alternatives: ["accept_scoped_candidate_evidence", "retain_exclusion_or_request_correction"] as const, consequences: ["accepted evidence remains separately gated from publication", "nonacceptance preserves exclusion without blocking other work"] as const, confidence: "high" as const, evidenceRecordIds: ids, blocksAffectedPublication: true as const, blocksOtherWork: false as const, review });
  const decisions = [decision("ga-primary:accept-official-result-authority-v1", CONTROL[0], "official result authority", "accept_twelve_portal_official_workbook_observations_without_winner_nomination_runoff_or_separate_certificate_claims"), decision("ga-primary:accept-geography-compatibility-v1", CONTROL[2], "historical geography compatibility", "accept_five_geography_candidates_retain_two_split_reviews_one_zero_membership_rejection_and_four_cd120_pending_rows"), decision("ga-primary:accept-identity-links-v1", CONTROL[1], "candidate identity links", "accept_seven_exact_and_five_derived_identity_candidates_without_direct_identifier_bridge"), decision("ga-primary:retain-primary-disposition-exclusion-v1", CONTROL[3], "primary disposition treatment", "retain_source_winner_unmarked_and_null_nomination_result_and_runoff_conclusions"), decision("ga-primary:retain-progressive-classification-exclusion-v1", CONTROL[4], "progressive classification", "retain_all_records_outside_progressive_classification_until_separate_evidence")];
  const summary = { reviewRecords: 12 as const, identityAndGeographyCandidates: 5 as const, identityCandidateCrosswalkReview: 2 as const, identityCandidateNoSameBlockGeography: 1 as const, identityCandidateCd120GeographyPending: 4 as const, officialAuthorityRecords: 12 as const, identityCandidates: 12 as const, geographyCandidates: 5 as const, exactIdentityCandidates: 7 as const, derivedIdentityCandidates: 5 as const, proposedDecisions: 5 as const, jointApprovedRecords: 0 as const, scoreEligibleRecords: 0 as const };
  const sources = entries.filter((entry) => PARENTS.includes(entry.id as typeof PARENTS[number]));
  const unsigned = { schema: GEORGIA_PRIMARY_JOINT_REVIEW_V1, version: 1 as const, generatedAt: "2026-08-07T09:00:00.000Z" as const, sourceCutoff: "2026-08-07" as const, reviewerOnly: true as const, publicationEligible: false as const, defaultUse: "exclude_from_evaluator_until_independent_authority_identity_geography_disposition_classification_and_publication_review" as const, review, inputs: { proposal: { sourceLockId: PARENTS[0], fileSha256: INPUTS.proposalFile, packageSha256: INPUTS.proposalPackage }, identity: { sourceLockId: PARENTS[1], fileSha256: INPUTS.identityFile, packageSha256: INPUTS.identityPackage, observationSetSha256: INPUTS.identitySet }, geography: { sourceLockId: PARENTS[2], fileSha256: INPUTS.geographyFile, packageSha256: INPUTS.geographyPackage, rowSetSha256: INPUTS.geographySet } }, sources, sourceSetSha256: digest("dsa-seats:ga-primary-joint-source-set:v1\0", sources), methodology: { joinKey: "identity_observation_id_and_parent_row_hash" as const, decisionsReviewedIndependently: true as const, jointPackageApprovesParents: false as const, automaticApprovals: 0 as const, evaluatorNumericValues: 0 as const, overlapThresholdUsed: false as const, alternateTargetDistrictSelected: false as const, cd120ContinuityInferred: false as const, rawGeometryEqualityAssessed: false as const, populationEquivalenceAssessed: false as const }, summary, records, reviewRecordSetSha256: digest("dsa-seats:ga-primary-joint-row-set:v1\0", records), decisions, decisionSetSha256: digest("dsa-seats:ga-primary-joint-decision-set:v1\0", decisions), inheritedDecisionResolutions: { authority: null, identity: null, geography: null, disposition: null, progressiveClassification: null } };
  return { ...unsigned, packageSha256: digest("dsa-seats:ga-primary-joint-package:v1\0", unsigned) };
}

export type GeorgiaPrimaryJointReviewPackage = ReturnType<typeof buildGeorgiaPrimaryJointReviewPackage>;
const TOP_KEYS = ["schema", "version", "generatedAt", "sourceCutoff", "reviewerOnly", "publicationEligible", "defaultUse", "review", "inputs", "sources", "sourceSetSha256", "methodology", "summary", "records", "reviewRecordSetSha256", "decisions", "decisionSetSha256", "inheritedDecisionResolutions", "packageSha256"] as const;
const RECORD_KEYS = ["bioguideId", "certificationStatus", "compatibilityDisposition", "currentTargetDistrictCode", "cycleYear", "dispositionDecisionStatus", "electionDate", "evaluatorUse", "geographyApproved", "geographyCandidate", "geographyConfidence", "geographyEvidenceClass", "geographyObservationId", "geographyParentRowSha256", "historicalCongressSession", "historicalGeoid", "identityApproved", "identityCandidate", "identityConfidence", "identityDispositionPreserved", "identityEvidenceClass", "identityObservationId", "identityParentRowSha256", "identityStatus", "jointApproved", "nominationConclusion", "officialHouseName", "progressiveClassificationStatus", "resultAuthorityStatus", "resultConclusion", "reviewCategory", "reviewRecordId", "reviewRecordSha256", "reviewerAction", "runoffAdvancementConclusion", "sameBlockCountForTarget", "scoreEligible", "sourceCandidateName", "sourceCandidateVotes", "sourceContestId", "sourceContestSha256", "sourceDistrictCode", "sourceWinnerStatus", "targetCd119Geoid", "targetSeatId"] as const;
export function validateGeorgiaPrimaryJointReviewPackage(value: GeorgiaPrimaryJointReviewPackage) {
  const { packageSha256, ...unsigned } = value;
  if (!exactKeys(value, TOP_KEYS) || value.schema !== GEORGIA_PRIMARY_JOINT_REVIEW_V1 || !value.reviewerOnly || value.publicationEligible || canonicalJson(value.review) !== canonicalJson(review) || canonicalJson(value.summary) !== canonicalJson({ reviewRecords: 12, identityAndGeographyCandidates: 5, identityCandidateCrosswalkReview: 2, identityCandidateNoSameBlockGeography: 1, identityCandidateCd120GeographyPending: 4, officialAuthorityRecords: 12, identityCandidates: 12, geographyCandidates: 5, exactIdentityCandidates: 7, derivedIdentityCandidates: 5, proposedDecisions: 5, jointApprovedRecords: 0, scoreEligibleRecords: 0 }) || value.records.length !== 12 || value.decisions.length !== 5) fail("PACKAGE_INVALID");
  const expectedCategories = ["identity_and_geography_candidates", "identity_candidate_crosswalk_review", "identity_candidate_crosswalk_review", "identity_candidate_no_same_block_geography", "identity_and_geography_candidates", "identity_and_geography_candidates", "identity_and_geography_candidates", "identity_and_geography_candidates", "identity_candidate_cd120_geography_pending", "identity_candidate_cd120_geography_pending", "identity_candidate_cd120_geography_pending", "identity_candidate_cd120_geography_pending"];
  if (value.records.some((row, index) => { if (!exactKeys(row, RECORD_KEYS)) return true; const rowUnsigned = structuredClone(row) as Partial<typeof row>; delete rowUnsigned.reviewRecordSha256; return row.reviewRecordSha256 !== digest("dsa-seats:ga-primary-joint-row:v1\0", rowUnsigned) || row.reviewCategory !== expectedCategories[index] || row.identityApproved || row.geographyApproved || row.jointApproved || row.scoreEligible || row.sourceWinnerStatus !== "not_marked_by_source" || row.resultAuthorityStatus !== "secretary_official_results_workbook_retained" || row.certificationStatus !== "official_results_flag_retained_no_separate_signed_certificate" || row.nominationConclusion !== null || row.resultConclusion !== null || row.runoffAdvancementConclusion !== null || row.progressiveClassificationStatus !== "not_retained" || (row.reviewCategory === "identity_and_geography_candidates") !== row.geographyCandidate || (row.reviewCategory === "identity_candidate_no_same_block_geography" && (row.sameBlockCountForTarget !== 0 || row.sourceDistrictCode !== "07" || row.currentTargetDistrictCode !== "06")); })) fail("ROW_INVALID");
  if (value.records.filter((row) => row.identityEvidenceClass === "exact_name_observation").length !== 7 || value.records.filter((row) => row.identityEvidenceClass === "derived_name_relationship").length !== 5) fail("ROW_INVALID");
  const ids = value.records.map((row) => row.reviewRecordId); if (value.decisions.some((decision) => canonicalJson(decision.review) !== canonicalJson(review) || canonicalJson(decision.evidenceRecordIds) !== canonicalJson(ids))) fail("DECISION_INVALID");
  if (value.reviewRecordSetSha256 !== digest("dsa-seats:ga-primary-joint-row-set:v1\0", value.records) || (GEORGIA_PRIMARY_JOINT_RECORD_SET_SHA256 && value.reviewRecordSetSha256 !== GEORGIA_PRIMARY_JOINT_RECORD_SET_SHA256) || value.decisionSetSha256 !== digest("dsa-seats:ga-primary-joint-decision-set:v1\0", value.decisions) || (GEORGIA_PRIMARY_JOINT_DECISION_SET_SHA256 && value.decisionSetSha256 !== GEORGIA_PRIMARY_JOINT_DECISION_SET_SHA256) || packageSha256 !== digest("dsa-seats:ga-primary-joint-package:v1\0", unsigned) || (GEORGIA_PRIMARY_JOINT_PACKAGE_SHA256 && packageSha256 !== GEORGIA_PRIMARY_JOINT_PACKAGE_SHA256)) fail("PACKAGE_INVALID"); return value;
}
