import { createHash } from "node:crypto";

import { canonicalJson } from "../fec/aipac-proposed-packages";
import { validateDsaTargetIncumbentRoster } from "../identity/incumbent-tenure-factual-candidate";
import { validateGeorgiaPrimaryResultsReceipt, type GeorgiaPrimaryResultsReceipt } from "./georgia-house-democratic-primary-results-receipt";
import { validateHouseDemocraticPrimarySourceSelectionProposal } from "./house-democratic-primary-source-selection-proposal";

export const GEORGIA_PRIMARY_IDENTITY_V1 = "georgia-current-incumbent-primary-linkage-candidate-v1" as const;
const INPUTS = { rosterFile: "8ae9bb3423e6160d00b5395186c42550e28811b817a482650875d87de71079e1", rosterPackage: "cf068848595dee99882ae74a6bef2b76061597fe0daa3c86b30c71bdcae18fee", proposalFile: "85246e9adfd181e6f24606b6eaa29250c45c9e8e42a6dd5af5cb162de17f45b1", proposalPackage: "a090e0be03dc2b0fa5edd0c1132a8261eed0f98ceb4df090154d0b150d8721fb", receiptFile: "cbf01649db31686e053544e2d616a1a52055117ee3f2747e8fed530266eb9308", receiptPackage: "0048130e863daae9d527528a1a004b73e811ff27ad1fac1d4d98ca13937944ee", receiptContestSet: "63233fddde9cf2a21543e7eb40ff182ed66d5a6b138108dcc43ad4577a74e82e", receiptTargetSet: "37413c20ce73f52e08990c321f397b15a788211aca8d6a18f5a2ec5c82881d06", houseFile: "4ccea8259aff2df6a175545e45bdac2dfcdf0085a9cc7ab6c46aa80527bc524b", congressFile: "bc48cccd12df96164e5a2415fc41e838ca255fe85c297731515529692f7982cf" } as const;
const TARGETS = {
  "02": { seat: "seat_house_ga_02_current", bioguide: "B000490", official: "Sanford D. Bishop, Jr.", methods: { 2022: "derived_source_middle_initial_and_suffix_omission", 2024: "derived_source_middle_initial_and_suffix_omission", 2026: "derived_source_middle_initial_and_suffix_omission" } },
  "04": { seat: "seat_house_ga_04_current", bioguide: "J000288", official: 'Henry C. "Hank" Johnson, Jr.', methods: { 2022: "exact_normalized_official_name_after_source_marker_removal", 2024: "derived_source_middle_initial_omission_with_nickname_match", 2026: "derived_source_middle_initial_omission_with_nickname_match" } },
  "05": { seat: "seat_house_ga_05_current", bioguide: "W000788", official: "Nikema Williams", methods: { 2022: "exact_normalized_official_name_after_source_marker_removal", 2024: "exact_normalized_official_name_after_source_marker_removal", 2026: "exact_normalized_official_name_after_source_marker_removal" } },
  "06": { seat: "seat_house_ga_06_current", bioguide: "M001208", official: "Lucy McBath", methods: { 2022: "exact_normalized_official_name_after_source_marker_removal", 2024: "exact_normalized_official_name_after_source_marker_removal", 2026: "exact_normalized_official_name_after_source_marker_removal" } },
} as const;
const OUTPUT_PARENTS = ["dsa-target-incumbent-roster-20260804-v1", "house-democratic-primary-source-selection-proposal-20260804-v1", "house-xml", "congress-legislators-current-20260804", "georgia-house-democratic-primary-results-2022-2026-v1"] as const;
const REQUIRED = [
  ["dsa-target-incumbent-roster-20260804-v1", "urn:dsa-seats:dsa-target-incumbent-roster:v1:2026-08-04", "data/metadata/dsa-target-incumbent-roster-20260804-v1.json", 21001, INPUTS.rosterFile, "production_projection_receipt", ["congress-legislators-current-20260804", "dsa-target-factual-projection-20260804-v1"]],
  ["house-democratic-primary-source-selection-proposal-20260804-v1", "urn:dsa-seats:house-democratic-primary-source-selection-proposal:v1:2026-08-04", "data/metadata/house-democratic-primary-source-selection-proposal-20260804-v1.json", 411793, INPUTS.proposalFile, "review_proposal", ["dsa-target-factual-projection-20260804-v1", "dsa-target-incumbent-roster-20260804-v1", "fec-2026-congressional-primary-dates", "geo-national-cd119"]],
  ["house-xml", "https://clerk.house.gov/xml/lists/MemberData.xml", "data/source/identity/house-member-data.xml", 556140, INPUTS.houseFile, "source", []],
  ["congress-legislators-current-20260804", "https://unitedstates.github.io/congress-legislators/legislators-current.json", "data/source/identity/congress-legislators-current-20260804.json", 1466894, INPUTS.congressFile, "source", []],
  ["georgia-house-democratic-primary-results-2022-2026-v1", "urn:dsa-seats:georgia-house-democratic-primary-results:v1:2022-2026", "data/metadata/georgia-house-democratic-primary-results-2022-2026-v1.json", 101663, INPUTS.receiptFile, "review_candidate", ["house-democratic-primary-source-selection-proposal-20260804-v1", "ga-2022-general-primary-total-votes-workbook", "ga-2024-general-primary-total-votes-workbook", "ga-2026-general-primary-total-votes-workbook"]],
] as const;
export const GEORGIA_PRIMARY_IDENTITY_OBSERVATION_SET_SHA256 = "b561d0f9d9c1f14f8cafb690bc40e2bc7742f9715fc419dcb6c75e286101741b";
export const GEORGIA_PRIMARY_IDENTITY_PACKAGE_SHA256 = "00c7c11bd1e75cb5963eea3933d4b652e8ea2e3f4e3793056604e7634cdd25d5";
export const GEORGIA_PRIMARY_IDENTITY_FILE_SHA256 = "1ded7ac81f648fc95259d1d07e967d9aaa59f533f1809e4e0be93a8fcd8a83ff";
const OUTPUT = { hash: GEORGIA_PRIMARY_IDENTITY_FILE_SHA256, bytes: 30782 } as const;
const GATES = ["review_incumbent_candidate_identity", "review_historical_district_compatibility_including_georgia_cd119_redraw", "review_regular_primary_and_runoff_disposition", "review_progressive_candidate_classification", "complete_human_data_review_and_publication_approval"] as const;
type Input = Readonly<{ roster: unknown; rosterFileSha256: string; proposal: unknown; proposalFileSha256: string; receipt: GeorgiaPrimaryResultsReceipt; receiptFileSha256: string; houseXml: string; houseFileSha256: string; congressJson: string; congressFileSha256: string; sourceLock: unknown }>;
const fail = (code: string): never => { throw new Error(`Georgia primary identity rejected: ${code}`); };
const sha = (value: string): string => createHash("sha256").update(value, "utf8").digest("hex");
const digest = (domain: string, value: unknown): string => createHash("sha256").update(domain, "ascii").update(canonicalJson(value), "utf8").digest("hex");
const normalize = (value: string): string => value.normalize("NFKD").replace(/[\u0300-\u036f]/g, "").toLowerCase().replace(/[^a-z0-9]+/g, " ").trim().replace(/\s+/g, " ");
const sourceName = (value: string): string => value.replace(/\s*\(I\)\s*$/, "").replace(/""/g, '"').trim();
const tag = (block: string, name: string): string => block.match(new RegExp(`<${name}(?: [^>]*)?>([^<]*)</${name}>`))?.[1] ?? "";

export function buildGeorgiaPrimaryIdentityCandidate(input: Input) {
  if (input.rosterFileSha256 !== INPUTS.rosterFile || input.proposalFileSha256 !== INPUTS.proposalFile || input.receiptFileSha256 !== INPUTS.receiptFile || input.houseFileSha256 !== INPUTS.houseFile || input.congressFileSha256 !== INPUTS.congressFile || sha(input.houseXml) !== INPUTS.houseFile || sha(input.congressJson) !== INPUTS.congressFile) fail("INPUT_HASH_MISMATCH");
  const roster = validateDsaTargetIncumbentRoster(input.roster), proposal = validateHouseDemocraticPrimarySourceSelectionProposal(input.proposal), receipt = validateGeorgiaPrimaryResultsReceipt(input.receipt);
  if (roster.rosterSha256 !== INPUTS.rosterPackage || proposal.packageSha256 !== INPUTS.proposalPackage || receipt.packageSha256 !== INPUTS.receiptPackage || receipt.summary.contestSetSha256 !== INPUTS.receiptContestSet || receipt.summary.targetObservationSetSha256 !== INPUTS.receiptTargetSet || ["approve-historic-primary-candidate-identity-resolution-v1", "decide-nonstandard-primary-disposition-treatment-v1"].some((id) => proposal.decisions.find((item) => item.decisionId === id)?.resolution !== null)) fail("PARENT_INVALID");
  const lock = input.sourceLock as { entries?: Array<{ id?: string; url?: string; retainedPath?: string; retainedStatus?: string; byteSize?: number; sha256?: string; kind?: string; parentIds?: string[] }> }; if (!Array.isArray(lock.entries)) fail("SOURCE_LOCK_MISMATCH");
  const lockEntries = lock.entries as NonNullable<typeof lock.entries>; if (REQUIRED.some(([id, url, path, bytes, hash, kind, parents]) => { const matches = lockEntries.filter((entry) => entry.id === id), entry = matches[0]; return matches.length !== 1 || entry?.url !== url || entry.retainedPath !== path || entry.retainedStatus !== "retained" || entry.byteSize !== bytes || entry.sha256 !== hash || entry.kind !== kind || canonicalJson(entry.parentIds) !== canonicalJson(parents); })) fail("SOURCE_LOCK_MISMATCH");
  const output = lockEntries.filter((entry) => entry.id === GEORGIA_PRIMARY_IDENTITY_V1); if (OUTPUT.hash ? output.length !== 1 || output[0]?.url !== "urn:dsa-seats:georgia-current-incumbent-primary-linkage-candidate:v1:2022-2026" || output[0].retainedPath !== "data/metadata/georgia-current-incumbent-primary-linkage-candidate-v1.json" || output[0].retainedStatus !== "retained" || output[0].byteSize !== OUTPUT.bytes || output[0].sha256 !== OUTPUT.hash || output[0].kind !== "review_candidate" || canonicalJson(output[0].parentIds) !== canonicalJson(OUTPUT_PARENTS) : output.length !== 0) fail("SOURCE_LOCK_MISMATCH");
  let people: Array<{ id?: { bioguide?: string }; name?: { official_full?: string }; terms?: Array<{ type?: string; state?: string; district?: number }> }>; try { people = JSON.parse(input.congressJson); } catch { return fail("CONGRESS_JSON_INVALID"); } if (!Array.isArray(people)) fail("CONGRESS_JSON_INVALID");
  const members = [...input.houseXml.matchAll(/<member>([\s\S]*?)<\/member>/g)].map((match) => match[1]!);
  for (const [district, target] of Object.entries(TARGETS)) { const rosterMatches = roster.rows.filter((row) => row.seatCycleId === target.seat && row.bioguideId === target.bioguide), personMatches = people.filter((person) => person.id?.bioguide === target.bioguide), clerkMatches = members.filter((member) => tag(member, "bioguideID") === target.bioguide), term = personMatches[0]?.terms?.at(-1); if (rosterMatches.length !== 1 || personMatches.length !== 1 || personMatches[0]?.name?.official_full !== target.official || term?.type !== "rep" || term.state !== "GA" || String(term.district).padStart(2, "0") !== district || clerkMatches.length !== 1 || tag(clerkMatches[0]!, "statedistrict") !== `GA${district}` || tag(clerkMatches[0]!, "official-name") !== target.official) fail("CURRENT_IDENTITY_INVALID"); }
  const mcbath = people.find((person) => person.id?.bioguide === "M001208"); if (!mcbath || ![["2021-01-03", 6], ["2023-01-03", 7], ["2025-01-03", 6]].every(([start, district]) => mcbath.terms?.some((term) => (term as { start?: string }).start === start && term.state === "GA" && term.district === district))) fail("HISTORICAL_TERM_EVIDENCE_INVALID");
  const contests = new Map(receipt.contests.map((contest) => [contest.contestId, contest]));
  const observations = receipt.targetObservations.map((parent) => {
    const target = TARGETS[parent.currentTargetDistrictCode as keyof typeof TARGETS] ?? fail("TARGET_INVALID"), contest = contests.get(parent.contestId) ?? fail("CONTEST_MISSING"), matches = contest.candidates.filter((candidate) => candidate.sourceCandidateName === parent.sourceCandidateNameObservation); if (matches.length !== 1) fail("SOURCE_CANDIDATE_INVALID"); const candidate = matches[0]!;
    const method = target.methods[parent.cycleYear], exact = method.startsWith("exact_"); if (exact && normalize(sourceName(candidate.sourceCandidateName)) !== normalize(target.official)) fail("SOURCE_CANDIDATE_INVALID"); if (!exact && parent.currentTargetDistrictCode === "02" && normalize(sourceName(candidate.sourceCandidateName)) !== "sanford bishop") fail("SOURCE_CANDIDATE_INVALID"); if (!exact && parent.currentTargetDistrictCode === "04" && normalize(sourceName(candidate.sourceCandidateName)) !== "henry hank johnson jr") fail("SOURCE_CANDIDATE_INVALID");
    const unsigned = { observationId: `ga:identity:${parent.cycleYear}:${parent.currentTargetDistrictCode}`, cycleYear: parent.cycleYear, electionDate: contest.electionDate, targetSeatId: target.seat, bioguideId: target.bioguide, officialHouseName: target.official, currentTargetDistrictCode: parent.currentTargetDistrictCode, sourceDistrictCode: parent.sourceDistrictCode, parentTargetObservationId: parent.observationId, parentTargetObservationSha256: parent.observationSha256, sourceContestId: contest.contestId, sourceContestSha256: contest.contestSha256, sourceCandidateCount: contest.candidates.length, sourceContestVotes: contest.sourceTotalVotes, sourceCandidateName: candidate.sourceCandidateName, sourceChoiceId: candidate.sourceChoiceId, sourceCandidateVotes: candidate.votes, sourceIncumbentMarkerStatus: "observed_not_identity_evidence" as const, identityStatus: "proposed_identity_link" as const, directIdentifierBridgeAvailable: false as const, matchMethod: method, evidenceClass: exact ? "exact_name_observation" as const : "derived_name_relationship" as const, confidence: "high" as const, resultAuthorityStatus: contest.resultAuthorityStatus, certificationStatus: contest.certificationStatus, sourceWinnerStatus: contest.sourceWinnerStatus, winnerConclusion: null, nominationConclusion: null, runoffAdvancementConclusion: null, identityApproved: false as const, geographyStatus: "separate_candidate_not_approved" as const, historicalGeographyCompatibilityClaim: null, selectionStatus: "unselected_source_winner_unmarked" as const, evaluatorUse: "excluded_pending_identity_geography_disposition_classification_and_publication_review" as const, scoreEligible: false as const, rationaleCodes: [exact ? "normalized_source_name_matches_current_official_name_after_incumbent_marker_removal" : method.includes("suffix") ? "source_name_omits_current_official_middle_initial_and_suffix" : "source_name_omits_current_official_middle_initial_while_nickname_and_suffix_match", parent.sourceDistrictCode === parent.currentTargetDistrictCode ? "source_and_current_district_numbers_match_without_geography_approval" : "congress_legislators_term_history_supports_person_identity_across_district_change_without_geography_claim", "source_incumbent_marker_not_used_as_identity_bridge"] };
    return { ...unsigned, rowSha256: digest("dsa-seats:ga-primary-identity-row:v1\0", unsigned) };
  });
  const summary = { targetSeats: 4 as const, observations: 12 as const, proposedIdentityLinks: 12 as const, exactNameObservations: 7 as const, derivedNameRelationships: 5 as const, linkedCandidateVotes: observations.reduce((sum, row) => sum + row.sourceCandidateVotes, 0), directIdentifierBridges: 0 as const, automaticallyApprovedRows: 0 as const, selectedRows: 0 as const, scoreEligibleRows: 0 as const };
  if (summary.linkedCandidateVotes !== 881116 || observations.filter((row) => row.evidenceClass === "exact_name_observation").length !== 7 || observations.filter((row) => row.evidenceClass === "derived_name_relationship").length !== 5) fail("SUMMARY_INVALID");
  const observationSetSha256 = digest("dsa-seats:ga-primary-identity-row-set:v1\0", observations), unsigned = { schema: GEORGIA_PRIMARY_IDENTITY_V1, version: 1 as const, generatedAt: "2026-08-07T07:30:00.000Z" as const, sourceCutoff: "2026-08-07" as const, reviewerOnly: true as const, publicationEligible: false as const, defaultUse: "exclude_from_evaluator_until_identity_geography_disposition_classification_and_publication_review" as const, review: { status: "proposed" as const, reviewer: null, reviewedAt: null, resolution: null }, inheritedUnresolvedGates: GATES, inputs: { roster: { sourceLockId: REQUIRED[0][0], fileSha256: INPUTS.rosterFile, rosterSha256: INPUTS.rosterPackage }, proposal: { sourceLockId: REQUIRED[1][0], fileSha256: INPUTS.proposalFile, packageSha256: INPUTS.proposalPackage }, houseClerk: { sourceLockId: REQUIRED[2][0], fileSha256: INPUTS.houseFile }, congressLegislators: { sourceLockId: REQUIRED[3][0], fileSha256: INPUTS.congressFile }, receipt: { sourceLockId: REQUIRED[4][0], fileSha256: INPUTS.receiptFile, packageSha256: INPUTS.receiptPackage, contestSetSha256: INPUTS.receiptContestSet, targetObservationSetSha256: INPUTS.receiptTargetSet } }, methodology: { scope: "four_current_georgia_target_seats_times_three_regular_primary_cycles", identityMethod: "exact_or_documented_middle_initial_and_suffix_omission_source_name_relationship", sourceIncumbentMarkerTreatment: "retained_as_source_text_not_identity_evidence", historicalDistrictTreatment: "identity_can_be_observed_across_source_district_change_without_geography_compatibility_claim", sourceWinnerTreatment: "not_marked_by_source_no_vote_rank_inference", runoffTreatment: "separate_events_not_retained_or_assessed", directIdentifierBridgeAvailable: false, automaticDecisionClosure: false, evaluatorNumericValues: 0 }, summary, observations, observationSetSha256, decisionSupport: { decisionId: "approve-historic-primary-candidate-identity-resolution-v1" as const, status: "proposed" as const, recommendedResolution: "accept_seven_exact_and_five_documented_name_relationship_candidates_while_reviewing_geography_separately" as const, defaultAssumption: "exclude_all_rows_from_evaluator_until_identity_geography_disposition_classification_and_publication_review" as const, affectedObservationIds: observations.map((row) => row.observationId), reviewerResolution: null, reviewer: null, reviewedAt: null } };
  return { ...unsigned, packageSha256: digest("dsa-seats:ga-primary-identity-candidate:v1\0", unsigned) };
}
export type GeorgiaPrimaryIdentityCandidate = ReturnType<typeof buildGeorgiaPrimaryIdentityCandidate>;
export function validateGeorgiaPrimaryIdentityCandidate(value: GeorgiaPrimaryIdentityCandidate): GeorgiaPrimaryIdentityCandidate { const {packageSha256,...unsigned}=value,set=digest("dsa-seats:ga-primary-identity-row-set:v1\0",value.observations);if(value.schema!==GEORGIA_PRIMARY_IDENTITY_V1||value.version!==1||!value.reviewerOnly||value.publicationEligible||value.review.status!=="proposed"||value.review.reviewer!==null||value.review.reviewedAt!==null||value.review.resolution!==null||value.observations.length!==12||value.summary.exactNameObservations!==7||value.summary.derivedNameRelationships!==5||value.summary.linkedCandidateVotes!==881116||value.observations.some((row)=>{const{rowSha256,...rest}=row;return rowSha256!==digest("dsa-seats:ga-primary-identity-row:v1\0",rest)||row.identityStatus!=="proposed_identity_link"||row.directIdentifierBridgeAvailable||row.identityApproved||row.geographyStatus!=="separate_candidate_not_approved"||row.historicalGeographyCompatibilityClaim!==null||row.sourceWinnerStatus!=="not_marked_by_source"||row.winnerConclusion!==null||row.nominationConclusion!==null||row.runoffAdvancementConclusion!==null||row.scoreEligible})||value.observations.find((row)=>row.observationId==="ga:identity:2022:06")?.sourceDistrictCode!=="07"||set!==GEORGIA_PRIMARY_IDENTITY_OBSERVATION_SET_SHA256||value.observationSetSha256!==set||packageSha256!==GEORGIA_PRIMARY_IDENTITY_PACKAGE_SHA256||packageSha256!==digest("dsa-seats:ga-primary-identity-candidate:v1\0",unsigned))fail("PACKAGE_INVARIANT_INVALID");return value;}
