import { createHash } from "node:crypto";
import { readFileSync } from "node:fs";
import { resolve } from "node:path";

import { describe, expect, it } from "vitest";

import { buildHouseDemocraticPrimarySourceSelectionProposal, validateHouseDemocraticPrimarySourceSelectionProposal } from "./house-democratic-primary-source-selection-proposal";

const bytes = (path: string): Buffer => readFileSync(resolve(path));
const sha = (path: string): string => createHash("sha256").update(bytes(path)).digest("hex");
const projectionPath = "data/metadata/dsa-target-factual-projection-20260804-v1.json";
const rosterPath = "data/metadata/dsa-target-incumbent-roster-20260804-v1.json";
const artifactPath = "data/metadata/house-democratic-primary-source-selection-proposal-20260804-v1.json";
const projection = JSON.parse(bytes(projectionPath).toString("utf8"));
const roster = JSON.parse(bytes(rosterPath).toString("utf8"));

describe("House Democratic primary source-selection proposal", () => {
  const proposal = buildHouseDemocraticPrimarySourceSelectionProposal({ projection, projectionFileSha256: sha(projectionPath), roster, rosterFileSha256: sha(rosterPath) });

  it("creates the exact 212-seat, 38-state, three-cycle all-missing reviewer-only plan", () => {
    const parsed = validateHouseDemocraticPrimarySourceSelectionProposal(proposal);
    expect(parsed.scope).toEqual({ releaseId: "rel_full_20260804_v2", universeDefinition: "occupied regular Democratic voting U.S. House seats", targetSeats: 212, targetStates: 38, targetUniverseSha256: "48dbd88aa49c6e12cc7c3e69cfd64a714758cd7aafcea65a94917bfb660acd54", cycles: [2022, 2024, 2026] });
    expect(parsed.stateCycles).toHaveLength(114);
    expect(parsed.seats).toHaveLength(212);
    expect(new Set(parsed.stateCycles.map((row) => `${row.stateCode}:${row.cycleYear}`)).size).toBe(114);
    expect(parsed.stateCycles.every((row) => row.resultAuthorityStatus === "not_retained" && row.certificationStatus === "unassessed" && row.resultSnapshotIds.length === 0)).toBe(true);
    expect(parsed.seats.every((row) => row.selection.selectedCycle === null && row.selection.selectedContestId === null && row.selection.incumbentCandidateIdentity === null && row.geography.crosswalkSnapshotIds.length === 0 && !row.scoreEligible)).toBe(true);
    expect(parsed.seats.every((row) => row.evaluatorValues.priorPrimaryMargin.reason === "primary_result_authority_not_retained" && row.evaluatorValues.priorDemocraticPrimaryVotes.reason === "primary_result_authority_not_retained" && row.evaluatorValues.priorProgressivePrimaryShare.reason === "progressive_candidate_classification_not_retained")).toBe(true);
  });

  it("binds the four fixed input receipts and six literal source classes and decisions", () => {
    expect(proposal.inputs.projection.fileSha256).toBe(sha(projectionPath));
    expect(proposal.inputs.roster.fileSha256).toBe(sha(rosterPath));
    expect(proposal.inputs.fecDiscovery).toMatchObject({ sourceLockId: "fec-2026-congressional-primary-dates", byteSize: 226820, authorityRole: "nationwide_discovery_and_drift_detection_not_state_result_authority" });
    expect(proposal.inputs.currentGeometry).toMatchObject({ sourceLockId: "geo-national-cd119", authorityRole: "current_target_reference_only_not_historical_result_geography" });
    expect(proposal.sourceClasses.map((row) => row.id)).toHaveLength(6);
    expect(proposal.decisions.map((row) => row.decisionId)).toHaveLength(6);
    expect(proposal.decisions.every((row) => row.blocksPublication && row.resolution === null)).toBe(true);
  });

  it("binds the generated bytes to the exact four-parent source-lock closure", () => {
    const lock = JSON.parse(bytes("data/source-lock.json").toString("utf8")) as { entries: { id: string; retainedPath: string | null; byteSize: number; sha256: string; kind: string; parentIds: string[] }[] };
    const entry = lock.entries.find((row) => row.id === "house-democratic-primary-source-selection-proposal-20260804-v1")!;
    expect(entry).toMatchObject({ retainedPath: artifactPath, byteSize: bytes(artifactPath).byteLength, sha256: sha(artifactPath), kind: "review_proposal" });
    expect(new Set(entry.parentIds)).toEqual(new Set(["dsa-target-factual-projection-20260804-v1", "dsa-target-incumbent-roster-20260804-v1", "fec-2026-congressional-primary-dates", "geo-national-cd119"]));
    expect(validateHouseDemocraticPrimarySourceSelectionProposal(JSON.parse(bytes(artifactPath).toString("utf8"))).packageSha256).toBe(proposal.packageSha256);
  });

  it("fails closed on numeric promotion, result linkage, geography promotion, and identity mutation", () => {
    expect(() => validateHouseDemocraticPrimarySourceSelectionProposal({ ...proposal, publicationEligible: true })).toThrow();
    const numeric = structuredClone(proposal); (numeric.seats[0]!.evaluatorValues.priorPrimaryMargin as unknown as { kind: string; reason: string }).kind = "value";
    expect(() => validateHouseDemocraticPrimarySourceSelectionProposal(numeric)).toThrow();
    const contest = structuredClone(proposal); (contest.seats[0]!.selection as unknown as { selectedContestId: string | null }).selectedContestId = "contest_primary";
    expect(() => validateHouseDemocraticPrimarySourceSelectionProposal(contest)).toThrow();
    const geography = structuredClone(proposal); (geography.seats[0]!.geography as unknown as { compatibilityStatus: string }).compatibilityStatus = "reviewed_crosswalk_compatible";
    expect(() => validateHouseDemocraticPrimarySourceSelectionProposal(geography)).toThrow();
    const identity = structuredClone(proposal); identity.seats[0]!.bioguideId = "A000001";
    expect(() => validateHouseDemocraticPrimarySourceSelectionProposal(identity)).toThrow();
    expect(() => buildHouseDemocraticPrimarySourceSelectionProposal({ projection, projectionFileSha256: "0".repeat(64), roster, rosterFileSha256: sha(rosterPath) })).toThrow();
  });
});
