/* eslint-disable @typescript-eslint/no-explicit-any -- immutable persisted v1 schemas are composed without changing their public types */
import { createHash } from "node:crypto";
import { canonicalJson } from "../fec/aipac-proposed-packages";
import { validateIllinoisPrimaryIdentityGeographyReviewPackage } from "./illinois-primary-identity-geography-review-package";

type LockEntry={id:string;url:string;retainedPath:string|null;retainedStatus:string;byteSize:number;sha256:string;kind:string;parentIds:string[]};
export type IllinoisPrimaryJointReviewV2Input=Readonly<{jointV1Json:string;authorityJson:string;sourceLock:{version:1;entries:LockEntry[]}}>;
const V1={id:"illinois-primary-identity-geography-review-package-v1",file:"795843b2b1a7e8a276b0ccfdcbab75f251adc5db4ae227c6a1f56601dc596c37",package:"3eccc7f17da59e4a3bb427e339d7af63b0181327b1e80c80226b43ae173a474d",set:"4df05250803ce13fc85bf8bec43cc341d89e961855a2da09bca2497d3d983a59",decisionSet:"e73a6bf0e4428692cd1571c2e9f8fc33b3c6384797098359a8021e318592ad54"} as const;
const AUTH={id:"illinois-primary-state-board-certification-authority-receipt-v1",file:"1c053efa0db3ea9c17fe68ea0c96dcf3e077f75770bfcdd4e6556d7bcd0f702a",package:"f7853562ea3d293a35a4a52dacf2866af7f8373d0217d84e5042a8220b3ccc73",set:"1f919084c9cf1f6ac95d0ec92e2ca1d649dd4ad920a0ceb971592e44b3597221"} as const;
const OUTPUT={id:"illinois-primary-identity-geography-review-package-v2",file:"69579eb1f8d1b63e0733bf65745bb13e6726ecbc82c832f2bae11e693e8e53aa",path:"data/metadata/illinois-primary-identity-geography-review-package-v2.json",bytes:117750,parents:[V1.id,AUTH.id]} as const;
const sha=(value:string)=>createHash("sha256").update(value).digest("hex"),digest=(domain:string,value:unknown)=>createHash("sha256").update(domain,"ascii").update(canonicalJson(value)).digest("hex"),order=(a:string,b:string)=>Buffer.compare(Buffer.from(a),Buffer.from(b));
const fail=(reason:string):never=>{throw new Error(`IL_PRIMARY_JOINT_REVIEW_V2_INVALID:${reason}`)};
function lock(input:IllinoisPrimaryJointReviewV2Input,id:string,file:string,path:string,kind:string,parents:string[]){const matches=input.sourceLock.entries.filter(entry=>entry.id===id),entry=matches[0];if(matches.length!==1||!entry||entry.retainedStatus!=="retained"||entry.sha256!==file||entry.retainedPath!==path||entry.kind!==kind||canonicalJson(entry.parentIds)!==canonicalJson(parents))fail(`source_lock:${id}`);}
function assemble(input:IllinoisPrimaryJointReviewV2Input){
 if(input.sourceLock.version!==1||sha(input.jointV1Json)!==V1.file||sha(input.authorityJson)!==AUTH.file)fail("input_bytes");
 const parent=validateIllinoisPrimaryIdentityGeographyReviewPackage(JSON.parse(input.jointV1Json)),authority=JSON.parse(input.authorityJson) as any;
 if(parent.packageSha256!==V1.package||parent.reviewRecordSetSha256!==V1.set||parent.decisionSetSha256!==V1.decisionSet||authority.packageSha256!==AUTH.package||authority.contestScopeSha256!==AUTH.set)fail("parent_identity");
 lock(input,V1.id,V1.file,"data/metadata/illinois-primary-identity-geography-review-package-v1.json","review_proposal",["house-democratic-primary-source-selection-proposal-20260804-v1","illinois-current-incumbent-primary-linkage-candidate-v1","illinois-primary-geography-compatibility-candidate-v1"]);
 lock(input,AUTH.id,AUTH.file,"data/metadata/illinois-primary-state-board-certification-authority-receipt-v1.json","evidence_receipt",["illinois-house-democratic-primary-results-receipt-2022-2024-v1","il-primary-certification-press-release-index-20260806","il-2022-primary-certification-release","il-2022-primary-certification-release-text","il-2024-primary-certification-release","il-2024-primary-certification-release-text"]);
 const output=input.sourceLock.entries.filter(entry=>entry.id===OUTPUT.id),outputEntry=output[0];if(output.length!==1||!outputEntry||outputEntry.url!=="urn:dsa-seats:illinois-primary-identity-geography-review-package:v2:2026-08-06"||outputEntry.retainedPath!==OUTPUT.path||outputEntry.retainedStatus!=="retained"||outputEntry.byteSize!==OUTPUT.bytes||outputEntry.sha256!==OUTPUT.file||outputEntry.kind!=="review_proposal"||canonicalJson(outputEntry.parentIds)!==canonicalJson(OUTPUT.parents))fail("source_lock:output");
 const authorityByContest=new Map(authority.contestScope.map((row:any)=>[row.contestId,row]));
 const records=parent.records.map((prior:any)=>{const evidence=authorityByContest.get(prior.contestId) as any;if(!evidence||evidence.parentContestSha256!==prior.contestSha256||evidence.cycleYear!==prior.cycleYear||evidence.districtCode!==prior.districtCode)fail("authority_join");const election=authority.elections.find((row:any)=>row.cycleYear===prior.cycleYear);const unsigned={reviewRecordId:prior.reviewRecordId,contestId:prior.contestId,contestSha256:prior.contestSha256,seatCycleId:prior.seatCycleId,districtCode:prior.districtCode,cycleYear:prior.cycleYear,parentReviewRecordSha256:prior.reviewRecordSha256,identity:prior.identity,geography:prior.geography,certification:{status:"election_level_authority_candidate" as const,authorityCandidate:true as const,approved:false as const,authoritySourceLockId:AUTH.id,authorityPackageSha256:AUTH.package,authorityScopeRowSha256:evidence.rowSha256,electionDate:evidence.authorityElectionDate,certificationDate:evidence.authorityCertificationDate,indexDisplayDate:election.indexDisplayDate,indexDateMatchesInstrument:election.indexDateMatchesInstrument,individualContestCertificateRetained:false as const,candidateCertificationByNameClaimed:false as const},progressiveClassificationStatus:prior.progressiveClassificationStatus,reviewDisposition:prior.reviewDisposition,jointApproved:false as const,evaluatorUse:prior.evaluatorUse,scoreEligible:false as const,publicationEligible:false as const,rationaleCodes:[...prior.rationaleCodes.filter((code:string)=>code!=="final_certification_not_retained"),"election_level_certification_authority_candidate_pending_independent_review","individual_contest_certificate_not_retained","parent_candidates_not_approved_by_composition"]};return{...unsigned,reviewRecordSha256:digest("dsa-seats:il-primary-joint-review-row:v2\0",unsigned)}}).sort((a:any,b:any)=>order(a.reviewRecordId,b.reviewRecordId));
 if(records.length!==34||records.some((row:any)=>row.certification.approved||row.jointApproved||row.scoreEligible||row.publicationEligible))fail("record_closure");
 const preserved=parent.decisions.filter((decision:any)=>decision.decisionId!=="il-primary:retain-certification-exclusion-v1");
 const ids=records.map((row:any)=>row.reviewRecordId);
 const certificationDecision={decisionId:"il-primary:accept-election-level-certification-authority-v2",affectedComponent:"statewide election-level certification authority",parentDecisionId:"collect-official-state-primary-results-and-certification-v1",question:"Should the retained State Board election-level certification authority be accepted for all 34 Illinois records without claiming individual contest certificates?",recommendedDecision:"Accept election-level State Board certification authority for all 34 records without claiming individual contest certificates or candidate-by-name certification.",defaultReversibleAssumption:"exclude_affected_records_from_evaluator_and_publication",alternatives:["Require individual contest certificates before accepting certification authority.","Reject the election-level authority and retain the v1 not-retained projection."],consequences:["Acceptance resolves only the election-level authority component.","Deferral keeps every record excluded while unrelated work continues."],confidence:"high",evidenceRecordIds:ids,blocksAffectedPublication:true,blocksOtherWork:false,workCompletedWhileWaiting:"Exact State Board instruments are retained and joined to all 34 immutable parent contest hashes.",review:{status:"proposed",reviewer:null,reviewedAt:null,resolution:null}};
 const decisions=[...preserved,certificationDecision].sort((a:any,b:any)=>order(a.decisionId,b.decisionId));
 const unsigned={schema:"illinois-primary-identity-geography-review-package-v2" as const,version:2 as const,generatedAt:"2026-08-06T15:15:00.000Z" as const,sourceCutoff:"2026-08-06" as const,reviewerOnly:true as const,publicationEligible:false as const,defaultUse:parent.defaultUse,review:parent.review,parents:{jointV1:{sourceLockId:V1.id,fileSha256:V1.file,packageSha256:V1.package,reviewRecordSetSha256:V1.set,decisionSetSha256:V1.decisionSet,superseded:false as const},certificationAuthority:{sourceLockId:AUTH.id,fileSha256:AUTH.file,packageSha256:AUTH.package,contestScopeSha256:AUTH.set}},methodology:{compositionOnly:true as const,parentRecordsMutated:false as const,electionAuthorityReplacesNotRetainedProjection:true as const,authorityAcceptanceAutomaticallyApprovesRecords:false as const,individualContestCertificatesClaimed:false as const,candidateCertificationByNameClaimed:false as const,automaticDecisionClosure:false as const,evaluatorNumericValues:0 as const},summary:{reviewRecords:34 as const,identityAndGeographyCandidates:28 as const,geographyCandidateIdentityOutsideCurrentTargetScope:6 as const,electionLevelCertificationAuthorityCandidates:34 as const,certificationApprovals:0 as const,jointApprovedRecords:0 as const,scoreEligibleRecords:0 as const,proposedDecisions:4 as const},records,reviewRecordSetSha256:digest("dsa-seats:il-primary-joint-review-row-set:v2\0",records),decisions,decisionSetSha256:digest("dsa-seats:il-primary-joint-review-decision-set:v2\0",decisions),inheritedDecisionResolutions:{certification:null,identity:null,geography:null,progressiveClassification:null}};
 return{...unsigned,packageSha256:digest("dsa-seats:il-primary-joint-review-package:v2\0",unsigned)};
}
export type IllinoisPrimaryIdentityGeographyReviewPackageV2=ReturnType<typeof assemble>;
export function buildIllinoisPrimaryIdentityGeographyReviewPackageV2(input:IllinoisPrimaryJointReviewV2Input){return assemble(input)}
export function validateIllinoisPrimaryIdentityGeographyReviewPackageV2(value:IllinoisPrimaryIdentityGeographyReviewPackageV2,input:IllinoisPrimaryJointReviewV2Input){if(canonicalJson(value)!==canonicalJson(assemble(input)))fail("semantic_or_hash_drift");return value}
