import { createHash } from "node:crypto";

import { canonicalJson } from "../fec/aipac-proposed-packages";
import { validateIllinoisHouseDemocraticPrimaryResultsReceipt } from "./illinois-house-democratic-primary-results-receipt";

type LockEntry = { id: string; url: string; retainedPath: string | null; retainedStatus: string; byteSize: number; sha256: string; kind: string; parentIds: string[] };
export type IllinoisPrimaryCertificationAuthorityInput = Readonly<{ parentReceiptJson: string; indexBytes: Buffer; release2022Bytes: Buffer; release2022TextBytes: Buffer; release2024Bytes: Buffer; release2024TextBytes: Buffer; sourceLock: { version: 1; entries: LockEntry[] } }>;
const PARENT = { id: "illinois-house-democratic-primary-results-receipt-2022-2024-v1", fileSha256: "3016e345d7989ff302557034fb65a63aff92a94f0fec3981b586bf7ea07f9534", packageSha256: "4c0f7bc0505b9e02d03585d8acd0fe47d6599b194f6efcdbcd6e40896d6a663f", contestSetSha256: "eaff782dec77a454d943125c2256d6b6f10121522510a4ec5a43c9e1058e52af" } as const;
const SOURCES = [
  { id: "il-primary-certification-press-release-index-20260806", url: "https://www.elections.il.gov/abouttheboard/pressreleasesall.aspx", retainedPath: "data/source/elections/primary-results/illinois/certification/press-release-index.html", byteSize: 66315, sha256: "a412c3e4042ddc0ecdcfdc053f5c285cd2edb3c9c23888bc597be254d5bcef61", kind: "official_source_index", parentIds: [] },
  { id: "il-2022-primary-certification-release", url: "https://www.elections.il.gov/NewDocDisplay.aspx?%2fM0cs48zOKUVo8NHFkkNhVwyxu6isYxmIQBUuKl3cnXZ14OCwk8xSlTDqHmM4r1%2fs4vCJdp%2fBAULh0fhhOvNcbJZOYWF6i8QLu28SSnazIrW%2bgZltjRHjlnFXvYIQJS7wSfUrvME7hqmfdajn%2f4dcA%3d%3d", retainedPath: "data/source/elections/primary-results/illinois/certification/2022-primary-certification-release.pdf", byteSize: 354098, sha256: "a6ed44113caff0ddad5357180ef90cd5e77bc536a1d898c7ed1c1bc4d7f68c44", kind: "official_certification_authority", parentIds: ["il-primary-certification-press-release-index-20260806"] },
  { id: "il-2022-primary-certification-release-text", url: "urn:dsa-seats:il-2022-primary-certification-release:pdftotext-layout-26.07.0", retainedPath: "data/source/elections/primary-results/illinois/certification/2022-primary-certification-release.txt", byteSize: 3569, sha256: "81490adafe8ea704339f89ffcdb39e3719d51c6c0e446baeadef2f6d75b0c72a", kind: "derived_extract", parentIds: ["il-2022-primary-certification-release"] },
  { id: "il-2024-primary-certification-release", url: "https://www.elections.il.gov/NewDocDisplay.aspx?%2fM0cs48zOKUVo8NHFkkNhVwyxu6isYxmIQBUuKl3cnXZ14OCwk8xSlTDqHmM4r1%2fs4vCJdp%2fBAULh0fhhOvNcQ91nqwZ5aG0qUbJYA%2fNKshy69rk9JoasNuB%2fqLHLlG7HQTDlFERMt8INv6%2fXcZ29KXgOHHaS61v", retainedPath: "data/source/elections/primary-results/illinois/certification/2024-primary-certification-release.pdf", byteSize: 344917, sha256: "a880424b5e9bc675e357d096aecfe178548e5ab320ad7ec625246222d3f56ed8", kind: "official_certification_authority", parentIds: ["il-primary-certification-press-release-index-20260806"] },
  { id: "il-2024-primary-certification-release-text", url: "urn:dsa-seats:il-2024-primary-certification-release:pdftotext-layout-26.07.0", retainedPath: "data/source/elections/primary-results/illinois/certification/2024-primary-certification-release.txt", byteSize: 6505, sha256: "41e4abec32a0f44c91d4d1b7ecf2839ae647857188f2c15c1dea99bc20619e7f", kind: "derived_extract", parentIds: ["il-2024-primary-certification-release"] },
] as const;
const OUTPUT = { id: "illinois-primary-state-board-certification-authority-receipt-v1", url: "urn:dsa-seats:illinois-primary-state-board-certification-authority-receipt:v1:2026-08-06", retainedPath: "data/metadata/illinois-primary-state-board-certification-authority-receipt-v1.json", retainedStatus: "retained", byteSize: 33439, sha256: "1c053efa0db3ea9c17fe68ea0c96dcf3e077f75770bfcdd4e6556d7bcd0f702a", kind: "evidence_receipt", parentIds: [PARENT.id, ...SOURCES.map((source) => source.id)] } as const;
const sha = (value: string | Buffer) => createHash("sha256").update(value).digest("hex");
const digest = (domain: string, value: unknown) => createHash("sha256").update(domain, "ascii").update(canonicalJson(value)).digest("hex");
const fail = (reason: string): never => { throw new Error(`IL_PRIMARY_CERTIFICATION_AUTHORITY_INVALID:${reason}`); };
function exactEntry(entries: LockEntry[], expected: typeof SOURCES[number]) { const matches = entries.filter((entry) => entry.id === expected.id); const entry = matches[0]; if (matches.length !== 1 || !entry || canonicalJson(entry) !== canonicalJson({ ...expected, retainedStatus: "retained" })) fail(`source_lock:${expected.id}`); return entry; }

function assemble(input: IllinoisPrimaryCertificationAuthorityInput) {
  if (input.sourceLock.version !== 1 || sha(input.parentReceiptJson) !== PARENT.fileSha256) fail("parent_bytes");
  const bytes = [input.indexBytes, input.release2022Bytes, input.release2022TextBytes, input.release2024Bytes, input.release2024TextBytes];
  if (bytes.some((value, index) => sha(value) !== SOURCES[index]!.sha256)) fail("source_bytes");
  const sources = SOURCES.map((source) => exactEntry(input.sourceLock.entries, source));
  const parent = validateIllinoisHouseDemocraticPrimaryResultsReceipt(JSON.parse(input.parentReceiptJson));
  if (parent.packageSha256 !== PARENT.packageSha256 || parent.summary.contestSetSha256 !== PARENT.contestSetSha256 || parent.contests.length !== 34) fail("parent_identity");
  const parentEntries = input.sourceLock.entries.filter((entry) => entry.id === PARENT.id), parentEntry = parentEntries[0];
  const expectedParentIds = [...parent.sourceListings.map((entry) => entry.id), ...parent.sources.map((entry) => entry.id), parent.methodologyParent.sourceLockId];
  if (parentEntries.length !== 1 || !parentEntry || parentEntry.retainedPath !== "data/metadata/illinois-house-democratic-primary-results-receipt-2022-2024-v1.json" || parentEntry.retainedStatus !== "retained" || parentEntry.byteSize !== 83040 || parentEntry.sha256 !== PARENT.fileSha256 || parentEntry.kind !== "review_candidate" || parentEntry.parentIds.length !== expectedParentIds.length || expectedParentIds.some((id) => !parentEntry.parentIds.includes(id))) fail("source_lock:parent");
  const outputEntries = input.sourceLock.entries.filter((entry) => entry.id === OUTPUT.id);
  if (outputEntries.length !== 1 || canonicalJson(outputEntries[0]) !== canonicalJson(OUTPUT)) fail("source_lock:output");
  const index = input.indexBytes.toString("utf8"), text2022 = input.release2022TextBytes.toString("utf8"), text2024 = input.release2024TextBytes.toString("utf8");
  if (!input.release2022Bytes.subarray(0, 5).equals(Buffer.from("%PDF-")) || !input.release2024Bytes.subarray(0, 5).equals(Buffer.from("%PDF-"))) fail("pdf_magic");
  if (!index.includes("Fri, August 5, 2022") || !index.includes("State Board of Elections certifies results of June 28 primary") || !index.includes("Fri, April 19, 2024") || !index.includes("State Board of Elections certifies March 19 primary results")) fail("index_sentinels");
  if (!text2022.includes("SPRINGFIELD (July 29, 2022)") || !text2022.includes("today certified the results") || !text2022.includes("of the June 28 primary election") || !text2022.includes("The Official Vote Totals Book for the primary")) fail("release_2022_sentinels");
  if (!text2024.includes("SPRINGFIELD (April 19, 2024)") || !text2024.includes("official vote total certified today by the Illinois State Board of Elections") || !text2024.includes("17 congressional seats")) fail("release_2024_sentinels");
  const elections = [
    { cycleYear: 2022 as const, electionDate: "2022-06-28" as const, certificationDate: "2022-07-29" as const, indexDisplayDate: "2022-08-05" as const, indexDateMatchesInstrument: false as const, status: "state_board_election_results_certified" as const, indexSourceLockId: SOURCES[0].id, releaseSourceLockId: SOURCES[1].id, textSourceLockId: SOURCES[2].id, scope: "statewide_primary_election_results" as const, individualContestCertificatesRetained: false as const },
    { cycleYear: 2024 as const, electionDate: "2024-03-19" as const, certificationDate: "2024-04-19" as const, indexDisplayDate: "2024-04-19" as const, indexDateMatchesInstrument: true as const, status: "state_board_election_results_certified" as const, indexSourceLockId: SOURCES[0].id, releaseSourceLockId: SOURCES[3].id, textSourceLockId: SOURCES[4].id, scope: "statewide_primary_election_results" as const, individualContestCertificatesRetained: false as const },
  ];
  const contestScope = parent.contests.map((contest) => { const unsigned = { contestId: contest.contestId, parentContestSha256: contest.contestSha256, cycleYear: contest.cycleYear, districtCode: contest.districtCode, contestDisposition: contest.contestDisposition, candidateCount: contest.candidates.length, candidateVotes: contest.candidateVotes, authorityElectionDate: contest.cycleYear === 2022 ? elections[0].electionDate : elections[1].electionDate, authorityCertificationDate: contest.cycleYear === 2022 ? elections[0].certificationDate : elections[1].certificationDate, authorityStatus: "state_board_election_results_certified" as const, authorityCoverageCandidate: true as const, certificationApproved: false as const, identityApproved: false as const, geographyApproved: false as const, scoreEligible: false as const, publicationEligible: false as const }; return { ...unsigned, rowSha256: digest("dsa-seats:il-primary-certification-authority-row:v1\0", unsigned) }; });
  if (contestScope.length !== 34 || contestScope.filter((row) => row.cycleYear === 2022).length !== 17 || contestScope.filter((row) => row.cycleYear === 2024).length !== 17 || contestScope.filter((row) => row.contestDisposition === "no_democratic_candidate_rows").map((row) => row.contestId).join(",") !== "il:2022:us-house:16:democratic,il:2024:us-house:16:democratic") fail("scope_closure");
  const unsigned = { schema: "illinois-primary-state-board-certification-authority-receipt-v1" as const, version: 1 as const, generatedAt: "2026-08-06T14:45:00.000Z" as const, sourceCutoff: "2026-08-06" as const, originalPublisher: "Illinois State Board of Elections" as const, reviewerOnly: true as const, publicationEligible: false as const, scoreEligible: false as const, deployed: false as const, review: { status: "proposed" as const, reviewer: null, reviewedAt: null, resolution: null }, inputs: { parentReceipt: { sourceLockId: PARENT.id, fileSha256: PARENT.fileSha256, packageSha256: PARENT.packageSha256, contestSetSha256: PARENT.contestSetSha256 }, sources }, elections, methodology: { electionLevelAuthorityOnly: true as const, individualContestCertificatesRetained: false as const, candidateCertificationByNameClaimed: false as const, winnerSelectionInferred: false as const, nominationInferred: false as const, parentContestFactsMutated: false as const, indexInstrumentDateDiscrepancyPreserved: true as const, automaticDecisionClosure: false as const, evaluatorNumericValues: 0 as const }, summary: { elections: 2 as const, contestObservations: 34 as const, cycle2022Contests: 17 as const, cycle2024Contests: 17 as const, candidateBearingContests: 32 as const, noCandidateRowContests: 2 as const, automaticallyApprovedRows: 0 as const, scoreEligibleRows: 0 as const }, contestScope, contestScopeSha256: digest("dsa-seats:il-primary-certification-authority-row-set:v1\0", contestScope), limitations: ["The State Board releases establish statewide primary-election result certification, not individually retained contest certificates.", "The 2022 index display date differs from the July 29 date inside the certification instrument; the instrument date controls this receipt and the discrepancy remains explicit.", "Certification authority does not by itself select a winner, establish nomination by name, approve identity or geography, enable evaluator values, or authorize publication."] as const };
  return { ...unsigned, packageSha256: digest("dsa-seats:il-primary-certification-authority-receipt:v1\0", unsigned) };
}
export type IllinoisPrimaryStateBoardCertificationAuthority = ReturnType<typeof assemble>;
export function buildIllinoisPrimaryStateBoardCertificationAuthority(input: IllinoisPrimaryCertificationAuthorityInput) { return assemble(input); }
export function validateIllinoisPrimaryStateBoardCertificationAuthority(value: IllinoisPrimaryStateBoardCertificationAuthority, input: IllinoisPrimaryCertificationAuthorityInput) { if (canonicalJson(value) !== canonicalJson(assemble(input))) fail("semantic_or_hash_drift"); return value; }
