import { createHash } from "node:crypto";

import { canonicalJson } from "../fec/aipac-proposed-packages";
import { validateNewYorkPrimaryGeographyCandidateV2, type NewYorkPrimaryGeographyCandidateV2, type NewYorkPrimaryGeographyV2Input } from "./new-york-primary-geography-compatibility-candidate-v2";
import { validateNewYorkPrimaryJointReviewPackage } from "./new-york-primary-identity-geography-review-package";

export const NEW_YORK_PRIMARY_JOINT_REVIEW_V2 = "new-york-primary-identity-geography-review-package-v2" as const;
type LockEntry = { id: string; url: string; retainedPath: string | null; retainedStatus: "retained" | "nonretained"; byteSize: number; sha256: string; kind: string; parentIds: string[] };
export type NewYorkPrimaryJointReviewV2Input = NewYorkPrimaryGeographyV2Input & Readonly<{ jointV1Json: string; geographyV2Json: string }>;
const JOINT_V1_SHA = "7c626a550f1e644db1977cd39af1437384ad31e1f76602fc0f2d024cc9cc4fb8", GEOGRAPHY_V2_SHA = "d2403c86107b131aa073c3aa26f267f50aad57b88122c517ac633413e93ab018";
const PARENTS = ["new-york-primary-identity-geography-review-package-v1", "new-york-primary-geography-compatibility-candidate-v2"] as const;
const requiredEntries: LockEntry[] = [
  { id: PARENTS[0], url: "urn:dsa-seats:new-york-primary-identity-geography-review-package:v1:2026-08-06", retainedPath: "data/metadata/new-york-primary-identity-geography-review-package-v1.json", retainedStatus: "retained", byteSize: 102113, sha256: JOINT_V1_SHA, kind: "review_proposal", parentIds: ["house-democratic-primary-source-selection-proposal-20260804-v1", "new-york-current-incumbent-primary-linkage-candidate-v1", "new-york-primary-geography-compatibility-candidate-v1"] },
  { id: PARENTS[1], url: "urn:dsa-seats:new-york-primary-geography-compatibility-candidate:v2:2026-08-06", retainedPath: "data/metadata/new-york-primary-geography-compatibility-candidate-v2.json", retainedStatus: "retained", byteSize: 90500, sha256: GEOGRAPHY_V2_SHA, kind: "review_candidate", parentIds: ["new-york-primary-geography-compatibility-candidate-v1", "new-york-2022-primary-block-crosswalk-candidate-v1"] },
];
const OUTPUT_SIZE = 135262, OUTPUT_SHA = "9bd59eeca6d214701a7b36f1f2f6f2689d7d2a1499af34ede818893cce7f87f4";
const sha = (value: string): string => createHash("sha256").update(value).digest("hex");
const digest = (domain: string, value: unknown): string => createHash("sha256").update(domain, "ascii").update(canonicalJson(value), "utf8").digest("hex");
const order = (left: string, right: string): number => Buffer.compare(Buffer.from(left), Buffer.from(right));
const fail = (reason: string): never => { throw new Error(`NY_PRIMARY_JOINT_REVIEW_V2_INVALID:${reason}`); };
const parse = (value: string, reason: string): unknown => { try { return JSON.parse(value); } catch { return fail(reason); } };
const exactEntry = (entries: LockEntry[], expected: LockEntry): LockEntry => {
  const matches = entries.filter((entry) => entry.id === expected.id);
  if (matches.length !== 1 || canonicalJson(matches[0]) !== canonicalJson(expected)) fail(`source_lock:${expected.id}`);
  return matches[0]!;
};

function assemble(input: NewYorkPrimaryJointReviewV2Input) {
  if (sha(input.jointV1Json) !== JOINT_V1_SHA || sha(input.geographyV2Json) !== GEOGRAPHY_V2_SHA) fail("input_bytes");
  const jointV1 = validateNewYorkPrimaryJointReviewPackage(parse(input.jointV1Json, "joint_v1_json"));
  const geographyInput = { geographyV1Json: input.geographyV1Json, crosswalkJson: input.crosswalkJson, receiptJson: input.receiptJson, authorityBytes: input.authorityBytes, assignmentBytes: input.assignmentBytes, cd118Bytes: input.cd118Bytes, cd119Bytes: input.cd119Bytes, sourceLock: input.sourceLock };
  const geography = validateNewYorkPrimaryGeographyCandidateV2(parse(input.geographyV2Json, "geography_v2_json") as NewYorkPrimaryGeographyCandidateV2, geographyInput);
  if (jointV1.packageSha256 !== "9abd860d67af83460ecc5e121344903c7a25e5d28691914f87a7f92ec94ed6e7" || jointV1.reviewRecordSetSha256 !== "f891eaaeb7dca0fdae46fe3e849a750cd46907b7d3ea5de467604f2a9a5fc19b" || jointV1.decisionSetSha256 !== "981a57a584b043c2cd1856d82ed2163c3e87c9b276596f87e1f9294276558da2" || geography.packageSha256 !== "d11566b0db64f439856798e3270ac444ef514920f948d3cfd3b1e717232445bc" || geography.rowSetSha256 !== "bfaf99c4dc4297927ba1141b3ae1bfd4545d3d47639f56734b427fc3c965c5ce") fail("parent_identity");
  for (const entry of requiredEntries) exactEntry(input.sourceLock.entries, entry);
  const output = input.sourceLock.entries.filter((entry) => entry.id === NEW_YORK_PRIMARY_JOINT_REVIEW_V2);
  if (!OUTPUT_SHA) { if (output.length) fail("unexpected_output_lock"); }
  else exactEntry(input.sourceLock.entries, { id: NEW_YORK_PRIMARY_JOINT_REVIEW_V2, url: "urn:dsa-seats:new-york-primary-identity-geography-review-package:v2:2026-08-06", retainedPath: "data/metadata/new-york-primary-identity-geography-review-package-v2.json", retainedStatus: "retained", byteSize: OUTPUT_SIZE, sha256: OUTPUT_SHA, kind: "review_proposal", parentIds: [...PARENTS] });
  const geographyByObservation = new Map(geography.rows.map((row) => [row.observationId, row]));
  const records = jointV1.records.map((parent) => {
    const geographyRow = geographyByObservation.get(parent.geographyObservationId) ?? fail("missing_geography_row");
    if (geographyRow.identityObservationId !== parent.identityObservationId || geographyRow.seatCycleId !== parent.seatCycleId || geographyRow.districtCode !== parent.districtCode || geographyRow.cycleYear !== parent.cycleYear || geographyRow.identityRowSha256 !== parent.identity.parentRowSha256 || geographyRow.resultDisposition !== parent.resultDisposition) fail("parent_join");
    const identityCandidate = parent.identity.candidate, identityNoMatch = parent.identity.status === "no_match", historical = parent.cycleYear === 2022, geographyCandidate = geographyRow.compatibilityCandidate;
    const category = historical
      ? geographyCandidate ? identityCandidate ? "identity_and_exact_block_membership_candidates" as const : "exact_block_membership_candidate_identity_not_applicable" as const
        : identityCandidate ? "identity_candidate_block_crosswalk_pending" as const : identityNoMatch ? "block_crosswalk_pending_identity_no_match" as const : "block_crosswalk_pending_identity_not_applicable" as const
      : identityCandidate ? "identity_and_geography_candidates" as const : "geography_candidate_identity_not_applicable" as const;
    const { reviewRecordSha256: parentReviewRecordSha256, geography: parentGeography, ...preserved } = parent;
    const unsigned = {
      ...preserved,
      parentReviewRecordSha256,
      geography: { parentRowSha256: geographyRow.rowSha256, parentV1RowSha256: parentGeography.parentRowSha256, status: geographyCandidate ? "candidate" as const : "crosswalk_review_required" as const, targetCd119Geoid: geographyRow.targetCd119Geoid, historicalCongressSession: geographyRow.historicalCongressSession, historicalGeoid: geographyRow.historicalGeoid, compatibilityDisposition: geographyRow.compatibilityDisposition, confidence: geographyRow.confidence, candidate: geographyCandidate, approved: false as const },
      historicalBlockCrosswalk: historical ? { ...geographyRow.historicalBlockCrosswalk!, compatibilityCandidate: geographyCandidate, approved: false as const, legalEffectAssessed: false as const, electionUseAssessed: false as const } : null,
      reviewCategory: category,
      reviewerAction: geographyCandidate && identityCandidate ? "review_identity_and_geography_independently" : geographyCandidate ? "review_exact_geography_while_preserving_identity_boundary" : identityCandidate ? "review_identity_while_retaining_block_crosswalk_requirement" : "retain_unresolved_parent_boundaries",
      rationaleCodes: [category, "parent_candidates_not_approved_by_join", "identity_and_result_dispositions_preserved", "source_winner_not_established_by_composition", "all_independent_review_gates_remain_open"],
    };
    return { ...unsigned, reviewRecordSha256: digest("dsa-seats:ny-primary-joint-review-row:v2\0", unsigned) };
  }).sort((left, right) => order(left.reviewRecordId, right.reviewRecordId));
  if (records.length !== 38 || geographyByObservation.size !== 38) fail("record_closure");
  const all = records.map((row) => row.reviewRecordId), identities = records.filter((row) => row.identity.candidate).map((row) => row.reviewRecordId), reported = records.filter((row) => row.resultDisposition === "reported_contest").map((row) => row.reviewRecordId);
  const common = { defaultReversibleAssumption: "exclude_affected_records_from_evaluator_and_publication" as const, confidence: "high" as const, blocksAffectedPublication: true as const, blocksOtherWork: false as const, review: { status: "proposed" as const, reviewer: null, reviewedAt: null, resolution: null } };
  const decisions = [
    { ...common, decisionId: "ny-primary:review-2022-block-crosswalk-and-retain-2024-session-keys-v2", parentDecisionId: "approve-historical-district-cd119-compatibility-v1", affectedComponent: "historical geography", question: "Should four 2022 exact-block-membership findings remain candidates while fifteen split rows remain crosswalk-review-required and nineteen 2024 session-key candidates retain their proposed status?", recommendedDecision: "Retain the four exact-block findings as candidates only, retain fifteen split rows for review, and preserve all 2024 candidate states without approval.", alternatives: ["Require additional evidence for all 38 rows.", "Promote split rows using an overlap threshold."], consequences: ["The recommendation improves the proposed evidence matrix without approving any geography relationship.", "Threshold promotion would create unsupported continuity."], evidenceRecordIds: all, workCompletedWhileWaiting: "The complete official 2022 and CD119 block universes are source-locked and exactly compared." },
    { ...common, decisionId: "ny-primary:accept-identity-links-v2", parentDecisionId: "approve-historic-primary-candidate-identity-resolution-v1", affectedComponent: "current-incumbent identity", question: "Should the 12 finite identity links be accepted?", recommendedDecision: "Accept six exact and six finite derived links while preserving four predecessor no-matches and 22 nonreported rows.", alternatives: ["Reject all proposed links.", "Require additional external identity evidence."], consequences: ["Acceptance resolves identity only.", "Deferral leaves every affected record excluded."], evidenceRecordIds: identities, workCompletedWhileWaiting: "All finite name and retained-alias evidence remains hash-bound in the immutable identity lineage." },
    { ...common, decisionId: "ny-primary:retain-primary-disposition-exclusion-v2", parentDecisionId: "decide-nonstandard-primary-disposition-treatment-v1", affectedComponent: "primary disposition", question: "Should reported, certified-uncontested, and unresolved states remain excluded from numeric evaluator use?", recommendedDecision: "Preserve all three dispositions without inferring winners, nominees, or zero values.", alternatives: ["Infer selection from candidate vote rank.", "Convert nonreported rows to zero."], consequences: ["The recommendation preserves factual boundaries.", "Either alternative would create unsupported facts."], evidenceRecordIds: all, workCompletedWhileWaiting: "All 38 disposition coordinates and 16 result payloads remain retained in immutable parents." },
    { ...common, decisionId: "ny-primary:retain-progressive-classification-exclusion-v2", parentDecisionId: "approve-progressive-candidate-classification-method-v1", affectedComponent: "progressive classification", question: "Should progressive-primary factors remain excluded?", recommendedDecision: "Retain exclusion because no reviewed progressive classification is present.", alternatives: ["Treat non-incumbents as progressive.", "Infer ideology from names or ballot order."], consequences: ["The recommendation prevents unsupported ideological scores.", "Either alternative fabricates classifications."], evidenceRecordIds: all, workCompletedWhileWaiting: "Identity and geography evidence remains isolated for later classification work." },
    { ...common, decisionId: "ny-primary:retain-reported-result-authority-boundaries-v2", parentDecisionId: "collect-official-state-primary-results-and-certification-v1", affectedComponent: "reported result authority", question: "Should nine statewide reported and seven NYC certified contests retain their distinct authority boundaries?", recommendedDecision: "Retain the distinct authorities and preserve that statewide final certification is not independently retained.", alternatives: ["Require separate final certification for every reported row.", "Flatten local and statewide authorities."], consequences: ["The recommendation preserves source status without authorizing publication or scoring.", "Flattening would erase material provenance."], evidenceRecordIds: reported, workCompletedWhileWaiting: "The exact statewide and NYC result packages remain independently source-locked." },
  ].sort((left, right) => order(left.decisionId, right.decisionId));
  const count = (category: string) => records.filter((row) => row.reviewCategory === category).length;
  const summary = { reviewRecords: 38 as const, historical2022Records: 19 as const, current2024Records: 19 as const, identityAndExactBlockMembershipCandidates: count("identity_and_exact_block_membership_candidates"), exactBlockMembershipCandidateIdentityNotApplicable: count("exact_block_membership_candidate_identity_not_applicable"), identityCandidateBlockCrosswalkPending: count("identity_candidate_block_crosswalk_pending"), blockCrosswalkPendingIdentityNoMatch: count("block_crosswalk_pending_identity_no_match"), blockCrosswalkPendingIdentityNotApplicable: count("block_crosswalk_pending_identity_not_applicable"), identityAndGeographyCandidates: count("identity_and_geography_candidates"), geographyCandidateIdentityNotApplicable: count("geography_candidate_identity_not_applicable"), historicalExactBlockMembershipCandidates: 4 as const, historicalCrosswalkReviewRequired: 15 as const, identityCandidates: identities.length, geographyCandidates: records.filter((row) => row.geography.candidate).length, reportedContestRecords: reported.length, certifiedUncontestedRecords: records.filter((row) => row.resultDisposition === "certified_uncontested").length, unresolvedRecords: records.filter((row) => row.resultDisposition === "unresolved_outside_retained_authority_scope").length, proposedDecisions: 5 as const, jointApprovedRecords: 0 as const, historicalBlockCrosswalkApprovedRecords: 0 as const, scoreEligibleRecords: 0 as const, evaluatorNumericValues: 0 as const };
  if (canonicalJson([summary.identityAndExactBlockMembershipCandidates, summary.exactBlockMembershipCandidateIdentityNotApplicable, summary.identityCandidateBlockCrosswalkPending, summary.blockCrosswalkPendingIdentityNoMatch, summary.blockCrosswalkPendingIdentityNotApplicable, summary.identityAndGeographyCandidates, summary.geographyCandidateIdentityNotApplicable]) !== canonicalJson([2, 2, 6, 4, 5, 4, 15])) fail("category_closure");
  const unsigned = {
    schema: NEW_YORK_PRIMARY_JOINT_REVIEW_V2, version: 2 as const, generatedAt: "2026-08-06T19:00:00.000Z" as const, sourceCutoff: "2026-08-06" as const,
    reviewerOnly: true as const, publicationEligible: false as const, defaultUse: "exclude_from_evaluator_until_authority_identity_geography_disposition_and_classification_review" as const,
    review: { status: "proposed" as const, reviewer: null, reviewedAt: null, resolution: null },
    parents: { jointV1: { sourceLockId: PARENTS[0], fileSha256: JOINT_V1_SHA, packageSha256: jointV1.packageSha256, recordSetSha256: jointV1.reviewRecordSetSha256, decisionSetSha256: jointV1.decisionSetSha256 }, geographyV2: { sourceLockId: PARENTS[1], fileSha256: GEOGRAPHY_V2_SHA, packageSha256: geography.packageSha256, rowSetSha256: geography.rowSetSha256 } },
    supersedes: [{ sourceLockId: PARENTS[0], scope: "joint_reviewer_composition_only" as const, preservesParentEvidence: true as const, preservesParentReviewState: true as const, doesNotResolveParentDecisions: true as const }],
    methodology: { scope: "exact_thirty_eight_new_york_joint_records_recomposed_with_geography_v2", parentCandidatesReviewedIndependently: true as const, jointPackageApprovesParents: false as const, blockCountsArePopulationVoterOrElectoralWeights: false as const, legalEffectAssessed: false as const, electionUseAssessed: false as const, automaticApprovals: 0 as const, evaluatorNumericValues: 0 as const },
    summary, records, reviewRecordSetSha256: digest("dsa-seats:ny-primary-joint-review-row-set:v2\0", records), decisions, decisionSetSha256: digest("dsa-seats:ny-primary-joint-decision-set:v2\0", decisions),
    inheritedDecisionResolutions: { authority: null, identity: null, geography: null, historicalBlockCrosswalk: null, disposition: null, progressiveClassification: null },
  };
  return { ...unsigned, packageSha256: digest("dsa-seats:ny-primary-joint-review-package:v2\0", unsigned) };
}

export type NewYorkPrimaryJointReviewPackageV2 = ReturnType<typeof assemble>;
export function buildNewYorkPrimaryJointReviewPackageV2(input: NewYorkPrimaryJointReviewV2Input): NewYorkPrimaryJointReviewPackageV2 { return assemble(input); }
export function validateNewYorkPrimaryJointReviewPackageV2(value: NewYorkPrimaryJointReviewPackageV2, input: NewYorkPrimaryJointReviewV2Input): NewYorkPrimaryJointReviewPackageV2 { if (canonicalJson(value) !== canonicalJson(assemble(input))) fail("semantic_or_hash_drift"); return value; }
