import { createHash } from "node:crypto";

import { canonicalJson } from "../fec/aipac-proposed-packages";
import { NYC_CERTIFIED_PACKAGE_SHA256, type NycCertifiedResultsReceipt, validateNycCertifiedResultsReceipt } from "./new-york-city-house-democratic-primary-certified-results-receipt";
import { NEW_YORK_DISPOSITION_PACKAGE_SHA256, type NewYorkPrimaryDispositionsReceipt, validateNewYorkPrimaryDispositionsReceipt } from "./new-york-house-democratic-primary-dispositions-receipt";

export const NEW_YORK_HOUSE_DEMOCRATIC_PRIMARY_DISPOSITIONS_V2 = "new-york-house-democratic-primary-dispositions-receipt-v2" as const;
export const NEW_YORK_DISPOSITION_V2_SET_SHA256 = "e1bbe206bf5d2e10d16e1e6fdfafbf296eb4d50221b51904e5f4ec3007b9f6fb" as const;
export const NEW_YORK_DISPOSITION_V2_PACKAGE_SHA256 = "708fb98844ecbb3664a10be938459d93e487cf2a7c16cc4e0ae573f4361de645" as const;
type Cycle = 2022 | 2024;
type Disposition = "reported_contest" | "certified_uncontested" | "unresolved_outside_retained_authority_scope";
type LocalAuthority = Readonly<{ parentSourceLockId: "new-york-city-house-democratic-primary-certified-results-2022-2024-v1"; localCertifiedContestId: string; contestSha256: string; localCertifiedSourceLockId: string; localAuthority: "Board of Elections in the City of New York"; localResultStatus: "local_canvassing_board_certified_candidate"; localSourceFileSha256: string; certificationAttestationDate: "2022-09-13" | "2024-07-16"; resultScope: "whole_district_crossover" | "single_county_whole_district" }>;
type Row = Readonly<{ seatCycleId: string; cycleYear: Cycle; stateCode: "NY"; districtCode: string; party: "Democratic"; office: "U.S. Representative"; disposition: Disposition; stateDispositionParentRowSha256: string; ballotCertificationSourceLockId: string; ballotCertificationPage: number | null; reportedContestId: string | null; localAuthority: LocalAuthority | null; voteValues: null; scoreEligible: false; evaluatorValues: Readonly<{ priorPrimaryMargin: null; priorDemocraticPrimaryVotes: null; priorProgressivePrimaryShare: null }>; rowSha256: string }>;
export type NewYorkPrimaryDispositionsV2Receipt = Readonly<{ schema: typeof NEW_YORK_HOUSE_DEMOCRATIC_PRIMARY_DISPOSITIONS_V2; version: 2; generatedAt: "2026-08-05T17:00:00.000Z"; sourceCutoff: "2026-08-05"; reviewerOnly: true; publicationEligible: false; review: Readonly<{ status: "proposed"; reviewer: null; reviewedAt: null }>; authorityScope: "composed state and NYC retained authority"; parents: Readonly<{ stateDisposition: Readonly<{ sourceLockId: "new-york-house-democratic-primary-dispositions-2022-2024-v1"; packageSha256: typeof NEW_YORK_DISPOSITION_PACKAGE_SHA256 }>; nycCertifiedResults: Readonly<{ sourceLockId: "new-york-city-house-democratic-primary-certified-results-2022-2024-v1"; packageSha256: typeof NYC_CERTIFIED_PACKAGE_SHA256 }> }>; stateLineage: Readonly<{ ballotCertifications: NewYorkPrimaryDispositionsReceipt["ballotCertifications"]; reportedResultsParent: NewYorkPrimaryDispositionsReceipt["reportedResultsParent"] }>; rows: readonly Row[]; summary: Readonly<{ seatCycles: 52; reportedContests: 19; certifiedUncontested: 15; unresolved: 18; localReportedOverrides: 8; reportedByCycle: Readonly<{ "2022": 15; "2024": 4 }>; certifiedUncontestedByCycle: Readonly<{ "2022": 4; "2024": 11 }>; unresolvedByCycle: Readonly<{ "2022": 7; "2024": 11 }>; dispositionSetSha256: string; evaluatorNumericValues: 0; scoreEligibleRows: 0 }>; limitations: readonly string[]; unresolvedGates: readonly string[]; packageSha256: string }>;

const LOCAL_KEYS = ["ny:2022:us-house:07:democratic", "ny:2022:us-house:08:democratic", "ny:2022:us-house:10:democratic", "ny:2022:us-house:11:democratic", "ny:2022:us-house:12:democratic", "ny:2022:us-house:13:democratic", "ny:2024:us-house:10:democratic", "ny:2024:us-house:14:democratic"] as const;
const LIMITATIONS = ["This v2 receipt composes two immutable reviewer candidates; it does not mutate or promote either parent.", "Only the eight exact NYC parent contests replace v1 unresolved rows. Absence from any result index remains unresolved, not uncontested, no-primary, or zero.", "Reported contest values remain in their result parents and are not copied into this disposition matrix.", "No row is public, score eligible, identity reviewed, historical-geography approved, or progressively classified."] as const;
const GATES = ["retain_remaining_county_ballot_and_result_authority", "review_incumbent_candidate_identity", "review_historical_district_compatibility", "review_progressive_candidate_classification", "complete_human_data_review_and_publication_approval"] as const;
const digest = (domain: string, value: unknown) => createHash("sha256").update(domain, "ascii").update(canonicalJson(value), "utf8").digest("hex");
const fail = (code: string): never => { throw new Error(`New York primary dispositions v2 rejected: ${code}`); };
const bytewise = (a: string, b: string) => Buffer.compare(Buffer.from(a), Buffer.from(b));
const count = (rows: readonly Row[], cycle: Cycle, disposition: Disposition) => rows.filter((row) => row.cycleYear === cycle && row.disposition === disposition).length;

export function buildNewYorkPrimaryDispositionsV2Receipt(input: Readonly<{ stateDisposition: NewYorkPrimaryDispositionsReceipt; nycCertifiedResults: NycCertifiedResultsReceipt }>): NewYorkPrimaryDispositionsV2Receipt {
  const state = validateNewYorkPrimaryDispositionsReceipt(input.stateDisposition), nyc = validateNycCertifiedResultsReceipt(input.nycCertifiedResults); const localBySeatId = new Map(nyc.contests.map((contest) => [contest.contestId.replace(/^nyc:/, "ny:"), contest])); const expected = [...LOCAL_KEYS].sort(bytewise); if (canonicalJson([...localBySeatId.keys()].sort(bytewise)) !== canonicalJson(expected)) fail("LOCAL_CONTEST_SET_INVALID");
  const rows: Row[] = state.rows.map((parent) => { const local = localBySeatId.get(parent.seatCycleId); if (local && parent.disposition !== "unresolved_outside_state_certification_scope") fail("LOCAL_OVERRIDE_PARENT_NOT_UNRESOLVED"); const disposition: Disposition = local ? "reported_contest" : parent.disposition === "unresolved_outside_state_certification_scope" ? "unresolved_outside_retained_authority_scope" : parent.disposition; const localAuthority: LocalAuthority | null = local ? { parentSourceLockId: "new-york-city-house-democratic-primary-certified-results-2022-2024-v1", localCertifiedContestId: local.contestId, contestSha256: local.contestSha256, localCertifiedSourceLockId: local.sourceLockId, localAuthority: local.authority, localResultStatus: local.resultStatus, localSourceFileSha256: local.sourceFileSha256, certificationAttestationDate: local.certificationAttestationDate, resultScope: local.resultScope } : null; const unsigned = { seatCycleId: parent.seatCycleId, cycleYear: parent.cycleYear, stateCode: parent.stateCode, districtCode: parent.districtCode, party: parent.party, office: parent.office, disposition, stateDispositionParentRowSha256: parent.rowSha256, ballotCertificationSourceLockId: parent.ballotCertificationSourceLockId, ballotCertificationPage: parent.ballotCertificationPage, reportedContestId: parent.reportedContestId, localAuthority, voteValues: null, scoreEligible: false as const, evaluatorValues: { priorPrimaryMargin: null, priorDemocraticPrimaryVotes: null, priorProgressivePrimaryShare: null } }; return { ...unsigned, rowSha256: digest("dsa-seats:ny-house-democratic-primary-disposition:v2\0", unsigned) }; });
  rows.sort((a, b) => bytewise(a.seatCycleId, b.seatCycleId)); const dispositionSetSha256 = digest("dsa-seats:ny-house-democratic-primary-disposition-set:v2\0", rows.map(({ seatCycleId, rowSha256 }) => ({ seatCycleId, rowSha256 }))); const unsigned = { schema: NEW_YORK_HOUSE_DEMOCRATIC_PRIMARY_DISPOSITIONS_V2, version: 2 as const, generatedAt: "2026-08-05T17:00:00.000Z" as const, sourceCutoff: "2026-08-05" as const, reviewerOnly: true as const, publicationEligible: false as const, review: { status: "proposed" as const, reviewer: null, reviewedAt: null }, authorityScope: "composed state and NYC retained authority" as const, parents: { stateDisposition: { sourceLockId: "new-york-house-democratic-primary-dispositions-2022-2024-v1" as const, packageSha256: NEW_YORK_DISPOSITION_PACKAGE_SHA256 }, nycCertifiedResults: { sourceLockId: "new-york-city-house-democratic-primary-certified-results-2022-2024-v1" as const, packageSha256: NYC_CERTIFIED_PACKAGE_SHA256 } }, stateLineage: { ballotCertifications: state.ballotCertifications, reportedResultsParent: state.reportedResultsParent }, rows, summary: { seatCycles: 52 as const, reportedContests: 19 as const, certifiedUncontested: 15 as const, unresolved: 18 as const, localReportedOverrides: 8 as const, reportedByCycle: { "2022": 15 as const, "2024": 4 as const }, certifiedUncontestedByCycle: { "2022": 4 as const, "2024": 11 as const }, unresolvedByCycle: { "2022": 7 as const, "2024": 11 as const }, dispositionSetSha256, evaluatorNumericValues: 0 as const, scoreEligibleRows: 0 as const }, limitations: LIMITATIONS, unresolvedGates: GATES }; return { ...unsigned, packageSha256: digest("dsa-seats:ny-house-democratic-primary-disposition-package:v2\0", unsigned) };
}

export function validateNewYorkPrimaryDispositionsV2Receipt(value: NewYorkPrimaryDispositionsV2Receipt): NewYorkPrimaryDispositionsV2Receipt {
  const { packageSha256, ...unsigned } = value; const setHash = digest("dsa-seats:ny-house-democratic-primary-disposition-set:v2\0", value.rows.map(({ seatCycleId, rowSha256 }) => ({ seatCycleId, rowSha256 }))); const ids = value.rows.map((row) => row.seatCycleId); const localKeys = value.rows.filter((row) => row.localAuthority !== null).map((row) => row.seatCycleId).sort(bytewise);
  if (packageSha256 !== NEW_YORK_DISPOSITION_V2_PACKAGE_SHA256 || packageSha256 !== digest("dsa-seats:ny-house-democratic-primary-disposition-package:v2\0", unsigned) || setHash !== NEW_YORK_DISPOSITION_V2_SET_SHA256 || value.summary.dispositionSetSha256 !== setHash || value.rows.length !== 52 || new Set(ids).size !== 52 || canonicalJson(localKeys) !== canonicalJson([...LOCAL_KEYS].sort(bytewise)) || value.rows.filter((row) => row.disposition === "reported_contest").length !== 19 || value.rows.filter((row) => row.disposition === "certified_uncontested").length !== 15 || value.rows.filter((row) => row.disposition === "unresolved_outside_retained_authority_scope").length !== 18 || count(value.rows, 2022, "reported_contest") !== 15 || count(value.rows, 2024, "reported_contest") !== 4 || count(value.rows, 2022, "certified_uncontested") !== 4 || count(value.rows, 2024, "certified_uncontested") !== 11 || count(value.rows, 2022, "unresolved_outside_retained_authority_scope") !== 7 || count(value.rows, 2024, "unresolved_outside_retained_authority_scope") !== 11 || value.summary.evaluatorNumericValues !== 0 || value.summary.scoreEligibleRows !== 0 || value.reviewerOnly !== true || value.publicationEligible !== false || canonicalJson(value.limitations) !== canonicalJson(LIMITATIONS) || canonicalJson(value.unresolvedGates) !== canonicalJson(GATES) || value.rows.some((row) => { const { rowSha256, ...rest } = row; return rowSha256 !== digest("dsa-seats:ny-house-democratic-primary-disposition:v2\0", rest) || row.voteValues !== null || row.scoreEligible || Object.values(row.evaluatorValues).some((item) => item !== null) || (row.localAuthority !== null) !== LOCAL_KEYS.includes(row.seatCycleId as typeof LOCAL_KEYS[number]) || (row.localAuthority !== null && (row.disposition !== "reported_contest" || row.reportedContestId !== null || row.localAuthority.localCertifiedContestId.replace(/^nyc:/, "ny:") !== row.seatCycleId)); })) fail("PACKAGE_INVARIANT_INVALID"); return value;
}
