import { createHash } from "node:crypto";
import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { describe, expect, it } from "vitest";

import { canonicalJson } from "../fec/aipac-proposed-packages";
import { buildNewYorkPrimaryDispositionsReceipt, validateNewYorkPrimaryDispositionsReceipt, type NewYorkPrimaryDispositionsReceipt } from "./new-york-house-democratic-primary-dispositions-receipt";
import type { NewYorkReportedResultsReceipt, NewYorkSourceEntry } from "./new-york-house-democratic-primary-reported-results-receipt";

const lock = JSON.parse(readFileSync(resolve("data/source-lock.json"), "utf8")) as { entries: NewYorkSourceEntry[] };
const certifications = () => lock.entries.filter((entry) => /^ny-202[24]-house-primary-ballot-certification$/.test(entry.id)).map((entry) => ({ entry, bytes: readFileSync(resolve(entry.retainedPath)) }));
const reportedResults = () => JSON.parse(readFileSync(resolve("data/metadata/new-york-house-democratic-primary-reported-results-2022-2024-v1.json"), "utf8")) as NewYorkReportedResultsReceipt;
const stored = () => JSON.parse(readFileSync(resolve("data/metadata/new-york-house-democratic-primary-dispositions-2022-2024-v1.json"), "utf8")) as NewYorkPrimaryDispositionsReceipt;

describe("New York Democratic House primary disposition matrix", () => {
  it("closes only the 26 state-certified district-years and leaves 26 unresolved", () => { const receipt = validateNewYorkPrimaryDispositionsReceipt(buildNewYorkPrimaryDispositionsReceipt({ certifications: certifications(), reportedResults: reportedResults() })); expect(receipt.summary).toEqual(expect.objectContaining({ seatCycles: 52, reportedContests: 11, certifiedUncontested: 15, unresolved: 26, evaluatorNumericValues: 0, scoreEligibleRows: 0 })); expect(receipt.rows.filter((row) => row.cycleYear === 2022 && row.disposition !== "unresolved_outside_state_certification_scope")).toHaveLength(13); expect(receipt.rows.filter((row) => row.cycleYear === 2024 && row.disposition !== "unresolved_outside_state_certification_scope")).toHaveLength(13); });
  it("never converts an uncontested certification or unresolved absence into a numeric result", () => { const receipt = stored(); expect(receipt.rows.every((row) => row.voteValues === null && !row.scoreEligible && Object.values(row.evaluatorValues).every((value) => value === null))).toBe(true); expect(receipt.rows.filter((row) => row.disposition === "certified_uncontested").every((row) => row.ballotCertificationPage !== null && row.reportedContestId === null)).toBe(true); expect(receipt.rows.filter((row) => row.disposition === "unresolved_outside_state_certification_scope").every((row) => row.ballotCertificationPage === null)).toBe(true); });
  it("rejects source drift and fully rehashed disposition tampering", () => { const inputs = certifications(); const changed = Buffer.from(inputs[0]!.bytes); changed[100] = changed[100]! ^ 1; expect(() => buildNewYorkPrimaryDispositionsReceipt({ certifications: [{ ...inputs[0]!, bytes: changed }, inputs[1]!], reportedResults: reportedResults() })).toThrow("CERTIFICATION_2022_INVALID"); const tampered = structuredClone(stored()); const row = tampered.rows.find((item) => item.seatCycleId === "ny:2024:us-house:02:democratic")!; (row as unknown as { disposition: string }).disposition = "reported_contest"; const unsignedRow = { ...row } as Record<string, unknown>; delete unsignedRow.rowSha256; (row as unknown as { rowSha256: string }).rowSha256 = createHash("sha256").update("dsa-seats:ny-house-democratic-primary-disposition:v1\0", "ascii").update(canonicalJson(unsignedRow), "utf8").digest("hex"); (tampered.summary as unknown as { dispositionSetSha256: string }).dispositionSetSha256 = createHash("sha256").update("dsa-seats:ny-house-democratic-primary-disposition-set:v1\0", "ascii").update(canonicalJson(tampered.rows.map(({ seatCycleId, rowSha256 }) => ({ seatCycleId, rowSha256 }))), "utf8").digest("hex"); const unsignedPackage = { ...tampered } as Record<string, unknown>; delete unsignedPackage.packageSha256; (tampered as unknown as { packageSha256: string }).packageSha256 = createHash("sha256").update("dsa-seats:ny-house-democratic-primary-disposition-package:v1\0", "ascii").update(canonicalJson(unsignedPackage), "utf8").digest("hex"); expect(() => validateNewYorkPrimaryDispositionsReceipt(tampered)).toThrow("PACKAGE_INVARIANT_INVALID"); });
  it("matches the checked-in canonical artifact byte-for-byte", () => { expect(buildNewYorkPrimaryDispositionsReceipt({ certifications: certifications(), reportedResults: reportedResults() })).toEqual(stored()); });
});
