import { createHash } from "node:crypto";

import { canonicalJson } from "../fec/aipac-proposed-packages";
import { NEW_YORK_REPORTED_PACKAGE_SHA256, type NewYorkReportedResultsReceipt, type NewYorkSourceEntry, validateNewYorkReportedResultsReceipt } from "./new-york-house-democratic-primary-reported-results-receipt";

export const NEW_YORK_HOUSE_DEMOCRATIC_PRIMARY_DISPOSITIONS_V1 = "new-york-house-democratic-primary-dispositions-receipt-v1" as const;
export const NEW_YORK_DISPOSITION_SET_SHA256 = "2493dd4ceab7616be7dc544c3c4f6e3e8abc121c4dcefde9b54ac958d209f69e" as const;
export const NEW_YORK_DISPOSITION_PACKAGE_SHA256 = "3c3b88e1d235ef89f8022456e16e2259294cfb62de3c0778a497c3fcc51d8a78" as const;
type Cycle = 2022 | 2024;
type Disposition = "reported_contest" | "certified_uncontested" | "unresolved_outside_state_certification_scope";
type CertificationInput = Readonly<{ entry: NewYorkSourceEntry; bytes: Buffer | Uint8Array | string }>;
type Row = Readonly<{ seatCycleId: string; cycleYear: Cycle; stateCode: "NY"; districtCode: string; party: "Democratic"; office: "U.S. Representative"; disposition: Disposition; ballotCertificationSourceLockId: string; ballotCertificationPage: number | null; reportedContestId: string | null; voteValues: null; scoreEligible: false; evaluatorValues: Readonly<{ priorPrimaryMargin: null; priorDemocraticPrimaryVotes: null; priorProgressivePrimaryShare: null }>; rowSha256: string }>;
export type NewYorkPrimaryDispositionsReceipt = Readonly<{ schema: typeof NEW_YORK_HOUSE_DEMOCRATIC_PRIMARY_DISPOSITIONS_V1; version: 1; generatedAt: "2026-08-05T15:00:00.000Z"; sourceCutoff: "2026-08-05"; reviewerOnly: true; publicationEligible: false; review: Readonly<{ status: "proposed"; reviewer: null; reviewedAt: null }>; originalPublisher: "New York State Board of Elections"; authorityScope: "state-certified multi-county congressional districts only"; ballotCertifications: readonly NewYorkSourceEntry[]; reportedResultsParent: Readonly<{ sourceLockId: "new-york-house-democratic-primary-reported-results-2022-2024-v1"; packageSha256: typeof NEW_YORK_REPORTED_PACKAGE_SHA256 }>; extraction: Readonly<{ tool: "pdftotext"; toolVersion: "26.07.0"; layoutMode: true; independentlyReviewedPages: true; candidateAddressesNotRetained: true }>; rows: readonly Row[]; summary: Readonly<{ seatCycles: 52; reportedContests: 11; certifiedUncontested: 15; unresolved: 26; resolvedByCycle: Readonly<{ "2022": 13; "2024": 13 }>; unresolvedByCycle: Readonly<{ "2022": 13; "2024": 13 }>; dispositionSetSha256: string; evaluatorNumericValues: 0; scoreEligibleRows: 0 }>; limitations: readonly string[]; unresolvedGates: readonly string[]; packageSha256: string }>;

const COVERED = ["02", "03", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26"] as const;
const REPORTED: Readonly<Record<Cycle, Readonly<Record<string, string>>>> = {
  2022: { "03": "ny:2022:us-house:03:democratic", "16": "ny:2022:us-house:16:democratic", "17": "ny:2022:us-house:17:democratic", "18": "ny:2022:us-house:18:democratic", "19": "ny:2022:us-house:19:democratic", "20": "ny:2022:us-house:20:democratic", "21": "ny:2022:us-house:21:democratic", "22": "ny:2022:us-house:22:democratic", "26": "ny:2022:us-house:26:democratic" },
  2024: { "16": "ny:2024:us-house:16:democratic", "22": "ny:2024:us-house:22:democratic" },
};
const UNCONTESTED: Readonly<Record<Cycle, readonly string[]>> = {
  2022: ["02", "23", "24", "25"],
  2024: ["02", "03", "17", "18", "19", "20", "21", "23", "24", "25", "26"],
};
const PAGES: Readonly<Record<Cycle, Readonly<Record<string, number>>>> = {
  2022: { "02": 3, "03": 4, "16": 5, "17": 6, "18": 7, "19": 8, "20": 9, "21": 10, "22": 11, "23": 12, "24": 12, "25": 13, "26": 14 },
  2024: { "02": 4, "03": 5, "16": 6, "17": 7, "18": 9, "19": 10, "20": 11, "21": 13, "22": 14, "23": 15, "24": 16, "25": 17, "26": 18 },
};
const LIMITATIONS = ["The two ballot certifications cover only congressional districts 02, 03, and 16 through 26 because those districts cross county boundaries; they do not establish a disposition for districts 01 or 04 through 15.", "Certified uncontested means the signed ballot certification explicitly labels the Democratic entry Uncontested; it is not a zero-vote result and carries no vote value.", "Reported-contest values remain governed by the separate reported-results receipt and are not duplicated here.", "No row is published, score eligible, identity reviewed, geography reviewed, or progressively classified."] as const;
const GATES = ["retain_county_board_authority_for_districts_01_and_04_through_15", "retain_independent_final_result_certification", "review_incumbent_candidate_identity", "review_historical_district_compatibility", "review_progressive_candidate_classification"] as const;
const sha = (value: Uint8Array) => createHash("sha256").update(value).digest("hex");
const digest = (domain: string, value: unknown) => createHash("sha256").update(domain, "ascii").update(canonicalJson(value), "utf8").digest("hex");
const fail = (code: string): never => { throw new Error(`New York primary dispositions rejected: ${code}`); };
const bytewise = (a: string, b: string) => Buffer.compare(Buffer.from(a), Buffer.from(b));

function verifyCertification(input: CertificationInput, year: Cycle): NewYorkSourceEntry {
  const expected = year === 2022 ? { size: 459911, hash: "ad7c4d99a0a561ac7bff1c4888c776ea921f5b0b08cebb85246f3c7f6cbdb53d" } : { size: 1369420, hash: "9b102d07b67f5dea488c22bf4d3be03d6459c39cd7e36b651fd2bbb27982d5eb" };
  const bytes = Buffer.from(input.bytes); if (input.entry.id !== `ny-${year}-house-primary-ballot-certification` || input.entry.retainedPath !== `data/source/elections/primary-results/new-york/${year}/official-primary-ballot-certification.pdf` || input.entry.byteSize !== expected.size || input.entry.sha256 !== expected.hash || bytes.byteLength !== expected.size || sha(bytes) !== expected.hash || bytes.subarray(0, 5).toString("ascii") !== "%PDF-" || input.entry.retainedStatus !== "retained" || input.entry.kind !== "source" || input.entry.parentIds.length !== 0) fail(`CERTIFICATION_${year}_INVALID`); return input.entry;
}

export function buildNewYorkPrimaryDispositionsReceipt(input: Readonly<{ certifications: readonly CertificationInput[]; reportedResults: NewYorkReportedResultsReceipt }>): NewYorkPrimaryDispositionsReceipt {
  const reported = validateNewYorkReportedResultsReceipt(input.reportedResults); const byYear = new Map(input.certifications.map((item) => [Number(item.entry.id.slice(3, 7)) as Cycle, item])); if (byYear.size !== 2) fail("CERTIFICATION_CLOSURE_INVALID");
  const ballotCertifications = ([2022, 2024] as const).map((year) => verifyCertification(byYear.get(year) ?? fail(`CERTIFICATION_${year}_MISSING`), year));
  const resultIds = new Set(reported.contests.map((contest) => contest.contestId)); const rows: Row[] = [];
  for (const cycleYear of [2022, 2024] as const) { const classified = [...Object.keys(REPORTED[cycleYear]), ...UNCONTESTED[cycleYear]].sort(bytewise); if (canonicalJson(classified) !== canonicalJson([...COVERED].sort(bytewise))) fail(`CERTIFICATION_PARTITION_${cycleYear}_INVALID`); for (let district = 1; district <= 26; district++) { const districtCode = String(district).padStart(2, "0"); const reportedContestId = REPORTED[cycleYear][districtCode] ?? null; const explicitlyUncontested = UNCONTESTED[cycleYear].includes(districtCode); if (reportedContestId && !resultIds.has(reportedContestId)) fail("REPORTED_PARENT_MISMATCH"); const disposition: Disposition = reportedContestId ? "reported_contest" : explicitlyUncontested ? "certified_uncontested" : "unresolved_outside_state_certification_scope"; const covered = disposition !== "unresolved_outside_state_certification_scope"; const unsigned = { seatCycleId: `ny:${cycleYear}:us-house:${districtCode}:democratic`, cycleYear, stateCode: "NY" as const, districtCode, party: "Democratic" as const, office: "U.S. Representative" as const, disposition, ballotCertificationSourceLockId: `ny-${cycleYear}-house-primary-ballot-certification`, ballotCertificationPage: covered ? PAGES[cycleYear][districtCode]! : null, reportedContestId, voteValues: null, scoreEligible: false as const, evaluatorValues: { priorPrimaryMargin: null, priorDemocraticPrimaryVotes: null, priorProgressivePrimaryShare: null } }; rows.push({ ...unsigned, rowSha256: digest("dsa-seats:ny-house-democratic-primary-disposition:v1\0", unsigned) }); } }
  rows.sort((a, b) => bytewise(a.seatCycleId, b.seatCycleId)); const dispositionSetSha256 = digest("dsa-seats:ny-house-democratic-primary-disposition-set:v1\0", rows.map(({ seatCycleId, rowSha256 }) => ({ seatCycleId, rowSha256 }))); const unsigned = { schema: NEW_YORK_HOUSE_DEMOCRATIC_PRIMARY_DISPOSITIONS_V1, version: 1 as const, generatedAt: "2026-08-05T15:00:00.000Z" as const, sourceCutoff: "2026-08-05" as const, reviewerOnly: true as const, publicationEligible: false as const, review: { status: "proposed" as const, reviewer: null, reviewedAt: null }, originalPublisher: "New York State Board of Elections" as const, authorityScope: "state-certified multi-county congressional districts only" as const, ballotCertifications, reportedResultsParent: { sourceLockId: "new-york-house-democratic-primary-reported-results-2022-2024-v1" as const, packageSha256: NEW_YORK_REPORTED_PACKAGE_SHA256 }, extraction: { tool: "pdftotext" as const, toolVersion: "26.07.0" as const, layoutMode: true as const, independentlyReviewedPages: true as const, candidateAddressesNotRetained: true as const }, rows, summary: { seatCycles: 52 as const, reportedContests: 11 as const, certifiedUncontested: 15 as const, unresolved: 26 as const, resolvedByCycle: { "2022": 13 as const, "2024": 13 as const }, unresolvedByCycle: { "2022": 13 as const, "2024": 13 as const }, dispositionSetSha256, evaluatorNumericValues: 0 as const, scoreEligibleRows: 0 as const }, limitations: LIMITATIONS, unresolvedGates: GATES };
  return { ...unsigned, packageSha256: digest("dsa-seats:ny-house-democratic-primary-disposition-package:v1\0", unsigned) };
}

export function validateNewYorkPrimaryDispositionsReceipt(value: NewYorkPrimaryDispositionsReceipt): NewYorkPrimaryDispositionsReceipt {
  const { packageSha256, ...unsigned } = value; const setHash = digest("dsa-seats:ny-house-democratic-primary-disposition-set:v1\0", value.rows.map(({ seatCycleId, rowSha256 }) => ({ seatCycleId, rowSha256 }))); const counts = { reported: value.rows.filter((row) => row.disposition === "reported_contest").length, uncontested: value.rows.filter((row) => row.disposition === "certified_uncontested").length, unresolved: value.rows.filter((row) => row.disposition === "unresolved_outside_state_certification_scope").length };
  if (packageSha256 !== NEW_YORK_DISPOSITION_PACKAGE_SHA256 || packageSha256 !== digest("dsa-seats:ny-house-democratic-primary-disposition-package:v1\0", unsigned) || setHash !== NEW_YORK_DISPOSITION_SET_SHA256 || value.summary.dispositionSetSha256 !== setHash || value.rows.length !== 52 || counts.reported !== 11 || counts.uncontested !== 15 || counts.unresolved !== 26 || value.reviewerOnly !== true || value.publicationEligible !== false || value.summary.evaluatorNumericValues !== 0 || value.summary.scoreEligibleRows !== 0 || canonicalJson(value.limitations) !== canonicalJson(LIMITATIONS) || canonicalJson(value.unresolvedGates) !== canonicalJson(GATES) || value.rows.some((row) => { const { rowSha256, ...rest } = row; return rowSha256 !== digest("dsa-seats:ny-house-democratic-primary-disposition:v1\0", rest) || row.voteValues !== null || row.scoreEligible || Object.values(row.evaluatorValues).some((item) => item !== null) || (row.disposition === "unresolved_outside_state_certification_scope") !== (row.ballotCertificationPage === null); })) fail("PACKAGE_INVARIANT_INVALID"); return value;
}
