import { createHash } from "node:crypto";
import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { describe, expect, it } from "vitest";

import { canonicalJson } from "../fec/aipac-proposed-packages";
import { buildNewYorkPrimaryDispositionsV2Receipt, validateNewYorkPrimaryDispositionsV2Receipt, type NewYorkPrimaryDispositionsV2Receipt } from "./new-york-house-democratic-primary-dispositions-v2-receipt";
import type { NycCertifiedResultsReceipt } from "./new-york-city-house-democratic-primary-certified-results-receipt";
import type { NewYorkPrimaryDispositionsReceipt } from "./new-york-house-democratic-primary-dispositions-receipt";

const stateDisposition = () => JSON.parse(readFileSync(resolve("data/metadata/new-york-house-democratic-primary-dispositions-2022-2024-v1.json"), "utf8")) as NewYorkPrimaryDispositionsReceipt;
const nycCertifiedResults = () => JSON.parse(readFileSync(resolve("data/metadata/new-york-city-house-democratic-primary-certified-results-2022-2024-v1.json"), "utf8")) as NycCertifiedResultsReceipt;
const stored = () => JSON.parse(readFileSync(resolve("data/metadata/new-york-house-democratic-primary-dispositions-2022-2024-v2.json"), "utf8")) as NewYorkPrimaryDispositionsV2Receipt;
const localKeys = ["ny:2022:us-house:07:democratic", "ny:2022:us-house:08:democratic", "ny:2022:us-house:10:democratic", "ny:2022:us-house:11:democratic", "ny:2022:us-house:12:democratic", "ny:2022:us-house:13:democratic", "ny:2024:us-house:10:democratic", "ny:2024:us-house:14:democratic"];

describe("New York Democratic House primary disposition matrix v2", () => {
  it("replaces exactly eight unresolved rows with local reported contests", () => { const receipt = validateNewYorkPrimaryDispositionsV2Receipt(buildNewYorkPrimaryDispositionsV2Receipt({ stateDisposition: stateDisposition(), nycCertifiedResults: nycCertifiedResults() })); expect(receipt.summary).toEqual(expect.objectContaining({ seatCycles: 52, reportedContests: 19, certifiedUncontested: 15, unresolved: 18, localReportedOverrides: 8, reportedByCycle: { "2022": 15, "2024": 4 }, unresolvedByCycle: { "2022": 7, "2024": 11 }, evaluatorNumericValues: 0, scoreEligibleRows: 0 })); expect(receipt.rows.filter((row) => row.localAuthority !== null).map((row) => row.seatCycleId)).toEqual(localKeys); });
  it("keeps state and NYC authority in distinct fields with exact parent lineage", () => { const state = stateDisposition(), nyc = nycCertifiedResults(), receipt = stored(); const stateRows = new Map(state.rows.map((row) => [row.seatCycleId, row])); const localContests = new Map(nyc.contests.map((contest) => [contest.contestId.replace(/^nyc:/, "ny:"), contest])); for (const row of receipt.rows) { const parent = stateRows.get(row.seatCycleId)!; expect(row.stateDispositionParentRowSha256).toBe(parent.rowSha256); expect(row.ballotCertificationSourceLockId).toBe(parent.ballotCertificationSourceLockId); expect(row.ballotCertificationPage).toBe(parent.ballotCertificationPage); expect(row.reportedContestId).toBe(parent.reportedContestId); const local = localContests.get(row.seatCycleId); if (local) expect(row.localAuthority).toEqual(expect.objectContaining({ localCertifiedContestId: local.contestId, contestSha256: local.contestSha256, localCertifiedSourceLockId: local.sourceLockId, localSourceFileSha256: local.sourceFileSha256 })); else expect(row.localAuthority).toBeNull(); } });
  it("retains no vote or evaluator value", () => { expect(stored().rows.every((row) => row.voteValues === null && !row.scoreEligible && Object.values(row.evaluatorValues).every((value) => value === null))).toBe(true); });
  it("rejects a fully rehashed local/state authority collapse", () => { const receipt = structuredClone(stored()), row = receipt.rows.find((item) => item.localAuthority !== null)!; (row as unknown as { reportedContestId: string }).reportedContestId = row.localAuthority!.localCertifiedContestId; const unsignedRow = { ...row } as Record<string, unknown>; delete unsignedRow.rowSha256; (row as unknown as { rowSha256: string }).rowSha256 = createHash("sha256").update("dsa-seats:ny-house-democratic-primary-disposition:v2\0", "ascii").update(canonicalJson(unsignedRow), "utf8").digest("hex"); (receipt.summary as unknown as { dispositionSetSha256: string }).dispositionSetSha256 = createHash("sha256").update("dsa-seats:ny-house-democratic-primary-disposition-set:v2\0", "ascii").update(canonicalJson(receipt.rows.map(({ seatCycleId, rowSha256 }) => ({ seatCycleId, rowSha256 }))), "utf8").digest("hex"); const unsignedPackage = { ...receipt } as Record<string, unknown>; delete unsignedPackage.packageSha256; (receipt as unknown as { packageSha256: string }).packageSha256 = createHash("sha256").update("dsa-seats:ny-house-democratic-primary-disposition-package:v2\0", "ascii").update(canonicalJson(unsignedPackage), "utf8").digest("hex"); expect(() => validateNewYorkPrimaryDispositionsV2Receipt(receipt)).toThrow("PACKAGE_INVARIANT_INVALID"); });
  it("matches the checked-in canonical artifact byte-for-byte", () => { expect(buildNewYorkPrimaryDispositionsV2Receipt({ stateDisposition: stateDisposition(), nycCertifiedResults: nycCertifiedResults() })).toEqual(stored()); });
});
