import { execFileSync } from "node:child_process";
import { createHash } from "node:crypto";
import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { describe, expect, it } from "vitest";
import { canonicalJson } from "../fec/aipac-proposed-packages";
import { assertNjPaPrimaryGeographyRowSemantics, buildNjPaPrimaryGeographyCompatibilityCandidate, parseTigerDistrictDbf, validateNjPaPrimaryGeographyCompatibilityCandidate } from "./nj-pa-primary-geography-compatibility-candidate";

const read = (path: string): Buffer => readFileSync(resolve(path));
const json = (path: string): unknown => JSON.parse(read(path).toString("utf8"));
const sha = (value: Buffer): string => createHash("sha256").update(value).digest("hex");
const dbf = (path: string): Buffer => execFileSync("unzip", ["-p", resolve(path), "*.dbf"], { maxBuffer: 4 * 1024 * 1024 });
function inputs() { const proposal = read("data/metadata/house-democratic-primary-source-selection-proposal-20260804-v1.json"), linkage = read("data/metadata/current-incumbent-primary-candidate-linkage-candidate-v1.json"), authority = read("data/source/elections/primary-results/geography/census-119-congressional-district-bef.html"), nj118 = read("data/source/tiger2022/tl_2022_34_cd118.zip"), pa118 = read("data/source/tiger2022/tl_2022_42_cd118.zip"), nj119 = read("data/source/tiger2025/tl_2025_34_cd119.zip"), pa119 = read("data/source/tiger2025/tl_2025_42_cd119.zip"); return { proposal: JSON.parse(proposal.toString("utf8")), proposalFileSha256: sha(proposal), linkage: JSON.parse(linkage.toString("utf8")), linkageFileSha256: sha(linkage), authorityHtml: authority.toString("utf8"), authorityFileSha256: sha(authority), nj118Dbf: dbf("data/source/tiger2022/tl_2022_34_cd118.zip"), nj118FileSha256: sha(nj118), pa118Dbf: dbf("data/source/tiger2022/tl_2022_42_cd118.zip"), pa118FileSha256: sha(pa118), nj119Dbf: dbf("data/source/tiger2025/tl_2025_34_cd119.zip"), nj119FileSha256: sha(nj119), pa119Dbf: dbf("data/source/tiger2025/tl_2025_42_cd119.zip"), pa119FileSha256: sha(pa119), sourceLock: json("data/source-lock.json") }; }
const build = () => buildNjPaPrimaryGeographyCompatibilityCandidate(inputs());

describe("NJ/PA primary geography compatibility candidate", () => {
  it("accounts for all 41 observations without approval, scoring, publication, or parent supersession", () => { const value = build(); expect(value.summary).toEqual({ seatCycleObservations: 41, cd118ToCd119PlanContinuityCandidates: 16, exactCd119SessionKeyCandidates: 16, cd120AuthorityPending: 9, compatibilityCandidates: 32, automaticallyApprovedRows: 0, scoreEligibleRows: 0 }); expect(value.review).toEqual({ status: "proposed", reviewer: null, reviewedAt: null, resolution: null }); expect({ parentSourceCutoff: value.parentSourceCutoff, parentSuperseded: value.parentSuperseded }).toEqual({ parentSourceCutoff: "2026-08-04", parentSuperseded: false }); expect(value.rows.every((row) => !row.compatibilityApproved && !row.identityApproved && !row.scoreEligible)).toBe(true); });
  it("uses direct plan-continuity evidence only for 2022 and exact CD119 keys only for 2024", () => { const value = build(); expect(value.rows.filter((row) => row.cycleYear === 2022).every((row) => row.historicalCongressSession === "118" && row.compatibilityDisposition === "official_no_plan_change_declaration_same_geoid_key_candidate" && row.historicalGeoid === row.targetCd119Geoid)).toBe(true); expect(value.rows.filter((row) => row.cycleYear === 2024).every((row) => row.historicalCongressSession === "119" && row.compatibilityDisposition === "same_cd119_session_and_geoid_exact_key_candidate" && row.historicalGeoid === row.targetCd119Geoid)).toBe(true); });
  it("leaves every 2026 observation unassessed pending CD120 authority", () => { const rows = build().rows.filter((row) => row.cycleYear === 2026); expect(rows).toHaveLength(9); expect(rows.every((row) => row.historicalCongressSession === "120" && row.historicalGeoid === null && !row.compatibilityCandidate && row.confidence === "none")).toBe(true); });
  it("binds all linkage and contest hashes without copying candidate personal data", () => { const value = build(), linkage = json("data/metadata/current-incumbent-primary-candidate-linkage-candidate-v1.json") as { links: { linkageId: string; contestSha256: string }[] }; expect(value.rows.map((row) => [row.linkageId, row.contestSha256])).toEqual(linkage.links.map((row) => [row.linkageId, row.contestSha256]).sort((a, b) => String(a[0]).localeCompare(String(b[0])))); expect(JSON.stringify(value)).not.toMatch(/sourceCandidateName|address|email|phone|donor/i); });
  it("proves exact NJ and PA session closures from both TIGER inventories", () => { const value = build(); expect(value.inputs.tigerLayers.map((layer) => [layer.stateFips, layer.cdSession, layer.districtCount])).toEqual([["34", "118", 12], ["42", "118", 17], ["34", "119", 12], ["42", "119", 17]]); expect(new Set(value.inputs.tigerLayers.map((layer) => layer.districtInventorySha256)).size).toBe(4); });
  it("rejects source-lock kind and retained-path substitutions independently", () => { const wrongKind = inputs(), wrongPath = inputs(); (wrongKind.sourceLock as { entries: { id: string; kind: string }[] }).entries.find((entry) => entry.id === "tiger-cd118-34")!.kind = "derived_artifact"; (wrongPath.sourceLock as { entries: { id: string; retainedPath?: string }[] }).entries.find((entry) => entry.id === "tiger-cd118-34")!.retainedPath = "data/source/tiger2022/substituted.zip"; expect(() => buildNjPaPrimaryGeographyCompatibilityCandidate(wrongKind)).toThrow("PRIMARY_GEOGRAPHY_SOURCE_LOCK_MISMATCH"); expect(() => buildNjPaPrimaryGeographyCompatibilityCandidate(wrongPath)).toThrow("PRIMARY_GEOGRAPHY_SOURCE_LOCK_MISMATCH"); });
  it("rejects a CD118 record that claims the wrong congressional session", () => { const bytes = Buffer.from(dbf("data/source/tiger2022/tl_2022_34_cd118.zip")), headerLength = bytes.readUInt16LE(8), index = bytes.indexOf(Buffer.from("118"), headerLength); expect(index).toBeGreaterThan(headerLength); bytes.write("119", index, "ascii"); expect(() => parseTigerDistrictDbf(bytes, "34", "118")).toThrow("PRIMARY_GEOGRAPHY_TIGER_INVENTORY_INVALID"); });
  it("rejects an altered DBF member even alongside the asserted source ZIP hash", () => { const value = inputs(); value.nj118Dbf = Buffer.from(value.nj118Dbf); value.nj118Dbf[value.nj118Dbf.length - 2] ^= 1; expect(() => buildNjPaPrimaryGeographyCompatibilityCandidate(value)).toThrow("PRIMARY_GEOGRAPHY_DBF_MEMBER_HASH_MISMATCH"); });
  it("rejects a fully rehashed 2022 row relabeled as a CD119 exact-session relationship", () => { const value = build(), changed = structuredClone(value.rows), target = changed.find((row) => row.cycleYear === 2022)!; target.historicalCongressSession = "119"; target.compatibilityDisposition = "same_cd119_session_and_geoid_exact_key_candidate"; target.evidenceClass = "derived_exact_session_and_key"; target.rationaleCodes = ["same_cd119_congressional_session", "same_state_district_geoid_in_cd119_inventory"]; const { rowSha256, ...unsigned } = target; expect(rowSha256).toMatch(/^[a-f0-9]{64}$/); target.rowSha256 = createHash("sha256").update("dsa-seats:nj-pa-primary-geography-row:v1\0").update(canonicalJson(unsigned)).digest("hex"); expect(() => assertNjPaPrimaryGeographyRowSemantics(changed)).toThrow("PRIMARY_GEOGRAPHY_ROW_OR_SET_INVALID"); });
  it("validates the retained immutable candidate", () => { expect(validateNjPaPrimaryGeographyCompatibilityCandidate(json("data/metadata/nj-pa-primary-geography-compatibility-candidate-v1.json")).packageSha256).toBe("cb662d10fcec1726518ac4329b16e2110ed4776d047b6b838421deb633f62a52"); });
});
