import { createHash } from "node:crypto";
import { z } from "zod";
import { canonicalJson } from "../fec/aipac-proposed-packages";
import { validateCurrentIncumbentPrimaryCandidateLinkageCandidate } from "./current-incumbent-primary-candidate-linkage-candidate";
import { validateHouseDemocraticPrimarySourceSelectionProposal } from "./house-democratic-primary-source-selection-proposal";

const SHA = z.string().regex(/^[a-f0-9]{64}$/);
const INPUTS = {
  proposalFile: "85246e9adfd181e6f24606b6eaa29250c45c9e8e42a6dd5af5cb162de17f45b1", proposalPackage: "a090e0be03dc2b0fa5edd0c1132a8261eed0f98ceb4df090154d0b150d8721fb",
  linkageFile: "d4b05e851c9024cad4076e07cf921cc21176ae3d2e92caaf4e847b5a9d85f53d", linkagePackage: "cea679fcc77960acf076de64d1d8fe4bbac668a024af7e345332f1effa76a4f4",
  authorityFile: "66a0551a6c3c6432bff0a6a6db23f221fbe02ead1d15221d7050633898914670",
  nj118File: "f50511a1a6971143732e73b1941a96ad6968d0703f4a5236c597dbb00e0f63cf", pa118File: "3e59d0b48b291c0ab626879b4d286b58506530706bcba6d0cfe767b531728a22",
  nj119File: "0bda6693ad95eaeccf6cf30e0d86842ae0928f36d8fc78b6cb9c4ac814fe2155", pa119File: "63945666b675bc4ddc6b99e06e36b6fdb389c132937b880491c370f77f532ae8",
  nj118Dbf: "cc81055a1de9287fddd8b1d06225c068db7ac93f154314a798578a0de66e66b3", pa118Dbf: "f1269e6a78d27782991f840e23390e10689e2951d3da686ebc6f840f2826d284",
  nj119Dbf: "09f9cdb0870c3f3e7d29f317f9e4decdbc81de03d96282889234dffe596de795", pa119Dbf: "303cc46247c5776df84986841862b806723b1dcc9795ef23fbfa5ce9d1e4bde2",
} as const;
const EXPECTED_PACKAGE = "cb662d10fcec1726518ac4329b16e2110ed4776d047b6b838421deb633f62a52";
const digest = (domain: string, value: unknown): string => createHash("sha256").update(domain).update(canonicalJson(value)).digest("hex");
const fileDigest = (value: Buffer | string): string => createHash("sha256").update(value).digest("hex");
const bytewise = (a: string, b: string): number => Buffer.compare(Buffer.from(a), Buffer.from(b));

export type TigerDistrictInventoryRow = Readonly<{ geoid: string; stateFips: "34" | "42"; districtCode: string; cdSession: "118" | "119"; landArea: number; waterArea: number }>;

function parseDbf(bytes: Buffer): ReadonlyArray<Readonly<Record<string, string>>> {
  if (bytes.length < 65 || bytes[0] !== 0x03) throw new Error("PRIMARY_GEOGRAPHY_DBF_HEADER_INVALID");
  const count = bytes.readUInt32LE(4), headerLength = bytes.readUInt16LE(8), recordLength = bytes.readUInt16LE(10);
  if (count < 1 || headerLength < 65 || recordLength < 2 || headerLength + count * recordLength > bytes.length) throw new Error("PRIMARY_GEOGRAPHY_DBF_LAYOUT_INVALID");
  const fields: { name: string; length: number; offset: number }[] = []; let offset = 1;
  for (let cursor = 32; cursor + 32 <= headerLength && bytes[cursor] !== 0x0d; cursor += 32) { const name = bytes.subarray(cursor, cursor + 11).toString("ascii").replace(/\0.*$/, "").trim(), length = bytes[cursor + 16]!; if (!name || length < 1) throw new Error("PRIMARY_GEOGRAPHY_DBF_FIELD_INVALID"); fields.push({ name, length, offset }); offset += length; }
  if (!fields.length || offset !== recordLength || bytes[headerLength - 1] !== 0x0d) throw new Error("PRIMARY_GEOGRAPHY_DBF_FIELDS_INVALID");
  return Array.from({ length: count }, (_, index) => { const start = headerLength + index * recordLength; if (bytes[start] !== 0x20) throw new Error("PRIMARY_GEOGRAPHY_DBF_DELETED_RECORD"); return Object.fromEntries(fields.map((field) => [field.name, bytes.subarray(start + field.offset, start + field.offset + field.length).toString("ascii").trim()])); });
}

export function parseTigerDistrictDbf(bytes: Buffer, stateFips: "34" | "42", cdSession: "118" | "119"): readonly TigerDistrictInventoryRow[] {
  const historical = cdSession === "118", stateField = historical ? "STATEFP20" : "STATEFP", geoidField = historical ? "GEOID20" : "GEOID", districtField = historical ? "CD118FP" : "CD119FP", landField = historical ? "ALAND20" : "ALAND", waterField = historical ? "AWATER20" : "AWATER";
  const rows = parseDbf(bytes).map((value) => ({ geoid: value[geoidField]!, stateFips: value[stateField] as "34" | "42", districtCode: value[districtField]!, cdSession: value.CDSESSN as "118" | "119", landArea: Number(value[landField]), waterArea: Number(value[waterField]) })).sort((a, b) => bytewise(a.geoid, b.geoid));
  const expectedCount = stateFips === "34" ? 12 : 17, expectedCodes = Array.from({ length: expectedCount }, (_, index) => String(index + 1).padStart(2, "0"));
  if (rows.length !== expectedCount || rows.some((value, index) => value.stateFips !== stateFips || value.cdSession !== cdSession || value.districtCode !== expectedCodes[index] || value.geoid !== `${stateFips}${value.districtCode}` || !Number.isSafeInteger(value.landArea) || value.landArea <= 0 || !Number.isSafeInteger(value.waterArea) || value.waterArea < 0)) throw new Error("PRIMARY_GEOGRAPHY_TIGER_INVENTORY_INVALID");
  return rows;
}

const layer = z.strictObject({ sourceLockId: z.string(), fileSha256: SHA, dbfMemberSha256: SHA, stateFips: z.enum(["34", "42"]), cdSession: z.enum(["118", "119"]), districtCount: z.number().int().positive(), districtInventorySha256: SHA });
const row = z.strictObject({
  linkageId: z.string(), contestSha256: SHA, seatCycleId: z.string(), stateCode: z.enum(["NJ", "PA"]), districtCode: z.string().regex(/^\d{2}$/), cycleYear: z.union([z.literal(2022), z.literal(2024), z.literal(2026)]), targetCd119Geoid: z.string().regex(/^(34|42)\d{2}$/), historicalCongressSession: z.enum(["118", "119", "120"]), historicalGeoid: z.string().regex(/^(34|42)\d{2}$/).nullable(),
  compatibilityDisposition: z.enum(["official_no_plan_change_declaration_same_geoid_key_candidate", "same_cd119_session_and_geoid_exact_key_candidate", "unassessed_cd120_authority_collection_pending"]), evidenceClass: z.enum(["direct_official_plan_continuity_and_derived_key", "derived_exact_session_and_key", "authority_pending"]), confidence: z.enum(["high", "none"]), compatibilityCandidate: z.boolean(), compatibilityApproved: z.literal(false), identityApproved: z.literal(false), evaluatorUse: z.literal("excluded_pending_authorized_identity_and_historical_geography_review"), scoreEligible: z.literal(false), rationaleCodes: z.array(z.string()).min(1), rowSha256: SHA,
});
export const njPaPrimaryGeographyCompatibilityCandidateSchema = z.strictObject({
  schema: z.literal("nj-pa-primary-geography-compatibility-candidate-v1"), version: z.literal(1), generatedAt: z.literal("2026-08-06T15:00:00.000Z"), sourceCutoff: z.literal("2026-08-05"), parentSourceCutoff: z.literal("2026-08-04"), parentSuperseded: z.literal(false), reviewerOnly: z.literal(true), publicationEligible: z.literal(false), defaultUse: z.literal("exclude_from_evaluator_until_authorized_identity_and_historical_geography_review"), review: z.strictObject({ status: z.literal("proposed"), reviewer: z.null(), reviewedAt: z.null(), resolution: z.null() }),
  inputs: z.strictObject({ sourceSelectionProposal: z.strictObject({ sourceLockId: z.literal("house-democratic-primary-source-selection-proposal-20260804-v1"), fileSha256: z.literal(INPUTS.proposalFile), packageSha256: z.literal(INPUTS.proposalPackage), informedDecisionId: z.literal("approve-historical-district-cd119-compatibility-v1"), decisionUnresolved: z.literal(true) }), linkageCandidate: z.strictObject({ sourceLockId: z.literal("current-incumbent-primary-candidate-linkage-candidate-v1"), fileSha256: z.literal(INPUTS.linkageFile), packageSha256: z.literal(INPUTS.linkagePackage), identityDecisionUnresolved: z.literal(true) }), censusPlanChangeAuthority: z.strictObject({ sourceLockId: z.literal("census-cd119-plan-change-authority-20260805"), fileSha256: z.literal(INPUTS.authorityFile), authorityClaim: z.literal("five_states_redrew_for_cd119_al_ga_la_ny_nc_nj_pa_absent") }), tigerLayers: z.array(layer).length(4) }),
  methodology: z.strictObject({ targetSession: z.literal("119"), cycleSessionMapping: z.strictObject({ "2022": z.literal("118"), "2024": z.literal("119"), "2026": z.literal("120") }), planContinuityRule: z.literal("official_census_redraw_scope_declaration_plus_same_state_district_key"), exactSameSessionRule: z.literal("same_cd119_session_state_and_district_geoid"), cd120Rule: z.literal("remain_unassessed_until_authoritative_cd120_plan_evidence_is_retained"), rawTigerGeometryEqualityAssessed: z.literal(false), rawCoordinateDifferenceImpliesPlanChange: z.literal(false), overlapThresholdUsed: z.literal(false), automaticDecisionClosure: z.literal(false), evaluatorNumericValues: z.literal(0) }),
  privacy: z.strictObject({ candidatePersonalDataExcluded: z.literal(true), rawGeometryExcluded: z.literal(true), rawSourceTextExcluded: z.literal(true) }),
  summary: z.strictObject({ seatCycleObservations: z.literal(41), cd118ToCd119PlanContinuityCandidates: z.literal(16), exactCd119SessionKeyCandidates: z.literal(16), cd120AuthorityPending: z.literal(9), compatibilityCandidates: z.literal(32), automaticallyApprovedRows: z.literal(0), scoreEligibleRows: z.literal(0) }),
  rows: z.array(row).length(41), rowSetSha256: SHA, decisionSupport: z.strictObject({ informsDecisionId: z.literal("approve-historical-district-cd119-compatibility-v1"), analysisConclusion: z.literal("official_evidence_supports_nj_pa_cd118_to_cd119_plan_continuity_and_exact_cd119_keys_while_cd120_remains_unassessed"), lifecycle: z.literal("evidence_for_bound_existing_decision_not_an_independent_decision") }), packageSha256: SHA,
});
export type NjPaPrimaryGeographyCompatibilityCandidate = z.infer<typeof njPaPrimaryGeographyCompatibilityCandidateSchema>;

type BuildInput = Readonly<{ proposal: unknown; proposalFileSha256: string; linkage: unknown; linkageFileSha256: string; authorityHtml: string; authorityFileSha256: string; nj118Dbf: Buffer; nj118FileSha256: string; pa118Dbf: Buffer; pa118FileSha256: string; nj119Dbf: Buffer; nj119FileSha256: string; pa119Dbf: Buffer; pa119FileSha256: string; sourceLock: unknown }>;
export function buildNjPaPrimaryGeographyCompatibilityCandidate(input: BuildInput): NjPaPrimaryGeographyCompatibilityCandidate {
  const files = [input.proposalFileSha256, input.linkageFileSha256, input.authorityFileSha256, input.nj118FileSha256, input.pa118FileSha256, input.nj119FileSha256, input.pa119FileSha256], expected = [INPUTS.proposalFile, INPUTS.linkageFile, INPUTS.authorityFile, INPUTS.nj118File, INPUTS.pa118File, INPUTS.nj119File, INPUTS.pa119File];
  if (files.some((value, index) => value !== expected[index]) || fileDigest(input.authorityHtml) !== INPUTS.authorityFile) throw new Error("PRIMARY_GEOGRAPHY_INPUT_FILE_HASH_MISMATCH");
  const dbfHashes = [fileDigest(input.nj118Dbf), fileDigest(input.pa118Dbf), fileDigest(input.nj119Dbf), fileDigest(input.pa119Dbf)], expectedDbfHashes = [INPUTS.nj118Dbf, INPUTS.pa118Dbf, INPUTS.nj119Dbf, INPUTS.pa119Dbf];
  if (dbfHashes.some((value, index) => value !== expectedDbfHashes[index])) throw new Error("PRIMARY_GEOGRAPHY_DBF_MEMBER_HASH_MISMATCH");
  const proposal = validateHouseDemocraticPrimarySourceSelectionProposal(input.proposal), linkage = validateCurrentIncumbentPrimaryCandidateLinkageCandidate(input.linkage), decision = proposal.decisions.find((value) => value.decisionId === "approve-historical-district-cd119-compatibility-v1");
  if (proposal.packageSha256 !== INPUTS.proposalPackage || linkage.packageSha256 !== INPUTS.linkagePackage || !decision || decision.resolution !== null || linkage.review.resolution !== null) throw new Error("PRIMARY_GEOGRAPHY_PARENT_OR_DECISION_INVALID");
  const phrase = "five states (Alabama, Georgia, Louisiana, New York, and North Carolina) that redrew their congressional district plans for the 119th Congress";
  if (!input.authorityHtml.includes(phrase) || input.authorityHtml.includes("five states (Alabama, Georgia, Louisiana, New Jersey") || input.authorityHtml.includes("five states (Alabama, Georgia, Louisiana, Pennsylvania")) throw new Error("PRIMARY_GEOGRAPHY_AUTHORITY_SEMANTICS_INVALID");
  const inventories = [parseTigerDistrictDbf(input.nj118Dbf, "34", "118"), parseTigerDistrictDbf(input.pa118Dbf, "42", "118"), parseTigerDistrictDbf(input.nj119Dbf, "34", "119"), parseTigerDistrictDbf(input.pa119Dbf, "42", "119")];
  const layerSpecs = [["tiger-cd118-34", INPUTS.nj118File, INPUTS.nj118Dbf, "34", "118"], ["tiger-cd118-42", INPUTS.pa118File, INPUTS.pa118Dbf, "42", "118"], ["tiger-cd119-34", INPUTS.nj119File, INPUTS.nj119Dbf, "34", "119"], ["tiger-cd119-42", INPUTS.pa119File, INPUTS.pa119Dbf, "42", "119"]] as const;
  const tigerLayers = layerSpecs.map(([sourceLockId, fileSha256, dbfMemberSha256, stateFips, cdSession], index) => ({ sourceLockId, fileSha256, dbfMemberSha256, stateFips, cdSession, districtCount: inventories[index]!.length, districtInventorySha256: digest("dsa-seats:tiger-district-inventory:v1\0", inventories[index]) }));
  const lock = z.object({ entries: z.array(z.object({ id: z.string(), retainedPath: z.string().nullable().optional(), retainedStatus: z.string(), sha256: SHA, kind: z.string() })) }).parse(input.sourceLock);
  const required = [["house-democratic-primary-source-selection-proposal-20260804-v1", INPUTS.proposalFile, "data/metadata/house-democratic-primary-source-selection-proposal-20260804-v1.json", "review_proposal"], ["current-incumbent-primary-candidate-linkage-candidate-v1", INPUTS.linkageFile, "data/metadata/current-incumbent-primary-candidate-linkage-candidate-v1.json", "review_candidate"], ["census-cd119-plan-change-authority-20260805", INPUTS.authorityFile, "data/source/elections/primary-results/geography/census-119-congressional-district-bef.html", "source"], ["tiger-cd118-34", INPUTS.nj118File, "data/source/tiger2022/tl_2022_34_cd118.zip", "source"], ["tiger-cd118-42", INPUTS.pa118File, "data/source/tiger2022/tl_2022_42_cd118.zip", "source"], ["tiger-cd119-34", INPUTS.nj119File, "data/source/tiger2025/tl_2025_34_cd119.zip", "source"], ["tiger-cd119-42", INPUTS.pa119File, "data/source/tiger2025/tl_2025_42_cd119.zip", "source"]] as const;
  if (required.some(([id, sha, path, kind]) => { const matches = lock.entries.filter((value) => value.id === id); return matches.length !== 1 || matches[0]!.retainedStatus !== "retained" || matches[0]!.sha256 !== sha || matches[0]!.retainedPath !== path || matches[0]!.kind !== kind; })) throw new Error("PRIMARY_GEOGRAPHY_SOURCE_LOCK_MISMATCH");
  const inventoryKeys = new Set(inventories.flatMap((values) => values.map((value) => `${value.cdSession}:${value.geoid}`)));
  const rows = linkage.links.map((value) => { const fips = value.stateCode === "NJ" ? "34" : "42", targetCd119Geoid = `${fips}${value.districtCode}`, historicalCongressSession = value.cycleYear === 2022 ? "118" as const : value.cycleYear === 2024 ? "119" as const : "120" as const, historicalGeoid = value.cycleYear === 2026 ? null : targetCd119Geoid, compatible = value.cycleYear !== 2026; if (!inventoryKeys.has(`119:${targetCd119Geoid}`) || (historicalGeoid && !inventoryKeys.has(`${historicalCongressSession}:${historicalGeoid}`))) throw new Error("PRIMARY_GEOGRAPHY_LINKAGE_KEY_OUTSIDE_TIGER_CLOSURE"); const unsigned = { linkageId: value.linkageId, contestSha256: value.contestSha256, seatCycleId: value.seatCycleId, stateCode: value.stateCode, districtCode: value.districtCode, cycleYear: value.cycleYear, targetCd119Geoid, historicalCongressSession, historicalGeoid, compatibilityDisposition: value.cycleYear === 2022 ? "official_no_plan_change_declaration_same_geoid_key_candidate" as const : value.cycleYear === 2024 ? "same_cd119_session_and_geoid_exact_key_candidate" as const : "unassessed_cd120_authority_collection_pending" as const, evidenceClass: value.cycleYear === 2022 ? "direct_official_plan_continuity_and_derived_key" as const : value.cycleYear === 2024 ? "derived_exact_session_and_key" as const : "authority_pending" as const, confidence: compatible ? "high" as const : "none" as const, compatibilityCandidate: compatible, compatibilityApproved: false as const, identityApproved: false as const, evaluatorUse: "excluded_pending_authorized_identity_and_historical_geography_review" as const, scoreEligible: false as const, rationaleCodes: value.cycleYear === 2022 ? ["official_census_cd119_redraw_list_excludes_nj_pa", "same_state_district_geoid_in_cd118_and_cd119_inventory"] : value.cycleYear === 2024 ? ["same_cd119_congressional_session", "same_state_district_geoid_in_cd119_inventory"] : ["cd120_authority_not_yet_retained", "do_not_assume_cd119_continuity_for_2026"] }; return { ...unsigned, rowSha256: digest("dsa-seats:nj-pa-primary-geography-row:v1\0", unsigned) }; }).sort((a, b) => bytewise(a.linkageId, b.linkageId));
  const unsigned = { schema: "nj-pa-primary-geography-compatibility-candidate-v1" as const, version: 1 as const, generatedAt: "2026-08-06T15:00:00.000Z" as const, sourceCutoff: "2026-08-05" as const, parentSourceCutoff: "2026-08-04" as const, parentSuperseded: false as const, reviewerOnly: true as const, publicationEligible: false as const, defaultUse: "exclude_from_evaluator_until_authorized_identity_and_historical_geography_review" as const, review: { status: "proposed" as const, reviewer: null, reviewedAt: null, resolution: null }, inputs: { sourceSelectionProposal: { sourceLockId: "house-democratic-primary-source-selection-proposal-20260804-v1" as const, fileSha256: INPUTS.proposalFile, packageSha256: INPUTS.proposalPackage, informedDecisionId: "approve-historical-district-cd119-compatibility-v1" as const, decisionUnresolved: true as const }, linkageCandidate: { sourceLockId: "current-incumbent-primary-candidate-linkage-candidate-v1" as const, fileSha256: INPUTS.linkageFile, packageSha256: INPUTS.linkagePackage, identityDecisionUnresolved: true as const }, censusPlanChangeAuthority: { sourceLockId: "census-cd119-plan-change-authority-20260805" as const, fileSha256: INPUTS.authorityFile, authorityClaim: "five_states_redrew_for_cd119_al_ga_la_ny_nc_nj_pa_absent" as const }, tigerLayers }, methodology: { targetSession: "119" as const, cycleSessionMapping: { "2022": "118" as const, "2024": "119" as const, "2026": "120" as const }, planContinuityRule: "official_census_redraw_scope_declaration_plus_same_state_district_key" as const, exactSameSessionRule: "same_cd119_session_state_and_district_geoid" as const, cd120Rule: "remain_unassessed_until_authoritative_cd120_plan_evidence_is_retained" as const, rawTigerGeometryEqualityAssessed: false as const, rawCoordinateDifferenceImpliesPlanChange: false as const, overlapThresholdUsed: false as const, automaticDecisionClosure: false as const, evaluatorNumericValues: 0 as const }, privacy: { candidatePersonalDataExcluded: true as const, rawGeometryExcluded: true as const, rawSourceTextExcluded: true as const }, summary: { seatCycleObservations: 41 as const, cd118ToCd119PlanContinuityCandidates: 16 as const, exactCd119SessionKeyCandidates: 16 as const, cd120AuthorityPending: 9 as const, compatibilityCandidates: 32 as const, automaticallyApprovedRows: 0 as const, scoreEligibleRows: 0 as const }, rows, rowSetSha256: digest("dsa-seats:nj-pa-primary-geography-row-set:v1\0", rows), decisionSupport: { informsDecisionId: "approve-historical-district-cd119-compatibility-v1" as const, analysisConclusion: "official_evidence_supports_nj_pa_cd118_to_cd119_plan_continuity_and_exact_cd119_keys_while_cd120_remains_unassessed" as const, lifecycle: "evidence_for_bound_existing_decision_not_an_independent_decision" as const } };
  return validateNjPaPrimaryGeographyCompatibilityCandidate({ ...unsigned, packageSha256: digest("dsa-seats:nj-pa-primary-geography-candidate:v1\0", unsigned) });
}

export function validateNjPaPrimaryGeographyCompatibilityCandidate(value: unknown): NjPaPrimaryGeographyCompatibilityCandidate {
  const parsed = njPaPrimaryGeographyCompatibilityCandidateSchema.parse(value), { packageSha256, ...unsigned } = parsed;
  assertNjPaPrimaryGeographyRowSemantics(parsed.rows);
  if (parsed.rowSetSha256 !== digest("dsa-seats:nj-pa-primary-geography-row-set:v1\0", parsed.rows)) throw new Error("PRIMARY_GEOGRAPHY_ROW_OR_SET_INVALID");
  const expectedLayers = [["tiger-cd118-34", INPUTS.nj118File, INPUTS.nj118Dbf, "34", "118", 12], ["tiger-cd118-42", INPUTS.pa118File, INPUTS.pa118Dbf, "42", "118", 17], ["tiger-cd119-34", INPUTS.nj119File, INPUTS.nj119Dbf, "34", "119", 12], ["tiger-cd119-42", INPUTS.pa119File, INPUTS.pa119Dbf, "42", "119", 17]];
  if (JSON.stringify(parsed.inputs.tigerLayers.map((value) => [value.sourceLockId, value.fileSha256, value.dbfMemberSha256, value.stateFips, value.cdSession, value.districtCount])) !== JSON.stringify(expectedLayers)) throw new Error("PRIMARY_GEOGRAPHY_LAYER_SEMANTICS_INVALID");
  if ((EXPECTED_PACKAGE && packageSha256 !== EXPECTED_PACKAGE) || packageSha256 !== digest("dsa-seats:nj-pa-primary-geography-candidate:v1\0", unsigned)) throw new Error("PRIMARY_GEOGRAPHY_PACKAGE_HASH_MISMATCH");
  const continuity = parsed.rows.filter((value) => value.compatibilityDisposition === "official_no_plan_change_declaration_same_geoid_key_candidate").length, exact = parsed.rows.filter((value) => value.compatibilityDisposition === "same_cd119_session_and_geoid_exact_key_candidate").length, pending = parsed.rows.filter((value) => value.compatibilityDisposition === "unassessed_cd120_authority_collection_pending").length;
  if (continuity !== 16 || exact !== 16 || pending !== 9 || parsed.summary.compatibilityCandidates !== continuity + exact) throw new Error("PRIMARY_GEOGRAPHY_SUMMARY_INVALID"); return parsed;
}

export function assertNjPaPrimaryGeographyRowSemantics(value: unknown): void {
  const rows = z.array(row).length(41).parse(value);
  const exactRationale = (actual: readonly string[], expected: readonly string[]): boolean => JSON.stringify(actual) === JSON.stringify(expected);
  if (rows.some((value, index) => { const { rowSha256, ...rowUnsigned } = value, fips = value.stateCode === "NJ" ? "34" : "42", district = Number(value.districtCode), keyValid = value.targetCd119Geoid === `${fips}${value.districtCode}` && district >= 1 && district <= (value.stateCode === "NJ" ? 12 : 17), common = rowSha256 === digest("dsa-seats:nj-pa-primary-geography-row:v1\0", rowUnsigned) && !(index > 0 && bytewise(rows[index - 1]!.linkageId, value.linkageId) >= 0) && !value.scoreEligible && !value.compatibilityApproved && !value.identityApproved && keyValid; if (!common) return true; if (value.cycleYear === 2022) return value.historicalCongressSession !== "118" || value.historicalGeoid !== value.targetCd119Geoid || value.compatibilityDisposition !== "official_no_plan_change_declaration_same_geoid_key_candidate" || value.evidenceClass !== "direct_official_plan_continuity_and_derived_key" || value.confidence !== "high" || !value.compatibilityCandidate || !exactRationale(value.rationaleCodes, ["official_census_cd119_redraw_list_excludes_nj_pa", "same_state_district_geoid_in_cd118_and_cd119_inventory"]); if (value.cycleYear === 2024) return value.historicalCongressSession !== "119" || value.historicalGeoid !== value.targetCd119Geoid || value.compatibilityDisposition !== "same_cd119_session_and_geoid_exact_key_candidate" || value.evidenceClass !== "derived_exact_session_and_key" || value.confidence !== "high" || !value.compatibilityCandidate || !exactRationale(value.rationaleCodes, ["same_cd119_congressional_session", "same_state_district_geoid_in_cd119_inventory"]); return value.stateCode !== "NJ" || value.historicalCongressSession !== "120" || value.historicalGeoid !== null || value.compatibilityDisposition !== "unassessed_cd120_authority_collection_pending" || value.evidenceClass !== "authority_pending" || value.confidence !== "none" || value.compatibilityCandidate || !exactRationale(value.rationaleCodes, ["cd120_authority_not_yet_retained", "do_not_assume_cd119_continuity_for_2026"]); })) throw new Error("PRIMARY_GEOGRAPHY_ROW_OR_SET_INVALID");
}
