/* eslint-disable @typescript-eslint/no-explicit-any -- adversarial persisted candidate mutations */
import { createHash } from "node:crypto";
import { execFileSync } from "node:child_process";
import { readFileSync } from "node:fs";
import { describe, expect, it } from "vitest";
import { buildNcPrimaryGeographyCandidate, validateNcPrimaryGeographyCandidate } from "./north-carolina-primary-geography-compatibility-candidate";
import { canonicalJson } from "../fec/aipac-proposed-packages";
const sha = (value: Buffer | string) => createHash("sha256").update(value).digest("hex");
const digest = (domain: string, value: unknown) => createHash("sha256").update(domain).update(canonicalJson(value)).digest("hex");
const json = (path: string) => { const bytes = readFileSync(path); return { value: JSON.parse(bytes.toString("utf8")), sha256: sha(bytes) }; };
const csv = (path: string, member: string) => execFileSync("unzip", ["-p", path, member], { encoding: "utf8", maxBuffer: 32 * 1024 * 1024 });
const build = (mutateLock?: (lock: any) => void, mutateInput?: (input: any) => void) => { const identity = json("data/metadata/north-carolina-current-incumbent-primary-linkage-candidate-v1.json"), authority = readFileSync("data/source/elections/primary-results/geography/north-carolina/ncga-redistricting.html"), p22 = "data/source/elections/primary-results/geography/north-carolina/2022/court-ordered-congressional-block-assignment.zip", p24 = "data/source/elections/primary-results/geography/north-carolina/2024/sl-2023-145-congressional-block-assignment.zip", p26 = "data/source/elections/primary-results/geography/north-carolina/2026/sl-2025-95-congressional-block-assignment.zip", b22 = readFileSync(p22), b24 = readFileSync(p24), b26 = readFileSync(p26), current = readFileSync("data/source/elections/primary-results/geography/north-carolina/current/37_NC_CD119.txt"), lock = structuredClone(json("data/source-lock.json").value); mutateLock?.(lock); const input: any = { identity: identity.value, identityFileSha256: identity.sha256, authorityHtml: authority.toString("utf8"), authorityFileSha256: sha(authority), block2022Csv: csv(p22, "Interim Congressional.csv"), block2022FileSha256: sha(b22), block2024Csv: csv(p24, "SL 2023-145.csv"), block2024FileSha256: sha(b24), block2026Csv: csv(p26, "SL 2025-95.csv"), block2026FileSha256: sha(b26), currentCsv: current.toString("utf8"), currentFileSha256: sha(current), sourceLock: lock }; mutateInput?.(input); return buildNcPrimaryGeographyCandidate(input); };
describe("North Carolina primary geography compatibility candidate", () => {
  it("rebuilds the exact reviewer-only artifact", () => { expect(build()).toEqual(validateNcPrimaryGeographyCandidate(json("data/metadata/north-carolina-primary-geography-compatibility-candidate-v1.json").value)); });
  it("separates exact membership from split crosswalk review", () => { const value = build(); expect(value.summary).toEqual({ targetObservations: 12, exactBlockMembershipCandidates: 7, crosswalkReviewRequired: 5, automaticallyApprovedRows: 0, scoreEligibleRows: 0 }); expect(value.rows.filter((row) => row.cycleYear === 2024 && row.compatibilityCandidate)).toHaveLength(4); expect(value.rows.filter((row) => row.cycleYear === 2026 && row.compatibilityCandidate).map((row) => row.districtCode)).toEqual(["02", "04", "12"]); expect(value.rows.filter((row) => row.cycleYear === 2022 && !row.compatibilityCandidate)).toHaveLength(4); });
  it("serializes exact block-count evidence without treating it as population", () => { const value = build(), nc01_2026 = value.rows.find((row) => row.cycleYear === 2026 && row.districtCode === "01")!, nc12_2022 = value.rows.find((row) => row.cycleYear === 2022 && row.districtCode === "12")!; expect(nc01_2026).toMatchObject({ sourceBlockCount: 26755, targetBlockCount: 23945, sameDistrictBlockCount: 15937, sourceRetentionPpm: 595664, targetCoveragePpm: 665567, compatibilityDisposition: "crosswalk_review_required" }); expect(nc12_2022.sourceToTargetSplits).toEqual([{ targetDistrictCode: "12", blockCount: 3729, sourceSharePpm: 397379 }, { targetDistrictCode: "14", blockCount: 2172, sourceSharePpm: 231458 }, { targetDistrictCode: "06", blockCount: 1910, sourceSharePpm: 203538 }, { targetDistrictCode: "08", blockCount: 1573, sourceSharePpm: 167626 }]); });
  it("keeps every row unapproved and score-ineligible", () => { expect(build().rows.every((row) => !row.compatibilityApproved && !row.identityApproved && !row.scoreEligible)).toBe(true); });
  it("rejects exact lineage loss and missing raw closure", () => { expect(() => build((lock) => { lock.entries.find((entry: any) => entry.id === "census-cd119-north-carolina-block-equivalency-extract-20260805").parentIds = []; })).toThrow("SOURCE_LOCK_MISMATCH"); expect(() => build((lock) => { lock.entries = lock.entries.filter((entry: any) => entry.id !== "census-cd119-block-equivalency-bundle-20260805"); })).toThrow("SOURCE_LOCK_MISMATCH"); });
  it("rejects unknown fields and fully rehashed semantic substitution", () => { const unknown: any = build(); unknown.rows[0].unexpected = true; expect(() => validateNcPrimaryGeographyCandidate(unknown)).toThrow("UNKNOWN_OR_MISSING_FIELD"); const drift: any = build(), row = drift.rows.find((value: any) => !value.compatibilityCandidate); row.sourceToTargetSplits[0].blockCount += 1; row.rowSha256 = digest("dsa-seats:nc-primary-geography-row:v1\0", Object.fromEntries(Object.entries(row).filter(([key]) => key !== "rowSha256"))); drift.rowSetSha256 = digest("dsa-seats:nc-primary-geography-row-set:v1\0", drift.rows); drift.packageSha256 = digest("dsa-seats:nc-primary-geography-candidate:v1\0", Object.fromEntries(Object.entries(drift).filter(([key]) => key !== "packageSha256"))); expect(() => validateNcPrimaryGeographyCandidate(drift)).toThrow("ROW_INVALID"); });
  it("rejects reordered, duplicated, malformed, or substituted input bytes", () => { expect(() => build(undefined, (input) => { const lines = input.block2022Csv.split("\n"); [lines[1], lines[2]] = [lines[2], lines[1]]; input.block2022Csv = lines.join("\n"); })).toThrow("INPUT_HASH_MISMATCH"); expect(() => build(undefined, (input) => { const lines = input.block2022Csv.split("\n"); lines.splice(2, 0, lines[1]); input.block2022Csv = lines.join("\n"); })).toThrow("INPUT_HASH_MISMATCH"); expect(() => build(undefined, (input) => { input.block2022Csv = input.block2022Csv.replace('"371139706002016","11"', "malformed"); })).toThrow("INPUT_HASH_MISMATCH"); expect(() => build(undefined, (input) => { input.currentCsv += "370000000000000,01\n"; })).toThrow("INPUT_HASH_MISMATCH"); });
  it("declares and bounds independently rounded split PPM", () => { const value: any = build(); expect(value.methodology).toMatchObject({ ppmRounding: "nearest_integer_per_value", splitShareAggregateTolerancePpm: 1 }); expect(value.rows.filter((row: any) => !row.compatibilityCandidate).every((row: any) => Math.abs(row.sourceToTargetSplits.reduce((sum: number, split: any) => sum + split.sourceSharePpm, 0) - 1_000_000) <= 1)).toBe(true); });
});
