/* eslint-disable @typescript-eslint/no-explicit-any -- adversarial persisted candidate mutations */
import { createHash } from "node:crypto";
import { readFileSync } from "node:fs";
import { describe, expect, it } from "vitest";
import { buildNcPrimaryIdentityCandidate, validateNcPrimaryIdentityCandidate } from "./north-carolina-current-incumbent-primary-linkage-candidate";
import { canonicalJson } from "../fec/aipac-proposed-packages";
const sha = (value: Buffer): string => createHash("sha256").update(value).digest("hex");
const json = (path: string) => { const bytes = readFileSync(path); return { bytes, value: JSON.parse(bytes.toString("utf8")), sha256: sha(bytes) }; };
const hash = (domain: string, value: unknown): string => createHash("sha256").update(domain, "ascii").update(canonicalJson(value)).digest("hex");
const build = (lockOverride?: unknown, congressOverride?: string) => { const roster = json("data/metadata/dsa-target-incumbent-roster-20260804-v1.json"), proposal = json("data/metadata/house-democratic-primary-source-selection-proposal-20260804-v1.json"), house = readFileSync("data/source/identity/house-member-data.xml"), congress = json("data/source/identity/congress-legislators-current-20260804.json"), receipt = json("data/metadata/north-carolina-house-democratic-primary-results-2022-2026-v1.json"), precedence = json("data/metadata/north-carolina-primary-source-precedence-decision-v1.json"), lock = json("data/source-lock.json"); return buildNcPrimaryIdentityCandidate({ roster: roster.value, rosterFileSha256: roster.sha256, proposal: proposal.value, proposalFileSha256: proposal.sha256, houseXml: house.toString("utf8"), houseFileSha256: sha(house), congressJson: congressOverride ?? congress.bytes.toString("utf8"), congressFileSha256: congress.sha256, receipt: receipt.value, receiptFileSha256: receipt.sha256, precedence: precedence.value, precedenceFileSha256: precedence.sha256, sourceLock: lockOverride ?? lock.value }); };
describe("North Carolina current-incumbent primary linkage candidate", () => {
  it("rebuilds the proposed artifact exactly", () => { expect(build()).toEqual(validateNcPrimaryIdentityCandidate(json("data/metadata/north-carolina-current-incumbent-primary-linkage-candidate-v1.json").value)); });
  it("closes the 12-row partition without approval", () => { const value = build(); expect(value.summary).toEqual({ targetSeats: 4, districtCycleObservations: 12, reportedContestObservations: 6, unreportedDistrictCycleObservations: 6, exactNameObservations: 4, derivedNameRelationships: 2, proposedIdentityLinks: 6, directIdentifierBridges: 0, automaticallyApprovedRows: 0, scoreEligibleRows: 0 }); expect(value.observations.every((row) => !row.identityApproved && !row.scoreEligible && row.historicalGeographyStatus === "separate_redraw_review_required")).toBe(true); });
  it("preserves both derived relationships explicitly", () => { const derived = build().observations.filter((row) => row.evidenceClass === "derived_name_relationship"); expect(derived.map((row) => [row.sourceObservation.kind === "reported_contest" ? row.sourceObservation.sourceCandidateName : null, row.rosterIdentity.officialHouseName, row.matchMethod])).toEqual([["Don Davis", "Donald G. Davis", "derived_common_short_form_same_district"], ["Alma Shealey Adams", "Alma S. Adams", "derived_middle_name_expansion_same_district"]]); });
  it("preserves six absent contests as unresolved blocks", () => { const unresolved = build().observations.filter((row) => row.sourceObservation.kind === "unreported_district_cycle_block"); expect(unresolved.map((row) => row.sourceObservation.kind === "unreported_district_cycle_block" ? row.sourceObservation.districtCycleId : null)).toEqual(["nc:2022:us-house:02:democratic", "nc:2024:us-house:01:democratic", "nc:2024:us-house:04:democratic", "nc:2024:us-house:12:democratic", "nc:2026:us-house:01:democratic", "nc:2026:us-house:02:democratic"]); expect(unresolved.every((row) => row.confidence === "none" && row.relationshipDisposition === "not_linked_no_reported_contest")).toBe(true); });
  it("rejects lifecycle, source fact, and source-lock drift", () => { const lifecycle: any = build(); lifecycle.review.reviewer = "fabricated"; expect(() => validateNcPrimaryIdentityCandidate(lifecycle)).toThrow(); const fact: any = build(); const reported = fact.observations.find((row: any) => row.sourceObservation.kind === "reported_contest"); reported.sourceObservation.votes++; expect(() => validateNcPrimaryIdentityCandidate(fact)).toThrow(); const wrong: any = structuredClone(json("data/source-lock.json").value); wrong.entries.find((entry: any) => entry.id === "north-carolina-primary-source-precedence-decision-v1").kind = "review_candidate"; expect(() => build(wrong)).toThrow("SOURCE_LOCK_MISMATCH"); });
  it("binds alias evidence to the exact congress-legislators bytes", () => { const congress = json("data/source/identity/congress-legislators-current-20260804.json").value; congress[0].name.official_full = "substituted"; expect(() => build(undefined, `${JSON.stringify(congress, null, 2)}\n`)).toThrow("INPUT_HASH_MISMATCH"); });
  it("rejects fully rehashed semantic substitutions and unknown fields", () => { const rehash = (candidate: any) => { for (const row of candidate.observations) { const rowUnsigned = structuredClone(row); delete rowUnsigned.rowSha256; row.rowSha256 = hash("dsa-seats:nc-primary-identity-row:v1\0", rowUnsigned); } candidate.observationSetSha256 = hash("dsa-seats:nc-primary-identity-row-set:v1\0", candidate.observations); const packageUnsigned = structuredClone(candidate); delete packageUnsigned.packageSha256; candidate.packageSha256 = hash("dsa-seats:nc-primary-identity-candidate:v1\0", packageUnsigned); }; const value: any = build(), row = value.observations.find((candidate: any) => candidate.observationId === "nc:identity:2022:01"); row.sourceObservation.sourceCandidateName = "Invented Name"; rehash(value); expect(() => validateNcPrimaryIdentityCandidate(value)).toThrow(); for (const mutate of [(candidate: any) => { candidate.extra = true; }, (candidate: any) => { candidate.observations[0].extra = true; }, (candidate: any) => { candidate.observations.find((entry: any) => entry.sourceObservation.kind === "reported_contest").sourceObservation.extra = true; }]) { const candidate: any = build(); mutate(candidate); rehash(candidate); expect(() => validateNcPrimaryIdentityCandidate(candidate)).toThrow(/FIELDS_INVALID/); } });
});
