import { createHash } from "node:crypto";
import { canonicalJson } from "../fec/aipac-proposed-packages";
import { validateNcPrimaryIdentityCandidate, type NcPrimaryIdentityCandidate } from "./north-carolina-current-incumbent-primary-linkage-candidate";

export const NC_PRIMARY_GEOGRAPHY_V1 = "north-carolina-primary-geography-compatibility-candidate-v1" as const;
export const NC_PRIMARY_GEOGRAPHY_ROW_SET_SHA256 = "254bb244bfb6d77851aa415e665569047cb1473e1cd689fd6acf030ef6aa0572";
export const NC_PRIMARY_GEOGRAPHY_PACKAGE_SHA256 = "838fd6acdb4a780993d9540bd68228cf76ca0b77f9ecab57d8403d85c0ba42df";
const INPUTS = {
  identityFile: "9a7903755fdceaffb29af2a40fee014ddf7abb63f455d2381a0376046399490c",
  identityPackage: "12fbecfa848ba85aa39d426d94a8be4ab3f77fc1356f6c0a288514037f9c4d76",
  identitySet: "b587a7f2b181d11d24be10404ecd7f79879522b434a521ebf08065c6b88d4ba0",
  authority: "8f11ae03c95c6e19e75cef133390c5e1176dc71d7253f72345fbd480504eb001",
  block2022: "95b0e6c0bca9bd18932195649fa23406c28b35f975aab9815c64c3d06cf74b4a",
  block2022Csv: "5f8c4f6104f8c37da3b171a4dd5ffd2f1d5f0a5a55bf33c1f240288733b10552",
  block2024: "9ff24ce1565750e8677c0c4d5d27f5b6c0f28ccc78b1ad93c53c4565c4d35dfe",
  block2024Csv: "6103ef6fff696d7d52bbfad06ea6c1e6cc0c51b35966c5c351022e9ab6ca7e7f",
  block2026: "f8fc2a273ed86482bd3aec400868f2a47ce91eaab42dd74d3509fc022daf4721",
  block2026Csv: "935095135dbc1e5d6803ea9ceb63dd6db1fc559569d71717fd13c03a65a0aae9",
  current: "e541c8300ea3a3db4cbe26a91ef95749ff8986076f452dab9af7e92769fbb784",
} as const;
type Cycle = 2022 | 2024 | 2026;
type Split = Readonly<{ targetDistrictCode: string; blockCount: number; sourceSharePpm: number }>;
type Row = Readonly<{ observationId: string; identityObservationSha256: string; seatCycleId: string; districtCode: string; cycleYear: Cycle; sourcePlan: "court_ordered_2022" | "sl_2023_145" | "sl_2025_95"; targetPlan: "cd119_sl_2023_145"; sourceBlockCount: number; targetBlockCount: number; sameDistrictBlockCount: number; sourceRetentionPpm: number; targetCoveragePpm: number; sourceToTargetSplits: readonly Split[]; compatibilityDisposition: "exact_block_membership_candidate" | "crosswalk_review_required"; compatibilityCandidate: boolean; compatibilityApproved: false; identityApproved: false; scoreEligible: false; evaluatorUse: "excluded_pending_authorized_identity_geography_and_review"; rationaleCodes: readonly string[]; rowSha256: string }>;
export type NcPrimaryGeographyCandidate = Readonly<{ schema: typeof NC_PRIMARY_GEOGRAPHY_V1; version: 1; generatedAt: "2026-08-06T02:00:00.000Z"; sourceCutoff: "2026-08-05"; reviewerOnly: true; publicationEligible: false; defaultUse: "exclude_from_evaluator_until_authorized_identity_geography_and_review"; review: Readonly<{ status: "proposed"; reviewer: null; reviewedAt: null; resolution: null }>; inputs: unknown; methodology: unknown; summary: Readonly<{ targetObservations: 12; exactBlockMembershipCandidates: 7; crosswalkReviewRequired: 5; automaticallyApprovedRows: 0; scoreEligibleRows: 0 }>; rows: readonly Row[]; rowSetSha256: string; decisionSupport: unknown; packageSha256: string }>;
type BuildInput = Readonly<{ identity: NcPrimaryIdentityCandidate; identityFileSha256: string; authorityHtml: string; authorityFileSha256: string; block2022Csv: string; block2022FileSha256: string; block2024Csv: string; block2024FileSha256: string; block2026Csv: string; block2026FileSha256: string; currentCsv: string; currentFileSha256: string; sourceLock: unknown }>;
const sha = (value: string | Buffer) => createHash("sha256").update(value).digest("hex");
const digest = (domain: string, value: unknown) => createHash("sha256").update(domain).update(canonicalJson(value)).digest("hex");
const sort = (a: string, b: string) => Buffer.compare(Buffer.from(a), Buffer.from(b));
const fail = (code: string): never => { throw new Error(`North Carolina primary geography rejected: ${code}`); };
const exactKeys = (value: unknown, keys: readonly string[]) => { if (!value || typeof value !== "object" || Array.isArray(value) || JSON.stringify(Object.keys(value).sort()) !== JSON.stringify([...keys].sort())) fail("UNKNOWN_OR_MISSING_FIELD"); };

function parseAssignment(text: string, format: "ncga" | "census") {
  const lines = text.replace(/^\uFEFF/, "").split(/\r?\n/); if (lines.at(-1) === "") lines.pop();
  const header = lines.shift(); if (header !== (format === "ncga" ? '"Block","District"' : "GEOID,CDFP")) fail("BLOCK_HEADER_INVALID");
  const rows = new Map<string, string>();
  for (const line of lines) { const match = (format === "ncga" ? /^"(\d{15})","(\d{1,2})"$/ : /^(\d{15}),(\d{2})$/).exec(line), block = match?.[1], district = match?.[2]; if (!block || !district || rows.has(block)) fail("BLOCK_ROW_INVALID"); rows.set(block as string, String(Number(district as string)).padStart(2, "0")); }
  const districts = new Set(rows.values()); if (rows.size !== 236_638 || districts.size !== 14 || Array.from({ length: 14 }, (_, i) => String(i + 1).padStart(2, "0")).some((district) => !districts.has(district))) fail("BLOCK_INVENTORY_INVALID");
  return rows;
}

export function buildNcPrimaryGeographyCandidate(input: BuildInput): NcPrimaryGeographyCandidate {
  const actual = [input.identityFileSha256, input.authorityFileSha256, input.block2022FileSha256, input.block2024FileSha256, input.block2026FileSha256, input.currentFileSha256, sha(input.authorityHtml), sha(input.block2022Csv), sha(input.block2024Csv), sha(input.block2026Csv), sha(input.currentCsv)];
  const expected = [INPUTS.identityFile, INPUTS.authority, INPUTS.block2022, INPUTS.block2024, INPUTS.block2026, INPUTS.current, INPUTS.authority, INPUTS.block2022Csv, INPUTS.block2024Csv, INPUTS.block2026Csv, INPUTS.current];
  if (actual.some((value, index) => value !== expected[index])) fail("INPUT_HASH_MISMATCH");
  const identity = validateNcPrimaryIdentityCandidate(input.identity); if (identity.packageSha256 !== INPUTS.identityPackage || identity.observationSetSha256 !== INPUTS.identitySet || identity.review.resolution !== null) fail("IDENTITY_PARENT_INVALID");
  for (const phrase of ["C2022C_Detail", "used for the 2022 election", "C2023E_Detail", "used for the 2024 election", "C2025E_Detail", "to be used for the 2026 elections"]) if (!input.authorityHtml.includes(phrase)) fail("PLAN_AUTHORITY_INVALID");
  const maps: Record<Cycle, Map<string, string>> = { 2022: parseAssignment(input.block2022Csv, "ncga"), 2024: parseAssignment(input.block2024Csv, "ncga"), 2026: parseAssignment(input.block2026Csv, "ncga") }, current = parseAssignment(input.currentCsv, "census");
  if ([...maps[2022].keys()].some((block) => !maps[2024].has(block) || !maps[2026].has(block) || !current.has(block))) fail("BLOCK_UNIVERSE_MISMATCH");
  if ([...current].some(([block, district]) => maps[2024].get(block) !== district)) fail("CD119_ASSIGNMENT_MISMATCH");
  const lock = input.sourceLock as { entries?: Array<Record<string, unknown>> }, required = [
    ["north-carolina-current-incumbent-primary-linkage-candidate-v1", INPUTS.identityFile, "data/metadata/north-carolina-current-incumbent-primary-linkage-candidate-v1.json", "review_candidate", ["dsa-target-incumbent-roster-20260804-v1", "house-democratic-primary-source-selection-proposal-20260804-v1", "house-xml", "congress-legislators-current-20260804", "north-carolina-house-democratic-primary-results-2022-2026-v1", "north-carolina-primary-source-precedence-decision-v1"]],
    ["ncga-congressional-redistricting-authority-20260805", INPUTS.authority, "data/source/elections/primary-results/geography/north-carolina/ncga-redistricting.html", "source", []],
    ["nc-2022-court-congressional-plan-block-assignment", INPUTS.block2022, "data/source/elections/primary-results/geography/north-carolina/2022/court-ordered-congressional-block-assignment.zip", "source", []],
    ["nc-2023-enacted-congressional-plan-block-assignment", INPUTS.block2024, "data/source/elections/primary-results/geography/north-carolina/2024/sl-2023-145-congressional-block-assignment.zip", "source", []],
    ["nc-2025-enacted-congressional-plan-block-assignment", INPUTS.block2026, "data/source/elections/primary-results/geography/north-carolina/2026/sl-2025-95-congressional-block-assignment.zip", "source", []],
    ["census-cd119-block-equivalency-bundle-20260805", "1433feb5178dc7b4188ee30f5f7f715851f4400740b8fe1ce606a876c6294bd6", "data/source/elections/primary-results/geography/north-carolina/current/census-cd119-block-equivalency-bundle.zip", "source", []],
    ["census-cd119-north-carolina-block-equivalency-extract-20260805", INPUTS.current, "data/source/elections/primary-results/geography/north-carolina/current/37_NC_CD119.txt", "derived_extract", ["census-cd119-block-equivalency-bundle-20260805"]],
  ] as const;
  if (!Array.isArray(lock.entries) || required.some(([id, file, path, kind, parentIds]) => { const matches = lock.entries!.filter((entry) => entry.id === id); return matches.length !== 1 || matches[0]!.retainedStatus !== "retained" || matches[0]!.sha256 !== file || matches[0]!.retainedPath !== path || matches[0]!.kind !== kind || JSON.stringify(matches[0]!.parentIds) !== JSON.stringify(parentIds); })) fail("SOURCE_LOCK_MISMATCH");
  const plans = { 2022: "court_ordered_2022", 2024: "sl_2023_145", 2026: "sl_2025_95" } as const;
  const rows = identity.observations.map((observation) => {
    const cycle = observation.cycleYear as Cycle, source = maps[cycle], district = observation.districtCode, sourceBlocks = [...source].filter(([, value]) => value === district).map(([block]) => block), targetBlocks = [...current].filter(([, value]) => value === district).map(([block]) => block), counts = new Map<string, number>();
    for (const block of sourceBlocks) { const target = current.get(block); if (target === undefined) fail("TARGET_BLOCK_MISSING"); const targetDistrict = target as string; counts.set(targetDistrict, (counts.get(targetDistrict) ?? 0) + 1); }
    const same = counts.get(district) ?? 0, exact = sourceBlocks.length === targetBlocks.length && same === sourceBlocks.length && counts.size === 1, ppm = (part: number, whole: number) => Math.round(part * 1_000_000 / whole);
    const splits = [...counts].map(([targetDistrictCode, blockCount]) => ({ targetDistrictCode, blockCount, sourceSharePpm: ppm(blockCount, sourceBlocks.length) })).sort((a, b) => b.blockCount - a.blockCount || sort(a.targetDistrictCode, b.targetDistrictCode));
    const unsigned = { observationId: observation.observationId, identityObservationSha256: observation.rowSha256, seatCycleId: observation.seatCycleId, districtCode: district, cycleYear: cycle, sourcePlan: plans[cycle], targetPlan: "cd119_sl_2023_145" as const, sourceBlockCount: sourceBlocks.length, targetBlockCount: targetBlocks.length, sameDistrictBlockCount: same, sourceRetentionPpm: ppm(same, sourceBlocks.length), targetCoveragePpm: ppm(same, targetBlocks.length), sourceToTargetSplits: splits, compatibilityDisposition: exact ? "exact_block_membership_candidate" as const : "crosswalk_review_required" as const, compatibilityCandidate: exact, compatibilityApproved: false as const, identityApproved: false as const, scoreEligible: false as const, evaluatorUse: "excluded_pending_authorized_identity_geography_and_review" as const, rationaleCodes: exact ? ["identical_2020_tabulation_block_membership", "still_requires_identity_and_geography_review"] : ["source_district_splits_across_current_cd119_districts", "block_counts_are_not_population_or_voter_weights", "no_automatic_crosswalk_threshold"] };
    return { ...unsigned, rowSha256: digest("dsa-seats:nc-primary-geography-row:v1\0", unsigned) };
  }).sort((a, b) => sort(a.observationId, b.observationId));
  if (rows.length !== 12 || rows.filter((row) => row.compatibilityCandidate).length !== 7 || rows.filter((row) => !row.compatibilityCandidate).length !== 5) fail("EXPECTED_CLOSURE_INVALID");
  const unsigned = { schema: NC_PRIMARY_GEOGRAPHY_V1, version: 1 as const, generatedAt: "2026-08-06T02:00:00.000Z" as const, sourceCutoff: "2026-08-05" as const, reviewerOnly: true as const, publicationEligible: false as const, defaultUse: "exclude_from_evaluator_until_authorized_identity_geography_and_review" as const, review: { status: "proposed" as const, reviewer: null, reviewedAt: null, resolution: null }, inputs: { identityCandidate: { sourceLockId: required[0][0], fileSha256: INPUTS.identityFile, packageSha256: INPUTS.identityPackage, observationSetSha256: INPUTS.identitySet }, planAuthority: { sourceLockId: required[1][0], fileSha256: INPUTS.authority }, blockAssignments: required.slice(2).map(([sourceLockId, fileSha256]) => ({ sourceLockId, fileSha256 })) }, methodology: { joinKey: "2020_census_tabulation_block_geoid", blockUniverse: 236_638, targetPlan: "cd119_sl_2023_145", blockCountsArePopulationWeighted: false, overlapThresholdUsed: false, ppmRounding: "nearest_integer_per_value", splitShareAggregateTolerancePpm: 1, exactMembershipRule: "source_and_target_district_block_sets_are_identical", splitDispositionRule: "crosswalk_review_required", automaticDecisionClosure: false, evaluatorNumericValues: 0 }, summary: { targetObservations: 12 as const, exactBlockMembershipCandidates: 7 as const, crosswalkReviewRequired: 5 as const, automaticallyApprovedRows: 0 as const, scoreEligibleRows: 0 as const }, rows, rowSetSha256: digest("dsa-seats:nc-primary-geography-row-set:v1\0", rows), decisionSupport: { informsDecisionId: "approve-historical-district-cd119-compatibility-v1", analysisConclusion: "seven_exact_block_membership_candidates_and_five_split_crosswalk_reviews", lifecycle: "evidence_for_bound_existing_decision_not_an_independent_decision" } };
  return { ...unsigned, packageSha256: digest("dsa-seats:nc-primary-geography-candidate:v1\0", unsigned) };
}

export function validateNcPrimaryGeographyCandidate(value: NcPrimaryGeographyCandidate): NcPrimaryGeographyCandidate {
  exactKeys(value, ["schema", "version", "generatedAt", "sourceCutoff", "reviewerOnly", "publicationEligible", "defaultUse", "review", "inputs", "methodology", "summary", "rows", "rowSetSha256", "decisionSupport", "packageSha256"]);
  exactKeys(value.review, ["status", "reviewer", "reviewedAt", "resolution"]);
  if (value.schema !== NC_PRIMARY_GEOGRAPHY_V1 || value.version !== 1 || !value.reviewerOnly || value.publicationEligible || value.review.status !== "proposed" || value.review.reviewer !== null || value.review.reviewedAt !== null || value.review.resolution !== null || value.rows.length !== 12) fail("LIFECYCLE_INVALID");
  const inputs = value.inputs as { identityCandidate: unknown; planAuthority: unknown; blockAssignments: unknown[] }, methodology = value.methodology as Record<string, unknown>, decisionSupport = value.decisionSupport as Record<string, unknown>;
  exactKeys(inputs, ["identityCandidate", "planAuthority", "blockAssignments"]); exactKeys(inputs.identityCandidate, ["sourceLockId", "fileSha256", "packageSha256", "observationSetSha256"]); exactKeys(inputs.planAuthority, ["sourceLockId", "fileSha256"]); if (!Array.isArray(inputs.blockAssignments) || inputs.blockAssignments.length !== 5) fail("INPUTS_INVALID"); for (const input of inputs.blockAssignments) exactKeys(input, ["sourceLockId", "fileSha256"]);
  exactKeys(methodology, ["joinKey", "blockUniverse", "targetPlan", "blockCountsArePopulationWeighted", "overlapThresholdUsed", "ppmRounding", "splitShareAggregateTolerancePpm", "exactMembershipRule", "splitDispositionRule", "automaticDecisionClosure", "evaluatorNumericValues"]); if (methodology.joinKey !== "2020_census_tabulation_block_geoid" || methodology.blockUniverse !== 236_638 || methodology.targetPlan !== "cd119_sl_2023_145" || methodology.blockCountsArePopulationWeighted !== false || methodology.overlapThresholdUsed !== false || methodology.ppmRounding !== "nearest_integer_per_value" || methodology.splitShareAggregateTolerancePpm !== 1 || methodology.automaticDecisionClosure !== false || methodology.evaluatorNumericValues !== 0) fail("METHODOLOGY_INVALID");
  exactKeys(value.summary, ["targetObservations", "exactBlockMembershipCandidates", "crosswalkReviewRequired", "automaticallyApprovedRows", "scoreEligibleRows"]); if (JSON.stringify(value.summary) !== JSON.stringify({ targetObservations: 12, exactBlockMembershipCandidates: 7, crosswalkReviewRequired: 5, automaticallyApprovedRows: 0, scoreEligibleRows: 0 })) fail("SUMMARY_INVALID");
  exactKeys(decisionSupport, ["informsDecisionId", "analysisConclusion", "lifecycle"]);
  const rowKeys = ["observationId", "identityObservationSha256", "seatCycleId", "districtCode", "cycleYear", "sourcePlan", "targetPlan", "sourceBlockCount", "targetBlockCount", "sameDistrictBlockCount", "sourceRetentionPpm", "targetCoveragePpm", "sourceToTargetSplits", "compatibilityDisposition", "compatibilityCandidate", "compatibilityApproved", "identityApproved", "scoreEligible", "evaluatorUse", "rationaleCodes", "rowSha256"], plans = { 2022: "court_ordered_2022", 2024: "sl_2023_145", 2026: "sl_2025_95" } as const;
  if (value.rows.some((row, index) => { exactKeys(row, rowKeys); for (const split of row.sourceToTargetSplits) exactKeys(split, ["targetDistrictCode", "blockCount", "sourceSharePpm"]); const unsigned = Object.fromEntries(Object.entries(row).filter(([key]) => key !== "rowSha256")), observationMatch = /^nc:identity:(2022|2024|2026):(\d{2})$/.exec(row.observationId), exact = row.compatibilityDisposition === "exact_block_membership_candidate", splitCount = row.sourceToTargetSplits.reduce((sum, split) => sum + split.blockCount, 0), splitPpm = row.sourceToTargetSplits.reduce((sum, split) => sum + split.sourceSharePpm, 0), sameSplit = row.sourceToTargetSplits.find((split) => split.targetDistrictCode === row.districtCode); return !observationMatch || Number(observationMatch[1]) !== row.cycleYear || observationMatch[2] !== row.districtCode || row.seatCycleId !== `seat_house_nc_${row.districtCode}_current` || !/^[a-f0-9]{64}$/.test(row.identityObservationSha256) || row.sourcePlan !== plans[row.cycleYear] || row.targetPlan !== "cd119_sl_2023_145" || row.sourceBlockCount < 1 || row.targetBlockCount < 1 || row.sameDistrictBlockCount < 0 || row.sameDistrictBlockCount > row.sourceBlockCount || row.sameDistrictBlockCount > row.targetBlockCount || splitCount !== row.sourceBlockCount || !sameSplit || sameSplit.blockCount !== row.sameDistrictBlockCount || row.sourceRetentionPpm !== Math.round(row.sameDistrictBlockCount * 1_000_000 / row.sourceBlockCount) || row.targetCoveragePpm !== Math.round(row.sameDistrictBlockCount * 1_000_000 / row.targetBlockCount) || row.sourceToTargetSplits.some((split) => split.sourceSharePpm !== Math.round(split.blockCount * 1_000_000 / row.sourceBlockCount)) || Math.abs(splitPpm - 1_000_000) > 1 || row.compatibilityCandidate !== exact || (exact ? row.sourceToTargetSplits.length !== 1 || row.sameDistrictBlockCount !== row.sourceBlockCount || row.sourceBlockCount !== row.targetBlockCount || row.sourceRetentionPpm !== 1_000_000 || row.targetCoveragePpm !== 1_000_000 || JSON.stringify(row.rationaleCodes) !== JSON.stringify(["identical_2020_tabulation_block_membership", "still_requires_identity_and_geography_review"]) : row.sourceToTargetSplits.length < 2 || JSON.stringify(row.rationaleCodes) !== JSON.stringify(["source_district_splits_across_current_cd119_districts", "block_counts_are_not_population_or_voter_weights", "no_automatic_crosswalk_threshold"])) || row.compatibilityApproved || row.identityApproved || row.scoreEligible || row.evaluatorUse !== "excluded_pending_authorized_identity_geography_and_review" || row.rowSha256 !== digest("dsa-seats:nc-primary-geography-row:v1\0", unsigned) || (index > 0 && sort(value.rows[index - 1]!.observationId, row.observationId) >= 0); })) fail("ROW_INVALID");
  if (new Set(value.rows.map((row) => row.observationId)).size !== 12 || value.rows.filter((row) => row.compatibilityCandidate).length !== 7 || value.rows.filter((row) => !row.compatibilityCandidate).length !== 5) fail("ROW_CLOSURE_INVALID");
  const { packageSha256, ...unsigned } = value, rowSet = digest("dsa-seats:nc-primary-geography-row-set:v1\0", value.rows); if (value.rowSetSha256 !== rowSet || rowSet !== NC_PRIMARY_GEOGRAPHY_ROW_SET_SHA256 || packageSha256 !== digest("dsa-seats:nc-primary-geography-candidate:v1\0", unsigned) || packageSha256 !== NC_PRIMARY_GEOGRAPHY_PACKAGE_SHA256) fail("PACKAGE_INVALID"); return value;
}
