/* eslint-disable @typescript-eslint/no-explicit-any -- adversarial persisted package mutations */
import { createHash } from "node:crypto";
import { readFileSync } from "node:fs";
import { describe, expect, it } from "vitest";
import { canonicalJson } from "../fec/aipac-proposed-packages";
import { buildNcPrimaryJointPackage, validateNcPrimaryJointPackage } from "./north-carolina-primary-identity-geography-review-package";
const sha = (value: Buffer) => createHash("sha256").update(value).digest("hex"), digest = (domain: string, value: unknown) => createHash("sha256").update(domain).update(canonicalJson(value)).digest("hex"), load = (path: string) => { const bytes = readFileSync(path); return { value: JSON.parse(bytes.toString("utf8")), sha256: sha(bytes) }; };
const build = (mutateLock?: (lock: any) => void) => { const proposal = load("data/metadata/house-democratic-primary-source-selection-proposal-20260804-v1.json"), precedence = load("data/metadata/north-carolina-primary-source-precedence-decision-v1.json"), identity = load("data/metadata/north-carolina-current-incumbent-primary-linkage-candidate-v1.json"), geography = load("data/metadata/north-carolina-primary-geography-compatibility-candidate-v1.json"), lock = structuredClone(load("data/source-lock.json").value); mutateLock?.(lock); return buildNcPrimaryJointPackage({ proposal: proposal.value, proposalFileSha256: proposal.sha256, precedence: precedence.value, precedenceFileSha256: precedence.sha256, identity: identity.value, identityFileSha256: identity.sha256, geography: geography.value, geographyFileSha256: geography.sha256, sourceLock: lock }); };
describe("North Carolina primary identity/geography joint review", () => {
  it("rebuilds the exact reviewer package", () => { expect(build()).toEqual(validateNcPrimaryJointPackage(load("data/metadata/north-carolina-primary-identity-geography-review-package-v1.json").value)); });
  it("closes the exact 3/3/4/2 state matrix", () => { expect(build().summary).toEqual({ reviewRecords: 12, identityAndExactGeographyCandidates: 3, identityCandidateSplitGeography: 3, exactGeographyIdentityUnresolved: 4, identityUnresolvedSplitGeography: 2, identityCandidates: 6, exactGeographyCandidates: 7, jointApprovedRecords: 0, scoreEligibleRecords: 0 }); });
  it("creates four concrete decisions with safe defaults", () => { const value = build(); expect(value.decisions.map((decision) => decision.evidenceRecordIds.length)).toEqual([3, 3, 4, 2]); expect(value.decisions.every((decision) => decision.defaultReversibleAssumption === "exclude_affected_joint_rows" && decision.blocksPublicationOfAffectedRows && !decision.blocksUnrelatedWork && decision.resolution.status === "proposed")).toBe(true); });
  it("preserves the unrelated source-precedence proposal", () => { expect(build().inheritedDecision).toEqual({ decisionId: "nc-2022-primary-archive-canvass-source-precedence-v1", status: "proposed", recommendedChoice: "use_final_state_canvass_for_certified_2022_candidate_totals", safeDefault: "exclude_affected_rows_pending_review", affectedTargetReviewRecords: 0, note: "nc03_and_nc11_conflicts_are_outside_the_four_current_target_seats_but_parent_cycle_precedence_remains_unresolved" }); });
  it("approves and scores no relationship", () => { expect(build().records.every((record) => !record.identity.approved && !record.geography.approved && !record.jointApproved && !record.scoreEligible)).toBe(true); });
  it("rejects exact parent lineage drift", () => { expect(() => build((lock) => { lock.entries.find((entry: any) => entry.id === "north-carolina-primary-geography-compatibility-candidate-v1").parentIds = []; })).toThrow("SOURCE_LOCK_MISMATCH"); });
  it("rejects unknown fields and fully rehashed semantic substitution", () => { const unknown: any = build(); unknown.records[0].unexpected = true; expect(() => validateNcPrimaryJointPackage(unknown)).toThrow("UNKNOWN_OR_MISSING_FIELD"); const drift: any = build(), record = drift.records[0]; record.reviewDisposition = "identity_unresolved_split_geography"; record.reviewRecordSha256 = digest("dsa-seats:nc-primary-joint-review-record:v1\0", Object.fromEntries(Object.entries(record).filter(([key]) => key !== "reviewRecordSha256"))); drift.reviewRecordSetSha256 = digest("dsa-seats:nc-primary-joint-review-record-set:v1\0", drift.records); drift.packageSha256 = digest("dsa-seats:nc-primary-joint-review-package:v1\0", Object.fromEntries(Object.entries(drift).filter(([key]) => key !== "packageSha256"))); expect(() => validateNcPrimaryJointPackage(drift)).toThrow("RECORD_INVALID"); });
});
