import { createHash } from "node:crypto";

import { canonicalJson } from "../fec/aipac-proposed-packages";
import { validateHouseDemocraticPrimarySourceSelectionProposal } from "./house-democratic-primary-source-selection-proposal";
import { validateOhioPrimaryIdentityCandidate, type OhioPrimaryIdentityCandidate } from "./ohio-current-incumbent-primary-linkage-candidate";
import { validateOhioPrimaryResultsReceiptV4, type OhioPrimaryResultsReceiptV4 } from "./ohio-house-democratic-primary-results-receipt-v4";

export const OHIO_PRIMARY_GEOGRAPHY_V1 = "ohio-primary-geography-compatibility-candidate-v1" as const;
export const OHIO_PRIMARY_GEOGRAPHY_ROW_SET_SHA256 = "140e09197591c86d93d3f526c4bd153bb132113642942b5237abbe13d9939a7e";
export const OHIO_PRIMARY_GEOGRAPHY_PACKAGE_SHA256 = "f45684cde798a8e3b6f6306b48255ef208520db2eccf5e5a7992ddf1b05ff924";
export const OHIO_PRIMARY_GEOGRAPHY_OUTPUT_FILE_SHA256 = "6410d7bbb653994c6b624840eb993c708504f9facd31d169e24048576eb97da5";
export const OHIO_PRIMARY_GEOGRAPHY_OUTPUT_BYTE_SIZE = 18_717;
const INPUTS = {
  proposalFile: "85246e9adfd181e6f24606b6eaa29250c45c9e8e42a6dd5af5cb162de17f45b1", proposalPackage: "a090e0be03dc2b0fa5edd0c1132a8261eed0f98ceb4df090154d0b150d8721fb",
  receiptFile: "9104931022e1fdc671f69678fe2dc4a8d8da44d087f65575ca69af16a3dd2b09", receiptPackage: "f8acd66b060daac23ad13c3054ff42a32c3124ea6986e356a9d82710bff1d295",
  identityFile: "b4e47cf3f5b17811f83f531637b1f916ba7dea6afceb001ee10a251593912f28", identityPackage: "bbdf13d44228ca37c7076cedd0bca4dedb379b842d252f57c7c56fb8913f92b9", identitySet: "a6c2acd6383975e76cfd15055b2ebc388b6c6a7d953edb634b8323cf59fbe288",
  authorityFile: "66a0551a6c3c6432bff0a6a6db23f221fbe02ead1d15221d7050633898914670",
  cd119File: "d1a3c0cae01f10954063c6e70b23a37680c9451d4318bdd790d1f814dbce57de", cd119Dbf: "f0a863112c10ba7ad929fdd8aef481cdcfc3bf0df5506b1e8e508675ac873994",
} as const;
const PARENTS = ["house-democratic-primary-source-selection-proposal-20260804-v1", "ohio-house-democratic-primary-results-2022-2026-v4", "ohio-current-incumbent-primary-linkage-candidate-v1", "census-cd119-plan-change-authority-20260805", "tiger-cd119-39"] as const;
const REQUIRED = [
  [PARENTS[0], "urn:dsa-seats:house-democratic-primary-source-selection-proposal:v1:2026-08-04", "data/metadata/house-democratic-primary-source-selection-proposal-20260804-v1.json", 411_793, INPUTS.proposalFile, "review_proposal", ["dsa-target-factual-projection-20260804-v1", "dsa-target-incumbent-roster-20260804-v1", "fec-2026-congressional-primary-dates", "geo-national-cd119"]],
  [PARENTS[1], "urn:dsa-seats:ohio-house-democratic-primary-results:v4:2022-2026", "data/metadata/ohio-house-democratic-primary-results-2022-2026-v4.json", 38_893, INPUTS.receiptFile, "review_evidence_receipt", ["ohio-house-democratic-primary-results-2022-2026-v3", "oh-2022-may-primary-fulton-results-index", "oh-2022-may-primary-fulton-official-wrapper", "oh-2022-may-primary-fulton-official-summary", "oh-2022-may-primary-stark-official-tabulation"]],
  [PARENTS[2], "urn:dsa-seats:ohio-current-incumbent-primary-linkage-candidate:v1:2024-2026", "data/metadata/ohio-current-incumbent-primary-linkage-candidate-v1.json", 23_634, INPUTS.identityFile, "review_candidate", ["dsa-target-incumbent-roster-20260804-v1", "house-democratic-primary-source-selection-proposal-20260804-v1", "house-xml", "congress-legislators-current-20260804", "ohio-house-democratic-primary-results-2022-2026-v4"]],
  [PARENTS[3], "https://www.census.gov/geographies/mapping-files/2025/dec/rdo/119-congressional-district-bef.html", "data/source/elections/primary-results/geography/census-119-congressional-district-bef.html", 324_827, INPUTS.authorityFile, "source", []],
  [PARENTS[4], "https://www2.census.gov/geo/tiger/TIGER2025/CD/tl_2025_39_cd119.zip", "data/source/tiger2025/tl_2025_39_cd119.zip", 853_533, INPUTS.cd119File, "source", []],
] as const;
type LockEntry = Readonly<{ id?: string; url?: string; retainedPath?: string; retainedStatus?: string; byteSize?: number; sha256?: string; kind?: string; parentIds?: readonly string[] }>;
type Input = Readonly<{ proposal: unknown; proposalFileSha256: string; receipt: OhioPrimaryResultsReceiptV4; receiptFileSha256: string; identity: OhioPrimaryIdentityCandidate; identityFileSha256: string; authorityHtml: string; authorityFileSha256: string; oh119Dbf: Buffer; oh119FileSha256: string; sourceLock: unknown }>;
const sha = (value: Buffer): string => createHash("sha256").update(value).digest("hex");
const digest = (domain: string, value: unknown): string => createHash("sha256").update(domain, "ascii").update(canonicalJson(value), "utf8").digest("hex");
const fail = (code: string): never => { throw new Error(`Ohio primary geography rejected: ${code}`); };
const exactKeys = (value: unknown, keys: readonly string[]): boolean => typeof value === "object" && value !== null && canonicalJson(Object.keys(value as object).sort()) === canonicalJson([...keys].sort());
const ROW_KEYS = ["geographyObservationId", "identityObservationId", "identityRowSha256", "identityStatus", "contestId", "contestSha256", "resultAuthorityStatus", "certificationStatus", "sourceWinnerStatus", "cycleYear", "electionDate", "seatCycleId", "districtCode", "targetCd119Geoid", "historicalCongressSession", "historicalGeoid", "compatibilityDisposition", "evidenceClass", "confidence", "compatibilityCandidate", "compatibilityApproved", "identityApproved", "identityDispositionPreserved", "evaluatorUse", "scoreEligible", "rationaleCodes", "rowSha256"] as const;

function inventory(bytes: Buffer): readonly string[] {
  if (bytes.length < 65 || bytes[0] !== 0x03) fail("DBF_INVALID");
  const count = bytes.readUInt32LE(4), headerLength = bytes.readUInt16LE(8), recordLength = bytes.readUInt16LE(10);
  if (count !== 15 || headerLength < 65 || headerLength + count * recordLength > bytes.length || bytes[headerLength - 1] !== 0x0d) fail("DBF_CLOSURE_INVALID");
  const fields: Array<{ name: string; offset: number; length: number }> = []; let offset = 1;
  for (let cursor = 32; cursor + 32 <= headerLength && bytes[cursor] !== 0x0d; cursor += 32) { const name = bytes.subarray(cursor, cursor + 11).toString("ascii").replace(/\0.*$/, "").trim(), length = bytes[cursor + 16]!; fields.push({ name, offset, length }); offset += length; }
  if (!fields.length || offset !== recordLength) fail("DBF_LAYOUT_INVALID");
  const rows = Array.from({ length: count }, (_, index) => { const start = headerLength + index * recordLength; if (bytes[start] !== 0x20) fail("DBF_DELETED_RECORD"); const value = Object.fromEntries(fields.map((field) => [field.name, bytes.subarray(start + field.offset, start + field.offset + field.length).toString("ascii").trim()])); return { state: value.STATEFP, geoid: value.GEOID, district: value.CD119FP, session: value.CDSESSN }; }).sort((left, right) => Buffer.compare(Buffer.from(left.geoid ?? ""), Buffer.from(right.geoid ?? "")));
  if (rows.some((row, index) => { const district = String(index + 1).padStart(2, "0"); return row.state !== "39" || row.geoid !== `39${district}` || row.district !== district || row.session !== "119"; })) fail("DBF_INVENTORY_INVALID");
  return rows.map((row) => row.geoid!);
}

export function buildOhioPrimaryGeographyCandidate(input: Input) {
  if (input.proposalFileSha256 !== INPUTS.proposalFile || input.receiptFileSha256 !== INPUTS.receiptFile || input.identityFileSha256 !== INPUTS.identityFile || input.authorityFileSha256 !== INPUTS.authorityFile || createHash("sha256").update(input.authorityHtml).digest("hex") !== INPUTS.authorityFile || input.oh119FileSha256 !== INPUTS.cd119File || sha(input.oh119Dbf) !== INPUTS.cd119Dbf) fail("INPUT_HASH_MISMATCH");
  const proposal = validateHouseDemocraticPrimarySourceSelectionProposal(input.proposal), receipt = validateOhioPrimaryResultsReceiptV4(input.receipt), identity = validateOhioPrimaryIdentityCandidate(input.identity);
  const decision = proposal.decisions.find((row) => row.decisionId === "approve-historical-district-cd119-compatibility-v1");
  if (proposal.packageSha256 !== INPUTS.proposalPackage || receipt.packageSha256 !== INPUTS.receiptPackage || identity.packageSha256 !== INPUTS.identityPackage || identity.observationSetSha256 !== INPUTS.identitySet || receipt.review.resolution !== null || identity.review.resolution !== null || decision?.resolution !== null || identity.observations.some((row) => Number(row.cycleYear) === 2022)) fail("PARENT_INVALID");
  const phrase = "five states (Alabama, Georgia, Louisiana, New York, and North Carolina) that redrew their congressional district plans for the 119th Congress";
  if (!input.authorityHtml.includes(phrase) || input.authorityHtml.includes("five states (Alabama, Ohio")) fail("AUTHORITY_INVALID");
  const entries = (input.sourceLock as { entries?: unknown })?.entries; if (!Array.isArray(entries)) fail("SOURCE_LOCK_MISMATCH");
  for (const [id, url, path, bytes, hash, kind, parents] of REQUIRED) { const matches = (entries as LockEntry[]).filter((entry) => entry.id === id), entry = matches[0]; if (matches.length !== 1 || entry?.url !== url || entry.retainedPath !== path || entry.retainedStatus !== "retained" || entry.byteSize !== bytes || entry.sha256 !== hash || entry.kind !== kind || canonicalJson(entry.parentIds) !== canonicalJson(parents)) fail("SOURCE_LOCK_MISMATCH"); }
  const output = (entries as LockEntry[]).filter((entry) => entry.id === OHIO_PRIMARY_GEOGRAPHY_V1);
  if (!OHIO_PRIMARY_GEOGRAPHY_OUTPUT_FILE_SHA256) { if (output.length) fail("SOURCE_LOCK_MISMATCH"); } else { const entry = output[0]; if (output.length !== 1 || entry?.url !== "urn:dsa-seats:ohio-primary-geography-compatibility-candidate:v1:2024-2026" || entry.retainedPath !== "data/metadata/ohio-primary-geography-compatibility-candidate-v1.json" || entry.retainedStatus !== "retained" || entry.byteSize !== OHIO_PRIMARY_GEOGRAPHY_OUTPUT_BYTE_SIZE || entry.sha256 !== OHIO_PRIMARY_GEOGRAPHY_OUTPUT_FILE_SHA256 || entry.kind !== "review_candidate" || canonicalJson(entry.parentIds) !== canonicalJson(PARENTS)) fail("SOURCE_LOCK_MISMATCH"); }
  const keys = new Set(inventory(input.oh119Dbf));
  const rows = identity.observations.map((observation) => {
    const targetCd119Geoid = `39${observation.districtCode}`; if (!keys.has(targetCd119Geoid)) fail("GEOGRAPHY_KEY_MISSING"); const current = observation.cycleYear === 2024;
    const unsigned = { geographyObservationId: `oh:geography:${observation.cycleYear}:${observation.districtCode}`, identityObservationId: observation.observationId, identityRowSha256: observation.rowSha256, identityStatus: observation.identityStatus, contestId: observation.contestId, contestSha256: observation.contestSha256, resultAuthorityStatus: observation.resultAuthorityStatus, certificationStatus: observation.certificationStatus, sourceWinnerStatus: observation.sourceWinnerStatus, cycleYear: observation.cycleYear, electionDate: observation.electionDate, seatCycleId: observation.seatCycleId, districtCode: observation.districtCode, targetCd119Geoid, historicalCongressSession: current ? "119" as const : "120" as const, historicalGeoid: current ? targetCd119Geoid : null, compatibilityDisposition: current ? "same_cd119_session_and_geoid_exact_key_candidate" as const : "unassessed_cd120_authority_collection_pending" as const, evidenceClass: current ? "derived_exact_session_and_key" as const : "authority_pending" as const, confidence: current ? "high" as const : "none" as const, compatibilityCandidate: current, compatibilityApproved: false as const, identityApproved: false as const, identityDispositionPreserved: true as const, evaluatorUse: "excluded_pending_authorized_identity_historical_geography_review" as const, scoreEligible: false as const, rationaleCodes: current ? ["same_cd119_congressional_session", "same_state_district_geoid_in_cd119_inventory"] : ["cd120_authority_not_yet_retained", "do_not_assume_cd119_continuity_for_2026"] };
    return { ...unsigned, rowSha256: digest("dsa-seats:oh-primary-geography-row:v1\0", unsigned) };
  });
  const summary = { identityObservations: 10 as const, districtGeographyObservations2022: 0 as const, partialCountyEvidenceExcluded2022: 12 as const, cd118ToCd119PlanContinuityCandidates: 0 as const, exactCd119SessionKeyCandidates: 5 as const, cd120AuthorityPending: 5 as const, compatibilityCandidates: 5 as const, numberedDistrictsInCd119Inventory: 15 as const, automaticallyApprovedRows: 0 as const, scoreEligibleRows: 0 as const };
  const unsigned = { schema: OHIO_PRIMARY_GEOGRAPHY_V1, version: 1 as const, generatedAt: "2026-08-07T05:00:00.000Z" as const, sourceCutoff: "2026-08-06" as const, reviewerOnly: true as const, publicationEligible: false as const, defaultUse: "exclude_from_evaluator_until_authorized_identity_and_historical_geography_review" as const, review: { status: "proposed" as const, reviewer: null, reviewedAt: null, resolution: null }, inputs: { proposal: { sourceLockId: PARENTS[0], fileSha256: INPUTS.proposalFile, packageSha256: INPUTS.proposalPackage }, receipt: { sourceLockId: PARENTS[1], fileSha256: INPUTS.receiptFile, packageSha256: INPUTS.receiptPackage }, identity: { sourceLockId: PARENTS[2], fileSha256: INPUTS.identityFile, packageSha256: INPUTS.identityPackage, observationSetSha256: INPUTS.identitySet }, censusPlanChangeAuthority: { sourceLockId: PARENTS[3], fileSha256: INPUTS.authorityFile, relevance: "cd119_context_only_not_cd120_continuity" as const }, tigerLayer: { sourceLockId: PARENTS[4], fileSha256: INPUTS.cd119File, dbfMemberSha256: INPUTS.cd119Dbf, congressSession: "119" as const, districtCount: 15 as const } }, methodology: { targetSession: "119" as const, cycleSessionMapping: { "2024": "119" as const, "2026": "120" as const }, exactSameSessionRule: "same_cd119_session_state_and_district_geoid" as const, cd120Rule: "remain_unassessed_until_authoritative_cd120_plan_evidence_is_retained" as const, partial2022CountySegmentsCreateGeographyRows: false as const, rawTigerGeometryEqualityAssessed: false as const, overlapThresholdUsed: false as const, populationEquivalenceAssessed: false as const, evaluatorNumericValues: 0 as const }, summary, rows, rowSetSha256: digest("dsa-seats:oh-primary-geography-row-set:v1\0", rows), decisionSupport: { informsDecisionId: "approve-historical-district-cd119-compatibility-v1" as const, analysisConclusion: "five_exact_cd119_keys_proposed_five_cd120_rows_pending_and_partial_2022_county_evidence_excluded" as const, lifecycle: "evidence_for_bound_existing_decision_not_an_independent_decision" as const } };
  return { ...unsigned, packageSha256: digest("dsa-seats:oh-primary-geography-package:v1\0", unsigned) };
}
export type OhioPrimaryGeographyCandidate = ReturnType<typeof buildOhioPrimaryGeographyCandidate>;
export function validateOhioPrimaryGeographyCandidate(value: OhioPrimaryGeographyCandidate): OhioPrimaryGeographyCandidate {
  const { packageSha256, ...unsigned } = value;
  if (value.schema !== OHIO_PRIMARY_GEOGRAPHY_V1 || !value.reviewerOnly || value.publicationEligible || value.review.status !== "proposed" || value.review.reviewer !== null || value.review.reviewedAt !== null || value.review.resolution !== null || value.rows.length !== 10 || canonicalJson(value.summary) !== canonicalJson({ identityObservations: 10, districtGeographyObservations2022: 0, partialCountyEvidenceExcluded2022: 12, cd118ToCd119PlanContinuityCandidates: 0, exactCd119SessionKeyCandidates: 5, cd120AuthorityPending: 5, compatibilityCandidates: 5, numberedDistrictsInCd119Inventory: 15, automaticallyApprovedRows: 0, scoreEligibleRows: 0 })) fail("LIFECYCLE_INVALID");
  for (const row of value.rows) { if (!exactKeys(row, ROW_KEYS)) fail("ROW_FIELDS_INVALID"); const rowUnsigned = structuredClone(row) as Partial<typeof row>; delete rowUnsigned.rowSha256; const pending = row.cycleYear === 2026; if (Number(row.cycleYear) === 2022 || row.rowSha256 !== digest("dsa-seats:oh-primary-geography-row:v1\0", rowUnsigned) || row.compatibilityApproved || row.identityApproved || row.scoreEligible || !row.identityDispositionPreserved || (pending ? row.historicalCongressSession !== "120" || row.historicalGeoid !== null || row.compatibilityCandidate || row.evidenceClass !== "authority_pending" || row.confidence !== "none" : row.historicalCongressSession !== "119" || row.historicalGeoid !== row.targetCd119Geoid || !row.compatibilityCandidate || row.evidenceClass !== "derived_exact_session_and_key" || row.confidence !== "high")) fail("ROW_INVALID"); }
  if (value.rowSetSha256 !== digest("dsa-seats:oh-primary-geography-row-set:v1\0", value.rows) || (OHIO_PRIMARY_GEOGRAPHY_ROW_SET_SHA256 && value.rowSetSha256 !== OHIO_PRIMARY_GEOGRAPHY_ROW_SET_SHA256) || packageSha256 !== digest("dsa-seats:oh-primary-geography-package:v1\0", unsigned) || (OHIO_PRIMARY_GEOGRAPHY_PACKAGE_SHA256 && packageSha256 !== OHIO_PRIMARY_GEOGRAPHY_PACKAGE_SHA256)) fail("PACKAGE_INVALID");
  return value;
}
