/* eslint-disable @typescript-eslint/no-explicit-any -- adversarial persisted candidate mutations */
import { createHash } from "node:crypto";import { readFileSync } from "node:fs";import { describe,expect,it } from "vitest";import { buildOregonPrimaryIdentityCandidate,validateOregonPrimaryIdentityCandidate } from "./oregon-current-incumbent-primary-linkage-candidate";
const sha=(value:Buffer)=>createHash("sha256").update(value).digest("hex"),json=(path:string)=>{const bytes=readFileSync(path);return{bytes,value:JSON.parse(bytes.toString("utf8")),sha256:sha(bytes)}};
const build=(lockOverride?:unknown)=>{const roster=json("data/metadata/dsa-target-incumbent-roster-20260804-v1.json"),proposal=json("data/metadata/house-democratic-primary-source-selection-proposal-20260804-v1.json"),house=readFileSync("data/source/identity/house-member-data.xml"),congress=json("data/source/identity/congress-legislators-current-20260804.json"),receipt=json("data/metadata/oregon-house-democratic-primary-results-2022-2026-v1.json"),lock=json("data/source-lock.json");return buildOregonPrimaryIdentityCandidate({roster:roster.value,rosterFileSha256:roster.sha256,proposal:proposal.value,proposalFileSha256:proposal.sha256,houseXml:house.toString("utf8"),houseFileSha256:sha(house),congressPeople:congress.value,congressFileSha256:congress.sha256,receipt:receipt.value,receiptFileSha256:receipt.sha256,sourceLock:lockOverride??lock.value})};
describe("Oregon current-incumbent primary linkage candidate",()=>{
 it("rebuilds the proposed artifact exactly",()=>{expect(build()).toEqual(validateOregonPrimaryIdentityCandidate(json("data/metadata/oregon-current-incumbent-primary-linkage-candidate-v1.json").value))});
 it("retains exact, derived, and unresolved evidence classes",()=>{const value=build();expect(value.summary).toEqual({targetSeats:5,contestObservations:15,exactNameObservations:8,derivedNameRelationships:5,unresolvedObservations:2,proposedIdentityLinks:13,directIdentifierBridges:0,automaticallyApprovedRows:0,scoreEligibleRows:0});expect(value.links.filter(row=>row.evidenceClass==="exact_name_observation")).toHaveLength(8);expect(value.links.filter(row=>row.evidenceClass==="derived_name_relationship")).toHaveLength(5);expect(value.links.filter(row=>row.evidenceClass==="unresolved")).toHaveLength(2)});
 it("preserves predecessor cycles as unresolved",()=>{const value=build(),unresolved=value.links.filter(row=>row.sourceCandidate===null);expect(unresolved.map(row=>[row.contestId,row.rosterIdentity.officialHouseName])).toEqual([["or:2022:regular:us-house:03:democratic","Maxine Dexter"],["or:2022:regular:us-house:05:democratic","Janelle S. Bynum"]]);expect(unresolved.every(row=>row.relationshipDisposition==="not_linked_no_unique_candidate"&&row.confidence==="none")).toBe(true)});
 it("keeps all links proposed and evaluator-excluded",()=>{expect(build().links.every(row=>!row.directIdentifierBridgeAvailable&&!row.identityApproved&&!row.scoreEligible&&row.historicalGeographyStatus==="separate_candidate_not_approved")).toBe(true)});
 it("rejects lifecycle, row, source, and lock drift",()=>{const lifecycle:any=build();lifecycle.review.reviewer="fabricated";expect(()=>validateOregonPrimaryIdentityCandidate(lifecycle)).toThrow();const row:any=build();row.links[0].identityApproved=true;expect(()=>validateOregonPrimaryIdentityCandidate(row)).toThrow();const lock:any=json("data/source-lock.json").value,wrong=structuredClone(lock);wrong.entries.find((entry:any)=>entry.id==="house-xml").kind="derived_artifact";expect(()=>build(wrong)).toThrow("SOURCE_LOCK_MISMATCH")});
});
