/* eslint-disable @typescript-eslint/no-explicit-any -- adversarial persisted package mutations */
import { createHash } from "node:crypto";import { readFileSync } from "node:fs";import { describe,expect,it } from "vitest";import { buildOregonPrimaryJointPackage,validateOregonPrimaryJointPackage } from "./oregon-primary-identity-geography-review-package";const sha=(v:Buffer)=>createHash("sha256").update(v).digest("hex"),load=(p:string)=>{const bytes=readFileSync(p);return{value:JSON.parse(bytes.toString("utf8")),sha256:sha(bytes)}};
const build=()=>{const proposal=load("data/metadata/house-democratic-primary-source-selection-proposal-20260804-v1.json"),identity=load("data/metadata/oregon-current-incumbent-primary-linkage-candidate-v1.json"),geography=load("data/metadata/oregon-primary-geography-compatibility-candidate-v1.json"),lock=load("data/source-lock.json");return buildOregonPrimaryJointPackage({proposal:proposal.value,proposalFileSha256:proposal.sha256,identity:identity.value,identityFileSha256:identity.sha256,geography:geography.value,geographyFileSha256:geography.sha256,sourceLock:lock.value})};
describe("Oregon primary identity/geography joint review",()=>{
 it("rebuilds the proposed package exactly",()=>expect(build()).toEqual(validateOregonPrimaryJointPackage(load("data/metadata/oregon-primary-identity-geography-review-package-v1.json").value)));
 it("preserves the exact 8/2/5 joint state matrix",()=>expect(build().summary).toEqual({reviewRecords:15,identityAndGeographyCandidates:8,geographyCandidateIdentityUnresolved:2,identityCandidateCd120GeographyPending:5,identityCandidates:13,geographyCandidates:10,jointApprovedRecords:0,scoreEligibleRecords:0}));
 it("does not approve either parent through the join",()=>expect(build().records.every(row=>!row.identity.identityApproved&&!row.geography.compatibilityApproved&&!row.jointApproved&&!row.scoreEligible)).toBe(true));
 it("preserves the two predecessor rows and five CD120 rows",()=>{const value=build();expect(value.records.filter(row=>row.reviewDisposition==="geography_candidate_identity_unresolved").map(row=>row.contestId)).toEqual(["or:2022:regular:us-house:03:democratic","or:2022:regular:us-house:05:democratic"]);expect(value.records.filter(row=>row.reviewDisposition==="identity_candidate_cd120_geography_pending")).toHaveLength(5)});
 it("rejects fabricated lifecycle and row approval",()=>{const lifecycle:any=build();lifecycle.review.reviewer="fabricated";expect(()=>validateOregonPrimaryJointPackage(lifecycle)).toThrow();const row:any=build();row.records[0].jointApproved=true;expect(()=>validateOregonPrimaryJointPackage(row)).toThrow()});
});
