/* eslint-disable @typescript-eslint/no-explicit-any -- adversarial persisted-candidate mutations */
import { readFileSync } from "node:fs";
import { describe, expect, it } from "vitest";
import { buildOregonPrimaryGeographyCandidateV2, validateOregonPrimaryGeographyCandidateV2 } from "./oregon-primary-geography-compatibility-candidate-v2";

const input=()=>{const base="data/source/elections/primary-results/geography/oregon/2026";return{geographyV1Json:readFileSync("data/metadata/oregon-primary-geography-compatibility-candidate-v1.json","utf8"),authorityReceiptJson:readFileSync("data/metadata/oregon-2026-congressional-plan-authority-receipt-v1.json","utf8"),redistrictingPageBytes:readFileSync(`${base}/redistricting.html`),enrolledBillBytes:readFileSync(`${base}/sb881-enrolled.pdf`),enrolledBillTextBytes:readFileSync(`${base}/sb881-enrolled.txt`),mapGuideBytes:readFileSync(`${base}/interactive-map-data.pdf`),mapGuideTextBytes:readFileSync(`${base}/interactive-map-data.txt`),currentBlocksBytes:readFileSync("data/source/elections/primary-results/geography/oregon/current/41_OR_CD119.txt"),sourceLock:JSON.parse(readFileSync("data/source-lock.json","utf8"))}};

describe("Oregon primary geography compatibility candidate v2",()=>{
 it("composes six current-plan continuity candidates while retaining null CD120 GEOIDs",()=>{const value=buildOregonPrimaryGeographyCandidateV2(input());expect(value.summary).toEqual({contestCycleObservations:18,inheritedCandidates:12,oregon2026CurrentPlanContinuityCandidates:6,compatibilityCandidates:18,automaticallyApprovedRows:0,scoreEligibleRows:0});const current=value.rows.filter(row=>row.cycleYear===2026);expect(current.map(row=>row.districtCode)).toEqual(["01","02","03","04","05","06"]);expect(current.every(row=>row.historicalCongressSession==="120"&&row.historicalGeoid===null&&row.compatibilityCandidate&&row.planContinuityEvidence!==null)).toBe(true);expect(value.rows.every(row=>!row.compatibilityApproved&&!row.identityApproved&&!row.scoreEligible)).toBe(true);expect(Buffer.from(`${JSON.stringify(value,null,2)}\n`)).toEqual(readFileSync("data/metadata/oregon-primary-geography-compatibility-candidate-v2.json"))});
 it("rejects parent/source/lineage/output drift and lifecycle escalation",()=>{const parent=input();parent.geographyV1Json+=" ";expect(()=>buildOregonPrimaryGeographyCandidateV2(parent)).toThrow("OREGON_PRIMARY_GEOGRAPHY_V2_INVALID:input_bytes");const source=input();source.mapGuideTextBytes=Buffer.concat([source.mapGuideTextBytes,Buffer.from(" ")]);expect(()=>buildOregonPrimaryGeographyCandidateV2(source)).toThrow();const lock=input();lock.sourceLock.entries.find((entry:{id:string})=>entry.id==="oregon-2026-congressional-plan-authority-receipt-v1").parentIds=[];expect(()=>buildOregonPrimaryGeographyCandidateV2(lock)).toThrow();const currentInput=input(),base=buildOregonPrimaryGeographyCandidateV2(currentInput),mutations=[(v:any)=>{v.rows.find((r:any)=>r.cycleYear===2026).historicalGeoid="4101"},(v:any)=>{v.methodology.sourcePlanToCd119ExactBlockConcordanceAssessed=true},(v:any)=>{v.rows[0].compatibilityApproved=true},(v:any)=>{v.rows[0].scoreEligible=true},(v:any)=>{v.publicationEligible=true},(v:any)=>{v.review.reviewer="fabricated"},(v:any)=>{v.unexpected=true}];for(const mutate of mutations){const value=structuredClone(base);mutate(value);expect(()=>validateOregonPrimaryGeographyCandidateV2(value,currentInput)).toThrow("OREGON_PRIMARY_GEOGRAPHY_V2_INVALID:semantic_or_hash_drift")}});
});
