/* eslint-disable @typescript-eslint/no-explicit-any -- adversarial persisted candidate mutations */
import { createHash } from "node:crypto";import { execFileSync } from "node:child_process";import { readFileSync } from "node:fs";import { describe,expect,it } from "vitest";import { buildOregonPrimaryGeographyCandidate,validateOregonPrimaryGeographyCandidate } from "./oregon-primary-geography-compatibility-candidate";
const sha=(value:Buffer)=>createHash("sha256").update(value).digest("hex"),json=(path:string)=>{const bytes=readFileSync(path);return{bytes,value:JSON.parse(bytes.toString("utf8")),sha256:sha(bytes)}},dbf=(path:string)=>execFileSync("unzip",["-p",path,"*.dbf"]);
const build=()=>{const proposal=json("data/metadata/house-democratic-primary-source-selection-proposal-20260804-v1.json"),receipt=json("data/metadata/oregon-house-democratic-primary-results-2022-2026-v1.json"),authority=readFileSync("data/source/elections/primary-results/geography/census-119-congressional-district-bef.html"),or118=readFileSync("data/source/tiger2022/tl_2022_41_cd118.zip"),or119=readFileSync("data/source/tiger2025/tl_2025_41_cd119.zip"),sourceLock=json("data/source-lock.json").value;return buildOregonPrimaryGeographyCandidate({proposal:proposal.value,proposalFileSha256:proposal.sha256,receipt:receipt.value,receiptFileSha256:receipt.sha256,authorityHtml:authority.toString("utf8"),authorityFileSha256:sha(authority),or118Dbf:dbf("data/source/tiger2022/tl_2022_41_cd118.zip"),or118FileSha256:sha(or118),or119Dbf:dbf("data/source/tiger2025/tl_2025_41_cd119.zip"),or119FileSha256:sha(or119),sourceLock})};
describe("Oregon primary geography compatibility candidate",()=>{
 it("rebuilds the proposed artifact exactly",()=>{expect(build()).toEqual(validateOregonPrimaryGeographyCandidate(json("data/metadata/oregon-primary-geography-compatibility-candidate-v1.json").value))});
 it("separates CD118 continuity, CD119 exact keys, and CD120 pending",()=>{const value=build();expect(value.summary).toEqual({contestCycleObservations:18,cd118ToCd119PlanContinuityCandidates:6,exactCd119SessionKeyCandidates:6,cd120AuthorityPending:6,compatibilityCandidates:12,automaticallyApprovedRows:0,scoreEligibleRows:0});expect(value.rows.filter(row=>row.cycleYear===2022&&row.compatibilityCandidate)).toHaveLength(6);expect(value.rows.filter(row=>row.cycleYear===2024&&row.compatibilityCandidate)).toHaveLength(6);expect(value.rows.filter(row=>row.cycleYear===2026&&row.historicalGeoid===null&&!row.compatibilityCandidate)).toHaveLength(6)});
 it("keeps all rows unapproved and score-ineligible",()=>{expect(build().rows.every(row=>!row.compatibilityApproved&&!row.identityApproved&&!row.scoreEligible)).toBe(true)});
 it("rejects fabricated lifecycle and fully rehashed row drift",()=>{const value:any=build();value.review.reviewer="fabricated";expect(()=>validateOregonPrimaryGeographyCandidate(value)).toThrow();const drift:any=build();drift.rows[0].compatibilityApproved=true;expect(()=>validateOregonPrimaryGeographyCandidate(drift)).toThrow()});
 it("rejects source byte and lock drift",()=>{const proposal=json("data/metadata/house-democratic-primary-source-selection-proposal-20260804-v1.json");expect(()=>buildOregonPrimaryGeographyCandidate({proposal:proposal.value,proposalFileSha256:"0".repeat(64),receipt:{} as any,receiptFileSha256:"0".repeat(64),authorityHtml:"",authorityFileSha256:"0".repeat(64),or118Dbf:Buffer.alloc(0),or118FileSha256:"0".repeat(64),or119Dbf:Buffer.alloc(0),or119FileSha256:"0".repeat(64),sourceLock:{}})).toThrow("INPUT_HASH_MISMATCH")});
});
