import { createHash } from "node:crypto";
import { canonicalJson } from "../fec/aipac-proposed-packages";
import { validateHouseDemocraticPrimarySourceSelectionProposal } from "./house-democratic-primary-source-selection-proposal";
import { validateOregonPrimaryReceipt, type OregonPrimaryReceipt } from "./oregon-house-democratic-primary-results-receipt";

export const OREGON_PRIMARY_GEOGRAPHY_V1="oregon-primary-geography-compatibility-candidate-v1" as const;
export const OREGON_PRIMARY_GEOGRAPHY_ROW_SET_SHA256="c57f4f405d4806eb05687a8ecd85cd5b26f2225dd502adfd54386724b71c32a0";
export const OREGON_PRIMARY_GEOGRAPHY_PACKAGE_SHA256="8e8354e5dd6ddabcf3a97c3049015556b7262a0308df9d9e2cc3aae2995b06be";
const INPUTS={proposalFile:"85246e9adfd181e6f24606b6eaa29250c45c9e8e42a6dd5af5cb162de17f45b1",proposalPackage:"a090e0be03dc2b0fa5edd0c1132a8261eed0f98ceb4df090154d0b150d8721fb",receiptFile:"11c2da1823c1b56753375b906bbc004c6c06de7d5379147b1f566e838db71449",receiptPackage:"e27397dec36c7804ca220bd19647d5c18112f8a0b02f505b4ff443660bd1c25f",receiptSet:"4d9eedd708ebe4687d3aeeb0821448e2bf9939031e4a24317aa0c019c76e9ca1",authorityFile:"66a0551a6c3c6432bff0a6a6db23f221fbe02ead1d15221d7050633898914670",or118File:"7cb5f032ba20abef66f0395cb7c5e1ec5215fb748024f898458c0bd88533edf3",or118Dbf:"964cb9e745136f48363bc6bb8fc3bfdf5e07374c9d6c1a5fe5c8aa9d1ea49b1c",or119File:"264688a2c95768dcde1361db0dec03252df8f52c5a918ea1892a8bc320e6f33a",or119Dbf:"fb94e6893fa5338ca1bbac769dc1b3dd3a1cfc3934365e1d8fd508db26cfddde"} as const;
type Row=Readonly<{contestId:string;contestSha256:string;seatCycleId:string;districtCode:string;cycleYear:2022|2024|2026;targetCd119Geoid:string;historicalCongressSession:"118"|"119"|"120";historicalGeoid:string|null;compatibilityDisposition:"official_no_plan_change_declaration_same_geoid_key_candidate"|"same_cd119_session_and_geoid_exact_key_candidate"|"unassessed_cd120_authority_collection_pending";evidenceClass:"direct_official_plan_continuity_and_derived_key"|"derived_exact_session_and_key"|"authority_pending";confidence:"high"|"none";compatibilityCandidate:boolean;compatibilityApproved:false;identityApproved:false;evaluatorUse:"excluded_pending_authorized_identity_historical_geography_and_review";scoreEligible:false;rationaleCodes:readonly string[];rowSha256:string}>;
export type OregonPrimaryGeographyCandidate=Readonly<{schema:typeof OREGON_PRIMARY_GEOGRAPHY_V1;version:1;generatedAt:"2026-08-06T00:30:00.000Z";sourceCutoff:"2026-08-05";reviewerOnly:true;publicationEligible:false;defaultUse:"exclude_from_evaluator_until_authorized_identity_historical_geography_and_review";review:Readonly<{status:"proposed";reviewer:null;reviewedAt:null;resolution:null}>;inputs:unknown;methodology:unknown;summary:Readonly<{contestCycleObservations:18;cd118ToCd119PlanContinuityCandidates:6;exactCd119SessionKeyCandidates:6;cd120AuthorityPending:6;compatibilityCandidates:12;automaticallyApprovedRows:0;scoreEligibleRows:0}>;rows:readonly Row[];rowSetSha256:string;decisionSupport:unknown;packageSha256:string}>;
type BuildInput=Readonly<{proposal:unknown;proposalFileSha256:string;receipt:OregonPrimaryReceipt;receiptFileSha256:string;authorityHtml:string;authorityFileSha256:string;or118Dbf:Buffer;or118FileSha256:string;or119Dbf:Buffer;or119FileSha256:string;sourceLock:unknown}>;
const sha=(value:Buffer|string)=>createHash("sha256").update(value).digest("hex"),digest=(domain:string,value:unknown)=>createHash("sha256").update(domain).update(canonicalJson(value)).digest("hex"),sort=(a:string,b:string)=>Buffer.compare(Buffer.from(a),Buffer.from(b));
const fail=(code:string):never=>{throw new Error(`Oregon primary geography rejected: ${code}`)};

function parseDbf(bytes:Buffer,session:"118"|"119"){
  if(bytes.length<65||bytes[0]!==3)fail("DBF_HEADER_INVALID");
  const count=bytes.readUInt32LE(4),header=bytes.readUInt16LE(8),record=bytes.readUInt16LE(10),fields:{name:string;length:number;offset:number}[]=[];let offset=1;
  for(let cursor=32;cursor+32<=header&&bytes[cursor]!==0x0d;cursor+=32){const name=bytes.subarray(cursor,cursor+11).toString("ascii").replace(/\0.*$/g,"").trim(),length=bytes[cursor+16]!;if(!name||length<1)fail("DBF_FIELD_INVALID");fields.push({name,length,offset});offset+=length}
  if(count!==6||header<65||record<2||header+count*record>bytes.length||offset!==record||bytes[header-1]!==0x0d)fail("DBF_LAYOUT_INVALID");
  const historical=session==="118",stateField=historical?"STATEFP20":"STATEFP",geoidField=historical?"GEOID20":"GEOID",districtField=historical?"CD118FP":"CD119FP";
  const rows=Array.from({length:count},(_,index)=>{const start=header+index*record;if(bytes[start]!==0x20)fail("DBF_DELETED_RECORD");const value=Object.fromEntries(fields.map(field=>[field.name,bytes.subarray(start+field.offset,start+field.offset+field.length).toString("ascii").trim()]));return{state:value[stateField],geoid:value[geoidField],district:value[districtField],session:value.CDSESSN}}).sort((a,b)=>sort(a.geoid??"",b.geoid??""));
  if(rows.some((row,index)=>row.state!=="41"||row.geoid!==`41${String(index+1).padStart(2,"0")}`||row.district!==String(index+1).padStart(2,"0")||row.session!==session))fail("DBF_INVENTORY_INVALID");
  return rows;
}

export function buildOregonPrimaryGeographyCandidate(input:BuildInput):OregonPrimaryGeographyCandidate{
  const hashes=[input.proposalFileSha256,input.receiptFileSha256,input.authorityFileSha256,input.or118FileSha256,input.or119FileSha256,sha(input.authorityHtml),sha(input.or118Dbf),sha(input.or119Dbf)],expected=[INPUTS.proposalFile,INPUTS.receiptFile,INPUTS.authorityFile,INPUTS.or118File,INPUTS.or119File,INPUTS.authorityFile,INPUTS.or118Dbf,INPUTS.or119Dbf];if(hashes.some((value,index)=>value!==expected[index]))fail("INPUT_HASH_MISMATCH");
  const proposal=validateHouseDemocraticPrimarySourceSelectionProposal(input.proposal),receipt=validateOregonPrimaryReceipt(input.receipt),decision=proposal.decisions.find(value=>value.decisionId==="approve-historical-district-cd119-compatibility-v1");if(proposal.packageSha256!==INPUTS.proposalPackage||receipt.packageSha256!==INPUTS.receiptPackage||receipt.summary.contestSetSha256!==INPUTS.receiptSet||!decision||decision.resolution!==null||receipt.review.resolution!==null)fail("PARENT_INVALID");
  const phrase="five states (Alabama, Georgia, Louisiana, New York, and North Carolina) that redrew their congressional district plans for the 119th Congress";if(!input.authorityHtml.includes(phrase)||input.authorityHtml.includes("five states (Alabama, Oregon"))fail("AUTHORITY_INVALID");
  const inventories=[parseDbf(input.or118Dbf,"118"),parseDbf(input.or119Dbf,"119")],keys=new Set(inventories.flatMap(rows=>rows.map(row=>`${row.session}:${row.geoid}`))),lock=input.sourceLock as{entries?:Array<{id:string;retainedPath?:string;retainedStatus:string;sha256:string;kind:string}>},required=[["house-democratic-primary-source-selection-proposal-20260804-v1",INPUTS.proposalFile,"data/metadata/house-democratic-primary-source-selection-proposal-20260804-v1.json","review_proposal"],["oregon-house-democratic-primary-results-2022-2026-v1",INPUTS.receiptFile,"data/metadata/oregon-house-democratic-primary-results-2022-2026-v1.json","review_candidate"],["census-cd119-plan-change-authority-20260805",INPUTS.authorityFile,"data/source/elections/primary-results/geography/census-119-congressional-district-bef.html","source"],["tiger-cd118-41",INPUTS.or118File,"data/source/tiger2022/tl_2022_41_cd118.zip","source"],["tiger-cd119-41",INPUTS.or119File,"data/source/tiger2025/tl_2025_41_cd119.zip","source"]] as const;
  if(!Array.isArray(lock.entries)||required.some(([id,file,path,kind])=>{const matches=lock.entries!.filter(entry=>entry.id===id);return matches.length!==1||matches[0]!.retainedStatus!=="retained"||matches[0]!.sha256!==file||matches[0]!.retainedPath!==path||matches[0]!.kind!==kind}))fail("SOURCE_LOCK_MISMATCH");
  const rows=receipt.contests.map(contest=>{const target=`41${contest.districtCode}`,session=contest.cycleYear===2022?"118" as const:contest.cycleYear===2024?"119" as const:"120" as const,historical=contest.cycleYear===2026?null:target,candidate=contest.cycleYear!==2026;if(!keys.has(`119:${target}`)||(historical&&!keys.has(`${session}:${historical}`)))fail("CONTEST_OUTSIDE_TIGER_CLOSURE");const unsigned={contestId:contest.contestId,contestSha256:contest.contestSha256,seatCycleId:`seat_house_or_${contest.districtCode}_current`,districtCode:contest.districtCode,cycleYear:contest.cycleYear,targetCd119Geoid:target,historicalCongressSession:session,historicalGeoid:historical,compatibilityDisposition:contest.cycleYear===2022?"official_no_plan_change_declaration_same_geoid_key_candidate" as const:contest.cycleYear===2024?"same_cd119_session_and_geoid_exact_key_candidate" as const:"unassessed_cd120_authority_collection_pending" as const,evidenceClass:contest.cycleYear===2022?"direct_official_plan_continuity_and_derived_key" as const:contest.cycleYear===2024?"derived_exact_session_and_key" as const:"authority_pending" as const,confidence:candidate?"high" as const:"none" as const,compatibilityCandidate:candidate,compatibilityApproved:false as const,identityApproved:false as const,evaluatorUse:"excluded_pending_authorized_identity_historical_geography_and_review" as const,scoreEligible:false as const,rationaleCodes:contest.cycleYear===2022?["official_census_cd119_redraw_list_excludes_or","same_state_district_geoid_in_cd118_and_cd119_inventory"]:contest.cycleYear===2024?["same_cd119_congressional_session","same_state_district_geoid_in_cd119_inventory"]:["cd120_authority_not_yet_retained","do_not_assume_cd119_continuity_for_2026"]};return{...unsigned,rowSha256:digest("dsa-seats:or-primary-geography-row:v1\0",unsigned)}}).sort((a,b)=>sort(a.contestId,b.contestId));
  const unsigned={schema:OREGON_PRIMARY_GEOGRAPHY_V1,version:1 as const,generatedAt:"2026-08-06T00:30:00.000Z" as const,sourceCutoff:"2026-08-05" as const,reviewerOnly:true as const,publicationEligible:false as const,defaultUse:"exclude_from_evaluator_until_authorized_identity_historical_geography_and_review" as const,review:{status:"proposed" as const,reviewer:null,reviewedAt:null,resolution:null},inputs:{sourceSelectionProposal:{sourceLockId:"house-democratic-primary-source-selection-proposal-20260804-v1",fileSha256:INPUTS.proposalFile,packageSha256:INPUTS.proposalPackage,decisionUnresolved:true},oregonReceipt:{sourceLockId:"oregon-house-democratic-primary-results-2022-2026-v1",fileSha256:INPUTS.receiptFile,packageSha256:INPUTS.receiptPackage,contestSetSha256:INPUTS.receiptSet},censusPlanChangeAuthority:{sourceLockId:"census-cd119-plan-change-authority-20260805",fileSha256:INPUTS.authorityFile,authorityClaim:"five_states_redrew_for_cd119_al_ga_la_ny_nc_or_absent"},tigerLayers:[{sourceLockId:"tiger-cd118-41",fileSha256:INPUTS.or118File,dbfMemberSha256:INPUTS.or118Dbf,cdSession:"118",districtCount:6},{sourceLockId:"tiger-cd119-41",fileSha256:INPUTS.or119File,dbfMemberSha256:INPUTS.or119Dbf,cdSession:"119",districtCount:6}]},methodology:{targetSession:"119",cycleSessionMapping:{"2022":"118","2024":"119","2026":"120"},rawTigerGeometryEqualityAssessed:false,overlapThresholdUsed:false,automaticDecisionClosure:false,evaluatorNumericValues:0},summary:{contestCycleObservations:18 as const,cd118ToCd119PlanContinuityCandidates:6 as const,exactCd119SessionKeyCandidates:6 as const,cd120AuthorityPending:6 as const,compatibilityCandidates:12 as const,automaticallyApprovedRows:0 as const,scoreEligibleRows:0 as const},rows,rowSetSha256:digest("dsa-seats:or-primary-geography-row-set:v1\0",rows),decisionSupport:{informsDecisionId:"approve-historical-district-cd119-compatibility-v1",analysisConclusion:"official_evidence_supports_or_cd118_to_cd119_plan_continuity_and_exact_cd119_keys_while_cd120_remains_unassessed",lifecycle:"evidence_for_bound_existing_decision_not_an_independent_decision"}};
  return{...unsigned,packageSha256:digest("dsa-seats:or-primary-geography-candidate:v1\0",unsigned)};
}

export function validateOregonPrimaryGeographyCandidate(value:OregonPrimaryGeographyCandidate):OregonPrimaryGeographyCandidate{
  if(value.schema!==OREGON_PRIMARY_GEOGRAPHY_V1||value.version!==1||!value.reviewerOnly||value.publicationEligible||value.review.status!=="proposed"||value.review.reviewer!==null||value.review.reviewedAt!==null||value.review.resolution!==null||value.rows.length!==18)fail("LIFECYCLE_INVALID");
  if(value.rows.some((row,index)=>{const rowHashInput=Object.fromEntries(Object.entries(row).filter(([key])=>key!=="rowSha256"));return row.compatibilityApproved||row.identityApproved||row.scoreEligible||row.rowSha256!==digest("dsa-seats:or-primary-geography-row:v1\0",rowHashInput)||(index>0&&sort(value.rows[index-1]!.contestId,row.contestId)>=0)||(row.cycleYear===2026?(row.historicalGeoid!==null||row.compatibilityCandidate||row.confidence!=="none"):(row.historicalGeoid!==row.targetCd119Geoid||!row.compatibilityCandidate||row.confidence!=="high"))}))fail("ROW_INVALID");
  const {packageSha256,...unsigned}=value,rowSet=digest("dsa-seats:or-primary-geography-row-set:v1\0",value.rows);if(value.rowSetSha256!==rowSet||rowSet!==OREGON_PRIMARY_GEOGRAPHY_ROW_SET_SHA256||packageSha256!==digest("dsa-seats:or-primary-geography-candidate:v1\0",unsigned)||packageSha256!==OREGON_PRIMARY_GEOGRAPHY_PACKAGE_SHA256)fail("PACKAGE_INVALID");return value;
}
