import { createHash } from "node:crypto";
import { canonicalJson } from "../fec/aipac-proposed-packages";
import { validateTexasPrimaryGeographyCandidateV2, type TexasPrimaryGeographyCandidateV2, type TexasPrimaryGeographyV2Input } from "./texas-primary-geography-compatibility-candidate-v2";
import { validateTexasPrimaryIdentityGeographyReviewPackage } from "./texas-primary-identity-geography-review-package";

export const TEXAS_PRIMARY_JOINT_REVIEW_V2 = "texas-primary-identity-geography-review-package-v2" as const;
type LockEntry = { id: string; url: string; retainedPath: string | null; retainedStatus: "retained" | "nonretained"; byteSize: number; sha256: string; kind: string; parentIds: string[] };
export type TexasPrimaryJointReviewV2Input = TexasPrimaryGeographyV2Input & Readonly<{ jointV1Json: string; geographyV2Json: string }>;
const JOINT_SHA = "f6b6636a3829685faa5b5b5fc47440726608d46e1d8b766c620e3d24d42d615f", GEOGRAPHY_SHA = "8cf09b2b0f7250a7cca6acb2dc08ad67769b0837beaaa9b736cef51849eabf67";
const PARENTS = ["texas-primary-identity-geography-review-package-v1", "texas-primary-geography-compatibility-candidate-v2"] as const;
const OUTPUT_ENTRY: LockEntry = { id: TEXAS_PRIMARY_JOINT_REVIEW_V2, url: "urn:dsa-seats:texas-primary-identity-geography-review-package:v2:2026-08-06", retainedPath: "data/metadata/texas-primary-identity-geography-review-package-v2.json", retainedStatus: "retained", byteSize: 277078, sha256: "3e8f31e9bc92403f0a3223fd793ddab694d45bf42dc6054f85761099d7a38072", kind: "review_proposal", parentIds: [...PARENTS] };
const requiredEntries: LockEntry[] = [
  { id: PARENTS[0], url: "urn:dsa-seats:texas-primary-identity-geography-review-package:v1:2026-08-05", retainedPath: "data/metadata/texas-primary-identity-geography-review-package-v1.json", retainedStatus: "retained", byteSize: 233427, sha256: JOINT_SHA, kind: "review_proposal", parentIds: ["house-democratic-primary-source-selection-proposal-20260804-v1", "texas-current-incumbent-primary-event-identity-candidate-v1", "texas-primary-geography-compatibility-candidate-v1"] },
  { id: PARENTS[1], url: "urn:dsa-seats:texas-primary-geography-compatibility-candidate:v2:2026-08-06", retainedPath: "data/metadata/texas-primary-geography-compatibility-candidate-v2.json", retainedStatus: "retained", byteSize: 187351, sha256: GEOGRAPHY_SHA, kind: "review_candidate", parentIds: ["texas-primary-geography-compatibility-candidate-v1", "texas-2026-primary-block-crosswalk-candidate-v1"] },
];
const sha = (value: string) => createHash("sha256").update(value).digest("hex");
const digest = (domain: string, value: unknown) => createHash("sha256").update(domain, "ascii").update(canonicalJson(value), "utf8").digest("hex");
const order = (left: string, right: string) => Buffer.compare(Buffer.from(left), Buffer.from(right));
const fail = (reason: string): never => { throw new Error(`TX_PRIMARY_JOINT_REVIEW_V2_INVALID:${reason}`); };
const exactEntry = (entries: LockEntry[], expected: LockEntry) => { const matches = entries.filter((entry) => entry.id === expected.id); if (matches.length !== 1 || canonicalJson(matches[0]) !== canonicalJson(expected)) fail(`source_lock:${expected.id}`); };

function assemble(input: TexasPrimaryJointReviewV2Input) {
  if (sha(input.jointV1Json) !== JOINT_SHA || sha(input.geographyV2Json) !== GEOGRAPHY_SHA) fail("input_bytes");
  const joint = validateTexasPrimaryIdentityGeographyReviewPackage(JSON.parse(input.jointV1Json));
  const geographyInput = { geographyV1Json: input.geographyV1Json, crosswalkJson: input.crosswalkJson, currentStatusBytes: input.currentStatusBytes, enrolledLawBytes: input.enrolledLawBytes, datasetBytes: input.datasetBytes, planBlocksBytes: input.planBlocksBytes, currentBlocksBytes: input.currentBlocksBytes, sourceLock: input.sourceLock };
  const geography = validateTexasPrimaryGeographyCandidateV2(JSON.parse(input.geographyV2Json) as TexasPrimaryGeographyCandidateV2, geographyInput);
  if (joint.packageSha256 !== "d964089acf669dc2b95c3dfab19cd93f719619fecc3ac9dce411b3a90749be8b" || geography.packageSha256 !== "ce68de1820b1e5763f34c722ac79f6722f21ad4a53eecc39166ebd70c5fe3036" || geography.rowSetSha256 !== "35bd41317eba6bc40e649e4b4ba13c0c1db06c51c5405951038b05dceb0ef526") fail("parent_identity");
  for (const entry of requiredEntries) exactEntry(input.sourceLock.entries, entry);
  exactEntry(input.sourceLock.entries, OUTPUT_ENTRY);
  const geographyByObservation = new Map(geography.rows.map((row) => [row.observationId, row]));
  const records = joint.records.map((parent) => {
    const geo = geographyByObservation.get(parent.geographyObservationId) ?? fail("missing_geography_row");
    if (geo.identityObservationId !== parent.identityObservationId || geo.eventId !== parent.eventId || geo.cycleYear !== parent.cycleYear || geo.electionStage !== parent.electionStage || geo.sourceObservationStatus !== parent.sourceObservationStatus || geo.sourceContestId !== parent.sourceContestId || geo.sourceContestSha256 !== parent.sourceContestSha256 || geo.certificationStatus !== parent.certificationStatus) fail("geography_join");
    const identityCandidate = parent.identity.candidate, geographyCandidate = geo.compatibilityCandidate;
    const reviewCategory = identityCandidate && geographyCandidate ? "identity_and_geography_candidates" as const : !identityCandidate && geographyCandidate ? "geography_candidate_identity_unresolved" as const : identityCandidate ? "identity_candidate_crosswalk_review_required" as const : "identity_unresolved_crosswalk_review_required" as const;
    const reviewerAction = geographyCandidate ? (identityCandidate ? "review_identity_and_geography_independently" as const : "review_geography_and_retain_identity_unresolved" as const) : (identityCandidate ? "review_identity_and_retain_geography_crosswalk_review_required" as const : "retain_identity_unresolved_and_geography_crosswalk_review_required" as const);
    const { reviewRecordSha256: parentReviewRecordSha256, ...parentUnsigned } = parent;
    if (!parentReviewRecordSha256) fail("parent_record_hash");
    const unsigned = { ...parentUnsigned, geography: { parentRowSha256: geo.rowSha256, status: geographyCandidate ? "candidate" as const : "crosswalk_review_required" as const, targetCd119Geoid: geo.targetCd119Geoid, historicalCongressSession: geo.historicalCongressSession, historicalGeoid: geo.historicalGeoid, evidenceClass: geo.evidenceClass, confidence: geo.confidence, compatibilityDisposition: geo.compatibilityDisposition, candidate: geographyCandidate, approved: false as const, planBlockCrosswalk: geo.planBlockCrosswalk }, reviewCategory, reviewerAction, rationaleCodes: [reviewCategory, "parent_candidates_not_approved_by_join", "result_disposition_unchanged", "all_independent_review_gates_remain_open"] };
    return { ...unsigned, reviewRecordSha256: digest("dsa-seats:tx-primary-joint-review-record:v2\0", unsigned) };
  }).sort((left, right) => order(left.reviewRecordId, right.reviewRecordId));
  const decisions = joint.decisions.map((parent) => parent.decisionId === "tx-primary:accept-geography-compatibility-v1" ? { ...parent, question: "Should the 52 inherited Texas geography candidates be accepted while all 26 PlanC2333 split rows remain crosswalk-review-required?", recommendedDecision: "Accept the 52 inherited candidates without claiming raw geometry equality and retain all 26 PlanC2333 split rows for crosswalk review.", consequences: ["Acceptance resolves only the 2022 and 2024 geography candidates; it does not promote any 2026 row.", "Deferral keeps all 78 records excluded while preserving the completed PlanC2333 evidence chain."], workCompletedWhileWaiting: "All 78 geography rows are joined; 52 inherited candidates and 26 evidence-backed split-review rows retain exact parent hashes." } : parent).sort((left, right) => order(left.decisionId, right.decisionId));
  if (records.length !== 78 || decisions.length !== 5 || decisions.some((decision) => decision.review.reviewer !== null || decision.review.reviewedAt !== null || decision.review.resolution !== null) || records.filter((record) => record.cycleYear === 2026).some((record) => record.geography.status !== "crosswalk_review_required" || record.geography.candidate || record.geography.planBlockCrosswalk === null)) fail("closure");
  const unsigned = { schema: TEXAS_PRIMARY_JOINT_REVIEW_V2, version: 2 as const, generatedAt: "2026-08-06T14:30:00.000Z" as const, sourceCutoff: "2026-08-06" as const, reviewerOnly: true as const, publicationEligible: false as const, defaultUse: joint.defaultUse, review: joint.review, inheritedUnresolvedGates: joint.inheritedUnresolvedGates, parents: { jointV1: { sourceLockId: PARENTS[0], fileSha256: JOINT_SHA, packageSha256: joint.packageSha256, reviewRecordSetSha256: joint.reviewRecordSetSha256, decisionSetSha256: joint.decisionSetSha256, superseded: false as const }, geographyV2: { sourceLockId: PARENTS[1], fileSha256: GEOGRAPHY_SHA, packageSha256: geography.packageSha256, rowSetSha256: geography.rowSetSha256 } }, methodology: { compositionOnly: true as const, identityAndResultProjectionPreserved: true as const, geographyProjectionSource: PARENTS[1], splitRowsPromotedByThreshold: false as const, automaticDecisionClosure: false as const, evaluatorNumericValues: 0 as const }, summary: { reviewRecords: 78 as const, identityAndGeographyCandidates: 25 as const, geographyCandidateIdentityUnresolved: 27 as const, identityCandidateCrosswalkReviewRequired: 8 as const, identityUnresolvedCrosswalkReviewRequired: 18 as const, identityCandidates: 33 as const, geographyCandidates: 52 as const, reportedContestRecords: 44 as const, sourceUnobservedEventRecords: 34 as const, proposedDecisions: 5 as const, jointApprovedRecords: 0 as const, scoreEligibleRecords: 0 as const }, records, reviewRecordSetSha256: digest("dsa-seats:tx-primary-joint-review-record-set:v2\0", records), decisions, decisionSetSha256: digest("dsa-seats:tx-primary-joint-review-decision-set:v2\0", decisions), inheritedDecisionResolutions: joint.inheritedDecisionResolutions };
  return { ...unsigned, packageSha256: digest("dsa-seats:tx-primary-joint-review-package:v2\0", unsigned) };
}
export type TexasPrimaryJointReviewPackageV2 = ReturnType<typeof assemble>;
export function buildTexasPrimaryJointReviewPackageV2(input: TexasPrimaryJointReviewV2Input) { return assemble(input); }
export function validateTexasPrimaryJointReviewPackageV2(value: TexasPrimaryJointReviewPackageV2, input: TexasPrimaryJointReviewV2Input) { if (canonicalJson(value) !== canonicalJson(assemble(input))) fail("semantic_or_hash_drift"); return value; }
