/* eslint-disable @typescript-eslint/no-explicit-any -- adversarial immutable-package mutations */
import { createHash } from "node:crypto";
import { readFileSync } from "node:fs";
import { describe,expect,it } from "vitest";
import { canonicalJson } from "../fec/aipac-proposed-packages";
import { buildVirginiaPrimaryJointReviewPackage,validateVirginiaPrimaryJointReviewPackage } from "./virginia-primary-identity-geography-review-package";
const text=(path:string)=>readFileSync(path,"utf8");
const digest=(domain:string,value:unknown)=>createHash("sha256").update(domain,"ascii").update(canonicalJson(value),"utf8").digest("hex");
const build=()=>buildVirginiaPrimaryJointReviewPackage({proposalJson:text("data/metadata/house-democratic-primary-source-selection-proposal-20260804-v1.json"),identityJson:text("data/metadata/virginia-current-incumbent-primary-linkage-candidate-v1.json"),geographyJson:text("data/metadata/virginia-primary-geography-compatibility-candidate-v1.json"),sourceLockJson:text("data/source-lock.json")});
const rehash=(value:any)=>{for(const row of value.records){const unsigned={...row};delete unsigned.recordSha256;row.recordSha256=digest("dsa-seats:va-primary-joint-row:v1\0",unsigned)}value.recordSetSha256=digest("dsa-seats:va-primary-joint-row-set:v1\0",value.records);value.decisionSetSha256=digest("dsa-seats:va-primary-joint-decision-set:v1\0",value.decisions);const unsigned={...value};delete unsigned.packageSha256;value.packageSha256=digest("dsa-seats:va-primary-joint-package:v1\0",unsigned);return value};

describe("Virginia primary identity/geography joint review package",()=>{
 it("joins all twelve rows into exact independent review categories",()=>{const value=build();expect(value.summary).toEqual({reviewRecords:12,bothCandidates:3,geographyCandidateIdentityNoMatch:1,geographyCandidateIdentityUnassessed:8,officialAuthorityRecords:4,identityCandidates:3,geographyCandidates:12,proposedDecisions:5,jointApprovedRecords:0,scoreEligibleRecords:0});expect(value.records.find(row=>row.recordId==="va-primary-joint:2024:11")).toEqual(expect.objectContaining({reviewCategory:"geography_candidate_identity_no_match",identityStatus:"reported_contest_no_current_incumbent_match",jointApproved:false,scoreEligible:false}));expect(value.records.filter(row=>row.reviewCategory==="geography_candidate_identity_unassessed")).toHaveLength(8);expect(validateVirginiaPrimaryJointReviewPackage(value)).toEqual(value);expect(text("data/metadata/virginia-primary-identity-geography-review-package-v1.json")).toBe(`${JSON.stringify(value,null,2)}\n`)});
 it("keeps five decisions independently scoped",()=>{const value=build();expect(value.decisions.map(row=>[row.decisionId,row.evidenceRecordIds.length])).toEqual([["va-primary:accept-official-result-authority-v1",4],["va-primary:accept-geography-compatibility-v1",12],["va-primary:accept-identity-links-v1",3],["va-primary:retain-primary-disposition-exclusion-v1",12],["va-primary:retain-progressive-classification-exclusion-v1",12]]);expect(value.decisions.every(row=>row.review.status==="proposed"&&row.review.resolution===null)).toBe(true)});
 it.each([["joint approval",(v:any)=>{v.records[0].jointApproved=true}],["score",(v:any)=>{v.records[0].scoreEligible=true}],["predecessor identity",(v:any)=>{v.records.find((r:any)=>r.recordId==="va-primary-joint:2024:11").identityStatus="proposed_identity_link"}],["publication",(v:any)=>{v.publicationEligible=true}],["unknown claim",(v:any)=>{v.records[0].nominee=true}]])("rejects fully rehashed %s",(_label,mutate)=>{const value=structuredClone(build()) as any;mutate(value);expect(()=>validateVirginiaPrimaryJointReviewPackage(rehash(value))).toThrow("VA_PRIMARY_JOINT_REVIEW_INVALID")});
});
