/* eslint-disable @typescript-eslint/no-explicit-any -- immutable JSON parents are strictly hash- and validator-bound */
import { createHash } from "node:crypto";
import { canonicalJson } from "../fec/aipac-proposed-packages";
import { validateDsaTargetIncumbentRoster } from "../identity/incumbent-tenure-factual-candidate";
import { validateHouseDemocraticPrimarySourceSelectionProposal } from "./house-democratic-primary-source-selection-proposal";
import { validateVirginiaPrimaryReceipt } from "./virginia-house-democratic-primary-results-receipt";

type Input = { rosterBytes: Buffer; proposalBytes: Buffer; receiptBytes: Buffer; houseBytes: Buffer; congressBytes: Buffer; sourceLockBytes: Buffer };
type MatchMethod = "exact_normalized_official_house_name_same_district" | "derived_official_middle_name_expands_source_middle_initial_same_district";
type Row = { observationId: string; cycleYear: 2022 | 2024; districtCode: string; seatCycleId: string; bioguideId: string; officialHouseName: string; officialContestStatus: "official_result_present" | "official_result_not_present_for_target_district_cycle"; contestId: string | null; contestSha256: string | null; sourceCandidateName: string | null; sourceCandidateVotes: number | null; sourceWinnerMarker: boolean | null; officialResultWinnerName: string | null; identityStatus: "proposed_identity_link" | "reported_contest_no_current_incumbent_match" | "official_result_absent_identity_unassessed"; matchMethod: MatchMethod | null; evidenceClass: "exact_name_observation" | "derived_name_relationship" | null; confidence: "high" | null; identityApproved: false; selected: false; evaluatorUse: "excluded_pending_identity_geography_disposition_classification_and_publication_review"; scoreEligible: false; rowSha256: string };
export type VirginiaCurrentIncumbentPrimaryLinkageCandidate = ReturnType<typeof buildVirginiaCurrentIncumbentPrimaryLinkageCandidate>;

const FILES = { roster: "8ae9bb3423e6160d00b5395186c42550e28811b817a482650875d87de71079e1", proposal: "85246e9adfd181e6f24606b6eaa29250c45c9e8e42a6dd5af5cb162de17f45b1", receipt: "85858953a6b8478e3a738e3427fb160e2428efc3805de377192bdc8e75433e47", house: "4ccea8259aff2df6a175545e45bdac2dfcdf0085a9cc7ab6c46aa80527bc524b", congress: "bc48cccd12df96164e5a2415fc41e838ca255fe85c297731515529692f7982cf" } as const;
const targets = [["03", "S000185", "Robert C. \"Bobby\" Scott"], ["04", "M001227", "Jennifer L. McClellan"], ["07", "V000138", "Eugene Simon Vindman"], ["08", "B001292", "Donald S. Beyer, Jr."], ["10", "S001230", "Suhas Subramanyam"], ["11", "W000831", "James R. Walkinshaw"]] as const;
const expectedLinks: Record<string, { name: string; method: MatchMethod }> = { "2022:08": { name: "Donald S. Beyer, Jr.", method: "exact_normalized_official_house_name_same_district" }, "2024:07": { name: "Eugene S. Vindman", method: "derived_official_middle_name_expands_source_middle_initial_same_district" }, "2024:10": { name: "Suhas Subramanyam", method: "exact_normalized_official_house_name_same_district" } };
const sourceIds = ["dsa-target-incumbent-roster-20260804-v1", "house-democratic-primary-source-selection-proposal-20260804-v1", "house-xml", "congress-legislators-current-20260804", "virginia-house-democratic-primary-results-2022-2026-v1"] as const;
const SOURCE_SET_SHA256 = "bc219b9b81f4f39d989281b6b259cd674b5ea5e08f91cb7779bdf9c48f371c74";
const OBSERVATION_SET_SHA256 = "017958f7adad4054c58e8069ee856a29d8cb265f0e237deebdfb1b97c9d0f778";
const PACKAGE_SHA256 = "6090c0d73dff58746d56bef48252b561bef2eedf4cb4ab390e0799071c97da52";
const OUTPUT = { id: "virginia-current-incumbent-primary-linkage-candidate-v1", url: "urn:dsa-seats:virginia-current-incumbent-primary-linkage-candidate:v1:2026-08-06", path: "data/metadata/virginia-current-incumbent-primary-linkage-candidate-v1.json", bytes: 17_012, sha256: "ca318b9782f8c42813497a991dc151ecf07841aee3cde7aa6a310b521c53fa56", parents: [...sourceIds] } as const;
const review = { status: "proposed" as const, reviewer: null, reviewedAt: null, resolution: null };
const summary = { targetSeats: 6 as const, targetCycleRows: 12 as const, officialContestsPresent: 4 as const, officialResultsAbsent: 8 as const, proposedIdentityLinks: 3 as const, exactNameObservations: 2 as const, derivedNameRelationships: 1 as const, reportedContestNoCurrentIncumbentMatch: 1 as const, unofficial2026RowsImported: 0 as const, automaticallyApprovedRows: 0 as const, selectedRows: 0 as const, scoreEligibleRows: 0 as const };
const limitations = ["Only event-certified 2022 and 2024 result evidence participates; the retained unofficial 2026 snapshots are excluded.", "A source winner marker or highest vote total does not establish current-incumbent identity, selection, nomination, or approval.", "An absent target district-cycle result remains absent and is not converted into zero, uncontested, no-candidate, or no-primary.", "The 2024 VA-11 result names Gerald Connolly and is not linked to current incumbent James Walkinshaw."] as const;
const unresolvedGates = ["review_incumbent_candidate_identity", "review_historical_district_compatibility", "decide_nonstandard_primary_disposition_treatment", "review_progressive_candidate_classification", "complete_human_data_review_and_publication_approval"] as const;
const sha = (value: Buffer) => createHash("sha256").update(value).digest("hex");
const digest = (domain: string, value: unknown) => createHash("sha256").update(domain, "ascii").update(canonicalJson(value), "utf8").digest("hex");
const fail = (): never => { throw new Error("VA_PRIMARY_IDENTITY_CANDIDATE_INVALID"); };
const exactKeys = (value: object, expected: readonly string[]) => canonicalJson(Object.keys(value).sort()) === canonicalJson([...expected].sort());
const TOP_KEYS = ["generatedAt", "limitations", "observationSetSha256", "observations", "packageSha256", "publicationEligible", "review", "reviewerOnly", "schema", "sourceCutoff", "sources", "summary", "unresolvedGates", "version"] as const;
const ROW_KEYS = ["bioguideId", "confidence", "contestId", "contestSha256", "cycleYear", "districtCode", "evaluatorUse", "evidenceClass", "identityApproved", "identityStatus", "matchMethod", "observationId", "officialContestStatus", "officialHouseName", "officialResultWinnerName", "rowSha256", "scoreEligible", "seatCycleId", "selected", "sourceCandidateName", "sourceCandidateVotes", "sourceWinnerMarker"] as const;
const parse = (bytes: Buffer) => { try { return JSON.parse(bytes.toString("utf8")); } catch { return fail(); } };
const tag = (block: string, name: string) => block.match(new RegExp(`<${name}>([^<]*)</${name}>`))?.[1] ?? "";

export function buildVirginiaCurrentIncumbentPrimaryLinkageCandidate(input: Input) {
  if (sha(input.rosterBytes) !== FILES.roster || sha(input.proposalBytes) !== FILES.proposal || sha(input.receiptBytes) !== FILES.receipt || sha(input.houseBytes) !== FILES.house || sha(input.congressBytes) !== FILES.congress) fail();
  const roster = validateDsaTargetIncumbentRoster(parse(input.rosterBytes)), proposal = validateHouseDemocraticPrimarySourceSelectionProposal(parse(input.proposalBytes)), receipt = validateVirginiaPrimaryReceipt(parse(input.receiptBytes)), congress = parse(input.congressBytes), lock = parse(input.sourceLockBytes);
  if (!Array.isArray(congress) || proposal.decisions.find((decision) => decision.decisionId === "approve-historic-primary-candidate-identity-resolution-v1")?.resolution !== null) fail();
  const sources = sourceIds.map((id) => { const matches = lock.entries?.filter((entry: any) => entry.id === id) ?? []; if (matches.length !== 1) fail(); return matches[0]; });
  if (digest("dsa-seats:va-primary-identity-source-set:v1\0", sources) !== SOURCE_SET_SHA256) fail();
  const outputEntries = lock.entries?.filter((entry: any) => entry.id === OUTPUT.id) ?? [];
  if (outputEntries.length !== 1 || outputEntries[0].url !== OUTPUT.url || outputEntries[0].retainedPath !== OUTPUT.path || outputEntries[0].retainedStatus !== "retained" || outputEntries[0].byteSize !== OUTPUT.bytes || outputEntries[0].sha256 !== OUTPUT.sha256 || outputEntries[0].kind !== "review_candidate" || canonicalJson(outputEntries[0].parentIds) !== canonicalJson(OUTPUT.parents)) fail();
  const xml = input.houseBytes.toString("utf8"), blocks = [...xml.matchAll(/<member>([\s\S]*?)<\/member>/g)].map((match) => match[1]!);
  const observations: Row[] = [];
  for (const cycleYear of [2022, 2024] as const) for (const [districtCode, bioguideId, officialHouseName] of targets) {
    const seatCycleId = `seat_house_va_${districtCode}_current`, rosterRows = roster.rows.filter((row) => row.seatCycleId === seatCycleId), memberBlocks = blocks.filter((block) => tag(block, "bioguideID") === bioguideId), people = congress.filter((person: any) => person.id?.bioguide === bioguideId);
    const currentTerms = people[0]?.terms?.filter((term: any) => term.type === "rep" && term.state === "VA" && term.district === Number(districtCode)) ?? [];
    if (rosterRows.length !== 1 || rosterRows[0]!.bioguideId !== bioguideId || memberBlocks.length !== 1 || tag(memberBlocks[0]!, "statedistrict") !== `VA${districtCode}` || tag(memberBlocks[0]!, "official-name") !== officialHouseName || people.length !== 1 || people[0]?.name?.official_full !== officialHouseName || currentTerms.length === 0) fail();
    const contests = receipt.contests.filter((contest) => contest.cycleYear === cycleYear && contest.districtCode === districtCode && contest.resultAuthorityStatus === "official_result_retained"); if (contests.length > 1) fail(); const contest = contests[0], expected = expectedLinks[`${cycleYear}:${districtCode}`];
    let sourceCandidate = null as any;
    if (contest && expected) { sourceCandidate = contest.candidates.find((candidate) => candidate.sourceCandidateName === expected.name); if (!sourceCandidate || (cycleYear === 2024 && sourceCandidate.sourceWinnerMarker !== true)) fail(); }
    const identityStatus = !contest ? "official_result_absent_identity_unassessed" as const : sourceCandidate ? "proposed_identity_link" as const : "reported_contest_no_current_incumbent_match" as const;
    const unsigned = { observationId: `va:identity:${cycleYear}:${districtCode}`, cycleYear, districtCode, seatCycleId, bioguideId, officialHouseName, officialContestStatus: contest ? "official_result_present" as const : "official_result_not_present_for_target_district_cycle" as const, contestId: contest?.contestId ?? null, contestSha256: contest?.contestSha256 ?? null, sourceCandidateName: sourceCandidate?.sourceCandidateName ?? null, sourceCandidateVotes: sourceCandidate?.votes ?? null, sourceWinnerMarker: sourceCandidate?.sourceWinnerMarker ?? null, officialResultWinnerName: contest?.winnerSourceCandidateName ?? null, identityStatus, matchMethod: expected?.method ?? null, evidenceClass: expected ? expected.method.startsWith("exact_") ? "exact_name_observation" as const : "derived_name_relationship" as const : null, confidence: expected ? "high" as const : null, identityApproved: false as const, selected: false as const, evaluatorUse: "excluded_pending_identity_geography_disposition_classification_and_publication_review" as const, scoreEligible: false as const };
    observations.push({ ...unsigned, rowSha256: digest("dsa-seats:va-primary-identity-row:v1\0", unsigned) });
  }
  const unsigned = { schema: "virginia-current-incumbent-primary-linkage-candidate-v1" as const, version: 1 as const, generatedAt: "2026-08-06T14:30:00.000Z" as const, sourceCutoff: "2026-08-05" as const, reviewerOnly: true as const, publicationEligible: false as const, review, sources, summary, observations, observationSetSha256: digest("dsa-seats:va-primary-identity-row-set:v1\0", observations), limitations, unresolvedGates };
  return { ...unsigned, packageSha256: digest("dsa-seats:va-primary-identity-package:v1\0", unsigned) };
}

export function validateVirginiaCurrentIncumbentPrimaryLinkageCandidate(value: VirginiaCurrentIncumbentPrimaryLinkageCandidate) {
  const { packageSha256, ...unsigned } = value;
  const invalidRow = value.observations.length !== 12 || value.observations.some((row, index) => { const cycle = index < 6 ? 2022 : 2024, [district, bioguide, name] = targets[index % 6]!, expected = expectedLinks[`${cycle}:${district}`], contestPresent = ["2022:08", "2024:07", "2024:10", "2024:11"].includes(`${cycle}:${district}`), noMatch = `${cycle}:${district}` === "2024:11", unsignedRow: Partial<Row> = { ...row }; delete unsignedRow.rowSha256; return !exactKeys(row, ROW_KEYS) || row.observationId !== `va:identity:${cycle}:${district}` || row.cycleYear !== cycle || row.districtCode !== district || row.seatCycleId !== `seat_house_va_${district}_current` || row.bioguideId !== bioguide || row.officialHouseName !== name || row.officialContestStatus !== (contestPresent ? "official_result_present" : "official_result_not_present_for_target_district_cycle") || row.identityStatus !== (expected ? "proposed_identity_link" : noMatch ? "reported_contest_no_current_incumbent_match" : "official_result_absent_identity_unassessed") || row.matchMethod !== (expected?.method ?? null) || row.evidenceClass !== (expected ? expected.method.startsWith("exact_") ? "exact_name_observation" : "derived_name_relationship" : null) || row.confidence !== (expected ? "high" : null) || row.identityApproved !== false || row.selected !== false || row.evaluatorUse !== "excluded_pending_identity_geography_disposition_classification_and_publication_review" || row.scoreEligible !== false || row.rowSha256 !== digest("dsa-seats:va-primary-identity-row:v1\0", unsignedRow); });
  if (!exactKeys(value, TOP_KEYS) || value.schema !== "virginia-current-incumbent-primary-linkage-candidate-v1" || value.version !== 1 || value.generatedAt !== "2026-08-06T14:30:00.000Z" || value.sourceCutoff !== "2026-08-05" || value.reviewerOnly !== true || value.publicationEligible !== false || canonicalJson(value.review) !== canonicalJson(review) || canonicalJson(value.summary) !== canonicalJson(summary) || canonicalJson(value.limitations) !== canonicalJson(limitations) || canonicalJson(value.unresolvedGates) !== canonicalJson(unresolvedGates) || digest("dsa-seats:va-primary-identity-source-set:v1\0", value.sources) !== SOURCE_SET_SHA256 || value.observationSetSha256 !== OBSERVATION_SET_SHA256 || value.observationSetSha256 !== digest("dsa-seats:va-primary-identity-row-set:v1\0", value.observations) || packageSha256 !== PACKAGE_SHA256 || packageSha256 !== digest("dsa-seats:va-primary-identity-package:v1\0", unsigned) || invalidRow) fail();
  return value;
}
