/* eslint-disable @typescript-eslint/no-explicit-any -- immutable JSON parents are hash- and validator-bound */
import { createHash } from "node:crypto";
import { canonicalJson } from "../fec/aipac-proposed-packages";
import { validateHouseDemocraticPrimarySourceSelectionProposal } from "./house-democratic-primary-source-selection-proposal";
import { validateVirginiaPrimaryReceipt } from "./virginia-house-democratic-primary-results-receipt";
import { validateVirginiaCurrentIncumbentPrimaryLinkageCandidate } from "./virginia-current-incumbent-primary-linkage-candidate";

type Input = { proposalBytes: Buffer; receiptBytes: Buffer; identityBytes: Buffer; authorityBytes: Buffer; cd118Zip: Buffer; cd118Dbf: Buffer; cd119Zip: Buffer; cd119Dbf: Buffer; sourceLockBytes: Buffer };
type IdentityStatus = "proposed_identity_link" | "reported_contest_no_current_incumbent_match" | "official_result_absent_identity_unassessed";
type Row = { observationId:string;identityObservationId:string;identityRowSha256:string;identityStatus:IdentityStatus;contestId:string|null;contestSha256:string|null;resultAuthorityStatus:"official_result_retained"|null;certificationStatus:"event_level_board_certification_retained_no_individual_certificate"|null;sourceWinnerStatus:"marked_by_source"|"not_marked_by_source"|"not_applicable_no_reported_contest";cycleYear:2022|2024;seatCycleId:string;districtCode:string;targetCd119Geoid:string;historicalCongressSession:"118"|"119";historicalGeoid:string;compatibilityDisposition:"official_no_plan_change_declaration_same_geoid_key_candidate"|"same_cd119_session_and_geoid_exact_key_candidate";evidenceClass:"direct_official_plan_continuity_and_derived_key"|"derived_exact_session_and_key";confidence:"high";compatibilityCandidate:true;compatibilityApproved:false;identityApproved:false;identityDispositionPreserved:true;evaluatorUse:"excluded_pending_identity_historical_geography_disposition_review_and_publication_approval";scoreEligible:false;rowSha256:string };
export type VirginiaPrimaryGeographyCandidate = ReturnType<typeof buildVirginiaPrimaryGeographyCandidate>;

const FILES={proposal:"85246e9adfd181e6f24606b6eaa29250c45c9e8e42a6dd5af5cb162de17f45b1",receipt:"85858953a6b8478e3a738e3427fb160e2428efc3805de377192bdc8e75433e47",identity:"ca318b9782f8c42813497a991dc151ecf07841aee3cde7aa6a310b521c53fa56",authority:"66a0551a6c3c6432bff0a6a6db23f221fbe02ead1d15221d7050633898914670",cd118:"b5aa7d080a41ab64350340844c2658bf16fe3549b89fb9b65262af4821ba6001",cd118Dbf:"78cf73e65ebf2207d06662bfa446e22667df0ea1a0ff580c94de5edd1ab916b3",cd119:"e9c7eabefcf65e957fb4d505c759dfed08e1a994dbeff34ba015d4a9b612d731",cd119Dbf:"cb2c35b7d550b7fda62c1d35f333fa0e0ed558da05edafc8535f9824942cfbe3"} as const;
const ids=["house-democratic-primary-source-selection-proposal-20260804-v1","virginia-house-democratic-primary-results-2022-2026-v1","virginia-current-incumbent-primary-linkage-candidate-v1","census-cd119-plan-change-authority-20260805","tiger-cd118-51","tiger-cd119-51"] as const;
const SOURCE_SET="384fec16d163a62472a18f7d71075d002cc27019dc329e17f469ed7d5cb6c23d";
const SET="5a191d63d50302b35e8e3f323fc3628dad11cb6c6eabf591d46c2260e0b36f69"; const PACKAGE="0a470c2b402997e778c08f7b93c8ded614a41f053ea6e990f1af05fb25121920";
const OUTPUT={id:"virginia-primary-geography-compatibility-candidate-v1",url:"urn:dsa-seats:virginia-primary-geography-compatibility-candidate:v1:2026-08-06",path:"data/metadata/virginia-primary-geography-compatibility-candidate-v1.json",bytes:20_458,sha256:"b4309ff23ab9b32fe6be76705b5fce436b2228abb64cc86860ae2c3ac39df23c",parents:[...ids]} as const;
const districts=["03","04","07","08","10","11"] as const;
const review={status:"proposed" as const,reviewer:null,reviewedAt:null,resolution:null};
const summary={identityRows:12 as const,identityProposedLinks:3 as const,identityNoMatchRows:1 as const,identityUnassessedRows:8 as const,cd118ToCd119PlanContinuityCandidates:6 as const,exactCd119SessionKeyCandidates:6 as const,numberedDistrictsPerLayer:11 as const,specialDistrictRowsPerLayer:0 as const,compatibilityCandidates:12 as const,automaticallyApprovedRows:0 as const,scoreEligibleRows:0 as const};
const sha=(v:Buffer)=>createHash("sha256").update(v).digest("hex");
const digest=(domain:string,v:unknown)=>createHash("sha256").update(domain,"ascii").update(canonicalJson(v),"utf8").digest("hex");
const fail=():never=>{throw new Error("VA_PRIMARY_GEOGRAPHY_CANDIDATE_INVALID")};
const parse=(v:Buffer)=>{try{return JSON.parse(v.toString("utf8"))}catch{return fail()}};
const exact=(v:object,keys:readonly string[])=>canonicalJson(Object.keys(v).sort())===canonicalJson([...keys].sort());
const projection=(rows:readonly Row[])=>rows.map(row=>{const value:Partial<Row>={...row};delete value.rowSha256;return value});
const TOP=["generatedAt","packageSha256","parentProjectionSha256","publicationEligible","rawTigerGeometryEqualityAssessed","review","reviewerOnly","rowSetSha256","rows","schema","sourceCutoff","sources","summary","version"] as const;
const ROW=["certificationStatus","compatibilityApproved","compatibilityCandidate","compatibilityDisposition","confidence","contestId","contestSha256","cycleYear","districtCode","evaluatorUse","evidenceClass","historicalCongressSession","historicalGeoid","identityApproved","identityDispositionPreserved","identityObservationId","identityRowSha256","identityStatus","observationId","resultAuthorityStatus","rowSha256","scoreEligible","seatCycleId","sourceWinnerStatus","targetCd119Geoid"] as const;

function inventory(bytes:Buffer,session:"118"|"119"){
  if(bytes.length<65||bytes[0]!==3)fail();const count=bytes.readUInt32LE(4),header=bytes.readUInt16LE(8),record=bytes.readUInt16LE(10),fields:Array<{name:string;length:number;offset:number}>=[];let offset=1;
  for(let cursor=32;cursor+32<=header&&bytes[cursor]!==13;cursor+=32){const name=bytes.subarray(cursor,cursor+11).toString("ascii").replace(/\0.*$/,"").trim(),length=bytes[cursor+16]!;if(!name||length<1)fail();fields.push({name,length,offset});offset+=length;}
  if(count!==11||header+count*record>bytes.length||offset!==record||bytes[header-1]!==13)fail();const old=session==="118",sf=old?"STATEFP20":"STATEFP",gf=old?"GEOID20":"GEOID",df=old?"CD118FP":"CD119FP";
  const rows=Array.from({length:count},(_,i)=>{const start=header+i*record;if(bytes[start]!==32)fail();const v=Object.fromEntries(fields.map(f=>[f.name,bytes.subarray(start+f.offset,start+f.offset+f.length).toString("ascii").trim()]));return{state:v[sf],geoid:v[gf],district:v[df],session:v.CDSESSN};}).sort((a,b)=>Buffer.compare(Buffer.from(a.geoid??""),Buffer.from(b.geoid??"")));
  if(rows.some((r,i)=>r.state!=="51"||r.geoid!==`51${String(i+1).padStart(2,"0")}`||r.district!==String(i+1).padStart(2,"0")||r.session!==session))fail();return rows;
}

export function buildVirginiaPrimaryGeographyCandidate(input:Input){
  const actual=[sha(input.proposalBytes),sha(input.receiptBytes),sha(input.identityBytes),sha(input.authorityBytes),sha(input.cd118Zip),sha(input.cd118Dbf),sha(input.cd119Zip),sha(input.cd119Dbf)];if(actual.some((v,i)=>v!==Object.values(FILES)[i]))fail();
  const proposal=validateHouseDemocraticPrimarySourceSelectionProposal(parse(input.proposalBytes)),receipt=validateVirginiaPrimaryReceipt(parse(input.receiptBytes)),identity=validateVirginiaCurrentIncumbentPrimaryLinkageCandidate(parse(input.identityBytes)),lock=parse(input.sourceLockBytes);
  if(proposal.decisions.find(d=>d.decisionId==="approve-historical-district-cd119-compatibility-v1")?.resolution!==null||receipt.packageSha256!=="0048f27a17220816e7aeaf0f8abcd4760608cfbf889bcac681b7f2cbb60b300d"||identity.packageSha256!=="6090c0d73dff58746d56bef48252b561bef2eedf4cb4ab390e0799071c97da52")fail();
  const phrase="five states (Alabama, Georgia, Louisiana, New York, and North Carolina) that redrew their congressional district plans for the 119th Congress";if(!input.authorityBytes.toString("utf8").includes(phrase))fail();
  const keys=new Set([...inventory(input.cd118Dbf,"118"),...inventory(input.cd119Dbf,"119")].map(r=>`${r.session}:${r.geoid}`));const sources=ids.map(id=>{const m=lock.entries?.filter((e:any)=>e.id===id)??[];if(m.length!==1)fail();return m[0]});if(digest("dsa-seats:va-primary-geography-source-set:v1\0",sources)!==SOURCE_SET)fail();const outputs=lock.entries?.filter((e:any)=>e.id===OUTPUT.id)??[];if(outputs.length!==1||outputs[0].url!==OUTPUT.url||outputs[0].retainedPath!==OUTPUT.path||outputs[0].retainedStatus!=="retained"||outputs[0].byteSize!==OUTPUT.bytes||outputs[0].sha256!==OUTPUT.sha256||outputs[0].kind!=="review_candidate"||canonicalJson(outputs[0].parentIds)!==canonicalJson(OUTPUT.parents))fail();
  const rows:Row[]=identity.observations.map(o=>{const session=o.cycleYear===2022?"118" as const:"119" as const,geoid=`51${o.districtCode}`,contests=receipt.contests.filter(c=>c.contestId===o.contestId);if(!keys.has(`${session}:${geoid}`)||!keys.has(`119:${geoid}`)||(o.contestId===null?contests.length!==0:contests.length!==1||contests[0]!.contestSha256!==o.contestSha256))fail();const contest=contests[0];if(contest&&(contest.resultAuthorityStatus!=="official_result_retained"||contest.certificationStatus!=="event_level_board_certification_retained_no_individual_certificate"))fail();const unsigned={observationId:`va:geography:${o.cycleYear}:${o.districtCode}`,identityObservationId:o.observationId,identityRowSha256:o.rowSha256,identityStatus:o.identityStatus,contestId:o.contestId,contestSha256:o.contestSha256,resultAuthorityStatus:contest?"official_result_retained" as const:null,certificationStatus:contest?"event_level_board_certification_retained_no_individual_certificate" as const:null,sourceWinnerStatus:contest?(contest.winnerSourceCandidateName===null?"not_marked_by_source" as const:"marked_by_source" as const):"not_applicable_no_reported_contest" as const,cycleYear:o.cycleYear,seatCycleId:o.seatCycleId,districtCode:o.districtCode,targetCd119Geoid:geoid,historicalCongressSession:session,historicalGeoid:geoid,compatibilityDisposition:o.cycleYear===2022?"official_no_plan_change_declaration_same_geoid_key_candidate" as const:"same_cd119_session_and_geoid_exact_key_candidate" as const,evidenceClass:o.cycleYear===2022?"direct_official_plan_continuity_and_derived_key" as const:"derived_exact_session_and_key" as const,confidence:"high" as const,compatibilityCandidate:true as const,compatibilityApproved:false as const,identityApproved:false as const,identityDispositionPreserved:true as const,evaluatorUse:"excluded_pending_identity_historical_geography_disposition_review_and_publication_approval" as const,scoreEligible:false as const};return{...unsigned,rowSha256:digest("dsa-seats:va-primary-geography-row:v1\0",unsigned)}});
  const parentProjectionSha256=digest("dsa-seats:va-primary-geography-parent-projection:v1\0",projection(rows));const unsigned={schema:"virginia-primary-geography-compatibility-candidate-v1" as const,version:1 as const,generatedAt:"2026-08-06T15:30:00.000Z" as const,sourceCutoff:"2026-08-05" as const,reviewerOnly:true as const,publicationEligible:false as const,review,sources,summary,rawTigerGeometryEqualityAssessed:false as const,parentProjectionSha256,rows,rowSetSha256:digest("dsa-seats:va-primary-geography-row-set:v1\0",rows)};return{...unsigned,packageSha256:digest("dsa-seats:va-primary-geography-package:v1\0",unsigned)};
}

export function validateVirginiaPrimaryGeographyCandidate(value:VirginiaPrimaryGeographyCandidate){
  const {packageSha256,...unsigned}=value;const expected=[2022,2024].flatMap(y=>districts.map(d=>`va:geography:${y}:${d}`));const invalid=value.rows.length!==12||value.rows.some((r,i)=>{const{rowSha256,...u}=r,cycle=i<6?2022:2024,d=districts[i%6]!,continuity=cycle===2022,key=`${cycle}:${d}`,status:IdentityStatus=key==="2022:08"||key==="2024:07"||key==="2024:10"?"proposed_identity_link":key==="2024:11"?"reported_contest_no_current_incumbent_match":"official_result_absent_identity_unassessed",present=status!=="official_result_absent_identity_unassessed";return!exact(r,ROW)||r.observationId!==expected[i]||r.identityObservationId!==`va:identity:${cycle}:${d}`||r.identityStatus!==status||r.cycleYear!==cycle||r.districtCode!==d||r.seatCycleId!==`seat_house_va_${d}_current`||r.targetCd119Geoid!==`51${d}`||r.historicalGeoid!==`51${d}`||r.historicalCongressSession!==(continuity?"118":"119")||r.compatibilityDisposition!==(continuity?"official_no_plan_change_declaration_same_geoid_key_candidate":"same_cd119_session_and_geoid_exact_key_candidate")||r.evidenceClass!==(continuity?"direct_official_plan_continuity_and_derived_key":"derived_exact_session_and_key")||(present?(r.resultAuthorityStatus!=="official_result_retained"||r.certificationStatus!=="event_level_board_certification_retained_no_individual_certificate"||r.sourceWinnerStatus!==(cycle===2022?"not_marked_by_source":"marked_by_source")):(r.contestId!==null||r.contestSha256!==null||r.resultAuthorityStatus!==null||r.certificationStatus!==null||r.sourceWinnerStatus!=="not_applicable_no_reported_contest"))||!r.compatibilityCandidate||r.compatibilityApproved||r.identityApproved||!r.identityDispositionPreserved||r.evaluatorUse!=="excluded_pending_identity_historical_geography_disposition_review_and_publication_approval"||r.scoreEligible||rowSha256!==digest("dsa-seats:va-primary-geography-row:v1\0",u)});
  if(!exact(value,TOP)||value.schema!=="virginia-primary-geography-compatibility-candidate-v1"||value.version!==1||value.generatedAt!=="2026-08-06T15:30:00.000Z"||value.sourceCutoff!=="2026-08-05"||!value.reviewerOnly||value.publicationEligible||canonicalJson(value.review)!==canonicalJson(review)||canonicalJson(value.summary)!==canonicalJson(summary)||value.rawTigerGeometryEqualityAssessed||digest("dsa-seats:va-primary-geography-source-set:v1\0",value.sources)!==SOURCE_SET||value.parentProjectionSha256!==digest("dsa-seats:va-primary-geography-parent-projection:v1\0",projection(value.rows))||value.rowSetSha256!==digest("dsa-seats:va-primary-geography-row-set:v1\0",value.rows)||(SET&&value.rowSetSha256!==SET)||(PACKAGE&&packageSha256!==PACKAGE)||packageSha256!==digest("dsa-seats:va-primary-geography-package:v1\0",unsigned)||invalid)fail();return value;
}
