/* eslint-disable @typescript-eslint/no-explicit-any -- immutable JSON parents are file-, package-, and validator-bound */
import { createHash } from "node:crypto";
import { canonicalJson } from "../fec/aipac-proposed-packages";
import { validateHouseDemocraticPrimarySourceSelectionProposal } from "./house-democratic-primary-source-selection-proposal";
import { validateVirginiaCurrentIncumbentPrimaryLinkageCandidate } from "./virginia-current-incumbent-primary-linkage-candidate";
import { validateVirginiaPrimaryGeographyCandidate } from "./virginia-primary-geography-compatibility-candidate";

type Input={proposalJson:string;identityJson:string;geographyJson:string;sourceLockJson:string};
type Category="identity_and_geography_candidates"|"geography_candidate_identity_no_match"|"geography_candidate_identity_unassessed";
type RecordRow={recordId:string;identityObservationId:string;identityRowSha256:string;geographyObservationId:string;geographyRowSha256:string;cycleYear:2022|2024;districtCode:string;seatCycleId:string;contestId:string|null;contestSha256:string|null;identityStatus:"proposed_identity_link"|"reported_contest_no_current_incumbent_match"|"official_result_absent_identity_unassessed";identityEvidenceClass:"exact_name_observation"|"derived_name_relationship"|null;sourceWinnerStatus:"marked_by_source"|"not_marked_by_source"|"not_applicable_no_reported_contest";historicalCongressSession:"118"|"119";compatibilityDisposition:string;geographyEvidenceClass:"direct_official_plan_continuity_and_derived_key"|"derived_exact_session_and_key";resultAuthorityStatus:"official_result_retained"|null;certificationStatus:"event_level_board_certification_retained_no_individual_certificate"|null;nominationConclusion:null;resultConclusion:null;reviewCategory:Category;identityCandidate:boolean;geographyCandidate:true;identityApproved:false;geographyApproved:false;jointApproved:false;progressiveClassificationStatus:"not_retained";evaluatorUse:"excluded_pending_authority_identity_geography_disposition_classification_and_publication_review";scoreEligible:false;recordSha256:string};
type Decision={decisionId:string;affectedComponent:string;parentDecisionId:string;question:string;recommendedDecision:string;defaultReversibleAssumption:"exclude_affected_records_from_evaluator_and_publication";alternatives:readonly[string,string];consequences:readonly[string,string];confidence:"high";evidenceRecordIds:string[];blocksAffectedPublication:true;blocksOtherWork:false;workCompletedWhileWaiting:string;review:typeof review};
export type VirginiaPrimaryJointReviewPackage=ReturnType<typeof buildVirginiaPrimaryJointReviewPackage>;

const FILES={proposal:"85246e9adfd181e6f24606b6eaa29250c45c9e8e42a6dd5af5cb162de17f45b1",identity:"ca318b9782f8c42813497a991dc151ecf07841aee3cde7aa6a310b521c53fa56",geography:"b4309ff23ab9b32fe6be76705b5fce436b2228abb64cc86860ae2c3ac39df23c"} as const;
const PACKAGES={identity:"6090c0d73dff58746d56bef48252b561bef2eedf4cb4ab390e0799071c97da52",identitySet:"017958f7adad4054c58e8069ee856a29d8cb265f0e237deebdfb1b97c9d0f778",geography:"0a470c2b402997e778c08f7b93c8ded614a41f053ea6e990f1af05fb25121920",geographySet:"5a191d63d50302b35e8e3f323fc3628dad11cb6c6eabf591d46c2260e0b36f69"} as const;
const parentIds=["house-democratic-primary-source-selection-proposal-20260804-v1","virginia-current-incumbent-primary-linkage-candidate-v1","virginia-primary-geography-compatibility-candidate-v1"] as const;
const SOURCE_SET="46555001164da894a4e01b2e636d9d901a22f2b8401fd8980f51fccdb90b394b";const RECORD_SET="598c7c95b91b2c2e7c70ae26255e2e202b6555714b60e3b1895fd9f3bfcd2483";const DECISION_SET="011978792c08ec2d2d0750ea9d08de5e910422f2f969a39bb733fd17ac4914fb";const PACKAGE="a5588e14fc266549f7ac6871d4f6235f2855992cd7df4d9471f8881ae6ab07e0";
const OUTPUT={id:"virginia-primary-identity-geography-review-package-v1",url:"urn:dsa-seats:virginia-primary-identity-geography-review-package:v1:2026-08-06",path:"data/metadata/virginia-primary-identity-geography-review-package-v1.json",bytes:30_979,sha256:"2b3c67da9ed5cc8833ee1dc2bf4139edb7757b6e80d3533b93ffd1914cc12af8",parents:[...parentIds]} as const;
const review={status:"proposed" as const,reviewer:null,reviewedAt:null,resolution:null};
const summary={reviewRecords:12 as const,bothCandidates:3 as const,geographyCandidateIdentityNoMatch:1 as const,geographyCandidateIdentityUnassessed:8 as const,officialAuthorityRecords:4 as const,identityCandidates:3 as const,geographyCandidates:12 as const,proposedDecisions:5 as const,jointApprovedRecords:0 as const,scoreEligibleRecords:0 as const};
const sha=(v:string)=>createHash("sha256").update(v,"utf8").digest("hex");
const digest=(d:string,v:unknown)=>createHash("sha256").update(d,"ascii").update(canonicalJson(v),"utf8").digest("hex");
const fail=():never=>{throw new Error("VA_PRIMARY_JOINT_REVIEW_INVALID")};
const parse=(v:string)=>{try{return JSON.parse(v)}catch{return fail()}};
const exact=(v:object,keys:readonly string[])=>canonicalJson(Object.keys(v).sort())===canonicalJson([...keys].sort());
const RECORD_KEYS=["certificationStatus","compatibilityDisposition","contestId","contestSha256","cycleYear","districtCode","evaluatorUse","geographyApproved","geographyCandidate","geographyEvidenceClass","geographyObservationId","geographyRowSha256","historicalCongressSession","identityApproved","identityCandidate","identityEvidenceClass","identityObservationId","identityRowSha256","identityStatus","jointApproved","nominationConclusion","progressiveClassificationStatus","recordId","recordSha256","resultAuthorityStatus","resultConclusion","reviewCategory","scoreEligible","seatCycleId","sourceWinnerStatus"] as const;
const TOP_KEYS=["decisionSetSha256","decisions","defaultUse","generatedAt","inheritedDecisionResolutions","methodology","packageSha256","publicationEligible","recordSetSha256","records","review","reviewerOnly","schema","sourceCutoff","sources","summary","version"] as const;

export function buildVirginiaPrimaryJointReviewPackage(input:Input){
 if(sha(input.proposalJson)!==FILES.proposal||sha(input.identityJson)!==FILES.identity||sha(input.geographyJson)!==FILES.geography)fail();
 const proposal=validateHouseDemocraticPrimarySourceSelectionProposal(parse(input.proposalJson)),identity=validateVirginiaCurrentIncumbentPrimaryLinkageCandidate(parse(input.identityJson)),geography=validateVirginiaPrimaryGeographyCandidate(parse(input.geographyJson)),lock=parse(input.sourceLockJson);
 if(identity.packageSha256!==PACKAGES.identity||identity.observationSetSha256!==PACKAGES.identitySet||geography.packageSha256!==PACKAGES.geography||geography.rowSetSha256!==PACKAGES.geographySet||["collect-official-state-primary-results-and-certification-v1","approve-historic-primary-candidate-identity-resolution-v1","approve-historical-district-cd119-compatibility-v1","decide-nonstandard-primary-disposition-treatment-v1","approve-progressive-candidate-classification-method-v1"].some(id=>proposal.decisions.find(d=>d.decisionId===id)?.resolution!==null))fail();
 const sources=parentIds.map(id=>{const matches=lock.entries?.filter((e:any)=>e.id===id)??[];if(matches.length!==1)fail();return matches[0]});if(digest("dsa-seats:va-primary-joint-source-set:v1\0",sources)!==SOURCE_SET)fail();const outputs=lock.entries?.filter((e:any)=>e.id===OUTPUT.id)??[];if(outputs.length!==1||outputs[0].url!==OUTPUT.url||outputs[0].retainedPath!==OUTPUT.path||outputs[0].retainedStatus!=="retained"||outputs[0].byteSize!==OUTPUT.bytes||outputs[0].sha256!==OUTPUT.sha256||outputs[0].kind!=="review_proposal"||canonicalJson(outputs[0].parentIds)!==canonicalJson(OUTPUT.parents))fail();
 const records:RecordRow[]=geography.rows.map(g=>{const matches=identity.observations.filter(i=>i.observationId===g.identityObservationId);if(matches.length!==1)fail();const i=matches[0]!;if(g.identityRowSha256!==i.rowSha256||g.identityStatus!==i.identityStatus||g.contestId!==i.contestId||g.contestSha256!==i.contestSha256||g.cycleYear!==i.cycleYear||g.districtCode!==i.districtCode||g.seatCycleId!==i.seatCycleId)fail();const candidate=i.identityStatus==="proposed_identity_link",category:Category=candidate?"identity_and_geography_candidates":i.identityStatus==="reported_contest_no_current_incumbent_match"?"geography_candidate_identity_no_match":"geography_candidate_identity_unassessed";const unsigned={recordId:`va-primary-joint:${i.cycleYear}:${i.districtCode}`,identityObservationId:i.observationId,identityRowSha256:i.rowSha256,geographyObservationId:g.observationId,geographyRowSha256:g.rowSha256,cycleYear:i.cycleYear,districtCode:i.districtCode,seatCycleId:i.seatCycleId,contestId:i.contestId,contestSha256:i.contestSha256,identityStatus:i.identityStatus,identityEvidenceClass:i.evidenceClass,sourceWinnerStatus:g.sourceWinnerStatus,historicalCongressSession:g.historicalCongressSession,compatibilityDisposition:g.compatibilityDisposition,geographyEvidenceClass:g.evidenceClass,resultAuthorityStatus:g.resultAuthorityStatus,certificationStatus:g.certificationStatus,nominationConclusion:null,resultConclusion:null,reviewCategory:category,identityCandidate:candidate,geographyCandidate:true as const,identityApproved:false as const,geographyApproved:false as const,jointApproved:false as const,progressiveClassificationStatus:"not_retained" as const,evaluatorUse:"excluded_pending_authority_identity_geography_disposition_classification_and_publication_review" as const,scoreEligible:false as const};return{...unsigned,recordSha256:digest("dsa-seats:va-primary-joint-row:v1\0",unsigned)}});
 const all=records.map(r=>r.recordId),official=records.filter(r=>r.resultAuthorityStatus!==null).map(r=>r.recordId),candidates=records.filter(r=>r.identityCandidate).map(r=>r.recordId);const decision=(decisionId:string,component:string,parentDecisionId:string,evidenceRecordIds:string[],recommendedDecision:string,work:string):Decision=>({decisionId,affectedComponent:component,parentDecisionId,question:`Review ${component} independently for the scoped Virginia records.`,recommendedDecision,defaultReversibleAssumption:"exclude_affected_records_from_evaluator_and_publication",alternatives:["accept_scoped_candidate_evidence","retain_exclusion_or_request_correction"],consequences:["accepted evidence remains separately gated from publication","nonacceptance preserves current exclusion without blocking other work"],confidence:"high",evidenceRecordIds,blocksAffectedPublication:true,blocksOtherWork:false,workCompletedWhileWaiting:work,review});
 const decisions=[decision("va-primary:accept-official-result-authority-v1","official result authority","collect-official-state-primary-results-and-certification-v1",official,"accept_event_level_certified_result_authority_without_claiming_individual_certificates","Four target contests retain official result and event-level certification evidence; eight absent rows are excluded."),decision("va-primary:accept-geography-compatibility-v1","historical geography compatibility","approve-historical-district-cd119-compatibility-v1",all,"accept_twelve_geography_candidates_without_geometry_equality_claim","Complete CD118/CD119 inventories and Census no-redraw authority are retained."),decision("va-primary:accept-identity-links-v1","candidate identity links","approve-historic-primary-candidate-identity-resolution-v1",candidates,"accept_three_name_relationships_and_preserve_no_match_and_unassessed_rows","Two exact and one finite derived identity candidates are retained."),decision("va-primary:retain-primary-disposition-exclusion-v1","primary disposition treatment","decide-nonstandard-primary-disposition-treatment-v1",all,"retain_reported_no_match_and_absent_distinctions_pending_review","Absence remains nonnumeric and VA-11 remains a predecessor no-match."),decision("va-primary:retain-progressive-classification-exclusion-v1","progressive classification","approve-progressive-candidate-classification-method-v1",all,"retain_all_records_outside_progressive_classification_until_separate_evidence","No progressive classification evidence is introduced by this join.")];
 const unsigned={schema:"virginia-primary-identity-geography-review-package-v1" as const,version:1 as const,generatedAt:"2026-08-06T16:30:00.000Z" as const,sourceCutoff:"2026-08-05" as const,reviewerOnly:true as const,publicationEligible:false as const,defaultUse:"exclude_from_evaluator_until_independent_decisions_and_publication_review" as const,review,methodology:{decisionsReviewedIndependently:true as const,jointPackageApprovesParents:false as const,automaticApprovals:0 as const,evaluatorNumericValues:0 as const,unofficial2026Rows:0 as const,rawTigerGeometryEqualityAssessed:false as const,overlapAssessed:false as const,populationEquivalenceAssessed:false as const},sources,summary,records,recordSetSha256:digest("dsa-seats:va-primary-joint-row-set:v1\0",records),decisions,decisionSetSha256:digest("dsa-seats:va-primary-joint-decision-set:v1\0",decisions),inheritedDecisionResolutions:{authority:null,identity:null,geography:null,disposition:null,progressiveClassification:null}};return{...unsigned,packageSha256:digest("dsa-seats:va-primary-joint-package:v1\0",unsigned)};
}

export function validateVirginiaPrimaryJointReviewPackage(value:VirginiaPrimaryJointReviewPackage){
 const {packageSha256,...unsigned}=value,ids=value.records.map(r=>r.recordId),official=value.records.filter(r=>r.resultAuthorityStatus!==null).map(r=>r.recordId),candidates=value.records.filter(r=>r.identityCandidate).map(r=>r.recordId);if(!exact(value,TOP_KEYS)||value.schema!=="virginia-primary-identity-geography-review-package-v1"||value.version!==1||value.generatedAt!=="2026-08-06T16:30:00.000Z"||value.sourceCutoff!=="2026-08-05"||!value.reviewerOnly||value.publicationEligible||canonicalJson(value.review)!==canonicalJson(review)||canonicalJson(value.summary)!==canonicalJson(summary)||value.records.length!==12||value.decisions.length!==5||value.records.some(r=>{const{recordSha256,...u}=r,key=`${r.cycleYear}:${r.districtCode}`,status=key==="2022:08"||key==="2024:07"||key==="2024:10"?"proposed_identity_link":key==="2024:11"?"reported_contest_no_current_incumbent_match":"official_result_absent_identity_unassessed",category:Category=status==="proposed_identity_link"?"identity_and_geography_candidates":status==="reported_contest_no_current_incumbent_match"?"geography_candidate_identity_no_match":"geography_candidate_identity_unassessed";return!exact(r,RECORD_KEYS)||r.recordId!==`va-primary-joint:${r.cycleYear}:${r.districtCode}`||r.identityStatus!==status||r.reviewCategory!==category||r.identityCandidate!==(status==="proposed_identity_link")||!r.geographyCandidate||r.identityApproved||r.geographyApproved||r.jointApproved||r.scoreEligible||r.progressiveClassificationStatus!=="not_retained"||recordSha256!==digest("dsa-seats:va-primary-joint-row:v1\0",u)})||value.decisions.some(d=>canonicalJson(d.review)!==canonicalJson(review))||canonicalJson(value.decisions.map(d=>[d.decisionId,d.evidenceRecordIds.length]))!==canonicalJson([["va-primary:accept-official-result-authority-v1",4],["va-primary:accept-geography-compatibility-v1",12],["va-primary:accept-identity-links-v1",3],["va-primary:retain-primary-disposition-exclusion-v1",12],["va-primary:retain-progressive-classification-exclusion-v1",12]])||canonicalJson(value.decisions[0]!.evidenceRecordIds)!==canonicalJson(official)||canonicalJson(value.decisions[2]!.evidenceRecordIds)!==canonicalJson(candidates)||[value.decisions[1]!,value.decisions[3]!,value.decisions[4]!].some(d=>canonicalJson(d.evidenceRecordIds)!==canonicalJson(ids))||value.recordSetSha256!==digest("dsa-seats:va-primary-joint-row-set:v1\0",value.records)||value.decisionSetSha256!==digest("dsa-seats:va-primary-joint-decision-set:v1\0",value.decisions)||(RECORD_SET&&value.recordSetSha256!==RECORD_SET)||(DECISION_SET&&value.decisionSetSha256!==DECISION_SET)||(PACKAGE&&packageSha256!==PACKAGE)||packageSha256!==digest("dsa-seats:va-primary-joint-package:v1\0",unsigned))fail();return value;
}
