import { createHash } from "node:crypto";

import { canonicalJson } from "../fec/aipac-proposed-packages";
import { validateDsaTargetIncumbentRoster } from "../identity/incumbent-tenure-factual-candidate";
import { validateHouseDemocraticPrimarySourceSelectionProposal } from "./house-democratic-primary-source-selection-proposal";
import { validateWashingtonHouseTopTwoResultsReceipt } from "./washington-house-top-two-results-receipt";

export const WASHINGTON_TOP_TWO_IDENTITY_V1 = "washington-current-incumbent-top-two-linkage-candidate-v1" as const;
export const WASHINGTON_TOP_TWO_IDENTITY_ROW_SET_SHA256 = "5be84bd55abebdaf647b95727db0b324d4a70fc0167c7a08478a0a35246267ae";
export const WASHINGTON_TOP_TWO_IDENTITY_PACKAGE_SHA256 = "8ef11d58375a07018cdf05bffce1b68777c1d013149a3d292c69c7e52cd1db11";
const INPUTS = {
  rosterFile: "8ae9bb3423e6160d00b5395186c42550e28811b817a482650875d87de71079e1", rosterPackage: "cf068848595dee99882ae74a6bef2b76061597fe0daa3c86b30c71bdcae18fee",
  proposalFile: "85246e9adfd181e6f24606b6eaa29250c45c9e8e42a6dd5af5cb162de17f45b1", proposalPackage: "a090e0be03dc2b0fa5edd0c1132a8261eed0f98ceb4df090154d0b150d8721fb",
  houseFile: "4ccea8259aff2df6a175545e45bdac2dfcdf0085a9cc7ab6c46aa80527bc524b", congressFile: "bc48cccd12df96164e5a2415fc41e838ca255fe85c297731515529692f7982cf",
  receiptFile: "eac5df760de11a6612c2e8a95374a8041b2debb94068e0d08afadecd775963da", receiptPackage: "a930a28888f3892f0b4459063b0d0a2c195bfada26960b705757124a403e5e13", receiptSet: "30fbbe0795413030a49fb366375c9898e97e7f778a5441e9785fcddd36b2a259",
} as const;
const TARGETS = [["01", "D000617", "Suzan K. DelBene"], ["02", "L000560", "Rick Larsen"], ["03", "G000600", "Marie Gluesenkamp Perez"], ["06", "R000621", "Emily Randall"], ["07", "J000298", "Pramila Jayapal"], ["08", "S001216", "Kim Schrier"], ["09", "S000510", "Adam Smith"], ["10", "S001159", "Marilyn Strickland"]] as const;
const LOCK_PARENTS = {
  roster: ["congress-legislators-current-20260804", "dsa-target-factual-projection-20260804-v1"], proposal: ["dsa-target-factual-projection-20260804-v1", "dsa-target-incumbent-roster-20260804-v1", "fec-2026-congressional-primary-dates", "geo-national-cd119"], house: [], congress: [],
  receipt: ["wa-2022-house-primary-results", "wa-2024-house-primary-results", "wa-2022-primary-certification", "wa-2024-primary-certification", "house-democratic-primary-source-selection-proposal-20260804-v1"],
} as const;
const OUTPUT_PARENTS = ["dsa-target-incumbent-roster-20260804-v1", "house-democratic-primary-source-selection-proposal-20260804-v1", "house-xml", "congress-legislators-current-20260804", "washington-house-top-two-results-receipt-20220802-20240806-v1"] as const;
const OUTPUT_FILE_SHA256 = "d8abddb956831e60487d65cf4b26fec5112032737be73f547d12af7338961093";
const OUTPUT_BYTE_SIZE = 34961;
type MatchMethod = "exact_normalized_official_house_name_same_district" | "derived_official_middle_initial_not_in_source_name_same_district";
type Observation = Readonly<{ observationId: string; contestId: string; contestSha256: string; cycleYear: 2022 | 2024; electionDate: "2022-08-02" | "2024-08-06"; seatCycleId: string; districtCode: string; rosterIdentity: Readonly<{ bioguideId: string; officialHouseName: string; officialHouseMemberDataSha256: typeof INPUTS.houseFile }>; sourceCandidateCount: number; reportedContestVotes: number; sourceCandidate: Readonly<{ sourceCandidateName: string; partyPreference: string | null; votes: number; rowIdentity: string }> | null; identityStatus: "proposed_identity_link" | "reported_contest_no_unique_candidate_match"; matchMethod: MatchMethod | null; evidenceClass: "exact_name_observation" | "derived_name_relationship" | null; confidence: "high" | null; certificationStatus: "certified"; nominationSystem: "top_two"; formulaApplicability: "confirmed_incompatible"; sourceWinnerStatus: "not_established"; identityApproved: false; selected: false; selectionStatus: "unselected_top_two_source_does_not_establish_nomination_winner_or_advancement"; evaluatorUse: "excluded_formula_incompatible_top_two_pending_identity_geography_review_and_publication_approval"; scoreEligible: false; rationaleCodes: readonly string[]; rowSha256: string }>;
export type WashingtonTopTwoIdentityCandidate = Readonly<{ schema: typeof WASHINGTON_TOP_TWO_IDENTITY_V1; version: 1; generatedAt: "2026-08-06T15:00:00.000Z"; sourceCutoff: "2026-08-05"; reviewerOnly: true; publicationEligible: false; defaultUse: "exclude_from_partisan_primary_evaluator_formula_incompatible_top_two"; review: Readonly<{ status: "proposed"; reviewer: null; reviewedAt: null; resolution: null }>; inputs: Readonly<Record<string, unknown>>; methodology: Readonly<Record<string, unknown>>; summary: Readonly<{ targetSeats: 8; contestObservations: 16; reportedCandidateRows: number; reportedContestVotes: number; proposedIdentityLinks: number; exactNameObservations: number; derivedNameRelationships: number; reportedContestNoUniqueMatch: number; directIdentifierBridges: 0; automaticallyApprovedRows: 0; selectedRows: 0; scoreEligibleRows: 0 }>; observations: readonly Observation[]; observationSetSha256: string; decisionSupport: Readonly<Record<string, unknown>>; packageSha256: string }>;
export type WashingtonTopTwoIdentityInput = Readonly<{ rosterJson: string; proposalJson: string; houseXml: string; congressJson: string; receiptJson: string; sourceLockJson: string }>;
const sha = (value: string): string => createHash("sha256").update(value).digest("hex");
const digest = (domain: string, value: unknown): string => createHash("sha256").update(domain, "ascii").update(canonicalJson(value), "utf8").digest("hex");
const order = (left: string, right: string): number => Buffer.compare(Buffer.from(left), Buffer.from(right));
const fail = (code: string): never => { throw new Error(`Washington top-two identity rejected: ${code}`); };
const parse = (value: string, code: string): unknown => { try { return JSON.parse(value); } catch { return fail(code); } };
const tag = (block: string, name: string): string => block.match(new RegExp(`<${name}>([^<]*)</${name}>`))?.[1] ?? "";

export function buildWashingtonTopTwoIdentityCandidate(input: WashingtonTopTwoIdentityInput): WashingtonTopTwoIdentityCandidate {
  if (sha(input.rosterJson) !== INPUTS.rosterFile || sha(input.proposalJson) !== INPUTS.proposalFile || sha(input.houseXml) !== INPUTS.houseFile || sha(input.congressJson) !== INPUTS.congressFile || sha(input.receiptJson) !== INPUTS.receiptFile) fail("INPUT_HASH_MISMATCH");
  const roster = validateDsaTargetIncumbentRoster(parse(input.rosterJson, "ROSTER_JSON_INVALID")); const proposal = validateHouseDemocraticPrimarySourceSelectionProposal(parse(input.proposalJson, "PROPOSAL_JSON_INVALID")); const receipt = validateWashingtonHouseTopTwoResultsReceipt(parse(input.receiptJson, "RECEIPT_JSON_INVALID") as Parameters<typeof validateWashingtonHouseTopTwoResultsReceipt>[0]);
  if (roster.rosterSha256 !== INPUTS.rosterPackage || proposal.packageSha256 !== INPUTS.proposalPackage || receipt.packageSha256 !== INPUTS.receiptPackage || receipt.summary.contestSetSha256 !== INPUTS.receiptSet || receipt.nominationSystem !== "top_two" || receipt.formulaApplicability !== "confirmed_incompatible" || receipt.certificationStatus !== "certified" || proposal.decisions.find((row) => row.decisionId === "approve-historic-primary-candidate-identity-resolution-v1")?.resolution !== null) fail("PARENT_INVALID");
  const people = parse(input.congressJson, "CONGRESS_JSON_INVALID") as Array<{ id?: { bioguide?: string }; name?: { official_full?: string } }>; if (!Array.isArray(people)) fail("IDENTITY_SOURCE_INVALID");
  const blocks = [...input.houseXml.matchAll(/<member>([\s\S]*?)<\/member>/g)].map((match) => match[1]!);
  const lock = parse(input.sourceLockJson, "SOURCE_LOCK_JSON_INVALID") as { entries?: Array<{ id: string; retainedPath?: string; retainedStatus: string; byteSize?: number; sha256: string; kind: string; parentIds?: string[] }> };
  const required = [["dsa-target-incumbent-roster-20260804-v1", INPUTS.rosterFile, "data/metadata/dsa-target-incumbent-roster-20260804-v1.json", "production_projection_receipt", LOCK_PARENTS.roster], ["house-democratic-primary-source-selection-proposal-20260804-v1", INPUTS.proposalFile, "data/metadata/house-democratic-primary-source-selection-proposal-20260804-v1.json", "review_proposal", LOCK_PARENTS.proposal], ["house-xml", INPUTS.houseFile, "data/source/identity/house-member-data.xml", "source", LOCK_PARENTS.house], ["congress-legislators-current-20260804", INPUTS.congressFile, "data/source/identity/congress-legislators-current-20260804.json", "source", LOCK_PARENTS.congress], ["washington-house-top-two-results-receipt-20220802-20240806-v1", INPUTS.receiptFile, "data/metadata/washington-house-top-two-results-receipt-20220802-20240806-v1.json", "review_proposal", LOCK_PARENTS.receipt]] as const;
  const entries: NonNullable<typeof lock.entries> = lock.entries ?? fail("SOURCE_LOCK_MISMATCH"); if (required.some(([id, hash, path, kind, parents]) => { const rows = entries.filter((entry) => entry.id === id); return rows.length !== 1 || rows[0]!.sha256 !== hash || rows[0]!.retainedPath !== path || rows[0]!.retainedStatus !== "retained" || rows[0]!.kind !== kind || canonicalJson(rows[0]!.parentIds) !== canonicalJson(parents); })) fail("SOURCE_LOCK_MISMATCH");
  const output = entries.filter((entry) => entry.id === WASHINGTON_TOP_TWO_IDENTITY_V1); if (!OUTPUT_FILE_SHA256) { if (output.length) fail("SOURCE_LOCK_MISMATCH"); } else if (output.length !== 1 || output[0]!.retainedPath !== "data/metadata/washington-current-incumbent-top-two-linkage-candidate-v1.json" || output[0]!.retainedStatus !== "retained" || output[0]!.byteSize !== OUTPUT_BYTE_SIZE || output[0]!.sha256 !== OUTPUT_FILE_SHA256 || output[0]!.kind !== "review_candidate" || canonicalJson(output[0]!.parentIds) !== canonicalJson(OUTPUT_PARENTS)) fail("SOURCE_LOCK_MISMATCH");
  const observations: Observation[] = [];
  for (const [districtCode, bioguideId, officialName] of TARGETS) {
    const member = blocks.filter((block) => tag(block, "bioguideID") === bioguideId), currentPeople = people.filter((person) => person.id?.bioguide === bioguideId);
    if (roster.rows.filter((row) => row.seatCycleId === `seat_house_wa_${districtCode}_current` && row.bioguideId === bioguideId).length !== 1 || member.length !== 1 || tag(member[0]!, "statedistrict") !== `WA${districtCode}` || tag(member[0]!, "official-name") !== officialName || currentPeople.length !== 1 || currentPeople[0]!.name?.official_full !== officialName) fail("OFFICIAL_IDENTITY_CLOSURE_INVALID");
    for (const cycleYear of [2022, 2024] as const) {
      const contestRows = receipt.contests.filter((row) => row.cycleYear === cycleYear && row.districtCode === String(Number(districtCode))); if (contestRows.length !== 1) fail("CONTEST_PARTITION_INVALID"); const contest = contestRows[0]!;
      const noMatch = cycleYear === 2022 && districtCode === "06", sourceName = districtCode === "01" ? "Suzan DelBene" : officialName;
      const matches = noMatch ? [] : contest.candidates.filter((row) => row.candidateName === sourceName && !row.isWriteIn); if ((!noMatch && matches.length !== 1) || (noMatch && contest.candidates.some((row) => row.candidateName === officialName))) fail("SOURCE_CANDIDATE_IDENTITY_INVALID");
      const source = matches[0], method: MatchMethod | null = noMatch ? null : districtCode === "01" ? "derived_official_middle_initial_not_in_source_name_same_district" : "exact_normalized_official_house_name_same_district";
      const sourceCandidate = source ? { sourceCandidateName: source.candidateName, partyPreference: source.partyPreference, votes: source.votes, rowIdentity: digest("dsa-seats:wa-top-two-identity-source-candidate:v1\0", { contestId: contest.contestId, contestSha256: contest.contestSha256, ...source }) } : null;
      const unsigned = { observationId: `wa:identity:${cycleYear}:${districtCode}`, contestId: contest.contestId, contestSha256: contest.contestSha256, cycleYear, electionDate: cycleYear === 2022 ? "2022-08-02" as const : "2024-08-06" as const, seatCycleId: `seat_house_wa_${districtCode}_current`, districtCode, rosterIdentity: { bioguideId, officialHouseName: officialName, officialHouseMemberDataSha256: INPUTS.houseFile }, sourceCandidateCount: contest.candidates.length, reportedContestVotes: contest.contestTotalVotes, sourceCandidate, identityStatus: noMatch ? "reported_contest_no_unique_candidate_match" as const : "proposed_identity_link" as const, matchMethod: method, evidenceClass: noMatch ? null : districtCode === "01" ? "derived_name_relationship" as const : "exact_name_observation" as const, confidence: noMatch ? null : "high" as const, certificationStatus: "certified" as const, nominationSystem: "top_two" as const, formulaApplicability: "confirmed_incompatible" as const, sourceWinnerStatus: "not_established" as const, identityApproved: false as const, selected: false as const, selectionStatus: "unselected_top_two_source_does_not_establish_nomination_winner_or_advancement" as const, evaluatorUse: "excluded_formula_incompatible_top_two_pending_identity_geography_review_and_publication_approval" as const, scoreEligible: false as const, rationaleCodes: noMatch ? ["reported_contest_no_unique_current_incumbent_candidate_match", "predecessor_candidate_not_cross_linked", "top_two_does_not_establish_nomination_winner_or_advancement", "formula_incompatible"] : [method!, "same_district_and_cycle", "finite_audited_name_relationship", "party_preference_not_nomination_or_endorsement", "top_two_does_not_establish_nomination_winner_or_advancement", "formula_incompatible"] };
      observations.push({ ...unsigned, rowSha256: digest("dsa-seats:wa-top-two-identity-row:v1\0", unsigned) });
    }
  }
  observations.sort((left, right) => order(left.observationId, right.observationId)); const observationSetSha256 = digest("dsa-seats:wa-top-two-identity-row-set:v1\0", observations);
  const unsigned = { schema: WASHINGTON_TOP_TWO_IDENTITY_V1, version: 1 as const, generatedAt: "2026-08-06T15:00:00.000Z" as const, sourceCutoff: "2026-08-05" as const, reviewerOnly: true as const, publicationEligible: false as const, defaultUse: "exclude_from_partisan_primary_evaluator_formula_incompatible_top_two" as const, review: { status: "proposed" as const, reviewer: null, reviewedAt: null, resolution: null }, inputs: { roster: { sourceLockId: required[0][0], fileSha256: INPUTS.rosterFile, packageSha256: INPUTS.rosterPackage }, proposal: { sourceLockId: required[1][0], fileSha256: INPUTS.proposalFile, packageSha256: INPUTS.proposalPackage }, houseClerk: { sourceLockId: required[2][0], fileSha256: INPUTS.houseFile }, congressLegislators: { sourceLockId: required[3][0], fileSha256: INPUTS.congressFile }, receipt: { sourceLockId: required[4][0], fileSha256: INPUTS.receiptFile, packageSha256: INPUTS.receiptPackage, contestSetSha256: INPUTS.receiptSet } }, methodology: { scope: "eight_current_washington_target_seats_times_two_certified_top_two_cycles", matchTreatment: "finite_exact_and_middle_initial_relationships_no_fuzzy_matching", nominationTreatment: "party_preference_is_not_nomination_or_endorsement", sourceWinnerTreatment: "not_established", formulaApplicability: "confirmed_incompatible", automaticDecisionClosure: false, evaluatorNumericValues: 0 }, summary: { targetSeats: 8 as const, contestObservations: 16 as const, reportedCandidateRows: observations.reduce((sum, row) => sum + row.sourceCandidateCount, 0), reportedContestVotes: observations.reduce((sum, row) => sum + row.reportedContestVotes, 0), proposedIdentityLinks: observations.filter((row) => row.identityStatus === "proposed_identity_link").length, exactNameObservations: observations.filter((row) => row.evidenceClass === "exact_name_observation").length, derivedNameRelationships: observations.filter((row) => row.evidenceClass === "derived_name_relationship").length, reportedContestNoUniqueMatch: observations.filter((row) => row.identityStatus === "reported_contest_no_unique_candidate_match").length, directIdentifierBridges: 0 as const, automaticallyApprovedRows: 0 as const, selectedRows: 0 as const, scoreEligibleRows: 0 as const }, observations, observationSetSha256, decisionSupport: { decisionId: "approve-historic-primary-candidate-identity-resolution-v1", formulaDecisionId: "exclude-washington-top-two-from-partisan-primary-v01", status: "proposed", recommendedResolution: "accept_thirteen_exact_and_two_middle_initial_links_preserve_2022_wa06_no_match_and_formula_exclusion", reviewerResolution: null, reviewer: null, reviewedAt: null } };
  return { ...unsigned, packageSha256: digest("dsa-seats:wa-top-two-identity-candidate:v1\0", unsigned) };
}

export function validateWashingtonTopTwoIdentityCandidate(value: unknown): WashingtonTopTwoIdentityCandidate {
  if (typeof value !== "object" || value === null || Array.isArray(value)) fail("PACKAGE_SHAPE_INVALID"); const candidate = value as WashingtonTopTwoIdentityCandidate;
  const expected = { targetSeats: 8, contestObservations: 16, reportedCandidateRows: 115, reportedContestVotes: 3141178, proposedIdentityLinks: 15, exactNameObservations: 13, derivedNameRelationships: 2, reportedContestNoUniqueMatch: 1, directIdentifierBridges: 0, automaticallyApprovedRows: 0, selectedRows: 0, scoreEligibleRows: 0 };
  if (candidate.schema !== WASHINGTON_TOP_TWO_IDENTITY_V1 || candidate.version !== 1 || !candidate.reviewerOnly || candidate.publicationEligible || candidate.review.status !== "proposed" || candidate.review.reviewer !== null || candidate.review.reviewedAt !== null || candidate.review.resolution !== null || canonicalJson(candidate.summary) !== canonicalJson(expected) || candidate.observations.length !== 16 || candidate.observations.some((row) => row.identityApproved || row.selected || row.scoreEligible || row.certificationStatus !== "certified" || row.nominationSystem !== "top_two" || row.formulaApplicability !== "confirmed_incompatible" || row.sourceWinnerStatus !== "not_established")) fail("LIFECYCLE_INVALID");
  if (candidate.observations.some((row) => { const { rowSha256, ...unsigned } = row; return rowSha256 !== digest("dsa-seats:wa-top-two-identity-row:v1\0", unsigned); }) || candidate.observationSetSha256 !== digest("dsa-seats:wa-top-two-identity-row-set:v1\0", candidate.observations)) fail("ROW_INVALID"); const { packageSha256, ...unsigned } = candidate; if (packageSha256 !== digest("dsa-seats:wa-top-two-identity-candidate:v1\0", unsigned)) fail("PACKAGE_HASH_INVALID"); if (WASHINGTON_TOP_TWO_IDENTITY_ROW_SET_SHA256 && candidate.observationSetSha256 !== WASHINGTON_TOP_TWO_IDENTITY_ROW_SET_SHA256) fail("ROW_SET_IDENTITY_INVALID"); if (WASHINGTON_TOP_TWO_IDENTITY_PACKAGE_SHA256 && candidate.packageSha256 !== WASHINGTON_TOP_TWO_IDENTITY_PACKAGE_SHA256) fail("PACKAGE_IDENTITY_INVALID"); return candidate;
}
