import { createHash } from "node:crypto";

import { canonicalJson } from "../fec/aipac-proposed-packages";
import { validateFilingRunwayExceptionAuthorityProposal } from "./filing-runway-exception-authority-proposal";
import { validateHouseDemocraticPrimarySourceSelectionProposal } from "./house-democratic-primary-source-selection-proposal";
import { validateWashingtonTopTwoIdentityCandidate, type WashingtonTopTwoIdentityCandidate } from "./washington-current-incumbent-top-two-linkage-candidate";
import { validateWashingtonPrimaryGeographyCandidate, type WashingtonPrimaryGeographyCandidate } from "./washington-primary-geography-compatibility-candidate";

export const WASHINGTON_PRIMARY_JOINT_REVIEW_V1 = "washington-primary-identity-geography-review-package-v1" as const;
export const WASHINGTON_PRIMARY_JOINT_RECORD_SET_SHA256 = "eda33d9f555eb715deffb7625537bd442ccdfc166b7963b9d97acfe957d86e1f";
export const WASHINGTON_PRIMARY_JOINT_DECISION_SET_SHA256 = "44d619125b57e8b2a10446fddb84240dddc50f95222c33d66a8cc281b2d16013";
export const WASHINGTON_PRIMARY_JOINT_PACKAGE_SHA256 = "c7b6691c27756bc62a241015392fa5bf6a51ee8b5e806188ccfd172f8e1bc7a8";
const INPUTS = {
  proposalFile: "85246e9adfd181e6f24606b6eaa29250c45c9e8e42a6dd5af5cb162de17f45b1", proposalPackage: "a090e0be03dc2b0fa5edd0c1132a8261eed0f98ceb4df090154d0b150d8721fb",
  formulaFile: "8e6495526ac258233a1342840b0e2ac8bcbc5511ba127779126dc78a411982ec", formulaPackage: "f357157df143ab6ae95f2f50bda3b1e052876229646db2f42185080ccd97b513",
  identityFile: "d8abddb956831e60487d65cf4b26fec5112032737be73f547d12af7338961093", identityPackage: "8ef11d58375a07018cdf05bffce1b68777c1d013149a3d292c69c7e52cd1db11", identitySet: "5be84bd55abebdaf647b95727db0b324d4a70fc0167c7a08478a0a35246267ae",
  geographyFile: "393ce5c9394102686777e1a87ba6e63665ab617f6fd3d7c83dcea1392078389b", geographyPackage: "22e6eaf9d819c1939b3260cb7173cff576371344f2da75dd520d7b6c2d06d251", geographySet: "bf7bf88c3cd5030f56a326391e60c3ebea08dfc97c9430277a22e27bfc983d22",
} as const;
const PROPOSAL_PARENTS = ["dsa-target-factual-projection-20260804-v1", "dsa-target-incumbent-roster-20260804-v1", "fec-2026-congressional-primary-dates", "geo-national-cd119"] as const;
const FORMULA_PARENTS = ["house-filing-runway-authority-proposal-20260804-v1", "ct-2026-election-calendar", "wa-top-two-candidate-faq"] as const;
const IDENTITY_PARENTS = ["dsa-target-incumbent-roster-20260804-v1", "house-democratic-primary-source-selection-proposal-20260804-v1", "house-xml", "congress-legislators-current-20260804", "washington-house-top-two-results-receipt-20220802-20240806-v1"] as const;
const GEOGRAPHY_PARENTS = ["house-democratic-primary-source-selection-proposal-20260804-v1", "washington-house-top-two-results-receipt-20220802-20240806-v1", "washington-current-incumbent-top-two-linkage-candidate-v1", "census-cd119-plan-change-authority-20260805", "tiger-cd118-53", "tiger-cd119-53"] as const;
const OUTPUT_PARENTS = ["house-democratic-primary-source-selection-proposal-20260804-v1", "filing-runway-exception-authority-proposal-20260804-v1", "washington-current-incumbent-top-two-linkage-candidate-v1", "washington-primary-geography-compatibility-candidate-v1"] as const;
const OUTPUT_FILE_SHA256 = "127196d44d5d4f17420d74f61b2615e5bf2dcc4d4c057d1b0cabfc4cffa375cf";
const OUTPUT_BYTE_SIZE = 53_116;

type ReviewRecord = Readonly<{ reviewRecordId: string; identityObservationId: string; geographyObservationId: string; contestId: string; contestSha256: string; cycleYear: 2022 | 2024; electionDate: "2022-08-02" | "2024-08-06"; seatCycleId: string; districtCode: string; identity: Readonly<{ parentRowSha256: string; status: "candidate" | "unresolved"; identityStatus: "proposed_identity_link" | "reported_contest_no_unique_candidate_match"; bioguideId: string; officialHouseName: string; sourceCandidateName: string | null; evidenceClass: "exact_name_observation" | "derived_name_relationship" | null; confidence: "high" | null; candidate: boolean; approved: false }>; geography: Readonly<{ parentRowSha256: string; status: "candidate"; targetCd119Geoid: string; historicalCongressSession: "118" | "119"; historicalGeoid: string; evidenceClass: "direct_official_plan_continuity_and_derived_key" | "derived_exact_session_and_key"; confidence: "high"; compatibilityDisposition: string; candidate: true; approved: false }>; reviewCategory: "identity_and_geography_candidates" | "geography_candidate_identity_unresolved"; resultDispositionPreserved: true; certificationStatus: "certified"; nominationSystem: "top_two"; formulaApplicability: "confirmed_incompatible"; sourceWinnerStatus: "not_established"; progressiveClassificationStatus: "not_retained"; jointApproved: false; evaluatorUse: "excluded_formula_incompatible_top_two_pending_identity_geography_disposition_classification_review_and_publication_approval"; scoreEligible: false; reviewerAction: "review_identity_and_geography_independently" | "review_geography_while_preserving_identity_no_match"; rationaleCodes: readonly string[]; reviewRecordSha256: string }>;
type Decision = Readonly<{ decisionId: string; affectedComponent: string; parentDecisionId: string; question: string; recommendedDecision: string; defaultReversibleAssumption: "exclude_affected_records_from_evaluator_and_publication"; alternatives: readonly string[]; consequences: readonly string[]; confidence: "high"; evidenceRecordIds: readonly string[]; blocksAffectedPublication: true; blocksOtherWork: false; workCompletedWhileWaiting: string; review: Readonly<{ status: "proposed"; reviewer: null; reviewedAt: null; resolution: null }> }>;
export type WashingtonPrimaryJointReviewPackage = Readonly<{ schema: typeof WASHINGTON_PRIMARY_JOINT_REVIEW_V1; version: 1; generatedAt: "2026-08-06T17:00:00.000Z"; sourceCutoff: "2026-08-05"; reviewerOnly: true; publicationEligible: false; defaultUse: "exclude_formula_incompatible_top_two_until_identity_geography_disposition_classification_review"; review: Readonly<{ status: "proposed"; reviewer: null; reviewedAt: null; resolution: null }>; inputs: Readonly<Record<string, unknown>>; methodology: Readonly<Record<string, unknown>>; summary: Readonly<{ reviewRecords: 16; identityAndGeographyCandidates: 15; geographyCandidateIdentityUnresolved: 1; identityCandidates: 15; geographyCandidates: 16; certifiedTopTwoRecords: 16; proposedDecisions: 5; jointApprovedRecords: 0; scoreEligibleRecords: 0 }>; records: readonly ReviewRecord[]; reviewRecordSetSha256: string; decisions: readonly Decision[]; decisionSetSha256: string; inheritedDecisionResolutions: Readonly<{ resultAuthority: null; identity: null; geography: null; dispositionAndFormula: null; progressiveClassification: null }>; packageSha256: string }>;
export type WashingtonPrimaryJointReviewInput = Readonly<{ proposalJson: string; formulaAuthorityJson: string; identityJson: string; geographyJson: string; sourceLockJson: string }>;

const sha = (value: string): string => createHash("sha256").update(value).digest("hex");
const digest = (domain: string, value: unknown): string => createHash("sha256").update(domain, "ascii").update(canonicalJson(value), "utf8").digest("hex");
const order = (a: string, b: string): number => Buffer.compare(Buffer.from(a), Buffer.from(b));
const fail = (code: string): never => { throw new Error(`Washington primary joint review rejected: ${code}`); };
const parse = <T>(value: string, code: string): T => { try { return JSON.parse(value) as T; } catch { return fail(code); } };

export function buildWashingtonPrimaryJointReviewPackage(input: WashingtonPrimaryJointReviewInput): WashingtonPrimaryJointReviewPackage {
  if (sha(input.proposalJson) !== INPUTS.proposalFile || sha(input.formulaAuthorityJson) !== INPUTS.formulaFile || sha(input.identityJson) !== INPUTS.identityFile || sha(input.geographyJson) !== INPUTS.geographyFile) fail("INPUT_HASH_MISMATCH");
  const proposal = validateHouseDemocraticPrimarySourceSelectionProposal(parse(input.proposalJson, "PROPOSAL_JSON_INVALID")), formulaAuthority = validateFilingRunwayExceptionAuthorityProposal(parse(input.formulaAuthorityJson, "FORMULA_AUTHORITY_JSON_INVALID")), identity = validateWashingtonTopTwoIdentityCandidate(parse<WashingtonTopTwoIdentityCandidate>(input.identityJson, "IDENTITY_JSON_INVALID")), geography = validateWashingtonPrimaryGeographyCandidate(parse<WashingtonPrimaryGeographyCandidate>(input.geographyJson, "GEOGRAPHY_JSON_INVALID"));
  const parentDecisionIds = ["collect-official-state-primary-results-and-certification-v1", "approve-historic-primary-candidate-identity-resolution-v1", "approve-historical-district-cd119-compatibility-v1", "decide-nonstandard-primary-disposition-treatment-v1", "approve-progressive-candidate-classification-method-v1"];
  const waFormula = formulaAuthority.states.find((state) => state.stateCode === "WA") ?? fail("PARENT_INVALID"), formulaDecision = formulaAuthority.decisions.find((decision) => decision.decisionId === "exclude-washington-top-two-from-partisan-primary-v01") ?? fail("PARENT_INVALID");
  if (proposal.packageSha256 !== INPUTS.proposalPackage || formulaAuthority.packageSha256 !== INPUTS.formulaPackage || formulaAuthority.review.status !== "proposed" || formulaAuthority.review.reviewer !== null || formulaAuthority.review.reviewedAt !== null || waFormula.electionPath !== "top_two_non_nominating" || waFormula.formulaApplicability !== "confirmed_incompatible" || waFormula.evaluatorValueEligible || formulaDecision.resolution !== null || identity.packageSha256 !== INPUTS.identityPackage || identity.observationSetSha256 !== INPUTS.identitySet || geography.packageSha256 !== INPUTS.geographyPackage || geography.rowSetSha256 !== INPUTS.geographySet || identity.review.resolution !== null || geography.review.resolution !== null || parentDecisionIds.some((id) => proposal.decisions.find((decision) => decision.decisionId === id)?.resolution !== null)) fail("PARENT_INVALID");
  const sourceLock = parse<{ entries?: Array<{ id: string; retainedPath?: string; retainedStatus: string; byteSize?: number; sha256: string; kind: string; parentIds?: string[] }> }>(input.sourceLockJson, "SOURCE_LOCK_JSON_INVALID"), entries = sourceLock.entries ?? fail("SOURCE_LOCK_MISMATCH");
  const required = [["house-democratic-primary-source-selection-proposal-20260804-v1", INPUTS.proposalFile, "data/metadata/house-democratic-primary-source-selection-proposal-20260804-v1.json", "review_proposal", PROPOSAL_PARENTS], ["filing-runway-exception-authority-proposal-20260804-v1", INPUTS.formulaFile, "data/metadata/filing-runway-exception-authority-proposal-20260804-v1.json", "review_proposal", FORMULA_PARENTS], ["washington-current-incumbent-top-two-linkage-candidate-v1", INPUTS.identityFile, "data/metadata/washington-current-incumbent-top-two-linkage-candidate-v1.json", "review_candidate", IDENTITY_PARENTS], ["washington-primary-geography-compatibility-candidate-v1", INPUTS.geographyFile, "data/metadata/washington-primary-geography-compatibility-candidate-v1.json", "review_candidate", GEOGRAPHY_PARENTS]] as const;
  if (required.some(([id, file, path, kind, parents]) => { const found = entries.filter((entry) => entry.id === id); return found.length !== 1 || found[0]!.retainedStatus !== "retained" || found[0]!.sha256 !== file || found[0]!.retainedPath !== path || found[0]!.kind !== kind || canonicalJson(found[0]!.parentIds) !== canonicalJson(parents); })) fail("SOURCE_LOCK_MISMATCH");
  const output = entries.filter((entry) => entry.id === WASHINGTON_PRIMARY_JOINT_REVIEW_V1); if (!OUTPUT_FILE_SHA256) { if (output.length) fail("SOURCE_LOCK_MISMATCH"); } else if (output.length !== 1 || output[0]!.retainedPath !== "data/metadata/washington-primary-identity-geography-review-package-v1.json" || output[0]!.retainedStatus !== "retained" || output[0]!.byteSize !== OUTPUT_BYTE_SIZE || output[0]!.sha256 !== OUTPUT_FILE_SHA256 || output[0]!.kind !== "review_proposal" || canonicalJson(output[0]!.parentIds) !== canonicalJson(OUTPUT_PARENTS)) fail("SOURCE_LOCK_MISMATCH");
  const geographyByIdentity = new Map(geography.rows.map((row) => [row.identityObservationId, row]));
  const records: ReviewRecord[] = identity.observations.map((identityRow) => {
    const geographyRow = geographyByIdentity.get(identityRow.observationId) ?? fail("PARENT_JOIN_INVALID");
    if (geographyRow.identityRowSha256 !== identityRow.rowSha256 || geographyRow.contestId !== identityRow.contestId || geographyRow.contestSha256 !== identityRow.contestSha256 || geographyRow.cycleYear !== identityRow.cycleYear || geographyRow.districtCode !== identityRow.districtCode || geographyRow.seatCycleId !== identityRow.seatCycleId || geographyRow.identityStatus !== identityRow.identityStatus) fail("PARENT_JOIN_INVALID");
    const identityCandidate = identityRow.identityStatus === "proposed_identity_link", category = identityCandidate ? "identity_and_geography_candidates" as const : "geography_candidate_identity_unresolved" as const;
    const unsigned = { reviewRecordId: `wa-primary-joint:${identityRow.cycleYear}:${identityRow.districtCode}`, identityObservationId: identityRow.observationId, geographyObservationId: geographyRow.observationId, contestId: identityRow.contestId, contestSha256: identityRow.contestSha256, cycleYear: identityRow.cycleYear, electionDate: identityRow.electionDate, seatCycleId: identityRow.seatCycleId, districtCode: identityRow.districtCode, identity: { parentRowSha256: identityRow.rowSha256, status: identityCandidate ? "candidate" as const : "unresolved" as const, identityStatus: identityRow.identityStatus, bioguideId: identityRow.rosterIdentity.bioguideId, officialHouseName: identityRow.rosterIdentity.officialHouseName, sourceCandidateName: identityRow.sourceCandidate?.sourceCandidateName ?? null, evidenceClass: identityRow.evidenceClass, confidence: identityRow.confidence, candidate: identityCandidate, approved: false as const }, geography: { parentRowSha256: geographyRow.rowSha256, status: "candidate" as const, targetCd119Geoid: geographyRow.targetCd119Geoid, historicalCongressSession: geographyRow.historicalCongressSession, historicalGeoid: geographyRow.historicalGeoid, evidenceClass: geographyRow.evidenceClass, confidence: geographyRow.confidence, compatibilityDisposition: geographyRow.compatibilityDisposition, candidate: true as const, approved: false as const }, reviewCategory: category, resultDispositionPreserved: true as const, certificationStatus: "certified" as const, nominationSystem: "top_two" as const, formulaApplicability: "confirmed_incompatible" as const, sourceWinnerStatus: "not_established" as const, progressiveClassificationStatus: "not_retained" as const, jointApproved: false as const, evaluatorUse: "excluded_formula_incompatible_top_two_pending_identity_geography_disposition_classification_review_and_publication_approval" as const, scoreEligible: false as const, reviewerAction: identityCandidate ? "review_identity_and_geography_independently" as const : "review_geography_while_preserving_identity_no_match" as const, rationaleCodes: [category, "parent_candidates_not_approved_by_join", "certified_top_two_party_preference_not_nomination_or_endorsement", "source_winner_and_advancement_not_established", "formula_incompatible_with_partisan_primary_evaluator", "all_independent_review_gates_remain_open"] };
    return { ...unsigned, reviewRecordSha256: digest("dsa-seats:wa-primary-joint-review-row:v1\0", unsigned) };
  }).sort((a, b) => order(a.reviewRecordId, b.reviewRecordId));
  if (records.length !== 16 || geographyByIdentity.size !== 16 || records.filter((row) => row.reviewCategory === "identity_and_geography_candidates").length !== 15 || records.filter((row) => row.reviewCategory === "geography_candidate_identity_unresolved").length !== 1) fail("JOIN_CLOSURE_INVALID");
  const all = records.map((row) => row.reviewRecordId), linked = records.filter((row) => row.identity.candidate).map((row) => row.reviewRecordId), common = { defaultReversibleAssumption: "exclude_affected_records_from_evaluator_and_publication" as const, confidence: "high" as const, blocksAffectedPublication: true as const, blocksOtherWork: false as const, review: { status: "proposed" as const, reviewer: null, reviewedAt: null, resolution: null } };
  const decisions: Decision[] = [
    { ...common, decisionId: "wa-primary:retain-certified-top-two-result-authority-v1", affectedComponent: "certified top-two result authority", parentDecisionId: parentDecisionIds[0]!, question: "Should the 16 certified Washington top-two contest observations be retained as scoped result authority without treating them as Democratic-primary results?", recommendedDecision: "Retain certified contest facts while preserving the top-two formula exclusion.", alternatives: ["Require additional certification evidence.", "Reject the retained result authority."], consequences: ["Retention authorizes no identity, geography, nomination, winner, score, or publication state.", "Deferral keeps all records excluded while preserving the retained facts."], evidenceRecordIds: all, workCompletedWhileWaiting: "Certified result files, certification authorities, contest hashes, and exact joins are retained." },
    { ...common, decisionId: "wa-primary:accept-geography-compatibility-v1", affectedComponent: "historical geography", parentDecisionId: parentDecisionIds[2]!, question: "Should eight CD118 continuity and eight exact CD119 key rows be accepted as geography candidates?", recommendedDecision: "Accept all 16 geography candidates without claiming raw geometry equality or overlap.", alternatives: ["Require block-level crosswalk evidence for 2022.", "Reject all geography candidates."], consequences: ["Acceptance resolves geography only and preserves WA-06 identity no-match.", "Deferral keeps geography excluded without discarding Census evidence."], evidenceRecordIds: all, workCompletedWhileWaiting: "Complete official CD118/CD119 inventories, Census authority, and parent joins are retained." },
    { ...common, decisionId: "wa-primary:accept-identity-links-v1", affectedComponent: "current-incumbent identity", parentDecisionId: parentDecisionIds[1]!, question: "Should 13 exact and two finite middle-initial identity links be accepted?", recommendedDecision: "Accept the 15 proposed links while preserving 2022 WA-06 as a predecessor no-match.", alternatives: ["Reject all proposed links.", "Require external evidence for the two middle-initial rows."], consequences: ["Acceptance resolves identity only and does not approve geography or scoring.", "Every option keeps Derek Kilmer unlinked from Emily Randall."], evidenceRecordIds: linked, workCompletedWhileWaiting: "Official identities, finite name evidence, parent hashes, and WA-06 no-match are retained." },
    { ...common, decisionId: "wa-primary:retain-top-two-formula-exclusion-v1", affectedComponent: "top-two disposition and evaluator formula", parentDecisionId: "exclude-washington-top-two-from-partisan-primary-v01", question: "Should all 16 records remain excluded from the partisan-primary formula because top-two party preference is not nomination or endorsement and winner or advancement is not established here?", recommendedDecision: "Retain the formula exclusion and all null evaluator values.", alternatives: ["Treat party preference as Democratic nomination.", "Infer advancement or winner from vote rank."], consequences: ["The recommendation preserves certified facts without method mismatch.", "Either alternative requires a new versioned method and cannot be authorized by this join."], evidenceRecordIds: all, workCompletedWhileWaiting: "The separate filing-runway exception authority and every parent row are explicitly formula-incompatible." },
    { ...common, decisionId: "wa-primary:retain-progressive-classification-exclusion-v1", affectedComponent: "progressive candidate classification", parentDecisionId: parentDecisionIds[4]!, question: "Should progressive-primary factors remain excluded because no reviewed ideological classifications are present?", recommendedDecision: "Retain the exclusion.", alternatives: ["Treat all non-incumbents as progressive.", "Infer ideology from name or party preference."], consequences: ["The recommendation prevents unsupported values from entering scoring.", "Either alternative fabricates classification evidence."], evidenceRecordIds: all, workCompletedWhileWaiting: "Identity and geography evidence are isolated so classification can proceed independently." },
  ].sort((a, b) => order(a.decisionId, b.decisionId));
  const unsigned = { schema: WASHINGTON_PRIMARY_JOINT_REVIEW_V1, version: 1 as const, generatedAt: "2026-08-06T17:00:00.000Z" as const, sourceCutoff: "2026-08-05" as const, reviewerOnly: true as const, publicationEligible: false as const, defaultUse: "exclude_formula_incompatible_top_two_until_identity_geography_disposition_classification_review" as const, review: { status: "proposed" as const, reviewer: null, reviewedAt: null, resolution: null }, inputs: { proposal: { sourceLockId: required[0][0], fileSha256: INPUTS.proposalFile, packageSha256: INPUTS.proposalPackage }, formulaAuthority: { sourceLockId: required[1][0], fileSha256: INPUTS.formulaFile, packageSha256: INPUTS.formulaPackage, decisionId: formulaDecision.decisionId, resolution: null, electionPath: waFormula.electionPath, formulaApplicability: waFormula.formulaApplicability }, identity: { sourceLockId: required[2][0], fileSha256: INPUTS.identityFile, packageSha256: INPUTS.identityPackage, observationSetSha256: INPUTS.identitySet }, geography: { sourceLockId: required[3][0], fileSha256: INPUTS.geographyFile, packageSha256: INPUTS.geographyPackage, rowSetSha256: INPUTS.geographySet } }, methodology: { scope: "exact_sixteen_washington_identity_observations_joined_one_to_one_with_geography_rows", identityAndGeographyReviewedIndependently: true, certifiedResultAuthorityReviewedIndependently: true, formulaAndClassificationReviewedIndependently: true, jointPackageApprovesParents: false, automaticApprovals: 0, evaluatorNumericValues: 0 }, summary: { reviewRecords: 16 as const, identityAndGeographyCandidates: 15 as const, geographyCandidateIdentityUnresolved: 1 as const, identityCandidates: 15 as const, geographyCandidates: 16 as const, certifiedTopTwoRecords: 16 as const, proposedDecisions: 5 as const, jointApprovedRecords: 0 as const, scoreEligibleRecords: 0 as const }, records, reviewRecordSetSha256: digest("dsa-seats:wa-primary-joint-review-row-set:v1\0", records), decisions, decisionSetSha256: digest("dsa-seats:wa-primary-joint-decision-set:v1\0", decisions), inheritedDecisionResolutions: { resultAuthority: null, identity: null, geography: null, dispositionAndFormula: null, progressiveClassification: null } };
  return validateWashingtonPrimaryJointReviewPackage({ ...unsigned, packageSha256: digest("dsa-seats:wa-primary-joint-review-package:v1\0", unsigned) });
}

export function validateWashingtonPrimaryJointReviewPackage(value: unknown): WashingtonPrimaryJointReviewPackage {
  const candidate = value as WashingtonPrimaryJointReviewPackage; if (typeof candidate !== "object" || candidate === null || Array.isArray(candidate)) fail("PACKAGE_SHAPE_INVALID");
  if (candidate.schema !== WASHINGTON_PRIMARY_JOINT_REVIEW_V1 || candidate.version !== 1 || !candidate.reviewerOnly || candidate.publicationEligible || candidate.review.status !== "proposed" || candidate.review.reviewer !== null || candidate.review.reviewedAt !== null || candidate.review.resolution !== null || candidate.records.length !== 16 || candidate.decisions.length !== 5 || candidate.records.some((row) => row.jointApproved || row.scoreEligible || row.identity.approved || row.geography.approved || row.certificationStatus !== "certified" || row.nominationSystem !== "top_two" || row.formulaApplicability !== "confirmed_incompatible" || row.sourceWinnerStatus !== "not_established") || candidate.decisions.some((row) => row.review.status !== "proposed" || row.review.reviewer !== null || row.review.reviewedAt !== null || row.review.resolution !== null || !row.blocksAffectedPublication || row.blocksOtherWork)) fail("LIFECYCLE_INVALID");
  if (candidate.records.some((row, index) => { const { reviewRecordSha256, ...unsigned } = row; return reviewRecordSha256 !== digest("dsa-seats:wa-primary-joint-review-row:v1\0", unsigned) || (index > 0 && order(candidate.records[index - 1]!.reviewRecordId, row.reviewRecordId) >= 0); }) || candidate.reviewRecordSetSha256 !== digest("dsa-seats:wa-primary-joint-review-row-set:v1\0", candidate.records) || candidate.decisionSetSha256 !== digest("dsa-seats:wa-primary-joint-decision-set:v1\0", candidate.decisions)) fail("SET_INVALID");
  const { packageSha256, ...unsigned } = candidate; if (packageSha256 !== digest("dsa-seats:wa-primary-joint-review-package:v1\0", unsigned)) fail("PACKAGE_HASH_INVALID"); if (WASHINGTON_PRIMARY_JOINT_RECORD_SET_SHA256 && candidate.reviewRecordSetSha256 !== WASHINGTON_PRIMARY_JOINT_RECORD_SET_SHA256) fail("RECORD_SET_IDENTITY_INVALID"); if (WASHINGTON_PRIMARY_JOINT_DECISION_SET_SHA256 && candidate.decisionSetSha256 !== WASHINGTON_PRIMARY_JOINT_DECISION_SET_SHA256) fail("DECISION_SET_IDENTITY_INVALID"); if (WASHINGTON_PRIMARY_JOINT_PACKAGE_SHA256 && packageSha256 !== WASHINGTON_PRIMARY_JOINT_PACKAGE_SHA256) fail("PACKAGE_IDENTITY_INVALID"); return candidate;
}
