import { createHash } from "node:crypto";

import { canonicalJson } from "../fec/aipac-proposed-packages";
import { validateHouseDemocraticPrimarySourceSelectionProposal } from "./house-democratic-primary-source-selection-proposal";
import { validateWashingtonTopTwoIdentityCandidate, type WashingtonTopTwoIdentityCandidate } from "./washington-current-incumbent-top-two-linkage-candidate";
import { validateWashingtonHouseTopTwoResultsReceipt, type WashingtonHouseTopTwoResultsReceipt } from "./washington-house-top-two-results-receipt";

export const WASHINGTON_PRIMARY_GEOGRAPHY_V1 = "washington-primary-geography-compatibility-candidate-v1" as const;
export const WASHINGTON_PRIMARY_GEOGRAPHY_ROW_SET_SHA256 = "bf7bf88c3cd5030f56a326391e60c3ebea08dfc97c9430277a22e27bfc983d22";
export const WASHINGTON_PRIMARY_GEOGRAPHY_PACKAGE_SHA256 = "22e6eaf9d819c1939b3260cb7173cff576371344f2da75dd520d7b6c2d06d251";
const INPUTS = {
  proposalFile: "85246e9adfd181e6f24606b6eaa29250c45c9e8e42a6dd5af5cb162de17f45b1", proposalPackage: "a090e0be03dc2b0fa5edd0c1132a8261eed0f98ceb4df090154d0b150d8721fb",
  receiptFile: "eac5df760de11a6612c2e8a95374a8041b2debb94068e0d08afadecd775963da", receiptPackage: "a930a28888f3892f0b4459063b0d0a2c195bfada26960b705757124a403e5e13", receiptSet: "30fbbe0795413030a49fb366375c9898e97e7f778a5441e9785fcddd36b2a259",
  identityFile: "d8abddb956831e60487d65cf4b26fec5112032737be73f547d12af7338961093", identityPackage: "8ef11d58375a07018cdf05bffce1b68777c1d013149a3d292c69c7e52cd1db11", identitySet: "5be84bd55abebdaf647b95727db0b324d4a70fc0167c7a08478a0a35246267ae",
  authorityFile: "66a0551a6c3c6432bff0a6a6db23f221fbe02ead1d15221d7050633898914670",
  cd118File: "8994727a7d0462a72553d09f7f2ca91d75f77f24a01435d786003b4bb499b762", cd118Dbf: "2f996229056db97ad7f7715ef666b404903d17a8b298cfaabf3aeaafaeb2c13f",
  cd119File: "25e5d538f8a177d18fbafa83aa2e826bfeaadb73efbeca94d4072139679d7260", cd119Dbf: "205c6e428ccbbe225b4dbe0a84e26a7ae9a2a0f715f419825af1b6db29fa04d7",
} as const;
const PROPOSAL_PARENTS = ["dsa-target-factual-projection-20260804-v1", "dsa-target-incumbent-roster-20260804-v1", "fec-2026-congressional-primary-dates", "geo-national-cd119"] as const;
const RECEIPT_PARENTS = ["wa-2022-house-primary-results", "wa-2024-house-primary-results", "wa-2022-primary-certification", "wa-2024-primary-certification", "house-democratic-primary-source-selection-proposal-20260804-v1"] as const;
const IDENTITY_PARENTS = ["dsa-target-incumbent-roster-20260804-v1", "house-democratic-primary-source-selection-proposal-20260804-v1", "house-xml", "congress-legislators-current-20260804", "washington-house-top-two-results-receipt-20220802-20240806-v1"] as const;
const OUTPUT_PARENTS = ["house-democratic-primary-source-selection-proposal-20260804-v1", "washington-house-top-two-results-receipt-20220802-20240806-v1", "washington-current-incumbent-top-two-linkage-candidate-v1", "census-cd119-plan-change-authority-20260805", "tiger-cd118-53", "tiger-cd119-53"] as const;
const OUTPUT_FILE_SHA256 = "393ce5c9394102686777e1a87ba6e63665ab617f6fd3d7c83dcea1392078389b";
const OUTPUT_BYTE_SIZE = 29_143;

type Row = Readonly<{ observationId: string; identityObservationId: string; identityRowSha256: string; identityStatus: "proposed_identity_link" | "reported_contest_no_unique_candidate_match"; contestId: string; contestSha256: string; cycleYear: 2022 | 2024; electionDate: "2022-08-02" | "2024-08-06"; seatCycleId: string; districtCode: string; sourceWinnerStatus: "not_established"; certificationStatus: "certified"; nominationSystem: "top_two"; targetCd119Geoid: string; historicalCongressSession: "118" | "119"; historicalGeoid: string; compatibilityDisposition: "official_no_plan_change_declaration_same_geoid_key_candidate" | "same_cd119_session_and_geoid_exact_key_candidate"; evidenceClass: "direct_official_plan_continuity_and_derived_key" | "derived_exact_session_and_key"; confidence: "high"; compatibilityCandidate: true; compatibilityApproved: false; identityApproved: false; selected: false; formulaApplicability: "confirmed_incompatible"; evaluatorUse: "excluded_formula_incompatible_top_two_pending_identity_geography_review_and_publication_approval"; scoreEligible: false; rationaleCodes: readonly string[]; rowSha256: string }>;
export type WashingtonPrimaryGeographyCandidate = Readonly<{ schema: typeof WASHINGTON_PRIMARY_GEOGRAPHY_V1; version: 1; generatedAt: "2026-08-06T16:00:00.000Z"; sourceCutoff: "2026-08-05"; reviewerOnly: true; publicationEligible: false; defaultUse: "exclude_formula_incompatible_top_two_until_identity_geography_review_and_publication_approval"; review: Readonly<{ status: "proposed"; reviewer: null; reviewedAt: null; resolution: null }>; inputs: Readonly<Record<string, unknown>>; methodology: Readonly<Record<string, unknown>>; summary: Readonly<{ contestCycleObservations: 16; cd118ToCd119PlanContinuityCandidates: 8; exactCd119SessionKeyCandidates: 8; compatibilityCandidates: 16; automaticallyApprovedRows: 0; scoreEligibleRows: 0 }>; rows: readonly Row[]; rowSetSha256: string; decisionSupport: Readonly<Record<string, unknown>>; packageSha256: string }>;
export type WashingtonPrimaryGeographyInput = Readonly<{ proposal: unknown; proposalFileSha256: string; receipt: WashingtonHouseTopTwoResultsReceipt; receiptFileSha256: string; identity: WashingtonTopTwoIdentityCandidate; identityFileSha256: string; authorityHtml: string; authorityFileSha256: string; cd118Zip: Buffer; cd118FileSha256: string; cd118Dbf: Buffer; cd119Zip: Buffer; cd119FileSha256: string; cd119Dbf: Buffer; sourceLock: unknown }>;

const sha = (value: Buffer | string): string => createHash("sha256").update(value).digest("hex");
const digest = (domain: string, value: unknown): string => createHash("sha256").update(domain, "ascii").update(canonicalJson(value), "utf8").digest("hex");
const order = (a: string, b: string): number => Buffer.compare(Buffer.from(a), Buffer.from(b));
const fail = (code: string): never => { throw new Error(`Washington primary geography rejected: ${code}`); };

function parseDbf(bytes: Buffer, session: "118" | "119") {
  if (bytes.length < 65 || bytes[0] !== 3) fail("DBF_HEADER_INVALID");
  const count = bytes.readUInt32LE(4), headerLength = bytes.readUInt16LE(8), recordLength = bytes.readUInt16LE(10), fields: Array<{ name: string; length: number; offset: number }> = [];
  let offset = 1;
  for (let cursor = 32; cursor + 32 <= headerLength && bytes[cursor] !== 0x0d; cursor += 32) { const name = bytes.subarray(cursor, cursor + 11).toString("ascii").replace(/\0.*$/, "").trim(), length = bytes[cursor + 16]!; if (!name || length < 1) fail("DBF_FIELD_INVALID"); fields.push({ name, length, offset }); offset += length; }
  if (count !== 10 || headerLength + count * recordLength > bytes.length || offset !== recordLength || bytes[headerLength - 1] !== 0x0d) fail("DBF_LAYOUT_INVALID");
  const old = session === "118", stateField = old ? "STATEFP20" : "STATEFP", geoidField = old ? "GEOID20" : "GEOID", districtField = old ? "CD118FP" : "CD119FP";
  const rows = Array.from({ length: count }, (_, index) => { const start = headerLength + index * recordLength; if (bytes[start] !== 0x20) fail("DBF_DELETED_RECORD"); const value = Object.fromEntries(fields.map((field) => [field.name, bytes.subarray(start + field.offset, start + field.offset + field.length).toString("ascii").trim()])); return { state: value[stateField], geoid: value[geoidField], district: value[districtField], session: value.CDSESSN }; }).sort((a, b) => order(a.geoid ?? "", b.geoid ?? ""));
  if (rows.some((row, index) => { const district = String(index + 1).padStart(2, "0"); return row.state !== "53" || row.geoid !== `53${district}` || row.district !== district || row.session !== session; })) fail("DBF_INVENTORY_INVALID");
  return rows;
}

export function buildWashingtonPrimaryGeographyCandidate(input: WashingtonPrimaryGeographyInput): WashingtonPrimaryGeographyCandidate {
  const actual = [input.proposalFileSha256, input.receiptFileSha256, input.identityFileSha256, input.authorityFileSha256, input.cd118FileSha256, input.cd119FileSha256, sha(input.authorityHtml), sha(input.cd118Zip), sha(input.cd118Dbf), sha(input.cd119Zip), sha(input.cd119Dbf)], expected = [INPUTS.proposalFile, INPUTS.receiptFile, INPUTS.identityFile, INPUTS.authorityFile, INPUTS.cd118File, INPUTS.cd119File, INPUTS.authorityFile, INPUTS.cd118File, INPUTS.cd118Dbf, INPUTS.cd119File, INPUTS.cd119Dbf];
  if (actual.some((value, index) => value !== expected[index])) fail("INPUT_HASH_MISMATCH");
  if (!input.cd118Zip.subarray(0, 4).equals(Buffer.from([0x50, 0x4b, 3, 4])) || !input.cd119Zip.subarray(0, 4).equals(Buffer.from([0x50, 0x4b, 3, 4]))) fail("ZIP_FORMAT_INVALID");
  const proposal = validateHouseDemocraticPrimarySourceSelectionProposal(input.proposal), receipt = validateWashingtonHouseTopTwoResultsReceipt(input.receipt), identity = validateWashingtonTopTwoIdentityCandidate(input.identity);
  if (proposal.packageSha256 !== INPUTS.proposalPackage || receipt.packageSha256 !== INPUTS.receiptPackage || receipt.summary.contestSetSha256 !== INPUTS.receiptSet || !receipt.reviewerOnly || receipt.publicationEligible || receipt.certificationStatus !== "certified" || receipt.nominationSystem !== "top_two" || receipt.formulaApplicability !== "confirmed_incompatible" || identity.packageSha256 !== INPUTS.identityPackage || identity.observationSetSha256 !== INPUTS.identitySet || proposal.decisions.find((row) => row.decisionId === "approve-historical-district-cd119-compatibility-v1")?.resolution !== null || identity.review.resolution !== null) fail("PARENT_INVALID");
  const phrase = "five states (Alabama, Georgia, Louisiana, New York, and North Carolina) that redrew their congressional district plans for the 119th Congress";
  if (!input.authorityHtml.includes(phrase) || input.authorityHtml.includes("five states (Alabama, Washington")) fail("AUTHORITY_INVALID");
  const inventories = [parseDbf(input.cd118Dbf, "118"), parseDbf(input.cd119Dbf, "119")], keys = new Set(inventories.flatMap((rows) => rows.map((row) => `${row.session}:${row.geoid}`)));
  const lock = input.sourceLock as { entries?: Array<{ id: string; retainedPath?: string; retainedStatus: string; byteSize?: number; sha256: string; kind: string; parentIds?: string[] }> }, entries = lock.entries ?? fail("SOURCE_LOCK_MISMATCH");
  const required = [["house-democratic-primary-source-selection-proposal-20260804-v1", INPUTS.proposalFile, "data/metadata/house-democratic-primary-source-selection-proposal-20260804-v1.json", "review_proposal", PROPOSAL_PARENTS], ["washington-house-top-two-results-receipt-20220802-20240806-v1", INPUTS.receiptFile, "data/metadata/washington-house-top-two-results-receipt-20220802-20240806-v1.json", "review_proposal", RECEIPT_PARENTS], ["washington-current-incumbent-top-two-linkage-candidate-v1", INPUTS.identityFile, "data/metadata/washington-current-incumbent-top-two-linkage-candidate-v1.json", "review_candidate", IDENTITY_PARENTS], ["census-cd119-plan-change-authority-20260805", INPUTS.authorityFile, "data/source/elections/primary-results/geography/census-119-congressional-district-bef.html", "source", []], ["tiger-cd118-53", INPUTS.cd118File, "data/source/tiger2022/tl_2022_53_cd118.zip", "source", []], ["tiger-cd119-53", INPUTS.cd119File, "data/source/tiger2025/tl_2025_53_cd119.zip", "source", []]] as const;
  if (required.some(([id, hash, path, kind, parents]) => { const found = entries.filter((entry) => entry.id === id); return found.length !== 1 || found[0]!.sha256 !== hash || found[0]!.retainedPath !== path || found[0]!.retainedStatus !== "retained" || found[0]!.kind !== kind || canonicalJson(found[0]!.parentIds) !== canonicalJson(parents); })) fail("SOURCE_LOCK_MISMATCH");
  const output = entries.filter((entry) => entry.id === WASHINGTON_PRIMARY_GEOGRAPHY_V1); if (!OUTPUT_FILE_SHA256) { if (output.length) fail("SOURCE_LOCK_MISMATCH"); } else if (output.length !== 1 || output[0]!.retainedPath !== "data/metadata/washington-primary-geography-compatibility-candidate-v1.json" || output[0]!.retainedStatus !== "retained" || output[0]!.byteSize !== OUTPUT_BYTE_SIZE || output[0]!.sha256 !== OUTPUT_FILE_SHA256 || output[0]!.kind !== "review_candidate" || canonicalJson(output[0]!.parentIds) !== canonicalJson(OUTPUT_PARENTS)) fail("SOURCE_LOCK_MISMATCH");
  const rows: Row[] = identity.observations.map((observation) => {
    const contest = receipt.contests.filter((value) => value.contestId === observation.contestId); if (contest.length !== 1 || contest[0]!.contestSha256 !== observation.contestSha256 || contest[0]!.cycleYear !== observation.cycleYear || String(Number(observation.districtCode)) !== contest[0]!.districtCode) fail("RECEIPT_IDENTITY_MISMATCH");
    const target = `53${observation.districtCode}`, session = observation.cycleYear === 2022 ? "118" as const : "119" as const; if (!keys.has(`119:${target}`) || !keys.has(`${session}:${target}`)) fail("IDENTITY_OBSERVATION_OUTSIDE_TIGER_CLOSURE");
    const unsigned = { observationId: `wa:geography:${observation.cycleYear}:${observation.districtCode}`, identityObservationId: observation.observationId, identityRowSha256: observation.rowSha256, identityStatus: observation.identityStatus, contestId: observation.contestId, contestSha256: observation.contestSha256, cycleYear: observation.cycleYear, electionDate: observation.electionDate, seatCycleId: observation.seatCycleId, districtCode: observation.districtCode, sourceWinnerStatus: observation.sourceWinnerStatus, certificationStatus: "certified" as const, nominationSystem: "top_two" as const, targetCd119Geoid: target, historicalCongressSession: session, historicalGeoid: target, compatibilityDisposition: observation.cycleYear === 2022 ? "official_no_plan_change_declaration_same_geoid_key_candidate" as const : "same_cd119_session_and_geoid_exact_key_candidate" as const, evidenceClass: observation.cycleYear === 2022 ? "direct_official_plan_continuity_and_derived_key" as const : "derived_exact_session_and_key" as const, confidence: "high" as const, compatibilityCandidate: true as const, compatibilityApproved: false as const, identityApproved: false as const, selected: false as const, formulaApplicability: "confirmed_incompatible" as const, evaluatorUse: "excluded_formula_incompatible_top_two_pending_identity_geography_review_and_publication_approval" as const, scoreEligible: false as const, rationaleCodes: observation.cycleYear === 2022 ? ["official_census_cd119_redraw_list_excludes_wa", "same_state_district_geoid_in_cd118_and_cd119_inventory", "raw_geometry_equality_not_asserted", "top_two_formula_incompatible"] : ["same_cd119_congressional_session", "same_state_district_geoid_in_cd119_inventory", "top_two_formula_incompatible"] };
    return { ...unsigned, rowSha256: digest("dsa-seats:wa-primary-geography-row:v1\0", unsigned) };
  }).sort((a, b) => order(a.observationId, b.observationId));
  const unsigned = { schema: WASHINGTON_PRIMARY_GEOGRAPHY_V1, version: 1 as const, generatedAt: "2026-08-06T16:00:00.000Z" as const, sourceCutoff: "2026-08-05" as const, reviewerOnly: true as const, publicationEligible: false as const, defaultUse: "exclude_formula_incompatible_top_two_until_identity_geography_review_and_publication_approval" as const, review: { status: "proposed" as const, reviewer: null, reviewedAt: null, resolution: null }, inputs: { proposal: { sourceLockId: required[0][0], fileSha256: INPUTS.proposalFile, packageSha256: INPUTS.proposalPackage }, receipt: { sourceLockId: required[1][0], fileSha256: INPUTS.receiptFile, packageSha256: INPUTS.receiptPackage, contestSetSha256: INPUTS.receiptSet }, identity: { sourceLockId: required[2][0], fileSha256: INPUTS.identityFile, packageSha256: INPUTS.identityPackage, observationSetSha256: INPUTS.identitySet }, censusPlanChangeAuthority: { sourceLockId: required[3][0], fileSha256: INPUTS.authorityFile, authorityClaim: "five_states_redrew_for_cd119_al_ga_la_ny_nc_wa_absent" }, tigerLayers: [{ sourceLockId: required[4][0], fileSha256: INPUTS.cd118File, dbfMemberSha256: INPUTS.cd118Dbf, cdSession: "118", districtCount: 10 }, { sourceLockId: required[5][0], fileSha256: INPUTS.cd119File, dbfMemberSha256: INPUTS.cd119Dbf, cdSession: "119", districtCount: 10 }] }, methodology: { targetSession: "119", cycleSessionMapping: { "2022": "118", "2024": "119" }, planContinuityRule: "official_census_redraw_scope_declaration_plus_same_state_district_key", exactSameSessionRule: "same_cd119_session_state_and_district_geoid", rawTigerGeometryEqualityAssessed: false, overlapThresholdUsed: false, automaticDecisionClosure: false, evaluatorNumericValues: 0 }, summary: { contestCycleObservations: 16 as const, cd118ToCd119PlanContinuityCandidates: 8 as const, exactCd119SessionKeyCandidates: 8 as const, compatibilityCandidates: 16 as const, automaticallyApprovedRows: 0 as const, scoreEligibleRows: 0 as const }, rows, rowSetSha256: digest("dsa-seats:wa-primary-geography-row-set:v1\0", rows), decisionSupport: { informsDecisionId: "approve-historical-district-cd119-compatibility-v1", formulaDecisionId: "exclude-washington-top-two-from-partisan-primary-v01", status: "proposed", recommendedResolution: "accept_eight_cd118_continuity_and_eight_exact_cd119_key_candidates_without_weakening_top_two_formula_exclusion", reviewerResolution: null, reviewer: null, reviewedAt: null } };
  return validateWashingtonPrimaryGeographyCandidate({ ...unsigned, packageSha256: digest("dsa-seats:wa-primary-geography-candidate:v1\0", unsigned) });
}

export function validateWashingtonPrimaryGeographyCandidate(value: unknown): WashingtonPrimaryGeographyCandidate {
  const candidate = value as WashingtonPrimaryGeographyCandidate; if (typeof candidate !== "object" || candidate === null || Array.isArray(candidate)) fail("PACKAGE_SHAPE_INVALID");
  if (candidate.schema !== WASHINGTON_PRIMARY_GEOGRAPHY_V1 || candidate.version !== 1 || !candidate.reviewerOnly || candidate.publicationEligible || candidate.review.status !== "proposed" || candidate.review.reviewer !== null || candidate.review.reviewedAt !== null || candidate.review.resolution !== null || candidate.rows.length !== 16 || canonicalJson(candidate.summary) !== canonicalJson({ contestCycleObservations: 16, cd118ToCd119PlanContinuityCandidates: 8, exactCd119SessionKeyCandidates: 8, compatibilityCandidates: 16, automaticallyApprovedRows: 0, scoreEligibleRows: 0 }) || candidate.rows.some((row) => !row.compatibilityCandidate || row.compatibilityApproved || row.identityApproved || row.selected || row.scoreEligible || row.formulaApplicability !== "confirmed_incompatible" || row.nominationSystem !== "top_two" || row.sourceWinnerStatus !== "not_established")) fail("LIFECYCLE_INVALID");
  if (candidate.rows.some((row, index) => { const { rowSha256, ...unsigned } = row; return rowSha256 !== digest("dsa-seats:wa-primary-geography-row:v1\0", unsigned) || (index > 0 && order(candidate.rows[index - 1]!.observationId, row.observationId) >= 0) || (row.cycleYear === 2022 ? row.historicalCongressSession !== "118" || row.compatibilityDisposition !== "official_no_plan_change_declaration_same_geoid_key_candidate" : row.historicalCongressSession !== "119" || row.compatibilityDisposition !== "same_cd119_session_and_geoid_exact_key_candidate"); }) || candidate.rowSetSha256 !== digest("dsa-seats:wa-primary-geography-row-set:v1\0", candidate.rows)) fail("ROW_INVALID");
  const { packageSha256, ...unsigned } = candidate; if (packageSha256 !== digest("dsa-seats:wa-primary-geography-candidate:v1\0", unsigned)) fail("PACKAGE_HASH_INVALID"); if (WASHINGTON_PRIMARY_GEOGRAPHY_ROW_SET_SHA256 && candidate.rowSetSha256 !== WASHINGTON_PRIMARY_GEOGRAPHY_ROW_SET_SHA256) fail("ROW_SET_IDENTITY_INVALID"); if (WASHINGTON_PRIMARY_GEOGRAPHY_PACKAGE_SHA256 && packageSha256 !== WASHINGTON_PRIMARY_GEOGRAPHY_PACKAGE_SHA256) fail("PACKAGE_IDENTITY_INVALID"); return candidate;
}
