import { createHash, generateKeyPairSync } from "node:crypto";
import { describe, expect, it } from "vitest";
import { fecV2ReceiptSetDigestSha256 } from "@/ingestion/fec/snapshot-digest";
import { buildFecV2ArtifactTranscriptFromCanonicalBytes, buildFecV2ExpectedDataReviews, canonical, canonicalSha256, fecV2ClosureScopingStateSha256, fecV2PublicationProofQuery, LaunchProofError, prepareFecV2ArtifactTranscriptWithClient, type FecV2ArtifactTranscript, type FecV2CanonicalPayload, type FecV2GraphRow, type PublicKeyResolver, type SignatureVerifier, validateFecV2ArtifactSemantics, validateFecV2ArtifactTranscript, validateFecV2PublicationGraph, verifyFecV2DataReviewSignatures, verifyFecV2PublicationEvidence } from "./launch-data-proofs";
import { encodeFecEnumerationPage, encodeFecFilingLedger, fecFilingIdentitySha256, fecPassOccurrenceDigestSha256, type FecFilingIdentityV1 } from "@/ingestion/fec/filing-ledger";
import { encodeFecSanitizedFilingArtifact } from "@/ingestion/fec/efo-sanitizer";

const hash = (n: number) => n.toString(16).padStart(64, "0");
const plan = hash(1), snapshot = "snapshot", cutoff = "2026-07-18T00:00:00.000Z";
const row = (values: Record<string, string | number | bigint | boolean | null | Date>): FecV2GraphRow => values;

function fixture(): FecV2CanonicalPayload {
  const dates = Array.from({ length: 564 }, (_, i) => new Date(Date.UTC(2025, 0, 1 + i)).toISOString().slice(0, 10));
  const enumeration = dates.flatMap(date => (["F24", "F3", "F3X", "F5"] as const).flatMap(form => [1, 2].map(pass => row({ plan_sha256: plan, artifact_sha256: hash(10 + dates.indexOf(date) * 8 + ["F24", "F3", "F3X", "F5"].indexOf(form) * 2 + pass), artifact_kind: "enumeration_page", pass, form_type: form, receipt_date: date, requested_file_number: null, page_number: 1, terminal: 1 }))));
  const receipts = [...enumeration.map((page, i) => ({ receiptId: `r${i}`, objectKey: `fec/${i}`, versionId: `v${i}`, etag: `e${i}`, artifactSha256: String(page.artifact_sha256), byteSize: "9", artifactKind: "enumeration_page", upstreamEntitySha256: null, retrievedAt: cutoff, snapshotId: snapshot, planSha256: plan })), { receiptId: "ledger", objectKey: "fec/ledger", versionId: "v", etag: "e", artifactSha256: hash(5000), byteSize: "9", artifactKind: "filing_ledger", upstreamEntitySha256: null, retrievedAt: cutoff, snapshotId: snapshot, planSha256: plan }, { receiptId: "sanitized", objectKey: "fec/sanitized", versionId: "v", etag: "e", artifactSha256: hash(5001), byteSize: "9", artifactKind: "sanitized_filing", upstreamEntitySha256: null, retrievedAt: cutoff, snapshotId: snapshot, planSha256: plan }];
  const digest = fecV2ReceiptSetDigestSha256(plan, snapshot, receipts.map(item => ({ ...item, byteSize: BigInt(item.byteSize), retrievedAt: new Date(item.retrievedAt) })));
  const seats = Array.from({ length: 541 }, (_, i) => `seat-${i}`);
  return {
    schemaVersion: 2, kind: "fec_v2_exact_election", proof: { proofId: "proof", releaseId: "release", planSha256: plan }, release: { id: "release", sourceCutoff: "2026-07-18" }, route: { route: "fec_v2_exact_election", planSha256: plan }, plan: row({}),
    targets: seats.map(seat => row({ plan_sha256: plan, seat_cycle_id: seat, kind: "candidate_resolution_required", disposition: null, evidence_sha256: null })),
    sourceSnapshots: [row({ snapshot_id: snapshot, usage_status: "approved", sealed_at: cutoff, receipt_set_digest_sha256: digest, checksum_sha256: digest })],
    artifacts: receipts.map(item => row({ plan_sha256: plan, artifact_sha256: item.artifactSha256, artifact_kind: item.artifactKind, canonical_byte_size: BigInt(9) })), receipts,
    enumerationPages: enumeration, filingLedgers: [row({ artifact_sha256: hash(5000), artifact_kind: "filing_ledger", stable: 1, finalized_at: cutoff })],
    filingLedgerEntries: [row({ ledger_sha256: hash(5000), file_number: "file", canonical_form_type: "F24", report_date: null, receipt_date: "2025-01-01" })], pageLineage: [row({ ledger_sha256: hash(5000), file_number: "file", page_sha256: enumeration[0]!.artifact_sha256, pass: 1 }), row({ ledger_sha256: hash(5000), file_number: "file", page_sha256: enumeration[1]!.artifact_sha256, pass: 2 })], amendmentLinks: [],
    sanitizedFilings: [row({ artifact_sha256: hash(5001), artifact_kind: "sanitized_filing", ledger_sha256: hash(5000), file_number: "file", report_date: null })], alternateScoping: [],
    mappings: seats.map((seat, i) => row({ id: `m${i}`, plan_sha256: plan, seat_cycle_id: seat, target_kind: "candidate_resolution_required", fec_candidate_id: `c${i}` })),
    committees: [row({ id: "committee", candidate_mapping_id: "m0" })], elections: seats.map((seat, i) => row({ id: `e${i}`, plan_sha256: plan, seat_cycle_id: seat, candidate_mapping_id: `m${i}`, contest_id: `contest${i}`, election_code: "G", election_date: "2026-11-03" })),
    closures: seats.map((seat, i) => row({ id: `c${i}`, plan_sha256: plan, seat_cycle_id: seat, target_kind: "candidate_resolution_required", subject_kind: "candidate", subject_identity: `m${i}`, candidate_mapping_id: `m${i}`, status: "finalized", finalized_at: cutoff })),
    closureReceipts: seats.map((_, i) => row({ closure_id: `c${i}`, receipt_id: "r0" })), closureSnapshots: seats.map((_, i) => row({ closure_id: `c${i}`, snapshot_id: snapshot })),
    coverage: seats.map((seat, i) => row({ plan_sha256: plan, seat_cycle_id: seat, closure_id: `c${i}`, subject_identity: `m${i}`, outcome: "complete_zero", support_cents: BigInt(0), oppose_cents: BigInt(0) })),
    aggregates: seats.map((seat, i) => row({ seat_cycle_id: seat, candidate_mapping_id: `m${i}`, election_mapping_id: `e${i}`, closure_id: `c${i}`, support_cents: BigInt(0), oppose_cents: BigInt(0), methodology: "fec-receipt-cutoff-v2", coverage_through: "2026-07-18" })), dataSignatures: [], manifest: row({}), nationwideGate: row({}), digests: [],
  };
}
const valid = () => expect(() => validateFecV2PublicationGraph(fixture())).not.toThrow();
const invalid = (change: (payload: FecV2CanonicalPayload) => void) => { const payload = fixture(); change(payload); expect(() => validateFecV2PublicationGraph(payload)).toThrow(LaunchProofError); };
const mixedChain = () => {
  const p = fixture(), lookup = [1, 2].map(pass => row({ plan_sha256: plan, artifact_sha256: hash(8000 + pass), artifact_kind: "enumeration_page", pass, form_type: "F24", receipt_date: null, requested_file_number: "old", page_number: 1, terminal: 1 }));
  (p.enumerationPages as FecV2GraphRow[]).push(...lookup);
  (p.filingLedgerEntries as FecV2GraphRow[]).push(row({ ledger_sha256: hash(5000), file_number: "old", canonical_form_type: "F24", report_date: null, receipt_date: "2024-12-31" }), row({ ledger_sha256: hash(5000), file_number: "leaf", canonical_form_type: "F24", report_date: null, receipt_date: "2025-01-01" }));
  (p.pageLineage as FecV2GraphRow[]).push(...lookup.map(page => row({ ledger_sha256: hash(5000), file_number: "old", page_sha256: page.artifact_sha256, pass: page.pass })), row({ ledger_sha256: hash(5000), file_number: "leaf", page_sha256: p.enumerationPages[0]!.artifact_sha256, pass: 1 }), row({ ledger_sha256: hash(5000), file_number: "leaf", page_sha256: p.enumerationPages[1]!.artifact_sha256, pass: 2 }));
  (p.amendmentLinks as FecV2GraphRow[]).push(row({ ledger_sha256: hash(5000), file_number: "leaf", predecessor_file_number: "old" }));
  const added = lookup.map((page, i) => ({ receiptId: `old-${i}`, objectKey: `fec/old-${i}`, versionId: "v", etag: "e", artifactSha256: String(page.artifact_sha256), byteSize: "9", artifactKind: "enumeration_page", upstreamEntitySha256: null, retrievedAt: cutoff, snapshotId: snapshot, planSha256: plan }));
  (p.receipts as unknown as Array<(typeof p.receipts)[number]>).push(...added);
  (p.artifacts as FecV2GraphRow[]).push(...added.map(item => row({ plan_sha256: plan, artifact_sha256: item.artifactSha256, artifact_kind: item.artifactKind, canonical_byte_size: BigInt(9) })));
  const digest = fecV2ReceiptSetDigestSha256(plan, snapshot, p.receipts.map(item => ({ ...item, byteSize: BigInt(item.byteSize), retrievedAt: new Date(item.retrievedAt) })));
  (p.sourceSnapshots[0] as Record<string, unknown>).receipt_set_digest_sha256 = digest; (p.sourceSnapshots[0] as Record<string, unknown>).checksum_sha256 = digest;
  return p;
};

describe("validateFecV2PublicationGraph", () => {
  it("accepts a coherent exact 541-seat graph", valid);
  it("rejects duplicate or missing target seats", () => { invalid(p => (p.targets as FecV2GraphRow[])[1] = p.targets[0]!); invalid(p => (p.targets as FecV2GraphRow[]).pop()); });
  it("rejects missing or extra closures", () => { invalid(p => (p.closures as FecV2GraphRow[]).pop()); invalid(p => (p.closures as FecV2GraphRow[]).push(row({ ...p.closures[0]!, id: "extra" }))); });
  it("rejects global closures and absent coverage", () => { invalid(p => (p.closures[0] as Record<string, unknown>).subject_kind = "global_block"); invalid(p => (p.coverage as FecV2GraphRow[]).pop()); });
  it("rejects terminal targets with aggregates", () => invalid(p => { (p.targets[0] as Record<string, unknown>).kind = "terminal"; (p.closures[0] as Record<string, unknown>).target_kind = "terminal"; (p.closures[0] as Record<string, unknown>).candidate_mapping_id = null; (p.closures[0] as Record<string, unknown>).subject_kind = "terminal"; (p.closures[0] as Record<string, unknown>).subject_identity = "terminal"; (p.coverage[0] as Record<string, unknown>).subject_identity = "terminal"; (p.mappings as FecV2GraphRow[]).shift(); (p.elections as FecV2GraphRow[]).shift(); }));
  it("rejects a candidate without its mapping or election", () => { invalid(p => (p.mappings as FecV2GraphRow[]).pop()); invalid(p => (p.elections as FecV2GraphRow[]).pop()); });
  it("rejects aggregate cent mismatches", () => invalid(p => (p.aggregates[0] as Record<string, unknown>).support_cents = BigInt(1)));
  it("rejects closure with no inputs", () => invalid(p => { (p.closureReceipts as FecV2GraphRow[]).shift(); (p.closureSnapshots as FecV2GraphRow[]).shift(); }));
  it("requires each receipt snapshot in its closure", () => invalid(p => (p.closureSnapshots[0] as Record<string, unknown>).snapshot_id = "unknown"));
  it("rejects an invalid snapshot receipt digest", () => invalid(p => (p.sourceSnapshots[0] as Record<string, unknown>).checksum_sha256 = hash(99)));
  it("rejects orphaned and mismatched artifacts", () => { invalid(p => (p.artifacts[0] as Record<string, unknown>).canonical_byte_size = BigInt(8)); invalid(p => (p.artifacts as FecV2GraphRow[]).push(row({ artifact_sha256: hash(99), artifact_kind: "enumeration_page", canonical_byte_size: BigInt(9) }))); });
  it("requires the exact single artifact subtype", () => { invalid(p => (p.enumerationPages as FecV2GraphRow[]).push(row({ ...p.enumerationPages[0]! }))); invalid(p => (p.enumerationPages[0] as Record<string, unknown>).artifact_kind = "filing_ledger"); });
  it("rejects stable=0 ledgers and draft closures", () => { invalid(p => (p.filingLedgers[0] as Record<string, unknown>).stable = 0); invalid(p => (p.closures[0] as Record<string, unknown>).status = "draft"); });
  it("defers occurrence/pass completeness to replayed artifact semantics", () => { const p = fixture(); (p.pageLineage as FecV2GraphRow[]).pop(); expect(() => validateFecV2PublicationGraph(p)).not.toThrow(); });
  it("rejects incomplete nationwide partitions and page closure defects", () => {
    invalid(p => (p.enumerationPages as FecV2GraphRow[]).pop());
    invalid(p => (p.enumerationPages[0] as Record<string, unknown>).pass = 2);
    invalid(p => (p.enumerationPages[0] as Record<string, unknown>).page_number = 2);
    invalid(p => { (p.enumerationPages[0] as Record<string, unknown>).terminal = 0; });
    invalid(p => { (p.enumerationPages as FecV2GraphRow[]).push(row({ ...p.enumerationPages[0]!, artifact_sha256: hash(9999), page_number: 2, terminal: 1 })); });
  });
  it("rejects malformed predecessor lookup pairs", () => invalid(p => { (p.enumerationPages[0] as Record<string, unknown>).receipt_date = null; (p.enumerationPages[0] as Record<string, unknown>).requested_file_number = "file"; }));
  it("requires exact lookup buckets only for old amendment predecessors", () => {
    expect(() => validateFecV2PublicationGraph(mixedChain())).not.toThrow();
    const allInWindow = mixedChain(); (allInWindow.filingLedgerEntries.find(entry => entry.file_number === "old") as Record<string, unknown>).receipt_date = "2025-01-01"; (allInWindow.enumerationPages as FecV2GraphRow[]).splice(-2); (allInWindow.artifacts as FecV2GraphRow[]).splice(-2); (allInWindow.receipts as unknown as unknown[]).splice(-2); for (const edge of allInWindow.pageLineage.filter(entry => entry.file_number === "old")) (edge as Record<string, unknown>).page_sha256 = edge.pass === 1 ? allInWindow.enumerationPages[0]!.artifact_sha256 : allInWindow.enumerationPages[1]!.artifact_sha256; const digest = fecV2ReceiptSetDigestSha256(plan, snapshot, allInWindow.receipts.map(item => ({ ...item, byteSize: BigInt(item.byteSize), retrievedAt: new Date(item.retrievedAt) }))); (allInWindow.sourceSnapshots[0] as Record<string, unknown>).receipt_set_digest_sha256 = digest; (allInWindow.sourceSnapshots[0] as Record<string, unknown>).checksum_sha256 = digest; expect(() => validateFecV2PublicationGraph(allInWindow)).not.toThrow();
    const missing = mixedChain(); (missing.enumerationPages as FecV2GraphRow[]).pop(); expect(() => validateFecV2PublicationGraph(missing)).toThrow(LaunchProofError);
    const unrelated = mixedChain(); (unrelated.filingLedgerEntries as FecV2GraphRow[]).push(row({ ledger_sha256: hash(5000), file_number: "orphan-old", canonical_form_type: "F24", report_date: null, receipt_date: "2024-12-31" })); expect(() => validateFecV2PublicationGraph(unrelated)).toThrow(LaunchProofError);
  });
  it("rejects missing and cyclic amendment predecessors", () => { invalid(p => (p.amendmentLinks as FecV2GraphRow[]).push(row({ ledger_sha256: p.filingLedgers[0]!.artifact_sha256, file_number: "file", predecessor_file_number: "missing" }))); invalid(p => { (p.filingLedgerEntries as FecV2GraphRow[]).push(row({ ledger_sha256: p.filingLedgers[0]!.artifact_sha256, file_number: "two" })); (p.amendmentLinks as FecV2GraphRow[]).push(row({ ledger_sha256: p.filingLedgers[0]!.artifact_sha256, file_number: "file", predecessor_file_number: "two" }), row({ ledger_sha256: p.filingLedgers[0]!.artifact_sha256, file_number: "two", predecessor_file_number: "file" })); }); });
  it("rejects branching amendment chains", () => invalid(p => { (p.filingLedgerEntries as FecV2GraphRow[]).push(row({ ledger_sha256: hash(5000), file_number: "two" }), row({ ledger_sha256: hash(5000), file_number: "three" })); (p.amendmentLinks as FecV2GraphRow[]).push(row({ ledger_sha256: hash(5000), file_number: "two", predecessor_file_number: "file" }), row({ ledger_sha256: hash(5000), file_number: "three", predecessor_file_number: "file" })); }));
  it("rejects a sanitized filing with a wrong file", () => invalid(p => (p.sanitizedFilings[0] as Record<string, unknown>).file_number = "wrong"));
  it("rejects bad alternate scoping", () => invalid(p => (p.alternateScoping as FecV2GraphRow[]).push(row({ ledger_sha256: hash(5000), file_number: "file", sanitized_artifact_sha256: hash(5001), conclusion: "inside" }))));
  it("handles bigint maxima without numeric overflow", () => { const p = fixture(); const max = BigInt("999999999999999999999999999999999999999999999999999999"); for (const collection of [p.coverage, p.aggregates]) { (collection[0] as Record<string, unknown>).support_cents = max; (collection[0] as Record<string, unknown>).oppose_cents = max; } (p.coverage[0] as Record<string, unknown>).outcome = "complete_nonzero"; expect(() => validateFecV2PublicationGraph(p)).not.toThrow(); });
});

describe("decoded FEC V2 artifact semantics", () => {
  type Sanitized = { kind: "sanitized_filing"; fileNumber: number; ledgerIdentitySha256: string; reportDate: string | null; candidateIds: string[]; scopeConclusion: "inside_candidate_targets" | "outside_candidate_targets"; semanticSha256: string };
  const semanticProjection = ({ fileNumber, ledgerIdentitySha256, reportDate, candidateIds, scopeConclusion }: Sanitized) => ({ fileNumber, ledgerIdentitySha256, reportDate, candidateIds, scopeConclusion });
  const refreshSemanticSha256 = (filing: Sanitized) => { filing.semanticSha256 = canonicalSha256(semanticProjection(filing)); };
  const transcript = (p: FecV2CanonicalPayload, conclusion: "inside_candidate_targets" | "outside_candidate_targets" = "inside_candidate_targets"): FecV2ArtifactTranscript => {
    const descriptor = p.receipts.find(item => item.artifactKind === "sanitized_filing")!, candidateIds = conclusion === "inside_candidate_targets" ? ["H00000001"] : ["H99999999"], decoded: Sanitized = { kind: "sanitized_filing", fileNumber: 12, ledgerIdentitySha256: hash(12), reportDate: null, candidateIds, scopeConclusion: conclusion, semanticSha256: "" };
    refreshSemanticSha256(decoded);
    return { ...descriptor, artifactKind: "sanitized_filing", replaySha256: descriptor.artifactSha256, replayByteSize: descriptor.byteSize, replayArtifactKind: "sanitized_filing", canonicalSchema: "fec-v2-sanitized-filing-v2", canonicalDecodeVersion: "1", decoded };
  };
  const payload = () => { const p = fixture(); (p.mappings as FecV2GraphRow[]).forEach((mapping, i) => (mapping as Record<string, unknown>).fec_candidate_id = `H${String(i + 1).padStart(8, "0")}`); return p; };
  const replayFixture = () => {
    const p = payload(), identity: FecFilingIdentityV1 = { fileNumber: 12, previousFileNumber: null, canonicalFormType: "F24", baseFormType: "F24", reportType: "M12", receiptDate: "2026-01-02", reportDate: null, coverageStartDate: null, coverageEndDate: null, authoritativeAmendmentChain: [12], amendmentIndicator: "N", filerId: "H00000001", committeeId: "C00000001", electronicStatus: "electronic", rawAvailability: "available" }, entryIdentitySha256 = fecFilingIdentitySha256(identity);
    const makePage = (pass: 1 | 2, terminal: boolean) => ({ schema: "fec-v2-enumeration-page-v1" as const, version: 1 as const, planSha256: plan, provenance: { kind: "daily_partition" as const, formType: "F24" as const, receiptDate: "2026-01-02" }, pass, pageNumber: terminal ? 2 : 1, terminal, records: terminal ? [] : [{ occurrenceIndex: 1, identity }], recordMultiplicity: terminal ? [] : [{ entryIdentitySha256, count: 1 }] });
    const pageBytes = [makePage(1, false), makePage(1, true), makePage(2, false), makePage(2, true)].map(value => encodeFecEnumerationPage(value));
    const descriptor = (kind: "enumeration_page" | "filing_ledger" | "sanitized_filing", bytes: Uint8Array, n: number) => ({ receiptId: `${kind}-${n}`, objectKey: `fec/${kind}/${n}`, versionId: "v", etag: "e", artifactSha256: createHash("sha256").update(bytes).digest("hex"), byteSize: String(bytes.byteLength), artifactKind: kind, upstreamEntitySha256: kind === "filing_ledger" ? null : hash(900 + n), retrievedAt: cutoff, snapshotId: snapshot, planSha256: plan });
    const pageDescriptors = pageBytes.map((bytes, i) => descriptor("enumeration_page", bytes, i));
    const passDigest = fecPassOccurrenceDigestSha256([{ identity, occurrenceIndex: 1 }]);
    const ledgerBytes = encodeFecFilingLedger({ schema: "fec-v2-filing-ledger-v1", version: 1, planSha256: plan, entries: [{ identity, entryIdentitySha256 }], sourcePageIdentities: pageDescriptors.map(item => item.artifactSha256).sort(), pass1DigestSha256: passDigest, pass2DigestSha256: passDigest, stable: true });
    const ledgerDescriptor = descriptor("filing_ledger", ledgerBytes, 0), sanitizedDescriptor = descriptor("sanitized_filing", new TextEncoder().encode("sanitized"), 0);
    const pageTranscripts = pageDescriptors.map((item, i) => buildFecV2ArtifactTranscriptFromCanonicalBytes(item, pageBytes[i]!));
    const ledgerTranscript = buildFecV2ArtifactTranscriptFromCanonicalBytes(ledgerDescriptor, ledgerBytes);
    const sanitized: Sanitized = { kind: "sanitized_filing", fileNumber: 12, ledgerIdentitySha256: entryIdentitySha256, reportDate: null, candidateIds: ["H00000001"], scopeConclusion: "inside_candidate_targets", semanticSha256: "" }; refreshSemanticSha256(sanitized);
    const sanitizedTranscript: FecV2ArtifactTranscript = { ...sanitizedDescriptor, artifactKind: "sanitized_filing", replaySha256: sanitizedDescriptor.artifactSha256, replayByteSize: sanitizedDescriptor.byteSize, replayArtifactKind: "sanitized_filing", canonicalSchema: "fec-v2-sanitized-filing-v2", canonicalDecodeVersion: "1", decoded: sanitized };
    const receipts = [...pageDescriptors, ledgerDescriptor, sanitizedDescriptor];
    (p as unknown as { receipts: typeof receipts; artifacts: FecV2GraphRow[]; enumerationPages: FecV2GraphRow[]; filingLedgers: FecV2GraphRow[]; filingLedgerEntries: FecV2GraphRow[]; pageLineage: FecV2GraphRow[]; sanitizedFilings: FecV2GraphRow[] }).receipts = receipts;
    (p as unknown as { artifacts: FecV2GraphRow[] }).artifacts = receipts.map(item => row({ plan_sha256: plan, artifact_sha256: item.artifactSha256, artifact_kind: item.artifactKind, canonical_byte_size: BigInt(item.byteSize) }));
    (p as unknown as { enumerationPages: FecV2GraphRow[] }).enumerationPages = pageDescriptors.map((item, i) => row({ plan_sha256: plan, artifact_sha256: item.artifactSha256, artifact_kind: "enumeration_page", pass: i < 2 ? 1 : 2, form_type: "F24", receipt_date: "2026-01-02", requested_file_number: null, page_number: i % 2 + 1, terminal: i % 2 }));
    (p as unknown as { filingLedgers: FecV2GraphRow[] }).filingLedgers = [row({ plan_sha256: plan, artifact_sha256: ledgerDescriptor.artifactSha256, artifact_kind: "filing_ledger", stable: 1, finalized_at: cutoff })];
    (p as unknown as { filingLedgerEntries: FecV2GraphRow[] }).filingLedgerEntries = [row({ plan_sha256: plan, ledger_sha256: ledgerDescriptor.artifactSha256, file_number: "12", entry_identity_sha256: entryIdentitySha256, canonical_form_type: "F24", base_form_type: "F24", report_type: "M12", report_date: null, receipt_date: "2026-01-02", coverage_start: null, coverage_end: null, amendment_indicator: "N", filer_id: "H00000001", committee_id: "C00000001", electronic_status: "electronic", raw_source_availability: "available" })];
    (p as unknown as { pageLineage: FecV2GraphRow[] }).pageLineage = [0, 2].map(i => row({ plan_sha256: plan, ledger_sha256: ledgerDescriptor.artifactSha256, file_number: "12", page_sha256: pageDescriptors[i]!.artifactSha256, pass: i === 0 ? 1 : 2, occurrence_index: 1 }));
    (p as unknown as { sanitizedFilings: FecV2GraphRow[] }).sanitizedFilings = [row({ plan_sha256: plan, artifact_sha256: sanitizedDescriptor.artifactSha256, artifact_kind: "sanitized_filing", ledger_sha256: ledgerDescriptor.artifactSha256, ledger_identity_sha256: entryIdentitySha256, file_number: "12", report_date: null })];
    return { p, transcript: [...pageTranscripts, ledgerTranscript, sanitizedTranscript] };
  };
  it("accepts fully DB-shaped replay evidence and rejects field or pass/occurrence mismatches", () => {
    const { p, transcript } = replayFixture(); expect(() => validateFecV2ArtifactSemantics(p, transcript)).not.toThrow();
    const field = replayFixture(); (field.p.filingLedgerEntries[0] as Record<string, unknown>).coverage_start = "2026-01-01"; expect(() => validateFecV2ArtifactSemantics(field.p, field.transcript)).toThrow(LaunchProofError);
    const occurrence = replayFixture(); (occurrence.p.pageLineage[0] as Record<string, unknown>).occurrence_index = 2; expect(() => validateFecV2ArtifactSemantics(occurrence.p, occurrence.transcript)).toThrow(LaunchProofError);
  });
  it("rejects incomplete transcript sets rather than treating sanitized evidence as standalone", () => { const p = payload(); expect(() => validateFecV2ArtifactSemantics(p, [transcript(p)])).toThrow(LaunchProofError); });
  it("rejects decoded report dates, target intersections, and alternate evidence defects", () => { const bad = (mutate: (p: FecV2CanonicalPayload, t: Extract<FecV2ArtifactTranscript, { artifactKind: "sanitized_filing" }>) => void) => { const p = payload(), t = transcript(p, "outside_candidate_targets") as Extract<FecV2ArtifactTranscript, { artifactKind: "sanitized_filing" }>; mutate(p, t); expect(() => validateFecV2ArtifactSemantics(p, [t])).toThrow(LaunchProofError); }; bad((p, t) => { void p; const decoded = t.decoded as Sanitized; decoded.reportDate = "2026-01-01"; refreshSemanticSha256(decoded); }); bad((p, t) => { void t; (p.alternateScoping as FecV2GraphRow[]).push(row({ ledger_sha256: hash(5000), file_number: "wrong", sanitized_artifact_sha256: hash(5001), conclusion: "outside_candidate_targets" })); }); bad((p, t) => { void t; (p.alternateScoping as FecV2GraphRow[]).push(row({ ledger_sha256: hash(5000), file_number: "file", sanitized_artifact_sha256: hash(5001), conclusion: "outside_candidate_targets" }), row({ ledger_sha256: hash(5000), file_number: "file", sanitized_artifact_sha256: hash(5001), conclusion: "outside_candidate_targets" })); }); });
  it("requires the decoded, sanitized, and ledger report dates to agree exactly", () => {
    const prepared = () => { const p = payload(), t = transcript(p) as Extract<FecV2ArtifactTranscript, { artifactKind: "sanitized_filing" }>; (p.filingLedgerEntries[0] as Record<string, unknown>).report_date = "2026-01-01"; (p.sanitizedFilings[0] as Record<string, unknown>).report_date = "2026-01-01"; const decoded = t.decoded as Sanitized; decoded.reportDate = "2026-01-01"; refreshSemanticSha256(decoded); return { p, t }; };
    for (const mutate of [(p: FecV2CanonicalPayload, t: Extract<FecV2ArtifactTranscript, { artifactKind: "sanitized_filing" }>) => { const decoded = t.decoded as Sanitized; decoded.reportDate = null; refreshSemanticSha256(decoded); }, (p: FecV2CanonicalPayload) => { (p.sanitizedFilings[0] as Record<string, unknown>).report_date = null; }, (p: FecV2CanonicalPayload) => { (p.filingLedgerEntries[0] as Record<string, unknown>).report_date = null; }]) { const { p, t } = prepared(); mutate(p, t); expect(() => validateFecV2ArtifactSemantics(p, [t])).toThrow(LaunchProofError); }
  });
  it("requires sorted candidate IDs and exact decoded schema", () => { const p = payload(), t = transcript(p) as Extract<FecV2ArtifactTranscript, { artifactKind: "sanitized_filing" }>; const malformed = { ...t, decoded: { ...t.decoded, candidateIds: ["H00000002", "H00000001"] } }; expect(validateFecV2ArtifactTranscript(malformed, p.receipts.find(item => item.artifactKind === "sanitized_filing")!)).toBe(false); });
  it("rejects a caller-forged sanitized scope conclusion", () => { const { p, transcript: evidence } = replayFixture(); const sanitized = evidence.find(item => item.artifactKind === "sanitized_filing")! as Extract<FecV2ArtifactTranscript, { artifactKind: "sanitized_filing" }>; const decoded = sanitized.decoded as Sanitized; decoded.scopeConclusion = "outside_candidate_targets"; refreshSemanticSha256(decoded); expect(() => validateFecV2ArtifactSemantics(p, evidence)).toThrow(LaunchProofError); });
  it("rejects substitution of another valid ledger identity hash", () => { const { p, transcript: evidence } = replayFixture(); const sanitized = evidence.find(item => item.artifactKind === "sanitized_filing")! as Extract<FecV2ArtifactTranscript, { artifactKind: "sanitized_filing" }>; const decoded = sanitized.decoded as Sanitized; decoded.ledgerIdentitySha256 = hash(999); refreshSemanticSha256(decoded); expect(() => validateFecV2ArtifactSemantics(p, evidence)).toThrow(LaunchProofError); });
});

describe("FEC V2 canonical artifact transcripts", () => {
  const identity: FecFilingIdentityV1 = { fileNumber: 12, previousFileNumber: null, canonicalFormType: "F24", baseFormType: "F24", reportType: "M12", reportDate: null, receiptDate: "2026-01-02", coverageStartDate: null, coverageEndDate: null, amendmentIndicator: "N", filerId: "H00000001", committeeId: "C00000001", electronicStatus: "electronic", rawAvailability: "available", authoritativeAmendmentChain: [12] };
  const descriptorFor = (artifactKind: "enumeration_page" | "filing_ledger" | "sanitized_filing", bytes: Uint8Array) => ({ receiptId: artifactKind, objectKey: `fec/${artifactKind}`, versionId: "v", etag: "e", artifactSha256: createHash("sha256").update(bytes).digest("hex"), byteSize: String(bytes.byteLength), artifactKind, upstreamEntitySha256: artifactKind === "filing_ledger" ? null : hash(88), retrievedAt: cutoff, snapshotId: snapshot, planSha256: plan } as const);
  it("derives strict enumeration and ledger evidence from canonical bytes", () => {
    const entryIdentitySha256 = fecFilingIdentitySha256(identity), page = { schema: "fec-v2-enumeration-page-v1" as const, version: 1 as const, planSha256: plan, provenance: { kind: "daily_partition" as const, formType: "F24" as const, receiptDate: "2026-01-02" }, pass: 1 as const, pageNumber: 1, terminal: false, records: [{ occurrenceIndex: 1, identity }], recordMultiplicity: [{ entryIdentitySha256, count: 1 }] }, pageBytes = encodeFecEnumerationPage(page), pageDescriptor = descriptorFor("enumeration_page", pageBytes), pageTranscript = buildFecV2ArtifactTranscriptFromCanonicalBytes(pageDescriptor, pageBytes);
    expect(pageTranscript.decoded.kind).toBe("enumeration_page"); expect(validateFecV2ArtifactTranscript(pageTranscript, pageDescriptor)).toBe(true);
    const ledger = { schema: "fec-v2-filing-ledger-v1" as const, version: 1 as const, planSha256: plan, entries: [{ identity, entryIdentitySha256 }], sourcePageIdentities: [pageDescriptor.artifactSha256], pass1DigestSha256: hash(77), pass2DigestSha256: hash(77), stable: true as const }, ledgerBytes = encodeFecFilingLedger(ledger), ledgerDescriptor = descriptorFor("filing_ledger", ledgerBytes), ledgerTranscript = buildFecV2ArtifactTranscriptFromCanonicalBytes(ledgerDescriptor, ledgerBytes);
    expect(ledgerTranscript.decoded.kind).toBe("filing_ledger"); expect(validateFecV2ArtifactTranscript(ledgerTranscript, ledgerDescriptor)).toBe(true);
  });
  it("binds lookup buckets to their own records, rejecting swapped lookup records", () => {
    const makeLookup = (fileNumber: number) => {
      const filing = { ...identity, fileNumber, authoritativeAmendmentChain: [fileNumber] }, entryIdentitySha256 = fecFilingIdentitySha256(filing);
      const value = { schema: "fec-v2-enumeration-page-v1" as const, version: 1 as const, planSha256: plan, provenance: { kind: "predecessor_lookup" as const, formType: "F24" as const, requestedFileNumber: fileNumber }, pass: 1 as const, pageNumber: 1, terminal: false, records: [{ occurrenceIndex: 1, identity: filing }], recordMultiplicity: [{ entryIdentitySha256, count: 1 }] };
      const bytes = encodeFecEnumerationPage(value), descriptor = descriptorFor("enumeration_page", bytes);
      return { descriptor, transcript: buildFecV2ArtifactTranscriptFromCanonicalBytes(descriptor, bytes) as Extract<FecV2ArtifactTranscript, { artifactKind: "enumeration_page" }> };
    };
    const first = makeLookup(12), second = makeLookup(13);
    expect(validateFecV2ArtifactTranscript(first.transcript, first.descriptor)).toBe(true);
    expect(validateFecV2ArtifactTranscript(second.transcript, second.descriptor)).toBe(true);
    const swapped = { ...first.transcript, decoded: { ...first.transcript.decoded, records: second.transcript.decoded.records, recordMultiplicity: second.transcript.decoded.recordMultiplicity } };
    expect(validateFecV2ArtifactTranscript(swapped, first.descriptor)).toBe(false);
  });
  it("rejects occurrence, multiplicity, pass digest, and unknown-key tampering", () => {
    const entryIdentitySha256 = fecFilingIdentitySha256(identity), page = { schema: "fec-v2-enumeration-page-v1" as const, version: 1 as const, planSha256: plan, provenance: { kind: "daily_partition" as const, formType: "F24" as const, receiptDate: "2026-01-02" }, pass: 1 as const, pageNumber: 1, terminal: false, records: [{ occurrenceIndex: 1, identity }], recordMultiplicity: [{ entryIdentitySha256, count: 1 }] }, pageBytes = encodeFecEnumerationPage(page), pageDescriptor = descriptorFor("enumeration_page", pageBytes), transcript = buildFecV2ArtifactTranscriptFromCanonicalBytes(pageDescriptor, pageBytes) as Extract<FecV2ArtifactTranscript, { artifactKind: "enumeration_page" }>;
    expect(validateFecV2ArtifactTranscript({ ...transcript, decoded: { ...transcript.decoded, records: [{ ...transcript.decoded.records[0]!, occurrenceIndex: 2 }] } }, pageDescriptor)).toBe(false);
    expect(validateFecV2ArtifactTranscript({ ...transcript, decoded: { ...transcript.decoded, recordMultiplicity: [{ entryIdentitySha256, count: 2 }] } }, pageDescriptor)).toBe(false);
    expect(validateFecV2ArtifactTranscript({ ...transcript, unexpected: true }, pageDescriptor)).toBe(false);
    const ledgerBytes = encodeFecFilingLedger({ schema: "fec-v2-filing-ledger-v1" as const, version: 1 as const, planSha256: plan, entries: [{ identity, entryIdentitySha256 }], sourcePageIdentities: [pageDescriptor.artifactSha256], pass1DigestSha256: hash(77), pass2DigestSha256: hash(77), stable: true as const }), ledgerDescriptor = descriptorFor("filing_ledger", ledgerBytes), ledger = buildFecV2ArtifactTranscriptFromCanonicalBytes(ledgerDescriptor, ledgerBytes) as Extract<FecV2ArtifactTranscript, { artifactKind: "filing_ledger" }>;
    expect(validateFecV2ArtifactTranscript({ ...ledger, decoded: { ...ledger.decoded, pass2DigestSha256: hash(78) } }, ledgerDescriptor)).toBe(false);
  });
  it("honors canonical decoder cancellation and deadlines", () => {
    const bytes = encodeFecEnumerationPage({ schema: "fec-v2-enumeration-page-v1", version: 1, planSha256: plan, provenance: { kind: "daily_partition", formType: "F24", receiptDate: "2026-01-02" }, pass: 1, pageNumber: 1, terminal: true, records: [], recordMultiplicity: [] }), descriptor = descriptorFor("enumeration_page", bytes), controller = new AbortController(); controller.abort();
    expect(() => buildFecV2ArtifactTranscriptFromCanonicalBytes(descriptor, bytes, { signal: controller.signal })).toThrow("FEC_LEDGER_ABORTED");
    expect(() => buildFecV2ArtifactTranscriptFromCanonicalBytes(descriptor, bytes, { deadlineMs: Date.now() - 1 })).toThrow("FEC_LEDGER_DEADLINE");
  });
  it("derives sanitized scope from canonical records, never caller conclusions", () => {
    const artifact = { schemaVersion: 2 as const, artifactKind: "sanitized_filing" as const, acquisitionPlanSha256: plan, fileNumber: 12, formatVersion: "8.5" as const, ledgerIdentitySha256: hash(12), reportDate: null, records: [], noRetention: { rawFilingNotStored: true as const, nonScheduleERecordsDiscarded: true as const, piiFieldsDiscarded: true as const } };
    const bytes = encodeFecSanitizedFilingArtifact(artifact), descriptor = descriptorFor("sanitized_filing", bytes);
    const transcript = buildFecV2ArtifactTranscriptFromCanonicalBytes(descriptor, bytes, { targetCandidateIds: [] });
    expect(transcript.canonicalSchema).toBe("fec-v2-sanitized-filing-v2");
    expect(transcript.decoded).toMatchObject({ fileNumber: 12, candidateIds: [], scopeConclusion: "outside_candidate_targets" });
    expect(() => buildFecV2ArtifactTranscriptFromCanonicalBytes(descriptor, bytes)).toThrow("FEC_V2_SANITIZED_TARGETS_INVALID");
    expect(() => buildFecV2ArtifactTranscriptFromCanonicalBytes(descriptor, bytes, { targetCandidateIds: ["H00000002", "H00000001"] })).toThrow("FEC_V2_SANITIZED_TARGETS_INVALID");
    expect(() => buildFecV2ArtifactTranscriptFromCanonicalBytes(descriptor, bytes, { targetCandidateIds: ["not-a-candidate"] })).toThrow("FEC_V2_SANITIZED_TARGETS_INVALID");
    expect(validateFecV2ArtifactTranscript({ ...transcript, canonicalSchema: "fec-v2-sanitized-filing-v1" }, descriptor)).toBe(false);
  });
  it.each(["F3X", "F24", "F5"] as const)("derives inside scope from nonempty %s records", canonicalFormType => {
    const noticeCode = canonicalFormType === "F24" ? "24" as const : null;
    const artifact = { schemaVersion: 2 as const, artifactKind: "sanitized_filing" as const, acquisitionPlanSha256: plan, fileNumber: 12, formatVersion: "8.5" as const, ledgerIdentitySha256: hash(12), reportDate: "2026-01-01", records: [{ fileNumber: 12, filerId: "C00000001", canonicalFormType, electionCode: "G2026", candidateId: "H00000001", supportOppose: "S" as const, disseminationDate: "2026-01-01", expenditureDate: null, amountCents: BigInt(1), transactionIdSha256: hash(13), backReferenceIdSha256: null, backReferenceScheduleSha256: null, memoCode: null, noticeCode, isNotice: noticeCode !== null }], noRetention: { rawFilingNotStored: true as const, nonScheduleERecordsDiscarded: true as const, piiFieldsDiscarded: true as const } };
    const bytes = encodeFecSanitizedFilingArtifact(artifact), descriptor = descriptorFor("sanitized_filing", bytes), transcript = buildFecV2ArtifactTranscriptFromCanonicalBytes(descriptor, bytes, { targetCandidateIds: ["H00000001"] });
    expect(transcript.decoded).toMatchObject({ candidateIds: ["H00000001"], scopeConclusion: "inside_candidate_targets" });
  });
});

describe("FEC V2 exact-byte replay boundary", () => {
  const controls = () => ({ signal: new AbortController().signal, deadlineMs: Date.now() + 5_000 });
  const replayBytes = () => encodeFecEnumerationPage({ schema: "fec-v2-enumeration-page-v1", version: 1, planSha256: plan, provenance: { kind: "daily_partition", formType: "F24", receiptDate: "2026-01-02" }, pass: 1, pageNumber: 1, terminal: true, records: [], recordMultiplicity: [] });
  const clientFor = (bytes: Uint8Array) => ({ query: async (sql: string) => sql.includes("fec_v2_artifact_receipts") ? { rows: [{ receipt_id: "receipt", plan_sha256: plan, artifact_sha256: createHash("sha256").update(bytes).digest("hex"), artifact_kind: "enumeration_page", canonical_byte_size: BigInt(bytes.byteLength), upstream_entity_sha256: null, object_key: "fec/replay", version_id: "version", etag: "etag", byte_size: BigInt(bytes.byteLength), retrieved_at: cutoff, snapshot_id: snapshot }] } : { rows: [] } });
  const proof = { proofId: "proof", releaseId: "release", planSha256: plan };
  it("named regression: transcript is always rebuilt from exact-byte verifier output", async () => {
    const bytes = replayBytes(), result = await prepareFecV2ArtifactTranscriptWithClient(clientFor(bytes) as never, proof, { readCanonicalBytes: async () => bytes }, controls());
    expect(result.transcript[0]!.decoded).toMatchObject({ kind: "enumeration_page", terminal: true });
  });
  it("rejects corrupt, wrong, shared, and oversized replay bytes", async () => {
    const genuine = replayBytes(), bad = Uint8Array.from(genuine); bad[0] ^= 1;
    for (const bytes of [bad, new Uint8Array(genuine.byteLength)]) await expect(prepareFecV2ArtifactTranscriptWithClient(clientFor(genuine) as never, proof, { readCanonicalBytes: async () => bytes }, controls())).rejects.toMatchObject({ code: "LAUNCH_PROOF_ARTIFACT" });
    const shared = new Uint8Array(new SharedArrayBuffer(genuine.byteLength)); shared.set(genuine);
    await expect(prepareFecV2ArtifactTranscriptWithClient(clientFor(genuine) as never, proof, { readCanonicalBytes: async () => shared }, controls())).rejects.toMatchObject({ code: "LAUNCH_PROOF_ARTIFACT" });
    await expect(prepareFecV2ArtifactTranscriptWithClient(clientFor(genuine) as never, proof, { readCanonicalBytes: async () => new Uint8Array(64 * 1024 * 1024 + 1) }, controls())).rejects.toMatchObject({ code: "LAUNCH_PROOF_ARTIFACT" });
  });
  it("snapshots mutable verifier bytes before later mutation", async () => {
    const bytes = replayBytes(), pending = prepareFecV2ArtifactTranscriptWithClient(clientFor(bytes) as never, proof, { readCanonicalBytes: async () => { setTimeout(() => bytes.fill(0), 0); return bytes; } }, controls());
    await expect(pending).resolves.toMatchObject({ transcript: [{ decoded: { kind: "enumeration_page" } }] });
    await new Promise(resolve => setTimeout(resolve, 0));
  });
  it("bounds a verifier which ignores cancellation", async () => {
    await expect(prepareFecV2ArtifactTranscriptWithClient(clientFor(replayBytes()) as never, proof, { readCanonicalBytes: async () => new Promise<Uint8Array>(() => undefined) }, { signal: new AbortController().signal, deadlineMs: Date.now() + 20 })).rejects.toMatchObject({ code: "LAUNCH_PROOF_ARTIFACT" });
  });
});

const dataFixture = (): FecV2CanonicalPayload => {
  const p = fixture();
  (p.plan as Record<string, unknown>).origin_release_id = "release";
  (p.targets as FecV2GraphRow[]).push(row({ plan_sha256: plan, seat_cycle_id: "seat-terminal", kind: "terminal", disposition: null, evidence_sha256: null }));
  const writable = p as unknown as { mappings: FecV2GraphRow[]; committees: FecV2GraphRow[]; elections: FecV2GraphRow[]; closures: FecV2GraphRow[]; coverage: FecV2GraphRow[]; closureReceipts: FecV2GraphRow[]; closureSnapshots: FecV2GraphRow[] };
  const mapping = row({ id: "m0", plan_sha256: plan, seat_cycle_id: "seat-0", target_kind: "candidate_resolution_required", outcome: "mapped", fec_candidate_id: "candidate", evidence_sha256: hash(40) });
  const committee = row({ id: "committee", plan_sha256: plan, candidate_mapping_id: "m0", committee_id: "committee-id", designation: "P", evidence_sha256: hash(41) });
  const election = row({ id: "e0", plan_sha256: plan, seat_cycle_id: "seat-0", outcome: "mapped", candidate_mapping_id: "m0", contest_id: "contest", election_code: "G", election_date: "2026-11-03", evidence_sha256: hash(42) });
  const candidate = row({ id: "candidate-close", plan_sha256: plan, seat_cycle_id: "seat-0", target_kind: "candidate_resolution_required", subject_kind: "candidate", subject_identity: "m0", candidate_mapping_id: "m0", status: "finalized", finalized_at: cutoff, subject_sha256: "" });
  const terminal = row({ id: "terminal-close", plan_sha256: plan, seat_cycle_id: "seat-terminal", target_kind: "terminal", subject_kind: "terminal", subject_identity: "terminal", candidate_mapping_id: null, status: "finalized", finalized_at: cutoff, subject_sha256: "" });
  writable.mappings = [mapping]; writable.committees = [committee]; writable.elections = [election]; writable.closures = [candidate, terminal];
  writable.coverage = [row({ plan_sha256: plan, seat_cycle_id: "seat-0", closure_id: "candidate-close", subject_identity: "m0", outcome: "complete_zero", support_cents: BigInt(0), oppose_cents: BigInt(0) }), row({ plan_sha256: plan, seat_cycle_id: "seat-terminal", closure_id: "terminal-close", subject_identity: "terminal", outcome: "complete_zero", support_cents: BigInt(0), oppose_cents: BigInt(0) })];
  writable.closureReceipts = [row({ closure_id: "candidate-close", receipt_id: "r0" }), row({ closure_id: "terminal-close", receipt_id: "r0" })]; writable.closureSnapshots = [row({ closure_id: "candidate-close", snapshot_id: snapshot }), row({ closure_id: "terminal-close", snapshot_id: snapshot })];
  const mappingSubject = { id: "m0", plan_sha256: plan, seat_cycle_id: "seat-0", target_kind: "candidate_resolution_required", outcome: "mapped", fec_candidate_id: "candidate", candidacy_id: undefined, candidacy_contest_id: undefined, evidence_sha256: hash(40) };
  const committeeSubject = { id: "committee", plan_sha256: plan, candidate_mapping_id: "m0", committee_id: "committee-id", designation: "P", evidence_sha256: hash(41) };
  const electionSubject = { id: "e0", plan_sha256: plan, seat_cycle_id: "seat-0", outcome: "mapped", candidate_mapping_id: "m0", contest_id: "contest", election_code: "G", election_date: "2026-11-03", evidence_sha256: hash(42) };
  const closureHash = (closure: FecV2GraphRow, coverage: FecV2GraphRow, state: unknown[], selectedTarget: unknown) => canonicalSha256({ schemaVersion: 2, originReleaseId: "release", acquisitionPlanSha256: plan, subjectType: "finance_closure", subject: { closure: Object.fromEntries(Object.entries(closure).filter(([field]) => field !== "finalized_at" && field !== "subject_sha256")), selectedTarget, coverage, receiptIds: ["r0"], snapshotIds: [snapshot], candidateStateSha256: canonicalSha256(state), scopingStateSha256: fecV2ClosureScopingStateSha256(p, String(closure.id)) } });
  (candidate as Record<string, unknown>).subject_sha256 = closureHash(candidate, p.coverage[0]!, [{ subjectType: "committee_mapping", subject: committeeSubject }, { subjectType: "fec_mapping", subject: mappingSubject }, { subjectType: "outside_spending_election_mapping", subject: electionSubject }].sort((a, b) => canonical(a).localeCompare(canonical(b))), { seatCycleId: "seat-0", kind: "candidate_resolution_required", disposition: null, evidenceSha256: null });
  (terminal as Record<string, unknown>).subject_sha256 = closureHash(terminal, p.coverage[1]!, [], { seatCycleId: "seat-terminal", kind: "terminal", disposition: null, evidenceSha256: null });
  return p;
};
const keyMaterial = () => { const pair = generateKeyPairSync("ed25519"); const publicKey = pair.publicKey.export({ type: "spki", format: "pem" }).toString(); return { publicKey, fingerprint: createHash("sha256").update(pair.publicKey.export({ type: "spki", format: "der" })).digest("hex") }; };
const signatures = (p: FecV2CanonicalPayload) => { const key = keyMaterial(); (p as unknown as { dataSignatures: FecV2GraphRow[] }).dataSignatures = buildFecV2ExpectedDataReviews(p).map(review => row({ review_id: review.reviewId, plan_sha256: plan, origin_release_id: "release", subject_type: review.subjectType, subject_sha256: review.subjectSha256, reviewer_id: "reviewer", key_id: "key", public_key_fingerprint: key.fingerprint, signed_at: "2026-07-17T00:00:00.000Z", signature: "ok" })); return key; };
const resolver = (key: ReturnType<typeof keyMaterial>, overrides = {}): PublicKeyResolver => ({ resolve: async () => ({ publicKey: key.publicKey, publicKeyFingerprint: key.fingerprint, reviewerRole: "data_reviewer", allowedSubjectTypes: ["fec_mapping", "committee_mapping", "outside_spending_election_mapping", "finance_page_closure", "finance_amendment_closure", "finance_closure", "outside_spending_closure", "finance_terminal"], validFrom: new Date("2020-01-01T00:00:00.000Z"), validUntil: null, revokedAt: null, ...overrides }) });

describe("FEC V2 data reviews", () => {
  it("has the exact vocabulary, count, and bytewise review-ID order", () => { const reviews = buildFecV2ExpectedDataReviews(dataFixture()); expect(reviews).toHaveLength(9); expect(new Set(reviews.map(x => x.subjectType))).toEqual(new Set(["fec_mapping", "committee_mapping", "outside_spending_election_mapping", "finance_page_closure", "finance_amendment_closure", "finance_closure", "outside_spending_closure", "finance_terminal"])); expect(reviews.map(x => x.reviewId)).toEqual([...reviews.map(x => x.reviewId)].sort((a, b) => Buffer.compare(Buffer.from(a), Buffer.from(b)))); });
  it("ignores excluded fields and finalization timestamps", () => { const p = dataFixture(), before = buildFecV2ExpectedDataReviews(p); (p.closures[0] as Record<string, unknown>).created_at = cutoff; (p.closures[0] as Record<string, unknown>).finalized_at = "2026-07-19T00:00:00.000Z"; (p.filingLedgers[0] as Record<string, unknown>).finalized_at = "2026-07-19T00:00:00.000Z"; expect(buildFecV2ExpectedDataReviews(p).map(review => ({ ...review, finalizesAt: "" }))).toEqual(before.map(review => ({ ...review, finalizesAt: "" }))); });
  it("binds mapping and selected terminal evidence", () => { const p = dataFixture(), before = buildFecV2ExpectedDataReviews(p); (p.mappings[0] as Record<string, unknown>).evidence_sha256 = hash(88); expect(() => buildFecV2ExpectedDataReviews(p)).toThrow(LaunchProofError); const q = dataFixture(); const terminal = q.targets.find(target => target.seat_cycle_id === "seat-terminal") as Record<string, unknown>; terminal.evidence_sha256 = hash(89); expect(() => buildFecV2ExpectedDataReviews(q)).toThrow(LaunchProofError); const r = dataFixture(); (r.targets.find(target => target.seat_cycle_id === "seat-terminal") as Record<string, unknown>).disposition = "vacant"; expect(() => buildFecV2ExpectedDataReviews(r)).toThrow(LaunchProofError); expect(before).toHaveLength(9); });
  it("changes for semantic ledger input", () => { const p = dataFixture(), before = buildFecV2ExpectedDataReviews(p); (p.filingLedgerEntries[0] as Record<string, unknown>).report_date = "2026-01-01"; expect(buildFecV2ExpectedDataReviews(p)).not.toEqual(before); });
  it("binds only closure-local sanitized scoping artifacts and alternates", () => {
    const p = dataFixture(), closure = String(p.closures[0]!.id), before = fecV2ClosureScopingStateSha256(p, closure);
    (p.sanitizedFilings[0] as Record<string, unknown>).report_date = "2026-01-01";
    expect(fecV2ClosureScopingStateSha256(p, closure)).toBe(before);
    (p.closureReceipts as FecV2GraphRow[]).push(row({ closure_id: closure, receipt_id: "sanitized" }));
    const included = fecV2ClosureScopingStateSha256(p, closure);
    expect(included).not.toBe(before);
    (p.alternateScoping as FecV2GraphRow[]).push(row({ plan_sha256: plan, ledger_sha256: hash(5000), file_number: "file", sanitized_artifact_sha256: hash(5001), conclusion: "outside_candidate_targets" }));
    expect(fecV2ClosureScopingStateSha256(p, closure)).not.toBe(included);
    expect(() => buildFecV2ExpectedDataReviews(p)).toThrow(LaunchProofError);
  });
  it("rejects a stored closure hash mismatch", () => { const p = dataFixture(); (p.closures[0] as Record<string, unknown>).subject_sha256 = hash(7); expect(() => buildFecV2ExpectedDataReviews(p)).toThrow(LaunchProofError); });
  it("verifies every exact expected signature and returns de-duplicated identities", async () => { const p = dataFixture(), key = signatures(p); let calls = 0; const verifier: SignatureVerifier = { verify: async () => (calls += 1, true) }; const result = await verifyFecV2DataReviewSignatures(p, resolver(key), verifier); expect(calls).toBe(9); expect(result.reviewerIds).toEqual(new Set(["reviewer"])); expect(result.fingerprints).toEqual(new Set([key.fingerprint])); });
  it("rejects missing, extra, and duplicate signatures", async () => { for (const mutate of [(p: FecV2CanonicalPayload) => (p.dataSignatures as FecV2GraphRow[]).pop(), (p: FecV2CanonicalPayload) => (p.dataSignatures as FecV2GraphRow[]).push(p.dataSignatures[0]!), (p: FecV2CanonicalPayload) => (p.dataSignatures as FecV2GraphRow[])[1] = p.dataSignatures[0]!]) { const p = dataFixture(), key = signatures(p); mutate(p); await expect(verifyFecV2DataReviewSignatures(p, resolver(key), { verify: async () => true })).rejects.toThrow(LaunchProofError); } });
  it("rejects wrong type, hash, origin, plan, and review ID", async () => { for (const field of ["subject_type", "subject_sha256", "origin_release_id", "plan_sha256", "review_id"]) { const p = dataFixture(), key = signatures(p); (p.dataSignatures[0] as Record<string, unknown>)[field] = field === "subject_type" ? "wrong" : field === "review_id" ? "wrong" : hash(77); await expect(verifyFecV2DataReviewSignatures(p, resolver(key), { verify: async () => true })).rejects.toThrow(LaunchProofError); } });
  it("rejects stored and resolver fingerprint mismatches and non-Ed25519 keys", async () => { let p = dataFixture(), key = signatures(p); (p.dataSignatures[0] as Record<string, unknown>).public_key_fingerprint = hash(9); await expect(verifyFecV2DataReviewSignatures(p, resolver(key), { verify: async () => true })).rejects.toThrow(LaunchProofError); p = dataFixture(); key = signatures(p); await expect(verifyFecV2DataReviewSignatures(p, resolver(key, { publicKeyFingerprint: hash(8) }), { verify: async () => true })).rejects.toThrow(LaunchProofError); const rsa = generateKeyPairSync("rsa", { modulusLength: 2048 }).publicKey.export({ type: "spki", format: "pem" }).toString(); await expect(verifyFecV2DataReviewSignatures(p, resolver(key, { publicKey: rsa }), { verify: async () => true })).rejects.toThrow(LaunchProofError); });
  it("rejects invalid role, allowlist, window, revocation, cryptographic false, late, and future signatures", async () => { for (const overrides of [{ reviewerRole: "release_approver" }, { allowedSubjectTypes: [] }, { validUntil: new Date("2025-01-01T00:00:00.000Z") }, { revokedAt: new Date("2025-01-01T00:00:00.000Z") }]) { const p = dataFixture(), key = signatures(p); await expect(verifyFecV2DataReviewSignatures(p, resolver(key, overrides), { verify: async () => true })).rejects.toThrow(LaunchProofError); } const p = dataFixture(), key = signatures(p); await expect(verifyFecV2DataReviewSignatures(p, resolver(key), { verify: async () => false })).rejects.toThrow(LaunchProofError); (p.dataSignatures[0] as Record<string, unknown>).signed_at = "2026-07-19T00:00:00.000Z"; await expect(verifyFecV2DataReviewSignatures(p, resolver(key), { verify: async () => true })).rejects.toThrow(LaunchProofError); (p.dataSignatures[0] as Record<string, unknown>).signed_at = "2030-01-01T00:00:00.000Z"; await expect(verifyFecV2DataReviewSignatures(p, resolver(key), { verify: async () => true })).rejects.toThrow(LaunchProofError); });
  it("rejects a signature exactly at finalization", async () => { const p = dataFixture(), key = signatures(p); (p.dataSignatures[0] as Record<string, unknown>).signed_at = cutoff; await expect(verifyFecV2DataReviewSignatures(p, resolver(key), { verify: async () => true })).rejects.toThrow(LaunchProofError); });
});

const publicationFixture = () => {
  const payload = dataFixture();
  Object.assign(payload.plan as Record<string, unknown>, { plan_sha256: plan, sealed_at: cutoff });
  const key = keyMaterial(), canonicalHash = canonicalSha256(payload);
  const signatureId = `fecv2pub_${canonicalSha256({ releaseId: "release", acquisitionPlanSha256: plan, subjectSha256: canonicalHash }).slice(0, 32)}`;
  const evidence = { publicationSignatures: [{ signature_id: signatureId, plan_sha256: plan, canonical_sha256: canonicalHash, reviewer_id: "approver", signed_at: "2026-07-19T00:00:00.000Z", signature: "ok", key_id: "publication-key", public_key_fingerprint: key.fingerprint }], publicationProofs: [{ proof_id: "proof", signature_id: signatureId, plan_sha256: plan, canonical_sha256: canonicalHash, created_at: "2026-07-19T00:00:01.000Z" }] };
  const dataReviewResult = { reviewerIds: new Set(["reviewer"]), fingerprints: new Set([hash(2)]), latestSignedAt: "2026-07-17T00:00:00.000Z" };
  const publicationResolver = (overrides = {}): PublicKeyResolver => resolver(key, { reviewerRole: "release_approver", allowedSubjectTypes: ["publication"], ...overrides });
  return { payload, key, canonicalHash, evidence, dataReviewResult, publicationResolver };
};
const verifyPublication = (fixtureValue: ReturnType<typeof publicationFixture>, overrides: { resolver?: PublicKeyResolver; verifier?: SignatureVerifier; verifiedAt?: Date | string } = {}) => verifyFecV2PublicationEvidence(fixtureValue.payload, fixtureValue.payload.proof, fixtureValue.evidence, fixtureValue.dataReviewResult, overrides.resolver ?? fixtureValue.publicationResolver(), overrides.verifier ?? { verify: async () => true }, overrides.verifiedAt ?? "2026-07-20T00:00:00.000Z");

describe("FEC V2 publication evidence", () => {
  it("uses only actual publication-proof columns", async () => { const fakeClient = { query: async (sql: string) => { if (/plan_sha256/.test(sql)) throw new Error("publication proofs do not have plan_sha256"); return { rows: [] }; } }; await expect(fakeClient.query(fecV2PublicationProofQuery)).resolves.toEqual({ rows: [] }); });
  it("accepts exact evidence, calls crypto once, and returns its canonical hash", async () => { const f = publicationFixture(); let calls = 0; await expect(verifyPublication(f, { verifier: { verify: async () => (calls += 1, true) } })).resolves.toBe(f.canonicalHash); expect(calls).toBe(1); });
  it("rejects missing or extra release-local signatures and proofs", async () => { for (const mutate of [(f: ReturnType<typeof publicationFixture>) => f.evidence.publicationSignatures.pop(), (f: ReturnType<typeof publicationFixture>) => f.evidence.publicationProofs.pop(), (f: ReturnType<typeof publicationFixture>) => f.evidence.publicationSignatures.push({ ...f.evidence.publicationSignatures[0]! }), (f: ReturnType<typeof publicationFixture>) => f.evidence.publicationProofs.push({ ...f.evidence.publicationProofs[0]! })]) { const f = publicationFixture(); mutate(f); await expect(verifyPublication(f)).rejects.toThrow(LaunchProofError); } });
  it("rejects proof linkage, requested ID, plan, hash, and deterministic signature-ID defects", async () => { for (const mutate of [(f: ReturnType<typeof publicationFixture>) => f.evidence.publicationProofs[0]!.signature_id = "other", (f: ReturnType<typeof publicationFixture>) => f.evidence.publicationProofs[0]!.proof_id = "other", (f: ReturnType<typeof publicationFixture>) => f.evidence.publicationSignatures[0]!.plan_sha256 = hash(4), (f: ReturnType<typeof publicationFixture>) => f.evidence.publicationProofs[0]!.canonical_sha256 = hash(5), (f: ReturnType<typeof publicationFixture>) => f.evidence.publicationSignatures[0]!.signature_id = "wrong"]) { const f = publicationFixture(); mutate(f); await expect(verifyPublication(f)).rejects.toThrow(LaunchProofError); } });
  it("rejects reviewer and fingerprint separation independently", async () => { let f = publicationFixture(); f.evidence.publicationSignatures[0]!.reviewer_id = "reviewer"; await expect(verifyPublication(f)).rejects.toThrow(LaunchProofError); f = publicationFixture(); f.evidence.publicationSignatures[0]!.public_key_fingerprint = hash(2); await expect(verifyPublication(f)).rejects.toThrow(LaunchProofError); });
  it("rejects bad stored/resolved fingerprints, RSA keys, policy failures, and crypto false", async () => { let f = publicationFixture(); f.evidence.publicationSignatures[0]!.public_key_fingerprint = hash(6); await expect(verifyPublication(f)).rejects.toThrow(LaunchProofError); const cases: ((f: ReturnType<typeof publicationFixture>) => PublicKeyResolver)[] = [f => f.publicationResolver({ publicKeyFingerprint: hash(7) }), f => f.publicationResolver({ publicKey: generateKeyPairSync("rsa", { modulusLength: 2048 }).publicKey.export({ type: "spki", format: "pem" }).toString() }), f => f.publicationResolver({ reviewerRole: "data_reviewer" }), f => f.publicationResolver({ allowedSubjectTypes: [] }), f => f.publicationResolver({ validUntil: new Date("2020-01-01T00:00:00.000Z") }), f => f.publicationResolver({ revokedAt: new Date("2020-01-01T00:00:00.000Z") })]; for (const make of cases) { f = publicationFixture(); await expect(verifyPublication(f, { resolver: make(f) })).rejects.toThrow(LaunchProofError); } f = publicationFixture(); await expect(verifyPublication(f, { verifier: { verify: async () => false } })).rejects.toThrow(LaunchProofError); });
  it("requires publication signing strictly after all data and finalization boundaries", async () => { for (const signedAt of ["2026-07-17T00:00:00.000Z", cutoff]) { const f = publicationFixture(); f.evidence.publicationSignatures[0]!.signed_at = signedAt; await expect(verifyPublication(f)).rejects.toThrow(LaunchProofError); } await expect(verifyPublication(publicationFixture())).resolves.toBeTruthy(); });
  it("rejects proof creation at or before signing and future publication evidence", async () => { let f = publicationFixture(); f.evidence.publicationProofs[0]!.created_at = "2026-07-18T00:00:00.000Z"; await expect(verifyPublication(f)).rejects.toThrow(LaunchProofError); f = publicationFixture(); f.evidence.publicationProofs[0]!.created_at = f.evidence.publicationSignatures[0]!.signed_at; await expect(verifyPublication(f)).rejects.toThrow(LaunchProofError); f = publicationFixture(); f.evidence.publicationSignatures[0]!.signed_at = "2026-07-21T00:00:00.000Z"; f.evidence.publicationProofs[0]!.created_at = "2026-07-21T00:00:01.000Z"; await expect(verifyPublication(f)).rejects.toThrow(LaunchProofError); });
  it("resolves once and verifies with the initially fingerprint-checked key", async () => { const f = publicationFixture(); let calls = 0; const first = await f.publicationResolver().resolve("publication-key", "approver"); const unstable: PublicKeyResolver = { resolve: async () => { calls += 1; return calls === 1 ? first : { ...first!, publicKeyFingerprint: hash(8) }; } }; let verifiedKey = ""; await expect(verifyPublication(f, { resolver: unstable, verifier: { verify: async (_payload, _signature, publicKey) => (verifiedKey = publicKey, true) } })).resolves.toBeTruthy(); expect(calls).toBe(1); expect(verifiedKey).toBe(first!.publicKey); });
});
