import type { Metadata } from "next";
import Link from "next/link";
import { loadMethodologyPage } from "@/ui/server-data";
import { Shell, RouteState, fmtDate } from "@/components/presentational";
import { housePriorityBriefsV11 } from "@/lib/house-priority-index";
import { loadRapidExpansionStatus } from "@/ui/rapid-expansion-status";
import { getDefaultPriorityRepository } from "@/lib/priority-index-store";

export const dynamic = "force-dynamic";
export const metadata: Metadata = { title: "Method", description: "How the Priority Index score is built: routes, weights, formulas, missing-data rules, and limits." };

export default async function Methodology() {
  const [result, expansionStatus] = await Promise.all([loadMethodologyPage(), loadRapidExpansionStatus()]);
  if (!result.ok) return <RouteState code={result.code} />;
  const { value: page } = result;
  const rows = housePriorityBriefsV11();
  const model = getDefaultPriorityRepository().getModelRelease();
  const democrats = rows.filter((row) => row.incumbentParty === "Democratic");
  const republicans = rows.filter((row) => row.incumbentParty === "Republican");
  const covered = (key: string, candidates = rows) => candidates.filter((row) => row.scoreDrivers.some((driver) => driver.key === key && driver.score !== null)).length;

  return <Shell release={page.release}><main id="content" className="page method-page">
    <p className="eyebrow">METHOD · INDEX MODEL {model.version} · FACTUAL RELEASE {page.release.label}</p><h1>How the Priority Index works</h1>
    <p className="lede">The score is a comparative research index from 0–100. It helps order where investigation may be most useful; it is not a win probability, polling estimate, endorsement, or prediction. Source cutoff: {fmtDate(page.release.sourceCutoff)}.</p>

    <dl className="method-principles">
      <div><dt>Higher means</dt><dd>More structural or political reason to investigate the seat as an organizing opportunity.</dd></div>
      <div><dt>Missing means missing</dt><dd>An unavailable component is omitted and the remaining weights are renormalized. Missing never becomes zero.</dd></div>
      <div><dt>Two distinct routes</dt><dd>Democratic primary opportunities and Republican-held general-election fringes use different formulas.</dd></div>
    </dl>

    <section className="record-section"><div className="section-heading-pair"><div><p className="eyebrow">WEIGHT MATRIX</p><h2>What changes the final score</h2></div><p>Weights apply only inside the relevant party route. AIPAC support and primary feasibility help select the Democratic structural baseline; they are not added again afterward.</p></div>
      <div className="table-wrap method-weight-table" role="region" tabIndex={0} aria-label="Priority Index weight matrix"><table><thead><tr><th>Component</th><th>Democratic-held seat</th><th>Republican-held seat</th><th>Meaning</th></tr></thead><tbody>
        <tr><td><strong>Structural opportunity</strong></td><td>65% of final score</td><td>—</td><td>Stronger of the deep-blue and AIPAC-supported blue routes.</td></tr>
        <tr><td><strong>Incumbent alignment gap</strong></td><td>20% of final score</td><td>—</td><td>Distance from full alignment on the retained issue trackers.</td></tr>
        <tr><td><strong>Cash vulnerability</strong></td><td>15% of final score</td><td>20% of route weight</td><td>Lower incumbent cash produces a higher vulnerability score.</td></tr>
        <tr><td><strong>Local context</strong></td><td>20% of structural baseline when exact</td><td>15% of route weight when exact</td><td>Turnout, registration, and demographics for complete at-large county joins only.</td></tr>
        <tr><td><strong>General-election competitiveness</strong></td><td>—</td><td>45% of route weight</td><td>Closeness of the district&apos;s retained 2024 presidential result.</td></tr>
        <tr><td><strong>State Democratic primary contestation</strong></td><td>—</td><td>20% of route weight when retained</td><td>Share of the state&apos;s retained state-legislative Democratic primaries that drew more than one candidate.</td></tr>
        <tr><td><strong>Coverage multiplier</strong></td><td>—</td><td>0.6 + 0.4 × available weight</td><td>Scales the renormalized route by how much of its evidence is present: 0.78 with competitiveness alone, 1.0 with every component.</td></tr>
      </tbody></table></div>
    </section>

    <section className="record-section"><p className="eyebrow">DEMOCRATIC-HELD SEATS</p><h2>Primary-opportunity model</h2><p>The Democratic field starts with the stronger available structural route, then adds incumbent alignment and campaign-finance vulnerability.</p>
      <div className="method-grid"><article><h3>Deep-blue route</h3><code>0.70 × blue baseline + 0.30 × primary feasibility</code><p>Rewards safe Democratic districts where the retained primary evidence indicates a challenge may be structurally plausible.</p></article><article><h3>AIPAC-supported blue route</h3><code>0.60 × AIPAC support + 0.25 × blue baseline + 0.15 × primary feasibility</code><p>Available only when retained numeric AIPAC evidence exists. The higher available structural route becomes the baseline.</p></article></div>
      <div className="formula-block"><span>Exact-context structural baseline</span><code>0.80 × prior structural baseline + 0.20 × local context</code><span>Final Democratic score</span><code>0.65 × structural baseline + 0.20 × alignment gap + 0.15 × cash vulnerability</code></div>
    </section>

    <section className="record-section"><p className="eyebrow">REPUBLICAN-HELD SEATS</p><h2>Republican-held flip screen</h2><p>Republican seats combine district competitiveness, incumbent cash vulnerability, exact at-large local context, and state-level Democratic primary contestation. They do not receive invented Democratic-primary, AIPAC, or Democratic-incumbent alignment values.</p>
      <div className="formula-block"><span>District competitiveness</span><code>clamp(100 − 4 × max(0, Republican margin), 0, 100)</code><span>Route weights</span><code>0.45 × competitiveness + 0.20 × cash vulnerability + 0.15 × local context + 0.20 × state contestation</code><span>Available weight W</span><code>sum of the weights whose component is present</code><span>Final Republican score</span><code>(weighted sum ÷ W) × (0.6 + 0.4 × W)</code></div>
      <p>V0.9 removed the flat 0.70 multiplier. A missing component is omitted and the rest are renormalized, then the route is scaled by how much of its evidence is present: 0.78 with competitiveness alone and 1.0 with all four components. The penalty is for missing evidence, not for party, and no seat is clamped.</p>
    </section>

    <section className="record-section"><div className="section-heading-pair"><div><p className="eyebrow">COMPONENT DICTIONARY</p><h2>What every number represents</h2></div><p>Every component is expressed on a 0–100 scale. A high component always increases priority; it does not necessarily mean the underlying raw value is high.</p></div><div className="table-wrap component-dictionary" role="region" tabIndex={0} aria-label="Component dictionary. Scroll horizontally to view all columns."><table><thead><tr><th scope="col">Component</th><th scope="col">Evidence</th><th scope="col">What it measures</th></tr></thead><tbody>
        <tr><th scope="row">Blue baseline</th><td>structural</td><td>District Democratic strength derived from the retained 2024 presidential result. Higher values indicate a safer Democratic baseline.</td></tr>
        <tr><th scope="row">Primary feasibility</th><td>contest evidence</td><td>For 22 linked 2024 incumbent contests, this is 100 minus the incumbent&apos;s share of all retained Democratic-primary contest votes. Nineteen links use exact normalized names, two use documented name relationships, and RI-01 uses a reviewed alias. Other seats retain the earlier partial estimate. It is not a challenger forecast or winner claim.</td></tr>
        <tr><th scope="row">AIPAC support</th><td>FEC evidence</td><td>Numeric retained evidence connected to the AIPAC network. Tracker labels may add context, but are not counted a second time.</td></tr>
        <tr><th scope="row">Incumbent alignment gap</th><td>voting-record gap</td><td>Distance between retained Left and Palestine tracker scores and full alignment. Available trackers are normalized and partial coverage receives a missingness penalty.</td></tr>
        <tr><th scope="row">Cash vulnerability</th><td>FEC finance</td><td>An inverse logarithmic cash-on-hand scale. It measures the incumbent&apos;s financial vulnerability, not challenger fundraising strength. Since v0.10 the value comes from the FEC candidate summary snapshot named by the refresh pointer and is the one component that moves on refresh.</td></tr>
        <tr><th scope="row">General-election competitiveness</th><td>Republican route</td><td>Closeness of a Republican-held district using the 2024 presidential result. A tied district starts at 100; every Republican margin point subtracts four.</td></tr>
        <tr><th scope="row">State Democratic primary contestation</th><td>Republican route</td><td>Share of the state&apos;s latest retained state-legislative Democratic primaries that drew more than one named candidate, scaled so a 40% contested share is 100. Six states carry a value; catalogs that retain only contested primaries are ineligible. It is state-level organizing context, not a district measure.</td></tr>
        <tr><th scope="row">Local context</th><td>exact county joins</td><td>An available-weight blend of inverse turnout/CVAP, inverse registration/CVAP, down-ballot overperformance, and demographic opportunity. DE-AL, SD-AL, and WY-AL have all weights; ND-AL has 70% and renormalizes the available weights.</td></tr>
      </tbody></table></div></section>

    <section className="record-section"><div className="section-heading-pair"><div><p className="eyebrow">CASH SCALE</p><h2>Why the finance curve is logarithmic</h2></div><p>Campaign cash spans orders of magnitude. A logarithmic curve prevents one very large account from flattening meaningful differences among lower-cash incumbents.</p></div>
      <div className="formula-block"><span>Cash vulnerability</span><code>100 × (1 − log(cash ÷ $50,000) ÷ log(100))</code><small>Clamped to 100 at $50,000 or less and 0 at $5 million or more.</small></div>
      <div className="cash-anchors" aria-label="Cash vulnerability scale anchors"><article><strong>$50K</strong><span>100</span><small>Most vulnerable anchor</small></article><article><strong>$500K</strong><span>50</span><small>Midpoint</small></article><article><strong>$5M</strong><span>0</span><small>Least vulnerable anchor</small></article></div>
    </section>

    <section className="record-section"><p className="eyebrow">MISSING DATA</p><h2>Omission, not punishment</h2><p>If cash is not reported, its weight is removed and available inputs are renormalized. The three affected seats are not assigned a zero cash score.</p>
      <div className="method-grid"><article><h3>Democratic seat without cash</h3><code>(0.65 × baseline + 0.20 × alignment) ÷ 0.85</code><p>Preserves the ratio between structural and alignment evidence.</p></article><article><h3>Republican seat with competitiveness only</h3><code>competitiveness × (0.6 + 0.4 × 0.45)</code><p>Renormalizes to the one present component, then scales by its 45% coverage.</p></article></div>
      <ul><li>Missing AIPAC evidence makes that structural route unavailable; it does not produce an AIPAC score of zero.</li><li>Non-applicable components are shown as an em dash on the opposite party route.</li><li>Receipts and disbursements remain context only and are not substitutes for missing cash.</li></ul>
    </section>

    <section className="record-section"><div className="section-heading-pair"><div><p className="eyebrow">HOUSE LAYER V0.9</p><h2>Direct primary evidence with identity and geography gates</h2></div><p>House rows in index model {model.version} are scored with the v0.9 House formula. It activates a 2024 primary component only when the retained candidate name is linked to the current incumbent and the contest district is the same CD119 key. The metric is <code>100 − incumbent vote share</code>; source winner markers never drive the calculation.</p></div>
      <div className="method-grid"><article><h3>Primary identity gate</h3><code>current House identity + retained candidate-name evidence</code><p>Nineteen rows use exact normalized names, two use documented name relationships, and RI-01 uses a reviewed alias that bridges the source spelling Gabriel Amo to the House name Gabe Amo. The alias table is a retained, hash-pinned editorial ledger with the reviewer and date recorded.</p></article><article><h3>Primary geography gate</h3><code>2024 contest session 119 + exact district key</code><p>No historical crosswalk or same-number assumption is used. The 22 admitted rows then replace, rather than stack on top of, the earlier inferred primary component.</p></article></div>
      <p>{expansionStatus ? `Current active closure: ${expansionStatus.score.directPrimaryActiveSeats} direct primary rows, ${expansionStatus.score.unresolvedPrimaryRows} unresolved identity rows, ${expansionStatus.score.republicanSeatsWithStateContestation} Republican seats with state contestation, and ${expansionStatus.score.unchangedSeats} seats unchanged from v0.8.` : "The retained v0.9 projection is unavailable."}</p>
    </section>

    <section className="record-section"><div className="section-heading-pair"><div><p className="eyebrow">LOCAL CONTEXT</p><h2>County context with an exact-geography gate</h2></div><p>Four complete at-large county universes add a House-versus-presidential component only where every county closes against the current Census universe. A local score requires at least 60% of the component weight and a direct turnout or registration measure.</p></div>
      <div className="method-grid"><article><h3>Demographic opportunity</h3><code>.35 renter + .25 age 18–34 + .25 inverse income + .15 density</code><p>Each county measure becomes a within-state midrank percentile, then county percentiles are population-weighted into an exact district geography.</p></article><article><h3>Local context</h3><code>.40 inverse ballots/CVAP + .30 inverse registration/CVAP + .20 down-ballot overperformance + .10 demographics</code><p>Down-ballot overperformance is <code>clamp(50 + 5 × (House D share − Harris share), 0, 100)</code>. House share counts candidate votes, including write-ins, and excludes overvotes and undervotes.</p></article></div>
      <div className="formula-block"><span>Expanded structural score</span><code>.80 × current structural + .20 × local context</code><small>Only exact at-large or whole-county CD119 joins may qualify. Split counties remain unavailable until an authoritative allocation is retained.</small></div>
      <p>{expansionStatus ? `Current local-context closure: ${expansionStatus.score.localContextActiveSeats} seats (${expansionStatus.score.activeDistricts.map((row) => row.districtLabel).join(", ")}) have exact local context and the House comparison. ND-AL is the one partial-component activation.` : "The retained v0.9 projection is unavailable."}</p>
      <p>South Dakota uses one bounded identifier correction: the source already labels the county Oglala Lakota but carries obsolete FIPS 46113. The Census Bureau states that Shannon County (46-113) changed name and code to Oglala Lakota County (46-102) effective May 1, 2015. V0.6 applied only that documented substitution; v0.7 preserves it unchanged.</p>
      <p>North Dakota has complete 2024 ballots and CVAP values for all 53 counties, complete county demographics, and a complete at-large House comparison. Active-registration values are unavailable in the retained EAVS rows, so that 30% subweight is omitted—not set to zero—and the available 70% is renormalized. The resulting local-context value is 63.3.</p>
    </section>

    <section className="record-section"><div className="section-heading-pair"><div><p className="eyebrow">SENATE V0.1</p><h2>Same routes, statewide inputs</h2></div><p>Senate seats use the chamber-agnostic scorer: the Democratic-caucus route is <code>renormalized(0.65 × structural + 0.20 × alignment gap + 0.15 × cash) × (0.6 + 0.4 W)</code> and the Republican route is the v0.9 formula above. The blue baseline and competitiveness come from the statewide 2024 presidential result; only 2024 is retained statewide, so no multi-cycle floor applies.</p></div>
      <div className="method-grid"><article><h3>What is measured</h3><code>statewide margin · FEC candidate summary cash · 119th Senate tracker sheets · state contestation</code><p>{expansionStatus ? `${expansionStatus.senate.cashValues} of 100 senators have a cash value, ${expansionStatus.senate.alignmentValues} Democratic-caucus members have tracker alignment, and ${expansionStatus.senate.stateContestationValues} Republican seats carry state contestation.` : "The retained Senate projection is unavailable."}</p></article><article><h3>What is omitted</h3><code>primary feasibility · AIPAC support · local context</code><p>No Senate primary evidence or Senate AIPAC evidence is retained, so those weights are removed and the rest renormalized. Independents who caucus with Democrats take the Democratic route and are labelled.</p></article></div>
    </section>

    <section className="record-section"><div className="section-heading-pair"><div><p className="eyebrow">GOVERNORS V0.1</p><h2>Fifty governorships, statewide inputs only</h2></div><p>Governors use the same two routes as the Senate with the statewide 2024 presidential result and, where retained, state Democratic primary contestation. No governor finance, alignment, or primary evidence is retained, so those weights are omitted and the rest renormalized; the Democratic route reduces to the blue baseline. The holder, party, and term end come from the Open States executive rosters (CC0); term limits and retirements are not observed.</p></div></section>

    <section className="record-section"><div className="section-heading-pair"><div><p className="eyebrow">STATE LEGISLATURES</p><h2>Own-race margins, one state at a time</h2></div><p>{expansionStatus ? `${expansionStatus.stateLegislative.legislators.toLocaleString("en-US")} sitting legislators across ${expansionStatus.stateLegislative.chambers} chambers are retained from the Open States roster snapshot of ${expansionStatus.stateLegislative.snapshotDate}. ${expansionStatus.stateLegislative.primaryMatched} Democratic holders in the ${expansionStatus.stateLegislative.catalogStates} catalog states match a candidate in their latest retained Democratic primary, which gives a direct primary feasibility value.` : "The retained state-legislative roster is unavailable."} {expansionStatus?.stateLegislative.scored ? `${expansionStatus.stateLegislative.scored.seats.toLocaleString("en-US")} seats in ${expansionStatus.stateLegislative.scored.coveredStates.join(", ")} are ranked on the same two routes as Congress. Their district baseline is the seat's own most recent general-election margin from the state election authority's official returns, not a presidential overlay, because no open nationwide file gives presidential results by legislative district. An uncontested race counts as the maximum margin, so ${expansionStatus.stateLegislative.scored.uncontestedBaselines} of those seats carry a baseline of 100 or 0 with no finer signal; ${expansionStatus.stateLegislative.scored.primaryFeasibilityValues} Democratic seats add retained primary evidence. Seats in other states stay unranked until their returns are retained.` : "No state-legislative seats are ranked yet."}</p></div></section>

    <section className="record-section"><p className="eyebrow">WORKED EXAMPLES</p><h2>Two hypothetical seats</h2><div className="worked-examples"><article><span>Democratic-held</span><h3>Baseline 80 · alignment 60 · cash 40</h3><code>(.65 × 80) + (.20 × 60) + (.15 × 40) = 70.0</code><p>A solid structural opportunity with a moderate alignment gap and stronger incumbent finances.</p></article><article><span>Republican-held</span><h3>Competitiveness 80 · cash 60 · no local or state context</h3><code>((.45 × 80) + (.20 × 60)) ÷ .65 × (.6 + .4 × .65) = 63.5</code><p>A competitive fringe seat scaled to 86% because 35% of its route evidence is missing.</p></article></div></section>

    <section className="record-section"><p className="eyebrow">READING THE RESULT</p><h2>Score bands are triage labels</h2><div className="score-bands"><article><strong>80–100</strong><span>Investigate first</span></article><article><strong>60–79.9</strong><span>Strong case</span></article><article><strong>40–59.9</strong><span>Watchlist</span></article><article><strong>0–39.9</strong><span>Lower relative priority</span></article></div><p>These bands help read a long ranked list. They are not calibrated probabilities, quality grades, endorsement thresholds, or promises of electoral viability.</p></section>

    <section className="record-section"><div className="section-heading-pair"><div><p className="eyebrow">HOUSE MODEL COVERAGE</p><h2>The House denominator behind the method</h2></div><p>These counts are calculated from the House records displayed by the Priority Index. Senate, governor, and state-legislative coverage is given in their sections above.</p></div><div className="method-coverage"><article><strong>{rows.length}</strong><span>ranked House seats</span></article><article><strong>{democrats.length}</strong><span>Democratic seats</span></article><article><strong>{republicans.length}</strong><span>Republican seats</span></article><article><strong>{covered("cash_vulnerability")}</strong><span>cash values</span></article><article><strong>{covered("aipac_support", democrats)}</strong><span>numeric AIPAC values</span></article><article><strong>{covered("incumbent_alignment_gap", democrats)}</strong><span>alignment values</span></article><article><strong>{covered("state_primary_contestation", republicans)}</strong><span>state contestation values</span></article></div></section>

    <section className="record-section"><p className="eyebrow">LIMITS & DATA DISCIPLINE</p><h2>What the index still does not know</h2><ul><li>It does not yet model challenger cash, candidate quality, endorsements, polling, race ratings, field capacity, or local organizing strength.</li><li>Historical primary coverage is not complete in every state and cycle. The rapid ledger is separately reported on the Sources page; only 22 identity- and geography-gated 2024 rows enter v0.9.</li><li>County demographics, registration, and turnout affect the active score only for DE-AL, ND-AL, SD-AL, and WY-AL. Split-county seats remain unchanged until an authoritative allocation is retained.</li><li>The 2024 county House projection is a research fallback. It is used only where the entire current at-large county universe and candidate denominator close exactly; it remains excluded everywhere else.</li><li>ND-AL has no retained active-registration value. The score visibly reports 70% local evidence coverage and does not impute the missing 30% subweight.</li><li>State-legislative catalogs feed a state-level Democratic contestation share on the Republican route for six states, and direct primary evidence for matched state legislators in ten states. County- and local-office catalogs never flow into any rank.</li><li>State-legislative seats are ranked only in states whose official general-election returns are retained. Most of them carry the own-race margin as their only measured input, so many share the same score; the Priority Index shows those as ties and opens on seats with two or more inputs.</li><li>Senate scores use a statewide baseline and omit primary feasibility; they are comparable to House scores only in the sense that both use the same weights and coverage rule.</li><li>Election results retain their reported certification and completeness boundaries; missing values remain labeled.</li><li>Scores are rounded to one decimal and sorted descending, then by stable seat identifier for deterministic ties.</li></ul><p><Link href="/sources">Open the Sources page</Link> for score-input coverage, retained snapshot lineage, and explicit missing reasons.</p></section>
  </main></Shell>;
}
