import { loadMethodologyPage } from "@/ui/server-data";
import { Shell, RouteState, fmtDate } from "@/components/presentational";
export const dynamic = "force-dynamic";

export default async function Methodology() {
  const result = await loadMethodologyPage();
  if (!result.ok) return <RouteState code={result.code} />;
  const { value: page } = result;
  return <Shell release={page.release}><main className="page method-page">
    <p className="eyebrow">METHOD / {page.release.label}</p><h1>How the Priority Index works</h1>
    <p className="lede">The score is a comparative research index from 0–100. It is not a win probability, polling estimate, endorsement, or prediction. Source cutoff: {fmtDate(page.release.sourceCutoff)}.</p>
    <section className="method-principles"><article><b>Higher means</b><p>More structural or political reason to investigate the seat as an organizing opportunity.</p></article><article><b>Missing means missing</b><p>An unavailable component is never silently replaced with zero. Each route says which evidence it uses.</p></article><article><b>Routes are distinct</b><p>Democratic primary opportunities and Republican-held general-election fringes are scored with different formulas.</p></article></section>
    <section className="record-section"><p className="eyebrow">DEMOCRATIC-HELD SEATS</p><h2>Primary-opportunity model</h2><p>The Democratic field starts with the stronger of two structural routes, then blends that baseline with the incumbent alignment gap.</p><div className="formula-block"><code>final = 0.75 × structural baseline + 0.25 × incumbent alignment gap</code></div><div className="method-grid"><article><h3>Deep-blue route</h3><code>0.70 × blue baseline + 0.30 × primary feasibility</code><p>Used when district safety and the available primary evidence are more informative than the AIPAC route.</p></article><article><h3>AIPAC-supported blue route</h3><code>0.60 × AIPAC support + 0.25 × blue baseline + 0.15 × primary feasibility</code><p>Used only when the retained numeric AIPAC evidence exists and produces the stronger structural score.</p></article></div></section>
    <section className="record-section"><p className="eyebrow">REPUBLICAN-HELD SEATS</p><h2>General-election fringe model</h2><p>Republican seats do not receive invented Democratic-primary, AIPAC, or Democratic-incumbent alignment values. They enter through one structural screen based on the retained 2024 presidential margin.</p><div className="formula-block"><code>competitiveness = clamp(100 − 4 × max(0, Republican margin), 0, 100)</code><code>priority = 0.65 × competitiveness</code></div><p>The 65% multiplier caps this route at 65. A tied or Democratic-leaning Republican-held district scores 65; R+5 scores 52; R+10 scores 39; R+20 scores 13. The cap keeps a fringe flag from outranking the strongest evidence-rich primary opportunities by construction.</p></section>
    <section className="record-section"><p className="eyebrow">COMPONENT DICTIONARY</p><h2>What each number represents</h2><div className="component-table"><article><h3>Blue baseline</h3><b>0–100 · structural</b><p>District Democratic strength derived from the retained 2024 presidential result. Higher values indicate a safer Democratic baseline.</p></article><article><h3>Primary feasibility</h3><b>0–100 · contest evidence</b><p>The currently available evidence about whether a Democratic primary challenge is structurally plausible. It remains explicitly partial where nationwide historical inputs are incomplete.</p></article><article><h3>AIPAC support</h3><b>0–100 · FEC evidence</b><p>Numeric retained evidence connected to the AIPAC network. Tracker labels are context only and are not counted a second time.</p></article><article><h3>Incumbent alignment gap</h3><b>0–100 · voting record gap</b><p>The distance between retained Left and Palestine tracker scores and full alignment. Available tracker weights are normalized, then reduced by a missingness penalty when coverage is partial.</p></article><article><h3>General-election fringe</h3><b>0–100 · Republican route</b><p>Closeness of a Republican-held district using the 2024 presidential result. It is a screening signal, not a forecast of challenger strength.</p></article></div></section>
    <section className="record-section"><p className="eyebrow">RANKING & LIMITS</p><h2>How rows are ordered</h2><ul><li>Scores are rounded to one decimal place for display.</li><li>Rows sort by score descending, then by stable seat identifier for deterministic ties.</li><li>The opening field is the first 50 rows; filters can reveal all 430 occupied Democratic- and Republican-held seats.</li><li>Vacancies, delegates, the Resident Commissioner, and the one Clerk source row not labeled Democratic or Republican are outside this index.</li><li>Cash on hand, biography, and service history add context but do not change the current score.</li><li>Demographics remain display-only and never change rank.</li></ul></section>
    <section className="record-section"><p className="eyebrow">DATA DISCIPLINE</p><h2>Source and uncertainty rules</h2><p>Election results retain their reported certification and completeness status. ACS values retain estimate, margin of error, period, universe, and lineage. FEC summaries retain filing and amendment context. Missing values remain labeled, and district changes are not treated as identity changes. The <a href="/sources">Sources page</a> provides the active release coverage and snapshot inventory.</p></section>
  </main></Shell>;
}
