import { createHash } from "node:crypto";
import type { SnapshotId } from "@/domain/contracts";
import type { RawObjectStore } from "../core/raw-object-store";
import type { SourceAdapter, ValidationIssue } from "../core/types";
import { ACS_INDICATOR_DICTIONARY, type AcsIndicatorDefinition } from "./indicator-dictionary";
import { parseAcsSummaryTableIncrementally, type AcsTableRow } from "./table-parser";

export const ACS_ADAPTER_VERSION = "acs-direct-table-v2";
export const ACS_SOURCE_LIMITS = Object.freeze({ tableBytes: 32 * 1024 * 1024, chunkBytes: 1024 * 1024 });
const hash = (bytes: Uint8Array): string => createHash("sha256").update(bytes).digest("hex");
const sha = (value: unknown): value is string => typeof value === "string" && /^[a-f0-9]{64}$/.test(value);
const finite = (value: unknown): value is number => typeof value === "number" && Number.isSafeInteger(value) && value >= 0;
const body = async function* (bytes: Uint8Array): AsyncIterable<Uint8Array> { for (let i = 0; i < bytes.length; i += ACS_SOURCE_LIMITS.chunkBytes) yield bytes.subarray(i, i + ACS_SOURCE_LIMITS.chunkBytes); };

export interface AcsAdapterOptions {
  readonly rawStore: RawObjectStore; readonly sourceLockSha256: string; readonly definition: AcsIndicatorDefinition; readonly lockId: AcsIndicatorDefinition["lockId"];
  readonly sourceBytes: Uint8Array; readonly sourceUrl: string; readonly sourceChecksumSha256: string; readonly sourceByteSize: number;
  readonly snapshotId: SnapshotId; readonly parserVersion: string; readonly upstreamRelease: string;
}
export interface AcsStagedExtrasV1 { readonly schemaVersion: 1; readonly sourceLockSha256: string; readonly lockId: AcsIndicatorDefinition["lockId"]; readonly sourceTable: string; readonly estimateColumn: string; readonly marginOfErrorColumn: string; readonly label: string; readonly universe: string; readonly stateFips: string; readonly districtCode: string; readonly estimateMissingReason: string | null; readonly marginOfErrorMissingReason: string | null; }
export interface AcsStageRow { readonly sourceNaturalKey: string; readonly geography: string; readonly variable: string; readonly surveyPeriod: string; readonly estimate: number | null; readonly marginOfError: number | null; readonly unit: string; readonly redactedExtras: AcsStagedExtrasV1; }
export interface AcsRawValue { readonly bytes: Uint8Array; readonly sourceLockSha256: string; readonly lockId: string; readonly sourceUrl: string; }
const extrasKeys = ["schemaVersion", "sourceLockSha256", "lockId", "sourceTable", "estimateColumn", "marginOfErrorColumn", "label", "universe", "stateFips", "districtCode", "estimateMissingReason", "marginOfErrorMissingReason"] as const;
export function decodeAcsStagedExtras(value: unknown): AcsStagedExtrasV1 {
  if (!value || typeof value !== "object" || Array.isArray(value)) throw new Error("ACS_EXTRAS_INVALID"); const v = value as Record<string, unknown>;
  if (Object.keys(v).length !== extrasKeys.length || extrasKeys.some(k => !(k in v)) || v.schemaVersion !== 1 || !sha(v.sourceLockSha256) || typeof v.lockId !== "string" || typeof v.sourceTable !== "string" || typeof v.estimateColumn !== "string" || typeof v.marginOfErrorColumn !== "string" || typeof v.label !== "string" || typeof v.universe !== "string" || !/^\d{2}$/.test(String(v.stateFips)) || !/^\d{2}$/.test(String(v.districtCode)) || !(v.estimateMissingReason === null || typeof v.estimateMissingReason === "string") || !(v.marginOfErrorMissingReason === null || typeof v.marginOfErrorMissingReason === "string")) throw new Error("ACS_EXTRAS_INVALID");
  return v as unknown as AcsStagedExtrasV1;
}
export function createAcsAdapter(options: AcsAdapterOptions): SourceAdapter<AcsRawValue, AcsStageRow> {
  const d = options.definition, exactDefinition = ACS_INDICATOR_DICTIONARY.find(x => x.id === d.id);
  if (!exactDefinition || exactDefinition !== d || options.lockId !== d.lockId || options.sourceUrl !== d.sourceUrl || !sha(options.sourceLockSha256) || !sha(options.sourceChecksumSha256) || !finite(options.sourceByteSize) || options.sourceByteSize !== options.sourceBytes.byteLength || options.sourceByteSize > ACS_SOURCE_LIMITS.tableBytes || hash(options.sourceBytes) !== options.sourceChecksumSha256 || !options.parserVersion || !options.upstreamRelease) throw new Error("ACS_SOURCE_RECEIPT_MISMATCH");
  const eventRows = async (bytes: Uint8Array) => { let count = 0; for await (const event of parseAcsSummaryTableIncrementally(body(bytes), d)) { if (event.kind === "row" || event.kind === "quarantine") count++; } return count; };
  const stageRow = (r: AcsTableRow): AcsStageRow => ({ sourceNaturalKey: r.sourceNaturalKey, geography: `${r.stateFips}${r.districtCode}`, variable: d.variableId, surveyPeriod: d.surveyPeriod, estimate: r.estimate.kind === "value" ? r.estimate.value : null, marginOfError: r.marginOfError.kind === "value" ? r.marginOfError.value : null, unit: d.unit, redactedExtras: { schemaVersion: 1, sourceLockSha256: options.sourceLockSha256, lockId: d.lockId, sourceTable: d.sourceTable, estimateColumn: d.estimateColumn, marginOfErrorColumn: d.marginOfErrorColumn, label: d.label, universe: d.universe, stateFips: r.stateFips, districtCode: r.districtCode, estimateMissingReason: r.estimate.kind === "missing" ? r.estimate.reason : null, marginOfErrorMissingReason: r.marginOfError.kind === "missing" ? r.marginOfError.reason : null } });
  return { sourceName: "acs", adapterVersion: options.parserVersion,
    async *extract(context) { if (context.signal?.aborted) throw new Error("INGEST_ABORTED"); const receipt = await options.rawStore.put({ objectKey: `acs/${d.lockId}/${options.sourceChecksumSha256}.dat`, body: body(options.sourceBytes), expectedSha256: options.sourceChecksumSha256, signal: context.signal }); if (receipt.sha256 !== options.sourceChecksumSha256 || receipt.byteSize !== options.sourceByteSize) throw new Error("ACS_SOURCE_RECEIPT_MISMATCH"); yield { value: { bytes: options.sourceBytes, sourceLockSha256: options.sourceLockSha256, lockId: d.lockId, sourceUrl: d.sourceUrl }, receipt, snapshot: { id: options.snapshotId, sourceUrl: d.sourceUrl, checksumSha256: receipt.sha256, upstreamRelease: options.upstreamRelease, publishedAt: null, license: "public-domain", usageStatus: "approved" }, expectedRecordCount: await eventRows(options.sourceBytes) }; },
    async *parse(raw) { if (raw.snapshot.checksumSha256 !== options.sourceChecksumSha256 || raw.receipt.sha256 !== options.sourceChecksumSha256 || raw.receipt.byteSize !== options.sourceByteSize || raw.value.sourceLockSha256 !== options.sourceLockSha256 || raw.value.lockId !== d.lockId || raw.value.sourceUrl !== d.sourceUrl || raw.value.bytes.byteLength !== options.sourceByteSize || hash(raw.value.bytes) !== options.sourceChecksumSha256) throw new Error("ACS_RAW_BINDING_MISMATCH"); for await (const event of parseAcsSummaryTableIncrementally(body(raw.value.bytes), d)) { if (event.kind === "row") yield { kind: "row", row: stageRow(event.row) }; else yield { kind: "quarantine", sourceNaturalKey: hash(Buffer.from(`${options.sourceLockSha256}:${event.lineNumber}:${event.errorCode}`)), payloadChecksum: hash(event.payload), errorCode: event.errorCode }; } },
    naturalKey: row => row.sourceNaturalKey,
    async stage(client, runId, rows) { if (!rows.length) return; await client.query("INSERT INTO stg_acs(run_id,release_id,source_natural_key,snapshot_id,geography,variable,survey_period,estimate,margin_of_error,unit,redacted_extras) SELECT $1,ir.release_id,x.key,ir.snapshot_id,x.geography,x.variable,x.period,x.estimate,x.moe,x.unit,x.extras::jsonb FROM ingest_runs ir CROSS JOIN unnest($2::text[],$3::text[],$4::text[],$5::text[],$6::numeric[],$7::numeric[],$8::text[],$9::jsonb[]) AS x(key,geography,variable,period,estimate,moe,unit,extras) WHERE ir.id=$1", [runId, rows.map(x => x.sourceNaturalKey), rows.map(x => x.geography), rows.map(x => x.variable), rows.map(x => x.surveyPeriod), rows.map(x => x.estimate), rows.map(x => x.marginOfError), rows.map(x => x.unit), rows.map(x => JSON.stringify(x.redactedExtras))]); },
    async validateStaged(client, runId): Promise<readonly ValidationIssue[]> { const result = await client.query<{ valid: unknown }>("SELECT (count(*) + (SELECT quarantined_count FROM ingest_runs WHERE id=$1) = (SELECT extracted_count FROM ingest_runs WHERE id=$1)) AND count(DISTINCT geography)=count(*) AND count(DISTINCT variable)=1 AND count(DISTINCT survey_period)=1 AND count(DISTINCT unit)=1 AND bool_and(snapshot_id=(SELECT snapshot_id FROM ingest_runs WHERE id=$1)) AND bool_and(redacted_extras->>'sourceLockSha256'=$2 AND redacted_extras->>'lockId'=$3 AND redacted_extras->>'sourceTable'=$4 AND redacted_extras->>'estimateColumn'=$5 AND redacted_extras->>'marginOfErrorColumn'=$6 AND redacted_extras->>'label'=$7 AND redacted_extras->>'universe'=$8 AND redacted_extras ?& ARRAY['schemaVersion','sourceLockSha256','lockId','sourceTable','estimateColumn','marginOfErrorColumn','label','universe','stateFips','districtCode','estimateMissingReason','marginOfErrorMissingReason'] AND jsonb_typeof(redacted_extras)='object' AND (SELECT count(*) FROM jsonb_object_keys(redacted_extras))=12) AS valid FROM stg_acs WHERE run_id=$1", [runId, options.sourceLockSha256, d.lockId, d.sourceTable, d.estimateColumn, d.marginOfErrorColumn, d.label, d.universe]); return result.rows[0]?.valid === true || result.rows[0]?.valid === "t" ? [] : [{ code: "ACS_STAGE_INVALID", message: "ACS staged records do not match the run-bound direct-table receipt." }]; },
    async loadFromStage() { throw new Error("ACS_FINALIZE_REQUIRED"); },
  };
}
