import { fireEvent, render, screen, waitFor } from "@testing-library/react";
import { afterEach, describe, expect, it, vi } from "vitest";
import { CorrectionForm, isPublicHttpsSourceUrl, isPublicId } from "./correction-form";

const tokenResponse = { ok: true, json: async () => ({ csrfToken: "csrf", idempotencyToken: "idem" }) };
describe("CorrectionForm", () => {
  afterEach(() => vi.unstubAllGlobals());
  it("uses only bounded release and seat prefill identifiers", () => { expect(isPublicId("rel_safe_1", "rel")).toBe(true); expect(isPublicId("<img>", "rel")).toBe(false); expect(isPublicId("seat_safe_1", "seat")).toBe(true); });
  it("accepts only source URLs the server's public HTTPS contract accepts", () => {
    expect(isPublicHttpsSourceUrl("https://EXAMPLE.com/a?key=A%2FZ&x=(one),two;three!$&'*=~")).toBe(true);
    for (const value of ["https://example.local/a", "https://127.0.0.1/a", "https://example.com:443/a", "https://user@example.com/a", "https://example.com/a%2f", "https://example.com/a%2", "https://example.com/a@b", "https://example.com/a/..", "https://example.com/a/../evidence", "https://example.com/a/%2E%2E/evidence"]) expect(isPublicHttpsSourceUrl(value)).toBe(false);
  });
  it("labels the permitted fields and excludes prohibited collection", async () => { vi.stubGlobal("fetch", vi.fn().mockResolvedValue(tokenResponse)); render(<CorrectionForm releaseId="rel_1" seatCycleId="seat_1" />); expect(await screen.findByLabelText("Correction area")).toBeInTheDocument(); expect(screen.getByLabelText("What should be corrected?")).toBeInTheDocument(); expect(screen.getByLabelText(/Source URL/)).toBeInTheDocument(); expect(screen.queryByLabelText(/email|address|voter|political affiliation|demographics/i)).not.toBeInTheDocument(); });
  it("posts the contractual body and security headers once", async () => { const fetch = vi.fn().mockResolvedValueOnce(tokenResponse).mockResolvedValueOnce({ ok: true, json: async () => ({ status: "accepted", correctionId: "cor_1" }) }); vi.stubGlobal("fetch", fetch); render(<CorrectionForm releaseId="rel_1" seatCycleId="seat_1" />); const text = await screen.findByLabelText("What should be corrected?"); fireEvent.change(text, { target: { value: "This published holder needs a source review." } }); fireEvent.click(screen.getByRole("button", { name: "Submit for review" })); await waitFor(() => expect(fetch).toHaveBeenCalledTimes(2)); expect(fetch.mock.calls[1][1]).toMatchObject({ method: "POST", headers: { "Content-Type": "application/json", "X-CSRF-Token": "csrf", "Idempotency-Key": "idem" } }); expect(JSON.parse(fetch.mock.calls[1][1].body)).toEqual({ releaseId: "rel_1", seatCycleId: "seat_1", fieldPath: "identity.current_holder", explanation: "This published holder needs a source review." }); const status = await screen.findByRole("status"); expect(status).toHaveTextContent("Correction received"); expect(status).toHaveFocus(); });
  it("focuses the response and prevents duplicate submission", async () => { let resolve!: (value: unknown) => void; const fetch = vi.fn().mockResolvedValueOnce(tokenResponse).mockImplementationOnce(() => new Promise((done) => { resolve = done; })); vi.stubGlobal("fetch", fetch); render(<CorrectionForm releaseId="rel_1" />); fireEvent.change(await screen.findByLabelText("What should be corrected?"), { target: { value: "This published holder needs a source review." } }); const button = screen.getByRole("button", { name: "Submit for review" }); fireEvent.click(button); fireEvent.click(button); expect(fetch).toHaveBeenCalledTimes(2); resolve({ ok: false, json: async () => ({ status: "rate_limited" }) }); const status = await screen.findByRole("status"); expect(status).toHaveTextContent("Too many submissions"); expect(status).toHaveFocus(); });
  it.each(["accepted", "replay"] as const)("makes %s submissions terminal so a second correction cannot reuse the token", async (outcome) => { const fetch = vi.fn().mockResolvedValueOnce(tokenResponse).mockResolvedValueOnce({ ok: true, json: async () => ({ status: outcome, correctionId: "cor_1" }) }); vi.stubGlobal("fetch", fetch); render(<CorrectionForm releaseId="rel_1" />); fireEvent.change(await screen.findByLabelText("What should be corrected?"), { target: { value: "This published holder needs a source review." } }); fireEvent.click(screen.getByRole("button", { name: "Submit for review" })); await screen.findByText(/To report another correction, reopen or reload this page/); expect(screen.getByRole("button", { name: "Submit for review" })).toBeDisabled(); expect(screen.getByLabelText("Correction area")).toBeDisabled(); expect(screen.getByLabelText("What should be corrected?")).toBeDisabled(); expect(screen.getByLabelText(/Source URL/)).toBeDisabled(); fireEvent.click(screen.getByRole("button", { name: "Submit for review" })); expect(fetch).toHaveBeenCalledTimes(2); });
});
