import Link from "next/link";
import type { ReactNode } from "react";
export function fmtDate(value: string | null | undefined) { if (!value) return "Not published"; return new Intl.DateTimeFormat("en-US", { dateStyle: "medium", timeZone: "UTC" }).format(new Date(value)); }
export function fmtNumber(value: number) { return new Intl.NumberFormat("en-US", { maximumFractionDigits: 1 }).format(value); }
export function fmtMoney(value: number) { return new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 0 }).format(value); }
export function words(value: string) { return value.replace(/_/g, " "); }
export function missing(reason: string) { return `Unavailable — ${words(reason)}`; }
export function fact(value: { kind: "value"; value: number } | { kind: "missing"; reason: string }, formatter = fmtNumber) { return value.kind === "value" ? formatter(value.value) : missing(value.reason); }
export function Status({ children }: { children: string }) { return <span className={`status status-${children.replace(/_/g, "-")}`}>{words(children)}</span>; }
export function Lineage({ status, asOf, methodology, inputs }: { status: string; asOf: string; methodology: string; inputs: readonly unknown[] }) { return <p className="lineage"><Status>{status}</Status><span>As of {fmtDate(asOf)}</span><span>{methodology}</span><span>{inputs.length} input {inputs.length === 1 ? "snapshot" : "snapshots"}</span></p>; }
export function ReleaseStrip({ release }: { release: { label: string; status: string; sourceCutoff: string; publishedAt: string | null } }) { return <div className="release-strip"><span><b>PRIVATE PROTOTYPE</b> · 10-seat limited coverage</span><span>{release.label} · <Status>{release.status}</Status> · source cutoff {fmtDate(release.sourceCutoff)}</span></div>; }
export function Shell({ children, release }: { children: ReactNode; release?: { label: string; status: string; sourceCutoff: string; publishedAt: string | null } }) { return <><header className="masthead"><Link className="wordmark" href="/">SEAT / RECORD</Link><nav aria-label="Primary navigation"><Link href="/">Browse</Link><Link href="/corrections">Corrections</Link><Link href="/lookup">Address lookup</Link><Link href="/sources">Sources</Link><Link href="/methodology">Method</Link></nav></header>{release && <ReleaseStrip release={release} />}{children}<footer>SEAT / RECORD · Private research prototype · <Link href="/sources">Source ledger</Link></footer></>; }
export function Notice({ title, children }: { title: string; children: ReactNode }) { return <section className="notice" aria-labelledby="notice-title"><h2 id="notice-title">{title}</h2><div>{children}</div></section>; }
export function RouteState({ code }: { code: "invalid_request" | "not_found" | "unavailable" | "configuration" }) { const copy = { invalid_request: ["Request not available", "This URL includes a filter or value this research release does not accept."], not_found: ["Seat not in this release", "This private prototype has limited coverage."], unavailable: ["Data temporarily unavailable", "The research record cannot be loaded right now. Please try again later."], configuration: ["Research data unavailable", "This deployment is not configured to serve the private research release."] }[code]; return <Shell><main className="page state"><p className="eyebrow">RECORD STATUS</p><h1>{copy[0]}</h1><p>{copy[1]}</p><Link className="button" href="/">Return to browse</Link></main></Shell>; }
