/** Disposable, mechanism-only lifecycle drill. Never accepts a production target. */
import { createHash, randomUUID } from "node:crypto";
import { Pool, type PoolClient } from "pg";
import { baselineCandidateRelease, computeReleaseDigest, contentDomains, recheckNationwideValidationGateShared, validateNationwideCandidateRelease } from "@/db/catalog-release";
import { loadNationwideManifest, seedNationwideCandidateManifest, type BoundaryBundle } from "@/db/manifest";
import { promoteCandidateRelease, rollbackPublishedRelease, rollForwardRetiredRelease } from "@/db/releases";
import { computeCanonicalDataChecksum } from "@/domain/validate-manifest";
import { nationwideSkeleton } from "@/test/fixtures/nationwide-skeleton";
import { markLoaded, markValidated, startIngestRun } from "@/db/ingestion";
import { createJsonlOperationalSignalSink, operationalSignalSchema } from "@/operations/signals";
import { PostgresSeatResearchRepository } from "@/repositories/postgres";

export const RELEASE_DRILL_OPT_IN = "RUN_SYNTHETIC_RELEASE_DRILL";
export interface ReleaseDrillEnvironment { readonly DATABASE_URL?: string; readonly INGEST_DATABASE_URL?: string; readonly RELEASE_PREFLIGHT_DATABASE_URL?: string; readonly RELEASE_OPERATOR_DATABASE_URL?: string; readonly WEB_DATABASE_URL?: string; readonly RELEASE_DRILL_OPT_IN?: string; readonly NODE_ENV?: string; }
export interface ReleaseDrillConnections { readonly owner: string; readonly ingest: string; readonly preflight: string; readonly operator: string; readonly web: string; }
type ReleaseDrillChecks = { readonly roleAttestations: true; readonly stalePromotionRejected: true; readonly writerFreezeRejected: true; readonly expiredProofRejected: true; readonly domainInvalidations: readonly ["member", "acs", "finance", "elections", "maps"]; readonly immutableFingerprintPreserved: true; readonly rollbackPreserved: true; readonly rollForwardPreserved: true; readonly consumedProofs: number; readonly ingestHistoryRows: number; readonly digestRows: number; };
export type ReleaseDrillResult = { readonly evidenceClass: "local-synthetic"; readonly evidenceVersion: 2; readonly verified: true; readonly durationMs: number; readonly completedAt: string; readonly publishedReleaseId: string; readonly domains: 7; readonly publicSmokes: 3; readonly operationalSignals: number; readonly checks: ReleaseDrillChecks & { readonly rollbackPublicSmoke: true; readonly rollForwardPublicSmoke: true; readonly operationalSignalsObserved: true; }; };
const authenticResults = new WeakSet<object>();

/** Identity, not shape, is the provenance boundary for in-process drill evidence. */
export function isAuthenticReleaseDrillResult(value: unknown): value is ReleaseDrillResult {
  return !!value && typeof value === "object" && authenticResults.has(value);
}

const roles = { owner: "dsa_seats_migration_owner", ingest: "dsa_seats_ingest", preflight: "dsa_seats_release_preflight", operator: "dsa_seats_release_operator", web: "dsa_seats_web" } as const;
function safeUrl(value: string | undefined, name: string): URL { if (!value) throw new Error(`${name} is required for the synthetic release drill`); let url: URL; try { url = new URL(value); } catch { throw new Error(`${name} must be a valid PostgreSQL URL`); } if (url.protocol !== "postgres:" && url.protocol !== "postgresql:") throw new Error(`${name} must use postgres or postgresql`); return url; }
/** Validate targets without returning any credentials or locators beyond the caller supplied connections. */
export function assertReleaseDrillEnvironment(env: ReleaseDrillEnvironment): ReleaseDrillConnections {
  if (env.RELEASE_DRILL_OPT_IN !== RELEASE_DRILL_OPT_IN) throw new Error(`RELEASE_DRILL_OPT_IN must exactly equal ${RELEASE_DRILL_OPT_IN}`);
  if (!env.NODE_ENV || env.NODE_ENV.toLowerCase() === "production") throw new Error("Synthetic release drill requires nonproduction NODE_ENV");
  const entries = [["DATABASE_URL", env.DATABASE_URL], ["INGEST_DATABASE_URL", env.INGEST_DATABASE_URL], ["RELEASE_PREFLIGHT_DATABASE_URL", env.RELEASE_PREFLIGHT_DATABASE_URL], ["RELEASE_OPERATOR_DATABASE_URL", env.RELEASE_OPERATOR_DATABASE_URL], ["WEB_DATABASE_URL", env.WEB_DATABASE_URL]] as const;
  const urls = entries.map(([name, value]) => [name, safeUrl(value, name)] as const); const targets = new Set<string>(); const users = new Set<string>();
  for (const [name, url] of urls) { if (url.search || url.hash) throw new Error(`${name} must not include URL parameters or fragments`); const database = decodeURIComponent(url.pathname).replace(/^\//, ""); if (!database.endsWith("_test") || !database) throw new Error(`${name} must name one disposable *_test database`); if (!new Set(["localhost", "127.0.0.1", "::1"]).has(url.hostname)) throw new Error(`${name} must use a loopback host`); if (!url.username) throw new Error(`${name} must include a LOGIN username`); targets.add(`${url.hostname}:${url.port}/${database}`); users.add(decodeURIComponent(url.username)); }
  if (targets.size !== 1 || users.size !== 5) throw new Error("Synthetic release drill requires one target and five distinct LOGIN usernames");
  return { owner: env.DATABASE_URL!, ingest: env.INGEST_DATABASE_URL!, preflight: env.RELEASE_PREFLIGHT_DATABASE_URL!, operator: env.RELEASE_OPERATOR_DATABASE_URL!, web: env.WEB_DATABASE_URL! };
}
function fixture(releaseId: string): { manifest: ReturnType<typeof nationwideSkeleton>; bundle: BoundaryBundle } { const manifest = structuredClone(nationwideSkeleton()); const replace = (v: unknown): void => { if (Array.isArray(v)) v.forEach(replace); else if (v && typeof v === "object") { const r = v as Record<string, unknown>; if (r.releaseId === "rel_synthetic") r.releaseId = releaseId; Object.values(r).forEach(replace); } }; replace(manifest); manifest.mapArtifacts = []; manifest.release = { ...manifest.release, id: releaseId as never, label: "Synthetic lifecycle mechanism", status: "candidate", publishedAt: null, previousReleaseId: null }; const geography = manifest.geographyVersions.find(value => value.kind === "house_district")!; manifest.acsObservations = [{ releaseId: releaseId as never, geographyVersionId: geography.id, variable: "synthetic", label: "Synthetic", estimate: { kind: "value", value: 1 }, marginOfError: { kind: "value", value: 0 }, unit: "count", surveyPeriod: "synthetic", universe: "synthetic", lineage: { inputs: [{ snapshotId: "snap_input" as never, role: "original_publisher" }], asOf: "2024-01-01", methodology: "synthetic", status: "reported" } }] as never; manifest.coverageRecords = manifest.coverageRecords.map(record => record.domain === "acs" ? { ...record, status: "partial", observedCount: 1, missingByReason: [{ reason: "not_collected", count: 490 }] } : record) as never; const bytes = JSON.stringify({ type: "FeatureCollection", features: manifest.geographyVersions.map((g, i) => { const x = -90 + (i % 30) * 3; const y = -25 + Math.floor(i / 30) * 3; return { type: "Feature", properties: { sourceGeoid: g.sourceGeoid, stateCode: g.stateCode, districtCode: g.kind === "house_district" ? g.districtCode : null }, geometry: { type: "MultiPolygon", coordinates: [[[[x, y], [x + .5, y], [x + .5, y + .5], [x, y + .5], [x, y]]]] } }; }) }); manifest.geometryArtifacts[0]!.checksumSha256 = createHash("sha256").update(bytes).digest("hex"); manifest.canonicalDataChecksumSha256 = computeCanonicalDataChecksum(manifest); return { manifest, bundle: [{ artifactId: manifest.geometryArtifacts[0]!.id, objectKey: manifest.geometryArtifacts[0]!.objectKey, bytes }] }; }
async function createCandidate(ingest: Pool, id: string, predecessor: string, cutoff: string): Promise<void> { await ingest.query("INSERT INTO data_releases(id,label,status,source_cutoff,created_at,previous_release_id) VALUES($1,'Synthetic lifecycle mechanism','candidate',$2,clock_timestamp(),$3)", [id, cutoff, predecessor]); }
async function recordSyntheticIngestHistory(ingest: Pool, releaseId: string): Promise<void> { const row = (await ingest.query<{ source_id: string; id: string; checksum_sha256: string }>("SELECT source_id,id,checksum_sha256 FROM source_snapshots WHERE release_id=$1 ORDER BY id LIMIT 1", [releaseId])).rows[0]; if (!row) throw new Error("Synthetic drill requires a baseline snapshot"); const id = `run_drill_${randomUUID().replace(/-/g, "")}`; const token = randomUUID(); await startIngestRun(ingest, { id, releaseId, sourceId: row.source_id, snapshotId: row.id, adapterVersion: "synthetic-drill", upstreamRelease: "synthetic-drill-v1", rawStoreKind: "local", rawStoreLocator: "/tmp/synthetic-drill", rawObjectKey: "synthetic/drill.json", rawObjectSha256: row.checksum_sha256, rawObjectByteSize: 0, leaseToken: token, leaseDurationMs: 10_000, extractedCount: 0 }); await markValidated(ingest, id, token); await markLoaded(ingest, id, token); }
async function attest(pool: Pool, expected: string | null): Promise<void> { const r = await pool.query<{ user: string; super: boolean; owner: boolean; memberships: string[] }>("SELECT session_user AS user,(SELECT rolsuper FROM pg_roles WHERE rolname=session_user) super,(SELECT pg_get_userbyid(datdba)::text FROM pg_database WHERE datname=current_database())=session_user::text owner,coalesce(array_agg(g.rolname::text ORDER BY g.rolname::text) FILTER(WHERE g.rolname IS NOT NULL),ARRAY[]::text[]) memberships FROM pg_roles u LEFT JOIN pg_auth_members x ON x.member=u.oid LEFT JOIN pg_roles g ON g.oid=x.roleid WHERE u.rolname=session_user GROUP BY session_user"); const row = r.rows[0]; if (!row || row.super || row.owner || (expected === null ? row.memberships.length !== 0 : row.memberships.length !== 1 || row.memberships[0] !== expected)) throw new Error("Synthetic drill runtime principal attestation failed"); }
async function snapshot(pool: Pool, ids: readonly string[]): Promise<string> { const rows = await pool.query("SELECT r.id,r.label,r.source_cutoff,r.created_at,r.previous_release_id,m.schema_version,m.canonical_data_checksum_sha256,m.geometry_checksum_sha256,m.content_checksum_sha256,(SELECT jsonb_agg(jsonb_build_array(s.id,s.source_id,s.source_url,s.published_at,s.retrieved_at,s.checksum_sha256,s.parser_version,s.license,s.usage_status) ORDER BY s.id) FROM source_snapshots s WHERE s.release_id=r.id) snapshots,(SELECT jsonb_agg(jsonb_build_array(i.id,i.source_id,i.snapshot_id,i.status,i.adapter_version,i.upstream_release,i.raw_store_kind,i.raw_store_locator,i.raw_object_key,i.raw_object_sha256,i.raw_object_byte_size,i.raw_object_version_id) ORDER BY i.id) FROM ingest_runs i WHERE i.release_id=r.id) ingest_history,(SELECT jsonb_agg(jsonb_build_array(d.domain,d.row_count,d.sha256) ORDER BY d.domain) FROM release_content_digests d WHERE d.release_id=r.id) digests,(SELECT jsonb_build_array(g.schema_version,g.manifest_checksum_sha256,g.geometry_checksum_sha256,g.content_checksum_sha256,g.domain_count,g.domain_checksum_sha256) FROM nationwide_validation_gates g WHERE g.release_id=r.id) gate FROM data_releases r JOIN release_manifests m ON m.release_id=r.id WHERE r.id=ANY($1) ORDER BY r.id", [ids]); if (rows.rowCount !== ids.length || rows.rows.some((r: { digests: unknown[] | null }) => r.digests?.length !== 7)) throw new Error("Synthetic drill preservation evidence is incomplete"); for (const id of ids) { const loaded = await loadNationwideManifest(pool, id); const manifest = rows.rows.find((row: { id: string }) => row.id === id)! as { canonical_data_checksum_sha256: string; content_checksum_sha256: string; geometry_checksum_sha256: string; digests: [string, number, string][] }; if (loaded.canonicalDataChecksumSha256 !== manifest.canonical_data_checksum_sha256 || createHash("sha256").update(JSON.stringify({ data: manifest.canonical_data_checksum_sha256, geometry: manifest.geometry_checksum_sha256 })).digest("hex") !== manifest.content_checksum_sha256) throw new Error("Synthetic drill strict manifest fingerprint is inconsistent"); for (const domain of Object.keys(contentDomains) as (keyof typeof contentDomains)[]) { const stored = manifest.digests.find(digest => digest[0] === domain); const computed = await computeReleaseDigest(pool, id, domain); if (!stored || Number(stored[1]) !== computed.rowCount || stored[2] !== computed.sha256) throw new Error("Synthetic drill digest fingerprint is inconsistent"); } } return JSON.stringify(rows.rows); }
type DomainMutation = { readonly domain: "member" | "acs" | "finance" | "elections" | "maps"; readonly statement: string; readonly values?: readonly unknown[] };
const domainMutations: readonly DomainMutation[] = [
  { domain: "member", statement: "UPDATE biographical_facts SET value='Synthetic invalidation' WHERE release_id=$1 AND fact='bioguide_id' AND value IS NOT NULL AND person_id=(SELECT person_id FROM biographical_facts WHERE release_id=$1 AND fact='bioguide_id' AND value IS NOT NULL ORDER BY person_id LIMIT 1)" },
  { domain: "acs", statement: "UPDATE acs_observations SET estimate=2 WHERE release_id=$1 AND geography_version_id=(SELECT geography_version_id FROM acs_observations WHERE release_id=$1 ORDER BY geography_version_id LIMIT 1)" },
  { domain: "finance", statement: "UPDATE finance_aggregates SET methodology_version='synthetic-probe' WHERE release_id=$1 AND id=(SELECT id FROM finance_aggregates WHERE release_id=$1 ORDER BY id LIMIT 1)" },
  { domain: "elections", statement: "UPDATE election_decisions SET status='unavailable' WHERE release_id=$1 AND id=(SELECT id FROM election_decisions WHERE release_id=$1 ORDER BY id LIMIT 1)" },
  { domain: "maps", statement: "UPDATE geometry_artifacts SET checksum_sha256=$2 WHERE release_id=$1 AND id=(SELECT id FROM geometry_artifacts WHERE release_id=$1 ORDER BY id LIMIT 1)", values: ["c".repeat(64)] },
];
async function proveDomainInvalidations(ingest: Pool, web: Pool, releaseId: string, publishedId: string): Promise<void> { const client = await ingest.connect(); try { for (const mutation of domainMutations) { await client.query("BEGIN"); try { const result = await client.query(mutation.statement, [releaseId, ...(mutation.values ?? [])]); if (result.rowCount !== 1) throw new Error(`Synthetic drill ${mutation.domain} invalidation row is absent`); const removed = await client.query("SELECT EXISTS(SELECT 1 FROM release_content_digests WHERE release_id=$1 AND domain=$2) digest,EXISTS(SELECT 1 FROM nationwide_validation_gates WHERE release_id=$1) gate", [releaseId, mutation.domain]); if (removed.rows[0]?.digest || removed.rows[0]?.gate) throw new Error(`Synthetic drill ${mutation.domain} invalidation was not transactional`); let rejected = false; try { await recheckNationwideValidationGateShared(client, releaseId); } catch { rejected = true; } if (!rejected || (await web.query<{ id: string }>("SELECT id FROM data_releases WHERE status='published'")).rows[0]?.id !== publishedId) throw new Error(`Synthetic drill ${mutation.domain} invalidation did not preserve published pointer`); } finally { await client.query("ROLLBACK"); } } } finally { client.release(); } }
async function waitForWriter(pool: Pool, pid: number): Promise<void> { for (let i = 0; i < 200; i += 1) { if ((await pool.query<{ waiting: boolean }>("SELECT EXISTS(SELECT 1 FROM pg_locks WHERE locktype='advisory' AND pid=$1 AND NOT granted) waiting", [pid])).rows[0]?.waiting) return; await new Promise(resolve => setTimeout(resolve, 5)); } throw new Error("Synthetic drill writer did not block"); }
async function issue(preflight: PoolClient, id: string, target: string, current: string | null, ttl = 300): Promise<void> { await preflight.query("SELECT public.issue_release_preflight($1,'promote',$2,$3,$3,NULL,$4)", [id, target, current, ttl]); }
async function publicSmoke(repository: PostgresSeatResearchRepository, expectedReleaseId: string): Promise<void> { const active = await repository.getActiveRelease(); if (active.id !== expectedReleaseId) throw new Error("web public smoke resolved an unexpected release"); const page = await repository.listSeatPage(active.id, { limit: 1, sort: "state", direction: "asc" }); const seat = page.items[0]; if (!seat) throw new Error("web public smoke found no seat"); const profile = await repository.getSeatProfile(active.id, seat.id); const [sources, coverage] = await Promise.all([repository.listSources(active.id), repository.listReleaseCoverage(active.id)]); if (!profile || sources.length === 0 || coverage.length === 0) throw new Error("web public smoke evidence is incomplete"); }
async function waitForSignals(lines: readonly string[], expected: number): Promise<void> { for (let i = 0; i < 200; i += 1) { if (lines.length === expected) return; await new Promise(resolve => setTimeout(resolve, 5)); } throw new Error("Synthetic drill operational signals were not delivered"); }

export async function runSyntheticReleaseDrill(connections: ReleaseDrillConnections, timeoutMs = 60_000): Promise<ReleaseDrillResult> {
  if (!Number.isSafeInteger(timeoutMs) || timeoutMs < 2_000 || timeoutMs > 120_000) throw new Error("Synthetic drill timeout must be between 2000 and 120000ms"); const started = performance.now(); const owner = new Pool({ connectionString: connections.owner, statement_timeout: timeoutMs }); const ingest = new Pool({ connectionString: connections.ingest, statement_timeout: timeoutMs }); const preflight = new Pool({ connectionString: connections.preflight, statement_timeout: timeoutMs }); const operator = new Pool({ connectionString: connections.operator, statement_timeout: timeoutMs }); const web = new Pool({ connectionString: connections.web, statement_timeout: timeoutMs }); const signalLines: string[] = []; const signalSink = createJsonlOperationalSignalSink(line => { if (signalLines.length < 32) signalLines.push(line); }); const repository = new PostgresSeatResearchRepository(web, signalSink); const lifecyclePools = { preflightPool: preflight, operatorPool: operator, signalSink }; const suffix = randomUUID().replace(/-/g, ""); const [r1, r2, r3] = ["r1", "r2", "r3"].map(n => `rel_drill_${n}_${suffix}`);
  try {
    await Promise.all([attest(owner, roles.owner), attest(ingest, roles.ingest), attest(preflight, roles.preflight), attest(operator, roles.operator), attest(web, roles.web)]);
    const seeded = fixture(r1); await seedNationwideCandidateManifest(owner, seeded.manifest, seeded.bundle); await validateNationwideCandidateRelease(ingest, r1); await promoteCandidateRelease(ingest, r1, 3, undefined, undefined, lifecyclePools);
    await createCandidate(ingest, r2, r1, seeded.manifest.release.sourceCutoff); await baselineCandidateRelease(ingest, r1, r2); await validateNationwideCandidateRelease(ingest, r2); await promoteCandidateRelease(ingest, r2, 3, undefined, undefined, lifecyclePools);
    await createCandidate(ingest, r3, r2, seeded.manifest.release.sourceCutoff); await baselineCandidateRelease(ingest, r2, r3); await recordSyntheticIngestHistory(ingest, r3); await validateNationwideCandidateRelease(ingest, r3); const before = await snapshot(ingest, [r1, r2, r3]);
    // A live proof freezes a writer after it has waited on the exact release
    // lock. The same short-lived proof must not transition after expiry.
    const p = await preflight.connect(); const w = await ingest.connect(); let expiredProof = ""; try { await p.query("BEGIN"); await p.query("SELECT pg_advisory_xact_lock(hashtext('dsa_seats_release:' || $1))", [r3]); const pid = (await w.query<{ pid: number }>("SELECT pg_backend_pid() pid")).rows[0]!.pid; await w.query("BEGIN"); const write = w.query("UPDATE biographical_facts SET value='blocked' WHERE release_id=$1 AND fact='birth_date'", [r3]); await waitForWriter(preflight, pid); expiredProof = randomUUID(); await issue(p, expiredProof, r3, r2, 1); await p.query("COMMIT"); await write.then(() => { throw new Error("writer unexpectedly changed candidate"); }, e => { if ((e as { code?: string }).code !== "55000") throw e; }); await w.query("ROLLBACK"); } finally { await p.query("ROLLBACK").catch(() => undefined); p.release(); await w.query("ROLLBACK").catch(() => undefined); w.release(); }
    await new Promise(resolve => setTimeout(resolve, 1_100)); let expiredRejected = false; try { await operator.query("SELECT public.lifecycle_promote_candidate($1,$2,$3,$3,NULL)", [expiredProof, r3, r2]); } catch { expiredRejected = true; } if (!expiredRejected || (await web.query<{ id: string }>("SELECT id FROM data_releases WHERE status='published'")).rows[0]?.id !== r2) throw new Error("expired proof changed lifecycle state");
    await proveDomainInvalidations(ingest, web, r3, r2); const person = (await ingest.query<{ id: string; display_name: string }>("SELECT id,display_name FROM people WHERE release_id=$1 ORDER BY id LIMIT 1", [r3])).rows[0]; if (!person) throw new Error("missing synthetic person"); await ingest.query("UPDATE people SET display_name='Synthetic stale candidate' WHERE release_id=$1 AND id=$2", [r3, person.id]); let staleRejected = false; try { await promoteCandidateRelease(ingest, r3, 1, undefined, undefined, lifecyclePools); } catch { staleRejected = true; } if (!staleRejected || (await web.query<{ id: string }>("SELECT id FROM data_releases WHERE status='published'")).rows[0]?.id !== r2) throw new Error("stale candidate promoted"); await ingest.query("UPDATE people SET display_name=$3 WHERE release_id=$1 AND id=$2", [r3, person.id, person.display_name]); await validateNationwideCandidateRelease(ingest, r3); await promoteCandidateRelease(ingest, r3, 3, undefined, undefined, lifecyclePools);
    await publicSmoke(repository, r3); await rollbackPublishedRelease(ingest, 3, lifecyclePools); if (await snapshot(ingest, [r1, r2, r3]) !== before) throw new Error("rollback altered immutable evidence"); await publicSmoke(repository, r2); await rollForwardRetiredRelease(ingest, r3, 3, undefined, undefined, lifecyclePools); if (await snapshot(ingest, [r1, r2, r3]) !== before) throw new Error("roll-forward altered immutable evidence"); await publicSmoke(repository, r3);
    await waitForSignals(signalLines, 21); const signals = signalLines.map(line => operationalSignalSchema.parse(JSON.parse(line))); if (signals.length !== 21 || signals.filter(signal => signal.kind === "lifecycle").length !== 6 || signals.filter(signal => signal.kind === "repository").length !== 15 || signals.some(signal => signal.outcome === "failure" && signal.kind !== "lifecycle")) throw new Error("Synthetic drill operational signal evidence is incomplete"); const consumed = 4; const ingestHistoryRows = Number((await ingest.query("SELECT count(*)::int count FROM ingest_runs WHERE release_id=$1 AND adapter_version='synthetic-drill' AND status='loaded'", [r3])).rows[0]?.count ?? 0); if (ingestHistoryRows !== 1) throw new Error("Synthetic drill ingest evidence is missing"); const result: ReleaseDrillResult = Object.freeze({ evidenceClass: "local-synthetic", evidenceVersion: 2, verified: true, durationMs: Math.floor(performance.now() - started), completedAt: new Date().toISOString(), publishedReleaseId: r3, domains: 7, publicSmokes: 3, operationalSignals: signals.length, checks: Object.freeze({ roleAttestations: true, stalePromotionRejected: true, writerFreezeRejected: true, expiredProofRejected: true, domainInvalidations: Object.freeze(["member", "acs", "finance", "elections", "maps"]) as ReleaseDrillChecks["domainInvalidations"], immutableFingerprintPreserved: true, rollbackPreserved: true, rollForwardPreserved: true, rollbackPublicSmoke: true, rollForwardPublicSmoke: true, operationalSignalsObserved: true, consumedProofs: consumed, ingestHistoryRows, digestRows: 21 }) }); authenticResults.add(result); return result;
  } finally { await Promise.all([owner.end(), ingest.end(), preflight.end(), operator.end(), web.end()]); }
}
