import { describe, expect, it } from "vitest";
import { assertReleaseDrillEnvironment, isAuthenticReleaseDrillResult, RELEASE_DRILL_OPT_IN, type ReleaseDrillResult } from "./release-drill";

const urls = { DATABASE_URL: "postgres://owner:secret@localhost/drill_test", INGEST_DATABASE_URL: "postgres://ingest:secret@localhost/drill_test", NATIONWIDE_FINALIZER_DATABASE_URL: "postgres://finalizer:secret@localhost/drill_test", RELEASE_PREFLIGHT_DATABASE_URL: "postgres://preflight:secret@localhost/drill_test", RELEASE_OPERATOR_DATABASE_URL: "postgres://operator:secret@localhost/drill_test", WEB_DATABASE_URL: "postgres://web:secret@localhost/drill_test", RELEASE_DRILL_OPT_IN, NODE_ENV: "test" };
describe("synthetic release drill safety", () => {
  it("requires the exact opt-in and a single disposable target", () => expect(assertReleaseDrillEnvironment(urls)).toEqual(expect.objectContaining({ owner: urls.DATABASE_URL })));
  it.each([{ ...urls, RELEASE_DRILL_OPT_IN: "yes" }, { ...urls, NODE_ENV: "production" }, { ...urls, NODE_ENV: undefined }, { ...urls, NATIONWIDE_FINALIZER_DATABASE_URL: undefined }, { ...urls, NATIONWIDE_FINALIZER_DATABASE_URL: urls.INGEST_DATABASE_URL }, { ...urls, WEB_DATABASE_URL: "mysql://web@localhost/drill_test" }, { ...urls, WEB_DATABASE_URL: "postgres://web@prod.example/drill_test" }, { ...urls, WEB_DATABASE_URL: "postgres://web@localhost/drill" }, { ...urls, WEB_DATABASE_URL: "postgres://web@localhost/other_test" }, { ...urls, WEB_DATABASE_URL: urls.INGEST_DATABASE_URL }, { ...urls, WEB_DATABASE_URL: "postgres://web@localhost/drill_test?host=prod.example" }, { ...urls, WEB_DATABASE_URL: "postgres://web@localhost/drill_test?database=prod" }, { ...urls, WEB_DATABASE_URL: "postgres://web@localhost/drill_test#bypass" }])("rejects unsafe environment", (env) => expect(() => assertReleaseDrillEnvironment(env)).toThrow());
  it("does not authenticate a structurally valid lookalike", () => { const result: ReleaseDrillResult = { evidenceClass: "local-synthetic", evidenceVersion: 2, verified: true, durationMs: 1, completedAt: "2026-01-01T00:00:00.000Z", publishedReleaseId: "rel_synthetic", domains: 7, publicSmokes: 3, operationalSignals: 21, checks: { roleAttestations: true, stalePromotionRejected: true, writerFreezeRejected: true, expiredProofRejected: true, domainInvalidations: ["member", "acs", "finance", "elections", "maps"], immutableFingerprintPreserved: true, rollbackPreserved: true, rollForwardPreserved: true, rollbackPublicSmoke: true, rollForwardPublicSmoke: true, operationalSignalsObserved: true, consumedProofs: 4, ingestHistoryRows: 1, digestRows: 21 } }; expect(isAuthenticReleaseDrillResult(result)).toBe(false); expect(isAuthenticReleaseDrillResult(JSON.parse(JSON.stringify(result)))).toBe(false); });
});
