import { createHash } from "node:crypto";
import { execFileSync } from "node:child_process";
import { mkdir,readFile,rename,rm,writeFile } from "node:fs/promises";
import { dirname } from "node:path";
const pdf={url:"https://elect.ky.gov/results/2020-2029/Documents/2022%20Primary%20Election%20results.pdf",path:"data/source/rapid/house-primary/ky/2022/primary-results.pdf",bytes:221_391,sha256:"385848ad3fd60c221d299cc8d75abc7bb646c96fdfa8e3ab21327590aaff0253"} as const;
const text={path:"data/source/rapid/house-primary/ky/2022/primary-results-layout.txt",bytes:103_147,sha256:"57bba153f9be1e67678759eeb69ec9b9d21f46796c8afe9ca3d23128d3f83590"} as const;
const sha=(bytes:Buffer)=>createHash("sha256").update(bytes).digest("hex");
async function main(){let pdfBytes:Buffer;try{pdfBytes=await readFile(pdf.path);if(pdfBytes.length!==pdf.bytes||sha(pdfBytes)!==pdf.sha256)throw new Error("KENTUCKY_2022_PDF_CONFLICT");}catch(error){if((error as NodeJS.ErrnoException).code!=="ENOENT")throw error;const response=await fetch(pdf.url,{headers:{"user-agent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 Chrome/138 Safari/537.36",referer:"https://elect.ky.gov/results/2020-2029/Pages/2022.aspx"}});if(!response.ok)throw new Error(`KENTUCKY_2022_FETCH_FAILED:${response.status}`);pdfBytes=Buffer.from(await response.arrayBuffer());if(pdfBytes.length!==pdf.bytes||sha(pdfBytes)!==pdf.sha256)throw new Error("KENTUCKY_2022_PDF_DRIFT");await mkdir(dirname(pdf.path),{recursive:true});await writeFile(pdf.path,pdfBytes,{flag:"wx"});}
try{const prior=await readFile(text.path);if(prior.length!==text.bytes||sha(prior)!==text.sha256)throw new Error("KENTUCKY_2022_TEXT_CONFLICT");return;}catch(error){if((error as NodeJS.ErrnoException).code!=="ENOENT")throw error;}const temporary=`${text.path}.tmp-${process.pid}`;execFileSync("pdftotext",["-layout",pdf.path,temporary]);const textBytes=await readFile(temporary);try{if(textBytes.length!==text.bytes||sha(textBytes)!==text.sha256)throw new Error("KENTUCKY_2022_TEXT_DRIFT");await rename(temporary,text.path);}finally{await rm(temporary,{force:true});}}
main().catch(error=>{process.stderr.write(`${error instanceof Error?error.message:"KENTUCKY_2022_ACQUISITION_FAILED"}\n`);process.exitCode=1;});
