import { createHash, randomUUID } from "node:crypto";
import { createReadStream, createWriteStream } from "node:fs";
import { link, lstat, mkdir, realpath, rm } from "node:fs/promises";
import { basename, isAbsolute, relative, resolve } from "node:path";
import { Readable, Transform } from "node:stream";
import { pipeline } from "node:stream/promises";
import { CopyObjectCommand, DeleteObjectCommand, GetBucketVersioningCommand, HeadObjectCommand, S3Client } from "@aws-sdk/client-s3";
import { Upload } from "@aws-sdk/lib-storage";
export interface RawObjectPut { readonly objectKey:string; readonly body:AsyncIterable<Uint8Array>; readonly expectedSha256?:string; readonly signal?:AbortSignal; }
export interface RawObjectResult { readonly storeKind:"local"|"s3"; readonly storeLocator:string; readonly objectKey:string; readonly sha256:string; readonly byteSize:number; readonly versionId?:string; readonly etag?:string; }
export interface RawObjectStore { put(input:RawObjectPut):Promise<RawObjectResult>; }
interface UploadHandle { done():Promise<{VersionId?:string;ETag?:string}>;abort():Promise<void>|void; }
export type S3UploadFactory=(params:{Bucket:string;Key:string;Body:Readable})=>UploadHandle;
type S3Sender=Pick<S3Client,"send">;
const safeKey=(key:string)=>{if(!key||isAbsolute(key)||key.includes("\\")||key.split("/").includes(".."))throw new Error("Raw object key escapes its configured root");};
const missing=(e:unknown)=>{const x=e as {name?:string;$metadata?:{httpStatusCode?:number}};return x.name==="NotFound"||x.$metadata?.httpStatusCode===404;};
const checksum=(expected:string|undefined,actual:string)=>{if(expected!==undefined&&(!/^[a-f0-9]{64}$/.test(expected)||expected!==actual))throw new Error("Raw object checksum mismatch");};
const abort=(signal:AbortSignal|undefined)=>{if(signal?.aborted)throw new Error("Raw object upload aborted");};
async function receipt(path:string,key:string,root:string):Promise<RawObjectResult>{const hash=createHash("sha256");let byteSize=0;for await(const chunk of createReadStream(path)){hash.update(chunk);byteSize+=chunk.length;}return {storeKind:"local",storeLocator:root,objectKey:key,sha256:hash.digest("hex"),byteSize};}
export class LocalRawObjectStore implements RawObjectStore { constructor(private readonly root:string){} async put(input:RawObjectPut):Promise<RawObjectResult>{safeKey(input.objectKey);abort(input.signal);await mkdir(this.root,{recursive:true});const root=await realpath(this.root);let parent=root;for(const part of input.objectKey.split("/").slice(0,-1)){const next=resolve(parent,part);try{const s=await lstat(next);if(s.isSymbolicLink()||!s.isDirectory())throw new Error("Raw object path resolves outside its configured root");}catch(e){if((e as NodeJS.ErrnoException).code!=="ENOENT")throw e;await mkdir(next);const s=await lstat(next);if(s.isSymbolicLink()||!s.isDirectory())throw new Error("Raw object path resolves outside its configured root");}parent=next;}if(relative(root,parent).startsWith(".."))throw new Error("Raw object key escapes its configured root");const target=resolve(parent,basename(input.objectKey));try{const s=await lstat(target);if(s.isSymbolicLink()||!s.isFile())throw new Error("Raw object target cannot be replaced");if(!input.expectedSha256)throw new Error("Raw object key already exists; expected checksum is required");const old=await receipt(target,input.objectKey,root);checksum(input.expectedSha256,old.sha256);return old;}catch(e){if((e as NodeJS.ErrnoException).code!=="ENOENT")throw e;}const temp=resolve(parent,`.${basename(target)}.${randomUUID()}.partial`),hash=createHash("sha256");let byteSize=0;const meter=new Transform({transform(chunk:Buffer,_enc,cb){hash.update(chunk);byteSize+=chunk.length;cb(null,chunk);}});try{await pipeline(Readable.from(input.body),meter,createWriteStream(temp,{flags:"wx"}),{signal:input.signal});const sha256=hash.digest("hex");checksum(input.expectedSha256,sha256);try{await link(temp,target);}catch(e){if((e as NodeJS.ErrnoException).code!=="EEXIST")throw e;const old=await receipt(target,input.objectKey,root);if(old.sha256!==sha256)throw new Error("Raw object key already exists with different bytes");return old;}return {storeKind:"local",storeLocator:root,objectKey:input.objectKey,sha256,byteSize};}finally{await rm(temp,{force:true});}}}
export class S3RawObjectStore implements RawObjectStore { constructor(private readonly client:S3Sender,private readonly bucket:string,private readonly uploadFactory:S3UploadFactory=(p)=>new Upload({client:client as S3Client,params:p,leavePartsOnError:false})){} async put(input:RawObjectPut):Promise<RawObjectResult>{safeKey(input.objectKey);abort(input.signal);const v=await this.client.send(new GetBucketVersioningCommand({Bucket:this.bucket}));if(v.Status!=="Enabled")throw new Error("RAW_OBJECT_BUCKET must have versioning Enabled");if(input.expectedSha256){const key=`${input.objectKey}.${input.expectedSha256}`;try{const old=await this.client.send(new HeadObjectCommand({Bucket:this.bucket,Key:key}));if(!old.VersionId||old.Metadata?.sha256!==input.expectedSha256||!Number.isSafeInteger(Number(old.ContentLength))||Number(old.ContentLength)<0)throw new Error("Raw object key already exists with different checksum");return {storeKind:"s3",storeLocator:this.bucket,objectKey:key,sha256:input.expectedSha256,byteSize:Number(old.ContentLength),versionId:old.VersionId,etag:old.ETag};}catch(e){if(!missing(e))throw e;}}const temp=`${input.objectKey}.tmp.${randomUUID()}`,hash=createHash("sha256");let byteSize=0;const meter=new Transform({transform(chunk:Buffer,_enc,cb){hash.update(chunk);byteSize+=chunk.length;cb(null,chunk);}}),upload=this.uploadFactory({Bucket:this.bucket,Key:temp,Body:Readable.from(input.body).pipe(meter)}),onAbort=()=>{void upload.abort();};input.signal?.addEventListener("abort",onAbort,{once:true});let tempVersion:string|undefined;try{const done=await upload.done();tempVersion=done.VersionId;if(!tempVersion)throw new Error("Raw object upload did not return a VersionId");const sha256=hash.digest("hex");checksum(input.expectedSha256,sha256);abort(input.signal);const key=`${input.objectKey}.${sha256}`,copied=await this.client.send(new CopyObjectCommand({Bucket:this.bucket,Key:key,CopySource:`${this.bucket}/${encodeURIComponent(temp)}?versionId=${encodeURIComponent(tempVersion)}`,MetadataDirective:"REPLACE",Metadata:{sha256}}));if(!copied.VersionId)throw new Error("Raw object promotion did not return a VersionId");const verified=await this.client.send(new HeadObjectCommand({Bucket:this.bucket,Key:key,VersionId:copied.VersionId}));if(verified.VersionId!==copied.VersionId||verified.Metadata?.sha256!==sha256||Number(verified.ContentLength)!==byteSize)throw new Error("Raw object promotion verification failed");return {storeKind:"s3",storeLocator:this.bucket,objectKey:key,sha256,byteSize,versionId:copied.VersionId,etag:verified.ETag??copied.CopyObjectResult?.ETag};}finally{input.signal?.removeEventListener("abort",onAbort);if(tempVersion)await this.client.send(new DeleteObjectCommand({Bucket:this.bucket,Key:temp,VersionId:tempVersion}));}}}
