import { createHash, randomUUID } from "node:crypto";
import { createReadStream, createWriteStream } from "node:fs";
import { link, lstat, mkdir, realpath, rm } from "node:fs/promises";
import { basename, isAbsolute, relative, resolve } from "node:path";
import { Readable, Transform } from "node:stream";
import { pipeline } from "node:stream/promises";
import { CopyObjectCommand, DeleteObjectCommand, GetBucketVersioningCommand, GetObjectCommand, HeadObjectCommand, PutObjectCommand, S3Client } from "@aws-sdk/client-s3";
import { Upload } from "@aws-sdk/lib-storage";

export interface RawObjectPut { readonly objectKey:string; readonly body:AsyncIterable<Uint8Array>; readonly expectedSha256?:string; readonly signal?:AbortSignal; }
export interface RawObjectResult { readonly storeKind:"local"|"s3"; readonly storeLocator:string; readonly objectKey:string; readonly sha256:string; readonly byteSize:number; readonly versionId?:string; readonly etag?:string; }
/** Internal direct-final V2 result; visible versions are never deleted and require operator reconciliation on failure. */
export type VersionedPutResult=Readonly<{storeKind:"s3";storeLocator:string;objectKey:string;sha256:string;byteSize:number;versionId:string;etag:string;disposition:"created"|"existing"}>;
export interface RawObjectStore { put(input:RawObjectPut):Promise<RawObjectResult>; read(receipt:RawObjectResult,signal?:AbortSignal):Promise<Uint8Array>; }
interface UploadHandle { done():Promise<{VersionId?:string;ETag?:string}>; abort():Promise<void>|void; }
export type S3UploadFactory=(params:{Bucket:string;Key:string;Body:Readable})=>UploadHandle;
type S3Sender=Pick<S3Client,"send">;
const maxReadBytes=256*1024*1024;
const abort=(signal?:AbortSignal)=>{if(signal?.aborted)throw new Error("Raw object upload aborted");};
const safeKey=(key:string)=>{if(!key||isAbsolute(key)||key.includes("\\")||key.split("/").includes(".."))throw new Error("Raw object key escapes its configured root");};
const missing=(e:unknown)=>{const x=e as {name?:string;$metadata?:{httpStatusCode?:number}};return x.name==="NotFound"||x.$metadata?.httpStatusCode===404;};
const checksum=(expected:string|undefined,actual:string)=>{if(expected!==undefined&&(!/^[a-f0-9]{64}$/.test(expected)||expected!==actual))throw new Error("Raw object checksum mismatch");};
const validVersion=(value:unknown):value is string=>typeof value==="string"&&value.length>0;
const validEtag=(value:unknown):value is string=>typeof value==="string"&&value.length>0;
const verifyReceipt=(value:RawObjectResult,kind:"local"|"s3",locator:string)=>{if(value.storeKind!==kind||value.storeLocator!==locator)throw new Error("Raw object receipt does not belong to this store");safeKey(value.objectKey);if(!/^[a-f0-9]{64}$/.test(value.sha256)||!Number.isSafeInteger(value.byteSize)||value.byteSize<0||value.byteSize>maxReadBytes)throw new Error("Raw object receipt is invalid");};
const collect=async(body:AsyncIterable<Uint8Array>,value:RawObjectResult,signal?:AbortSignal)=>{const hash=createHash("sha256"),chunks:Buffer[]=[];let size=0;for await(const chunk of body){abort(signal);const copy=Buffer.from(chunk);size+=copy.length;if(size>maxReadBytes||size>value.byteSize)throw new Error("Raw object exceeds read limit");hash.update(copy);chunks.push(copy);}abort(signal);if(size!==value.byteSize||hash.digest("hex")!==value.sha256)throw new Error("Raw object content verification failed");return Buffer.concat(chunks,size);};
async function localReceipt(path:string,key:string,root:string):Promise<RawObjectResult>{const hash=createHash("sha256");let byteSize=0;for await(const chunk of createReadStream(path)){hash.update(chunk);byteSize+=chunk.length;}return {storeKind:"local",storeLocator:root,objectKey:key,sha256:hash.digest("hex"),byteSize};}

export class LocalRawObjectStore implements RawObjectStore {
  constructor(private readonly root:string){}
  async read(value:RawObjectResult,signal?:AbortSignal):Promise<Uint8Array>{abort(signal);const root=await realpath(this.root);abort(signal);verifyReceipt(value,"local",root);let current=root;for(const [i,part] of value.objectKey.split("/").entries()){const next=resolve(current,part);if(relative(root,next).startsWith(".."))throw new Error("Raw object key escapes its configured root");const stat=await lstat(next);abort(signal);if(stat.isSymbolicLink()||(i===value.objectKey.split("/").length-1?!stat.isFile():!stat.isDirectory()))throw new Error("Raw object path is not a regular file");current=next;}return collect(createReadStream(current),value,signal);}
  async put(input:RawObjectPut):Promise<RawObjectResult>{safeKey(input.objectKey);abort(input.signal);await mkdir(this.root,{recursive:true});abort(input.signal);const root=await realpath(this.root);let parent=root;for(const part of input.objectKey.split("/").slice(0,-1)){const next=resolve(parent,part);await mkdir(next,{recursive:true});const s=await lstat(next);abort(input.signal);if(s.isSymbolicLink()||!s.isDirectory())throw new Error("Raw object path resolves outside its configured root");parent=next;}const target=resolve(parent,basename(input.objectKey));try{const old=await localReceipt(target,input.objectKey,root);checksum(input.expectedSha256,old.sha256);return old;}catch(e){if((e as NodeJS.ErrnoException).code!=="ENOENT")throw e;}const temp=resolve(parent,`.${basename(target)}.${randomUUID()}.partial`),hash=createHash("sha256");let byteSize=0;const meter=new Transform({transform(chunk:Buffer,_e,cb){hash.update(chunk);byteSize+=chunk.length;cb(null,chunk);}});try{await pipeline(Readable.from(input.body),meter,createWriteStream(temp,{flags:"wx"}),{signal:input.signal});abort(input.signal);const sha256=hash.digest("hex");checksum(input.expectedSha256,sha256);try{await link(temp,target);}catch(e){if((e as NodeJS.ErrnoException).code!=="EEXIST")throw e;const old=await localReceipt(target,input.objectKey,root);if(old.sha256!==sha256)throw new Error("Raw object key already exists with different bytes");return old;}return {storeKind:"local",storeLocator:root,objectKey:input.objectKey,sha256,byteSize};}finally{await rm(temp,{force:true});}}
}

export class S3RawObjectStore implements RawObjectStore {
  /** Configured bucket identity only; deliberately exposes no client or credentials. */
  get storeLocator(): string { return this.bucket; }
  constructor(private readonly client:S3Sender,private readonly bucket:string,private readonly uploadFactory:S3UploadFactory=(p)=>new Upload({client:client as S3Client,params:p,leavePartsOnError:false})){}
  async assertVersioning(signal?:AbortSignal):Promise<void>{abort(signal);const v=await this.client.send(new GetBucketVersioningCommand({Bucket:this.bucket}),{abortSignal:signal});abort(signal);if(v.Status!=="Enabled")throw new Error("RAW_OBJECT_BUCKET must have versioning Enabled");}
  async read(value:RawObjectResult,signal?:AbortSignal):Promise<Uint8Array>{abort(signal);verifyReceipt(value,"s3",this.bucket);if(!validVersion(value.versionId)||value.versionId==="null")throw new Error("Raw object receipt requires a VersionId");const output=await this.client.send(new GetObjectCommand({Bucket:this.bucket,Key:value.objectKey,VersionId:value.versionId}),{abortSignal:signal}) as {VersionId?:string;ETag?:string;Metadata?:Record<string,string>;ContentLength?:number;Body?:AsyncIterable<Uint8Array>};abort(signal);if(output.VersionId!==value.versionId||output.Metadata?.sha256!==value.sha256||output.ContentLength!==value.byteSize||(value.etag!==undefined&&output.ETag!==value.etag)||!output.Body)throw new Error("Raw object response verification failed");return collect(output.Body,value,signal);}
  private async upload(key:string,body:AsyncIterable<Uint8Array>,signal?:AbortSignal):Promise<{VersionId:string;ETag?:string}> { abort(signal);const upload=this.uploadFactory({Bucket:this.bucket,Key:key,Body:Readable.from(body)});let abortPromise:Promise<void>|undefined;const onAbort=()=>{abortPromise??=Promise.resolve(upload.abort()).catch(()=>undefined);};signal?.addEventListener("abort",onAbort,{once:true});try{if(signal?.aborted){onAbort();await abortPromise;abort(signal);}const done=await upload.done();abort(signal);if(!validVersion(done.VersionId))throw new Error("Raw object upload did not return a VersionId");return {VersionId:done.VersionId,ETag:done.ETag};}finally{signal?.removeEventListener("abort",onAbort);if(signal?.aborted){onAbort();await abortPromise;}} }
  private async cleanup(key:string,versionId?:string):Promise<void>{const c=new AbortController();const timer=setTimeout(()=>c.abort(),5_000);try{await this.client.send(new DeleteObjectCommand({Bucket:this.bucket,Key:key,...(versionId?{VersionId:versionId}:{})}),{abortSignal:c.signal});}finally{clearTimeout(timer);}}
  async put(input:RawObjectPut):Promise<RawObjectResult>{safeKey(input.objectKey);await this.assertVersioning(input.signal);if(input.expectedSha256){const key=`${input.objectKey}.${input.expectedSha256}`;try{abort(input.signal);const old=await this.client.send(new HeadObjectCommand({Bucket:this.bucket,Key:key}),{abortSignal:input.signal});abort(input.signal);if(!validVersion(old.VersionId)||old.Metadata?.sha256!==input.expectedSha256||!Number.isSafeInteger(Number(old.ContentLength))||Number(old.ContentLength)<0)throw new Error("Raw object key already exists with different checksum");return {storeKind:"s3",storeLocator:this.bucket,objectKey:key,sha256:input.expectedSha256,byteSize:Number(old.ContentLength),versionId:old.VersionId,etag:old.ETag};}catch(e){if(!missing(e))throw e;}}const temp=`${input.objectKey}.tmp.${randomUUID()}`,hash=createHash("sha256");let byteSize=0;const metered=(async function*(){for await(const part of input.body){abort(input.signal);const copy=Uint8Array.from(part);hash.update(copy);byteSize+=copy.byteLength;yield copy;}})();let version:string|undefined;try{const done=await this.upload(temp,metered,input.signal);version=done.VersionId;const sha256=hash.digest("hex");checksum(input.expectedSha256,sha256);abort(input.signal);const key=`${input.objectKey}.${sha256}`;const copied=await this.client.send(new CopyObjectCommand({Bucket:this.bucket,Key:key,CopySource:`${this.bucket}/${encodeURIComponent(temp)}?versionId=${encodeURIComponent(version)}`,MetadataDirective:"REPLACE",Metadata:{sha256}}),{abortSignal:input.signal});abort(input.signal);if(!validVersion(copied.VersionId))throw new Error("Raw object promotion did not return a VersionId");const verified=await this.client.send(new HeadObjectCommand({Bucket:this.bucket,Key:key,VersionId:copied.VersionId}),{abortSignal:input.signal});abort(input.signal);if(verified.VersionId!==copied.VersionId||verified.Metadata?.sha256!==sha256||Number(verified.ContentLength)!==byteSize)throw new Error("Raw object promotion verification failed");return {storeKind:"s3",storeLocator:this.bucket,objectKey:key,sha256,byteSize,versionId:copied.VersionId,etag:verified.ETag??copied.CopyObjectResult?.ETag};}finally{await this.cleanup(temp,version);}}
  /** Direct-final V2 objects are immutable once PutObject is visible; callers reconcile failures. */
  async putKnownVersioned(input:Readonly<{objectKey:string;body:Uint8Array;expectedByteSize:number;expectedSha256:string;signal?:AbortSignal;onMutationAttempt?:()=>void}>):Promise<VersionedPutResult>{safeKey(input.objectKey);if(!/^[a-f0-9]{64}$/.test(input.expectedSha256)||!input.objectKey.endsWith(`.${input.expectedSha256}`)||!Number.isSafeInteger(input.expectedByteSize)||input.expectedByteSize<0||input.expectedByteSize>64*1024*1024||!(input.body instanceof Uint8Array)||input.body.byteLength!==input.expectedByteSize)throw new Error("Raw object checksum mismatch");await this.assertVersioning(input.signal);try{const old=await this.client.send(new HeadObjectCommand({Bucket:this.bucket,Key:input.objectKey}),{abortSignal:input.signal});abort(input.signal);if(!validVersion(old.VersionId)||old.VersionId==="null"||!validEtag(old.ETag)||old.Metadata?.sha256!==input.expectedSha256||Number(old.ContentLength)!==input.expectedByteSize)throw new Error("Raw object key already exists with different checksum");return {storeKind:"s3",storeLocator:this.bucket,objectKey:input.objectKey,sha256:input.expectedSha256,byteSize:input.expectedByteSize,versionId:old.VersionId,etag:old.ETag,disposition:"existing"};}catch(e){if(!missing(e))throw e;}if(createHash("sha256").update(input.body).digest("hex")!==input.expectedSha256)throw new Error("Raw object checksum mismatch");input.onMutationAttempt?.();const result=await this.client.send(new PutObjectCommand({Bucket:this.bucket,Key:input.objectKey,Body:input.body,Metadata:{sha256:input.expectedSha256}}),{abortSignal:input.signal});const versionId=result.VersionId;abort(input.signal);if(!validVersion(versionId)||versionId==="null"||!validEtag(result.ETag))throw new Error("Raw object upload did not return a VersionId");const head=await this.client.send(new HeadObjectCommand({Bucket:this.bucket,Key:input.objectKey,VersionId:versionId}),{abortSignal:input.signal});abort(input.signal);if(head.VersionId!==versionId||head.ETag!==result.ETag||head.Metadata?.sha256!==input.expectedSha256||Number(head.ContentLength)!==input.expectedByteSize)throw new Error("Raw object promotion verification failed");return {storeKind:"s3",storeLocator:this.bucket,objectKey:input.objectKey,sha256:input.expectedSha256,byteSize:input.expectedByteSize,versionId,etag:result.ETag,disposition:"created"};}
}
