import { createHash, randomUUID } from "node:crypto";
import type { Pool, PoolClient } from "pg";
import { failExpiredRun, markFailed, markLoaded, markValidated, recordQuarantineBatch, recordStageBatch, startIngestRun } from "@/db/ingestion";
import type { ReleaseId, SourceId } from "@/domain/contracts";
import type { RawObject, SourceAdapter } from "./types";

export interface RunSourceOptions { readonly pool: Pool; readonly releaseId: ReleaseId; readonly sourceId: SourceId; readonly cutoff: Date; readonly maxBatchSize?: number; readonly dryRun?: boolean; readonly signal?: AbortSignal; readonly leaseDurationMs?: number; }
export interface RunSourceResult { readonly runIds: readonly string[]; readonly reusedRunIds: readonly string[]; }
type Prior = { id: string; status: "running" | "validated" | "failed" | "loaded"; lease_token: string; lease_expires_at: Date | null; snapshot_id: string; raw_store_kind: "local" | "s3"; raw_store_locator: string; raw_object_key: string; raw_object_sha256: string; raw_object_byte_size: string | number; raw_object_version_id: string | null; raw_object_etag: string | null };
const checkAbort = (signal: AbortSignal | undefined): void => { if (signal?.aborted) throw new Error("INGEST_ABORTED"); };
const diagnostic = (code: string): string => `parse_${createHash("sha256").update(code).digest("hex").slice(0, 16)}`;
const opaqueKey = (value: string): string => createHash("sha256").update(value).digest("hex");
const identityFor = (release: string, source: string, adapter: string, upstream: string, hash: string): string => createHash("sha256").update([release, source, adapter, upstream, hash].join("\n")).digest("hex");
const validKey = (key: string): boolean => !!key && !key.startsWith("/") && !key.includes("\\") && !key.split("/").includes("..");
const validLease = (value: number): number => { const result = value ?? 60_000; if (!Number.isSafeInteger(result) || result < 1) throw new Error("leaseDurationMs must be a positive integer"); return result; };
const persistedByteSize = (value: string | number): number | undefined => {
 if (typeof value === "number") return Number.isSafeInteger(value) && value >= 0 ? value : undefined;
 if (!/^(?:0|[1-9][0-9]*)$/.test(value)) return undefined;
 const parsed = Number(value);
 return Number.isSafeInteger(parsed) ? parsed : undefined;
};
const receiptMatches = (run: Prior, raw: RawObject<unknown>): boolean => run.snapshot_id === raw.snapshot.id && run.raw_store_kind === raw.receipt.storeKind && run.raw_store_locator === raw.receipt.storeLocator && run.raw_object_key === raw.receipt.objectKey && run.raw_object_sha256 === raw.receipt.sha256 && persistedByteSize(run.raw_object_byte_size) === raw.receipt.byteSize && (run.raw_object_version_id ?? undefined) === raw.receipt.versionId && (run.raw_object_etag ?? undefined) === raw.receipt.etag;

async function snapshot(client: PoolClient, raw: RawObject<unknown>, releaseId: string, sourceId: string, parserVersion: string, insert: boolean): Promise<void> {
 const values=[sourceId,raw.snapshot.sourceUrl,raw.snapshot.publishedAt?.toISOString() ?? null,raw.snapshot.checksumSha256,parserVersion,raw.snapshot.license,raw.snapshot.usageStatus];
 const old=await client.query<{source_id:string;source_url:string;published_at:Date|null;checksum_sha256:string;parser_version:string;license:string;usage_status:string}>(`SELECT source_id,source_url,published_at,checksum_sha256,parser_version,license,usage_status FROM source_snapshots WHERE release_id=$1 AND id=$2${insert ? " FOR UPDATE" : ""}`,[releaseId,raw.snapshot.id]);
 if (!old.rowCount) { if (!insert) throw new Error("SNAPSHOT_CONFLICT"); await client.query("INSERT INTO source_snapshots(id,release_id,source_id,source_url,published_at,retrieved_at,checksum_sha256,parser_version,license,usage_status) VALUES($1,$2,$3,$4,$5,now(),$6,$7,$8,$9)",[raw.snapshot.id,releaseId,...values]); return; }
 const row=old.rows[0]!; if(row.source_id!==values[0]||row.source_url!==values[1]||(row.published_at?.toISOString()??null)!==values[2]||row.checksum_sha256!==values[3]||row.parser_version!==values[4]||row.license!==values[5]||row.usage_status!==values[6]) throw new Error("SNAPSHOT_CONFLICT");
}

export async function runSource<TRaw,TStage>(adapter:SourceAdapter<TRaw,TStage>,options:RunSourceOptions):Promise<RunSourceResult> {
 const max=options.maxBatchSize??1000, leaseDurationMs=validLease(options.leaseDurationMs ?? 60_000); if(!Number.isInteger(max)||max<1||max>1000)throw new Error("maxBatchSize must be an integer from 1 through 1000"); if(!(options.cutoff instanceof Date)||!Number.isFinite(options.cutoff.getTime()))throw new Error("cutoff must be a valid UTC date");
 const runIds:string[]=[],reusedRunIds:string[]=[];
 for await(const raw of adapter.extract({releaseId:options.releaseId,sourceId:options.sourceId,cutoff:options.cutoff,signal:options.signal})) {
  checkAbort(options.signal); if(!Number.isSafeInteger(raw.expectedRecordCount)||raw.expectedRecordCount<0||raw.receipt.sha256!==raw.snapshot.checksumSha256||!/^[a-f0-9]{64}$/.test(raw.receipt.sha256)||!validKey(raw.receipt.objectKey)||!Number.isSafeInteger(raw.receipt.byteSize)||raw.receipt.byteSize<0||!raw.receipt.storeLocator||(raw.receipt.storeKind==="s3"&&!raw.receipt.versionId)||(raw.receipt.storeKind==="local"&&raw.receipt.versionId))throw new Error("RAW_RECEIPT_MISMATCH");
  const client=await options.pool.connect(), identity=identityFor(options.releaseId,options.sourceId,adapter.adapterVersion,raw.snapshot.upstreamRelease,raw.receipt.sha256); let runId:string|undefined,leaseToken:string|undefined;
  try {
   const lock=await client.query<{acquired:boolean}>("SELECT pg_try_advisory_lock(hashtextextended($1, 0)) AS acquired",[identity]); if(!lock.rows[0]?.acquired)throw new Error("INGEST_ALREADY_RUNNING"); await client.query("BEGIN");
   const prior=await client.query<Prior>("SELECT id,status,lease_token,lease_expires_at,snapshot_id,raw_store_kind,raw_store_locator,raw_object_key,raw_object_sha256,raw_object_byte_size,raw_object_version_id,raw_object_etag FROM ingest_runs WHERE release_id=$1 AND source_id=$2 AND adapter_version=$3 AND upstream_release=$4 AND raw_object_sha256=$5 ORDER BY CASE status WHEN 'loaded' THEN 1 WHEN 'validated' THEN 2 WHEN 'running' THEN 3 WHEN 'failed' THEN 4 END, started_at DESC FOR UPDATE",[options.releaseId,options.sourceId,adapter.adapterVersion,raw.snapshot.upstreamRelease,raw.receipt.sha256]); const old=prior.rows[0];
   if(old&&(old.status==="loaded"||(old.status==="validated"&&options.dryRun))){if(!receiptMatches(old,raw))throw new Error("RAW_RECEIPT_MISMATCH");await snapshot(client,raw,options.releaseId,options.sourceId,adapter.adapterVersion,false);await client.query("COMMIT");reusedRunIds.push(old.id);continue;}
   if(old?.status==="running"){if(!receiptMatches(old,raw))throw new Error("RAW_RECEIPT_MISMATCH");if(old.lease_expires_at&&old.lease_expires_at>new Date())throw new Error("INGEST_ALREADY_RUNNING");await failExpiredRun(client,old.id,old.lease_token);}
   await snapshot(client,raw,options.releaseId,options.sourceId,adapter.adapterVersion,old?.status!=="validated");
   if(old?.status==="validated"){if(!receiptMatches(old,raw))throw new Error("RAW_RECEIPT_MISMATCH");await adapter.loadFromStage(client,old.id,options.releaseId);await markLoaded(client,old.id,old.lease_token);await client.query("COMMIT");runIds.push(old.id);continue;}
   runId=`run_${identity}${old?`_${randomUUID()}`:""}`;leaseToken=randomUUID();await startIngestRun(client,{id:runId,releaseId:options.releaseId,sourceId:options.sourceId,snapshotId:raw.snapshot.id,adapterVersion:adapter.adapterVersion,upstreamRelease:raw.snapshot.upstreamRelease,rawStoreKind:raw.receipt.storeKind,rawStoreLocator:raw.receipt.storeLocator,rawObjectKey:raw.receipt.objectKey,rawObjectSha256:raw.receipt.sha256,rawObjectByteSize:raw.receipt.byteSize,rawObjectVersionId:raw.receipt.versionId,rawObjectEtag:raw.receipt.etag,leaseToken,leaseDurationMs,extractedCount:raw.expectedRecordCount});await client.query("COMMIT");
   let rows:TStage[]=[],quarantines:Array<{sourceNaturalKey:string;payloadChecksum:string;errorCode:string}>=[],accounted=0;
   const flush=async()=>{if(!rows.length&&!quarantines.length)return;await client.query("BEGIN");try{if(rows.length){await adapter.stage(client,runId!,rows);await recordStageBatch(client,runId!,leaseToken!,rows.length,leaseDurationMs);}if(quarantines.length){await client.query("INSERT INTO quarantined_records(run_id,release_id,source_natural_key,snapshot_id,payload_checksum,parser_error_code,redacted_diagnostic) SELECT $1,$2,x.key,$3,x.checksum,x.code,'parser failure' FROM unnest($4::text[],$5::text[],$6::text[]) AS x(key,checksum,code)",[runId,options.releaseId,raw.snapshot.id,quarantines.map(q=>opaqueKey(q.sourceNaturalKey)),quarantines.map(q=>q.payloadChecksum),quarantines.map(q=>diagnostic(q.errorCode))]);await recordQuarantineBatch(client,runId!,leaseToken!,quarantines.length,leaseDurationMs);}await client.query("COMMIT");rows=[];quarantines=[];}catch(e){await client.query("ROLLBACK");throw e;}};
   let keys=new Set<string>();for await(const parsed of adapter.parse(raw)){checkAbort(options.signal);if(++accounted>raw.expectedRecordCount)throw new Error("Parsed record count exceeds raw object manifest count");if(parsed.kind==="quarantine"){if(!/^[a-f0-9]{64}$/.test(parsed.payloadChecksum))throw new Error("PARSER_RECEIPT_MISMATCH");if(keys.has(parsed.sourceNaturalKey))throw new Error("DUPLICATE_BATCH_KEY");keys.add(parsed.sourceNaturalKey);quarantines.push(parsed);}else{const key=adapter.naturalKey(parsed.row);if(keys.has(key))throw new Error("DUPLICATE_BATCH_KEY");keys.add(key);rows.push(parsed.row);}if(rows.length+quarantines.length===max){await flush();keys=new Set<string>();}}
   if(accounted!==raw.expectedRecordCount)throw new Error("Parsed record count does not match raw object manifest count");await flush();await client.query("BEGIN");const issues=await adapter.validateStaged(client,runId);if(issues.length)throw new Error(`Staged validation failed: ${issues.map(x=>x.code).join(",").slice(0,256)}`);await markValidated(client,runId,leaseToken);if(!options.dryRun){await adapter.loadFromStage(client,runId,options.releaseId);await markLoaded(client,runId,leaseToken);}await client.query("COMMIT");runIds.push(runId);
  }catch(error){await client.query("ROLLBACK").catch(()=>undefined);if(runId&&leaseToken){try{await client.query("BEGIN");await markFailed(client,runId,leaseToken);await client.query("COMMIT");}catch{await client.query("ROLLBACK").catch(()=>undefined);}}const msg=error instanceof Error?error.message:"";const safe=["INGEST_ABORTED","DUPLICATE_BATCH_KEY","SNAPSHOT_CONFLICT","RAW_RECEIPT_MISMATCH","INGEST_ALREADY_RUNNING","Parsed record count exceeds raw object manifest count","Parsed record count does not match raw object manifest count","Staged validation failed"].find(x=>msg.startsWith(x));throw new Error(safe??"Ingestion failed");}finally{await client.query("SELECT pg_advisory_unlock(hashtextextended($1, 0))",[identity]).catch(()=>undefined);client.release();}
 }
 return {runIds,reusedRunIds};
}
export const checksumPayload=(payload:Uint8Array):string=>createHash("sha256").update(payload).digest("hex");
