/** Local-only FEC research acquisition.  This deliberately has no DB/release imports. */
import { createHash } from "node:crypto";
import { lstat, link, mkdir, open, readFile, rename, unlink } from "node:fs/promises";
import { dirname, relative, resolve, sep } from "node:path";
import { loadFecApiCredential } from "@/ingestion/fec/credential";
import { encodeFecAcquisitionPlan, fecAcquisitionPlanSha256, fecTargetUniverseSha256, type FecAcquisitionPlanV2 } from "@/ingestion/fec/acquisition-plan";
import { enumerateNationwideFecFilings, type FecEnumeratorResult } from "@/ingestion/fec/fec-enumerator";
import { FecV2RunBudget } from "@/ingestion/fec/fetch-client-v2";
import { loadFecEfoLayouts } from "@/ingestion/fec/efo-layout";
import { encodeFecSanitizedFilingArtifact } from "@/ingestion/fec/efo-sanitizer";
import { acquireCanonicalFecV2SanitizedFilingForLocalResearch, FecSanitizedFilingAcquisitionError, type FecLocalResearchSanitizedFilingOptions, type FecLocalResearchSanitizedFilingResult } from "@/ingestion/fec/sanitized-filing-acquisition";

const MAX_MANIFEST_BYTES = 8 * 1024 * 1024;
type Args = Readonly<{ output: string; artifacts: string; hours: number; resume: boolean }>;
export type LocalManifest = Readonly<{ schema: "fec-local-research-manifest-v1"; publicationEligible: false; reviewStatus: "unreviewed"; purpose: "local-research-acquisition"; planSha256: string; createdAt: string; updatedAt: string; completed: boolean; counts: { pages: number; entries: number; sanitized: number; outcomes: number }; ledger?: Receipt; pages: Receipt[]; sanitized: Array<{ fileNumber: number; receipt: Receipt }>; outcomes: Array<{ fileNumber: number; outcome: string }> }>;
export type LocalResearchArtifactRecord = Readonly<{ kind: string; relativePath: string; sha256: string; byteSize: number }>;
type Receipt = LocalResearchArtifactRecord;
const sha = (b: Uint8Array) => createHash("sha256").update(b).digest("hex");
const canonical = (value: unknown) => Buffer.from(`${JSON.stringify(value)}\n`);
export function parseFetchFecLocalArguments(argv: readonly string[]): Args { let output: string | undefined, artifacts: string | undefined, hours = 6, resume = false; for (let i = 0; i < argv.length; i++) { const x = argv[i]; if (x === "--resume" && !resume) { resume = true; continue; } if (x !== "--output" && x !== "--hours" && x !== "--artifacts") throw new Error("FEC_LOCAL_ARGUMENT_INVALID"); const value = argv[++i]; if (!value || value.startsWith("--") || value.includes("\0")) throw new Error("FEC_LOCAL_ARGUMENT_INVALID"); if (x === "--output" && !output) output = value; else if (x === "--artifacts" && !artifacts) artifacts = value; else if (x === "--hours" && /^\d+$/.test(value) && Number(value) >= 1 && Number(value) <= 6) hours = Number(value); else throw new Error("FEC_LOCAL_ARGUMENT_INVALID"); } if (!output) throw new Error("FEC_LOCAL_ARGUMENT_INVALID"); return { output, artifacts: artifacts ?? `${output}.artifacts`, hours, resume }; }
const safeKind = (kind: string): boolean => /^[a-z_]+$/.test(kind);
/** Private content-addressed writer; deliberately not a VersionedRawObjectStore. */
export async function writeLocalResearchArtifact(root: string, kind: string, bytes: Uint8Array, expectedSha256 = sha(bytes)): Promise<LocalResearchArtifactRecord> { if (!safeKind(kind) || bytes.byteLength > 64 * 1024 * 1024 || !/^[a-f0-9]{64}$/.test(expectedSha256) || sha(bytes) !== expectedSha256) throw new Error("FEC_LOCAL_ARTIFACT_INVALID"); const absoluteRoot = resolve(root), dir = resolve(absoluteRoot, kind), target = resolve(dir, `${expectedSha256}.json`); if (!target.startsWith(`${absoluteRoot}${sep}`)) throw new Error("FEC_LOCAL_ARTIFACT_UNSAFE"); await mkdir(dir, { recursive: true, mode: 0o700 }); const existing = async (): Promise<boolean> => { try { const s = await lstat(target); if (s.isSymbolicLink() || !s.isFile() || s.size !== bytes.byteLength) throw new Error("FEC_LOCAL_ARTIFACT_UNSAFE"); return sha(await readFile(target)) === expectedSha256; } catch (e) { if ((e as NodeJS.ErrnoException).code === "ENOENT") return false; throw e; } }; if (!await existing()) { const temp = resolve(dir, `.${expectedSha256}.${process.pid}.${Math.random().toString(16).slice(2)}`), f = await open(temp, "wx", 0o600); try { await f.writeFile(bytes); await f.sync(); } finally { await f.close(); } try { await link(temp, target); } catch (e) { if ((e as NodeJS.ErrnoException).code !== "EEXIST") throw e; } finally { await unlink(temp).catch(() => undefined); } if (!await existing()) throw new Error("FEC_LOCAL_ARTIFACT_CORRUPT"); } return Object.freeze({ kind, relativePath: relative(absoluteRoot, target), sha256: expectedSha256, byteSize: bytes.byteLength }); }
export async function readLocalResearchArtifact(root: string, record: LocalResearchArtifactRecord): Promise<Uint8Array> { if (!safeKind(record.kind) || !/^[a-f0-9]{64}$/.test(record.sha256) || !Number.isSafeInteger(record.byteSize) || record.byteSize < 0 || record.byteSize > 64 * 1024 * 1024 || record.relativePath !== `${record.kind}/${record.sha256}.json`) throw new Error("FEC_LOCAL_ARTIFACT_INVALID"); const target = resolve(root, record.relativePath); if (!target.startsWith(`${resolve(root)}${sep}`)) throw new Error("FEC_LOCAL_ARTIFACT_UNSAFE"); const s = await lstat(target); if (s.isSymbolicLink() || !s.isFile() || s.size !== record.byteSize) throw new Error("FEC_LOCAL_ARTIFACT_UNSAFE"); const bytes = await readFile(target); if (sha(bytes) !== record.sha256) throw new Error("FEC_LOCAL_ARTIFACT_CORRUPT"); try { if (!Buffer.from(bytes).equals(canonical(JSON.parse(Buffer.from(bytes).toString("utf8"))))) throw new Error("bad"); } catch { throw new Error("FEC_LOCAL_ARTIFACT_CORRUPT"); } return bytes; }
export function localResearchPlan(): FecAcquisitionPlanV2 { const ids = Array.from({ length: 541 }, (_, n) => `local_fec_scope_${String(n + 1).padStart(3, "0")}`); return { schemaVersion: 2, adapterVersion: "fec-receipt-cutoff-v2", releaseId: "rel_local_fec_research", receiptCutoff: "2026-07-18", campaignCycle: 2026, sourceLockSha256: sha(Buffer.from("local-research-acquisition-v1\n")), enumerationLowerBound: "2025-01-01", targetUniverseSha256: fecTargetUniverseSha256(ids), forms: ["F24", "F3", "F3X", "F5"], enumeration: { granularity: "day", serverOrderBy: "receipt_date", clientCanonicalOrderBy: "file_number", completePasses: 2 }, targets: ids.map(seatCycleId => ({ kind: "candidate_resolution_required" as const, seatCycleId })) }; }
function base(planSha256: string, now: string): LocalManifest { return { schema: "fec-local-research-manifest-v1", publicationEligible: false, reviewStatus: "unreviewed", purpose: "local-research-acquisition", planSha256, createdAt: now, updatedAt: now, completed: false, counts: { pages: 0, entries: 0, sanitized: 0, outcomes: 0 }, pages: [], sanitized: [], outcomes: [] }; }
function normalize(m: LocalManifest, now: string): LocalManifest { const pages = [...m.pages].sort((a,b) => a.sha256.localeCompare(b.sha256)); const sanitized = [...m.sanitized].sort((a,b) => a.fileNumber-b.fileNumber), outcomes = [...m.outcomes].sort((a,b) => a.fileNumber-b.fileNumber); return { ...m, updatedAt: now, pages, sanitized, outcomes, counts: { pages: pages.length, entries: m.counts.entries, sanitized: sanitized.length, outcomes: outcomes.length } }; }
export async function readLocalManifest(path: string): Promise<LocalManifest | undefined> { try { const s = await lstat(path); if (s.isSymbolicLink() || !s.isFile() || s.size > MAX_MANIFEST_BYTES) throw new Error("FEC_LOCAL_MANIFEST_UNSAFE"); const b = await readFile(path); const m = JSON.parse(b.toString("utf8")) as LocalManifest; if (!Buffer.from(b).equals(canonical(m)) || m.schema !== "fec-local-research-manifest-v1" || m.publicationEligible !== false || m.reviewStatus !== "unreviewed" || m.purpose !== "local-research-acquisition" || !/^[a-f0-9]{64}$/.test(m.planSha256)) throw new Error("FEC_LOCAL_MANIFEST_INVALID"); return m; } catch (e) { if ((e as NodeJS.ErrnoException).code === "ENOENT") return undefined; throw e; } }
export async function writeLocalManifest(path: string, manifest: LocalManifest): Promise<void> { const bytes = canonical(manifest); if (bytes.byteLength > MAX_MANIFEST_BYTES) throw new Error("FEC_LOCAL_MANIFEST_TOO_LARGE"); await mkdir(dirname(path), { recursive: true, mode: 0o700 }); try { if ((await lstat(path)).isSymbolicLink()) throw new Error("FEC_LOCAL_MANIFEST_UNSAFE"); } catch (e) { if ((e as NodeJS.ErrnoException).code !== "ENOENT") throw e; } const temporary = `${path}.tmp-${process.pid}`; const f = await open(temporary, "wx", 0o600); try { await f.writeFile(bytes); await f.sync(); } finally { await f.close(); } await rename(temporary, path); }
type Deps = Readonly<{ enumerate: typeof enumerateNationwideFecFilings; acquire: (options: FecLocalResearchSanitizedFilingOptions) => Promise<FecLocalResearchSanitizedFilingResult>; layout: Awaited<ReturnType<typeof loadFecEfoLayouts>>; writeArtifact: typeof writeLocalResearchArtifact; write: (p: string, m: LocalManifest) => Promise<void>; read: (p: string) => Promise<LocalManifest | undefined>; now: () => string }>;
export async function runFetchFecLocal(args: Args, env: NodeJS.ProcessEnv, deps: Deps, signal = new AbortController().signal): Promise<Pick<LocalManifest, "counts" | "completed">> { const plan = localResearchPlan(), planBytes = encodeFecAcquisitionPlan(plan), planSha256 = fecAcquisitionPlanSha256(planBytes), deadlineMs = Date.now() + args.hours * 3_600_000, budget = new FecV2RunBudget({ signal, deadline: deadlineMs }); let manifest = args.resume ? await deps.read(args.output) : undefined; if (manifest && manifest.planSha256 !== planSha256) throw new Error("FEC_LOCAL_RESUME_PLAN_MISMATCH"); manifest ??= base(planSha256, deps.now()); if (args.resume) for (const receipt of [...manifest.pages, ...(manifest.ledger ? [manifest.ledger] : []), ...manifest.sanitized.map(x => x.receipt)]) await readLocalResearchArtifact(args.artifacts, receipt); let pendingCheckpoint = Promise.resolve(); const checkpoint = async () => { pendingCheckpoint = pendingCheckpoint.then(async () => { manifest = normalize(manifest!, deps.now()); await deps.write(args.output, manifest!); }); await pendingCheckpoint; };
  try { const result: FecEnumeratorResult = await deps.enumerate({ plan, planSha256, budget, apiKey: loadFecApiCredential(env), sinkPage: async a => { if (!manifest!.pages.some(x => x.sha256 === a.artifactSha256)) { const receipt = await deps.writeArtifact(args.artifacts, "enumeration_page", a.bytes, a.artifactSha256); manifest!.pages.push(receipt); await checkpoint(); } } }); manifest.counts.entries = result.counts.entries; if (!manifest.ledger) { const receipt = await deps.writeArtifact(args.artifacts, "filing_ledger", result.ledgerBytes, result.ledgerSha256); manifest = { ...manifest, ledger: receipt }; await checkpoint(); }
    const urls = new Map(result.fecUrlsByFileNumber); let next = 0; const worker = async () => { for (;;) { const entry = result.ledger.entries[next++]; if (!entry) return; const id = entry.identity; if (manifest!.sanitized.some(x => x.fileNumber === id.fileNumber) || manifest!.outcomes.some(x => x.fileNumber === id.fileNumber)) continue; const outcome = id.electronicStatus === "paper" ? "paper_filing_unreviewed" : id.rawAvailability !== "available" ? "source_unavailable" : undefined; if (outcome) { manifest!.outcomes.push({ fileNumber: id.fileNumber, outcome }); await checkpoint(); continue; } const fecUrl = urls.get(id.fileNumber); if (!fecUrl) throw new Error("FEC_LOCAL_EVIDENCE_INCONSISTENT"); try { const got = await deps.acquire({ planSha256, ledgerIdentitySha256: entry.entryIdentitySha256, identity: id, layout: deps.layout, budget, fecUrl, signal, deadlineMs }); const receipt = await deps.writeArtifact(args.artifacts, "sanitized_filing", encodeFecSanitizedFilingArtifact(got.artifact), got.artifactSha256); manifest!.sanitized.push({ fileNumber: id.fileNumber, receipt }); await checkpoint(); } catch (e) { if (e instanceof FecSanitizedFilingAcquisitionError && e.processingOutcome) { manifest!.outcomes.push({ fileNumber: id.fileNumber, outcome: e.processingOutcome }); await checkpoint(); } else throw e; } } }; await Promise.all([worker(), worker()]); manifest = { ...manifest, completed: true }; await checkpoint(); return { counts: manifest.counts, completed: true }; } catch (e) { manifest = { ...manifest, completed: false }; await checkpoint().catch(() => undefined); throw e; } }
async function loadLocalFecLayouts() { const bytes = await readFile("data/metadata/fec-efo-layouts-v1.json"); if (sha(bytes) !== "78b9ee5d72fdca9b34da26a73de152ffc280d89a22ca71f8330aa7d8c04f7929") throw new Error("FEC_LOCAL_LAYOUT_INVALID"); return loadFecEfoLayouts(bytes, "c667016493df28c186445201cf8a2bcff43563bccc41b75b2bcc06366b69132b"); }
export async function executeFetchFecLocal(argv: readonly string[], env = process.env): Promise<Pick<LocalManifest, "counts" | "completed">> {
  const args = parseFetchFecLocalArguments(argv), layout = await loadLocalFecLayouts(), controller = new AbortController(), stop = () => controller.abort(); process.once("SIGINT", stop);
  try {
    return await runFetchFecLocal(args, env, { enumerate: enumerateNationwideFecFilings, acquire: acquireCanonicalFecV2SanitizedFilingForLocalResearch, layout, writeArtifact: writeLocalResearchArtifact, write: writeLocalManifest, read: readLocalManifest, now: () => new Date().toISOString() }, controller.signal);
  } finally { process.removeListener("SIGINT", stop); }
}
export async function main(argv = process.argv.slice(2), env = process.env): Promise<void> { if (env === process.env) { try { process.loadEnvFile(); } catch (e) { if ((e as NodeJS.ErrnoException).code !== "ENOENT") throw e; } } const args = parseFetchFecLocalArguments(argv), result = await executeFetchFecLocal(argv, env); process.stdout.write(`${JSON.stringify({ output: resolve(args.output), artifacts: resolve(args.artifacts), counts: result.counts, completed: result.completed })}\n`); }
if (require.main === module) main().catch(() => { process.stderr.write("FEC_LOCAL_ACQUISITION_FAILED\n"); process.exitCode = 1; });
