import { describe, expect, it } from "vitest";
import { parseFinalizeFecArguments, parseMappingFinalizationSnapshot, parseMappingFinalizationSource } from "./finalize-fec";

const args = ["--release", "rel_candidate", "--source-release", "rel_source", "--run", "run_one", "--source", '{"id":"src_fec","name":"fec","authority":"official","homepageUrl":"https://api.open.fec.gov"}', "--snapshot", '{"id":"snap_fec","sourceId":"src_fec","sourceUrl":"urn:fec","checksumSha256":"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa","publishedAt":null,"retrievedAt":"2024-01-01T00:00:00.000Z","parserVersion":"openfec-sanitized-v1","license":"synthetic","usageStatus":"approved"}', "--mapping-source", '{"id":"src_mapping","name":"ballot","authority":"official","homepageUrl":"https://example.test/mapping"}', "--mapping-snapshot", '{"id":"mapping","sourceId":"src_mapping","sourceUrl":"urn:mapping","checksumSha256":"bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb","publishedAt":null,"retrievedAt":"2024-01-01T00:00:00.000Z","parserVersion":"ballot-mapping-v2","license":"synthetic","usageStatus":"approved"}', "--mapping", '{"candidateId":"H00000001","electionCycle":2024,"candidacyId":"c","seatCycleId":"seat","snapshotId":"mapping","committees":[]}', "--finance-scope", '{"reportForm":"F3","reportType":"YE","coverageStartDate":"2024-01-01","coverageEndDate":"2024-12-31","asOf":"2024-12-31","cutoff":"2024-12-31"}'] as const;
describe("FEC finalization CLI", () => { it("requires a complete, unique, single-run finalization contract", () => { expect(() => parseFinalizeFecArguments(args.slice(0, 6))).toThrow(); expect(() => parseFinalizeFecArguments([...args, "--run", "run_two"])).toThrow(); }); it("requires every exact source and snapshot attestation field", () => { const missingChecksum = args.map((value) => value.includes("checksumSha256") ? value.replace(/,"checksumSha256":"[a-f]+"/, "") : value); expect(() => parseFinalizeFecArguments(missingChecksum)).toThrow(); }); it("accepts a distinct approved mapping parser and rejects loose mapping metadata", () => { expect(parseFinalizeFecArguments(args).mappingSnapshot.parserVersion).toBe("ballot-mapping-v2"); expect(() => parseMappingFinalizationSnapshot({ ...JSON.parse(args[13]), parserVersion: "", extra: true })).toThrow(); }); it("parses the immutable expected metadata", () => { expect(parseFinalizeFecArguments(args)).toMatchObject({ release: "rel_candidate", runIds: ["run_one"], source: { id: "src_fec" }, snapshot: { id: "snap_fec", usageStatus: "approved" }, mappingSource: { id: "src_mapping" }, mappingSnapshot: { id: "mapping" }, mapping: { seatCycleId: "seat" } }); }); });

describe("mapping finalization metadata", () => {
  it("rejects truthy non-string fields", () => {
    expect(() => parseMappingFinalizationSource({ id: 1, name: "Mapping", authority: "derived", homepageUrl: "https://example.test" })).toThrow();
    const snapshot = JSON.parse(args[13]);
    expect(() => parseMappingFinalizationSnapshot({ ...snapshot, parserVersion: 1 })).toThrow();
    expect(() => parseMappingFinalizationSnapshot({ ...snapshot, license: {} })).toThrow();
  });
});
