import { execFileSync } from "node:child_process";
import { createHash } from "node:crypto";
import { readFile, writeFile } from "node:fs/promises";
import { buildNcPrimaryGeographyCandidate } from "../src/ingestion/elections/north-carolina-primary-geography-compatibility-candidate";
const sha = (value: Buffer | string) => createHash("sha256").update(value).digest("hex");
const load = async (path: string) => { const bytes = await readFile(path); return { bytes, json: JSON.parse(bytes.toString("utf8")), sha256: sha(bytes) }; };
const csv = (path: string, member: string) => execFileSync("unzip", ["-p", path, member], { encoding: "utf8", maxBuffer: 32 * 1024 * 1024 });
async function main() { const identity = await load("data/metadata/north-carolina-current-incumbent-primary-linkage-candidate-v1.json"), authority = await readFile("data/source/elections/primary-results/geography/north-carolina/ncga-redistricting.html"), block2022Path = "data/source/elections/primary-results/geography/north-carolina/2022/court-ordered-congressional-block-assignment.zip", block2024Path = "data/source/elections/primary-results/geography/north-carolina/2024/sl-2023-145-congressional-block-assignment.zip", block2026Path = "data/source/elections/primary-results/geography/north-carolina/2026/sl-2025-95-congressional-block-assignment.zip", block2022 = await readFile(block2022Path), block2024 = await readFile(block2024Path), block2026 = await readFile(block2026Path), current = await readFile("data/source/elections/primary-results/geography/north-carolina/current/37_NC_CD119.txt"), sourceLock = JSON.parse(await readFile("data/source-lock.json", "utf8")), value = buildNcPrimaryGeographyCandidate({ identity: identity.json, identityFileSha256: identity.sha256, authorityHtml: authority.toString("utf8"), authorityFileSha256: sha(authority), block2022Csv: csv(block2022Path, "Interim Congressional.csv"), block2022FileSha256: sha(block2022), block2024Csv: csv(block2024Path, "SL 2023-145.csv"), block2024FileSha256: sha(block2024), block2026Csv: csv(block2026Path, "SL 2025-95.csv"), block2026FileSha256: sha(block2026), currentCsv: current.toString("utf8"), currentFileSha256: sha(current), sourceLock }), output = "data/metadata/north-carolina-primary-geography-compatibility-candidate-v1.json", bytes = Buffer.from(`${JSON.stringify(value, null, 2)}\n`); try { await writeFile(output, bytes, { flag: "wx", mode: 0o644 }); } catch (error) { if ((error as NodeJS.ErrnoException).code !== "EEXIST" || !(await readFile(output)).equals(bytes)) throw new Error("NC_PRIMARY_GEOGRAPHY_OUTPUT_CONFLICT"); } console.log(JSON.stringify({ output, byteSize: bytes.length, sha256: sha(bytes), packageSha256: value.packageSha256, rowSetSha256: value.rowSetSha256, summary: value.summary }, null, 2)); }
main().catch((error) => { console.error(error); process.exitCode = 1; });
