import { createHmac, createHash } from "node:crypto";
import { describe, expect, it, vi } from "vitest";
import { parseAddressConfig } from "@/address/config";
import { issueAddressCsrf } from "@/address/security";
import { createAddressHandler } from "./route";

const now = new Date("2026-01-02T03:04:05.000Z");
const base = { ADDRESS_LOOKUP_KILL_SWITCH: "allow", ADDRESS_DEPLOYMENT_ID: "deploy", ADDRESS_DEPLOYMENT_ALLOWLIST: "deploy", ADDRESS_APPROVAL_REVISION: "a".repeat(64), ADDRESS_DATABASE_URL: "postgres://x", ADDRESS_RELEASE_ID: "rel_1", ADDRESS_PRODUCT_VINTAGE: "2025" };
const enabled = parseAddressConfig({ ...base, ADDRESS_LOOKUP_MODE: "enabled", ADDRESS_PUBLIC_ORIGIN: "https://example.test", ADDRESS_TRUSTED_IP_HEADER: "x-address-edge", ADDRESS_CSRF_SECRET: "c".repeat(32), ADDRESS_SUBJECT_HMAC_SECRET: "s".repeat(32), ADDRESS_SUBJECT_HMAC_GENERATION: "one" });
const runtime = (repository = { consumeMetadataAttempt: vi.fn(async () => ({ allowed: true, retryAfter: null })), consumeEnabledLookup: vi.fn(async () => ({ allowed: true, retryAfter: null })), consumeCanary: vi.fn(async () => ({ allowed: true, retryAfter: null })) }) => ({ repository, resolver: { resolve: vi.fn(async () => ({ status: "safe" })) as never } });
function enabledRequest(config = enabled) { const csrf = issueAddressCsrf(config, now.getTime()); return new Request("https://example.test/api/address/resolve", { method: "POST", headers: { origin: "https://example.test", "sec-fetch-site": "same-origin", "content-type": "application/json", "x-address-edge": "203.0.113.1", cookie: csrf.cookie.split(";", 1)[0]!, "x-csrf-token": csrf.token }, body: JSON.stringify({ address: "123 Example Street" }) }); }
describe("address resolve route", () => {
  it("is disabled before body, runtime, or configuration extras", async () => { const make = vi.fn(); const h = createAddressHandler({ getConfig: () => ({ mode: "disabled" }), createRuntime: make }); const r = await h.POST(new Request("https://x/api/address/resolve", { method: "POST", duplex: "half", body: new ReadableStream({ pull() { throw new Error("read"); } }) } as RequestInit)); expect(r.status).toBe(503); expect(await r.json()).toEqual({ status: "disabled", errorCode: "LOOKUP_DISABLED" }); expect(make).not.toHaveBeenCalled(); expect(r.headers.get("cache-control")).toBe("no-store"); expect(r.headers.get("location")).toBeNull(); });
  it("only issues CSRF material in enabled mode and resolves after purpose-separated admission", async () => { const r = runtime(); const h = createAddressHandler({ getConfig: () => enabled, createRuntime: () => r, now: () => now }); const token = await h.GET(new Request("https://example.test/api/address/resolve")); expect(token.status).toBe(200); expect(token.headers.get("set-cookie")).toMatch(/^__Host-address_csrf=/); const out = await h.POST(enabledRequest()); expect(out.status).toBe(200); expect(out.headers.get("cache-control")).toBe("no-store"); expect(out.headers.get("content-type")).toMatch(/^application\/json/); expect(await out.text()).not.toMatch(/NaN|Infinity/); expect(r.repository.consumeMetadataAttempt).toHaveBeenCalledBefore(r.resolver.resolve as ReturnType<typeof vi.fn>); expect(r.repository.consumeEnabledLookup).toHaveBeenCalledOnce(); expect((r.repository.consumeMetadataAttempt.mock.calls as unknown as [Buffer][])[0]![0]).not.toEqual((r.repository.consumeEnabledLookup.mock.calls as unknown as [Buffer][])[0]![0]); });
  it.each([{ origin: "https://evil.test" }, { "content-encoding": "gzip" }, { "x-address-edge": "1.1.1.1, 2.2.2.2" }])("rejects enabled unsafe metadata", async (headers) => { const h = createAddressHandler({ getConfig: () => enabled, createRuntime: () => runtime(), now: () => now }); const req = enabledRequest(); Object.entries(headers).forEach(([k, v]) => req.headers.set(k, v)); const out = await h.POST(req); expect(out.status).toBe(403); expect(await out.text()).not.toContain("Example"); });
  it("caps Retry-After and rejects loose deployment allowlists", async () => { const r = runtime({ consumeMetadataAttempt: vi.fn(async () => ({ allowed: false, retryAfter: 999999 })), consumeEnabledLookup: vi.fn(), consumeCanary: vi.fn() } as never); const out = await createAddressHandler({ getConfig: () => enabled, createRuntime: () => r, now: () => now }).POST(enabledRequest()); expect(out.headers.get("retry-after")).toBe("86400"); expect(() => parseAddressConfig({ ...base, ADDRESS_LOOKUP_MODE: "enabled", ADDRESS_DEPLOYMENT_ALLOWLIST: "deploy,,other", ADDRESS_PUBLIC_ORIGIN: "https://example.test", ADDRESS_TRUSTED_IP_HEADER: "x-address-edge", ADDRESS_CSRF_SECRET: "c".repeat(32), ADDRESS_SUBJECT_HMAC_SECRET: "s".repeat(32), ADDRESS_SUBJECT_HMAC_GENERATION: "one" })).toThrow(); });
  it("requires an authenticated canary body and consumes its nonce", async () => { const bytes = Buffer.from(JSON.stringify({ address: "123 Example Street" })); const sha = createHash("sha256").update(bytes).digest("hex"); const c = parseAddressConfig({ ...base, ADDRESS_LOOKUP_MODE: "canary", ADDRESS_CANARY_KEY_ID: "key", ADDRESS_CANARY_HMAC_SECRET: "k".repeat(32), ADDRESS_CANARY_NOT_BEFORE: String(Math.floor(now.getTime() / 1000) - 1), ADDRESS_CANARY_UNTIL: String(Math.floor(now.getTime() / 1000) + 60), ADDRESS_CANARY_ALLOWLIST: JSON.stringify({ vector: sha }) }); const ts = String(Math.floor(now.getTime() / 1000)); const nonce = "n".repeat(43); const signed = `POST\n/api/address/resolve\n${sha}\nvector\n${c.approvalRevision}\n${ts}\n${nonce}`; const auth = `v1.key.${ts}.${nonce}.vector.${sha}.${createHmac("sha256", "k".repeat(32)).update(signed).digest("base64url")}`; const r = runtime(); const out = await createAddressHandler({ getConfig: () => c, createRuntime: () => r, now: () => now }).POST(new Request("https://x/api/address/resolve", { method: "POST", headers: { "content-type": "application/json", authorization: auth }, body: bytes })); expect(out.status).toBe(200); expect(r.repository.consumeCanary).toHaveBeenCalledOnce(); expect(r.repository.consumeCanary).toHaveBeenCalledWith(expect.objectContaining({ expiresAt: new Date(now.getTime() + 600_000) }), expect.any(AbortSignal)); });
  it("rejects oversized, invalid UTF-8, and deadline-expired bodies", async () => { const h = createAddressHandler({ getConfig: () => enabled, createRuntime: () => runtime(), now: () => now }); const large = enabledRequest(); large.headers.set("content-length", "999999"); const tooLarge = new Request(large, { body: "x".repeat(1025), duplex: "half" } as RequestInit); expect((await h.POST(tooLarge)).status).toBe(413); const invalid = new Request(enabledRequest(), { body: new Uint8Array([0xff]), duplex: "half" } as RequestInit); expect((await h.POST(invalid)).status).toBe(400); vi.useFakeTimers(); try { const waiting = new Request(enabledRequest(), { body: new ReadableStream<Uint8Array>({ pull() {} }), duplex: "half" } as RequestInit); const response = h.POST(waiting); await vi.advanceTimersByTimeAsync(5_000); expect((await response).status).toBe(400); } finally { vi.useRealTimers(); } });
  it("propagates caller abort to admission", async () => { const r = runtime(); const controller = new AbortController(); const request = new Request(enabledRequest(), { signal: controller.signal }); controller.abort(); const out = await createAddressHandler({ getConfig: () => enabled, createRuntime: () => r, now: () => now }).POST(request); expect(out.status).toBe(400); expect(r.repository.consumeMetadataAttempt).toHaveBeenLastCalledWith(expect.any(Buffer), request.signal); expect(request.signal.aborted).toBe(true); expect(r.repository.consumeEnabledLookup).not.toHaveBeenCalled(); });
  it("fails closed when configuration is unavailable", async () => { const make = vi.fn(); const out = await createAddressHandler({ getConfig: () => { throw new Error("kill switch"); }, createRuntime: make }).POST(enabledRequest()); expect(out.status).toBe(503); expect(await out.json()).toEqual({ status: "unavailable" }); expect(make).not.toHaveBeenCalled(); });
  it("treats a repeated canary nonce as a repository-enforced replay", async () => { const bytes = Buffer.from(JSON.stringify({ address: "123 Example Street" })); const sha = createHash("sha256").update(bytes).digest("hex"); const c = parseAddressConfig({ ...base, ADDRESS_LOOKUP_MODE: "canary", ADDRESS_CANARY_KEY_ID: "key", ADDRESS_CANARY_HMAC_SECRET: "k".repeat(32), ADDRESS_CANARY_NOT_BEFORE: String(Math.floor(now.getTime() / 1000) - 1), ADDRESS_CANARY_UNTIL: String(Math.floor(now.getTime() / 1000) + 60), ADDRESS_CANARY_ALLOWLIST: JSON.stringify({ vector: sha }) }); const ts = String(Math.floor(now.getTime() / 1000)), nonce = "n".repeat(43), signed = `POST\n/api/address/resolve\n${sha}\nvector\n${c.approvalRevision}\n${ts}\n${nonce}`, auth = `v1.key.${ts}.${nonce}.vector.${sha}.${createHmac("sha256", "k".repeat(32)).update(signed).digest("base64url")}`; const r = runtime({ consumeMetadataAttempt: vi.fn(), consumeEnabledLookup: vi.fn(), consumeCanary: vi.fn().mockResolvedValueOnce({ allowed: true, retryAfter: null }).mockResolvedValueOnce({ allowed: false, retryAfter: 12 }) } as never); const h = createAddressHandler({ getConfig: () => c, createRuntime: () => r, now: () => now }); const request = () => new Request("https://x/api/address/resolve", { method: "POST", headers: { "content-type": "application/json", authorization: auth }, body: bytes }); expect((await h.POST(request())).status).toBe(200); const replay = await h.POST(request()); expect(replay.status).toBe(429); expect(replay.headers.get("retry-after")).toBe("12"); expect(r.resolver.resolve).toHaveBeenCalledOnce(); });
  it("rejects non-POST methods without issuing CSRF material", async () => { const h = createAddressHandler({ getConfig: () => enabled }); for (const method of ["HEAD", "OPTIONS", "PUT", "PATCH", "DELETE"] as const) { const response = await h[method](); expect(response.status).toBe(405); expect(response.headers.get("cache-control")).toBe("no-store"); expect(response.headers.get("location")).toBeNull(); expect(response.headers.get("set-cookie")).toBeNull(); } });
  it("rejects duplicate canary vectors", () => { const sha = "a".repeat(64); expect(() => parseAddressConfig({ ...base, ADDRESS_LOOKUP_MODE: "canary", ADDRESS_CANARY_KEY_ID: "key", ADDRESS_CANARY_HMAC_SECRET: "k".repeat(32), ADDRESS_CANARY_NOT_BEFORE: "1", ADDRESS_CANARY_UNTIL: "2", ADDRESS_CANARY_ALLOWLIST: JSON.stringify([{ id: "vector", sha256: sha }, { id: "vector", sha256: sha }]) })).toThrow(); });
});
