import { describe, expect, it, vi } from "vitest";
import { CallerAbortError, CensusGeocoderAdapter } from "./census-geocoder";
const meta = { id: "4", name: "Public_AR_Current" }; const vintage = { id: "4", name: "Current_Current" };
const payload = (matches: unknown[]) => ({ result: { input: { benchmark: { id: 4, benchmarkName: meta.name }, vintage: { id: 4, vintageName: vintage.name } }, addressMatches: matches, harmless: true } });
const response = (body: unknown, ok = true) => ({ ok, redirected: false, url: "https://geocoding.geo.census.gov/geocoder/geographies/onelineaddress", json: async () => body }) as Response;
describe("CensusGeocoderAdapter", () => {
  const options = (fetch: typeof globalThis.fetch) => ({ benchmark: meta, vintage, congressionalLayerName: "119th Congressional Districts", timeoutMs: 1000, fetch });
  it("uses the fixed, encoded Census request and discards unneeded fields", async () => { const fetcher = vi.fn().mockResolvedValue(response(payload([{ coordinates: { x: 1, y: 2 }, geographies: { States: [{ GEOID: "02" }], "119th Congressional Districts": [{ GEOID: "0200" }] }, matchedAddress: "discard" }]))); const adapter = new CensusGeocoderAdapter(options(fetcher)); expect(await adapter.geocode("Fictional Plaza & 7")).toEqual({ benchmark: meta, vintage, candidates: [{ longitude: 1, latitude: 2, stateGeoid: "02", congressionalDistrictGeoid: "0200" }] }); const [url, init] = fetcher.mock.calls[0]!; expect(fetcher).toHaveBeenCalledTimes(1); expect(url.toString()).toContain("address=Fictional+Plaza+%26+7"); expect(url.searchParams.get("benchmark")).toBe("Public_AR_Current"); expect(url.searchParams.get("vintage")).toBe("Current_Current"); expect(url.searchParams.get("format")).toBe("json"); expect(url.searchParams.get("layers")).toBe("States,119th Congressional Districts"); expect(init).toMatchObject({ method: "GET", redirect: "error", cache: "no-store" }); });
  it("returns no/multiple candidates and null absent geography IDs", async () => { const fetcher = vi.fn().mockResolvedValue(response(payload([]))); const adapter = new CensusGeocoderAdapter({ benchmark: meta, vintage, congressionalLayerName: "CD", timeoutMs: 1000, fetch: fetcher }); expect((await adapter.geocode("Fictional Plaza 7")).candidates).toEqual([]); fetcher.mockResolvedValueOnce(response(payload([{ coordinates: { x: 1, y: 2 } }, { coordinates: { x: 2, y: 3 } }]))); expect((await adapter.geocode("Fictional Plaza 7")).candidates).toHaveLength(2); });
  it("keeps malformed, response protocol, metadata, and upstream errors sanitized", async () => { for (const value of [response({ secret: "Fictional Plaza 7 upstream body" }), { ...response(payload([])), redirected: true }, { ...response(payload([])), url: "https://evil.example/geocoder/geographies/onelineaddress" }, { ...response(payload([])), url: "https://geocoding.geo.census.gov/wrong" }, response(payload([]), false), response({ result: { input: { benchmark: { id: 99, benchmarkName: meta.name }, vintage: { id: 4, vintageName: vintage.name } }, addressMatches: [] } })]) { const adapter = new CensusGeocoderAdapter(options(vi.fn().mockResolvedValue(value))); await expect(adapter.geocode("Fictional Plaza 7")).rejects.not.toThrow(/Fictional|upstream body/); } });
  it("rejects invalid coordinates at the response boundary", async () => { for (const coordinates of [{ x: Infinity, y: 1 }, { x: 181, y: 1 }, { x: 1, y: -91 }]) { const adapter = new CensusGeocoderAdapter(options(vi.fn().mockResolvedValue(response(payload([{ coordinates }])) ) as typeof fetch)); await expect(adapter.geocode("Fictional Plaza 7")).rejects.toThrow("protocol failure"); } });
  it("passes an abort signal to fetch, sanitizes timeouts, and rethrows caller cancellation", async () => { const timeoutFetch = vi.fn(async (_url: RequestInfo | URL, init?: RequestInit) => { expect(init?.signal).toBeInstanceOf(AbortSignal); return await new Promise<Response>((_resolve, reject) => init!.signal!.addEventListener("abort", () => reject(new Error("Fictional Plaza 7")), { once: true })); }); const adapter = new CensusGeocoderAdapter({ ...options(timeoutFetch as typeof fetch), timeoutMs: 1 }); await expect(adapter.geocode("Fictional Plaza 7")).rejects.toThrow("Census geocoder request failed"); const controller = new AbortController(); controller.abort(); const callerFetch = vi.fn(); await expect(new CensusGeocoderAdapter(options(callerFetch as typeof fetch)).geocode("Fictional Plaza 7", controller.signal)).rejects.toBeInstanceOf(CallerAbortError); expect(callerFetch).not.toHaveBeenCalled(); });
});
