import { describe, expect, it, vi } from "vitest";
import { addressInputSchema } from "@/domain/address";
import { CallerAbortError, type CensusGeocodeResult } from "./census-geocoder";
import { PostgresAddressResolver, PostgresSeatLocator, type LocatorResult, type SeatLocator } from "./postgres-resolver";

const input = { address: "Fictional Plaza 7" };
const coded = (candidates: CensusGeocodeResult["candidates"]): CensusGeocodeResult => ({ benchmark: { id: "4", name: "Public_AR_Current" }, vintage: { id: "4", name: "Current_Current" }, candidates });
const candidate = { longitude: -150, latitude: 60, stateGeoid: "02", congressionalDistrictGeoid: "0200" };
const matched: LocatorResult = { kind: "matched", houseSeat: { officeTermId: "term_house", seatCycleId: "seat_house", geographyVersionId: "geo_house" }, senateSeats: [{ senateClass: 2, officeTermId: "term_senate_2", seatCycleId: "seat_senate_2" }, { senateClass: 3, officeTermId: "term_senate_3", seatCycleId: "seat_senate_3" }] };
function setup(options: { enabled?: boolean; allowed?: boolean; preflight?: boolean | Error; geocode?: CensusGeocodeResult | Error; locate?: LocatorResult | Error } = {}) {
  const locator: SeatLocator = { preflight: vi.fn(async () => { if (options.preflight instanceof Error) throw options.preflight; return options.preflight ?? true; }), locate: vi.fn(async () => { if (options.locate instanceof Error) throw options.locate; return options.locate ?? matched; }) };
  const geocoder = { geocode: vi.fn(async () => { if (options.geocode instanceof Error) throw options.geocode; return options.geocode ?? coded([candidate]); }) };
  const limiter = { tryAcquire: vi.fn(() => options.allowed ?? true) };
  return { resolver: new PostgresAddressResolver({ releaseId: "rel_1", productVintage: "2025", enabled: options.enabled ?? true }, geocoder, locator, limiter), locator, geocoder, limiter };
}
describe("PostgresAddressResolver", () => {
  it("parses input before side effects", async () => { const { resolver, limiter } = setup(); expect(() => addressInputSchema.parse({ address: "short" })).toThrow(); await expect(resolver.resolve({ address: "short" } as never)).rejects.toThrow(); expect(limiter.tryAcquire).not.toHaveBeenCalled(); });
  it("short-circuits disabled and rate limited requests", async () => { const disabled = setup({ enabled: false }); expect((await disabled.resolver.resolve(input)).status).toBe("disabled"); expect(disabled.limiter.tryAcquire).not.toHaveBeenCalled(); expect(disabled.locator.preflight).not.toHaveBeenCalled(); expect(disabled.geocoder.geocode).not.toHaveBeenCalled(); const limited = setup({ allowed: false }); expect((await limited.resolver.resolve(input)).status).toBe("rate_limited"); expect(limited.locator.preflight).not.toHaveBeenCalled(); expect(limited.geocoder.geocode).not.toHaveBeenCalled(); });
  it("handles preflight and geocoder failures without sending an address before preflight", async () => { for (const preflight of [false, new Error("db")]) { const s = setup({ preflight }); expect((await s.resolver.resolve(input)).status).toBe("resolver_failure"); expect(s.geocoder.geocode).not.toHaveBeenCalled(); } const s = setup({ geocode: new Error("upstream") }); expect((await s.resolver.resolve(input)).status).toBe("upstream_failure"); });
  it("maps zero, multiple, and malformed unique candidates", async () => { for (const [candidates, status] of [[[], "no_match"], [[candidate, candidate], "ambiguous"], [[{ ...candidate, stateGeoid: null }], "upstream_failure"]] as const) expect((await setup({ geocode: coded([...candidates]) }).resolver.resolve(input)).status).toBe(status); });
  it("forwards exact locator arguments and maps every locator branch", async () => { for (const [locate, status] of [[matched, "matched"], [{ kind: "unsupported" }, "unsupported_prototype_coverage"], [{ kind: "vintage_mismatch" }, "vintage_mismatch"], [{ kind: "geography_ambiguous" }, "geography_ambiguous"], [{ kind: "resolver_failure" }, "resolver_failure"], [new Error("db"), "resolver_failure"]] as const) { const s = setup({ locate }); const result = await s.resolver.resolve(input); expect(result.status).toBe(status); expect(s.locator.locate).toHaveBeenCalledWith("rel_1", "2025", "02", "0200", -150, 60, undefined); if (result.status === "matched") expect(result).toMatchObject({ houseSeat: matched.houseSeat, senateSeats: matched.senateSeats }); expect(JSON.stringify(result)).not.toMatch(/Fictional|longitude|latitude|matchedAddress/i); } });
  it("fails closed for inconsistent Census geography identity", async () => { const s = setup({ geocode: coded([{ ...candidate, congressionalDistrictGeoid: "0102" }]) }); await expect(s.resolver.resolve(input)).resolves.toMatchObject({ status: "vintage_mismatch" }); expect(s.locator.locate).not.toHaveBeenCalled(); });
  it("rejects caller aborts before and during resolver stages", async () => { const aborted = new AbortController(); aborted.abort(); const early = setup(); await expect(early.resolver.resolve(input, aborted.signal)).rejects.toBeInstanceOf(CallerAbortError); expect(early.limiter.tryAcquire).not.toHaveBeenCalled(); let release!: () => void; const waiting = new Promise<void>((resolve) => { release = resolve; }); const s = setup(); s.locator.preflight = vi.fn(async (_release, _vintage, signal) => { await waiting; if (signal?.aborted) throw new CallerAbortError(); return true; }); const controller = new AbortController(); const pending = s.resolver.resolve(input, controller.signal); await Promise.resolve(); controller.abort(); release(); await expect(pending).rejects.toBeInstanceOf(CallerAbortError); expect(s.geocoder.geocode).not.toHaveBeenCalled(); });
  it("waits for one deferred cancellation before releasing the owned client", async () => { let rejectRead!: (error: Error) => void; let readStarted!: () => void; const started = new Promise<void>((resolve) => { readStarted = resolve; }); let cancellationStarted!: () => void; const cancellationStartedPromise = new Promise<void>((resolve) => { cancellationStarted = resolve; }); let settleCancellation!: () => void; const cancellation = new Promise<void>((resolve) => { settleCancellation = resolve; }); const client = { processID: 42, release: vi.fn(), query: vi.fn((sql: string) => { if (sql.startsWith("SELECT EXISTS")) { readStarted(); return new Promise((_resolve, reject) => { rejectRead = reject; }); } return Promise.resolve({ rows: [{ ok: true }] }); }) }; const pool = { connect: vi.fn().mockResolvedValue(client) }; const cancelBackend = vi.fn(async () => { cancellationStarted(); await cancellation; });
    expect(() => new PostgresSeatLocator(pool as never, 0)).toThrow("Invalid statement timeout"); const locator = new PostgresSeatLocator(pool as never, 123, cancelBackend); const already = new AbortController(); already.abort(); await expect(locator.preflight("rel", "v", already.signal)).rejects.toBeInstanceOf(CallerAbortError); expect(pool.connect).not.toHaveBeenCalled(); const controller = new AbortController(); const pending = locator.preflight("rel", "v", controller.signal); await started; controller.abort(); controller.abort(); await cancellationStartedPromise; rejectRead(new Error("query canceled")); await Promise.resolve(); expect(cancelBackend).toHaveBeenCalledOnce(); expect(cancelBackend).toHaveBeenCalledWith(42); expect(client.release).not.toHaveBeenCalled(); expect(pool.connect).toHaveBeenCalledOnce(); settleCancellation(); await expect(pending).rejects.toBeInstanceOf(CallerAbortError); expect(client.query).toHaveBeenCalledWith("SELECT set_config('statement_timeout',$1,true)", ["123"]); expect(client.release).toHaveBeenCalledOnce(); });
  it("rejects an already-aborted or in-flight locate", async () => { const aborted = new AbortController(); aborted.abort(); const idlePool = { connect: vi.fn() }; await expect(new PostgresSeatLocator(idlePool as never).locate("r", "v", "02", "0200", 1, 2, aborted.signal)).rejects.toBeInstanceOf(CallerAbortError); expect(idlePool.connect).not.toHaveBeenCalled(); let rejectRead!: (error: Error) => void; let started!: () => void; const startedRead = new Promise<void>((resolve) => { started = resolve; }); let cancelled!: () => void; const didCancel = new Promise<void>((resolve) => { cancelled = resolve; }); const client = { processID: 43, release: vi.fn(), query: vi.fn((sql: string) => { if (sql.startsWith("WITH p")) { started(); return new Promise((_resolve, reject) => { rejectRead = reject; }); } return Promise.resolve({ rows: [] }); }) }; const pool = { connect: vi.fn().mockResolvedValue(client) }; const cancelBackend = vi.fn(async () => { cancelled(); }); const controller = new AbortController(); const pending = new PostgresSeatLocator(pool as never, 5_000, cancelBackend).locate("r", "v", "02", "0200", 1, 2, controller.signal); await startedRead; controller.abort(); await didCancel; rejectRead(new Error("canceled")); await expect(pending).rejects.toBeInstanceOf(CallerAbortError); expect(cancelBackend).toHaveBeenCalledWith(43); });
});
