import { createHash, createHmac, randomBytes, timingSafeEqual } from "node:crypto";
import { isIP } from "node:net";
import type { AddressConfig } from "./config";
const b64 = /^[A-Za-z0-9_-]{43}$/; const hex = /^[a-f0-9]{64}$/;
const equal = (a: Buffer, b: Buffer) => a.length === b.length && timingSafeEqual(a, b);
export const digest = (body: Uint8Array) => createHash("sha256").update(body).digest("hex");
export function canonicalIp(value: string | null): string | undefined { if (!value || value.trim() !== value || value.includes(",") || !isIP(value)) return undefined; try { return new URL(isIP(value) === 6 ? `http://[${value}]/` : `http://${value}/`).hostname.replace(/^\[|\]$/g, ""); } catch { return undefined; } }
export function issueAddressCsrf(config: Pick<AddressConfig, "csrfSecret">, now = Date.now()) { const nonce = randomBytes(32).toString("base64url"); const token = `${now}.${nonce}.${createHmac("sha256", config.csrfSecret!).update(`address-csrf:${now}:${nonce}`).digest("base64url")}`; return { token, cookie: `__Host-address_csrf=${nonce}; Max-Age=1800; Path=/; Secure; HttpOnly; SameSite=Strict` }; }
export function verifyAddressCsrf(config: Pick<AddressConfig, "csrfSecret">, cookie: string | null, token: string | null, now = Date.now()): boolean { const matches = cookie?.match(/(?:^|;\s*)__Host-address_csrf=([A-Za-z0-9_-]{43})(?=;|$)/g); const nonce = matches?.length === 1 ? matches[0]!.split("=")[1] : undefined; const p = token?.split("."); if (!nonce || !p || p.length !== 3 || !/^\d+$/.test(p[0]!) || !b64.test(p[1]!) || !b64.test(p[2]!) || !equal(Buffer.from(nonce), Buffer.from(p[1]!))) return false; const issued = Number(p[0]); return Number.isSafeInteger(issued) && issued <= now && now - issued <= 1_800_000 && equal(Buffer.from(p[2]!, "base64url"), createHmac("sha256", config.csrfSecret!).update(`address-csrf:${issued}:${nonce}`).digest()); }
export function verifyCanary(config: AddressConfig, authorization: string | null, bodySha: string | undefined, now: number): { keyId: string; nonceHash: Buffer; timestamp: Date } | undefined { const c = config.canary; const p = authorization?.split("."); if (!c || now < c.notBefore || now > c.until || !p || p.length !== 7 || p[0] !== "v1" || p[1] !== c.keyId || !/^\d+$/.test(p[2]!) || !b64.test(p[3]!) || !/^[A-Za-z0-9_-]{1,128}$/.test(p[4]!) || !hex.test(p[5]!) || !/^[A-Za-z0-9_-]{43}$/.test(p[6]!)) return undefined; const ts = Number(p[2]); if (!Number.isSafeInteger(ts) || ts < c.notBefore || ts > c.until || now - ts > 300 || ts - now > 30 || !bodySha || bodySha !== p[5] || c.vectors.get(p[4]) !== bodySha) return undefined; const signed = `POST\n/api/address/resolve\n${p[5]}\n${p[4]}\n${config.approvalRevision}\n${p[2]}\n${p[3]}`; if (!equal(Buffer.from(p[6]!, "base64url"), createHmac("sha256", c.secret).update(signed).digest())) return undefined; return { keyId: p[1]!, nonceHash: createHash("sha256").update(p[3]!).digest(), timestamp: new Date(ts * 1000) }; }
/** Cheap pre-body gate: digest/signature verification intentionally happens after bounded read. */
export function canaryAuthorizationLooksValid(config: AddressConfig, authorization: string | null, now: number): boolean { const c = config.canary; const p = authorization?.split("."); if (!c || now < c.notBefore || now > c.until || !p || p.length !== 7 || p[0] !== "v1" || p[1] !== c.keyId || !/^\d+$/.test(p[2]!) || !b64.test(p[3]!) || !/^[A-Za-z0-9_-]{1,128}$/.test(p[4]!) || !hex.test(p[5]!) || !/^[A-Za-z0-9_-]{43}$/.test(p[6]!)) return false; const ts = Number(p[2]); return Number.isSafeInteger(ts) && ts >= c.notBefore && ts <= c.until && now - ts <= 300 && ts - now <= 30 && c.vectors.get(p[4]) === p[5]; }
