import { createHash } from "node:crypto";
import { readFileSync } from "node:fs";
import { join } from "node:path";
import { validateMississippiPrimaryResults } from "./house-primary-mississippi-results";
import { type HousePrimaryCoverageLedgerV5, type HousePrimaryProjectionV5, validateHousePrimaryProjectionV5 } from "./house-primary-projection-v5";

type ParentObservation = HousePrimaryProjectionV5["observations"][number];
export type HousePrimaryV6Observation = Omit<ParentObservation, "resultAuthorityStatus"> & Readonly<{ resultAuthorityStatus: ParentObservation["resultAuthorityStatus"] | "official_statewide_democratic_recap_pdf_retained_no_separate_certification_instrument" }>;
export interface HousePrimaryProjectionV6 { readonly schema: "rapid-house-primary-projection-v6"; readonly version: 6; readonly parentProjectionPackageSha256: string; readonly mississippiResultsPackageSha256: string; readonly observations: readonly HousePrimaryV6Observation[]; readonly observationSetSha256: string; readonly coverageRows: HousePrimaryProjectionV5["coverageRows"]; readonly coverageSetSha256: string; readonly summary: Readonly<{ stateCycles: 48; districtObservations: 78; reportedContests: 15; sourceAbsent: 1; processedDistricts: 16; candidateRows: 34; retainedCandidateVotes: 1071972; scoreEligibleDistricts: 0 }>; readonly packageSha256: string; }
export interface HousePrimaryCoverageLedgerV6 extends Omit<HousePrimaryCoverageLedgerV5, "schema" | "version" | "projectionSha256"> { readonly schema: "rapid-house-primary-coverage-ledger-v6"; readonly version: 6; readonly projectionSha256: string; }
const byteCompare = (left: string, right: string) => left < right ? -1 : left > right ? 1 : 0;
const canonical = (value: unknown): string => value === null || typeof value !== "object" ? JSON.stringify(value) : Array.isArray(value) ? `[${value.map(canonical).join(",")}]` : `{${Object.keys(value as object).sort(byteCompare).map((key) => `${JSON.stringify(key)}:${canonical((value as Record<string, unknown>)[key])}`).join(",")}}`;
const hash = (domain: string, value: unknown) => createHash("sha256").update(`${domain}\0${canonical(value)}`).digest("hex");
const exact = (left: unknown, right: unknown) => canonical(left) === canonical(right);
export function buildHousePrimaryProjectionV6(root = process.cwd()): HousePrimaryProjectionV6 {
  const parent = validateHousePrimaryProjectionV5(JSON.parse(readFileSync(join(root, "data/metadata/rapid-house-primary-projection-v5.json"), "utf8")), root), mississippi = validateMississippiPrimaryResults(JSON.parse(readFileSync(join(root, "data/metadata/rapid-house-primary-mississippi-results-v1.json"), "utf8")), root), result = mississippi.results[0];
  const observations: HousePrimaryV6Observation[] = parent.observations.map((row) => { if (row.observationId !== "ms:primary:2024:02") return row; if (row.parseStatus !== "ready_unparsed" || !exact(row.sourceLockIds, ["ms-2024-primary-results"])) throw new Error("HOUSE_PRIMARY_V6_MISSISSIPPI_PARENT_INVALID"); return { ...row, parseStatus: "parsed", missingReason: null, sourceLockIds: result.sourceLockIds, sourceContestId: result.resultId, candidateCount: 1, votes: result.totalVotes, sourceWinnerStatus: result.sourceWinnerStatus, resultAuthorityStatus: result.resultAuthorityStatus }; });
  const coverageRows = parent.coverageRows.map((row) => row.stateCode === "MS" && row.cycleYear === 2024 ? { ...row, parsedDistrictCount: 1, sourceAbsentDistrictCount: 0, status: "parsed" as const, missingByReason: [], artifactLockIds: [...result.sourceLockIds] } : row);
  const reportedContests = observations.filter((row) => row.parseStatus === "parsed").length, sourceAbsent = observations.filter((row) => row.parseStatus === "source_absent").length, retainedCandidateVotes = observations.reduce((sum, row) => sum + (row.votes ?? 0), 0);
  if (observations.length !== 78 || coverageRows.length !== 48 || reportedContests !== 15 || sourceAbsent !== 1 || retainedCandidateVotes !== 1071972 || observations.some((row) => row.scoreEligible || row.winner !== null || row.identity !== null)) throw new Error("HOUSE_PRIMARY_V6_CLOSURE_INVALID");
  const observationSetSha256 = hash("dsa-seats:rapid-house-primary-v6-observation-set:v1", observations), coverageSetSha256 = hash("dsa-seats:rapid-house-primary-v6-coverage-set:v1", coverageRows), summary = { stateCycles: 48 as const, districtObservations: 78 as const, reportedContests: 15 as const, sourceAbsent: 1 as const, processedDistricts: 16 as const, candidateRows: 34 as const, retainedCandidateVotes: 1071972 as const, scoreEligibleDistricts: 0 as const }, unsigned = { schema: "rapid-house-primary-projection-v6" as const, version: 6 as const, parentProjectionPackageSha256: parent.packageSha256, mississippiResultsPackageSha256: mississippi.packageSha256, observations, observationSetSha256, coverageRows, coverageSetSha256, summary };
  return { ...unsigned, packageSha256: hash("dsa-seats:rapid-house-primary-v6-package:v1", unsigned) };
}
export function validateHousePrimaryProjectionV6(value: unknown, root = process.cwd()): HousePrimaryProjectionV6 { const expected = buildHousePrimaryProjectionV6(root); if (!exact(value, expected)) throw new Error("HOUSE_PRIMARY_PROJECTION_V6_INVALID"); return value as HousePrimaryProjectionV6; }
export function buildHousePrimaryCoverageLedgerV6(projection = buildHousePrimaryProjectionV6()): HousePrimaryCoverageLedgerV6 { const rowSetSha256 = hash("dsa-seats:rapid-house-primary-v6-ledger-row-set:v1", projection.coverageRows), unsigned = { schema: "rapid-house-primary-coverage-ledger-v6" as const, version: 6 as const, projectionSha256: projection.packageSha256, rows: projection.coverageRows, rowSetSha256 }; return { ...unsigned, packageSha256: hash("dsa-seats:rapid-house-primary-v6-ledger-package:v1", unsigned) }; }
export function validateHousePrimaryCoverageLedgerV6(value: unknown, projection = buildHousePrimaryProjectionV6()): HousePrimaryCoverageLedgerV6 { const expected = buildHousePrimaryCoverageLedgerV6(projection); if (!exact(value, expected)) throw new Error("HOUSE_PRIMARY_COVERAGE_LEDGER_V6_INVALID"); return value as HousePrimaryCoverageLedgerV6; }
