import { createHash } from "node:crypto";
import { readFileSync } from "node:fs";
import { join } from "node:path";
import { type HousePrimaryCoverageLedgerV8, type HousePrimaryProjectionV8, validateHousePrimaryProjectionV8 } from "./house-primary-projection-v8";
import { validateVermontPrimaryResults } from "./house-primary-vermont-results";

type ParentObservation = HousePrimaryProjectionV8["observations"][number];
export type HousePrimaryV9Observation = Omit<ParentObservation, "resultAuthorityStatus"> & Readonly<{ resultAuthorityStatus: ParentObservation["resultAuthorityStatus"] | "official_secretary_canvass_report_retained" }>;
export interface HousePrimaryProjectionV9 { readonly schema: "rapid-house-primary-projection-v9"; readonly version: 9; readonly parentProjectionPackageSha256: string; readonly vermontResultsPackageSha256: string; readonly observations: readonly HousePrimaryV9Observation[]; readonly observationSetSha256: string; readonly coverageRows: HousePrimaryProjectionV8["coverageRows"]; readonly coverageSetSha256: string; readonly summary: Readonly<{ stateCycles: 48; districtObservations: 78; reportedContests: 24; sourceAbsent: 2; processedDistricts: 26; candidateRows: 63; retainedCandidateVotes: 1509803; sourceMarkedWinnerContests: 5; scoreEligibleDistricts: 0 }>; readonly packageSha256: string; }
export interface HousePrimaryCoverageLedgerV9 extends Omit<HousePrimaryCoverageLedgerV8, "schema" | "version" | "projectionSha256"> { readonly schema: "rapid-house-primary-coverage-ledger-v9"; readonly version: 9; readonly projectionSha256: string; }
const byteCompare = (left: string, right: string) => left < right ? -1 : left > right ? 1 : 0;
const canonical = (value: unknown): string => value === null || typeof value !== "object" ? JSON.stringify(value) : Array.isArray(value) ? `[${value.map(canonical).join(",")}]` : `{${Object.keys(value as object).sort(byteCompare).map((key) => `${JSON.stringify(key)}:${canonical((value as Record<string, unknown>)[key])}`).join(",")}}`;
const hash = (domain: string, value: unknown) => createHash("sha256").update(`${domain}\0${canonical(value)}`).digest("hex");
const exact = (left: unknown, right: unknown) => canonical(left) === canonical(right);

export function buildHousePrimaryProjectionV9(root = process.cwd()): HousePrimaryProjectionV9 {
  const parent = validateHousePrimaryProjectionV8(JSON.parse(readFileSync(join(root, "data/metadata/rapid-house-primary-projection-v8.json"), "utf8")), root), vermont = validateVermontPrimaryResults(JSON.parse(readFileSync(join(root, "data/metadata/rapid-house-primary-vermont-results-v1.json"), "utf8")), root), byObservation = new Map(vermont.results.map((row) => [`vt:primary:${row.cycleYear}:al`, row]));
  const observations: HousePrimaryV9Observation[] = parent.observations.map((row) => {
    if (row.stateCode !== "VT" || row.cycleYear === 2026) return row;
    const result = byObservation.get(row.observationId); if (!result) throw new Error("HOUSE_PRIMARY_V9_VERMONT_RESULT_MISSING");
    return { ...row, parseStatus: "parsed", missingReason: null, sourceLockIds: result.sourceLockIds, sourceContestId: result.resultId, candidateCount: result.sourceCandidateNames.length, votes: result.candidateVoteSum, sourceWinnerStatus: result.sourceWinnerStatus, resultAuthorityStatus: result.resultAuthorityStatus };
  });
  const coverageRows = parent.coverageRows.map((row) => row.stateCode !== "VT" || row.cycleYear === 2026 ? row : { ...row, retainedArtifactCount: 2, parsedDistrictCount: 1, sourceAbsentDistrictCount: 0, status: "parsed" as const, missingByReason: [], artifactLockIds: [`vt-${row.cycleYear}-primary-official-canvass`, `vt-${row.cycleYear}-primary-official-canvass-text`] });
  const reportedContests = observations.filter((row) => row.parseStatus === "parsed").length, sourceAbsent = observations.filter((row) => row.parseStatus === "source_absent").length, retainedCandidateVotes = observations.reduce((sum, row) => sum + (row.votes ?? 0), 0), sourceMarkedWinnerContests = observations.filter((row) => row.sourceWinnerStatus === "marked_by_source").length;
  if (observations.length !== 78 || coverageRows.length !== 48 || reportedContests !== 24 || sourceAbsent !== 2 || retainedCandidateVotes !== 1509803 || sourceMarkedWinnerContests !== 5 || observations.some((row) => row.scoreEligible || row.winner !== null || row.identity !== null)) throw new Error("HOUSE_PRIMARY_V9_CLOSURE_INVALID");
  const observationSetSha256 = hash("dsa-seats:rapid-house-primary-v9-observation-set:v1", observations), coverageSetSha256 = hash("dsa-seats:rapid-house-primary-v9-coverage-set:v1", coverageRows), summary = { stateCycles: 48 as const, districtObservations: 78 as const, reportedContests: 24 as const, sourceAbsent: 2 as const, processedDistricts: 26 as const, candidateRows: 63 as const, retainedCandidateVotes: 1509803 as const, sourceMarkedWinnerContests: 5 as const, scoreEligibleDistricts: 0 as const }, unsigned = { schema: "rapid-house-primary-projection-v9" as const, version: 9 as const, parentProjectionPackageSha256: parent.packageSha256, vermontResultsPackageSha256: vermont.packageSha256, observations, observationSetSha256, coverageRows, coverageSetSha256, summary };
  return { ...unsigned, packageSha256: hash("dsa-seats:rapid-house-primary-v9-package:v1", unsigned) };
}
export function validateHousePrimaryProjectionV9(value: unknown, root = process.cwd()): HousePrimaryProjectionV9 { const expected = buildHousePrimaryProjectionV9(root); if (!exact(value, expected)) throw new Error("HOUSE_PRIMARY_PROJECTION_V9_INVALID"); return value as HousePrimaryProjectionV9; }
export function buildHousePrimaryCoverageLedgerV9(projection = buildHousePrimaryProjectionV9()): HousePrimaryCoverageLedgerV9 { const rowSetSha256 = hash("dsa-seats:rapid-house-primary-v9-ledger-row-set:v1", projection.coverageRows), unsigned = { schema: "rapid-house-primary-coverage-ledger-v9" as const, version: 9 as const, projectionSha256: projection.packageSha256, rows: projection.coverageRows, rowSetSha256 }; return { ...unsigned, packageSha256: hash("dsa-seats:rapid-house-primary-v9-ledger-package:v1", unsigned) }; }
export function validateHousePrimaryCoverageLedgerV9(value: unknown, projection = buildHousePrimaryProjectionV9()): HousePrimaryCoverageLedgerV9 { const expected = buildHousePrimaryCoverageLedgerV9(projection); if (!exact(value, expected)) throw new Error("HOUSE_PRIMARY_COVERAGE_LEDGER_V9_INVALID"); return value as HousePrimaryCoverageLedgerV9; }
