import { createHash } from "node:crypto";
import { readFileSync } from "node:fs";
import { join } from "node:path";
import { validateAlabamaPrimaryResults } from "./house-primary-alabama-results";
import { type HousePrimaryCoverageLedgerV7, type HousePrimaryProjectionV7, validateHousePrimaryProjectionV7 } from "./house-primary-projection-v7";

type ParentObservation = HousePrimaryProjectionV7["observations"][number];
export type HousePrimaryV8Observation = Omit<ParentObservation, "resultAuthorityStatus"> & Readonly<{ resultAuthorityStatus: ParentObservation["resultAuthorityStatus"] | "official_secretary_precinct_workbooks_retained" }>;
export interface HousePrimaryProjectionV8 { readonly schema: "rapid-house-primary-projection-v8"; readonly version: 8; readonly parentProjectionPackageSha256: string; readonly alabamaResultsPackageSha256: string; readonly observations: readonly HousePrimaryV8Observation[]; readonly observationSetSha256: string; readonly coverageRows: HousePrimaryProjectionV7["coverageRows"]; readonly coverageSetSha256: string; readonly summary: Readonly<{ stateCycles: 48; districtObservations: 78; reportedContests: 22; sourceAbsent: 2; processedDistricts: 24; candidateRows: 58; retainedCandidateVotes: 1361396; sourceMarkedWinnerContests: 4; scoreEligibleDistricts: 0 }>; readonly packageSha256: string; }
export interface HousePrimaryCoverageLedgerV8 extends Omit<HousePrimaryCoverageLedgerV7, "schema" | "version" | "projectionSha256"> { readonly schema: "rapid-house-primary-coverage-ledger-v8"; readonly version: 8; readonly projectionSha256: string; }
const byteCompare = (left: string, right: string) => left < right ? -1 : left > right ? 1 : 0;
const canonical = (value: unknown): string => value === null || typeof value !== "object" ? JSON.stringify(value) : Array.isArray(value) ? `[${value.map(canonical).join(",")}]` : `{${Object.keys(value as object).sort(byteCompare).map((key) => `${JSON.stringify(key)}:${canonical((value as Record<string, unknown>)[key])}`).join(",")}}`;
const hash = (domain: string, value: unknown) => createHash("sha256").update(`${domain}\0${canonical(value)}`).digest("hex");
const exact = (left: unknown, right: unknown) => canonical(left) === canonical(right);

export function buildHousePrimaryProjectionV8(root = process.cwd()): HousePrimaryProjectionV8 {
  const parent = validateHousePrimaryProjectionV7(JSON.parse(readFileSync(join(root, "data/metadata/rapid-house-primary-projection-v7.json"), "utf8")), root), alabama = validateAlabamaPrimaryResults(JSON.parse(readFileSync(join(root, "data/metadata/rapid-house-primary-alabama-results-v1.json"), "utf8")), root), byObservation = new Map(alabama.results.map((row) => [`al:primary:${row.cycleYear}:${row.districtLabel.slice(-2)}`, row]));
  const observations: HousePrimaryV8Observation[] = parent.observations.map((row) => {
    if (row.stateCode !== "AL" || row.cycleYear === 2026) return row;
    const result = byObservation.get(row.observationId);
    if (result) return { ...row, parseStatus: "parsed", missingReason: null, sourceLockIds: result.sourceLockIds, sourceContestId: result.resultId, candidateCount: result.sourceCandidateNames.length, votes: result.totalVotes, sourceWinnerStatus: result.sourceWinnerStatus, resultAuthorityStatus: result.resultAuthorityStatus };
    if (row.observationId !== "al:primary:2022:07") throw new Error("HOUSE_PRIMARY_V8_ALABAMA_RESULT_MISSING");
    return { ...row, parseStatus: "source_absent", missingReason: "source_absent", sourceLockIds: alabama.sourceAbsent[0].sourceLockIds };
  });
  const coverageRows = parent.coverageRows.map((row) => row.stateCode !== "AL" || row.cycleYear === 2026 ? row : row.cycleYear === 2022 ? { ...row, retainedArtifactCount: 1, parsedDistrictCount: 1, sourceAbsentDistrictCount: 1, status: "parsed" as const, missingByReason: [{ reason: "source_absent" as const, count: 1 }], artifactLockIds: ["al-2022-primary-precinct-results"] } : { ...row, retainedArtifactCount: 2, parsedDistrictCount: 2, sourceAbsentDistrictCount: 0, status: "parsed" as const, missingByReason: [], artifactLockIds: ["al-2024-primary-precinct-results", "al-2024-primary-runoff-precinct-results"] });
  const reportedContests = observations.filter((row) => row.parseStatus === "parsed").length, sourceAbsent = observations.filter((row) => row.parseStatus === "source_absent").length, retainedCandidateVotes = observations.reduce((sum, row) => sum + (row.votes ?? 0), 0), sourceMarkedWinnerContests = observations.filter((row) => row.sourceWinnerStatus === "marked_by_source").length;
  if (observations.length !== 78 || coverageRows.length !== 48 || reportedContests !== 22 || sourceAbsent !== 2 || retainedCandidateVotes !== 1361396 || sourceMarkedWinnerContests !== 4 || observations.some((row) => row.scoreEligible || row.winner !== null || row.identity !== null)) throw new Error("HOUSE_PRIMARY_V8_CLOSURE_INVALID");
  const observationSetSha256 = hash("dsa-seats:rapid-house-primary-v8-observation-set:v1", observations), coverageSetSha256 = hash("dsa-seats:rapid-house-primary-v8-coverage-set:v1", coverageRows), summary = { stateCycles: 48 as const, districtObservations: 78 as const, reportedContests: 22 as const, sourceAbsent: 2 as const, processedDistricts: 24 as const, candidateRows: 58 as const, retainedCandidateVotes: 1361396 as const, sourceMarkedWinnerContests: 4 as const, scoreEligibleDistricts: 0 as const }, unsigned = { schema: "rapid-house-primary-projection-v8" as const, version: 8 as const, parentProjectionPackageSha256: parent.packageSha256, alabamaResultsPackageSha256: alabama.packageSha256, observations, observationSetSha256, coverageRows, coverageSetSha256, summary }; return { ...unsigned, packageSha256: hash("dsa-seats:rapid-house-primary-v8-package:v1", unsigned) };
}
export function validateHousePrimaryProjectionV8(value: unknown, root = process.cwd()): HousePrimaryProjectionV8 { const expected = buildHousePrimaryProjectionV8(root); if (!exact(value, expected)) throw new Error("HOUSE_PRIMARY_PROJECTION_V8_INVALID"); return value as HousePrimaryProjectionV8; }
export function buildHousePrimaryCoverageLedgerV8(projection = buildHousePrimaryProjectionV8()): HousePrimaryCoverageLedgerV8 { const rowSetSha256 = hash("dsa-seats:rapid-house-primary-v8-ledger-row-set:v1", projection.coverageRows), unsigned = { schema: "rapid-house-primary-coverage-ledger-v8" as const, version: 8 as const, projectionSha256: projection.packageSha256, rows: projection.coverageRows, rowSetSha256 }; return { ...unsigned, packageSha256: hash("dsa-seats:rapid-house-primary-v8-ledger-package:v1", unsigned) }; }
export function validateHousePrimaryCoverageLedgerV8(value: unknown, projection = buildHousePrimaryProjectionV8()): HousePrimaryCoverageLedgerV8 { const expected = buildHousePrimaryCoverageLedgerV8(projection); if (!exact(value, expected)) throw new Error("HOUSE_PRIMARY_COVERAGE_LEDGER_V8_INVALID"); return value as HousePrimaryCoverageLedgerV8; }
