import { createHash } from "node:crypto";
import { readFileSync } from "node:fs";
import { join } from "node:path";
import { validateNewHampshirePrimaryResultsV2 } from "./house-primary-new-hampshire-results-v2";
import { type HousePrimaryCoverageLedgerV14, type HousePrimaryProjectionV14, validateHousePrimaryProjectionV14 } from "./house-primary-projection-v14";
import { byteCompare, canonical, hash, sha, exact } from "./shared";

export interface HousePrimaryProjectionV15 { readonly schema:"rapid-house-primary-projection-v15";readonly version:15;readonly parentProjectionPackageSha256:string;readonly newHampshireResultsV2PackageSha256:string;readonly observations:HousePrimaryProjectionV14["observations"];readonly observationSetSha256:string;readonly coverageRows:HousePrimaryProjectionV14["coverageRows"];readonly coverageSetSha256:string;readonly summary:Readonly<{stateCycles:48;districtObservations:78;reportedContests:32;sourceAbsent:3;processedDistricts:35;candidateRows:81;retainedCandidateVotes:1974475;sourceMarkedWinnerContests:6;scoreEligibleDistricts:0}>;readonly packageSha256:string }
export interface HousePrimaryCoverageLedgerV15 extends Omit<HousePrimaryCoverageLedgerV14,"schema"|"version"|"projectionSha256"> { readonly schema:"rapid-house-primary-coverage-ledger-v15";readonly version:15;readonly projectionSha256:string }


export function buildHousePrimaryProjectionV15(root=process.cwd()):HousePrimaryProjectionV15 {
  const parent=validateHousePrimaryProjectionV14(JSON.parse(readFileSync(join(root,"data/metadata/rapid-house-primary-projection-v14.json"),"utf8")),root),nh=validateNewHampshirePrimaryResultsV2(JSON.parse(readFileSync(join(root,"data/metadata/rapid-house-primary-new-hampshire-results-v2.json"),"utf8")),root),byDistrict=new Map(nh.results.filter(row=>row.cycleYear===2022).map(row=>[row.districtLabel,row]));
  const observations:HousePrimaryProjectionV14["observations"]=parent.observations.map(row=>{if(row.stateCode!=="NH"||row.cycleYear!==2022)return row;const result=byDistrict.get(row.districtLabel as "NH-01"|"NH-02");if(!result)throw new Error("HOUSE_PRIMARY_V15_NH_RESULT_MISSING");return{...row,parseStatus:"parsed",missingReason:null,sourceLockIds:[result.sourceLockId],sourceContestId:result.resultId,candidateCount:result.candidateCount,votes:result.totalCandidateVotes,sourceWinnerStatus:result.sourceWinnerStatus,resultAuthorityStatus:result.resultAuthorityStatus,winner:null,identity:null,scoreEligible:false};});
  const coverageRows=parent.coverageRows.map(row=>row.stateCode!=="NH"||row.cycleYear!==2022?row:{...row,retainedArtifactCount:2,parsedDistrictCount:2,sourceAbsentDistrictCount:0,status:"parsed" as const,missingByReason:[],artifactLockIds:["nh-2022-democratic-cd1-primary-workbook-archived","nh-2022-democratic-cd2-primary-workbook-archived"]});
  const reportedContests=observations.filter(row=>row.parseStatus==="parsed").length,sourceAbsent=observations.filter(row=>row.parseStatus==="source_absent").length,retainedCandidateVotes=observations.reduce((sum,row)=>sum+(row.votes??0),0),sourceMarkedWinnerContests=observations.filter(row=>row.sourceWinnerStatus==="marked_by_source").length;
  if(observations.length!==78||coverageRows.length!==48||reportedContests!==32||sourceAbsent!==3||retainedCandidateVotes!==1_974_475||sourceMarkedWinnerContests!==6||observations.some(row=>row.scoreEligible||row.winner!==null||row.identity!==null))throw new Error("HOUSE_PRIMARY_V15_CLOSURE_INVALID");
  const observationSetSha256=hash("dsa-seats:rapid-house-primary-v15-observation-set:v1",observations),coverageSetSha256=hash("dsa-seats:rapid-house-primary-v15-coverage-set:v1",coverageRows),summary={stateCycles:48 as const,districtObservations:78 as const,reportedContests:32 as const,sourceAbsent:3 as const,processedDistricts:35 as const,candidateRows:81 as const,retainedCandidateVotes:1_974_475 as const,sourceMarkedWinnerContests:6 as const,scoreEligibleDistricts:0 as const},unsigned={schema:"rapid-house-primary-projection-v15" as const,version:15 as const,parentProjectionPackageSha256:parent.packageSha256,newHampshireResultsV2PackageSha256:nh.packageSha256,observations,observationSetSha256,coverageRows,coverageSetSha256,summary};return{...unsigned,packageSha256:hash("dsa-seats:rapid-house-primary-v15-package:v1",unsigned)};
}
export function validateHousePrimaryProjectionV15(value:unknown,root=process.cwd()):HousePrimaryProjectionV15{const expected=buildHousePrimaryProjectionV15(root);if(!exact(value,expected))throw new Error("HOUSE_PRIMARY_PROJECTION_V15_INVALID");return value as HousePrimaryProjectionV15;}
export function buildHousePrimaryCoverageLedgerV15(projection=buildHousePrimaryProjectionV15()):HousePrimaryCoverageLedgerV15{const rowSetSha256=hash("dsa-seats:rapid-house-primary-v15-ledger-row-set:v1",projection.coverageRows),unsigned={schema:"rapid-house-primary-coverage-ledger-v15" as const,version:15 as const,projectionSha256:projection.packageSha256,rows:projection.coverageRows,rowSetSha256};return{...unsigned,packageSha256:hash("dsa-seats:rapid-house-primary-v15-ledger-package:v1",unsigned)};}
export function validateHousePrimaryCoverageLedgerV15(value:unknown,projection=buildHousePrimaryProjectionV15()):HousePrimaryCoverageLedgerV15{const expected=buildHousePrimaryCoverageLedgerV15(projection);if(!exact(value,expected))throw new Error("HOUSE_PRIMARY_COVERAGE_LEDGER_V15_INVALID");return value as HousePrimaryCoverageLedgerV15;}
