import { createHash } from "node:crypto";
import { readFileSync } from "node:fs";
import { join } from "node:path";

import { validateNewHampshirePrimaryResults } from "./house-primary-new-hampshire-results";
import { type HousePrimaryCoverageLedgerV12,type HousePrimaryProjectionV12,validateHousePrimaryProjectionV12 } from "./house-primary-projection-v12";

type ParentObservation=HousePrimaryProjectionV12["observations"][number];
export type HousePrimaryV13Observation=Omit<ParentObservation,"resultAuthorityStatus">&Readonly<{resultAuthorityStatus:ParentObservation["resultAuthorityStatus"]|"archived_copy_of_official_secretary_workbook_retained_live_host_403_not_claimed_certified"}>;
export interface HousePrimaryProjectionV13 {
  readonly schema:"rapid-house-primary-projection-v13";readonly version:13;readonly parentProjectionPackageSha256:string;readonly newHampshireResultsPackageSha256:string;
  readonly observations:readonly HousePrimaryV13Observation[];readonly observationSetSha256:string;readonly coverageRows:HousePrimaryProjectionV12["coverageRows"];readonly coverageSetSha256:string;
  readonly summary:Readonly<{stateCycles:48;districtObservations:78;reportedContests:29;sourceAbsent:3;processedDistricts:32;candidateRows:77;retainedCandidateVotes:1_801_515;sourceMarkedWinnerContests:6;scoreEligibleDistricts:0}>;readonly packageSha256:string;
}
export interface HousePrimaryCoverageLedgerV13 extends Omit<HousePrimaryCoverageLedgerV12,"schema"|"version"|"projectionSha256">{readonly schema:"rapid-house-primary-coverage-ledger-v13";readonly version:13;readonly projectionSha256:string;}
const byteCompare=(left:string,right:string)=>left<right?-1:left>right?1:0;
const canonical=(value:unknown):string=>value===null||typeof value!=="object"?JSON.stringify(value):Array.isArray(value)?`[${value.map(canonical).join(",")}]`:`{${Object.keys(value as object).sort(byteCompare).map(key=>`${JSON.stringify(key)}:${canonical((value as Record<string,unknown>)[key])}`).join(",")}}`;
const hash=(domain:string,value:unknown)=>createHash("sha256").update(`${domain}\0${canonical(value)}`).digest("hex");const exact=(left:unknown,right:unknown)=>canonical(left)===canonical(right);
export function buildHousePrimaryProjectionV13(root=process.cwd()):HousePrimaryProjectionV13{
  const parent=validateHousePrimaryProjectionV12(JSON.parse(readFileSync(join(root,"data/metadata/rapid-house-primary-projection-v12.json"),"utf8")),root),nh=validateNewHampshirePrimaryResults(JSON.parse(readFileSync(join(root,"data/metadata/rapid-house-primary-new-hampshire-results-v1.json"),"utf8")),root),byDistrict=new Map(nh.results.map(row=>[row.districtLabel,row]));
  const observations:HousePrimaryV13Observation[]=parent.observations.map(row=>{if(row.stateCode!=="NH"||row.cycleYear!==2024)return row;const result=byDistrict.get(row.districtLabel as "NH-01"|"NH-02");if(!result)throw new Error("HOUSE_PRIMARY_V13_NH_RESULT_MISSING");return{...row,parseStatus:"parsed" as const,missingReason:null,sourceLockIds:[result.sourceLockId],sourceContestId:result.resultId,candidateCount:result.candidateCount,votes:result.totalCandidateVotes,sourceWinnerStatus:result.sourceWinnerStatus,resultAuthorityStatus:result.resultAuthorityStatus,winner:null,identity:null,scoreEligible:false as const};});
  const coverageRows=parent.coverageRows.map(row=>row.stateCode!=="NH"||row.cycleYear!==2024?row:{...row,retainedArtifactCount:3,parsedDistrictCount:2,sourceAbsentDistrictCount:0,status:"parsed" as const,missingByReason:[],artifactLockIds:["nh-2024-primary-results","nh-2024-democratic-cd1-primary-workbook-archived","nh-2024-democratic-cd2-primary-workbook-archived"]});
  const reportedContests=observations.filter(row=>row.parseStatus==="parsed").length,sourceAbsent=observations.filter(row=>row.parseStatus==="source_absent").length,retainedCandidateVotes=observations.reduce((sum,row)=>sum+(row.votes??0),0),sourceMarkedWinnerContests=observations.filter(row=>row.sourceWinnerStatus==="marked_by_source").length;
  if(observations.length!==78||coverageRows.length!==48||reportedContests!==29||sourceAbsent!==3||retainedCandidateVotes!==1_801_515||sourceMarkedWinnerContests!==6||observations.some(row=>row.scoreEligible||row.winner!==null||row.identity!==null))throw new Error("HOUSE_PRIMARY_V13_CLOSURE_INVALID");
  const observationSetSha256=hash("dsa-seats:rapid-house-primary-v13-observation-set:v1",observations),coverageSetSha256=hash("dsa-seats:rapid-house-primary-v13-coverage-set:v1",coverageRows),summary={stateCycles:48 as const,districtObservations:78 as const,reportedContests:29 as const,sourceAbsent:3 as const,processedDistricts:32 as const,candidateRows:77 as const,retainedCandidateVotes:1_801_515 as const,sourceMarkedWinnerContests:6 as const,scoreEligibleDistricts:0 as const},unsigned={schema:"rapid-house-primary-projection-v13" as const,version:13 as const,parentProjectionPackageSha256:parent.packageSha256,newHampshireResultsPackageSha256:nh.packageSha256,observations,observationSetSha256,coverageRows,coverageSetSha256,summary};return{...unsigned,packageSha256:hash("dsa-seats:rapid-house-primary-v13-package:v1",unsigned)};
}
export function validateHousePrimaryProjectionV13(value:unknown,root=process.cwd()):HousePrimaryProjectionV13{const expected=buildHousePrimaryProjectionV13(root);if(!exact(value,expected))throw new Error("HOUSE_PRIMARY_PROJECTION_V13_INVALID");return value as HousePrimaryProjectionV13;}
export function buildHousePrimaryCoverageLedgerV13(projection=buildHousePrimaryProjectionV13()):HousePrimaryCoverageLedgerV13{const rowSetSha256=hash("dsa-seats:rapid-house-primary-v13-ledger-row-set:v1",projection.coverageRows),unsigned={schema:"rapid-house-primary-coverage-ledger-v13" as const,version:13 as const,projectionSha256:projection.packageSha256,rows:projection.coverageRows,rowSetSha256};return{...unsigned,packageSha256:hash("dsa-seats:rapid-house-primary-v13-ledger-package:v1",unsigned)};}
export function validateHousePrimaryCoverageLedgerV13(value:unknown,projection=buildHousePrimaryProjectionV13()):HousePrimaryCoverageLedgerV13{const expected=buildHousePrimaryCoverageLedgerV13(projection);if(!exact(value,expected))throw new Error("HOUSE_PRIMARY_COVERAGE_LEDGER_V13_INVALID");return value as HousePrimaryCoverageLedgerV13;}
