import { readFileSync } from "node:fs";
import { join } from "node:path";
import { validateGeorgiaStateLegislativeResults } from "./georgia-state-legislative-results";
import { validateRapidLocalContextCoverageV5 } from "./local-context-coverage-v5";
import { byteCompare, canonical, hash, sha, exact } from "./shared";
type Artifact = Readonly<{ id: string; label: string; scope: string; summary: Readonly<Record<string, number>>; packageSha256: string; formulaEligibleCount: 0 }>;
export interface RapidLocalContextCoverageV6 { readonly schema: "rapid-local-context-coverage-v6"; readonly version: 6; readonly releaseRelationship: "separate_rapid_acquisition_excluded_from_released_score"; readonly artifacts: readonly Artifact[]; readonly artifactSetSha256: string; readonly packageSha256: string }
export function buildRapidLocalContextCoverageV6(root = process.cwd()): RapidLocalContextCoverageV6 { const prior = validateRapidLocalContextCoverageV5(JSON.parse(readFileSync(join(root, "data/metadata/rapid-local-context-coverage-v5.json"), "utf8")), root), georgia = validateGeorgiaStateLegislativeResults(JSON.parse(readFileSync(join(root, "data/metadata/rapid-georgia-state-legislative-primary-results-v1.json"), "utf8")), root), artifacts: Artifact[] = [...prior.artifacts, { id: "rapid-georgia-state-legislative-primary-results-v1", label: "Georgia state-legislative primary context", scope: "Georgia 2022, 2024, and 2026 state House and Senate regular primaries", summary: { officeDistrictRows: georgia.summary.officeDistrictRows, partyContests: georgia.summary.partyContests, candidateRows: georgia.summary.candidateRows, candidateVotes: georgia.summary.candidateVotes, formulaEligibleContests: georgia.summary.formulaEligibleContests }, packageSha256: georgia.packageSha256, formulaEligibleCount: 0 }], artifactSetSha256 = hash("dsa-seats:rapid-local-context-coverage-artifact-set:v6", artifacts), unsigned = { schema: "rapid-local-context-coverage-v6" as const, version: 6 as const, releaseRelationship: "separate_rapid_acquisition_excluded_from_released_score" as const, artifacts, artifactSetSha256 }; return { ...unsigned, packageSha256: hash("dsa-seats:rapid-local-context-coverage-package:v6", unsigned) }; }
export function validateRapidLocalContextCoverageV6(value: unknown, root = process.cwd()): RapidLocalContextCoverageV6 { const expected = buildRapidLocalContextCoverageV6(root); if (canonical(value) !== canonical(expected)) throw new Error("RAPID_LOCAL_CONTEXT_COVERAGE_V6_INVALID"); return value as RapidLocalContextCoverageV6; }
