import { createHash } from "node:crypto";
import { readFileSync } from "node:fs";
import { join } from "node:path";
import { validateKentuckyStateLegislativeResults } from "./kentucky-state-legislative-results";
import { validateRapidLocalContextCoverageV11 } from "./local-context-coverage-v11";
type Artifact = Readonly<{ id: string; label: string; scope: string; summary: Readonly<Record<string, number>>; packageSha256: string; formulaEligibleCount: 0 }>;
export interface RapidLocalContextCoverageV12 { readonly schema: "rapid-local-context-coverage-v12"; readonly version: 12; readonly releaseRelationship: "separate_rapid_acquisition_excluded_from_released_score"; readonly artifacts: readonly Artifact[]; readonly artifactSetSha256: string; readonly packageSha256: string }
const cmp = (a: string, b: string) => a < b ? -1 : a > b ? 1 : 0, canonical = (v: unknown): string => v === null || typeof v !== "object" ? JSON.stringify(v) : Array.isArray(v) ? `[${v.map(canonical).join(",")}]` : `{${Object.keys(v as object).sort(cmp).map((k) => `${JSON.stringify(k)}:${canonical((v as Record<string, unknown>)[k])}`).join(",")}}`, hash = (d: string, v: unknown) => createHash("sha256").update(`${d}\0${canonical(v)}`).digest("hex");
export function buildRapidLocalContextCoverageV12(root = process.cwd()): RapidLocalContextCoverageV12 { const prior = validateRapidLocalContextCoverageV11(JSON.parse(readFileSync(join(root, "data/metadata/rapid-local-context-coverage-v11.json"), "utf8")), root), kentucky = validateKentuckyStateLegislativeResults(JSON.parse(readFileSync(join(root, "data/metadata/rapid-kentucky-state-legislative-primary-results-v1.json"), "utf8")), root), artifacts: Artifact[] = [...prior.artifacts, { id: "rapid-kentucky-state-legislative-primary-results-v1", label: "Kentucky state-legislative primary context", scope: "Kentucky 2022, 2024, and 2026 reported Democratic and Republican state House and Senate primary contests", summary: { reportedPartyContests: kentucky.summary.reportedPartyContests, candidateRows: kentucky.summary.candidateRows, candidateVotes: kentucky.summary.candidateVotes, formulaEligibleContests: kentucky.summary.formulaEligibleContests }, packageSha256: kentucky.packageSha256, formulaEligibleCount: 0 }], artifactSetSha256 = hash("dsa-seats:rapid-local-context-coverage-artifact-set:v12", artifacts), unsigned = { schema: "rapid-local-context-coverage-v12" as const, version: 12 as const, releaseRelationship: "separate_rapid_acquisition_excluded_from_released_score" as const, artifacts, artifactSetSha256 }; return { ...unsigned, packageSha256: hash("dsa-seats:rapid-local-context-coverage-package:v12", unsigned) }; }
export function validateRapidLocalContextCoverageV12(value: unknown, root = process.cwd()): RapidLocalContextCoverageV12 { const expected = buildRapidLocalContextCoverageV12(root); if (canonical(value) !== canonical(expected)) throw new Error("RAPID_LOCAL_CONTEXT_COVERAGE_V12_INVALID"); return value as RapidLocalContextCoverageV12; }
