import { readFileSync } from "node:fs";
import { join } from "node:path";

import { validateHawaiiStateLegislativeResults } from "./hawaii-state-legislative-results";
import { validateRapidLocalContextCoverageV9 } from "./local-context-coverage-v9";
import { byteCompare, canonical, hash, sha, exact } from "./shared";

type Artifact = Readonly<{ id: string; label: string; scope: string; summary: Readonly<Record<string, number>>; packageSha256: string; formulaEligibleCount: 0 }>;
export interface RapidLocalContextCoverageV10 { readonly schema: "rapid-local-context-coverage-v10"; readonly version: 10; readonly releaseRelationship: "separate_rapid_acquisition_excluded_from_released_score"; readonly artifacts: readonly Artifact[]; readonly artifactSetSha256: string; readonly packageSha256: string }
export function buildRapidLocalContextCoverageV10(root = process.cwd()): RapidLocalContextCoverageV10 { const prior = validateRapidLocalContextCoverageV9(JSON.parse(readFileSync(join(root, "data/metadata/rapid-local-context-coverage-v9.json"), "utf8")), root), hawaii = validateHawaiiStateLegislativeResults(JSON.parse(readFileSync(join(root, "data/metadata/rapid-hawaii-state-legislative-primary-results-v1.json"), "utf8")), root), artifacts: Artifact[] = [...prior.artifacts, { id: "rapid-hawaii-state-legislative-primary-results-v1", label: "Hawaii state-legislative primary context", scope: "Hawaii 2022 and 2024 reported Democratic and Republican state House and Senate primary contests", summary: { reportedPartyContests: hawaii.summary.reportedPartyContests, candidateRows: hawaii.summary.candidateRows, candidateVotes: hawaii.summary.candidateVotes, inferredNoContestRows: hawaii.summary.inferredNoContestRows, formulaEligibleContests: hawaii.summary.formulaEligibleContests }, packageSha256: hawaii.packageSha256, formulaEligibleCount: 0 }], artifactSetSha256 = hash("dsa-seats:rapid-local-context-coverage-artifact-set:v10", artifacts), unsigned = { schema: "rapid-local-context-coverage-v10" as const, version: 10 as const, releaseRelationship: "separate_rapid_acquisition_excluded_from_released_score" as const, artifacts, artifactSetSha256 }; return { ...unsigned, packageSha256: hash("dsa-seats:rapid-local-context-coverage-package:v10", unsigned) }; }
export function validateRapidLocalContextCoverageV10(value: unknown, root = process.cwd()): RapidLocalContextCoverageV10 { const expected = buildRapidLocalContextCoverageV10(root); if (canonical(value) !== canonical(expected)) throw new Error("RAPID_LOCAL_CONTEXT_COVERAGE_V10_INVALID"); return value as RapidLocalContextCoverageV10; }
