import { createHash } from "node:crypto";
import { readFileSync } from "node:fs";
import { join } from "node:path";
import { validateNorthCarolinaLocalOfficeResults } from "./north-carolina-local-office-results";
import { validateRapidLocalContextCoverageV12 } from "./local-context-coverage-v12";
type Artifact = Readonly<{ id: string; label: string; scope: string; summary: Readonly<Record<string, number>>; packageSha256: string; formulaEligibleCount: 0 }>;
export interface RapidLocalContextCoverageV13 { readonly schema: "rapid-local-context-coverage-v13"; readonly version: 13; readonly releaseRelationship: "separate_rapid_acquisition_excluded_from_released_score"; readonly artifacts: readonly Artifact[]; readonly artifactSetSha256: string; readonly packageSha256: string }
const cmp = (a: string, b: string) => a < b ? -1 : a > b ? 1 : 0, canonical = (v: unknown): string => v === null || typeof v !== "object" ? JSON.stringify(v) : Array.isArray(v) ? `[${v.map(canonical).join(",")}]` : `{${Object.keys(v as object).sort(cmp).map((k) => `${JSON.stringify(k)}:${canonical((v as Record<string, unknown>)[k])}`).join(",")}}`, hash = (d: string, v: unknown) => createHash("sha256").update(`${d}\0${canonical(v)}`).digest("hex");
export function buildRapidLocalContextCoverageV13(root = process.cwd()): RapidLocalContextCoverageV13 { const prior = validateRapidLocalContextCoverageV12(JSON.parse(readFileSync(join(root, "data/metadata/rapid-local-context-coverage-v12.json"), "utf8")), root), local = validateNorthCarolinaLocalOfficeResults(JSON.parse(readFileSync(join(root, "data/metadata/rapid-north-carolina-local-office-primary-results-v1.json"), "utf8")), root), artifacts: Artifact[] = [...prior.artifacts, { id: "rapid-north-carolina-local-office-primary-results-v1", label: "North Carolina local-office primary context", scope: "North Carolina 2022, 2024, and 2026 county, school-board, sheriff, court-clerk, register-of-deeds, and municipal primary contests", summary: { officeFamilies: local.summary.officeFamilies, officeContests: local.summary.officeContests, candidateRows: local.summary.candidateRows, candidateVotes: local.summary.candidateVotes, formulaEligibleContests: local.summary.formulaEligibleContests }, packageSha256: local.packageSha256, formulaEligibleCount: 0 }], artifactSetSha256 = hash("dsa-seats:rapid-local-context-coverage-artifact-set:v13", artifacts), unsigned = { schema: "rapid-local-context-coverage-v13" as const, version: 13 as const, releaseRelationship: "separate_rapid_acquisition_excluded_from_released_score" as const, artifacts, artifactSetSha256 }; return { ...unsigned, packageSha256: hash("dsa-seats:rapid-local-context-coverage-package:v13", unsigned) }; }
export function validateRapidLocalContextCoverageV13(value: unknown, root = process.cwd()): RapidLocalContextCoverageV13 { const expected = buildRapidLocalContextCoverageV13(root); if (canonical(value) !== canonical(expected)) throw new Error("RAPID_LOCAL_CONTEXT_COVERAGE_V13_INVALID"); return value as RapidLocalContextCoverageV13; }
