import { readFileSync } from "node:fs";
import { join } from "node:path";

import { validateRapidLocalContextCoverageV10 } from "./local-context-coverage-v10";
import { validateMissouriStateLegislativeResults } from "./missouri-state-legislative-results";
import { byteCompare, canonical, hash, sha, exact } from "./shared";

type Artifact = Readonly<{ id: string; label: string; scope: string; summary: Readonly<Record<string, number>>; packageSha256: string; formulaEligibleCount: 0 }>;
export interface RapidLocalContextCoverageV11 { readonly schema: "rapid-local-context-coverage-v11"; readonly version: 11; readonly releaseRelationship: "separate_rapid_acquisition_excluded_from_released_score"; readonly artifacts: readonly Artifact[]; readonly artifactSetSha256: string; readonly packageSha256: string }
export function buildRapidLocalContextCoverageV11(root = process.cwd()): RapidLocalContextCoverageV11 { const prior = validateRapidLocalContextCoverageV10(JSON.parse(readFileSync(join(root, "data/metadata/rapid-local-context-coverage-v10.json"), "utf8")), root), missouri = validateMissouriStateLegislativeResults(JSON.parse(readFileSync(join(root, "data/metadata/rapid-missouri-state-legislative-primary-results-v1.json"), "utf8")), root), artifacts: Artifact[] = [...prior.artifacts, { id: "rapid-missouri-state-legislative-primary-results-v1", label: "Missouri state-legislative primary context", scope: "Missouri 2022 and 2024 reported Democratic and Republican state House and Senate primary contests", summary: { partyContests: missouri.summary.partyContests, candidateRows: missouri.summary.candidateRows, candidateVotes: missouri.summary.candidateVotes, formulaEligibleContests: missouri.summary.formulaEligibleContests }, packageSha256: missouri.packageSha256, formulaEligibleCount: 0 }], artifactSetSha256 = hash("dsa-seats:rapid-local-context-coverage-artifact-set:v11", artifacts), unsigned = { schema: "rapid-local-context-coverage-v11" as const, version: 11 as const, releaseRelationship: "separate_rapid_acquisition_excluded_from_released_score" as const, artifacts, artifactSetSha256 }; return { ...unsigned, packageSha256: hash("dsa-seats:rapid-local-context-coverage-package:v11", unsigned) }; }
export function validateRapidLocalContextCoverageV11(value: unknown, root = process.cwd()): RapidLocalContextCoverageV11 { const expected = buildRapidLocalContextCoverageV11(root); if (canonical(value) !== canonical(expected)) throw new Error("RAPID_LOCAL_CONTEXT_COVERAGE_V11_INVALID"); return value as RapidLocalContextCoverageV11; }
