import { readFileSync } from "node:fs";
import { join } from "node:path";
import { validateDelawareStateLegislativeResults } from "./delaware-state-legislative-results";
import { validateRapidLocalContextCoverageV8 } from "./local-context-coverage-v8";
import { byteCompare, canonical, hash, sha, exact } from "./shared";
type Artifact = Readonly<{ id: string; label: string; scope: string; summary: Readonly<Record<string, number>>; packageSha256: string; formulaEligibleCount: 0 }>;
export interface RapidLocalContextCoverageV9 { readonly schema: "rapid-local-context-coverage-v9"; readonly version: 9; readonly releaseRelationship: "separate_rapid_acquisition_excluded_from_released_score"; readonly artifacts: readonly Artifact[]; readonly artifactSetSha256: string; readonly packageSha256: string }
export function buildRapidLocalContextCoverageV9(root = process.cwd()): RapidLocalContextCoverageV9 { const prior = validateRapidLocalContextCoverageV8(JSON.parse(readFileSync(join(root, "data/metadata/rapid-local-context-coverage-v8.json"), "utf8")), root), delaware = validateDelawareStateLegislativeResults(JSON.parse(readFileSync(join(root, "data/metadata/rapid-delaware-state-legislative-primary-results-v1.json"), "utf8")), root), artifacts: Artifact[] = [...prior.artifacts, { id: "rapid-delaware-state-legislative-primary-results-v1", label: "Delaware state-legislative primary context", scope: "Delaware 2022 and 2024 candidate-bearing state House and Senate primary contests", summary: { reportedPartyContests: delaware.summary.reportedPartyContests, candidateRows: delaware.summary.candidateRows, candidateVotes: delaware.summary.candidateVotes, inferredNoContestRows: delaware.summary.inferredNoContestRows, formulaEligibleContests: delaware.summary.formulaEligibleContests }, packageSha256: delaware.packageSha256, formulaEligibleCount: 0 }], artifactSetSha256 = hash("dsa-seats:rapid-local-context-coverage-artifact-set:v9", artifacts), unsigned = { schema: "rapid-local-context-coverage-v9" as const, version: 9 as const, releaseRelationship: "separate_rapid_acquisition_excluded_from_released_score" as const, artifacts, artifactSetSha256 }; return { ...unsigned, packageSha256: hash("dsa-seats:rapid-local-context-coverage-package:v9", unsigned) }; }
export function validateRapidLocalContextCoverageV9(value: unknown, root = process.cwd()): RapidLocalContextCoverageV9 { const expected = buildRapidLocalContextCoverageV9(root); if (canonical(value) !== canonical(expected)) throw new Error("RAPID_LOCAL_CONTEXT_COVERAGE_V9_INVALID"); return value as RapidLocalContextCoverageV9; }
