import { createHash } from "node:crypto";
import { readFileSync } from "node:fs";
import { join } from "node:path";
import { validateNorthCarolinaStateLegislativeResults } from "./north-carolina-state-legislative-results";
import { validateRapidLocalContextCoverageV6 } from "./local-context-coverage-v6";
type Artifact = Readonly<{ id: string; label: string; scope: string; summary: Readonly<Record<string, number>>; packageSha256: string; formulaEligibleCount: 0 }>;
export interface RapidLocalContextCoverageV7 { readonly schema: "rapid-local-context-coverage-v7"; readonly version: 7; readonly releaseRelationship: "separate_rapid_acquisition_excluded_from_released_score"; readonly artifacts: readonly Artifact[]; readonly artifactSetSha256: string; readonly packageSha256: string }
const byteCompare = (left: string, right: string) => left < right ? -1 : left > right ? 1 : 0, canonical = (value: unknown): string => value === null || typeof value !== "object" ? JSON.stringify(value) : Array.isArray(value) ? `[${value.map(canonical).join(",")}]` : `{${Object.keys(value as object).sort(byteCompare).map((key) => `${JSON.stringify(key)}:${canonical((value as Record<string, unknown>)[key])}`).join(",")}}`, hash = (domain: string, value: unknown) => createHash("sha256").update(`${domain}\0${canonical(value)}`).digest("hex");
export function buildRapidLocalContextCoverageV7(root = process.cwd()): RapidLocalContextCoverageV7 { const prior = validateRapidLocalContextCoverageV6(JSON.parse(readFileSync(join(root, "data/metadata/rapid-local-context-coverage-v6.json"), "utf8")), root), northCarolina = validateNorthCarolinaStateLegislativeResults(JSON.parse(readFileSync(join(root, "data/metadata/rapid-north-carolina-state-legislative-primary-results-v1.json"), "utf8")), root), artifacts: Artifact[] = [...prior.artifacts, { id: "rapid-north-carolina-state-legislative-primary-results-v1", label: "North Carolina state-legislative primary context", scope: "North Carolina 2022, 2024, and 2026 state House and Senate primaries", summary: { officeDistrictRows: northCarolina.summary.officeDistrictRows, partyContests: northCarolina.summary.partyContests, candidateRows: northCarolina.summary.candidateRows, candidateVotes: northCarolina.summary.candidateVotes, formulaEligibleContests: northCarolina.summary.formulaEligibleContests }, packageSha256: northCarolina.packageSha256, formulaEligibleCount: 0 }], artifactSetSha256 = hash("dsa-seats:rapid-local-context-coverage-artifact-set:v7", artifacts), unsigned = { schema: "rapid-local-context-coverage-v7" as const, version: 7 as const, releaseRelationship: "separate_rapid_acquisition_excluded_from_released_score" as const, artifacts, artifactSetSha256 }; return { ...unsigned, packageSha256: hash("dsa-seats:rapid-local-context-coverage-package:v7", unsigned) }; }
export function validateRapidLocalContextCoverageV7(value: unknown, root = process.cwd()): RapidLocalContextCoverageV7 { const expected = buildRapidLocalContextCoverageV7(root); if (canonical(value) !== canonical(expected)) throw new Error("RAPID_LOCAL_CONTEXT_COVERAGE_V7_INVALID"); return value as RapidLocalContextCoverageV7; }
