import { createHash } from "node:crypto";
import { z } from "zod";
import { validateDsaTargetReviewReportV6 } from "../../domain/dsa-target-review-report-v6";
import { validateAipacEvidenceFoundationCandidateV4 } from "./aipac-evidence-foundation-candidate-v4";
import { validateAipacNumericEvidenceCandidateV4 } from "./aipac-numeric-evidence-candidate-v4";
import { canonicalJson } from "./aipac-proposed-packages";

const SHA = z.string().regex(/^[a-f0-9]{64}$/);
const FILES = { foundation: "172095d17f0362e8f4da56ce4702727215b73c03362a22f0ae3270d1ebe95cc6", candidate: "4aae1342be0439f510f44bdb0b1d5d73066e6823599a186ab066cf7495eb9099", report: "cdce153e52cbfbcee669c64a6671b4d52cb11728f04c8a7bb2092c96b0063401" } as const;
const PACKAGES = { foundation: "657feef821124ecd4bd1af66784787652e2513a37401cb75d739fcfdf78ebb94", candidate: "7dd647ac1937b2104aef91db249e9afa72867464035560590823ec57c08b8c28", report: "9df5ab4cb08556aac9a5ff87aa33d8bdf2aeed3a374b9c7d46fdc60e1d7965b7" } as const;
const CLOSURE = { decisionId: "aipac-mapping-precedence:incumbent:seat_house_ca_31_current:2024:H8CA39174", receiptFileSha256: "1c3d46fcfc76a33ed1fca469cbefb9924622a2245f266fc6394850845c9b7198", receiptPackageSha256: "8201a54aa4894163bda0a24b214c10166ade3fe4fcbe31b6e0667d7094b11cee", evidenceSetSha256: "539ed96bbfa5e6058d5a3f9085b9d3d804616c3615c9613b265f6952228fe3c8", closureSha256: "a5a5298e3204443b1c6516e7de6537e684cfd155a48c3d2fda0ac6ef6da854ee" } as const;
const decision = z.strictObject({
  decisionId: z.string().min(1), component: z.enum(["candidate_committee_source_precedence", "numeric_lineage_methodology", "inferred_udp_relationships", "scoring_model", "publication_promotion"]), affectedSeatCycleId: z.string().min(1).nullable(), affectedCycleYear: z.number().int().nullable(),
  question: z.string().min(1), recommendedDecision: z.string().min(1), defaultReversibleAssumption: z.string().min(1), alternatives: z.array(z.string().min(1)).min(1), consequences: z.array(z.string().min(1)).min(1), confidence: z.enum(["high", "medium", "high_but_insufficiently_closed"]), blocksPublication: z.literal(true), blocksOtherWork: z.literal(false), workCompletedWhileWaiting: z.array(z.string().min(1)).min(1), requiredEvidence: z.array(z.string().min(1)), evidenceSha256s: z.array(SHA).min(1), officialFilingSourceLockIds: z.array(z.string().min(1)), resolution: z.null(), reviewer: z.null(), reviewedAt: z.null(), decisionSha256: SHA,
});
export const aipacNumericReviewPackageV4Schema = z.strictObject({ schema: z.literal("aipac-numeric-review-package-v4"), version: z.literal(4), generatedAt: z.literal("2026-08-05T23:30:00.000Z"), sourceCutoff: z.literal("2026-08-04"), reviewerOnly: z.literal(true), publicationEligible: z.literal(false), review: z.strictObject({ status: z.literal("proposed"), reviewer: z.null(), reviewedAt: z.null() }), inputs: z.strictObject({ foundation: z.strictObject({ fileSha256: z.literal(FILES.foundation), packageSha256: z.literal(PACKAGES.foundation) }), candidate: z.strictObject({ fileSha256: z.literal(FILES.candidate), packageSha256: z.literal(PACKAGES.candidate) }), report: z.strictObject({ fileSha256: z.literal(FILES.report), reportSha256: z.literal(PACKAGES.report) }) }), summary: z.strictObject({ totalDecisions: z.literal(4), mappingPrecedenceDecisions: z.literal(0), methodologyDecisions: z.literal(3), promotionDecisions: z.literal(1), automaticallyResolvedIncumbentCases: z.literal(6), automaticallyClosedMappingDecisions: z.literal(1), safeDefault: z.literal("retain_reviewer_candidate_exclude_from_publication") }), automaticEvidenceClosures: z.tuple([z.strictObject({ decisionId: z.string(), seatCycleId: z.string(), cycleYear: z.literal(2024), closureKind: z.literal("mechanically_verified_official_evidence"), receiptSourceLockId: z.literal("ca31-terminal-fec-chain-receipt-v1"), receiptFileSha256: SHA, receiptPackageSha256: SHA, evidenceSetSha256: SHA, reviewerAction: z.literal(false), reviewer: z.null(), reviewedAt: z.null(), closureSha256: SHA })]), decisions: z.array(decision).length(4), decisionSetSha256: SHA, packageSha256: SHA });
export type AipacNumericReviewPackageV4 = z.infer<typeof aipacNumericReviewPackageV4Schema>;
const hash = (domain: string, value: unknown): string => createHash("sha256").update(domain).update(canonicalJson(value)).digest("hex");
const order = (a: string, b: string): number => Buffer.compare(Buffer.from(a), Buffer.from(b));
type Unsigned = Omit<z.infer<typeof decision>, "decisionSha256">;
const seal = (value: Unsigned): z.infer<typeof decision> => decision.parse({ ...value, decisionSha256: hash("dsa-seats:aipac-numeric-review-decision:v4\0", value) });

export function buildAipacNumericReviewPackageV4(input: Readonly<{ foundation: unknown; foundationFileSha256: string; candidate: unknown; candidateFileSha256: string; report: unknown; reportFileSha256: string }>): AipacNumericReviewPackageV4 {
  if (canonicalJson([input.foundationFileSha256, input.candidateFileSha256, input.reportFileSha256]) !== canonicalJson([FILES.foundation, FILES.candidate, FILES.report])) throw new Error("AIPAC_NUMERIC_REVIEW_V4_INPUT_FILE_HASH_MISMATCH");
  const foundation = validateAipacEvidenceFoundationCandidateV4(input.foundation), candidate = validateAipacNumericEvidenceCandidateV4(input.candidate), report = validateDsaTargetReviewReportV6(input.report);
  if (foundation.packageSha256 !== PACKAGES.foundation || candidate.packageSha256 !== PACKAGES.candidate || report.reportSha256 !== PACKAGES.report || foundation.sourceCutoff !== candidate.sourceCutoff || candidate.sourceCutoff !== report.scope.sourceCutoff) throw new Error("AIPAC_NUMERIC_REVIEW_V4_INPUT_CLOSURE_INVALID");
  const base = { blocksPublication: true as const, blocksOtherWork: false as const, resolution: null, reviewer: null, reviewedAt: null };
  const highLevel: Unsigned[] = [
    { ...base, decisionId: "aipac-numeric:accept-lineage-methodology-v4", component: "numeric_lineage_methodology", affectedSeatCycleId: null, affectedCycleYear: null, question: "Should the cycle-scoped cutoff-ledger, terminal-revision, signed-net, exact/derived relationship-disposition, and transaction-receipt methodology be accepted for a future reviewed factual release?", recommendedDecision: "Accept only the reproducible v4 method, including the source-locked CA-31 terminal-chain closure and preserved House-cycle non-applicability states.", defaultReversibleAssumption: "retain_reviewer_candidate_exclude_from_publication", alternatives: ["Request a corrected coverage or transaction rule.", "Reject numeric use and keep AIPAC not collected."], consequences: ["Acceptance permits this exact method, not automatic publication, to enter a later reviewed release.", "Deferral leaves report v6 available only for reviewer analysis."], confidence: "high", workCompletedWhileWaiting: ["Numeric v4 retains 278 evidence rows with 261 evaluator-eligible rows, zero blocked cells, and four not-applicable cells.", "Every selected transaction remains joined to a cutoff-valid filing chain and receipt."], requiredEvidence: [], evidenceSha256s: [candidate.packageSha256, candidate.derivation.seatSetSha256, candidate.derivation.evidenceSetSha256], officialFilingSourceLockIds: [] },
    { ...base, decisionId: "aipac-numeric:accept-labeled-udp-inferences-v4", component: "inferred_udp_relationships", affectedSeatCycleId: null, affectedCycleYear: null, question: "Should the 16 usable UDP challenger relationships remain explicitly labeled inferences in a future reviewed release?", recommendedDecision: "Accept them only with exact inference or automatic-disposition provenance, confidence, same-seat primary rationale, and correction path; never relabel them as direct mappings.", defaultReversibleAssumption: "retain_reviewer_candidate_exclude_from_publication", alternatives: ["Require individual review of all 16 relationships.", "Exclude all challenger-opposition evidence."], consequences: ["Acceptance preserves reviewer-visible challenger-opposition evidence without a direct-observation claim.", "Rejection requires regenerated numeric and report artifacts."], confidence: "medium", workCompletedWhileWaiting: ["The Illinois 7 positive-origin relationship is mechanically admitted and California 47's invalid origin remains rejected.", "All retained inference relationships remain hash-bound."], requiredEvidence: [], evidenceSha256s: [foundation.packageSha256, foundation.derivation.relationshipSetSha256], officialFilingSourceLockIds: [] },
    { ...base, decisionId: "aipac-numeric:accept-v01-score-contract-v4", component: "scoring_model", affectedSeatCycleId: null, affectedCycleYear: null, question: "Should formula dsa-primary-target-v0.1 retain its AIPAC-route weights (60% AIPAC support, 25% blue baseline, 15% primary feasibility) and six-cell AIPAC coverage denominator, leaving MA-06 and NH-01 AIPAC-score-ineligible when 2026 is not applicable to a House candidacy?", recommendedDecision: "Accept the explainable v0.1 weights and denominator for this candidate; require a separately versioned formula, sensitivity analysis, and review package before changing either weights or not-applicable handling.", defaultReversibleAssumption: "retain_reviewer_candidate_exclude_from_publication", alternatives: ["Propose separately versioned AIPAC-route weights and regenerate sensitivity results.", "Propose a separately versioned not-applicable denominator and regenerate sensitivity results.", "Keep AIPAC evidence visible but exclude it from ranking."], consequences: ["Acceptance preserves the 60% AIPAC-route weight while keeping MA-06 and NH-01 AIPAC components null rather than converting their 2026 state to zero.", "Changing either weights or the denominator changes scores or eligibility and requires a new formula and report hash."], confidence: "high", workCompletedWhileWaiting: ["Report v6 decomposes the current 60/25/15 AIPAC route for 202 formula-compatible complete-coverage seats and keeps MA-06, NH-01, and eight Washington seats from that route.", "CA-31 is scoreable with complete-zero 2024 cells and no fabricated AIPAC evidence."], requiredEvidence: [], evidenceSha256s: [report.reportSha256, candidate.packageSha256], officialFilingSourceLockIds: [] },
    { ...base, decisionId: "aipac-numeric:promote-factual-release-v4", component: "publication_promotion", affectedSeatCycleId: null, affectedCycleYear: null, question: "Should numeric candidate v4 and report v6 be promoted to a new public factual release?", recommendedDecision: "Defer promotion until the three methodology decisions are explicitly decided, then generate a distinct approved release rather than mutating any candidate.", defaultReversibleAssumption: "retain_reviewer_candidate_exclude_from_publication", alternatives: ["Approve a corrected subset and regenerate every downstream artifact.", "Reject promotion while retaining reviewer-only research artifacts."], consequences: ["Approval after prerequisites enables public score and evidence UI work.", "Deferral leaves the deployed application and current published release unchanged and truthful."], confidence: "high", workCompletedWhileWaiting: ["Foundation v4, numeric v4, report v6, CA-31 terminal-chain closure, privacy minimization, and the public firewall are complete.", "No reviewer identity, approval timestamp, promotion, or public deployment was fabricated."], requiredEvidence: [], evidenceSha256s: [foundation.packageSha256, candidate.packageSha256, report.reportSha256], officialFilingSourceLockIds: [] },
  ];
  const decisions = highLevel.map(seal).sort((a, b) => order(a.decisionId, b.decisionId));
  const unsigned = { schema: "aipac-numeric-review-package-v4" as const, version: 4 as const, generatedAt: "2026-08-05T23:30:00.000Z" as const, sourceCutoff: "2026-08-04" as const, reviewerOnly: true as const, publicationEligible: false as const, review: { status: "proposed" as const, reviewer: null, reviewedAt: null }, inputs: { foundation: { fileSha256: FILES.foundation, packageSha256: foundation.packageSha256 }, candidate: { fileSha256: FILES.candidate, packageSha256: candidate.packageSha256 }, report: { fileSha256: FILES.report, reportSha256: report.reportSha256 } }, summary: { totalDecisions: 4 as const, mappingPrecedenceDecisions: 0 as const, methodologyDecisions: 3 as const, promotionDecisions: 1 as const, automaticallyResolvedIncumbentCases: 6 as const, automaticallyClosedMappingDecisions: 1 as const, safeDefault: "retain_reviewer_candidate_exclude_from_publication" as const }, automaticEvidenceClosures: foundation.automaticEvidenceClosures, decisions, decisionSetSha256: hash("dsa-seats:aipac-numeric-review-decision-set:v4\0", decisions) };
  return validateAipacNumericReviewPackageV4({ ...unsigned, packageSha256: hash("dsa-seats:aipac-numeric-review-package:v4\0", unsigned) });
}

export function validateAipacNumericReviewPackageV4(value: unknown): AipacNumericReviewPackageV4 {
  const parsed = aipacNumericReviewPackageV4Schema.parse(value), { packageSha256, ...unsigned } = parsed;
  if (packageSha256 !== hash("dsa-seats:aipac-numeric-review-package:v4\0", unsigned) || parsed.decisionSetSha256 !== hash("dsa-seats:aipac-numeric-review-decision-set:v4\0", parsed.decisions) || new Set(parsed.decisions.map((row) => row.decisionId)).size !== 4 || parsed.decisions.some((row) => row.decisionSha256 !== hash("dsa-seats:aipac-numeric-review-decision:v4\0", Object.fromEntries(Object.entries(row).filter(([key]) => key !== "decisionSha256"))) || row.resolution !== null || row.reviewer !== null || row.reviewedAt !== null)) throw new Error("AIPAC_NUMERIC_REVIEW_V4_INVARIANT_FAILED");
  const mapping = parsed.decisions.filter((row) => row.component === "candidate_committee_source_precedence"), closure = parsed.automaticEvidenceClosures[0];
  if (mapping.length !== 0 || closure.decisionId !== CLOSURE.decisionId || closure.receiptFileSha256 !== CLOSURE.receiptFileSha256 || closure.receiptPackageSha256 !== CLOSURE.receiptPackageSha256 || closure.evidenceSetSha256 !== CLOSURE.evidenceSetSha256 || closure.closureSha256 !== CLOSURE.closureSha256 || closure.reviewerAction || closure.reviewer !== null || closure.reviewedAt !== null || parsed.decisions.filter((row) => row.component === "publication_promotion").length !== 1) throw new Error("AIPAC_NUMERIC_REVIEW_V4_PENDING_DECISION_MISMATCH");
  return parsed;
}
