/* eslint-disable @typescript-eslint/no-explicit-any -- byte-pinned review parents */
import { createHash } from "node:crypto";
import { execFileSync } from "node:child_process";
import { readFileSync } from "node:fs";
import { z } from "zod";
import { aipacEvidenceSchema } from "../../domain/dsa-target-evaluator";
import { validateAipacEvidenceFoundationCandidateV3 } from "./aipac-evidence-foundation-candidate-v3";
import { aipacNumericBuildEvidence, aipacNumericParsePas2, aipacNumericSelectLatestDirect, aipacNumericTerminalFilings, type AipacNumericDirectRow, type AipacNumericFiling, type AipacNumericRelationship } from "./aipac-numeric-evidence-candidate";
import { canonicalJson } from "./aipac-proposed-packages";

const CYCLES = [2022, 2024, 2026] as const;
const SHA = z.string().regex(/^[a-f0-9]{64}$/);
const PARENTS = { closure: "7b9fd96d102a2367b67e21c969542a9bb2ae5a94a82997ea5baaabdb64d5a15b", foundation: "25dd9e55584e81586413d0d818c3ff6567c1cbdfeb093e1720bb6a36ae97b8dc", projection: "e1c2ab02cafb2ee438ec1a1c936f903e38cc19553d187b6b2d1dca55dc99d3ec", roster: "8ae9bb3423e6160d00b5395186c42550e28811b817a482650875d87de71079e1", sourceReceipts: "535247ffc7ab9879782ea77d5709b074413589efb774fb91b24a02c2146f88de" } as const;
const PAS2: Record<number, string> = { 2022: "a62d484e952b031d65aa2c712c25268f499c6f333e9e9cfcb40cf378056b30af", 2024: "81520f5d1371f2e89beecd148193e55fdcff7f1dfa6b3a63770e21b928bcbfaf", 2026: "ed0b8a1a498a6633870fe3dd38cd16a6325bcc9aec0102d0cee776cf6a17e240" };
const PACKAGE_SHA256 = "e30956852e24f9cdd9a95f8d978b3c3bdbd5978eae293f6e5aa5c0d57f04eeb8";
const SEAT_SET_SHA256 = "61af3ac2f8b765a04284aefd08d53d185583985870e2f0c9085bb854931645df";
const EVIDENCE_SET_SHA256 = "f328eb0cb02d3452526d04e723c6d833c4732fb38eea1e36b90911aa88b5ca9b";
const digest = (domain: string, value: unknown) => createHash("sha256").update(domain).update(canonicalJson(value)).digest("hex");
const bytesHash = (bytes: Uint8Array) => createHash("sha256").update(bytes).digest("hex");
const order = (a: string, b: string) => Buffer.compare(Buffer.from(a), Buffer.from(b));
const cell = z.strictObject({ cycleYear: z.union([z.literal(2022), z.literal(2024), z.literal(2026)]), channel: z.enum(["direct_aipac_pac", "independent_udp"]), disposition: z.enum(["complete_no_matching_evidence", "complete_matching_evidence", "blocked_pending_mapping", "blocked_invalid_origin", "not_applicable_no_house_candidacy"]), sourceSnapshotIds: z.array(z.string()).min(1), sourceArtifactSha256s: z.array(SHA).min(1), basisRelationshipSha256s: z.array(SHA), basisDispositionSha256s: z.array(SHA), qualifyingEvidenceCount: z.number().int().nonnegative() });
const receipt = z.strictObject({ evidenceSha256: SHA, transactionReceipts: z.array(z.object({ transactionIdentitySha256: SHA, sourceRecordIdentitySha256s: z.array(SHA).min(1).max(2), corroboration: z.enum(["single_terminal_record", "exact_f24_notice_f3x_non_notice"]) })).min(1), selectionRule: z.enum(["pas2_latest_terminal_transaction_revision", "schedule_e_terminal_transaction_or_exact_f24_f3x_corroboration"]) });
const seat = z.strictObject({ seatCycleId: z.string(), incumbentCandidateId: z.string().nullable(), status: z.enum(["complete", "partially_blocked_pending_mapping", "partially_blocked_invalid_origin"]), resolutionContext: z.strictObject({ pendingResolutionSha256s: z.array(SHA), pendingCycleYears: z.array(z.number().int()), notApplicableCycleYears: z.array(z.number().int()), invalidOriginDispositionSha256s: z.array(SHA) }), coverage: z.array(cell).length(6), evidence: z.array(aipacEvidenceSchema), evidenceReceipts: z.array(receipt), seatSha256: SHA });
export const aipacNumericEvidenceCandidateV3Schema = z.strictObject({ schema: z.literal("aipac-numeric-evidence-candidate-v3"), version: z.literal(3), generatedAt: z.literal("2026-08-05T21:30:00.000Z"), sourceCutoff: z.literal("2026-08-04"), reviewerOnly: z.literal(true), publicationEligible: z.literal(false), status: z.literal("automatic_numeric_candidate_with_cycle_resolution_firewall"), defaultUse: z.literal("use_in_reviewer_only_evaluation_exclude_from_publication"), inputs: z.strictObject({ closureFileSha256: z.literal(PARENTS.closure), foundationFileSha256: z.literal(PARENTS.foundation), projectionFileSha256: z.literal(PARENTS.projection), rosterFileSha256: z.literal(PARENTS.roster), sourceReceiptsFileSha256: z.literal(PARENTS.sourceReceipts), pas2ZipSha256ByCycle: z.strictObject({ "2022": z.literal(PAS2[2022]), "2024": z.literal(PAS2[2024]), "2026": z.literal(PAS2[2026]) }) }), summary: z.strictObject({ targetSeats: z.literal(212), completeSeats: z.literal(211), partiallyBlockedPendingSeats: z.literal(1), partiallyBlockedInvalidOriginSeats: z.literal(0), evidenceRows: z.literal(278), directEvidenceRows: z.literal(259), independentEvidenceRows: z.literal(19), seatsWithEvidence: z.literal(127), coverageCells: z.literal(1272), completeMatchingCoverageCells: z.literal(273), completeZeroCoverageCells: z.literal(993), blockedCoverageCells: z.literal(2), notApplicableCoverageCells: z.literal(4) }), derivation: z.strictObject({ seatSetSha256: z.literal(SEAT_SET_SHA256), evidenceSetSha256: z.literal(EVIDENCE_SET_SHA256) }), seats: z.array(seat).length(212), packageSha256: z.literal(PACKAGE_SHA256) });
export type AipacNumericEvidenceCandidateV3 = z.infer<typeof aipacNumericEvidenceCandidateV3Schema>;
export type NumericCandidateV3Paths = Readonly<{ closure: string; foundation: string; projection: string; roster: string; sourceReceipts: string; pas2ZipByCycle: Readonly<Record<number, string>> }>;

export function buildAipacNumericEvidenceCandidateV3FromFiles(paths: NumericCandidateV3Paths): AipacNumericEvidenceCandidateV3 {
  const raw = { closure: readFileSync(paths.closure), foundation: readFileSync(paths.foundation), projection: readFileSync(paths.projection), roster: readFileSync(paths.roster), sourceReceipts: readFileSync(paths.sourceReceipts) };
  for (const [key, expected] of Object.entries(PARENTS)) if (bytesHash(raw[key as keyof typeof raw]) !== expected) throw new Error(`AIPAC_NUMERIC_V3_PARENT_HASH_MISMATCH:${key}`);
  const closure: any = JSON.parse(raw.closure.toString()), foundation = validateAipacEvidenceFoundationCandidateV3(JSON.parse(raw.foundation.toString())), projection: any = JSON.parse(raw.projection.toString()), roster: any = JSON.parse(raw.roster.toString()), sources: any = JSON.parse(raw.sourceReceipts.toString());
  const filing = (id: string) => closure.filingLedgers.find((row: any) => row.committeeId === id)?.filings as AipacNumericFiling[] | undefined;
  const a = filing("C00797670"), u = filing("C00799031"); if (!a || !u || closure.sourceCutoff !== "2026-08-04" || closure.scheduleE.records.length !== 1145) throw new Error("AIPAC_NUMERIC_V3_CLOSURE_INVALID");
  const direct: AipacNumericDirectRow[] = []; for (const cycleYear of CYCLES) { const bytes = readFileSync(paths.pas2ZipByCycle[cycleYear]!); if (bytesHash(bytes) !== PAS2[cycleYear]) throw new Error(`AIPAC_NUMERIC_V3_PAS2_HASH_MISMATCH:${cycleYear}`); direct.push(...aipacNumericParsePas2(execFileSync("unzip", ["-p", paths.pas2ZipByCycle[cycleYear]!, "itpas2.txt"], { encoding: "utf8", maxBuffer: 256 * 1024 * 1024 }), cycleYear, aipacNumericTerminalFilings(a, "AIPAC_V3"))); }
  const udp = aipacNumericTerminalFilings(u, "UDP_V3");
  const effective = foundation.relationships.flatMap((wrapper: any) => {
    if (wrapper.resolution.kind === "inherited" || wrapper.resolution.kind === "challenger_auto_accepted") return wrapper.resolution.evaluatorUse === "reviewer_only_candidate" ? [{ relationship: { ...wrapper.sourceRelationship, evaluatorUse: "reviewer_only_candidate" }, wrapper, cycles: wrapper.sourceRelationship.effectiveCycleYears, dispositionSha256s: [] as string[] }] : [];
    if (wrapper.resolution.kind !== "incumbent_evidence_disposition_v2") return [];
    const cycles = wrapper.resolution.disposition.cycleDispositions.filter((value: any) => value.evaluatorUse === "reviewer_only_candidate");
    return cycles.length ? [{ relationship: { ...wrapper.sourceRelationship, candidateId: wrapper.resolution.effectiveCandidateId, effectiveCycleYears: cycles.map((value: any) => value.cycleYear), authorizedCommitteeIdsByCycle: cycles.map((value: any) => ({ cycleYear: value.cycleYear, committeeIds: value.committeeIds, principalCommitteeCrosscheck: "matched" })), evaluatorUse: "reviewer_only_candidate" }, wrapper, cycles: cycles.map((value: any) => value.cycleYear), dispositionSha256s: [wrapper.resolution.disposition.dispositionSha256] }] : [];
  });
  const evidenceBySeat = aipacNumericBuildEvidence(aipacNumericSelectLatestDirect(direct), closure.scheduleE.records, effective.map((value: any) => value.relationship) as AipacNumericRelationship[], udp, ["aipac-politics", "fec-aipac-pac", "fec-udp"]);
  const receiptByCycle = new Map(sources.sources.filter((row: any) => row.channel === "aipac_pac_pas2").map((row: any) => [row.cycleYear, row]));
  if (projection.seats.length !== 212 || new Set(roster.rows.map((row: any) => row.seatCycleId)).size !== 212) throw new Error("AIPAC_NUMERIC_V3_SEAT_UNIVERSE_MISMATCH");
  const seats = projection.seats.map((p: any) => {
    const seatCycleId = p.seatCycleId, wrappers = foundation.relationships.filter((row: any) => row.sourceRelationship.seatCycleId === seatCycleId), items = [...(evidenceBySeat.get(seatCycleId) ?? [])].sort((x: any, y: any) => x.evidence.cycleYear - y.evidence.cycleYear || order(x.evidence.kind, y.evidence.kind));
    const pending = wrappers.flatMap((row: any) => row.resolution.kind === "incumbent_evidence_disposition_v2" ? row.resolution.disposition.cycleDispositions.filter((c: any) => c.evaluatorUse === "excluded_pending_review").map((c: any) => ({ cycle: c.cycleYear, sha: row.resolution.disposition.dispositionSha256 })) : []);
    const na = wrappers.flatMap((row: any) => row.resolution.kind === "incumbent_evidence_disposition_v2" ? row.resolution.disposition.cycleDispositions.filter((c: any) => c.evaluatorUse === "not_applicable_no_house_candidacy").map((c: any) => c.cycleYear) : []);
    const invalid = wrappers.filter((row: any) => row.resolution.kind === "challenger_auto_rejected").map((row: any) => row.resolution.disposition.dispositionSha256);
    const rawEvidence = items.map((x: any) => x.evidence), rawReceipts = items.map((x: any) => x.receipt);
    const coverage = CYCLES.flatMap((cycleYear) => (["direct_aipac_pac", "independent_udp"] as const).map((channel) => { const matching = rawEvidence.map((row: any, index: number) => ({ row, index })).filter(({ row }: any) => row.cycleYear === cycleYear && (channel === "direct_aipac_pac" ? row.kind === "direct_contribution" : row.kind !== "direct_contribution")); const basis = effective.filter((x: any) => x.relationship.seatCycleId === seatCycleId && x.cycles.includes(cycleYear)); const disposition = pending.some((x: any) => x.cycle === cycleYear) ? "blocked_pending_mapping" : na.includes(cycleYear) ? "not_applicable_no_house_candidacy" : matching.length ? "complete_matching_evidence" : "complete_no_matching_evidence"; const source: any = receiptByCycle.get(cycleYear); return cell.parse({ cycleYear, channel, disposition, sourceSnapshotIds: channel === "direct_aipac_pac" ? [source.id, `aipac-pac-filing-ledger-${cycleYear}`] : [`udp-schedule-e-${cycleYear}-20260804`, `udp-filing-ledger-${cycleYear}`], sourceArtifactSha256s: channel === "direct_aipac_pac" ? [source.sha256, PARENTS.closure] : [PARENTS.closure], basisRelationshipSha256s: basis.map((x: any) => x.wrapper.relationshipSha256).sort(order), basisDispositionSha256s: basis.flatMap((x: any) => x.dispositionSha256s).sort(order), qualifyingEvidenceCount: disposition.startsWith("complete_") ? matching.length : 0 }); }));
    const allowed = new Set<number>(); for (const c of coverage.filter((c) => c.disposition === "complete_matching_evidence")) rawEvidence.forEach((row: any, index: number) => { if (row.cycleYear === c.cycleYear && (c.channel === "direct_aipac_pac" ? row.kind === "direct_contribution" : row.kind !== "direct_contribution")) allowed.add(index); });
    const evidence = rawEvidence.filter((_: any, index: number) => allowed.has(index)), evidenceReceipts = rawReceipts.filter((_: any, index: number) => allowed.has(index)); const status = pending.length ? "partially_blocked_pending_mapping" as const : invalid.length && coverage.some((c) => c.disposition === "blocked_invalid_origin") ? "partially_blocked_invalid_origin" as const : "complete" as const;
    const incumbentCandidateId = effective.find((x: any) => x.relationship.seatCycleId === seatCycleId && x.relationship.relationship === "incumbent")?.relationship.candidateId ?? null;
    const unsigned = { seatCycleId, incumbentCandidateId, status, resolutionContext: { pendingResolutionSha256s: pending.map((x: any) => x.sha).sort(order), pendingCycleYears: pending.map((x: any) => x.cycle).sort(), notApplicableCycleYears: [...new Set(na)].sort(), invalidOriginDispositionSha256s: invalid.sort(order) }, coverage, evidence, evidenceReceipts }; return seat.parse({ ...unsigned, seatSha256: digest("dsa-seats:aipac-numeric-seat:v3\0", unsigned) });
  }).sort((a: any, b: any) => order(a.seatCycleId, b.seatCycleId));
  const evidence = seats.flatMap((x: any) => x.evidence), cells = seats.flatMap((x: any) => x.coverage);
  const unsigned = { schema: "aipac-numeric-evidence-candidate-v3" as const, version: 3 as const, generatedAt: "2026-08-05T21:30:00.000Z" as const, sourceCutoff: "2026-08-04" as const, reviewerOnly: true as const, publicationEligible: false as const, status: "automatic_numeric_candidate_with_cycle_resolution_firewall" as const, defaultUse: "use_in_reviewer_only_evaluation_exclude_from_publication" as const, inputs: { closureFileSha256: PARENTS.closure, foundationFileSha256: PARENTS.foundation, projectionFileSha256: PARENTS.projection, rosterFileSha256: PARENTS.roster, sourceReceiptsFileSha256: PARENTS.sourceReceipts, pas2ZipSha256ByCycle: { "2022": PAS2[2022], "2024": PAS2[2024], "2026": PAS2[2026] } }, summary: { targetSeats: 212 as const, completeSeats: seats.filter((x: any) => x.status === "complete").length, partiallyBlockedPendingSeats: seats.filter((x: any) => x.status === "partially_blocked_pending_mapping").length, partiallyBlockedInvalidOriginSeats: seats.filter((x: any) => x.status === "partially_blocked_invalid_origin").length, evidenceRows: evidence.length, directEvidenceRows: evidence.filter((x: any) => x.kind === "direct_contribution").length, independentEvidenceRows: evidence.filter((x: any) => x.kind !== "direct_contribution").length, seatsWithEvidence: seats.filter((x: any) => x.evidence.length).length, coverageCells: cells.length, completeMatchingCoverageCells: cells.filter((x: any) => x.disposition === "complete_matching_evidence").length, completeZeroCoverageCells: cells.filter((x: any) => x.disposition === "complete_no_matching_evidence").length, blockedCoverageCells: cells.filter((x: any) => x.disposition === "blocked_pending_mapping" || x.disposition === "blocked_invalid_origin").length, notApplicableCoverageCells: cells.filter((x: any) => x.disposition === "not_applicable_no_house_candidacy").length }, derivation: { seatSetSha256: digest("dsa-seats:aipac-numeric-seat-set:v3\0", seats), evidenceSetSha256: digest("dsa-seats:aipac-numeric-evidence-set:v3\0", evidence) }, seats };
  return validateAipacNumericEvidenceCandidateV3({ ...unsigned, packageSha256: digest("dsa-seats:aipac-numeric-evidence-candidate:v3\0", unsigned) });
}
export function validateAipacNumericEvidenceCandidateV3(value: unknown): AipacNumericEvidenceCandidateV3 { const parsed = aipacNumericEvidenceCandidateV3Schema.parse(value); const { packageSha256, ...unsigned } = parsed; if (packageSha256 !== digest("dsa-seats:aipac-numeric-evidence-candidate:v3\0", unsigned)) throw new Error("AIPAC_NUMERIC_V3_PACKAGE_HASH_MISMATCH"); const seen = new Set<string>(); for (const row of parsed.seats) { const { seatSha256, ...u } = row; if (seatSha256 !== digest("dsa-seats:aipac-numeric-seat:v3\0", u)) throw new Error("AIPAC_NUMERIC_V3_SEAT_HASH_MISMATCH"); for (const c of row.coverage) { const key = `${c.cycleYear}:${c.channel}`; if (seen.has(`${row.seatCycleId}:${key}`)) throw new Error("AIPAC_NUMERIC_V3_COVERAGE_KEY_DUPLICATE"); seen.add(`${row.seatCycleId}:${key}`); if ((c.disposition === "blocked_pending_mapping" || c.disposition === "not_applicable_no_house_candidacy") && c.qualifyingEvidenceCount !== 0) throw new Error("AIPAC_NUMERIC_V3_TERMINAL_COUNT_INVALID"); } if (row.status === "complete" && row.coverage.some((c) => c.disposition.startsWith("blocked_"))) throw new Error("AIPAC_NUMERIC_V3_COMPLETE_BLOCKED"); }
  const evidence = parsed.seats.flatMap((x) => x.evidence); for (const row of parsed.seats) { if (row.evidence.length !== row.evidenceReceipts.length) throw new Error("AIPAC_NUMERIC_V3_RECEIPT_LENGTH_MISMATCH"); for (let index = 0; index < row.evidence.length; index++) { const e = row.evidence[index]!, r = row.evidenceReceipts[index]!, tx = r.transactionReceipts.map((x) => x.transactionIdentitySha256), sourceRows = r.transactionReceipts.flatMap((x) => x.sourceRecordIdentitySha256s); if (!r || r.evidenceSha256 !== digest("dsa-seats:aipac-evaluator-evidence:v1\0", e) || r.selectionRule !== (e.kind === "direct_contribution" ? "pas2_latest_terminal_transaction_revision" : "schedule_e_terminal_transaction_or_exact_f24_f3x_corroboration") || canonicalJson(tx) !== canonicalJson(e.sourceTransactionIdSha256s) || new Set(tx).size !== tx.length || new Set(sourceRows).size !== sourceRows.length || r.transactionReceipts.some((x) => e.kind === "direct_contribution" ? x.corroboration !== "single_terminal_record" || x.sourceRecordIdentitySha256s.length !== 1 : x.corroboration === "single_terminal_record" ? x.sourceRecordIdentitySha256s.length !== 1 : x.sourceRecordIdentitySha256s.length !== 2)) throw new Error("AIPAC_NUMERIC_V3_RECEIPT_MISMATCH"); } } if (parsed.derivation.seatSetSha256 !== digest("dsa-seats:aipac-numeric-seat-set:v3\0", parsed.seats) || parsed.derivation.evidenceSetSha256 !== digest("dsa-seats:aipac-numeric-evidence-set:v3\0", evidence)) throw new Error("AIPAC_NUMERIC_V3_DERIVATION_MISMATCH"); const ca = parsed.seats.find((x) => x.seatCycleId === "seat_house_ca_31_current")!, ma = parsed.seats.find((x) => x.seatCycleId === "seat_house_ma_06_current")!, md = parsed.seats.find((x) => x.seatCycleId === "seat_house_md_04_current")!, nh = parsed.seats.find((x) => x.seatCycleId === "seat_house_nh_01_current")!; if (ca.status !== "partially_blocked_pending_mapping" || ca.evidence.length || ca.coverage.filter((c) => c.disposition === "blocked_pending_mapping").length !== 2 || ca.coverage.some((c) => c.disposition === "blocked_pending_mapping" && c.cycleYear !== 2024)) throw new Error("AIPAC_NUMERIC_V3_CA31_MATRIX"); for (const row of [ma, nh]) if (row.coverage.filter((c) => c.disposition === "not_applicable_no_house_candidacy").length !== 2 || row.coverage.some((c) => c.disposition === "not_applicable_no_house_candidacy" && c.cycleYear !== 2026)) throw new Error("AIPAC_NUMERIC_V3_OFFICE_CHANGE_MATRIX"); if (md.incumbentCandidateId !== "H2MD04232" || canonicalJson(md.evidence.map((x) => x.netAmount)) !== canonicalJson([4258735.79]) || canonicalJson(ma.evidence.map((x) => x.netAmount)) !== canonicalJson([5000]) || canonicalJson(nh.evidence.map((x) => x.netAmount)) !== canonicalJson([2100, 10003])) throw new Error("AIPAC_NUMERIC_V3_AFFECTED_EVIDENCE_MATRIX"); return parsed; }
