import { createHash } from "node:crypto";
import { z } from "zod";
import { aipacEvidenceFoundationCandidateV3Schema, validateAipacEvidenceFoundationCandidateV3 } from "./aipac-evidence-foundation-candidate-v3";
import { aipacIncumbentResolutionDispositionsV3Schema, aipacIncumbentResolutionSemanticsSha256V3, validateAipacIncumbentResolutionDispositionsV3 } from "./aipac-incumbent-resolution-dispositions-v3";
import { canonicalJson } from "./aipac-proposed-packages";

const SHA = z.string().regex(/^[a-f0-9]{64}$/);
const INPUTS = { foundationFile: "25dd9e55584e81586413d0d818c3ff6567c1cbdfeb093e1720bb6a36ae97b8dc", foundationPackage: "812a0cf887dff3b268e0fdcc6800eab446e9bd20926508232f1a4c2b4b41ba0f", dispositionsFile: "a4cb0f8e8f7ac43307533c0c08e8f440d83ab7d71574bbbde946ad2ca6b3a973", dispositionsPackage: "a197a79bec4adab061f407f18d2cca2aa1b5783c18b2c343f4d91138915daab6", closureSha256: "a5a5298e3204443b1c6516e7de6537e684cfd155a48c3d2fda0ac6ef6da854ee", receiptFileSha256: "1c3d46fcfc76a33ed1fca469cbefb9924622a2245f266fc6394850845c9b7198", receiptPackageSha256: "8201a54aa4894163bda0a24b214c10166ade3fe4fcbe31b6e0667d7094b11cee", evidenceSetSha256: "539ed96bbfa5e6058d5a3f9085b9d3d804616c3615c9613b265f6952228fe3c8" } as const;
const sourceRelationship = aipacEvidenceFoundationCandidateV3Schema.shape.relationships.element.shape.sourceRelationship;
const inheritedResolution = aipacEvidenceFoundationCandidateV3Schema.shape.relationships.element.shape.resolution;
const disposition = aipacIncumbentResolutionDispositionsV3Schema.shape.dispositions.element;
const incumbentResolution = z.strictObject({ kind: z.literal("incumbent_evidence_disposition_v3"), evaluatorUse: z.literal("reviewer_only_candidate_with_cycle_exclusions"), effectiveCandidateId: z.string().regex(/^H[A-Z0-9]{8}$/), disposition });
const relationship = z.strictObject({ sourceRelationship, resolution: z.union([inheritedResolution, incumbentResolution]), relationshipSha256: SHA });
export const aipacEvidenceFoundationCandidateV4Schema = z.strictObject({
  schema: z.literal("aipac-evidence-foundation-candidate-v4"), version: z.literal(4), generatedAt: z.literal("2026-08-05T22:45:00.000Z"), sourceCutoff: z.literal("2026-08-04"), reviewerOnly: z.literal(true), publicationEligible: z.literal(false), status: z.literal("automatic_cycle_resolution_candidate_closure_no_mapping_decisions"), defaultUse: z.literal("use_cycle_eligible_relationships_in_next_reviewer_only_numeric_candidate_exclude_from_publication"),
  inputs: z.strictObject({ foundationV3: z.strictObject({ sourceLockId: z.literal("aipac-evidence-foundation-candidate-v3"), fileSha256: z.literal(INPUTS.foundationFile), packageSha256: z.literal(INPUTS.foundationPackage) }), incumbentDispositionsV3: z.strictObject({ sourceLockId: z.literal("aipac-incumbent-resolution-dispositions-v3"), fileSha256: z.literal(INPUTS.dispositionsFile), packageSha256: z.literal(INPUTS.dispositionsPackage) }) }),
  policy: z.strictObject({ incumbentCycles: z.literal("apply_exact_or_explicitly_derived_cycle_dispositions_without_claiming_human_approval"), identifierAliases: z.literal("preserve_H8_H4_cross_surface_identifier_discrepancy"), officeChanges: z.literal("retain_not_applicable_house_cycles_never_zero"), publication: z.literal("separate_methodology_review_and_release_promotion_required") }),
  summary: z.strictObject({ targetSeats: z.literal(212), inputRelationships: z.literal(229), inheritedDirectRelationships: z.literal(206), inheritedInferredRelationships: z.literal(15), challengerAutoAcceptedRelationships: z.literal(1), challengerRejectedInvalidOrigins: z.literal(1), incumbentDispositionRelationships: z.literal(6), usableReviewerCandidateRelationships: z.literal(228), autoUsableIncumbentHouseCycles: z.literal(10), autoNotApplicableHouseCycles: z.literal(2), pendingIncumbentHouseCycles: z.literal(0), remainingMappingDecisions: z.literal(0), automaticallyClosedMappingDecisions: z.literal(1), numericEvidenceRows: z.literal(0), evaluatorRouteSelections: z.literal(0) }),
  relationships: z.array(relationship).length(229), automaticEvidenceClosures: aipacIncumbentResolutionDispositionsV3Schema.shape.automaticEvidenceClosures, remainingDecisionQueue: z.tuple([]), derivation: z.strictObject({ relationshipSetSha256: SHA, automaticClosureSetSha256: SHA, remainingDecisionSetSha256: SHA, incumbentSemanticsSha256: SHA }), review: z.strictObject({ status: z.literal("automatic_dispositions_no_mapping_decisions"), reviewer: z.null(), reviewedAt: z.null() }), packageSha256: SHA,
});
export type AipacEvidenceFoundationCandidateV4 = z.infer<typeof aipacEvidenceFoundationCandidateV4Schema>;
const hash = (domain: string, value: unknown): string => createHash("sha256").update(domain).update(canonicalJson(value)).digest("hex");
const order = (a: string, b: string): number => Buffer.compare(Buffer.from(a), Buffer.from(b));
export function buildAipacEvidenceFoundationCandidateV4(input: Readonly<{ foundationV3: unknown; foundationV3FileSha256: string; dispositionsV3: unknown; dispositionsV3FileSha256: string }>): AipacEvidenceFoundationCandidateV4 {
  if (input.foundationV3FileSha256 !== INPUTS.foundationFile || input.dispositionsV3FileSha256 !== INPUTS.dispositionsFile) throw new Error("AIPAC_FOUNDATION_V4_INPUT_FILE_HASH_MISMATCH");
  const foundation = validateAipacEvidenceFoundationCandidateV3(input.foundationV3), dispositions = validateAipacIncumbentResolutionDispositionsV3(input.dispositionsV3);
  if (foundation.packageSha256 !== INPUTS.foundationPackage || dispositions.packageSha256 !== INPUTS.dispositionsPackage) throw new Error("AIPAC_FOUNDATION_V4_INPUT_PACKAGE_HASH_MISMATCH");
  const byDecision = new Map(dispositions.dispositions.map((row) => [row.sourceDecisionId, row]));
  const relationships = foundation.relationships.map((row) => { const replacement = row.resolution.kind === "incumbent_evidence_disposition_v2" ? byDecision.get(row.sourceRelationship.sourceDecisionId) : undefined; if (row.resolution.kind === "incumbent_evidence_disposition_v2" && !replacement) throw new Error("AIPAC_FOUNDATION_V4_INCUMBENT_DISPOSITION_MISSING"); const resolution = replacement ? { kind: "incumbent_evidence_disposition_v3" as const, evaluatorUse: "reviewer_only_candidate_with_cycle_exclusions" as const, effectiveCandidateId: replacement.canonicalCandidateId, disposition: replacement } : row.resolution; const unsigned = { sourceRelationship: row.sourceRelationship, resolution }; return relationship.parse({ ...unsigned, relationshipSha256: hash("dsa-seats:aipac-foundation-relationship:v4\0", unsigned) }); }).sort((a, b) => order(a.sourceRelationship.sourceDecisionId, b.sourceRelationship.sourceDecisionId));
  const remainingDecisionQueue = [] as const;
  const unsigned = { schema: "aipac-evidence-foundation-candidate-v4", version: 4, generatedAt: "2026-08-05T22:45:00.000Z", sourceCutoff: "2026-08-04", reviewerOnly: true, publicationEligible: false, status: "automatic_cycle_resolution_candidate_closure_no_mapping_decisions", defaultUse: "use_cycle_eligible_relationships_in_next_reviewer_only_numeric_candidate_exclude_from_publication", inputs: { foundationV3: { sourceLockId: "aipac-evidence-foundation-candidate-v3", fileSha256: INPUTS.foundationFile, packageSha256: foundation.packageSha256 }, incumbentDispositionsV3: { sourceLockId: "aipac-incumbent-resolution-dispositions-v3", fileSha256: INPUTS.dispositionsFile, packageSha256: dispositions.packageSha256 } }, policy: { incumbentCycles: "apply_exact_or_explicitly_derived_cycle_dispositions_without_claiming_human_approval", identifierAliases: "preserve_H8_H4_cross_surface_identifier_discrepancy", officeChanges: "retain_not_applicable_house_cycles_never_zero", publication: "separate_methodology_review_and_release_promotion_required" }, summary: { targetSeats: 212, inputRelationships: 229, inheritedDirectRelationships: 206, inheritedInferredRelationships: 15, challengerAutoAcceptedRelationships: 1, challengerRejectedInvalidOrigins: 1, incumbentDispositionRelationships: 6, usableReviewerCandidateRelationships: 228, autoUsableIncumbentHouseCycles: 10, autoNotApplicableHouseCycles: 2, pendingIncumbentHouseCycles: 0, remainingMappingDecisions: 0, automaticallyClosedMappingDecisions: 1, numericEvidenceRows: 0, evaluatorRouteSelections: 0 }, relationships, automaticEvidenceClosures: dispositions.automaticEvidenceClosures, remainingDecisionQueue, derivation: { relationshipSetSha256: hash("dsa-seats:aipac-foundation-relationship-set:v4\0", relationships), automaticClosureSetSha256: dispositions.derivation.automaticClosureSetSha256, remainingDecisionSetSha256: hash("dsa-seats:aipac-incumbent-resolution-decision-set:v3\0", remainingDecisionQueue), incumbentSemanticsSha256: dispositions.derivation.semanticsSha256 }, review: { status: "automatic_dispositions_no_mapping_decisions", reviewer: null, reviewedAt: null } } as const;
  return validateAipacEvidenceFoundationCandidateV4({ ...unsigned, packageSha256: hash("dsa-seats:aipac-evidence-foundation-candidate:v4\0", unsigned) });
}
export function validateAipacEvidenceFoundationCandidateV4(value: unknown): AipacEvidenceFoundationCandidateV4 { const parsed = aipacEvidenceFoundationCandidateV4Schema.parse(value), { packageSha256, ...unsigned } = parsed; if (packageSha256 !== hash("dsa-seats:aipac-evidence-foundation-candidate:v4\0", unsigned) || parsed.derivation.relationshipSetSha256 !== hash("dsa-seats:aipac-foundation-relationship-set:v4\0", parsed.relationships) || parsed.derivation.automaticClosureSetSha256 !== hash("dsa-seats:aipac-incumbent-automatic-closure-set:v3\0", parsed.automaticEvidenceClosures) || parsed.derivation.remainingDecisionSetSha256 !== hash("dsa-seats:aipac-incumbent-resolution-decision-set:v3\0", parsed.remainingDecisionQueue)) throw new Error("AIPAC_FOUNDATION_V4_HASH_MISMATCH"); const incumbents = parsed.relationships.filter((row): row is typeof row & { resolution: z.infer<typeof incumbentResolution> } => row.resolution.kind === "incumbent_evidence_disposition_v3"); if (incumbents.length !== 6 || parsed.relationships.some((row) => row.resolution.kind === "incumbent_evidence_disposition_v2") || aipacIncumbentResolutionSemanticsSha256V3(incumbents.map((row) => row.resolution.disposition)) !== parsed.derivation.incumbentSemanticsSha256 || parsed.remainingDecisionQueue.length !== 0) throw new Error("AIPAC_FOUNDATION_V4_UNIVERSE_MISMATCH"); const ca = incumbents.find((row) => row.sourceRelationship.seatCycleId === "seat_house_ca_31_current"), closure = parsed.automaticEvidenceClosures[0]; if (!ca || ca.resolution.disposition.alternateCandidateIds.length !== 0 || ca.resolution.disposition.identityDispositionScope !== "canonical_roster_identity_only" || ca.resolution.disposition.identifierMappingResolved || !ca.resolution.disposition.unresolvedIdentifierConflict || canonicalJson(ca.resolution.disposition.conflictingSignedFormCandidateIds) !== canonicalJson(["H4CA31170"]) || ca.resolution.disposition.cycleDispositions.find((row) => row.cycleYear === 2024)?.evaluatorUse !== "reviewer_only_candidate" || closure.receiptFileSha256 !== INPUTS.receiptFileSha256 || closure.receiptPackageSha256 !== INPUTS.receiptPackageSha256 || closure.evidenceSetSha256 !== INPUTS.evidenceSetSha256 || closure.closureSha256 !== INPUTS.closureSha256) throw new Error("AIPAC_FOUNDATION_V4_CA31_MISMATCH"); for (const row of parsed.relationships) { const { relationshipSha256, ...rowUnsigned } = row; if (relationshipSha256 !== hash("dsa-seats:aipac-foundation-relationship:v4\0", rowUnsigned)) throw new Error("AIPAC_FOUNDATION_V4_RELATIONSHIP_HASH_MISMATCH"); } return parsed; }
