import { createHash } from "node:crypto";
import { z } from "zod";
import { validateDsaTargetReviewReportV5 } from "../../domain/dsa-target-review-report-v5";
import { validateAipacEvidenceFoundationCandidateV3 } from "./aipac-evidence-foundation-candidate-v3";
import { validateAipacNumericEvidenceCandidateV3 } from "./aipac-numeric-evidence-candidate-v3";
import { canonicalJson } from "./aipac-proposed-packages";

const SHA = z.string().regex(/^[a-f0-9]{64}$/);
const FILES = { foundation: "25dd9e55584e81586413d0d818c3ff6567c1cbdfeb093e1720bb6a36ae97b8dc", candidate: "a2bf17ef05d02b4f35a9bcc5d9da602be14706068e1c5e6f0f8311bf5deb96e0", report: "c12fa569c15e6752f7fd788331ebd7753963f88616956db4429f5b65fd459ee5" } as const;
const PACKAGES = { foundation: "812a0cf887dff3b268e0fdcc6800eab446e9bd20926508232f1a4c2b4b41ba0f", candidate: "e30956852e24f9cdd9a95f8d978b3c3bdbd5978eae293f6e5aa5c0d57f04eeb8", report: "10829503f5982014abcba4d8b0eb6238a7710ba273f14f9579324f0493b3509f" } as const;
const DECISION_SET_SHA256 = "c01848a1a3df8785e63d3635ce0ca84e66ad1e162a34543d973a3b3700907364";
const PACKAGE_SHA256 = "bec26cf8af5aa673d6750f2da791b3e715f1d3a3d8f775b3b9d62aba33337d49";
const decision = z.strictObject({
  decisionId: z.string().min(1), component: z.enum(["candidate_committee_source_precedence", "numeric_lineage_methodology", "inferred_udp_relationships", "scoring_model", "publication_promotion"]), affectedSeatCycleId: z.string().min(1).nullable(), affectedCycleYear: z.number().int().nullable(),
  question: z.string().min(1), recommendedDecision: z.string().min(1), defaultReversibleAssumption: z.string().min(1), alternatives: z.array(z.string().min(1)).min(1), consequences: z.array(z.string().min(1)).min(1), confidence: z.enum(["high", "medium", "high_but_insufficiently_closed"]), blocksPublication: z.literal(true), blocksOtherWork: z.literal(false), workCompletedWhileWaiting: z.array(z.string().min(1)).min(1), requiredEvidence: z.array(z.string().min(1)), evidenceSha256s: z.array(SHA).min(1), officialFilingSourceLockIds: z.array(z.string().min(1)), resolution: z.null(), reviewer: z.null(), reviewedAt: z.null(), decisionSha256: SHA,
});
export const aipacNumericReviewPackageV3Schema = z.strictObject({ schema: z.literal("aipac-numeric-review-package-v3"), version: z.literal(3), generatedAt: z.literal("2026-08-05T22:00:00.000Z"), sourceCutoff: z.literal("2026-08-04"), reviewerOnly: z.literal(true), publicationEligible: z.literal(false), review: z.strictObject({ status: z.literal("proposed"), reviewer: z.null(), reviewedAt: z.null() }), inputs: z.strictObject({ foundation: z.strictObject({ fileSha256: z.literal(FILES.foundation), packageSha256: z.literal(PACKAGES.foundation) }), candidate: z.strictObject({ fileSha256: z.literal(FILES.candidate), packageSha256: z.literal(PACKAGES.candidate) }), report: z.strictObject({ fileSha256: z.literal(FILES.report), reportSha256: z.literal(PACKAGES.report) }) }), summary: z.strictObject({ totalDecisions: z.literal(5), mappingPrecedenceDecisions: z.literal(1), methodologyDecisions: z.literal(3), promotionDecisions: z.literal(1), automaticallyResolvedIncumbentCases: z.literal(5), safeDefault: z.literal("retain_reviewer_candidate_exclude_from_publication") }), decisions: z.array(decision).length(5), decisionSetSha256: SHA, packageSha256: SHA });
export type AipacNumericReviewPackageV3 = z.infer<typeof aipacNumericReviewPackageV3Schema>;
const hash = (domain: string, value: unknown): string => createHash("sha256").update(domain).update(canonicalJson(value)).digest("hex");
const order = (a: string, b: string): number => Buffer.compare(Buffer.from(a), Buffer.from(b));
type Unsigned = Omit<z.infer<typeof decision>, "decisionSha256">;
const seal = (value: Unsigned): z.infer<typeof decision> => decision.parse({ ...value, decisionSha256: hash("dsa-seats:aipac-numeric-review-decision:v3\0", value) });

export function buildAipacNumericReviewPackageV3(input: Readonly<{ foundation: unknown; foundationFileSha256: string; candidate: unknown; candidateFileSha256: string; report: unknown; reportFileSha256: string }>): AipacNumericReviewPackageV3 {
  if (canonicalJson([input.foundationFileSha256, input.candidateFileSha256, input.reportFileSha256]) !== canonicalJson([FILES.foundation, FILES.candidate, FILES.report])) throw new Error("AIPAC_NUMERIC_REVIEW_V3_INPUT_FILE_HASH_MISMATCH");
  const foundation = validateAipacEvidenceFoundationCandidateV3(input.foundation), candidate = validateAipacNumericEvidenceCandidateV3(input.candidate), report = validateDsaTargetReviewReportV5(input.report);
  if (foundation.packageSha256 !== PACKAGES.foundation || candidate.packageSha256 !== PACKAGES.candidate || report.reportSha256 !== PACKAGES.report || foundation.sourceCutoff !== candidate.sourceCutoff || candidate.sourceCutoff !== report.scope.sourceCutoff) throw new Error("AIPAC_NUMERIC_REVIEW_V3_INPUT_CLOSURE_INVALID");
  const base = { blocksPublication: true as const, blocksOtherWork: false as const, resolution: null, reviewer: null, reviewedAt: null };
  const pending = foundation.remainingDecisionQueue[0];
  const mapping = seal({ ...base, decisionId: pending.decisionId, component: "candidate_committee_source_precedence" as const, affectedSeatCycleId: pending.seatCycleId, affectedCycleYear: pending.cycleYear, question: pending.question, recommendedDecision: pending.recommendedDecision, defaultReversibleAssumption: pending.defaultReversibleAssumption, alternatives: [...pending.alternatives], consequences: [...pending.consequences], confidence: pending.confidence, workCompletedWhileWaiting: [...pending.workCompletedWhileWaiting], requiredEvidence: [...pending.requiredEvidence], evidenceSha256s: [pending.sourceResolutionSha256, pending.decisionSha256], officialFilingSourceLockIds: [...pending.officialFilingSourceLockIds] });
  const highLevel: Unsigned[] = [
    { ...base, decisionId: "aipac-numeric:accept-lineage-methodology-v3", component: "numeric_lineage_methodology", affectedSeatCycleId: null, affectedCycleYear: null, question: "Should the cycle-scoped cutoff-ledger, terminal-revision, signed-net, exact/derived relationship-disposition, and transaction-receipt methodology be accepted for a future reviewed factual release?", recommendedDecision: "Accept only the reproducible v3 method and preserve CA-31 2024 as pending plus all House-cycle non-applicability states.", defaultReversibleAssumption: "retain_reviewer_candidate_exclude_from_publication", alternatives: ["Request a corrected coverage or transaction rule.", "Reject numeric use and keep AIPAC not collected."], consequences: ["Acceptance permits this exact method, not automatic publication, to enter a later reviewed release.", "Deferral leaves report v5 available only for reviewer analysis."], confidence: "high", workCompletedWhileWaiting: ["Numeric v3 retains 278 evidence rows with 261 evaluator-eligible rows while preserving one pending and two not-applicable current-cycle states.", "Every selected transaction remains joined to a cutoff-valid filing chain and receipt."], requiredEvidence: [], evidenceSha256s: [candidate.packageSha256, candidate.derivation.seatSetSha256, candidate.derivation.evidenceSetSha256], officialFilingSourceLockIds: [] },
    { ...base, decisionId: "aipac-numeric:accept-labeled-udp-inferences-v3", component: "inferred_udp_relationships", affectedSeatCycleId: null, affectedCycleYear: null, question: "Should the 16 usable UDP challenger relationships remain explicitly labeled inferences in a future reviewed release?", recommendedDecision: "Accept them only with exact inference or automatic-disposition provenance, confidence, same-seat primary rationale, and correction path; never relabel them as direct mappings.", defaultReversibleAssumption: "retain_reviewer_candidate_exclude_from_publication", alternatives: ["Require individual review of all 16 relationships.", "Exclude all challenger-opposition evidence."], consequences: ["Acceptance preserves reviewer-visible challenger-opposition evidence without a direct-observation claim.", "Rejection requires regenerated numeric and report artifacts."], confidence: "medium", workCompletedWhileWaiting: ["The Illinois 7 positive-origin relationship is mechanically admitted and California 47's invalid origin remains rejected.", "All retained inference relationships remain hash-bound."], requiredEvidence: [], evidenceSha256s: [foundation.packageSha256, foundation.derivation.relationshipSetSha256], officialFilingSourceLockIds: [] },
    { ...base, decisionId: "aipac-numeric:retain-v01-no-na-denominator-v3", component: "scoring_model", affectedSeatCycleId: null, affectedCycleYear: null, question: "Should formula dsa-primary-target-v0.1 retain its six-cell AIPAC coverage denominator, leaving MA-06 and NH-01 AIPAC-score-ineligible when 2026 is not applicable to a House candidacy?", recommendedDecision: "Retain the v0.1 denominator for this candidate; require a separately versioned methodology, sensitivity analysis, and review package before any not-applicable denominator changes.", defaultReversibleAssumption: "retain_reviewer_candidate_exclude_from_publication", alternatives: ["Propose a separately versioned not-applicable-denominator formula and regenerate sensitivity results.", "Keep AIPAC evidence visible but exclude it from ranking."], consequences: ["Retention keeps MA-06 and NH-01 AIPAC components null rather than converting their 2026 state to zero.", "A new denominator changes eligibility and requires a new report hash."], confidence: "high", workCompletedWhileWaiting: ["Report v5 scores 201 formula-compatible complete-coverage seats and keeps CA-31, MA-06, NH-01, and eight Washington seats from the AIPAC route.", "MD-04, MN-03, and NY-04 are newly scoreable only under their completed v3 closures."], requiredEvidence: [], evidenceSha256s: [report.reportSha256, candidate.packageSha256], officialFilingSourceLockIds: [] },
    { ...base, decisionId: "aipac-numeric:promote-factual-release-v3", component: "publication_promotion", affectedSeatCycleId: null, affectedCycleYear: null, question: "Should numeric candidate v3 and report v5 be promoted to a new public factual release?", recommendedDecision: "Defer promotion until the CA-31 precedence and three methodology decisions are explicitly decided, then generate a distinct approved release rather than mutating any candidate.", defaultReversibleAssumption: "retain_reviewer_candidate_exclude_from_publication", alternatives: ["Approve a corrected subset and regenerate every downstream artifact.", "Reject promotion while retaining reviewer-only research artifacts."], consequences: ["Approval after prerequisites enables public score and evidence UI work.", "Deferral leaves the deployed application and current published release unchanged and truthful."], confidence: "high", workCompletedWhileWaiting: ["Foundation v3, numeric v3, report v5, source closure, privacy minimization, and the public firewall are complete.", "No reviewer identity, approval timestamp, promotion, or public deployment was fabricated."], requiredEvidence: [], evidenceSha256s: [foundation.packageSha256, candidate.packageSha256, report.reportSha256], officialFilingSourceLockIds: [] },
  ];
  const decisions = [mapping, ...highLevel.map(seal)].sort((a, b) => order(a.decisionId, b.decisionId));
  const unsigned = { schema: "aipac-numeric-review-package-v3" as const, version: 3 as const, generatedAt: "2026-08-05T22:00:00.000Z" as const, sourceCutoff: "2026-08-04" as const, reviewerOnly: true as const, publicationEligible: false as const, review: { status: "proposed" as const, reviewer: null, reviewedAt: null }, inputs: { foundation: { fileSha256: FILES.foundation, packageSha256: foundation.packageSha256 }, candidate: { fileSha256: FILES.candidate, packageSha256: candidate.packageSha256 }, report: { fileSha256: FILES.report, reportSha256: report.reportSha256 } }, summary: { totalDecisions: 5 as const, mappingPrecedenceDecisions: 1 as const, methodologyDecisions: 3 as const, promotionDecisions: 1 as const, automaticallyResolvedIncumbentCases: 5 as const, safeDefault: "retain_reviewer_candidate_exclude_from_publication" as const }, decisions, decisionSetSha256: hash("dsa-seats:aipac-numeric-review-decision-set:v3\0", decisions) };
  return validateAipacNumericReviewPackageV3({ ...unsigned, packageSha256: hash("dsa-seats:aipac-numeric-review-package:v3\0", unsigned) });
}

export function validateAipacNumericReviewPackageV3(value: unknown): AipacNumericReviewPackageV3 {
  const parsed = aipacNumericReviewPackageV3Schema.parse(value), { packageSha256, ...unsigned } = parsed;
  if (packageSha256 !== hash("dsa-seats:aipac-numeric-review-package:v3\0", unsigned) || packageSha256 !== PACKAGE_SHA256 || parsed.decisionSetSha256 !== hash("dsa-seats:aipac-numeric-review-decision-set:v3\0", parsed.decisions) || parsed.decisionSetSha256 !== DECISION_SET_SHA256 || new Set(parsed.decisions.map((row) => row.decisionId)).size !== 5 || parsed.decisions.some((row) => row.decisionSha256 !== hash("dsa-seats:aipac-numeric-review-decision:v3\0", Object.fromEntries(Object.entries(row).filter(([key]) => key !== "decisionSha256"))) || row.resolution !== null || row.reviewer !== null || row.reviewedAt !== null)) throw new Error("AIPAC_NUMERIC_REVIEW_V3_INVARIANT_FAILED");
  const mapping = parsed.decisions.filter((row) => row.component === "candidate_committee_source_precedence");
  if (mapping.length !== 1 || mapping[0]?.affectedSeatCycleId !== "seat_house_ca_31_current" || mapping[0]?.affectedCycleYear !== 2024 || mapping[0]?.defaultReversibleAssumption !== "exclude_only_ca31_2024_relationship") throw new Error("AIPAC_NUMERIC_REVIEW_V3_PENDING_DECISION_MISMATCH");
  return parsed;
}
