import { createHash } from "node:crypto";
import { z } from "zod";
import { validateDsaTargetReviewReportV4 } from "../../domain/dsa-target-review-report-v4";
import { validateAipacEvidenceFoundationCandidateV2 } from "./aipac-evidence-foundation-candidate-v2";
import { validateAipacNumericEvidenceCandidateV2 } from "./aipac-numeric-evidence-candidate-v2";
import { canonicalJson } from "./aipac-proposed-packages";

const SHA = z.string().regex(/^[a-f0-9]{64}$/);
const FILES = { foundation: "e4e2bfe3818fdbb99bbb0b92671a3419656d38f4d0679eb132a5c17e2b443686", candidate: "a02fa77b1caefc3fbfeb99035d648f4fe9934b374797b524498530f03a2ea12d", report: "f50c8a445b9e0e441a67004ded8929982c1fb35b5cc0aba2bf59189b3c5da808" } as const;
const DECISION_SET_SHA256 = "3d2c3733bf9a9b5ea725f095b0add09b2614e7470e71988e8a50b53c221b322f";
const PACKAGE_SHA256 = "408780bf094982c95b48549593efd1c3ed2e8f894449c61d47fd989204681d52";
const decision = z.strictObject({
  decisionId: z.string().min(1), component: z.enum(["mapping_resolution", "numeric_lineage_methodology", "inferred_udp_relationships", "scoring_model", "publication_promotion"]), affectedSeatCycleId: z.string().min(1).nullable(),
  question: z.string().min(1), recommendedDecision: z.string().min(1), defaultReversibleAssumption: z.literal("retain_reviewer_candidate_exclude_from_publication"), alternatives: z.array(z.string().min(1)).min(1), consequences: z.array(z.string().min(1)).min(1), confidence: z.enum(["high", "medium", "low"]),
  blocksPublication: z.literal(true), blocksOtherWork: z.literal(false), workCompletedWhileWaiting: z.array(z.string().min(1)).min(1), evidenceSha256s: z.array(SHA).min(1), resolution: z.null(), reviewer: z.null(), reviewedAt: z.null(), decisionSha256: SHA,
});
export const aipacNumericReviewPackageV2Schema = z.strictObject({
  schema: z.literal("aipac-numeric-review-package-v2"), version: z.literal(2), generatedAt: z.literal("2026-08-05T20:00:00.000Z"), sourceCutoff: z.literal("2026-08-04"), reviewerOnly: z.literal(true), publicationEligible: z.literal(false), review: z.strictObject({ status: z.literal("proposed"), reviewer: z.null(), reviewedAt: z.null() }),
  inputs: z.strictObject({ foundation: z.strictObject({ fileSha256: z.literal(FILES.foundation), packageSha256: z.literal("034d940df8f36c890c742ca94820836738fd242a37e62476b57d9bb266d2f178") }), candidate: z.strictObject({ fileSha256: z.literal(FILES.candidate), packageSha256: z.literal("c2e864ee17fe3c264c0a3e49ca2d24bc9fef2498ec998aae90b61920ebaf00ab") }), report: z.strictObject({ fileSha256: z.literal(FILES.report), reportSha256: z.literal("e428fc823ab5f6efa3eacd8f5191fabcb4580a7c4775b0bcae74518917523db9") }) }),
  summary: z.strictObject({ totalDecisions: z.literal(10), mappingResolutions: z.literal(6), methodologyDecisions: z.literal(3), promotionDecisions: z.literal(1), automaticallyAcceptedRelationships: z.literal(1), automaticallyRejectedInvalidOrigins: z.literal(1), safeDefault: z.literal("retain_reviewer_candidate_exclude_from_publication") }),
  decisions: z.array(decision).length(10), decisionSetSha256: SHA, packageSha256: SHA,
});
export type AipacNumericReviewPackageV2 = z.infer<typeof aipacNumericReviewPackageV2Schema>;
const hash = (domain: string, value: unknown): string => createHash("sha256").update(domain).update(canonicalJson(value)).digest("hex");
const order = (a: string, b: string): number => Buffer.compare(Buffer.from(a), Buffer.from(b));
type DecisionUnsigned = Omit<z.infer<typeof decision>, "decisionSha256">;
const seal = (value: DecisionUnsigned): z.infer<typeof decision> => decision.parse({ ...value, decisionSha256: hash("dsa-seats:aipac-numeric-review-decision:v2\0", value) });

export function buildAipacNumericReviewPackageV2(input: Readonly<{ foundation: unknown; foundationFileSha256: string; candidate: unknown; candidateFileSha256: string; report: unknown; reportFileSha256: string }>): AipacNumericReviewPackageV2 {
  const foundation = validateAipacEvidenceFoundationCandidateV2(input.foundation), candidate = validateAipacNumericEvidenceCandidateV2(input.candidate), report = validateDsaTargetReviewReportV4(input.report);
  if (canonicalJson([input.foundationFileSha256, input.candidateFileSha256, input.reportFileSha256]) !== canonicalJson([FILES.foundation, FILES.candidate, FILES.report]) || foundation.sourceCutoff !== candidate.sourceCutoff || candidate.sourceCutoff !== report.scope.sourceCutoff) throw new Error("AIPAC_NUMERIC_REVIEW_V2_INPUT_CLOSURE_INVALID");
  const base = { defaultReversibleAssumption: "retain_reviewer_candidate_exclude_from_publication" as const, blocksPublication: true as const, blocksOtherWork: false as const, resolution: null, reviewer: null, reviewedAt: null };
  const mappings = foundation.remainingDecisionQueue.map((row) => seal({ ...base, decisionId: row.decisionId, component: "mapping_resolution" as const, affectedSeatCycleId: row.seatCycleId, question: row.question, recommendedDecision: row.recommendedDecision, alternatives: ["Defer this relationship and keep all six AIPAC coverage cells blocked.", "Reject the proposed resolution and request a separately sourced correction."], consequences: row.consequences, confidence: "high" as const, workCompletedWhileWaiting: ["Official filing evidence was retained by hash without donor or contact details.", "Numeric v2 blocks this seat while every unrelated seat remains usable."], evidenceSha256s: [row.decisionSha256, row.resolutionCandidateSha256] }));
  const highLevel: DecisionUnsigned[] = [
    { ...base, decisionId: "aipac-numeric:accept-lineage-methodology-v2", component: "numeric_lineage_methodology", affectedSeatCycleId: null, question: "Should the cutoff-ledger, terminal-revision, signed-net, relationship-resolution, and transaction-receipt methodology be accepted for a future reviewed factual release?", recommendedDecision: "Accept the reproducible v2 methodology after regenerating its exact hash-bound package; preserve every pending, invalid-origin, and no-House-candidacy state.", alternatives: ["Request a corrected transaction or coverage rule.", "Reject numeric use and keep AIPAC not collected."], consequences: ["Acceptance permits this exact method, not automatic publication, to enter a later reviewed release.", "Deferral leaves report v4 available only for reviewer analysis."], confidence: "high", workCompletedWhileWaiting: ["All source rows were joined to cutoff-valid filing chains and 2,449 transaction receipts bind 2,673 hashed source records to 274 evidence groups.", "Six pending mappings emit no evidence and California 47 retains its rejected-origin diagnostic."], evidenceSha256s: [candidate.packageSha256, candidate.derivation.seatSetSha256, candidate.derivation.evidenceSetSha256] },
    { ...base, decisionId: "aipac-numeric:accept-labeled-udp-inferences-v2", component: "inferred_udp_relationships", affectedSeatCycleId: null, question: "Should the 16 usable UDP challenger relationships remain explicitly labeled inferences in a future reviewed release?", recommendedDecision: "Accept them only with their exact inference or resolution provenance, confidence, same-seat primary rationale, and correction path; never relabel them as direct mappings.", alternatives: ["Require individual review of all 16 relationships.", "Exclude all challenger-opposition evidence."], consequences: ["Acceptance preserves reviewer-visible challenger-opposition evidence without claiming direct observation.", "Rejection requires regenerated numeric and report artifacts."], confidence: "medium", workCompletedWhileWaiting: ["All inferred relationships remain labeled and hash-bound.", "The single invalid-origin association is rejected and six incumbent mappings remain pending."], evidenceSha256s: [foundation.packageSha256, foundation.derivation.relationshipSetSha256] },
    { ...base, decisionId: "aipac-numeric:accept-v01-score-use-v2", component: "scoring_model", affectedSeatCycleId: null, question: "Should formula dsa-primary-target-v0.1 use the candidate AIPAC component at 60% of the AIPAC route for a future reviewed release?", recommendedDecision: "Accept v0.1 as an explainable initial reviewer model, retain decomposed components, and require a separately versioned formula for any weight change.", alternatives: ["Choose a lower AIPAC-route weight and regenerate sensitivity results.", "Keep the component visible but exclude it from ranking."], consequences: ["Acceptance preserves 52 AIPAC-route selections in the formula-compatible candidate universe.", "A different weight changes ranks and requires a new report hash."], confidence: "medium", workCompletedWhileWaiting: ["Report v4 preserves component, route, rank, coverage, and resolution-state decomposition for all 212 seats.", "Six pending and eight Washington seats cannot receive an AIPAC component or route."], evidenceSha256s: [report.reportSha256, candidate.packageSha256] },
    { ...base, decisionId: "aipac-numeric:promote-factual-release-v2", component: "publication_promotion", affectedSeatCycleId: null, question: "Should numeric candidate v2 and report v4 be promoted to a new public factual release?", recommendedDecision: "Defer promotion until the three methodology decisions and six mapping resolutions are decided, then generate a distinct approved release rather than mutating either proposal.", alternatives: ["Approve a corrected subset and regenerate every downstream artifact.", "Reject promotion while retaining the research artifacts."], consequences: ["Approval after prerequisite resolution enables public score and evidence UI work.", "Deferral leaves the deployed application and published release unchanged and truthful."], confidence: "high", workCompletedWhileWaiting: ["Foundation v2, numeric v2, report v4, source closure, privacy minimization, and public firewall are complete.", "No reviewer identity, approval timestamp, promotion, or public deployment was fabricated."], evidenceSha256s: [foundation.packageSha256, candidate.packageSha256, report.reportSha256] },
  ];
  const decisions = [...mappings, ...highLevel.map(seal)].sort((a, b) => order(a.decisionId, b.decisionId));
  const unsigned = { schema: "aipac-numeric-review-package-v2" as const, version: 2 as const, generatedAt: "2026-08-05T20:00:00.000Z" as const, sourceCutoff: "2026-08-04" as const, reviewerOnly: true as const, publicationEligible: false as const, review: { status: "proposed" as const, reviewer: null, reviewedAt: null }, inputs: { foundation: { fileSha256: FILES.foundation, packageSha256: foundation.packageSha256 }, candidate: { fileSha256: FILES.candidate, packageSha256: candidate.packageSha256 }, report: { fileSha256: FILES.report, reportSha256: report.reportSha256 } }, summary: { totalDecisions: 10 as const, mappingResolutions: 6 as const, methodologyDecisions: 3 as const, promotionDecisions: 1 as const, automaticallyAcceptedRelationships: 1 as const, automaticallyRejectedInvalidOrigins: 1 as const, safeDefault: "retain_reviewer_candidate_exclude_from_publication" as const }, decisions, decisionSetSha256: hash("dsa-seats:aipac-numeric-review-decision-set:v2\0", decisions) };
  const value = aipacNumericReviewPackageV2Schema.parse({ ...unsigned, packageSha256: hash("dsa-seats:aipac-numeric-review-package:v2\0", unsigned) });
  return validateAipacNumericReviewPackageV2(value);
}

export function validateAipacNumericReviewPackageV2(value: unknown): AipacNumericReviewPackageV2 {
  const parsed = aipacNumericReviewPackageV2Schema.parse(value), { packageSha256, ...unsigned } = parsed;
  if (packageSha256 !== hash("dsa-seats:aipac-numeric-review-package:v2\0", unsigned) || packageSha256 !== PACKAGE_SHA256 || parsed.decisionSetSha256 !== hash("dsa-seats:aipac-numeric-review-decision-set:v2\0", parsed.decisions) || parsed.decisionSetSha256 !== DECISION_SET_SHA256) throw new Error("AIPAC_NUMERIC_REVIEW_V2_PACKAGE_HASH_MISMATCH");
  if (new Set(parsed.decisions.map((row) => row.decisionId)).size !== 10 || parsed.decisions.some((row) => row.decisionSha256 !== hash("dsa-seats:aipac-numeric-review-decision:v2\0", Object.fromEntries(Object.entries(row).filter(([key]) => key !== "decisionSha256"))) || row.resolution !== null || row.reviewer !== null || row.reviewedAt !== null)) throw new Error("AIPAC_NUMERIC_REVIEW_V2_DECISION_INVARIANT_FAILED");
  return parsed;
}
