import { createHash } from "node:crypto";
import { z } from "zod";
import { validateCa31TerminalChainReceipt } from "./ca31-terminal-chain-receipt";
import { aipacIncumbentResolutionDispositionsV2Schema, validateAipacIncumbentResolutionDispositionsV2 } from "./aipac-incumbent-resolution-dispositions-v2";
import { canonicalJson } from "./aipac-proposed-packages";

const SHA = z.string().regex(/^[a-f0-9]{64}$/);
const INPUTS = { dispositionsFile: "c4babb56fe21a99cde0dd9a5a9922f3510899cd507709f9d72afe892f05686fe", dispositionsPackage: "81f0d5996356ccae3747104009eaf5fdb4a96a2c8bf5a2c8da838eadcd924a7a", receiptFile: "1c3d46fcfc76a33ed1fca469cbefb9924622a2245f266fc6394850845c9b7198", receiptPackage: "8201a54aa4894163bda0a24b214c10166ade3fe4fcbe31b6e0667d7094b11cee", receiptEvidence: "539ed96bbfa5e6058d5a3f9085b9d3d804616c3615c9613b265f6952228fe3c8" } as const;
const priorDisposition = aipacIncumbentResolutionDispositionsV2Schema.shape.dispositions.element;
const priorCycleDisposition = priorDisposition.shape.cycleDispositions.element;
const disposition = priorDisposition.extend({ identityDispositionScope: z.enum(["source_to_canonical_identity", "canonical_roster_identity_only"]), identifierMappingResolved: z.boolean(), unresolvedIdentifierConflict: z.boolean(), conflictingSignedFormCandidateIds: z.array(z.string().regex(/^H[A-Z0-9]{8}$/)).max(1), cycleDispositions: z.array(priorCycleDisposition.extend({ evidenceRule: z.union([priorCycleDisposition.shape.evidenceRule, z.literal("terminal_form2_form1_chain_exact_committee_relationship")]) })).min(1) });
const automaticClosure = z.strictObject({ decisionId: z.literal("aipac-mapping-precedence:incumbent:seat_house_ca_31_current:2024:H8CA39174"), seatCycleId: z.literal("seat_house_ca_31_current"), cycleYear: z.literal(2024), closureKind: z.literal("mechanically_verified_official_evidence"), receiptSourceLockId: z.literal("ca31-terminal-fec-chain-receipt-v1"), receiptFileSha256: z.literal(INPUTS.receiptFile), receiptPackageSha256: z.literal(INPUTS.receiptPackage), evidenceSetSha256: SHA, reviewerAction: z.literal(false), reviewer: z.null(), reviewedAt: z.null(), closureSha256: SHA });

export const aipacIncumbentResolutionDispositionsV3Schema = z.strictObject({
  schema: z.literal("aipac-incumbent-resolution-dispositions-v3"), version: z.literal(3), generatedAt: z.literal("2026-08-05T22:30:00.000Z"), sourceCutoff: z.literal("2026-08-04"), reviewerOnly: z.literal(true), publicationEligible: z.literal(false), status: z.literal("automatic_evidence_dispositions_no_mapping_decisions"), defaultUse: z.literal("apply_only_to_a_new_reviewer_only_foundation_never_as_publication_approval"),
  inputs: z.strictObject({ dispositionsV2: z.strictObject({ sourceLockId: z.literal("aipac-incumbent-resolution-dispositions-v2"), fileSha256: z.literal(INPUTS.dispositionsFile), packageSha256: z.literal(INPUTS.dispositionsPackage) }), ca31TerminalReceipt: z.strictObject({ sourceLockId: z.literal("ca31-terminal-fec-chain-receipt-v1"), fileSha256: z.literal(INPUTS.receiptFile), packageSha256: z.literal(INPUTS.receiptPackage) }) }),
  policy: z.strictObject({ evidenceClosure: z.literal("remove_a_mapping_decision_only_when_cutoff_bounded_official_terminal_evidence_mechanically_proves_the_relationship"), identifierAliases: z.literal("preserve_cross_surface_H8_H4_identifier_discrepancy_without_claiming_identifier_equality"), publication: z.literal("mechanical_evidence_closure_is_not_review_approval_or_release_promotion") }),
  summary: z.strictObject({ inputCases: z.literal(6), fullyResolvedCases: z.literal(6), partiallyResolvedCases: z.literal(0), autoUsableHouseCycles: z.literal(10), autoNotApplicableHouseCycles: z.literal(2), pendingHouseCycles: z.literal(0), remainingMappingDecisions: z.literal(0), automaticallyClosedMappingDecisions: z.literal(1), fabricatedReviewerApprovals: z.literal(0) }),
  dispositions: z.array(disposition).length(6), automaticEvidenceClosures: z.tuple([automaticClosure]), remainingDecisionQueue: z.tuple([]), derivation: z.strictObject({ dispositionSetSha256: SHA, automaticClosureSetSha256: SHA, remainingDecisionSetSha256: SHA, semanticsSha256: SHA }), review: z.strictObject({ status: z.literal("automatic_evidence_dispositions"), reviewer: z.null(), reviewedAt: z.null() }), packageSha256: SHA,
});
export type AipacIncumbentResolutionDispositionsV3 = z.infer<typeof aipacIncumbentResolutionDispositionsV3Schema>;
const hash = (domain: string, value: unknown): string => createHash("sha256").update(domain).update(canonicalJson(value)).digest("hex");
const order = (a: string, b: string): number => Buffer.compare(Buffer.from(a), Buffer.from(b));
export const aipacIncumbentResolutionSemanticsSha256V3 = (rows: readonly z.infer<typeof disposition>[]): string => hash("dsa-seats:aipac-incumbent-resolution-semantics:v3\0", rows.map(({ seatCycleId, sourceCandidateId, canonicalCandidateId, alternateCandidateIds, identityDisposition, identityDispositionScope, identifierMappingResolved, unresolvedIdentifierConflict, conflictingSignedFormCandidateIds, rawPartyTreatment, cycleDispositions }) => ({ seatCycleId, sourceCandidateId, canonicalCandidateId, alternateCandidateIds, identityDisposition, identityDispositionScope, identifierMappingResolved, unresolvedIdentifierConflict, conflictingSignedFormCandidateIds, rawPartyTreatment, cycleDispositions })));

export function buildAipacIncumbentResolutionDispositionsV3(input: Readonly<{ dispositionsV2: unknown; dispositionsV2FileSha256: string; receipt: unknown; receiptFileSha256: string }>): AipacIncumbentResolutionDispositionsV3 {
  if (input.dispositionsV2FileSha256 !== INPUTS.dispositionsFile || input.receiptFileSha256 !== INPUTS.receiptFile) throw new Error("AIPAC_INCUMBENT_DISPOSITIONS_V3_INPUT_FILE_HASH_MISMATCH");
  const prior = validateAipacIncumbentResolutionDispositionsV2(input.dispositionsV2), receipt = validateCa31TerminalChainReceipt(input.receipt);
  if (prior.packageSha256 !== INPUTS.dispositionsPackage || receipt.packageSha256 !== INPUTS.receiptPackage) throw new Error("AIPAC_INCUMBENT_DISPOSITIONS_V3_INPUT_PACKAGE_HASH_MISMATCH");
  const dispositions = prior.dispositions.map((row) => {
    const cycleDispositions = row.seatCycleId === "seat_house_ca_31_current" ? row.cycleDispositions.map((cycle) => cycle.cycleYear === 2024 ? { ...cycle, disposition: "auto_verified_house_relationship" as const, evidenceRule: "terminal_form2_form1_chain_exact_committee_relationship" as const, provenanceKind: "direct" as const, confidence: "certain" as const, evaluatorUse: "reviewer_only_candidate" as const, rationaleCodes: [...receipt.conclusion.rationaleCodes] } : cycle) : row.cycleDispositions;
    const officialFilingSourceLockIds = row.seatCycleId === "seat_house_ca_31_current" ? [...new Set([...row.officialFilingSourceLockIds, "fec-form2-ca31-20230912", "fec-form1-1724934", "fec-form1-1814721"])] : row.officialFilingSourceLockIds;
    const sourceEvidenceRecordSha256s = row.seatCycleId === "seat_house_ca_31_current" ? [...new Set([...row.sourceEvidenceRecordSha256s, receipt.evidenceSetSha256, receipt.packageSha256])] : row.sourceEvidenceRecordSha256s;
    const { dispositionSha256, ...base } = row;
    if (!dispositionSha256) throw new Error("AIPAC_INCUMBENT_DISPOSITIONS_V3_PRIOR_ROW_HASH_MISSING");
    const rationaleCodes = row.seatCycleId === "seat_house_ca_31_current" ? [...row.rationaleCodes.filter((code) => code !== "CCL24_MISSING_DIRECT_FORM_EVIDENCE_OVERRIDE_REQUIRES_REVIEW"), "TERMINAL_FEC_CHAIN_RESOLVED_PRIOR_SOURCE_CONFLICT", "H8_H4_IDENTIFIER_DISCREPANCY_REMAINS_UNRESOLVED"] : row.rationaleCodes;
    const isCa31 = row.seatCycleId === "seat_house_ca_31_current";
    const unsigned = { ...base, alternateCandidateIds: isCa31 ? row.alternateCandidateIds.filter((id) => id !== "H4CA31170") : row.alternateCandidateIds, identityDispositionScope: isCa31 ? "canonical_roster_identity_only" as const : "source_to_canonical_identity" as const, identifierMappingResolved: !isCa31, unresolvedIdentifierConflict: isCa31, conflictingSignedFormCandidateIds: isCa31 ? ["H4CA31170"] : [], cycleDispositions, officialFilingSourceLockIds, sourceEvidenceRecordSha256s, rationaleCodes };
    return disposition.parse({ ...unsigned, dispositionSha256: hash("dsa-seats:aipac-incumbent-resolution-disposition:v3\0", unsigned) });
  }).sort((a, b) => order(a.seatCycleId, b.seatCycleId));
  const closureUnsigned = { decisionId: receipt.automaticDecisionClosure.decisionId, seatCycleId: receipt.conclusion.seatCycleId, cycleYear: receipt.conclusion.cycleYear, closureKind: receipt.automaticDecisionClosure.closureKind, receiptSourceLockId: "ca31-terminal-fec-chain-receipt-v1", receiptFileSha256: INPUTS.receiptFile, receiptPackageSha256: receipt.packageSha256, evidenceSetSha256: receipt.evidenceSetSha256, reviewerAction: false, reviewer: null, reviewedAt: null } as const;
  const automaticEvidenceClosures = [{ ...closureUnsigned, closureSha256: hash("dsa-seats:aipac-incumbent-automatic-closure:v3\0", closureUnsigned) }] as const, remainingDecisionQueue = [] as const;
  const unsigned = { schema: "aipac-incumbent-resolution-dispositions-v3", version: 3, generatedAt: "2026-08-05T22:30:00.000Z", sourceCutoff: "2026-08-04", reviewerOnly: true, publicationEligible: false, status: "automatic_evidence_dispositions_no_mapping_decisions", defaultUse: "apply_only_to_a_new_reviewer_only_foundation_never_as_publication_approval", inputs: { dispositionsV2: { sourceLockId: "aipac-incumbent-resolution-dispositions-v2", fileSha256: INPUTS.dispositionsFile, packageSha256: prior.packageSha256 }, ca31TerminalReceipt: { sourceLockId: "ca31-terminal-fec-chain-receipt-v1", fileSha256: INPUTS.receiptFile, packageSha256: receipt.packageSha256 } }, policy: { evidenceClosure: "remove_a_mapping_decision_only_when_cutoff_bounded_official_terminal_evidence_mechanically_proves_the_relationship", identifierAliases: "preserve_cross_surface_H8_H4_identifier_discrepancy_without_claiming_identifier_equality", publication: "mechanical_evidence_closure_is_not_review_approval_or_release_promotion" }, summary: { inputCases: 6, fullyResolvedCases: 6, partiallyResolvedCases: 0, autoUsableHouseCycles: 10, autoNotApplicableHouseCycles: 2, pendingHouseCycles: 0, remainingMappingDecisions: 0, automaticallyClosedMappingDecisions: 1, fabricatedReviewerApprovals: 0 }, dispositions, automaticEvidenceClosures, remainingDecisionQueue, derivation: { dispositionSetSha256: hash("dsa-seats:aipac-incumbent-resolution-disposition-set:v3\0", dispositions), automaticClosureSetSha256: hash("dsa-seats:aipac-incumbent-automatic-closure-set:v3\0", automaticEvidenceClosures), remainingDecisionSetSha256: hash("dsa-seats:aipac-incumbent-resolution-decision-set:v3\0", remainingDecisionQueue), semanticsSha256: aipacIncumbentResolutionSemanticsSha256V3(dispositions) }, review: { status: "automatic_evidence_dispositions", reviewer: null, reviewedAt: null } } as const;
  return validateAipacIncumbentResolutionDispositionsV3({ ...unsigned, packageSha256: hash("dsa-seats:aipac-incumbent-resolution-dispositions:v3\0", unsigned) });
}

export function validateAipacIncumbentResolutionDispositionsV3(value: unknown): AipacIncumbentResolutionDispositionsV3 {
  const parsed = aipacIncumbentResolutionDispositionsV3Schema.parse(value), { packageSha256, ...unsigned } = parsed;
  if (packageSha256 !== hash("dsa-seats:aipac-incumbent-resolution-dispositions:v3\0", unsigned) || parsed.derivation.dispositionSetSha256 !== hash("dsa-seats:aipac-incumbent-resolution-disposition-set:v3\0", parsed.dispositions) || parsed.derivation.automaticClosureSetSha256 !== hash("dsa-seats:aipac-incumbent-automatic-closure-set:v3\0", parsed.automaticEvidenceClosures) || parsed.derivation.remainingDecisionSetSha256 !== hash("dsa-seats:aipac-incumbent-resolution-decision-set:v3\0", parsed.remainingDecisionQueue) || parsed.derivation.semanticsSha256 !== aipacIncumbentResolutionSemanticsSha256V3(parsed.dispositions)) throw new Error("AIPAC_INCUMBENT_DISPOSITIONS_V3_HASH_MISMATCH");
  for (const row of parsed.dispositions) { const { dispositionSha256, ...rowUnsigned } = row; if (dispositionSha256 !== hash("dsa-seats:aipac-incumbent-resolution-disposition:v3\0", rowUnsigned)) throw new Error("AIPAC_INCUMBENT_DISPOSITIONS_V3_ROW_HASH_MISMATCH"); }
  const ca = parsed.dispositions.find((row) => row.seatCycleId === "seat_house_ca_31_current"), cycle = ca?.cycleDispositions.find((row) => row.cycleYear === 2024), closure = parsed.automaticEvidenceClosures[0];
  const { closureSha256, ...closureUnsigned } = closure;
  if (!ca || !cycle || cycle.disposition !== "auto_verified_house_relationship" || cycle.evidenceRule !== "terminal_form2_form1_chain_exact_committee_relationship" || cycle.evaluatorUse !== "reviewer_only_candidate" || ca.alternateCandidateIds.length !== 0 || ca.identityDispositionScope !== "canonical_roster_identity_only" || ca.identifierMappingResolved || !ca.unresolvedIdentifierConflict || canonicalJson(ca.conflictingSignedFormCandidateIds) !== canonicalJson(["H4CA31170"]) || !ca.officialFilingSourceLockIds.includes("fec-form2-ca31-20230912") || closure.receiptFileSha256 !== INPUTS.receiptFile || closure.receiptPackageSha256 !== INPUTS.receiptPackage || closure.evidenceSetSha256 !== INPUTS.receiptEvidence || closureSha256 !== hash("dsa-seats:aipac-incumbent-automatic-closure:v3\0", closureUnsigned) || closure.reviewerAction || closure.reviewer !== null || closure.reviewedAt !== null || parsed.remainingDecisionQueue.length !== 0) throw new Error("AIPAC_INCUMBENT_DISPOSITIONS_V3_CA31_CLOSURE_MISMATCH");
  return parsed;
}
