import { createHash } from "node:crypto";
import { z } from "zod";
import { validateDsaTargetReviewReportV3 } from "../../domain/dsa-target-review-report-v3";
import { canonicalJson } from "./aipac-proposed-packages";
import { validateAipacEvidenceFoundationCandidate } from "./aipac-evidence-foundation-candidate";
import { validateAipacNumericEvidenceCandidate } from "./aipac-numeric-evidence-candidate";

const SHA = z.string().regex(/^[a-f0-9]{64}$/);
const FILES = { foundation: "a0fe151080a0958c6cdddc447d50db4044700e31960d37dd2326ea86d6f7a7b7", candidate: "13e07985802bc6629ea46ed1287e429c949f66b47ca0cc6f5631d963acc129b7", report: "ecea6ddb2074566069faa75db73963faff949816f69acdc71bdfd5b39b44565b" } as const;
const DECISION_SET_SHA256 = "a3fe3ec5ec527c6991269850b8b0a3fd23971df46693b0a6d749aa02c9bd906e";
const PACKAGE_SHA256 = "df22d6c336603d12f5d81199d9e6cd0b1e512459c6aa089b9e99fc83842e61bc";
const decision = z.strictObject({
  decisionId: z.string().min(1), component: z.enum(["mapping_conflict", "numeric_lineage_methodology", "inferred_udp_relationships", "scoring_model", "publication_promotion"]),
  question: z.string().min(1), recommendedDecision: z.string().min(1), defaultReversibleAssumption: z.literal("retain_reviewer_candidate_exclude_from_publication"), alternatives: z.array(z.string().min(1)).min(1), consequences: z.array(z.string().min(1)).min(1), confidence: z.enum(["high", "medium", "low"]),
  blocksPublication: z.literal(true), blocksOtherWork: z.literal(false), workCompletedWhileWaiting: z.array(z.string().min(1)).min(1), evidenceSha256s: z.array(SHA).min(1), resolution: z.null(), reviewer: z.null(), reviewedAt: z.null(), decisionSha256: SHA,
});
export const aipacNumericReviewPackageSchema = z.strictObject({
  schema: z.literal("aipac-numeric-review-package-v1"), version: z.literal(1), generatedAt: z.literal("2026-08-05T08:15:00.000Z"), sourceCutoff: z.literal("2026-08-04"), reviewerOnly: z.literal(true), publicationEligible: z.literal(false), review: z.strictObject({ status: z.literal("proposed"), reviewer: z.null(), reviewedAt: z.null() }),
  inputs: z.strictObject({ foundation: z.strictObject({ fileSha256: z.literal(FILES.foundation), packageSha256: z.literal("cb888028e9038a69d5000d80f3bb330085200335597c101362584183b8be49da") }), candidate: z.strictObject({ fileSha256: z.literal(FILES.candidate), packageSha256: z.literal("dc3f6939701930226ad7558661e14b9912b7828266133d44260ae83570a2c077") }), report: z.strictObject({ fileSha256: z.literal(FILES.report), reportSha256: z.literal("a3db55181cbd0ffbe2c0b555276a5595ee37c7d233bcc30359eb2550dbcd918c") }) }),
  summary: z.strictObject({ totalDecisions: z.literal(12), mappingConflicts: z.literal(8), methodologyDecisions: z.literal(3), promotionDecisions: z.literal(1), safeDefault: z.literal("retain_reviewer_candidate_exclude_from_publication") }),
  decisions: z.array(decision).length(12), decisionSetSha256: z.literal(DECISION_SET_SHA256), packageSha256: z.literal(PACKAGE_SHA256),
});
export type AipacNumericReviewPackage = z.infer<typeof aipacNumericReviewPackageSchema>;
const hash = (domain: string, value: unknown): string => createHash("sha256").update(domain).update(canonicalJson(value)).digest("hex");
const order = (a: string, b: string): number => Buffer.compare(Buffer.from(a), Buffer.from(b));
type DecisionUnsigned = Omit<z.infer<typeof decision>, "decisionSha256">;
const seal = (value: DecisionUnsigned): z.infer<typeof decision> => decision.parse({ ...value, decisionSha256: hash("dsa-seats:aipac-numeric-review-decision:v1\0", value) });

export function buildAipacNumericReviewPackage(input: Readonly<{ foundation: unknown; foundationFileSha256: string; candidate: unknown; candidateFileSha256: string; report: unknown; reportFileSha256: string }>): AipacNumericReviewPackage {
  const foundation = validateAipacEvidenceFoundationCandidate(input.foundation), candidate = validateAipacNumericEvidenceCandidate(input.candidate), report = validateDsaTargetReviewReportV3(input.report);
  if (input.foundationFileSha256 !== FILES.foundation || input.candidateFileSha256 !== FILES.candidate || input.reportFileSha256 !== FILES.report || foundation.sourceCutoff !== candidate.sourceCutoff || candidate.sourceCutoff !== report.scope.sourceCutoff) throw new Error("AIPAC_NUMERIC_REVIEW_INPUT_CLOSURE_INVALID");
  const base = { defaultReversibleAssumption: "retain_reviewer_candidate_exclude_from_publication" as const, blocksPublication: true as const, blocksOtherWork: false as const, resolution: null, reviewer: null, reviewedAt: null };
  const conflicts = foundation.remainingDecisionQueue.map((row) => seal({ ...base, decisionId: row.decisionId, component: "mapping_conflict" as const, question: row.question, recommendedDecision: row.recommendedDecision, alternatives: row.alternatives, consequences: row.consequences, confidence: "low" as const, workCompletedWhileWaiting: row.workCompletedWhileWaiting, evidenceSha256s: [row.decisionSha256, ...row.evidenceRecordSha256s] }));
  const highLevel: DecisionUnsigned[] = [
    { ...base, decisionId: "aipac-numeric:accept-lineage-methodology-v1", component: "numeric_lineage_methodology", question: "Should the cutoff-ledger, terminal-revision, signed-net, and source-record receipt methodology be accepted for a future reviewed factual release?", recommendedDecision: "Accept the methodology after reproducing the exact candidate package from the three locked PAS2 ZIPs; retain the current artifact as reviewer-only until the complete package is approved.", alternatives: ["Request a corrected transaction-family rule.", "Reject numeric use and keep AIPAC not collected."], consequences: ["Acceptance permits this exact numeric method to enter a later reviewed release.", "Deferral leaves the v3 report useful only for reviewer analysis."], confidence: "high", workCompletedWhileWaiting: ["All source rows were joined to terminal cutoff-valid filing chains.", "2,435 transaction receipts bind 2,647 hashed source records to 272 evidence groups."], evidenceSha256s: [candidate.packageSha256, candidate.derivation.seatSetSha256, candidate.derivation.evidenceSetSha256] },
    { ...base, decisionId: "aipac-numeric:accept-labeled-udp-inferences-v1", component: "inferred_udp_relationships", question: "Should the 15 nonconflicting UDP challenger relationships be retained as explicitly inferred, medium-confidence relationships in a future reviewed release?", recommendedDecision: "Accept them only as labeled inferences with the exact same-seat primary rationale and correction path; never relabel them as direct mappings.", alternatives: ["Require individual review of all 15 relationships.", "Exclude all challenger-opposition evidence."], consequences: ["Acceptance preserves eight UDP challenger-opposition evidence groups as inferred evidence.", "Rejection removes only those inferred relationships and requires a regenerated report."], confidence: "medium", workCompletedWhileWaiting: ["All 15 relationships remain labeled inferred in the foundation.", "The eight true conflicts remain excluded."], evidenceSha256s: [foundation.packageSha256, foundation.derivation.relationshipSetSha256] },
    { ...base, decisionId: "aipac-numeric:accept-v01-score-use-v1", component: "scoring_model", question: "Should formula dsa-primary-target-v0.1 use the candidate AIPAC component at 60% of the AIPAC route for a future reviewed release?", recommendedDecision: "Accept v0.1 as an explainable initial reviewer model, retain the decomposed components, and require a separately versioned formula for any weight change.", alternatives: ["Choose a lower AIPAC route weight and regenerate sensitivity results.", "Keep the component visible but exclude it from ranking."], consequences: ["Acceptance preserves 51 AIPAC-route selections in the formula-compatible candidate universe.", "A different weight changes ranks and requires a new report hash."], confidence: "medium", workCompletedWhileWaiting: ["The report preserves component, route, and rank decomposition for all 212 seats.", "Eight Washington top-two seats are source-bound and formula-excluded."], evidenceSha256s: [report.reportSha256, candidate.packageSha256] },
    { ...base, decisionId: "aipac-numeric:promote-factual-release-v1", component: "publication_promotion", question: "Should this exact candidate and v3 report be promoted to a new public factual release?", recommendedDecision: "Defer promotion until the three methodology decisions and all affected mapping conflicts are resolved, then generate a distinct approved release rather than mutating this proposal.", alternatives: ["Approve a corrected subset and regenerate.", "Reject promotion while retaining the research artifact."], consequences: ["Approval after prerequisite resolution enables public score and evidence UI work.", "Deferral leaves the deployed v2 application unchanged and truthful."], confidence: "high", workCompletedWhileWaiting: ["The candidate, report, source-lock closure, privacy scan, and public firewall are complete.", "The published v2 report remains byte-identical and contains no candidate rankings."], evidenceSha256s: [candidate.packageSha256, report.reportSha256] },
  ];
  const decisions = [...conflicts, ...highLevel.map(seal)].sort((a, b) => order(a.decisionId, b.decisionId));
  const unsigned = { schema: "aipac-numeric-review-package-v1" as const, version: 1 as const, generatedAt: "2026-08-05T08:15:00.000Z" as const, sourceCutoff: "2026-08-04" as const, reviewerOnly: true as const, publicationEligible: false as const, review: { status: "proposed" as const, reviewer: null, reviewedAt: null }, inputs: { foundation: { fileSha256: FILES.foundation, packageSha256: foundation.packageSha256 }, candidate: { fileSha256: FILES.candidate, packageSha256: candidate.packageSha256 }, report: { fileSha256: FILES.report, reportSha256: report.reportSha256 } }, summary: { totalDecisions: 12 as const, mappingConflicts: 8 as const, methodologyDecisions: 3 as const, promotionDecisions: 1 as const, safeDefault: "retain_reviewer_candidate_exclude_from_publication" as const }, decisions, decisionSetSha256: hash("dsa-seats:aipac-numeric-review-decision-set:v1\0", decisions) };
  return validateAipacNumericReviewPackage({ ...unsigned, packageSha256: hash("dsa-seats:aipac-numeric-review-package:v1\0", unsigned) });
}

export function validateAipacNumericReviewPackage(value: unknown): AipacNumericReviewPackage {
  const parsed = aipacNumericReviewPackageSchema.parse(value), { packageSha256, ...unsigned } = parsed;
  if (packageSha256 !== hash("dsa-seats:aipac-numeric-review-package:v1\0", unsigned) || parsed.decisionSetSha256 !== hash("dsa-seats:aipac-numeric-review-decision-set:v1\0", parsed.decisions)) throw new Error("AIPAC_NUMERIC_REVIEW_PACKAGE_HASH_MISMATCH");
  if (new Set(parsed.decisions.map((row) => row.decisionId)).size !== 12 || parsed.decisions.some((row) => row.decisionSha256 !== hash("dsa-seats:aipac-numeric-review-decision:v1\0", Object.fromEntries(Object.entries(row).filter(([key]) => key !== "decisionSha256"))))) throw new Error("AIPAC_NUMERIC_REVIEW_DECISION_INVARIANT_FAILED");
  return parsed;
}
