import { createHash } from "node:crypto";
import { mkdtemp, rm, symlink, unlink, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { deflateRawSync } from "node:zlib";
import { describe, expect, it } from "vitest";
import { createFecBulkBootstrap, decodeFecBulkBootstrap, decodeFecBulkManifest, encodeFecBulkBootstrap, encodeFecBulkManifest, type BulkManifest } from "./bulk-bootstrap";

const sha=(b:Buffer)=>createHash("sha256").update(b).digest("hex");
const crc=(b:Buffer)=>{let c=0xffffffff;for(const x of b){c^=x;for(let i=0;i<8;i++)c=(c&1)?0xedb88320^(c>>>1):c>>>1;}return(c^0xffffffff)>>>0;};
/** A deliberately tiny stored ZIP whose headers can be changed independently. */
const zip=(name:string,body:Buffer,mutate?:(b:Buffer)=>void)=>{const n=Buffer.from(name),l=Buffer.alloc(30),c=Buffer.alloc(46);l.writeUInt32LE(0x04034b50);l.writeUInt16LE(20,4);l.writeUInt16LE(0x800,6);l.writeUInt32LE(crc(body),14);l.writeUInt32LE(body.length,18);l.writeUInt32LE(body.length,22);l.writeUInt16LE(n.length,26);c.writeUInt32LE(0x02014b50);c.writeUInt16LE(20,4);c.writeUInt16LE(20,6);c.writeUInt16LE(0x800,8);c.writeUInt32LE(crc(body),16);c.writeUInt32LE(body.length,20);c.writeUInt32LE(body.length,24);c.writeUInt16LE(n.length,28);const e=Buffer.alloc(22);e.writeUInt32LE(0x06054b50);e.writeUInt16LE(1,8);e.writeUInt16LE(1,10);e.writeUInt32LE(46+n.length,12);e.writeUInt32LE(30+n.length+body.length,16);const out=Buffer.concat([l,n,body,c,n,e]);mutate?.(out);return out;};
const officialZip=(name:string,body:Buffer)=>{const n=Buffer.from(name),compressed=deflateRawSync(body),checksum=crc(body),utCentral=Buffer.from([0x55,0x54,5,0,3,0,0,0,0]),utLocal=Buffer.from([0x55,0x54,9,0,3,0,0,0,0,0,0,0,0]),ux=Buffer.from([0x75,0x78,11,0,1,4,0,0,0,0,4,0,0,0,0]),localExtra=Buffer.concat([utLocal,ux]),centralExtra=Buffer.concat([utCentral,ux]),l=Buffer.alloc(30),c=Buffer.alloc(46),e=Buffer.alloc(22);l.writeUInt32LE(0x04034b50);l.writeUInt16LE(20,4);l.writeUInt32LE(8,8);l.writeUInt32LE(checksum,14);l.writeUInt32LE(compressed.length,18);l.writeUInt32LE(body.length,22);l.writeUInt16LE(n.length,26);l.writeUInt16LE(localExtra.length,28);const centralOffset=30+n.length+localExtra.length+compressed.length;c.writeUInt32LE(0x02014b50);c.writeUInt16LE(0x0314,4);c.writeUInt16LE(20,6);c.writeUInt32LE(8,10);c.writeUInt32LE(checksum,16);c.writeUInt32LE(compressed.length,20);c.writeUInt32LE(body.length,24);c.writeUInt16LE(n.length,28);c.writeUInt16LE(centralExtra.length,30);c.writeUInt32LE(0x81a40000,38);e.writeUInt32LE(0x06054b50);e.writeUInt16LE(1,8);e.writeUInt16LE(1,10);e.writeUInt32LE(46+n.length+centralExtra.length,12);e.writeUInt32LE(centralOffset,16);return Buffer.concat([l,n,localExtra,compressed,c,n,centralExtra,e]);};
const row=(v:string[])=>`${v.join("|")}\n`;
const code=(fn:()=>unknown, value:string)=>expect(fn).toThrow(value);
type Parts={cn:string;cm:string;ccl:string;web:string};
const base=():Parts=>({cn:row(["P00000001","Jane Private","X","2024","CA","P","01","","C","C00000001","address","","","",""]),cm:row(["C00000001","Committee Private","treasurer","","","","","zip-secret","D","H","","","","",""]),ccl:row(["P00000001","2024","2026","C00000001","H","D","0001"]),web:row(["P00000001","private","","","ignore","1","","-2","","","3",...Array(16).fill(""),"07/18/2026","",""])});
const fixture=async(change:(p:Parts)=>void=()=>{},zm?:(name:string,b:Buffer)=>void)=>{const root=await mkdtemp(join(tmpdir(),"fec-bulk-"));const p=base();change(p);const spec=[[["cn26.zip","cn.txt","cn"]],[["cm26.zip","cm.txt","cm"]],[["ccl26.zip","ccl.txt","ccl"]],[["weball26.zip","weball26.txt","web"]]] as const;const files:Record<string,Buffer>={};for(const [[archive,member,key]] of spec)files[archive]=zip(member,Buffer.from(p[key]),b=>zm?.(archive,b));await Promise.all(Object.entries(files).map(([n,b])=>writeFile(join(root,n),b)));const kinds=["candidate_master","committee_master","candidate_committee_linkage","candidate_summary"] as const;const names=Object.keys(files);const manifest:BulkManifest={version:1,cycle:2026,cutoff:"2026-07-18",publicationEligible:false,reviewStatus:"unreviewed",entries:kinds.map((kind,i)=>({kind,officialUrl:`https://www.fec.gov/files/bulk-downloads/2026/${names[i]}`,fileName:names[i]!,retrievedAt:"2026-01-01T00:00:00.000Z",byteSize:files[names[i]!]!.length,sha256:sha(files[names[i]!]!),finalUrl:`https://www.fec.gov/files/bulk-downloads/2026/${names[i]}`,etag:null,lastModified:null}))};return{root,manifest,close:()=>rm(root,{recursive:true,force:true})};};
const run=async(f:Awaited<ReturnType<typeof fixture>>)=>createFecBulkBootstrap(f.root,encodeFecBulkManifest(f.manifest));

describe("FEC bulk bootstrap",()=>{
 it("projects exact official fields, linkage identity, receipts, and no private fixture data",async()=>{const f=await fixture();try{const out=await run(f),text=Buffer.from(encodeFecBulkBootstrap(out)).toString();expect(out.candidates[0]).toMatchObject({candidateId:"P00000001",office:"P",principalCommitteeId:"C00000001"});expect(out.committees[0]).toEqual({committeeId:"C00000001",designation:"D",committeeType:"H"});expect(out.linkages[0]?.linkageId).toBe("1");expect(out.sourceReceipts.map(x=>[x.archive,x.member])).toEqual([["ccl26.zip","ccl.txt"],["cm26.zip","cm.txt"],["cn26.zip","cn.txt"],["weball26.zip","weball26.txt"]]);for(const secret of ["Jane Private","Committee Private","treasurer","address","zip-secret"])expect(text).not.toContain(secret);}finally{await f.close();}});
 it("accepts the official FEC DEFLATE and safe extra-field profile",async()=>{const f=await fixture();try{const parts=base(),members={"cn26.zip":["cn.txt",parts.cn],"cm26.zip":["cm.txt",parts.cm],"ccl26.zip":["ccl.txt",parts.ccl],"weball26.zip":["weball26.txt",parts.web]} as const;for(const entry of f.manifest.entries){const [member,text]=members[entry.fileName as keyof typeof members];const bytes=officialZip(member,Buffer.from(text));await writeFile(join(f.root,entry.fileName),bytes);Object.assign(entry,{byteSize:bytes.length,sha256:sha(bytes)});}expect((await run(f)).coherence.complete).toBe(true);}finally{await f.close();}});
 it("rejects a selected archive symlink",async()=>{const f=await fixture();try{await unlink(join(f.root,"cn26.zip"));await symlink(join(f.root,"cm26.zip"),join(f.root,"cn26.zip"));code(()=>createFecBulkBootstrap(f.root,encodeFecBulkManifest(f.manifest)),"FEC_BULK_FILE_INVALID");}finally{await f.close();}});
 it.each([["1","1.00"],["1.2","1.20"],[".50","0.50"],["-.50","-0.50"],["-2","-2.00"],["-0","0.00"]])("canonicalizes parsed money %s",async(value,want)=>{const f=await fixture(p=>p.web=row(["P00000001","","","","",value,"",value,"","",value,...Array(16).fill(""),"07/18/2026","",""]));try{expect((await run(f)).summaries[0]).toMatchObject({totalReceipts:want,totalDisbursements:want,cashOnHandCloseOfPeriod:want});}finally{await f.close();}});
 it.each(["90071992547409.92","1e2","1.234"])("rejects noncanonical money %s",async(value)=>{const f=await fixture(p=>p.web=row(["P00000001","","","","",value,"","","","","",...Array(16).fill(""),"","",""]));try{code(()=>createFecBulkBootstrap(f.root,encodeFecBulkManifest(f.manifest)),"FEC_BULK_FIELD_INVALID");}finally{await f.close();}});
 it.each([["02/29/2024",true],["02/29/2023",false],["13/01/2026",false]])("validates FEC dates",async(date,ok)=>{const f=await fixture(p=>p.web=row(["P00000001","","","","","","","","","","",...Array(16).fill(""),date,"",""]));try{if(ok)expect((await run(f)).summaries[0]?.coverageEndDate).toBe("2024-02-29");else code(()=>createFecBulkBootstrap(f.root,encodeFecBulkManifest(f.manifest)),"FEC_BULK_FIELD_INVALID");}finally{await f.close();}});
 it.each([["cn","P00000001"],["cm","C00000001"],["ccl","0001"],["web","P00000001"]] as const)("rejects duplicate %s primary keys",async(kind,id)=>{const f=await fixture(p=>p[kind]+=p[kind].replace(kind==="ccl"?"0001":kind==="cm"?"C00000001":"P00000001",id));try{code(()=>createFecBulkBootstrap(f.root,encodeFecBulkManifest(f.manifest)),"FEC_BULK_DUPLICATE_KEY");}finally{await f.close();}});
 it.each(["cn","ccl","web"] as const)("quarantines unresolved references from %s",async(kind)=>{const f=await fixture(p=>{if(kind==="cn")p.cn=p.cn.replace("C00000001","C00000002");if(kind==="ccl")p.ccl=p.ccl.replace("P00000001","P00000002");if(kind==="web")p.web=p.web.replace("P00000001","P00000002");});try{const coherence=(await run(f)).coherence;expect(coherence.complete).toBe(false);expect(kind==="cn"?coherence.unresolvedPrincipalCommittees:kind==="ccl"?coherence.unresolvedLinkageCandidates:coherence.unresolvedSummaryCandidates).toHaveLength(1);}finally{await f.close();}});
 it("quarantines an unresolved linkage committee",async()=>{const f=await fixture(p=>p.ccl=p.ccl.replace("C00000001","C00000002"));try{const coherence=(await run(f)).coherence;expect(coherence.complete).toBe(false);expect(coherence.unresolvedLinkageCommittees).toHaveLength(1);}finally{await f.close();}});
 it.each(["unknown kind","duplicate","missing","wrong url","wrong final url","placeholder","noncanonical order"])("validates manifest %s",async(which)=>{const f=await fixture();try{const m={...f.manifest,entries:[...f.manifest.entries]} as unknown as {entries:Record<string,unknown>[]};if(which==="unknown kind")m.entries[0]={...m.entries[0],kind:"nope"};if(which==="duplicate")m.entries[1]={...m.entries[1],kind:"candidate_master"};if(which==="missing")m.entries.pop();if(which==="wrong url")m.entries[0]={...m.entries[0],officialUrl:"https://evil.test/cn26.zip"};if(which==="wrong final url")m.entries[0]={...m.entries[0],finalUrl:"https://www.fec.gov/x"};if(which==="placeholder")m.entries[0]={...m.entries[0],etag:"placeholder"};if(which==="noncanonical order"){const bytes=Buffer.from(JSON.stringify({...m,entries:[...m.entries].reverse()}));code(()=>decodeFecBulkManifest(bytes),"FEC_BULK_MANIFEST_NONCANONICAL");return;}code(()=>encodeFecBulkManifest(m as never),"FEC_BULK_MANIFEST_INVALID");}finally{await f.close();}});
 it("accepts null manifest headers",async()=>{const f=await fixture();try{expect((await run(f)).sourceReceipts.every(x=>x.etag===null&&x.lastModified===null)).toBe(true);}finally{await f.close();}});
 it.each(["encrypted","comment","extra","path","crc","local size","method","utf8","oversize","ratio","symlink attr","malformed"])("rejects malformed ZIP %s",async(which)=>{const f=await fixture(()=>{},(name,b)=>{if(name!=="cn26.zip")return;const central=b.length-22-(46+6);if(which==="encrypted")b.writeUInt16LE(1,central+8);if(which==="comment")b.writeUInt16LE(1,b.length-2);if(which==="extra")b.writeUInt16LE(1,central+30);if(which==="path")b.write("/",central+46);if(which==="crc")b.writeUInt32LE(0,central+16);if(which==="local size")b.writeUInt32LE(999,18);if(which==="method")b.writeUInt16LE(99,central+10);if(which==="utf8")b[central+46]=0xff;if(which==="oversize")b.writeUInt32LE(4*1024*1024+1,central+24);if(which==="ratio")b.writeUInt32LE(100,central+24);if(which==="symlink attr")b.writeUInt32LE(0xa1ff0000,central+38);if(which==="malformed")b.writeUInt32LE(0,b.length-22);});try{code(()=>createFecBulkBootstrap(f.root,encodeFecBulkManifest(f.manifest)),"FEC_BULK_ZIP_INVALID");}finally{await f.close();}});
 it.each(["bad utf8","control","no lf","field count","field size"])("rejects invalid rows %s",async(which)=>{const f=await fixture(p=>{if(which==="control")p.cn=p.cn.replace("P","\u0001");if(which==="no lf")p.cn=p.cn.trimEnd();if(which==="field count")p.cn="P00000001\n";if(which==="field size")p.cn=p.cn.replace("Jane Private","x".repeat(1025));},(name,b)=>{if(which==="bad utf8"&&name==="cn26.zip")b[36]=0xff;});try{code(()=>createFecBulkBootstrap(f.root,encodeFecBulkManifest(f.manifest)),which==="bad utf8"?"FEC_BULK_ZIP_INVALID":which==="field count"||which==="field size"?"FEC_BULK_FIELD_INVALID":"FEC_BULK_ROWS_INVALID");}finally{await f.close();}});
 it.each(["nested unknown","privacy key","reordered","unsorted arrays","duplicate arrays"])("rejects invalid artifact decoder input %s",async(which)=>{const f=await fixture();try{const out=await run(f);const raw=JSON.parse(Buffer.from(encodeFecBulkBootstrap(out)).toString()) as {cycle:number;name?:string;candidates:Record<string,unknown>[];sourceReceipts:Record<string,unknown>[]} & Record<string,unknown>;if(which==="nested unknown")raw.candidates[0]!.x=1;if(which==="privacy key")raw.name="x";if(which==="unsorted arrays")raw.sourceReceipts.reverse();if(which==="duplicate arrays")raw.candidates.push(raw.candidates[0]!);const {cycle,...rest}=raw;const serialized=which==="reordered"?{cycle,...rest}:raw;const bytes=Buffer.from(JSON.stringify(serialized));code(()=>decodeFecBulkBootstrap(bytes),which==="reordered"?"FEC_BULK_NONCANONICAL":"FEC_BULK_INVALID");}finally{await f.close();}});
 it.each(["negative field count","wrong field count","large archive","large member","large rows","projected mismatch"])("rejects impossible receipt provenance: %s",async(which)=>{const f=await fixture();try{const raw=JSON.parse(Buffer.from(encodeFecBulkBootstrap(await run(f))).toString()) as {sourceReceipts:Record<string,number>[]};const receipt=raw.sourceReceipts[0]!;if(which==="negative field count")receipt.memberFieldCount=-1;if(which==="wrong field count")receipt.memberFieldCount=15;if(which==="large archive")receipt.archiveByteSize=4*1024*1024+1;if(which==="large member")receipt.memberByteSize=4*1024*1024+1;if(which==="large rows")receipt.memberRows=25_001;if(which==="projected mismatch")receipt.projectedRows+=1;code(()=>decodeFecBulkBootstrap(Buffer.from(JSON.stringify(raw))),"FEC_BULK_INVALID");}finally{await f.close();}});
 it.each(["cn26.zip","cm26.zip","weball26.zip"])("rejects a canonical decoder mutation with unprojected %s rows",async(archive)=>{const f=await fixture();try{const raw=JSON.parse(Buffer.from(encodeFecBulkBootstrap(await run(f))).toString()) as {sourceReceipts:{archive:string;memberRows:number}[]};raw.sourceReceipts.find(receipt=>receipt.archive===archive)!.memberRows+=1;code(()=>decodeFecBulkBootstrap(Buffer.from(JSON.stringify(raw))),"FEC_BULK_INVALID");}finally{await f.close();}});
 it("rejects a canonical decoder mutation with excess unsupported linkage rows",async()=>{const f=await fixture();try{const raw=JSON.parse(Buffer.from(encodeFecBulkBootstrap(await run(f))).toString()) as {sourceReceipts:{archive:string;memberRows:number}[];coherence:{complete:boolean;unsupportedLinkageRows:number}};raw.sourceReceipts.find(receipt=>receipt.archive==="ccl26.zip")!.memberRows=2;raw.coherence.complete=false;raw.coherence.unsupportedLinkageRows=2;code(()=>decodeFecBulkBootstrap(Buffer.from(JSON.stringify(raw))),"FEC_BULK_INVALID");}finally{await f.close();}});
 it("guards oversized manifest and bootstrap decoder input",()=>{code(()=>decodeFecBulkManifest(Buffer.alloc(64*1024+1)),"FEC_BULK_MANIFEST_INPUT_TOO_LARGE");code(()=>decodeFecBulkBootstrap(Buffer.alloc(32*1024*1024+1)),"FEC_BULK_INPUT_TOO_LARGE");});
});
