import { describe, expect, it } from "vitest";
import { decodeFecEnumerationPage, decodeFecFilingLedger, encodeFecEnumerationPage, encodeFecFilingIdentityV1, encodeFecFilingLedger, fecFilingIdentitySha256, fecFilingLedgerSha256, fecPassOccurrenceDigestSha256, fecSourcePageIdentitySha256, type FecEnumerationPageV1, type FecFilingIdentityV1 } from "./filing-ledger";

const identity: FecFilingIdentityV1 = { fileNumber: 12, previousFileNumber: null, canonicalFormType: "F24", baseFormType: "F24", reportType: "M12", receiptDate: "2026-01-02", reportDate: null, coverageStartDate: null, coverageEndDate: null, authoritativeAmendmentChain: [12], amendmentIndicator: "N", filerId: "H00000001", committeeId: "C00000001", electronicStatus: "electronic", rawAvailability: "available" };
const page = (): FecEnumerationPageV1 => { const entryIdentitySha256 = fecFilingIdentitySha256(identity); return { schema: "fec-v2-enumeration-page-v1", version: 1, planSha256: "a".repeat(64), provenance: { kind: "daily_partition", formType: "F24", receiptDate: "2026-01-02" }, pass: 1, pageNumber: 1, terminal: false, records: [{ identity, occurrenceIndex: 1 }], recordMultiplicity: [{ entryIdentitySha256, count: 1 }] }; };
describe("FEC filing ledger canonical artifacts", () => {
  it("has frozen identity bytes and a domain-separated golden hash", () => {
    expect(Buffer.from(encodeFecFilingIdentityV1(identity)).toString()).toBe('{"fileNumber":12,"previousFileNumber":null,"canonicalFormType":"F24","baseFormType":"F24","reportType":"M12","receiptDate":"2026-01-02","reportDate":null,"coverageStartDate":null,"coverageEndDate":null,"authoritativeAmendmentChain":[12],"amendmentIndicator":"N","filerId":"H00000001","committeeId":"C00000001","electronicStatus":"electronic","rawAvailability":"available"}\n');
    expect(fecFilingIdentitySha256(identity)).toBe("cf2876e63527976c0bb56edfcc06a28a7aa7ce119ae48e77e2b91fff0e5117bc");
  });
  it("requires DB-compatible report types and paired ordered coverage dates", () => {
    for (const mutate of [(value: FecFilingIdentityV1) => ({ ...value, reportType: "Q_1" }), (value: FecFilingIdentityV1) => ({ ...value, coverageStartDate: "2026-01-02", coverageEndDate: null }), (value: FecFilingIdentityV1) => ({ ...value, coverageStartDate: "2026-01-03", coverageEndDate: "2026-01-02" })]) expect(() => fecFilingIdentitySha256(mutate(identity))).toThrow(/FEC_LEDGER_INVALID/);
    for (const reportType of ["Q1", "24", "48", "12G", "30G", "1BAD"]) expect(fecFilingIdentitySha256({ ...identity, reportType, coverageStartDate: "2026-01-01", coverageEndDate: "2026-01-02" })).toMatch(/^[a-f0-9]{64}$/);
  });
  it("round trips newline canonical pages and excludes names", () => { const encoded = encodeFecEnumerationPage(page()), text = Buffer.from(encoded).toString(); expect(text.endsWith("\n")).toBe(true); expect(decodeFecEnumerationPage(encoded)).toEqual(page()); expect(text).not.toContain("name"); });
  it("rejects unknown fields, coercion, sparse records, and non-empty terminal", () => { for (const mutate of [(p: Record<string, unknown>) => p.extra = 1, (p: Record<string, unknown>) => ((p.records as Array<Record<string, unknown>>)[0]!.occurrenceIndex = "1"), (p: Record<string, unknown>) => { const sparse: unknown[] = []; sparse.length = 1; p.records = sparse; }, (p: Record<string, unknown>) => p.terminal = true]) { const p = page() as unknown as Record<string, unknown>; mutate(p); expect(() => decodeFecEnumerationPage(Buffer.from(JSON.stringify(p) + "\n"))).toThrow(/FEC_LEDGER/); } });
  it("binds nonterminal records to their daily or predecessor provenance", () => {
    const replace = (p: FecEnumerationPageV1, replacement: FecFilingIdentityV1) => ({ ...p, records: [{ identity: replacement, occurrenceIndex: 1 }], recordMultiplicity: [{ entryIdentitySha256: fecFilingIdentitySha256(replacement), count: 1 }] });
    expect(() => encodeFecEnumerationPage(replace(page(), { ...identity, canonicalFormType: "F3" }))).toThrow(/FEC_LEDGER_INVALID/);
    expect(() => encodeFecEnumerationPage(replace(page(), { ...identity, receiptDate: "2026-01-03" }))).toThrow(/FEC_LEDGER_INVALID/);
    const lookup = { ...page(), provenance: { kind: "predecessor_lookup" as const, formType: "F24" as const, requestedFileNumber: 12 } };
    expect(() => encodeFecEnumerationPage(lookup)).not.toThrow();
    expect(() => encodeFecEnumerationPage(replace(lookup, { ...identity, fileNumber: 13 }))).toThrow(/FEC_LEDGER_INVALID/);
    expect(() => encodeFecEnumerationPage(replace(lookup, { ...identity, canonicalFormType: "F3" }))).toThrow(/FEC_LEDGER_INVALID/);
    expect(() => encodeFecEnumerationPage({ ...page(), terminal: true, records: [], recordMultiplicity: [] })).not.toThrow();
  });
  it("binds ledger entries to identity hashes and equal pass digests", () => { const hash = fecFilingIdentitySha256(identity), ledger = { schema: "fec-v2-filing-ledger-v1" as const, version: 1 as const, planSha256: "a".repeat(64), stable: true as const, entries: [{ identity, entryIdentitySha256: hash }], sourcePageIdentities: ["b".repeat(64)], pass1DigestSha256: "c".repeat(64), pass2DigestSha256: "c".repeat(64) }; expect(decodeFecFilingLedger(encodeFecFilingLedger(ledger))).toEqual(ledger); ledger.entries[0]!.entryIdentitySha256 = "0".repeat(64); expect(() => encodeFecFilingLedger(ledger)).toThrow(/FEC_LEDGER/); });
  it("fails closed for cancellation, expired deadlines, and canary fields", () => { const controller = new AbortController(); controller.abort(); expect(() => encodeFecEnumerationPage(page(), { signal: controller.signal })).toThrow("FEC_LEDGER_ABORTED"); expect(() => encodeFecEnumerationPage(page(), { deadlineMs: Date.now() - 1 })).toThrow("FEC_LEDGER_DEADLINE"); const canary = page() as unknown as Record<string, unknown>; canary.name = "never-serialize"; expect(() => decodeFecEnumerationPage(Buffer.from(JSON.stringify(canary)))).toThrow("FEC_LEDGER_UNKNOWN_FIELD"); });
  it("commits a bytewise-sorted occurrence multiset and artifact page identities", () => { const one = [{ identity, occurrenceIndex: 1 }], twice = [{ identity, occurrenceIndex: 2 }, { identity, occurrenceIndex: 1 }]; expect(fecPassOccurrenceDigestSha256(one)).toBe(fecPassOccurrenceDigestSha256([...one].reverse())); expect(fecPassOccurrenceDigestSha256(one)).not.toBe(fecPassOccurrenceDigestSha256(twice)); expect(fecSourcePageIdentitySha256("a".repeat(64))).toBe("a".repeat(64)); expect(() => fecSourcePageIdentitySha256("A".repeat(64))).toThrow(/FEC_LEDGER/); });
  it("has frozen pass and ledger commitments", () => { const hash = fecFilingIdentitySha256(identity), digest = fecPassOccurrenceDigestSha256([{ identity, occurrenceIndex: 1 }]), ledger = { schema: "fec-v2-filing-ledger-v1" as const, version: 1 as const, planSha256: "a".repeat(64), stable: true as const, entries: [{ identity, entryIdentitySha256: hash }], sourcePageIdentities: ["b".repeat(64)], pass1DigestSha256: digest, pass2DigestSha256: digest }; expect(digest).toBe("17126ce984bbe0b4be270f54baa20f3e284e5c042ae8db3bf4504dafa31ce972"); expect(fecFilingLedgerSha256(ledger)).toBe("ac54070e1ee8296b1822993a42b8bfda0a80c96e43b3d570e74f0eeb5c55be1f"); });
});
