import type { Pool, PoolClient } from "pg";

export type FecV2SqlClient = Pick<PoolClient, "query">;
export type FecV2Pool = Pick<Pool, "connect" | "end">;
export type FecV2RunStatus = "running" | "completed" | "failed" | "invalidated";
type Instant = Date | string;
type Hash = string;
export type FecV2ArtifactKind = "enumeration_page" | "filing_ledger" | "sanitized_filing";
export type FecV2FormType = "F3" | "F3X" | "F24" | "F5";
export type FecV2AcquisitionOutcome = "source_unavailable" | "paper_filing_unreviewed" | "unsupported_layout" | "malformed_filing";
export type FecV2ReceiptDescriptor = Readonly<{ receiptId: string; artifactSha256: Hash; artifactKind: FecV2ArtifactKind; canonicalByteSize: number; upstreamEntitySha256: Hash | null; objectKey: string; versionId: string; etag: string; byteSize: number; retrievedAt: Instant; snapshotId: string }>;
export type FecV2Commitment = Readonly<{ acquisitionGraphSha256: Hash; descriptorSha256: Hash; descriptor: string }>;
export type FecV2CompletedCommitment = Readonly<FecV2Commitment & { originRunId: string; transcriptSha256: Hash }>;
export type FecV2ActiveRunCandidate = Readonly<{ runId: string; status: "running"; leaseExpiresAt: Instant; runDeadlineAt: Instant }>;
export type FecV2GraphRow = Readonly<Record<string, string | number | null | Record<string, unknown>>>;

const hash = (value: unknown): value is Hash => typeof value === "string" && /^[a-f0-9]{64}$/.test(value);
const text = (value: unknown): value is string => typeof value === "string" && value.length > 0;
const integer = (value: unknown): value is number => typeof value === "number" && Number.isSafeInteger(value);
const positive = (value: unknown): value is number => integer(value) && value > 0;
/** PostgreSQL bigint values must cross this boundary as canonical decimal text. */
const bigintSize = (value: unknown): number => { if (typeof value !== "string" || !/^[1-9]\d*$/.test(value)) fail("FEC_V2_PERSISTENCE_INPUT_INVALID"); const parsed = Number(value); if (!Number.isSafeInteger(parsed)) fail("FEC_V2_PERSISTENCE_INPUT_INVALID"); return parsed; };
const instant = (value: unknown): value is Instant => (value instanceof Date && Number.isFinite(value.getTime())) || (typeof value === "string" && value.length > 0);
const fail = (code: string): never => { throw new Error(code); };
const input = (condition: unknown): void => { if (!condition) fail("FEC_V2_PERSISTENCE_INPUT_INVALID"); };
const call = async (client: FecV2SqlClient, name: string, values: readonly unknown[]): Promise<void> => { await client.query(`SELECT public.${name}(${values.map((_, i) => `$${i + 1}`).join(",")})`, [...values]); };
const one = <T>(rows: readonly T[], code: string): T => rows.length === 1 ? rows[0]! : fail(code);
const receipt = (row: Record<string, unknown>): FecV2ReceiptDescriptor => {
  const canonicalByteSize = bigintSize(row.canonical_byte_size), byteSize = bigintSize(row.byte_size);
  input(text(row.receipt_id) && hash(row.artifact_sha256) && (row.artifact_kind === "enumeration_page" || row.artifact_kind === "filing_ledger" || row.artifact_kind === "sanitized_filing") && positive(canonicalByteSize) && (row.upstream_entity_sha256 === null || hash(row.upstream_entity_sha256)) && text(row.object_key) && text(row.version_id) && text(row.etag) && positive(byteSize) && instant(row.retrieved_at) && text(row.snapshot_id));
  return Object.freeze({ receiptId: row.receipt_id as string, artifactSha256: row.artifact_sha256 as Hash, artifactKind: row.artifact_kind as FecV2ArtifactKind, canonicalByteSize, upstreamEntitySha256: row.upstream_entity_sha256 as Hash | null, objectKey: row.object_key as string, versionId: row.version_id as string, etag: row.etag as string, byteSize, retrievedAt: row.retrieved_at as Instant, snapshotId: row.snapshot_id as string });
};

/** The runner's only acquisition-side SQL boundary. It deliberately exposes routines, never DML. */
export class FecV2AcquisitionPersistence {
  constructor(private readonly client: FecV2SqlClient, readonly releaseId: string, readonly planSha256: string, readonly runId: string, readonly token: string) {}
  claim(): Promise<void> { return call(this.client, "claim_fec_v2_run", [this.releaseId, this.planSha256, this.runId, this.token]); }
  heartbeat(): Promise<void> { return call(this.client, "heartbeat_fec_v2_run", [this.releaseId, this.planSha256, this.runId, this.token]); }
  abort(): Promise<void> { return call(this.client, "abort_fec_v2_run", [this.releaseId, this.planSha256, this.runId, this.token]); }
  stageSnapshot(value: Readonly<{ snapshotId: string; originReleaseId: string; sourceId: string; sourceUrl: string; publishedAt: Instant | null; retrievedAt: Instant; parserVersion: string; license: string }>): Promise<void> { input(text(value.snapshotId) && text(value.originReleaseId) && text(value.sourceId) && text(value.sourceUrl) && (value.publishedAt === null || instant(value.publishedAt)) && instant(value.retrievedAt) && text(value.parserVersion) && text(value.license)); return call(this.client, "stage_fec_v2_snapshot", [this.releaseId, this.planSha256, this.runId, this.token, value.snapshotId, value.originReleaseId, null, value.sourceId, value.sourceUrl, value.publishedAt, value.retrievedAt, null, value.parserVersion, value.license]); }
  stageArtifact(value: Readonly<{ sha256: Hash; kind: FecV2ArtifactKind; canonicalByteSize: number; createdAt: Instant }>): Promise<void> { input(hash(value.sha256) && (value.kind === "enumeration_page" || value.kind === "filing_ledger" || value.kind === "sanitized_filing") && positive(value.canonicalByteSize) && instant(value.createdAt)); return call(this.client, "stage_fec_v2_artifact", [this.releaseId, this.planSha256, this.runId, this.token, value.sha256, value.kind, value.canonicalByteSize, value.createdAt]); }
  stageReceipt(value: FecV2ReceiptDescriptor): Promise<void> { input(hash(value.artifactSha256) && value.canonicalByteSize === value.byteSize && positive(value.byteSize)); return call(this.client, "stage_fec_v2_receipt", [this.releaseId, this.planSha256, this.runId, this.token, value.receiptId, value.artifactSha256, value.artifactKind, value.canonicalByteSize, value.upstreamEntitySha256, value.objectKey, value.versionId, value.etag, value.byteSize, value.retrievedAt, value.snapshotId, null]); }
  stageEnumerationPage(value: Readonly<{ sha256: Hash; canonicalByteSize: number; pass: 1 | 2; formType: FecV2FormType; receiptDate: string | null; requestedFileNumber: number | null; pageNumber: number; terminal: 0 | 1 }>): Promise<void> { input(hash(value.sha256) && positive(value.canonicalByteSize) && (value.receiptDate === null) !== (value.requestedFileNumber === null) && (value.requestedFileNumber === null || positive(value.requestedFileNumber)) && positive(value.pageNumber)); return call(this.client, "stage_fec_v2_enumeration_page", [this.releaseId, this.planSha256, this.runId, this.token, value.sha256, "enumeration_page", value.canonicalByteSize, value.pass, value.formType, value.receiptDate, value.requestedFileNumber, value.pageNumber, value.terminal]); }
  stageLedgerHeader(value: Readonly<{ sha256: Hash; canonicalByteSize: number; stable: 0 | 1; finalizedAt: Instant | null }>): Promise<void> { input(hash(value.sha256) && positive(value.canonicalByteSize) && ((value.stable === 1) === (value.finalizedAt !== null)) && (value.finalizedAt === null || instant(value.finalizedAt))); return call(this.client, "stage_fec_v2_ledger_header", [this.releaseId, this.planSha256, this.runId, this.token, value.sha256, "filing_ledger", value.canonicalByteSize, value.stable, value.finalizedAt]); }
  stageLedgerEntry(value: Readonly<{ ledgerSha256: Hash; fileNumber: number; entryIdentitySha256: Hash; canonicalFormType: FecV2FormType; baseFormType: FecV2FormType; reportType: string; reportDate: string | null; receiptDate: string; coverageStart: string | null; coverageEnd: string | null; amendmentIndicator: "N" | "A" | "T" | null; filerId: string | null; committeeId: string | null; electronicStatus: "electronic" | "paper" | "unknown"; rawSourceAvailability: "available" | "unavailable" | "paper" | "unknown" }>): Promise<void> { input(hash(value.ledgerSha256) && positive(value.fileNumber) && hash(value.entryIdentitySha256) && /^[A-Z0-9]{1,8}$/.test(value.reportType) && text(value.receiptDate) && ((value.coverageStart === null) === (value.coverageEnd === null))); return call(this.client, "stage_fec_v2_ledger_entry", [this.releaseId, this.planSha256, this.runId, this.token, value.ledgerSha256, value.fileNumber, value.entryIdentitySha256, value.canonicalFormType, value.baseFormType, value.reportType, value.reportDate, value.receiptDate, value.coverageStart, value.coverageEnd, value.amendmentIndicator, value.filerId, value.committeeId, value.electronicStatus, value.rawSourceAvailability]); }
  stagePageLineage(value: Readonly<{ ledgerSha256: Hash; fileNumber: number; entryIdentitySha256: Hash; pageSha256: Hash; pass: 1 | 2; occurrenceIndex: number }>): Promise<void> { input(hash(value.ledgerSha256) && positive(value.fileNumber) && hash(value.entryIdentitySha256) && hash(value.pageSha256) && value.occurrenceIndex >= 1 && value.occurrenceIndex <= 100); return call(this.client, "stage_fec_v2_page_lineage", [this.releaseId, this.planSha256, this.runId, this.token, value.ledgerSha256, value.fileNumber, value.entryIdentitySha256, value.pageSha256, value.pass, value.occurrenceIndex]); }
  stageAmendmentLink(value: Readonly<{ ledgerSha256: Hash; fileNumber: number; entryIdentitySha256: Hash; predecessorFileNumber: number }>): Promise<void> { input(hash(value.ledgerSha256) && positive(value.fileNumber) && hash(value.entryIdentitySha256) && positive(value.predecessorFileNumber) && value.fileNumber !== value.predecessorFileNumber); return call(this.client, "stage_fec_v2_amendment_link", [this.releaseId, this.planSha256, this.runId, this.token, value.ledgerSha256, value.fileNumber, value.entryIdentitySha256, value.predecessorFileNumber]); }
  stageSanitizedFiling(value: Readonly<{ ledgerSha256: Hash; fileNumber: number; entryIdentitySha256: Hash; sha256: Hash; canonicalByteSize: number; reportDate: string | null }>): Promise<void> { input(hash(value.ledgerSha256) && positive(value.fileNumber) && hash(value.entryIdentitySha256) && hash(value.sha256) && positive(value.canonicalByteSize)); return call(this.client, "stage_fec_v2_sanitized_filing", [this.releaseId, this.planSha256, this.runId, this.token, value.ledgerSha256, value.fileNumber, value.entryIdentitySha256, value.sha256, "sanitized_filing", value.canonicalByteSize, value.reportDate]); }
  stageAcquisitionOutcome(value: Readonly<{ ledgerSha256: Hash; fileNumber: number; entryIdentitySha256: Hash; outcome: FecV2AcquisitionOutcome }>): Promise<void> { input(hash(value.ledgerSha256) && positive(value.fileNumber) && hash(value.entryIdentitySha256)); return call(this.client, "stage_fec_v2_acquisition_outcome", [this.releaseId, this.planSha256, this.runId, this.token, value.ledgerSha256, value.fileNumber, value.entryIdentitySha256, value.outcome]); }
  finalizeStagedSnapshot(snapshotId: string): Promise<void> { input(text(snapshotId)); return call(this.client, "finalize_fec_v2_staged_snapshot", [this.releaseId, this.planSha256, this.runId, this.token, snapshotId]); }
  promote(graph: Hash, descriptor: Hash, transcript: Hash): Promise<void> { input(hash(graph) && hash(descriptor) && hash(transcript)); return call(this.client, "promote_fec_v2_acquisition", [this.releaseId, this.planSha256, this.runId, this.token, graph, descriptor, transcript]); }
  async status(): Promise<FecV2RunStatus | undefined> { const result = await this.client.query<{ status: unknown }>("SELECT status FROM public.read_fec_v2_run_status($1,$2,$3)", [this.releaseId, this.planSha256, this.runId]); const row = result.rows[0]; if (!row) return undefined; if (result.rows.length !== 1 || !["running", "completed", "failed", "invalidated"].includes(row.status as string)) fail("FEC_V2_RUN_STATUS_INVALID"); return row.status as FecV2RunStatus; }
  async consumeCompletedReuse(attestationId: string, graph: Hash, descriptor: Hash, transcript: Hash): Promise<Readonly<{ descriptor: string; descriptorSha256: Hash }>> { input(text(attestationId) && hash(graph) && hash(descriptor) && hash(transcript)); const result = await this.client.query<{ descriptor: unknown; descriptor_sha256: unknown }>("SELECT * FROM public.consume_fec_v2_completed_reuse_attestation($1,$2,$3,$4,$5,$6,$7)", [this.releaseId, this.planSha256, this.runId, attestationId, graph, descriptor, transcript]); const row = one(result.rows, "FEC_V2_COMPLETED_REUSE_INVALID"); if (typeof row.descriptor !== "string" || !hash(row.descriptor_sha256)) fail("FEC_V2_COMPLETED_REUSE_INVALID"); return Object.freeze({ descriptor: row.descriptor as string, descriptorSha256: row.descriptor_sha256 as Hash }); }
  reapExpiredRun(expiredRunId: string, newRunId: string, newToken: string): Promise<void> { input(text(expiredRunId) && text(newRunId) && hash(newToken)); return call(this.client, "reap_expired_fec_v2_run", [this.releaseId, this.planSha256, expiredRunId, newRunId, newToken]); }
  async activeRunCandidate(): Promise<FecV2ActiveRunCandidate | undefined> {
    const result = await this.client.query<{ run_id: unknown; status: unknown; lease_expires_at: unknown; run_deadline_at: unknown }>("SELECT * FROM public.read_fec_v2_active_run_candidate($1,$2)", [this.releaseId, this.planSha256]);
    if (result.rows.length === 0) return undefined;
    const row = one(result.rows, "FEC_V2_ACTIVE_RUN_CANDIDATE_INVALID");
    if (!text(row.run_id) || row.status !== "running" || !instant(row.lease_expires_at) || !instant(row.run_deadline_at)) fail("FEC_V2_ACTIVE_RUN_CANDIDATE_INVALID");
    return Object.freeze({ runId: row.run_id as string, status: "running", leaseExpiresAt: row.lease_expires_at as Instant, runDeadlineAt: row.run_deadline_at as Instant });
  }
}

export async function lockFecV2Orchestration(client: FecV2SqlClient, releaseId: string, planSha256: string): Promise<void> {
  input(text(releaseId) && hash(planSha256));
  await client.query("SELECT pg_advisory_lock(hashtextextended('dsa_seats_fec_v2_orchestration:' || $1 || ':' || $2, 0))", [releaseId, planSha256]);
}
export async function unlockFecV2Orchestration(client: FecV2SqlClient, releaseId: string, planSha256: string): Promise<void> {
  const result = await client.query<{ pg_advisory_unlock: unknown }>("SELECT pg_advisory_unlock(hashtextextended('dsa_seats_fec_v2_orchestration:' || $1 || ':' || $2, 0))", [releaseId, planSha256]);
  if (result.rows.length !== 1 || result.rows[0]!.pg_advisory_unlock !== true) fail("FEC_V2_ORCHESTRATION_UNLOCK_FAILED");
}

export class FecV2ReplayVerifierPersistence {
  constructor(private readonly client: FecV2SqlClient, readonly releaseId: string, readonly planSha256: string, readonly runId: string) {}
  async stagedCommitment(): Promise<FecV2Commitment> { const result = await this.client.query<{ acquisition_graph_sha256: unknown; descriptor_sha256: unknown; descriptor: unknown }>("SELECT * FROM public.read_fec_v2_staged_acquisition_commitment($1,$2,$3)", [this.releaseId, this.planSha256, this.runId]); const row = one(result.rows, "FEC_V2_REPLAY_COMMITMENT_INVALID"); if (!hash(row.acquisition_graph_sha256) || !hash(row.descriptor_sha256) || typeof row.descriptor !== "string") fail("FEC_V2_REPLAY_COMMITMENT_INVALID"); return Object.freeze({ acquisitionGraphSha256: row.acquisition_graph_sha256 as Hash, descriptorSha256: row.descriptor_sha256 as Hash, descriptor: row.descriptor as string }); }
  async stagedReceiptDescriptors(): Promise<readonly FecV2ReceiptDescriptor[]> { const result = await this.client.query<Record<string, unknown>>("SELECT * FROM public.read_fec_v2_staged_receipt_descriptors($1,$2,$3)", [this.releaseId, this.planSha256, this.runId]); try { return Object.freeze(result.rows.map(receipt)); } catch { return fail("FEC_V2_STAGED_RECEIPT_DESCRIPTOR_INVALID"); } }
  private async stagedPage(name: string): Promise<readonly FecV2GraphRow[]> { const result = await this.client.query<Record<string, unknown>>(`SELECT * FROM public.${name}($1,$2,$3,$4,$5)`, [this.releaseId, this.planSha256, this.runId, null, 1000]); if (result.rows.length > 1000) fail("FEC_V2_GRAPH_PAGE_INVALID"); return Object.freeze(result.rows.map(row => Object.freeze(Object.fromEntries(Object.entries(row).map(([key, value]) => [key, value === null || typeof value === "string" || typeof value === "number" ? value : fail("FEC_V2_GRAPH_PAGE_INVALID")]))))); }
  async stagedEnumerationPages(): Promise<readonly FecV2GraphRow[]> { return this.stagedPage("read_fec_v2_staged_enumeration_pages_page"); }
  async stagedLedgerHeaders(): Promise<readonly FecV2GraphRow[]> { return this.stagedPage("read_fec_v2_staged_ledger_headers_page"); }
  async stagedLedgerEntries(): Promise<readonly FecV2GraphRow[]> { return this.stagedPage("read_fec_v2_staged_ledger_entries_page"); }
  async stagedPageLineage(): Promise<readonly FecV2GraphRow[]> { return this.stagedPage("read_fec_v2_staged_page_lineage_page"); }
  async stagedAmendmentLinks(): Promise<readonly FecV2GraphRow[]> { return this.stagedPage("read_fec_v2_staged_amendment_links_page"); }
  async stagedSanitizedFilings(): Promise<readonly FecV2GraphRow[]> { return this.stagedPage("read_fec_v2_staged_sanitized_filings_page"); }
  /** Completed readers are sealed-closure readers: no operational run is accepted. */
  private async completedPage(name: string, cursor: (row: FecV2GraphRow) => string): Promise<readonly FecV2GraphRow[]> {
    const rows: FecV2GraphRow[] = []; let after: string | null = null;
    for (;;) {
      const result = await this.client.query<Record<string, unknown>>(`SELECT * FROM public.${name}($1,$2,$3,$4)`, [this.releaseId, this.planSha256, after, 1000]);
      if (result.rows.length > 1000) fail("FEC_V2_GRAPH_PAGE_INVALID");
      const page = result.rows.map(row => Object.freeze(Object.fromEntries(Object.entries(row).map(([key, value]) => [key, value === null || typeof value === "string" || typeof value === "number" ? value : fail("FEC_V2_GRAPH_PAGE_INVALID")]))));
      if (rows.length + page.length > 4_000_000) fail("FEC_V2_GRAPH_PAGE_INVALID");
      rows.push(...page);
      if (page.length < 1000) return Object.freeze(rows);
      const next = cursor(page[page.length - 1]!); if (!text(next) || next === after) fail("FEC_V2_GRAPH_PAGE_INVALID"); after = next;
    }
  }
  async completedEnumerationPages(): Promise<readonly FecV2GraphRow[]> { return this.completedPage("read_fec_v2_completed_enumeration_pages_page", row => String(row.artifact_sha256)); }
  async completedLedgerHeaders(): Promise<readonly FecV2GraphRow[]> { return this.completedPage("read_fec_v2_completed_ledger_headers_page", row => String(row.artifact_sha256)); }
  async completedLedgerEntries(): Promise<readonly FecV2GraphRow[]> { return this.completedPage("read_fec_v2_completed_ledger_entries_page", row => `${row.file_number}\0${row.entry_identity_sha256}`); }
  async completedPageLineage(): Promise<readonly FecV2GraphRow[]> { return this.completedPage("read_fec_v2_completed_page_lineage_page", row => `${row.page_sha256}\u0001${row.file_number}\u0001${row.occurrence_index}`); }
  async completedAmendmentLinks(): Promise<readonly FecV2GraphRow[]> { return this.completedPage("read_fec_v2_completed_amendment_links_page", row => `${row.file_number}\0${row.entry_identity_sha256}`); }
  async completedSanitizedFilings(): Promise<readonly FecV2GraphRow[]> { return this.completedPage("read_fec_v2_completed_sanitized_filings_page", row => String(row.artifact_sha256)); }
  /** An empty result is the finite, ordinary "no completed run" case. */
  async completedCommitment(): Promise<FecV2CompletedCommitment | undefined> { const result = await this.client.query<{ origin_run_id: unknown; acquisition_graph_sha256: unknown; descriptor_sha256: unknown; transcript_sha256: unknown; descriptor: unknown }>("SELECT * FROM public.read_fec_v2_completed_acquisition_commitment($1,$2)", [this.releaseId, this.planSha256]); if (result.rows.length === 0) return undefined; const row = one(result.rows, "FEC_V2_COMPLETED_COMMITMENT_INVALID"); if (!text(row.origin_run_id) || !hash(row.acquisition_graph_sha256) || !hash(row.descriptor_sha256) || !hash(row.transcript_sha256) || typeof row.descriptor !== "string") fail("FEC_V2_COMPLETED_COMMITMENT_INVALID"); return Object.freeze({ originRunId: row.origin_run_id as string, acquisitionGraphSha256: row.acquisition_graph_sha256 as Hash, descriptorSha256: row.descriptor_sha256 as Hash, transcriptSha256: row.transcript_sha256 as Hash, descriptor: row.descriptor as string }); }
  async completedReceiptDescriptors(): Promise<readonly FecV2ReceiptDescriptor[]> { const result = await this.client.query<Record<string, unknown>>("SELECT * FROM public.read_fec_v2_completed_receipt_descriptors($1,$2)", [this.releaseId, this.planSha256]); try { return Object.freeze(result.rows.map(receipt)); } catch { return fail("FEC_V2_COMPLETED_RECEIPT_DESCRIPTOR_INVALID"); } }
  async issueStagedPromotionAttestation(graph: Hash, descriptor: Hash, transcript: Hash): Promise<string> { return this.issueAttestation("staged_promotion", graph, descriptor, transcript); }
  async issueCompletedReuseAttestation(graph: Hash, descriptor: Hash, transcript: Hash): Promise<string> { return this.issueAttestation("completed_reuse", graph, descriptor, transcript); }
  private async issueAttestation(purpose: "staged_promotion" | "completed_reuse", graph: Hash, descriptor: Hash, transcript: Hash): Promise<string> { input(hash(graph) && hash(descriptor) && hash(transcript)); const result = await this.client.query<{ issue_fec_v2_replay_attestation: unknown }>("SELECT public.issue_fec_v2_replay_attestation($1,$2,$3,$4,$5,$6,$7)", [this.releaseId, this.planSha256, this.runId, purpose, graph, descriptor, transcript]); const id = one(result.rows, "FEC_V2_REPLAY_ATTESTATION_INVALID").issue_fec_v2_replay_attestation; if (!text(id)) fail("FEC_V2_REPLAY_ATTESTATION_INVALID"); return id as string; }
}

export async function assertFecV2Role(client: FecV2SqlClient, expected: "dsa_seats_fec_v2_acquisition" | "dsa_seats_fec_v2_replay_verifier"): Promise<void> { const name = expected === "dsa_seats_fec_v2_acquisition" ? "assert_fec_v2_acquisition_admission" : "assert_fec_v2_replay_verifier_admission"; await client.query(`SELECT public.${name}()`); }
