import { createHash } from "node:crypto";
import { mkdtemp, readdir, readFile, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { describe, expect, it, vi } from "vitest";
import { acquireAndStoreFecV2SanitizedFilingForTesting, type FecSanitizedFilingAcquisitionTestingOptions } from "./sanitized-filing-acquisition";
import { loadFecEfoLayouts } from "./efo-layout";
import { FecV2RunBudget, FecV2TransportError, streamFecDocqueryFiling } from "./fetch-client-v2";
import { fecFilingIdentitySha256, type FecFilingIdentityV1 } from "./filing-ledger";
import { createS3VersionedRawObjectStoreForTesting, type VersionedRawObjectStore, type VersionedStoreActivation } from "./versioned-artifact-store";
import { S3RawObjectStore } from "@/ingestion/core/raw-object-store";
import { encodeFecSanitizedFilingArtifact } from "./efo-sanitizer";
type MutableOptions = { -readonly [K in keyof FecSanitizedFilingAcquisitionTestingOptions]: FecSanitizedFilingAcquisitionTestingOptions[K] };
const mutable = (options: FecSanitizedFilingAcquisitionTestingOptions): MutableOptions => options as MutableOptions;
const planSha256 = "a".repeat(64), workbookSha = "c667016493df28c186445201cf8a2bcff43563bccc41b75b2bcc06366b69132b";
const identity: FecFilingIdentityV1 = { fileNumber: 12, previousFileNumber: null, canonicalFormType: "F3", baseFormType: "F3", reportType: "Q1", reportDate: "2026-03-31", receiptDate: "2026-01-02", coverageStartDate: "2026-01-01", coverageEndDate: "2026-03-31", amendmentIndicator: "N", filerId: "C12345678", committeeId: "C12345678", electronicStatus: "electronic", rawAvailability: "available", authoritativeAmendmentChain: [12] };
const fields = (n: number, v: Record<number, string>) => Array.from({ length: n }, (_, i) => v[i + 1] ?? "").join("\x1c");
const raw = () => Buffer.from(`${fields(7, { 1: "HDR", 2: "FEC", 3: "8.5", 6: "RID", 7: "R1" })}\n${fields(23, { 1: "F3N", 2: "C12345678", 12: "Q1", 16: "01/01/2026", 17: "03/31/2026" })}\n`);
const rejects = (p: Promise<unknown>, code: string) => expect(p).rejects.toMatchObject({ code });
function containsCanary(value: unknown, canary: string, seen = new Set<object>()): boolean {
  if (typeof value === "string") return value.includes(canary);
  if (value instanceof Uint8Array || Buffer.isBuffer(value)) return Buffer.from(value.buffer, value.byteOffset, value.byteLength).includes(Buffer.from(canary));
  if (value instanceof ArrayBuffer) return Buffer.from(value).includes(Buffer.from(canary));
  if (value === null || typeof value !== "object" || seen.has(value)) return false;
  seen.add(value);
  if (value instanceof Map) { for (const [key, item] of value) if (containsCanary(key, canary, seen) || containsCanary(item, canary, seen)) return true; return false; }
  const descriptors = Object.getOwnPropertyDescriptors(value);
  for (const key of Reflect.ownKeys(descriptors)) { if (typeof key === "string" && key.includes(canary)) return true; const descriptor = descriptors[key as keyof typeof descriptors]; if (descriptor && "value" in descriptor && containsCanary(descriptor.value, canary, seen)) return true; }
  return false;
}
async function setup(body = raw()) { const c = new AbortController(), budget = new FecV2RunBudget({ signal: c.signal }), layout = loadFecEfoLayouts(await readFile("data/metadata/fec-efo-layouts-v1.json"), workbookSha), activation = {} as VersionedStoreActivation, puts: Array<{ expectedSha256: string; canonicalBytes: Uint8Array; activation: VersionedStoreActivation; expectedContext: unknown }> = []; const store = { assertActivated: vi.fn((token: VersionedStoreActivation) => { if (token !== activation) throw Error("bad token"); }), putCanonical: vi.fn(async (x: { expectedSha256: string; canonicalBytes: Uint8Array; activation: VersionedStoreActivation; expectedContext: unknown }) => { puts.push(x); return { storeKind: "s3" as const, storeLocator: "test", objectKey: "k", sha256: x.expectedSha256, byteSize: x.canonicalBytes.byteLength, versionId: "v", etag: "e", planSha256, artifactKind: "sanitized_filing" as const }; }) }; const streamer = vi.fn(input => streamFecDocqueryFiling({ ...input, dependencies: { fetch: async request => { const response = new Response(body, { headers: { "content-type": "text/plain" } }); Object.defineProperty(response, "url", { value: request.toString() }); return response; } } })); const options: FecSanitizedFilingAcquisitionTestingOptions = { planSha256, ledgerIdentitySha256: fecFilingIdentitySha256(identity), identity, layout, budget, fecUrl: "https://docquery.fec.gov/dcdev/posted/12.fec" as Parameters<typeof streamFecDocqueryFiling>[0]["fecUrl"], store: store as unknown as VersionedRawObjectStore, activation, signal: c.signal, deadlineMs: budget.deadline, streamer, dependencies: undefined, sanitizerLimits: undefined }; return { c, budget, activation, store, streamer, puts, options }; }
describe("sanitized filing acquisition", () => {
  it("uses testing injection with real transport and puts exact canonical sanitized bytes", async () => { const x = await setup(), result = await acquireAndStoreFecV2SanitizedFilingForTesting(x.options); expect(result.artifact.records).toEqual([]); expect(x.streamer).toHaveBeenCalledOnce(); expect(x.puts).toHaveLength(1); expect(x.puts.every(put => Buffer.from(put.canonicalBytes).equals(Buffer.from(encodeFecSanitizedFilingArtifact(result.artifact))))).toBe(true); });
  it.each([["paper", "available", "paper_filing_unreviewed"], ["paper", "unavailable", "paper_filing_unreviewed"], ["paper", "unknown", "paper_filing_unreviewed"], ["unknown", "unavailable", "source_unavailable"], ["electronic", "paper", "source_unavailable"], ["electronic", "unavailable", "source_unavailable"], ["electronic", "unknown", "source_unavailable"]] as const)("canonicalizes and hash-verifies inaccessible %s/%s before the zero-I/O availability gate", async (electronicStatus, rawAvailability, processingOutcome) => { const x = await setup(), altered: FecFilingIdentityV1 = { ...identity, electronicStatus, rawAvailability }, ledgerIdentitySha256 = fecFilingIdentitySha256(altered); await expect(acquireAndStoreFecV2SanitizedFilingForTesting({ ...x.options, identity: altered, ledgerIdentitySha256 })).rejects.toMatchObject({ code: "FEC_SANITIZED_ACQUISITION_UNAVAILABLE", processingOutcome }); expect(x.streamer).not.toHaveBeenCalled(); expect(x.store.assertActivated).not.toHaveBeenCalled(); expect(x.store.putCanonical).not.toHaveBeenCalled(); });
  it("acquires an unknown-status filing when raw evidence is available", async () => { const x = await setup(), altered = { ...identity, electronicStatus: "unknown" as const }, ledgerIdentitySha256 = fecFilingIdentitySha256(altered); await expect(acquireAndStoreFecV2SanitizedFilingForTesting({ ...x.options, identity: altered, ledgerIdentitySha256 })).resolves.toBeDefined(); expect(x.streamer).toHaveBeenCalledOnce(); });
  it.each(["unsupported", "malformed", "anything"])("rejects illegal raw availability %s as input before zero I/O", async availability => { const x = await setup(), altered = { ...identity, rawAvailability: availability } as never; await expect(acquireAndStoreFecV2SanitizedFilingForTesting({ ...x.options, identity: altered })).rejects.toMatchObject({ code: "FEC_SANITIZED_ACQUISITION_INPUT" }); expect(x.streamer).not.toHaveBeenCalled(); expect(x.store.assertActivated).not.toHaveBeenCalled(); expect(x.store.putCanonical).not.toHaveBeenCalled(); });
  it.each([["missing", undefined], ["forged", {}]])("rejects %s activation before zero streamer calls", async (_, activation) => { const x = await setup(); await rejects(acquireAndStoreFecV2SanitizedFilingForTesting({ ...x.options, activation: activation as never }), "FEC_SANITIZED_ACQUISITION_ACTIVATION"); expect(x.streamer).not.toHaveBeenCalled(); });
  it("rejects old and store-A tokens before streaming", async () => { const x = await setup(); x.store.assertActivated.mockImplementation(() => { throw Error("old"); }); await rejects(acquireAndStoreFecV2SanitizedFilingForTesting(x.options), "FEC_SANITIZED_ACQUISITION_ACTIVATION"); expect(x.streamer).not.toHaveBeenCalled(); const y = await setup(); const storeB = { assertActivated: () => { throw Error("B"); }, putCanonical: vi.fn() } as unknown as VersionedRawObjectStore; await rejects(acquireAndStoreFecV2SanitizedFilingForTesting({ ...y.options, store: storeB }), "FEC_SANITIZED_ACQUISITION_ACTIVATION"); expect(y.streamer).not.toHaveBeenCalled(); });
  it("passes exact activation and sanitized context to put", async () => { const x = await setup(), r = await acquireAndStoreFecV2SanitizedFilingForTesting(x.options), put = x.puts[0]; expect(put.activation).toBe(x.activation); expect(put.expectedSha256).toBe(r.artifactSha256); expect(put.expectedContext).toEqual({ kind: "sanitized_filing", fileNumber: 12, ledgerIdentitySha256: fecFilingIdentitySha256(identity) }); });
  it("rejects forged receipt without putting", async () => { const x = await setup(); mutable(x.options).streamer = async input => { input.consume(raw(), { signal: input.budget.signal, deadlineMs: input.budget.deadline }); return { requestSha256: "b".repeat(64), upstreamBodySha256: "0".repeat(64), bytes: raw().byteLength, retrievedAt: "2026-01-02T00:00:00.000Z" }; }; await rejects(acquireAndStoreFecV2SanitizedFilingForTesting(x.options), "FEC_SANITIZED_ACQUISITION_RECEIPT"); expect(x.puts).toEqual([]); });
  it("poisons the sanitizer when the streamer supplies an expired attempt context", async () => { const x = await setup(); let consumed = 0; mutable(x.options).streamer = async input => { consumed++; input.consume(raw(), { signal: input.budget.signal, deadlineMs: Date.now() - 1 }); return { requestSha256: "b".repeat(64), upstreamBodySha256: "0".repeat(64), bytes: raw().byteLength, retrievedAt: "2026-01-02T00:00:00.000Z" }; }; await rejects(acquireAndStoreFecV2SanitizedFilingForTesting(x.options), "FEC_SANITIZED_ACQUISITION_DEADLINE"); expect(consumed).toBe(1); expect(x.puts).toEqual([]); });
  it.each([["NUL", Buffer.concat([raw(), Buffer.from([0])])], ["bare CR", Buffer.concat([raw(), Buffer.from("\r")])], ["lowered limit", raw()]])("maps malformed %s from the real stream consumer without storing", async (kind, body) => { const x = await setup(body); if (kind === "lowered limit") mutable(x.options).sanitizerLimits = { rawByteLimit: 1 }; await expect(acquireAndStoreFecV2SanitizedFilingForTesting(x.options)).rejects.toMatchObject({ code: "FEC_SANITIZED_ACQUISITION_MALFORMED_FILING", processingOutcome: "malformed_filing" }); expect(x.puts).toEqual([]); });
  it.each([Buffer.concat([raw(), Buffer.from("F3Z\n")]), Buffer.from(raw().toString().replace("8.5", "8.4"))])("maps unsupported layouts from the real stream consumer without storing", async body => { const x = await setup(body); await expect(acquireAndStoreFecV2SanitizedFilingForTesting(x.options)).rejects.toMatchObject({ code: "FEC_SANITIZED_ACQUISITION_UNSUPPORTED_LAYOUT", processingOutcome: "unsupported_layout" }); expect(x.puts).toEqual([]); });
  it.each([["abort", "FEC_V2_ABORTED", "FEC_SANITIZED_ACQUISITION_ABORTED"], ["deadline", "FEC_V2_TIMEOUT", "FEC_SANITIZED_ACQUISITION_DEADLINE"]] as const)("maps transport %s without storing", async (_, transportCode, acquisitionCode) => { const x = await setup(); mutable(x.options).streamer = async () => { throw new FecV2TransportError(transportCode); }; await rejects(acquireAndStoreFecV2SanitizedFilingForTesting(x.options), acquisitionCode); expect(x.puts).toEqual([]); });
  it.each(["FEC_EFO_SANITIZER_INVALID", "FEC_EFO_SANITIZER_FAILED"] as const)("maps sanitizer %s to generic error without an outcome", async sanitizerError => { const x = await setup(); mutable(x.options).streamer = async () => { throw Error(sanitizerError); }; await expect(acquireAndStoreFecV2SanitizedFilingForTesting(x.options)).rejects.toMatchObject({ code: "FEC_SANITIZED_ACQUISITION_SANITIZER", processingOutcome: undefined }); expect(x.puts).toEqual([]); });
  it("does not leak foreign transport errors", async () => { const x = await setup(); mutable(x.options).streamer = async () => { throw Error("transport canary secret"); }; await expect(acquireAndStoreFecV2SanitizedFilingForTesting(x.options)).rejects.toMatchObject({ code: "FEC_SANITIZED_ACQUISITION_TRANSPORT" }); await expect(acquireAndStoreFecV2SanitizedFilingForTesting(x.options)).rejects.not.toThrow("transport canary secret"); expect(x.puts).toEqual([]); });
  it("rejects abort before transport", async () => { const x = await setup(); x.c.abort(); await rejects(acquireAndStoreFecV2SanitizedFilingForTesting(x.options), "FEC_SANITIZED_ACQUISITION_ABORTED"); expect(x.streamer).not.toHaveBeenCalled(); });
  it("snapshots values and rejects accessor options", async () => { const x = await setup(), input = { ...x.options }; Object.defineProperty(input, "planSha256", { enumerable: true, get: () => { throw Error("getter"); } }); await rejects(acquireAndStoreFecV2SanitizedFilingForTesting(input), "FEC_SANITIZED_ACQUISITION_INPUT"); expect(x.streamer).not.toHaveBeenCalled(); });
  it("keeps production API seam-free and guards testing API", async () => { const source = await readFile("src/ingestion/fec/sanitized-filing-acquisition.ts", "utf8"); expect(source).toMatch(/FecSanitizedFilingAcquisitionOptions = Base/); const env = process.env as Record<string, string | undefined>, prior = env.NODE_ENV; env.NODE_ENV = "production"; try { const x = await setup(); expect(() => acquireAndStoreFecV2SanitizedFilingForTesting(x.options)).toThrow("FEC_SANITIZED_ACQUISITION_INPUT"); } finally { if (prior === undefined) delete env.NODE_ENV; else env.NODE_ENV = prior; } });
  it("proves Task 6 raw canaries never cross any retained or diagnostic boundary", async () => {
    const canaries = ["S6-PAYEE-CANARY", "S6-NAME-CANARY", "S6-ADDRESS-CANARY", "s6-email@example.test", "S6-PHONE-CANARY", "S6-TRANSACTION-CANARY", "S6-BACKREF-CANARY"];
    const temp = await mkdtemp(join(tmpdir(), "task6-raw-canaries-")), tempBefore = await readdir(temp), commands: Array<{ name: string; input: Record<string, unknown> }> = [], diagnostics: unknown[] = [];
    const output = new Map<string, Uint8Array>(); let version = 0, corrupt = false;
    const sender = { send: async (command: { constructor: { name: string }; input: Record<string, unknown> }) => {
      const name = command.constructor.name, input = command.input; commands.push({ name, input });
      if (name === "GetBucketVersioningCommand") return { Status: "Enabled" };
      if (name === "HeadObjectCommand") { const body = output.get(String(input.Key)); if (!body) throw Object.assign(new Error("missing"), { name: "NotFound" }); return { VersionId: `v${version}`, ETag: "etag", Metadata: { sha256: String(input.Key).slice(-64) }, ContentLength: body.byteLength }; }
      if (name === "PutObjectCommand") { const body = Uint8Array.from(input.Body as Uint8Array); output.set(String(input.Key), body); version++; return { VersionId: `v${version}`, ETag: "etag" }; }
      if (name === "GetObjectCommand") { const body = output.get(String(input.Key))!; const replay = corrupt ? Uint8Array.from([body[0]! ^ 1, ...body.slice(1)]) : body; return { VersionId: input.VersionId, ETag: "etag", Metadata: { sha256: String(input.Key).slice(-64) }, ContentLength: replay.byteLength, Body: (async function* () { yield replay; })() }; }
      throw new Error("unexpected S3 command");
    } };
    const rawStore = new S3RawObjectStore(sender, "bucket"), store = createS3VersionedRawObjectStoreForTesting(rawStore, { mode: "local_loopback", endpointUrl: "http://127.0.0.1:9000", certificateValidation: false });
    const spies = [vi.spyOn(console, "log"), vi.spyOn(console, "info"), vi.spyOn(console, "warn"), vi.spyOn(console, "error"), vi.spyOn(console, "debug"), vi.spyOn(process.stdout, "write"), vi.spyOn(process.stderr, "write")];
    try {
      const x = await setup();
      const identity = { ...x.options.identity, canonicalFormType: "F3X" as const, baseFormType: "F3X" as const };
      const scheduleA = fields(12, { 1: "SA", 2: canaries[0]!, 3: canaries[1]!, 4: canaries[2]!, 5: canaries[3]!, 6: canaries[4]! });
      const scheduleE = fields(43, { 1: "SE", 2: "C12345678", 3: canaries[5]!, 4: canaries[6]!, 5: "SA", 18: "G2024", 20: "01/02/2026", 21: "12.34", 22: "01/03/2026", 27: "S", 28: "H0CA12345" });
      const fixture = Buffer.from(`${fields(7, { 1: "HDR", 2: "FEC", 3: "8.5", 6: "RID", 7: "R1" })}\n${fields(22, { 1: "F3XN", 2: "C12345678", 10: "Q1", 14: "01/01/2026", 15: "03/31/2026" })}\n${scheduleA}\n${scheduleE}\n`);
      const token = await store.preflight({ deadlineMs: Date.now() + 120_000 });
      const controller = new AbortController(), deadlineMs = Date.now() + 100_000;
      const options: FecSanitizedFilingAcquisitionTestingOptions = { ...x.options, identity, ledgerIdentitySha256: fecFilingIdentitySha256(identity), store, activation: token, budget: new FecV2RunBudget({ signal: controller.signal, deadline: deadlineMs }), signal: controller.signal, deadlineMs, streamer: input => streamFecDocqueryFiling({ ...input, dependencies: { fetch: async request => { const response = new Response(fixture, { headers: { "content-type": "text/plain" } }); Object.defineProperty(response, "url", { value: request.toString() }); return response; } } }) };
      const result = await acquireAndStoreFecV2SanitizedFilingForTesting(options), duplicate = await acquireAndStoreFecV2SanitizedFilingForTesting(options);
      expect(result.receipt.versionId).toBe("v1"); expect(duplicate.receipt).toEqual(result.receipt); expect(result.artifact.records).toHaveLength(1);
      expect(result.artifact.records[0]).toMatchObject({ transactionIdSha256: expect.stringMatching(/^[a-f0-9]{64}$/), backReferenceIdSha256: expect.stringMatching(/^[a-f0-9]{64}$/) });
      expect(result.artifact.records[0]).toMatchObject({ transactionIdSha256: createHash("sha256").update("fec-schedule-e:transaction-id:v1\0", "ascii").update(canaries[5]!, "ascii").digest("hex"), backReferenceIdSha256: createHash("sha256").update("fec-schedule-e:back-reference-id:v1\0", "ascii").update(canaries[6]!, "ascii").digest("hex") });
      expect(containsCanary(result.artifact, "SA")).toBe(false);
      expect(commands.filter(command => command.name === "PutObjectCommand")).toHaveLength(1);
      expect(commands.find(command => command.name === "PutObjectCommand")?.input.Body).toEqual(expect.any(Uint8Array));
      expect(commands.filter(command => command.name === "GetObjectCommand").every(command => command.input.VersionId === "v1")).toBe(true);
      corrupt = true;
      try { await store.readExactVersion(result.receipt, { activation: token, deadlineMs: Date.now() + 1_000, expectedContext: { kind: "sanitized_filing", fileNumber: 12, ledgerIdentitySha256: options.ledgerIdentitySha256 } }); } catch (error) { diagnostics.push(error, error instanceof Error ? error.stack : undefined); }
      corrupt = false;
      try { await store.readExactVersion(result.receipt, { activation: token, deadlineMs: Date.now() + 1_000, expectedContext: { kind: "sanitized_filing", fileNumber: 13, ledgerIdentitySha256: options.ledgerIdentitySha256 } }); } catch (error) { diagnostics.push(error, error instanceof Error ? error.stack : undefined); }
      const tempAfter = await readdir(temp), tempContents = await Promise.all(tempAfter.map(name => readFile(join(temp, name))));
      const actualSurfaces = [
        result, duplicate, result.receipt, duplicate.receipt, result.upstreamProvenance, duplicate.upstreamProvenance,
        ...commands, ...commands.map(command => command.input), ...commands.filter(command => command.name === "PutObjectCommand").map(command => command.input.Body),
        ...diagnostics, ...spies.flatMap(spy => spy.mock.calls), tempBefore, tempAfter, ...tempContents,
      ];
      for (const canary of canaries) for (const surface of actualSurfaces) expect(containsCanary(surface, canary)).toBe(false);
      expect(tempBefore).toEqual([]); expect(tempAfter).toEqual([]);
    } finally { for (const spy of spies) spy.mockRestore(); await rm(temp, { recursive: true, force: true }); }
  });
  it("canary scanner recursively examines descriptor data without invoking getters", () => {
    const canary = "S6-SCANNER-CANARY", control = Buffer.from(canary), guarded: Record<string, unknown> = { bytes: control, buffer: control.buffer.slice(control.byteOffset, control.byteOffset + control.byteLength), nested: new Map([["key", [canary]]]) };
    Object.defineProperty(guarded, "trap", { enumerable: true, get: () => { throw Error("getter invoked"); } });
    expect(containsCanary(guarded, canary)).toBe(true);
    delete guarded.bytes; delete guarded.buffer; guarded.nested = new Map();
    expect(containsCanary(guarded, canary)).toBe(false);
  });
});
