import { createHash } from "node:crypto";
import { describe, expect, it } from "vitest";
import { parseSanitizedScheduleERecord, type ParseSanitizedScheduleERecordInput, type ScheduleEPositions } from "./schedule-e";

const bytes = (value: string) => Buffer.from(value, "ascii");
const positions: ScheduleEPositions = { amount: 21, backReferenceSchedule: 5, backReferenceTransactionId: 4, candidateId: 28, disseminationDate: 20, electionCode: 18, expenditureDate: 22, filerId: 2, memoCode: 43, supportOppose: 27, transactionId: 3 };
const defaults: Record<keyof ScheduleEPositions, string> = { amount: "12.34", backReferenceSchedule: "SCH", backReferenceTransactionId: "BACK", candidateId: "H0ABC1234", disseminationDate: "02/29/2024", electionCode: "P2024", expenditureDate: "", filerId: "C12345678", memoCode: "X", supportOppose: "S", transactionId: "TX-1" };
const row = (overrides: Partial<Record<keyof ScheduleEPositions, string>> = {}, changes: Partial<ParseSanitizedScheduleERecordInput> = {}): ParseSanitizedScheduleERecordInput => {
  const activePositions = changes.positions ?? positions;
  const fields = Array.from({ length: 43 }, () => bytes(""));
  for (const key of Object.keys(activePositions) as (keyof ScheduleEPositions)[]) { const position = activePositions[key]; if (position !== null) fields[position - 1] = bytes(overrides[key] ?? defaults[key]); }
  return { fields, positions: activePositions, fileNumber: 123, canonicalFormType: "F3X", noticeCode: null, ...changes };
};
const parse = (overrides?: Partial<Record<keyof ScheduleEPositions, string>>, changes?: Partial<ParseSanitizedScheduleERecordInput>) => parseSanitizedScheduleERecord(row(overrides, changes));

describe("Schedule E sanitizer", () => {
  it("projects only the sanctioned values", () => { const value = parse(); expect(value).toMatchObject({ amountCents: BigInt(1234), disseminationDate: "2024-02-29", expenditureDate: null, memoCode: "X", noticeCode: null, isNotice: false }); expect(Object.keys(value).sort()).toEqual(["amountCents", "backReferenceIdSha256", "backReferenceScheduleSha256", "candidateId", "canonicalFormType", "disseminationDate", "electionCode", "expenditureDate", "fileNumber", "filerId", "isNotice", "memoCode", "noticeCode", "supportOppose", "transactionIdSha256"]); });
  it.each(["0", "0.01", "92233720368547758.07"])("accepts canonical money %s", amount => expect(parse({ amount }).amountCents).toBeDefined());
  it.each(["00", "01", "1.234", "-1", "+1", "1e2", "1,000", " 1", "92233720368547758.08"])("rejects noncanonical money %s", amount => expect(() => parse({ amount })).toThrow("FEC_SCHEDULE_E_VALUE_INVALID"));
  it("accepts bigint maximum cents and rejects maximum plus one", () => { expect(parse({ amount: "92233720368547758.07" }).amountCents).toBe(BigInt("9223372036854775807")); expect(() => parse({ amount: "92233720368547758.08" })).toThrow("FEC_SCHEDULE_E_VALUE_INVALID"); });
  it.each(["02/29/2024", "12/31/2023"])("normalizes real dates %s", disseminationDate => expect(parse({ disseminationDate }).disseminationDate).toMatch(/^\d{4}-\d{2}-\d{2}$/));
  it.each(["02/29/2023", "2024-02-29", "2/29/2024"])("rejects unsupported or unreal dates %s", disseminationDate => expect(() => parse({ disseminationDate })).toThrow("FEC_SCHEDULE_E_VALUE_INVALID"));
  it("validates identities and enums", () => { for (const [key, value] of [["candidateId", "Z12345678"], ["filerId", "c12345678"], ["electionCode", "2024"], ["supportOppose", "X"], ["memoCode", "Y"]] as const) expect(() => parse({ [key]: value })).toThrow("FEC_SCHEDULE_E_VALUE_INVALID"); });
  it("rejects controls, non-ASCII, and oversized fields", () => { for (const value of [new Uint8Array([0]), new Uint8Array([0x80]), new Uint8Array(16385)]) { const input = row(), fields = [...input.fields]; fields[positions.amount! - 1] = value; expect(() => parseSanitizedScheduleERecord({ ...input, fields })).toThrow("FEC_SCHEDULE_E_FIELD_INVALID"); } });
  it("requires present 1-based positions", () => { expect(() => parse({}, { positions: { ...positions, amount: null } })).toThrow("FEC_SCHEDULE_E_POSITION_INVALID"); expect(() => parse({}, { positions: { ...positions, amount: 12 } })).toThrow("FEC_SCHEDULE_E_POSITION_INVALID"); });
  it("permits F57 absent optional positions", () => { const f57: ScheduleEPositions = { amount: 19, backReferenceSchedule: null, backReferenceTransactionId: null, candidateId: 25, disseminationDate: 18, electionCode: 16, expenditureDate: null, filerId: 2, memoCode: null, supportOppose: 24, transactionId: 3 }; const value = parse({}, { canonicalFormType: "F5", positions: f57 }); expect(value.backReferenceIdSha256).toBeNull(); expect(value.memoCode).toBeNull(); });
  it("separates hash domains with exact bytes", () => { const value = parse({ transactionId: "same", backReferenceTransactionId: "same", backReferenceSchedule: "same" }); const expected = createHash("sha256").update("fec-schedule-e:transaction-id:v1\0", "ascii").update("same", "ascii").digest("hex"); expect(value.transactionIdSha256).toBe(expected); expect(new Set([value.transactionIdSha256, value.backReferenceIdSha256, value.backReferenceScheduleSha256]).size).toBe(3); });
  it("does not expose a canary in results or errors", () => { const canary = "SECRET-CANARY"; try { parse({ transactionId: canary }); } catch (error) { expect(String(error)).not.toContain(canary); } expect(JSON.stringify(parse({ transactionId: canary }), (_, value) => typeof value === "bigint" ? value.toString() : value)).not.toContain(canary); });
  it("derives bounded notice semantics from the cover", () => { expect(parse({}, { canonicalFormType: "F24", noticeCode: "24" }).isNotice).toBe(true); expect(parse({}, { canonicalFormType: "F5", noticeCode: "48", positions: { amount: 19, backReferenceSchedule: null, backReferenceTransactionId: null, candidateId: 25, disseminationDate: 18, electionCode: 16, expenditureDate: null, filerId: 2, memoCode: null, supportOppose: 24, transactionId: 3 } }).noticeCode).toBe("48"); for (const changes of [{ canonicalFormType: "F3X" as const, noticeCode: "24" as const }, { canonicalFormType: "F24" as const, noticeCode: null }, { noticeCode: "25" as never }]) expect(() => parse({}, changes)).toThrow("FEC_SCHEDULE_E_INPUT_INVALID"); });
});
