import { createHash, timingSafeEqual } from "node:crypto";
import https from "node:https";
import { isIP } from "node:net";
import { types } from "node:util";
import { S3Client } from "@aws-sdk/client-s3";
import { NodeHttpHandler } from "@smithy/node-http-handler";
import { S3RawObjectStore, type VersionedPutResult } from "@/ingestion/core/raw-object-store";
import { decodeFecSanitizedFilingArtifact, encodeFecSanitizedFilingArtifact } from "./efo-sanitizer";
import { decodeFecEnumerationPage, decodeFecFilingLedger, encodeFecEnumerationPage, encodeFecFilingLedger, type FecFormType } from "./filing-ledger";

const BRAND: unique symbol = Symbol("VersionedRawObjectStore");
const ACTIVATION_BRAND: unique symbol = Symbol("VersionedStoreActivation");
const MAX_BYTES = 64 * 1024 * 1024;
const MAX_ACTIVATION_MS = 8 * 60 * 60_000;
const GRACE = 1_000;
const SHA = /^[a-f0-9]{64}$/;
const BUCKET = /^[a-z0-9](?:[a-z0-9.-]{1,61}[a-z0-9])?$/;
const forms = new Set<FecFormType>(["F3", "F3X", "F24", "F5"]);
const kinds = new Set<ArtifactKind>(["enumeration_page", "filing_ledger", "sanitized_filing"]);

export type ArtifactKind = "enumeration_page" | "filing_ledger" | "sanitized_filing";
export type EndpointPolicy = Readonly<{ mode: "production"; endpointUrl: string; certificateValidation: true; retentionEvidenceSha256: string } | { mode: "local_loopback"; endpointUrl: string; certificateValidation: false }>;
type Provenance = Readonly<{ kind: "daily_partition"; formType: FecFormType; receiptDate: string } | { kind: "predecessor_lookup"; formType: FecFormType; requestedFileNumber: number }>;
export type ArtifactContext = Readonly<{ kind: "enumeration_page"; provenance: Provenance; pass: 1 | 2; pageNumber: number; terminal: boolean } | { kind: "filing_ledger"; planSha256: string; artifactSha256: string } | { kind: "sanitized_filing"; fileNumber: number; ledgerIdentitySha256: string }>;
export type VersionedArtifactReceipt = Readonly<{ storeKind: "s3"; storeLocator: string; objectKey: string; sha256: string; byteSize: number; versionId: string; etag: string; planSha256: string; artifactKind: ArtifactKind }>;
export type PersistedArtifactDescriptor = Readonly<{ plan: string; kind: ArtifactKind; hash: string; key: string; version: string; etag: string; size: number }>;
export type VersionedStoreActivation = Readonly<{ versioning: "enabled"; tlsBinding: "certificate_validation_enabled" | "local_loopback_unencrypted"; retentionEvidence: "external_operator_evidence"; activationBinding: string; expiresAtMs: number; readonly [ACTIVATION_BRAND]?: true }>;
export type VersioningPreflight = VersionedStoreActivation;
export type CanonicalArtifactInput = Readonly<{ activation: VersionedStoreActivation; planSha256: string; artifactKind: ArtifactKind; canonicalBytes: Uint8Array; expectedSha256: string; signal?: AbortSignal; deadlineMs: number; expectedContext: unknown }>;
export interface VersionedRawObjectStore { readonly [BRAND]: true; preflight(options: Readonly<{ signal?: AbortSignal; deadlineMs: number }>): Promise<VersionedStoreActivation>; assertActivated(token: VersionedStoreActivation, options: Readonly<{ signal?: AbortSignal; deadlineMs: number }>): void; putCanonical(input: CanonicalArtifactInput): Promise<VersionedArtifactReceipt>; readExactVersion(receipt: VersionedArtifactReceipt, options: Readonly<{ activation: VersionedStoreActivation; signal?: AbortSignal; deadlineMs: number; expectedContext: unknown }>): Promise<Uint8Array>; readPersistedExactVersion(descriptor: PersistedArtifactDescriptor, options: Readonly<{ activation: VersionedStoreActivation; signal?: AbortSignal; deadlineMs: number }>): Promise<Readonly<{ bytes: Uint8Array; context: ArtifactContext }>>; }
export type S3VersionedStoreConfig = Readonly<{ bucket: string; policy: EndpointPolicy; client: Readonly<{ region: string; endpoint: string; forcePathStyle: true; credentials: Readonly<{ accessKeyId: string; secretAccessKey: string; sessionToken?: string }> }> }>;
export const createProductionS3ClientConfig = (
  client: S3VersionedStoreConfig["client"],
  createHandler: (options: { httpsAgent: https.Agent }) => NodeHttpHandler = options => new NodeHttpHandler(options),
) => Object.freeze({
  ...client,
  // The AWS SDK decorates static credentials with internal provenance
  // metadata. Keep our parsed configuration immutable, but give the SDK its
  // own mutable credentials object so production requests do not fail before
  // signing.
  credentials: { ...client.credentials },
  requestHandler: createHandler({ httpsAgent: new https.Agent({ rejectUnauthorized: true }) }),
});
type Limits = Readonly<{ maxConcurrency?: number; maxInFlightBytes?: number }>;
type Code = "ABORTED" | "DEADLINE" | "INVALID" | "FAILED" | "VERIFY" | "ACTIVATION" | "CLEANUP";
class StoreError extends Error { constructor(readonly code: Code) { super(code); } }
const fail = (code: Code): never => { throw new StoreError(code); };
const hash = (bytes: Uint8Array): string => createHash("sha256").update(bytes).digest("hex");
const opaque = (value: unknown): value is string => typeof value === "string" && value.length > 0 && value.length <= 1024 && value !== "null";
const equal = (a: Uint8Array, b: Uint8Array): boolean => a.byteLength === b.byteLength && timingSafeEqual(a, b);
const positive = (value: unknown): value is number => typeof value === "number" && Number.isSafeInteger(value) && value > 0;
const check = (signal: AbortSignal | undefined, deadlineMs: number): void => { if (!Number.isFinite(deadlineMs) || deadlineMs > Date.now() + MAX_ACTIVATION_MS) fail("INVALID"); if (signal?.aborted) fail("ABORTED"); if (deadlineMs <= Date.now()) fail("DEADLINE"); };
export const fecV2ObjectKey = (planSha256: string, kind: ArtifactKind, sha256: string): string => `fec-v2/${planSha256}/${kind}/artifact.${sha256}`;
const ownedBytes = (value: Uint8Array): Uint8Array => { if (!ArrayBuffer.isView(value) || Object.prototype.toString.call(value) !== "[object Uint8Array]" || types.isSharedArrayBuffer(value.buffer) || value.byteLength > MAX_BYTES) fail("INVALID"); return Uint8Array.from(value); };
const hostname = (url: URL): string => url.hostname.toLowerCase().replace(/^\[|\]$/g, "").replace(/\.+$/, "");
/** True only for literal IPv4 loopback addresses and the IPv6 loopback address. */
export const isFecV2LiteralLoopbackHost = (host: string): boolean => {
  const literal = host.startsWith("[") && host.endsWith("]") ? host.slice(1, -1) : host;
  const family = isIP(literal);
  if (family === 4) return literal.split(".", 1)[0] === "127";
  if (family !== 6) return false;
  return new URL(`http://[${literal}]/`).hostname === "[::1]";
};
const policyValid = (policy: EndpointPolicy): void => { let url: URL; try { url = new URL(policy.endpointUrl); } catch { return fail("INVALID"); } const host = hostname(url), literalLoopback = isFecV2LiteralLoopbackHost(host); if (url.username || url.password || url.search || url.hash || host === "0.0.0.0" || host === "::") fail("INVALID"); if (policy.mode === "production" ? url.protocol !== "https:" || literalLoopback || host === "localhost" || host.startsWith("::ffff:") || !policy.certificateValidation || !SHA.test(policy.retentionEvidenceSha256) : url.protocol !== "http:" || !literalLoopback || policy.certificateValidation) fail("INVALID"); };
const clonePolicy = (policy: EndpointPolicy): EndpointPolicy => { let endpointUrl: string; try { endpointUrl = new URL(policy.endpointUrl).toString(); } catch { return fail("INVALID"); } const clone = policy.mode === "production" ? { mode: "production" as const, endpointUrl, certificateValidation: true as const, retentionEvidenceSha256: policy.retentionEvidenceSha256 } : { mode: "local_loopback" as const, endpointUrl, certificateValidation: false as const }; policyValid(clone); return Object.freeze(clone); };
const policyBinding = (policy: EndpointPolicy): string => hash(Buffer.from(policy.mode === "production" ? `production\0${policy.endpointUrl}\0${policy.certificateValidation}\0${policy.retentionEvidenceSha256}` : `local_loopback\0${policy.endpointUrl}\0${policy.certificateValidation}`));
const plain = (value: unknown, keys: readonly string[]): Record<string, unknown> => { if (value === null || typeof value !== "object" || Array.isArray(value) || Object.getPrototypeOf(value) !== Object.prototype || Object.keys(value).length !== keys.length || keys.some(key => !Object.prototype.hasOwnProperty.call(value, key))) fail("INVALID"); for (const key of keys) { const descriptor = Object.getOwnPropertyDescriptor(value, key); if (!descriptor || descriptor.get || descriptor.set || descriptor.value === undefined) fail("INVALID"); } return value as Record<string, unknown>; };
export const normalizeArtifactContext = (value: unknown): ArtifactContext => { const kind = value !== null && typeof value === "object" ? (value as { kind?: unknown }).kind : undefined; const x = plain(value, kind === "enumeration_page" ? ["kind", "provenance", "pass", "pageNumber", "terminal"] : kind === "filing_ledger" ? ["kind", "planSha256", "artifactSha256"] : ["kind", "fileNumber", "ledgerIdentitySha256"]); if (x.kind === "enumeration_page") { const p = plain(x.provenance, (x.provenance as { kind?: unknown })?.kind === "daily_partition" ? ["kind", "formType", "receiptDate"] : ["kind", "formType", "requestedFileNumber"]); if ((p.kind !== "daily_partition" && p.kind !== "predecessor_lookup") || !forms.has(p.formType as FecFormType) || !(x.pass === 1 || x.pass === 2) || !positive(x.pageNumber) || x.pageNumber > 1000 || typeof x.terminal !== "boolean" || (p.kind === "daily_partition" ? typeof p.receiptDate !== "string" || !/^\d{4}-\d\d-\d\d$/.test(p.receiptDate) : !positive(p.requestedFileNumber))) fail("INVALID"); const provenance: Provenance = p.kind === "daily_partition" ? Object.freeze({ kind: p.kind, formType: p.formType as FecFormType, receiptDate: p.receiptDate as string }) : Object.freeze({ kind: "predecessor_lookup" as const, formType: p.formType as FecFormType, requestedFileNumber: p.requestedFileNumber as number }); return Object.freeze({ kind: "enumeration_page" as const, provenance, pass: x.pass as 1 | 2, pageNumber: x.pageNumber as number, terminal: x.terminal as boolean }); } if (x.kind === "filing_ledger" && SHA.test(x.planSha256 as string) && SHA.test(x.artifactSha256 as string)) return Object.freeze({ kind: x.kind, planSha256: x.planSha256 as string, artifactSha256: x.artifactSha256 as string }); if (x.kind === "sanitized_filing" && positive(x.fileNumber) && SHA.test(x.ledgerIdentitySha256 as string)) return Object.freeze({ kind: x.kind, fileNumber: x.fileNumber as number, ledgerIdentitySha256: x.ledgerIdentitySha256 as string }); return fail("INVALID"); };
const same = (a: ArtifactContext, b: ArtifactContext): boolean => a.kind === b.kind && (a.kind === "enumeration_page" && b.kind === "enumeration_page" ? a.pass === b.pass && a.pageNumber === b.pageNumber && a.terminal === b.terminal && a.provenance.kind === b.provenance.kind && a.provenance.formType === b.provenance.formType && (a.provenance.kind === "daily_partition" && b.provenance.kind === "daily_partition" ? a.provenance.receiptDate === b.provenance.receiptDate : a.provenance.kind === "predecessor_lookup" && b.provenance.kind === "predecessor_lookup" && a.provenance.requestedFileNumber === b.provenance.requestedFileNumber) : a.kind === "filing_ledger" && b.kind === "filing_ledger" ? a.planSha256 === b.planSha256 && a.artifactSha256 === b.artifactSha256 : a.kind === "sanitized_filing" && b.kind === "sanitized_filing" && a.fileNumber === b.fileNumber && a.ledgerIdentitySha256 === b.ledgerIdentitySha256);
const contextFor = (kind: ArtifactKind, bytes: Uint8Array, planSha256: string, signal: AbortSignal, deadlineMs: number): ArtifactContext => { try { if (kind === "enumeration_page") { const x = decodeFecEnumerationPage(bytes, { signal, deadlineMs }); if (x.planSha256 !== planSha256 || !equal(bytes, encodeFecEnumerationPage(x, { signal, deadlineMs }))) fail("INVALID"); return normalizeArtifactContext({ kind, provenance: x.provenance, pass: x.pass, pageNumber: x.pageNumber, terminal: x.terminal }); } if (kind === "filing_ledger") { const x = decodeFecFilingLedger(bytes, { signal, deadlineMs }); if (x.planSha256 !== planSha256 || !equal(bytes, encodeFecFilingLedger(x, { signal, deadlineMs }))) fail("INVALID"); return normalizeArtifactContext({ kind, planSha256: x.planSha256, artifactSha256: hash(bytes) }); } const x = decodeFecSanitizedFilingArtifact(bytes, { signal, deadlineMs }); if (x.acquisitionPlanSha256 !== planSha256 || !equal(bytes, encodeFecSanitizedFilingArtifact(x, { signal, deadlineMs }))) fail("INVALID"); return normalizeArtifactContext({ kind, fileNumber: x.fileNumber, ledgerIdentitySha256: x.ledgerIdentitySha256 }); } catch (error) { if (error instanceof StoreError) throw error; throw new StoreError(signal.aborted ? "ABORTED" : "INVALID"); } };

class Semaphore { private slots = 0; private used = 0; private poisoned = false; private queue: Array<{ size: number; resolve: () => void; reject: (error: Error) => void; remove: () => void }> = []; constructor(private readonly maxConcurrency: number, private readonly maxBytes: number) {} async take(size: number, signal: AbortSignal, deadlineMs: number): Promise<void> { if (!Number.isSafeInteger(size) || size < 0 || size > this.maxBytes) fail("INVALID"); if (this.poisoned) fail("ACTIVATION"); check(signal, deadlineMs); if (this.slots < this.maxConcurrency && this.used + size <= this.maxBytes) { this.slots++; this.used += size; return; } await new Promise<void>((resolve, reject) => { const waiter = { size, resolve: () => { waiter.remove(); this.slots++; this.used += size; resolve(); }, reject, remove: () => { clearTimeout(timer); signal.removeEventListener("abort", abort); const index = this.queue.indexOf(waiter); if (index >= 0) this.queue.splice(index, 1); } }; const abort = () => { waiter.remove(); reject(new StoreError("ABORTED")); }; const timer = setTimeout(() => { waiter.remove(); reject(new StoreError("DEADLINE")); }, Math.max(0, deadlineMs - Date.now())); signal.addEventListener("abort", abort, { once: true }); this.queue.push(waiter); this.drain(); }); } poison(): void { this.poisoned = true; const waiters = this.queue.splice(0); for (const waiter of waiters) { waiter.remove(); waiter.reject(new StoreError("ACTIVATION")); } } release(size: number): void { this.slots--; this.used -= size; this.drain(); } private drain(): void { if (this.poisoned) return; for (const waiter of [...this.queue]) { if (this.slots >= this.maxConcurrency || this.used + waiter.size > this.maxBytes) break; waiter.resolve(); } } }

class S3VersionedRawObjectStore implements VersionedRawObjectStore {
  readonly [BRAND] = true as const; private activation?: VersionedStoreActivation; private readonly storeLocator: string; private poisoned = false; private readonly sem: Semaphore; private readonly poisonController = new AbortController();
  constructor(private readonly raw: S3RawObjectStore, private readonly policy: EndpointPolicy, limits: Limits = {}) { policyValid(policy); const storeLocator = raw.storeLocator, concurrency = limits.maxConcurrency ?? 2, maxBytes = limits.maxInFlightBytes ?? 128 * 1024 * 1024; if (!opaque(storeLocator) || !Number.isInteger(concurrency) || concurrency < 1 || concurrency > 2 || !Number.isSafeInteger(maxBytes) || maxBytes < 0 || maxBytes > 128 * 1024 * 1024) fail("INVALID"); this.storeLocator = storeLocator; this.sem = new Semaphore(concurrency, maxBytes); }
  static testing(raw: S3RawObjectStore, policy: EndpointPolicy, limits?: Limits): VersionedRawObjectStore { return new S3VersionedRawObjectStore(raw, clonePolicy(policy), limits); }
  static production(config: S3VersionedStoreConfig): VersionedRawObjectStore { if (process.env.NODE_TLS_REJECT_UNAUTHORIZED === "0" || config.policy.mode !== "production") fail("INVALID"); const policy = clonePolicy(config.policy); const clone = Object.freeze({ region: config.client.region, endpoint: config.client.endpoint, forcePathStyle: true as const, credentials: Object.freeze({ accessKeyId: config.client.credentials.accessKeyId, secretAccessKey: config.client.credentials.secretAccessKey, ...(config.client.credentials.sessionToken ? { sessionToken: config.client.credentials.sessionToken } : {}) }) }); if (!BUCKET.test(config.bucket) || !clone.region || !clone.credentials.accessKeyId || !clone.credentials.secretAccessKey || clone.endpoint !== policy.endpointUrl) fail("INVALID"); return new S3VersionedRawObjectStore(new S3RawObjectStore(new S3Client(createProductionS3ClientConfig(clone)), config.bucket), policy); }
  assertActivated(token: VersionedStoreActivation, options: Readonly<{ signal?: AbortSignal; deadlineMs: number }>): void { try { check(options.signal, options.deadlineMs); } catch { fail("ACTIVATION"); } if (this.poisoned || token !== this.activation || !token || token.expiresAtMs <= Date.now() || options.deadlineMs > token.expiresAtMs || token.activationBinding !== policyBinding(this.policy)) fail("ACTIVATION"); }
  private active(deadlineMs: number): void { if (this.poisoned || !this.activation || this.activation.expiresAtMs <= Date.now() || deadlineMs > this.activation.expiresAtMs + 1_000 || this.activation.activationBinding !== policyBinding(this.policy)) fail("ACTIVATION"); }
  private poison(): void { if (!this.poisoned) { this.poisoned = true; this.sem.poison(); this.poisonController.abort(); } }
  private async operation<T>(options: Readonly<{ signal?: AbortSignal; deadlineMs: number }>, size: number, workFn: (signal: AbortSignal) => Promise<T>): Promise<T> { const { signal, deadlineMs } = options; check(signal, deadlineMs); if (this.poisoned) fail("ACTIVATION"); const controller = new AbortController(); let reason: Code | undefined, acquired = false, work: Promise<T> | undefined; const stop = (code: Code) => { reason ??= code; controller.abort(); }; const abort = () => stop("ABORTED"), poisoned = () => stop("ACTIVATION"); const timer = setTimeout(() => stop("DEADLINE"), Math.max(0, deadlineMs - Date.now())); signal?.addEventListener("abort", abort, { once: true }); this.poisonController.signal.addEventListener("abort", poisoned, { once: true }); try { await this.sem.take(size, controller.signal, deadlineMs); acquired = true; if (reason || this.poisoned) fail(reason ?? "ACTIVATION"); check(signal, deadlineMs); work = Promise.resolve().then(() => workFn(controller.signal)); const result = await Promise.race([work, new Promise<never>((_, reject) => controller.signal.addEventListener("abort", () => reject(new StoreError(reason ?? "ABORTED")), { once: true }))]); check(signal, deadlineMs); if (this.poisoned) fail("ACTIVATION"); return result; } catch (error) { if (reason && work) { const settled = await Promise.race([work.then(() => true, () => true), new Promise<boolean>(resolve => setTimeout(() => resolve(false), GRACE))]); if (!settled) this.poison(); } if (reason) throw new StoreError(reason); if (error instanceof StoreError) throw error; throw new StoreError("FAILED"); } finally { clearTimeout(timer); signal?.removeEventListener("abort", abort); this.poisonController.signal.removeEventListener("abort", poisoned); if (acquired) this.sem.release(size); } }
  async preflight(options: Readonly<{ signal?: AbortSignal; deadlineMs: number }>): Promise<VersioningPreflight> { const controls = Object.freeze({ signal: options.signal, deadlineMs: options.deadlineMs }); const result = await this.operation(controls, 0, async signal => { await this.raw.assertVersioning(signal); return Object.freeze({ versioning: "enabled" as const, tlsBinding: this.policy.mode === "production" ? "certificate_validation_enabled" as const : "local_loopback_unencrypted" as const, retentionEvidence: "external_operator_evidence" as const, activationBinding: policyBinding(this.policy), expiresAtMs: Math.min(controls.deadlineMs, Date.now() + MAX_ACTIVATION_MS) }); }); this.activation = result; return result; }
  async putCanonical(input: CanonicalArtifactInput): Promise<VersionedArtifactReceipt> { const bytes = input.canonicalBytes, planSha256 = input.planSha256, artifactKind = input.artifactKind, expectedSha256 = input.expectedSha256, deadlineMs = input.deadlineMs, expected = normalizeArtifactContext(input.expectedContext), controls = Object.freeze({ signal: input.signal, deadlineMs }); check(controls.signal, deadlineMs); this.active(deadlineMs); if (!ArrayBuffer.isView(bytes) || Object.prototype.toString.call(bytes) !== "[object Uint8Array]" || types.isSharedArrayBuffer(bytes.buffer) || bytes.byteLength > MAX_BYTES || !SHA.test(planSha256) || !SHA.test(expectedSha256) || !kinds.has(artifactKind)) fail("INVALID"); const byteSize = bytes.byteLength; let mutationMayBeVisible = false; try { return await this.operation(controls, byteSize, async signal => { const body = ownedBytes(bytes); try { if (hash(body) !== expectedSha256 || !same(expected, contextFor(artifactKind, body, planSha256, signal, deadlineMs))) fail("VERIFY"); const result = await this.raw.putKnownVersioned({ objectKey: fecV2ObjectKey(planSha256, artifactKind, expectedSha256), body, expectedByteSize: byteSize, expectedSha256, signal, onMutationAttempt: () => { mutationMayBeVisible = true; } }); mutationMayBeVisible = true; this.verifyPut(result, { planSha256, artifactKind, expectedSha256, byteSize }); const receipt = Object.freeze({ storeKind: result.storeKind, storeLocator: result.storeLocator, objectKey: result.objectKey, sha256: result.sha256, byteSize: result.byteSize, versionId: result.versionId, etag: result.etag, planSha256, artifactKind }); const replayed = ownedBytes(await this.raw.read(receipt, signal)); if (replayed.byteLength !== receipt.byteSize || hash(replayed) !== receipt.sha256 || !same(expected, contextFor(receipt.artifactKind, replayed, receipt.planSha256, signal, deadlineMs)) || !equal(replayed, body)) fail("VERIFY"); check(signal, deadlineMs); this.active(deadlineMs); return receipt; } catch (error) { if (mutationMayBeVisible) this.poison(); throw error; } finally { body.fill(0); } }); } catch (error) { if (mutationMayBeVisible) this.poison(); throw error; } }
  private verifyPut(value: VersionedPutResult, expected: Readonly<{ planSha256: string; artifactKind: ArtifactKind; expectedSha256: string; byteSize: number }>): void { if (value.storeKind !== "s3" || !opaque(value.storeLocator) || value.storeLocator !== this.storeLocator || value.objectKey !== fecV2ObjectKey(expected.planSha256, expected.artifactKind, expected.expectedSha256) || value.sha256 !== expected.expectedSha256 || value.byteSize !== expected.byteSize || !opaque(value.versionId) || !opaque(value.etag) || (value.disposition !== "created" && value.disposition !== "existing")) fail("VERIFY"); }
  async readExactVersion(receipt: VersionedArtifactReceipt, options: Readonly<{ signal?: AbortSignal; deadlineMs: number; expectedContext: unknown }>): Promise<Uint8Array> { const controls = Object.freeze({ signal: options.signal, deadlineMs: options.deadlineMs }), snapshot = Object.freeze({ ...receipt }), expected = normalizeArtifactContext(options.expectedContext); check(controls.signal, controls.deadlineMs); this.active(controls.deadlineMs); if (snapshot.storeKind !== "s3" || !opaque(snapshot.storeLocator) || !SHA.test(snapshot.planSha256) || !kinds.has(snapshot.artifactKind) || !SHA.test(snapshot.sha256) || !Number.isSafeInteger(snapshot.byteSize) || snapshot.byteSize < 0 || snapshot.byteSize > MAX_BYTES || !opaque(snapshot.versionId) || !opaque(snapshot.etag) || snapshot.objectKey !== fecV2ObjectKey(snapshot.planSha256, snapshot.artifactKind, snapshot.sha256)) fail("INVALID"); return this.operation(controls, snapshot.byteSize, async signal => { let bytes: Uint8Array | undefined; try { bytes = ownedBytes(await this.raw.read(snapshot, signal)); if (bytes.byteLength !== snapshot.byteSize || hash(bytes) !== snapshot.sha256) fail("VERIFY"); if (!same(expected, contextFor(snapshot.artifactKind, bytes, snapshot.planSha256, signal, controls.deadlineMs))) fail("VERIFY"); return bytes; } catch (error) { bytes?.fill(0); throw error; } }); }
  async readPersistedExactVersion(descriptor: PersistedArtifactDescriptor, options: Readonly<{ signal?: AbortSignal; deadlineMs: number }>): Promise<Readonly<{ bytes: Uint8Array; context: ArtifactContext }>> {
    const d = Object.freeze({ ...descriptor }), controls = Object.freeze({ signal: options.signal, deadlineMs: options.deadlineMs });
    if (!SHA.test(d.plan) || !kinds.has(d.kind) || !SHA.test(d.hash) || d.key !== fecV2ObjectKey(d.plan, d.kind, d.hash) || !opaque(d.version) || !opaque(d.etag) || !Number.isSafeInteger(d.size) || d.size < 0 || d.size > MAX_BYTES) fail("INVALID");
    check(controls.signal, controls.deadlineMs); this.active(controls.deadlineMs);
    return this.operation(controls, d.size, async signal => { let bytes: Uint8Array | undefined; try { bytes = ownedBytes(await this.raw.read({ storeKind: "s3", storeLocator: this.storeLocator, objectKey: d.key, sha256: d.hash, byteSize: d.size, versionId: d.version, etag: d.etag }, signal)); if (bytes.byteLength !== d.size || hash(bytes) !== d.hash) fail("VERIFY"); return Object.freeze({ bytes, context: contextFor(d.kind, bytes, d.plan, signal, controls.deadlineMs) }); } catch (error) { bytes?.fill(0); throw error; } });
  }
}

/** The only production construction boundary; production policy is mandatory. */
const bindActivation = (store: VersionedRawObjectStore): VersionedRawObjectStore => new Proxy(store, { get(target, key, receiver) { const value = Reflect.get(target, key, receiver); if (key === "preflight" || key === "assertActivated") return value.bind(target); if (key === "putCanonical") return async (input: CanonicalArtifactInput) => { target.assertActivated(input.activation, { signal: input.signal, deadlineMs: input.deadlineMs }); return target.putCanonical(input); }; if (key === "readExactVersion") return async (receipt: VersionedArtifactReceipt, options: Parameters<VersionedRawObjectStore["readExactVersion"]>[1]) => { target.assertActivated(options.activation, { signal: options.signal, deadlineMs: options.deadlineMs }); return target.readExactVersion(receipt, options); }; if (key === "readPersistedExactVersion") return async (descriptor: PersistedArtifactDescriptor, options: Parameters<VersionedRawObjectStore["readPersistedExactVersion"]>[1]) => { target.assertActivated(options.activation, { signal: options.signal, deadlineMs: options.deadlineMs }); return target.readPersistedExactVersion(descriptor, options); }; return value; } });
export const createS3VersionedRawObjectStore = (config: S3VersionedStoreConfig): VersionedRawObjectStore => bindActivation(S3VersionedRawObjectStore.production(config));
/** Nonproduction environment-loader boundary; never permits local loopback in production. */
export const createNonproductionS3VersionedRawObjectStore = (config: S3VersionedStoreConfig): VersionedRawObjectStore => { if (process.env.NODE_ENV === "production" || config.policy.mode !== "local_loopback") fail("INVALID"); const policy = clonePolicy(config.policy); const client = Object.freeze({ ...config.client, credentials: Object.freeze({ ...config.client.credentials }) }); if (!BUCKET.test(config.bucket) || !client.region || !client.credentials.accessKeyId || !client.credentials.secretAccessKey || client.endpoint !== policy.endpointUrl) fail("INVALID"); return bindActivation(new S3VersionedRawObjectStore(new S3RawObjectStore(new S3Client(client), config.bucket), policy)); };
/** Test-only dependency-injection entry point. Production source must not import this factory. */
export const createS3VersionedRawObjectStoreForTesting = (raw: S3RawObjectStore, policy: EndpointPolicy, limits?: Limits): VersionedRawObjectStore => { if (process.env.NODE_ENV === "production") fail("INVALID"); return bindActivation(S3VersionedRawObjectStore.testing(raw, policy, limits)); };
