"use client";

import { type FormEvent, useEffect, useRef, useState } from "react";

type ApiResult = { status?: string; senateRepresentation?: "two_seats" | "none"; houseSeat?: { officeTermId?: string; seatCycleId?: string }; senateSeats?: Array<{ senateClass?: number; officeTermId?: string; seatCycleId?: string }> };
type Status = { kind: "success" | "error"; message: string; result?: ApiResult } | null;
function messageFor(status: string | undefined) { if (status === "no_match") return "No match was found. Check the address and try again."; if (status === "ambiguous" || status === "geography_ambiguous") return "The address could not be resolved to one geography. Check the address and try again."; if (status === "vintage_mismatch" || status === "unsupported_prototype_coverage") return "This address is not available in the current release."; if (status === "disabled") return "Address lookup is not available in this deployment."; if (status === "rate_limited") return "Too many lookup attempts. Please wait and try again."; return "Address lookup is unavailable right now. Please try again later."; }
function validResult(value: unknown): ApiResult { return value && typeof value === "object" ? value as ApiResult : {}; }

export function AddressForm() {
  const [address, setAddress] = useState(""); const [csrf, setCsrf] = useState<string | null>(null); const [preparing, setPreparing] = useState(true); const [submitting, setSubmitting] = useState(false); const [status, setStatus] = useState<Status>(null);
  const controller = useRef<AbortController | null>(null); const statusRef = useRef<HTMLDivElement>(null);
  useEffect(() => { const abort = new AbortController(); controller.current = abort; fetch("/api/address/resolve", { cache: "no-store", credentials: "same-origin", signal: abort.signal }).then(async response => response.ok ? response.json() : Promise.reject(new Error("unavailable"))).then((value: unknown) => { if (!value || typeof value !== "object" || typeof (value as { csrfToken?: unknown }).csrfToken !== "string") throw new Error("invalid"); setCsrf((value as { csrfToken: string }).csrfToken); }).catch(() => { if (!abort.signal.aborted) setStatus({ kind: "error", message: "Address lookup is unavailable right now. Please try again later." }); }).finally(() => { if (!abort.signal.aborted) setPreparing(false); }); return () => { controller.current?.abort(); setAddress(""); }; }, []);
  useEffect(() => { if (status) statusRef.current?.focus(); }, [status]);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (submitting || !csrf) return; const value = address.trim(); if (value.length < 8 || value.length > 300) { setAddress(""); setStatus({ kind: "error", message: "Enter an address between 8 and 300 characters." }); return; } controller.current?.abort(); const abort = new AbortController(); controller.current = abort; setSubmitting(true); setStatus(null); try { const response = await fetch("/api/address/resolve", { method: "POST", cache: "no-store", credentials: "same-origin", signal: abort.signal, headers: { "Content-Type": "application/json", "X-CSRF-Token": csrf }, body: JSON.stringify({ address: value }) }); const result = validResult(await response.json().catch(() => ({}))); if (result.status === "matched" && result.houseSeat && Array.isArray(result.senateSeats)) setStatus({ kind: "success", message: "Seats matched for the active release.", result }); else setStatus({ kind: "error", message: messageFor(result.status) }); } catch { if (!abort.signal.aborted) setStatus({ kind: "error", message: "Address lookup is unavailable right now. Please try again later." }); } finally { setAddress(""); if (!abort.signal.aborted) setSubmitting(false); } }
  return <section className="lookup-form-wrap" aria-label="Address lookup"><aside className="lookup-disclosure"><p className="eyebrow">BEFORE YOU SUBMIT</p><p>Your address is sent to the <strong>U.S. Census Bureau</strong> in a request URL for geocoding. Review the <a href="https://www.census.gov/about/policies/privacy.html" target="_blank" rel="noreferrer">official Census privacy material</a> before continuing.</p><p>This form is off by default and is not approved for public use. Do not enter another person’s address.</p></aside><form className="lookup-form" onSubmit={submit} noValidate><label htmlFor="lookup-address">Street address<input id="lookup-address" name="address" autoComplete="street-address" value={address} onChange={event => setAddress(event.target.value)} maxLength={300} disabled={preparing || submitting} aria-describedby="lookup-address-help" /></label><p className="field-help" id="lookup-address-help">Your address is sent only when you select “Find seats.” It is not placed in this page’s URL, browser history, or storage.</p><div className="lookup-actions"><button type="submit" disabled={preparing || submitting || !csrf}>{preparing ? "Preparing secure lookup…" : submitting ? "Finding seats…" : "Find seats"}</button></div>{status && <div ref={statusRef} className={`lookup-status ${status.kind}`} role="status" aria-live="polite" tabIndex={-1}><p>{status.message}</p>{status.result && <SeatResult result={status.result} />}</div>}</form></section>;
}
function SeatResult({ result }: { result: ApiResult }) { return <div className="lookup-results"><section><h2>House</h2><p>One House seat applies to this address.</p><dl><dt>Office term</dt><dd><code>{result.houseSeat?.officeTermId}</code></dd><dt>Seat cycle</dt><dd><code>{result.houseSeat?.seatCycleId}</code></dd></dl></section><section><h2>Senate</h2>{result.senateRepresentation === "none" ? <p>This territory has no Senate representation.</p> : <><p>Two Senate seats apply to this state.</p><ol>{result.senateSeats?.map(seat => <li key={`${seat.officeTermId}-${seat.seatCycleId}`}>Class {seat.senateClass}: <code>{seat.officeTermId}</code></li>)}</ol></>}</section></div>; }
