import { createHash } from "node:crypto";
import type { PoolClient } from "pg";
import { createNationalTigerManifest, parseNationalTigerArtifacts, TIGER_2025_JURISDICTIONS, type NationalTigerArtifactManifest, type NationalTigerFeature } from "./national";
import type { RawObjectResult, RawObjectStore } from "../core/raw-object-store";
import type { SourceAdapter, ValidationIssue } from "../core/types";
import type { ReleaseId, SnapshotId } from "@/domain/contracts";

export const TIGER_ARTIFACT_LIMITS = { cd119Bytes: 100 * 1024 * 1024, statesBytes: 25 * 1024 * 1024, derivedEnvelopeBytes: 1024 * 1024 } as const;
const sha256 = (bytes: Uint8Array): string => createHash("sha256").update(bytes).digest("hex");
const validHash = (value: unknown): value is string => typeof value === "string" && /^[a-f0-9]{64}$/.test(value);
const object = (value: unknown, code: string): Record<string, unknown> => { if (!value || typeof value !== "object" || Array.isArray(value)) throw new Error(code); return value as Record<string, unknown>; };
const exact = (value: Record<string, unknown>, keys: readonly string[], code: string): void => { if (Object.keys(value).length !== keys.length || keys.some(key => !(key in value))) throw new Error(code); };
const abort = (signal?: AbortSignal): void => { if (signal?.aborted) throw new Error("INGEST_ABORTED"); };
async function body(bytes: Uint8Array): Promise<AsyncIterable<Uint8Array>> { return (async function* () { for (let offset = 0; offset < bytes.byteLength; offset += 1024 * 1024) yield bytes.subarray(offset, offset + 1024 * 1024); })(); }
function json(bytes: Uint8Array, limit: number): unknown { if (bytes.byteLength > limit) throw new Error("TIGER_INPUT_TOO_LARGE"); try { return JSON.parse(new TextDecoder("utf-8", { fatal: true }).decode(bytes)); } catch { throw new Error("TIGER_INVALID_JSON"); } }

export interface TigerAdapterOptions { readonly rawStore: RawObjectStore; readonly snapshotId: SnapshotId; readonly upstreamRelease: string; readonly parserVersion: string; readonly sourceLockSha256: string; readonly lockIds: { readonly cd119: "geo-national-cd119"; readonly states: "geo-national-states"; readonly manifest: "geo-national-manifest"; readonly bundle: "geo-national-bundle" }; readonly manifest: NationalTigerArtifactManifest; readonly cd119Bytes: Uint8Array; readonly statesBytes: Uint8Array; readonly sourceUrl: string; readonly finalizeNationwide?: (client: PoolClient, runId: string, releaseId: ReleaseId) => Promise<void>; }
export interface TigerStageRow { readonly sourceNaturalKey: string; readonly artifactId: "cd119" | "states"; readonly geoid: string; readonly stateCode: string; readonly districtCode: string | null; readonly vintage: string; readonly checksumSha256: string; }
export type TigerEnvelopeComponent = RawObjectResult;
export interface TigerEnvelopeV1 { readonly schemaVersion: 1; readonly parserVersion: string; readonly upstreamRelease: string; readonly sourceUrl: string; readonly sourceLockSha256: string; readonly lockIds: { readonly cd119: "geo-national-cd119"; readonly states: "geo-national-states"; readonly manifest: "geo-national-manifest"; readonly bundle: "geo-national-bundle" }; readonly manifest: NationalTigerArtifactManifest; readonly components: { readonly cd119: TigerEnvelopeComponent; readonly states: TigerEnvelopeComponent }; }

function decodeReceipt(value: unknown, limit: number): RawObjectResult {
  const r = object(value, "TIGER_ENVELOPE_INVALID_RECEIPT");
  const keys = r.storeKind === "s3" && "etag" in r ? ["storeKind", "storeLocator", "objectKey", "sha256", "byteSize", "versionId", "etag"] : r.storeKind === "s3" ? ["storeKind", "storeLocator", "objectKey", "sha256", "byteSize", "versionId"] : ["storeKind", "storeLocator", "objectKey", "sha256", "byteSize"];
  exact(r, keys, "TIGER_ENVELOPE_UNKNOWN_FIELD");
  if ((r.storeKind !== "local" && r.storeKind !== "s3") || typeof r.storeLocator !== "string" || !r.storeLocator || typeof r.objectKey !== "string" || !r.objectKey || r.objectKey.startsWith("/") || r.objectKey.split("/").includes("..") || !validHash(r.sha256) || typeof r.byteSize !== "number" || !Number.isSafeInteger(r.byteSize) || r.byteSize < 0 || r.byteSize > limit || !r.objectKey.includes(r.sha256)) throw new Error("TIGER_ENVELOPE_INVALID_RECEIPT");
  if (r.storeKind === "s3") { if (typeof r.versionId !== "string" || !r.versionId || ("etag" in r && (typeof r.etag !== "string" || !r.etag))) throw new Error("TIGER_ENVELOPE_INVALID_RECEIPT"); return { storeKind: "s3", storeLocator: r.storeLocator, objectKey: r.objectKey, sha256: r.sha256, byteSize: r.byteSize, versionId: r.versionId, ...(typeof r.etag === "string" ? { etag: r.etag } : {}) }; }
  return { storeKind: "local", storeLocator: r.storeLocator, objectKey: r.objectKey, sha256: r.sha256, byteSize: r.byteSize };
}
function decodeManifest(value: unknown, cd: RawObjectResult, states: RawObjectResult): NationalTigerArtifactManifest {
  const m = object(value, "TIGER_ENVELOPE_INVALID_MANIFEST"); const artifacts = object(m.artifacts, "TIGER_ENVELOPE_INVALID_MANIFEST"); const archives = object(m.sourceArchives, "TIGER_ENVELOPE_INVALID_MANIFEST");
  exact(m, ["schemaVersion", "srid", "sourceArchives", "artifacts"], "TIGER_ENVELOPE_UNKNOWN_FIELD"); exact(artifacts, ["cd119Sha256", "statesSha256", "cd119FeatureCount", "stateFeatureCount"], "TIGER_ENVELOPE_UNKNOWN_FIELD");
  const archiveKeys = [...Object.keys(TIGER_2025_JURISDICTIONS).map(fips => `tl_2025_${fips}_cd119.zip`), "tl_2025_us_state.zip"].sort();
  if (m.schemaVersion !== 1 || m.srid !== 4326 || !validHash(artifacts.cd119Sha256) || !validHash(artifacts.statesSha256) || artifacts.cd119Sha256 !== cd.sha256 || artifacts.statesSha256 !== states.sha256 || artifacts.cd119FeatureCount !== 441 || artifacts.stateFeatureCount !== 56 || Object.keys(archives).sort().length !== archiveKeys.length || archiveKeys.some((key, index) => Object.keys(archives).sort()[index] !== key) || Object.values(archives).some(value => !validHash(value))) throw new Error("TIGER_ENVELOPE_INVALID_MANIFEST");
  return { schemaVersion: 1, srid: 4326, sourceArchives: archives as Record<string, string>, artifacts: { cd119Sha256: artifacts.cd119Sha256, statesSha256: artifacts.statesSha256, cd119FeatureCount: 441, stateFeatureCount: 56 } };
}
export function encodeTigerEnvelope(envelope: TigerEnvelopeV1): Uint8Array { return Buffer.from(JSON.stringify(envelope)); }
export function decodeTigerEnvelope(bytes: Uint8Array): TigerEnvelopeV1 {
  if (bytes.byteLength > TIGER_ARTIFACT_LIMITS.derivedEnvelopeBytes) throw new Error("TIGER_DERIVED_ENVELOPE_TOO_LARGE"); let raw: unknown; try { raw = JSON.parse(new TextDecoder("utf-8", { fatal: true }).decode(bytes)); } catch { throw new Error("TIGER_ENVELOPE_INVALID_JSON"); }
  const e = object(raw, "TIGER_ENVELOPE_INVALID"); exact(e, ["schemaVersion", "parserVersion", "upstreamRelease", "sourceUrl", "sourceLockSha256", "lockIds", "manifest", "components"], "TIGER_ENVELOPE_UNKNOWN_FIELD"); const components = object(e.components, "TIGER_ENVELOPE_INVALID"); exact(components, ["cd119", "states"], "TIGER_ENVELOPE_UNKNOWN_FIELD");
  if (e.schemaVersion !== 1 || typeof e.parserVersion !== "string" || !e.parserVersion || typeof e.upstreamRelease !== "string" || !e.upstreamRelease || typeof e.sourceUrl !== "string" || !e.sourceUrl || !validHash(e.sourceLockSha256)) throw new Error("TIGER_ENVELOPE_INVALID");
  const lockIds = object(e.lockIds, "TIGER_ENVELOPE_INVALID"); exact(lockIds, ["cd119", "states", "manifest", "bundle"], "TIGER_ENVELOPE_UNKNOWN_FIELD"); if (lockIds.cd119 !== "geo-national-cd119" || lockIds.states !== "geo-national-states" || lockIds.manifest !== "geo-national-manifest" || lockIds.bundle !== "geo-national-bundle") throw new Error("TIGER_ENVELOPE_INVALID_LOCK_ID");
  const cd119 = decodeReceipt(components.cd119, TIGER_ARTIFACT_LIMITS.cd119Bytes), states = decodeReceipt(components.states, TIGER_ARTIFACT_LIMITS.statesBytes);
  return { schemaVersion: 1, parserVersion: e.parserVersion, upstreamRelease: e.upstreamRelease, sourceUrl: e.sourceUrl, sourceLockSha256: e.sourceLockSha256, lockIds: lockIds as TigerEnvelopeV1["lockIds"], manifest: decodeManifest(e.manifest, cd119, states), components: { cd119, states } };
}
export async function readTigerComponents(rawStore: RawObjectStore, envelope: TigerEnvelopeV1, signal?: AbortSignal): Promise<{ readonly cd119Bytes: Uint8Array; readonly statesBytes: Uint8Array }> {
  const [cd119Bytes, statesBytes] = await Promise.all([rawStore.read(envelope.components.cd119, signal), rawStore.read(envelope.components.states, signal)]);
  if (cd119Bytes.byteLength !== envelope.components.cd119.byteSize || statesBytes.byteLength !== envelope.components.states.byteSize || sha256(cd119Bytes) !== envelope.components.cd119.sha256 || sha256(statesBytes) !== envelope.components.states.sha256) throw new Error("TIGER_COMPONENT_RECEIPT_MISMATCH");
  return { cd119Bytes, statesBytes };
}
export function createTigerAdapter(options: TigerAdapterOptions): SourceAdapter<TigerEnvelopeV1, TigerStageRow> {
  if (!options.upstreamRelease || !options.parserVersion || !options.sourceUrl || !validHash(options.sourceLockSha256) || options.cd119Bytes.byteLength > TIGER_ARTIFACT_LIMITS.cd119Bytes || options.statesBytes.byteLength > TIGER_ARTIFACT_LIMITS.statesBytes || sha256(options.cd119Bytes) !== options.manifest.artifacts.cd119Sha256 || sha256(options.statesBytes) !== options.manifest.artifacts.statesSha256) throw new Error("TIGER_SOURCE_RECEIPT_MISMATCH");
  const parsed = parseNationalTigerArtifacts(json(options.cd119Bytes, TIGER_ARTIFACT_LIMITS.cd119Bytes), json(options.statesBytes, TIGER_ARTIFACT_LIMITS.statesBytes)); createNationalTigerManifest(options.manifest.sourceArchives, options.manifest.artifacts.cd119Sha256, options.manifest.artifacts.statesSha256, parsed);
  const rows = (features: readonly NationalTigerFeature[], artifactId: TigerStageRow["artifactId"], checksumSha256: string): TigerStageRow[] => features.map(row => ({ sourceNaturalKey: `${artifactId}:${row.sourceGeoid}`, artifactId, geoid: row.sourceGeoid, stateCode: row.stateCode, districtCode: row.districtCode, vintage: "2025", checksumSha256 }));
  return { sourceName: "tiger", adapterVersion: options.parserVersion,
    async *extract(context) { abort(context.signal); const cd119 = await options.rawStore.put({ objectKey: `tiger/${options.upstreamRelease}/cd119/${sha256(options.cd119Bytes)}.geojson`, body: await body(options.cd119Bytes), expectedSha256: sha256(options.cd119Bytes), signal: context.signal }); const states = await options.rawStore.put({ objectKey: `tiger/${options.upstreamRelease}/states/${sha256(options.statesBytes)}.geojson`, body: await body(options.statesBytes), expectedSha256: sha256(options.statesBytes), signal: context.signal }); const value = decodeTigerEnvelope(encodeTigerEnvelope({ schemaVersion: 1, parserVersion: options.parserVersion, upstreamRelease: options.upstreamRelease, sourceUrl: options.sourceUrl, sourceLockSha256: options.sourceLockSha256, lockIds: options.lockIds, manifest: options.manifest, components: { cd119, states } })); const bytes = encodeTigerEnvelope(value), checksumSha256 = sha256(bytes); const receipt = await options.rawStore.put({ objectKey: `tiger/${options.upstreamRelease}/envelope/${checksumSha256}.json`, body: await body(bytes), expectedSha256: checksumSha256, signal: context.signal }); abort(context.signal); yield { value, receipt, snapshot: { id: options.snapshotId, sourceUrl: options.sourceUrl, checksumSha256, upstreamRelease: options.upstreamRelease, publishedAt: null, license: "public-domain", usageStatus: "approved" }, expectedRecordCount: 497 }; },
    async *parse(raw) { const envelope = decodeTigerEnvelope(encodeTigerEnvelope(raw.value)); const components = await readTigerComponents(options.rawStore, envelope); const p = parseNationalTigerArtifacts(json(components.cd119Bytes, TIGER_ARTIFACT_LIMITS.cd119Bytes), json(components.statesBytes, TIGER_ARTIFACT_LIMITS.statesBytes)); for (const row of rows(p.cd119, "cd119", envelope.components.cd119.sha256)) yield { kind: "row", row }; for (const row of rows(p.states, "states", envelope.components.states.sha256)) yield { kind: "row", row }; }, naturalKey: row => row.sourceNaturalKey,
    async stage(client, runId, staged) { if (!staged.length) return; await client.query("INSERT INTO stg_tiger(run_id,release_id,source_natural_key,snapshot_id,artifact_id,geoid,state_code,district_code,vintage,checksum_sha256,redacted_extras) SELECT $1,ir.release_id,x.key,ir.snapshot_id,x.artifact_id,x.geoid,x.state_code,x.district_code,x.vintage,x.checksum,'{}'::jsonb FROM ingest_runs ir CROSS JOIN unnest($2::text[],$3::text[],$4::text[],$5::text[],$6::text[],$7::text[],$8::text[]) AS x(key,artifact_id,geoid,state_code,district_code,vintage,checksum) WHERE ir.id=$1", [runId, staged.map(x => x.sourceNaturalKey), staged.map(x => x.artifactId), staged.map(x => x.geoid), staged.map(x => x.stateCode), staged.map(x => x.districtCode), staged.map(x => x.vintage), staged.map(x => x.checksumSha256)]); },
    async validateStaged(client, runId): Promise<readonly ValidationIssue[]> { const result = await client.query<{ total: unknown; cd: unknown; states: unknown; distinct_keys: unknown; bound: unknown }>("SELECT count(*) AS total,count(*) FILTER (WHERE artifact_id='cd119') AS cd,count(*) FILTER (WHERE artifact_id='states') AS states,count(DISTINCT artifact_id || ':' || geoid) AS distinct_keys,count(*) FILTER (WHERE (artifact_id='cd119' AND checksum_sha256=$2) OR (artifact_id='states' AND checksum_sha256=$3)) AS bound FROM stg_tiger WHERE run_id=$1", [runId, options.manifest.artifacts.cd119Sha256, options.manifest.artifacts.statesSha256]); const r = result.rows[0]; const number = (v: unknown): number => typeof v === "number" ? v : Number(v); return r && number(r.total) === 497 && number(r.cd) === 441 && number(r.states) === 56 && number(r.distinct_keys) === 497 && number(r.bound) === 497 ? [] : [{ code: "TIGER_STAGE_INVALID", message: "TIGER staging must contain all receipted national geometries." }]; },
    async loadFromStage(client, runId, releaseId) { if (!options.finalizeNationwide) throw new Error("NATIONWIDE_FINALIZE_REQUIRED"); await options.finalizeNationwide(client, runId, releaseId); },
  };
}
