/** Deterministic, I/O-free contract for retained national TIGER artifacts. */
import { NATIONWIDE_SEAT_POLICY } from "@/domain/validate-manifest";

export const TIGER_2025_JURISDICTIONS = { "01":"AL","02":"AK","04":"AZ","05":"AR","06":"CA","08":"CO","09":"CT","10":"DE","11":"DC","12":"FL","13":"GA","15":"HI","16":"ID","17":"IL","18":"IN","19":"IA","20":"KS","21":"KY","22":"LA","23":"ME","24":"MD","25":"MA","26":"MI","27":"MN","28":"MS","29":"MO","30":"MT","31":"NE","32":"NV","33":"NH","34":"NJ","35":"NM","36":"NY","37":"NC","38":"ND","39":"OH","40":"OK","41":"OR","42":"PA","44":"RI","45":"SC","46":"SD","47":"TN","48":"TX","49":"UT","50":"VT","51":"VA","53":"WA","54":"WV","55":"WI","56":"WY","60":"AS","66":"GU","69":"MP","72":"PR","78":"VI" } as const;
export type TigerStateFips = keyof typeof TIGER_2025_JURISDICTIONS;
export interface TigerGeometry { readonly type: "MultiPolygon"; readonly coordinates: readonly (readonly (readonly (readonly [number, number])[])[])[]; }
export interface NationalTigerFeature { readonly sourceGeoid:string; readonly sourceDistrictCode:string|null; readonly stateFips:TigerStateFips; readonly stateCode:string; readonly districtCode:string|null; readonly label?:string; readonly geometry:TigerGeometry; }
export interface NationalTigerArtifacts { readonly cd119:readonly NationalTigerFeature[]; readonly states:readonly NationalTigerFeature[]; }
export interface NationalTigerArtifactManifest { readonly schemaVersion:1; readonly srid:4326; readonly sourceArchives:Readonly<Record<string,string>>; readonly artifacts:Readonly<{cd119Sha256:string;statesSha256:string;cd119FeatureCount:441;stateFeatureCount:56}>; }
export interface StagingNationalTigerArtifactMetadata { readonly srid:4326; readonly sourceGeoid:string; readonly sourceDistrictCode:string|null; readonly stateFips:TigerStateFips; readonly stateCode:string; readonly districtCode:string|null; readonly label?:string; }
type RecordValue=Record<string,unknown>; type Kind="cd119"|"state";
const compare=(a:string,b:string)=>a<b?-1:a>b?1:0;
const record=(value:unknown):value is RecordValue=>typeof value==="object"&&value!==null&&!Array.isArray(value);
const fail=(message:string):never=>{throw new Error(`National TIGER: ${message}`);};
const validNumber=(value:unknown):value is number=>typeof value==="number"&&Number.isFinite(value);
const NON_VOTING_FIPS=new Set<TigerStateFips>(["11","60","66","69","72","78"]);
const expectedRawDistrictCodes=(stateFips:TigerStateFips):string[]=>{
  if(NON_VOTING_FIPS.has(stateFips)) return ["98"];
  const seats=NATIONWIDE_SEAT_POLICY[TIGER_2025_JURISDICTIONS[stateFips] as keyof typeof NATIONWIDE_SEAT_POLICY]?.[0];
  return seats===undefined?["00"]:seats===1?["00"]:Array.from({length:seats},(_,i)=>String(i+1).padStart(2,"0"));
};

function checkedGeometry(value:unknown,key:string):TigerGeometry {
  if (!record(value)) fail(`${key}: geometry must be Polygon or MultiPolygon`);
  const geometry=value as RecordValue; if (geometry.type!=="Polygon" && geometry.type!=="MultiPolygon" || !Array.isArray(geometry.coordinates)) fail(`${key}: geometry must be Polygon or MultiPolygon`);
  const polygons=(geometry.type==="Polygon"?[geometry.coordinates]:geometry.coordinates) as unknown[];
  if (!polygons.length) fail(`${key}: geometry is empty`);
  for (const polygon of polygons) { if (!Array.isArray(polygon)||!polygon.length) fail(`${key}: malformed polygon`); for (const ring of polygon as unknown[]) { if (!Array.isArray(ring)||ring.length<4) fail(`${key}: ring must have four coordinates`); let first:readonly [number,number]|undefined; let last:readonly [number,number]|undefined; for (const point of ring as unknown[]) { if (!Array.isArray(point)||point.length!==2||!validNumber(point[0])||!validNumber(point[1])||point[0]<-180||point[0]>180||point[1]<-90||point[1]>90) fail(`${key}: invalid longitude/latitude`); const coordinate=point as number[]; const pair:[number,number]=[coordinate[0]!,coordinate[1]!]; first??=pair; last=pair; } if (!first||!last||first[0]!==last[0]||first[1]!==last[1]) fail(`${key}: ring is not closed`); } }
  return { type:"MultiPolygon", coordinates:polygons as TigerGeometry["coordinates"] };
}
function canonicalFeature(value:unknown,kind:Kind,index:number):NationalTigerFeature {
  if (!record(value)) fail(`${kind}[${index}]: invalid Feature`); const raw=value as RecordValue; if(raw.type!=="Feature"||!record(raw.properties)) fail(`${kind}[${index}]: invalid Feature`);
  const p=raw.properties as RecordValue; const sourceGeoid=p.sourceGeoid; const sourceDistrictCode=p.sourceDistrictCode; const stateFips=p.stateFips; const stateCode=p.stateCode; const districtCode=p.districtCode;
  if(typeof sourceGeoid!=="string"||typeof stateFips!=="string"||!(stateFips in TIGER_2025_JURISDICTIONS)||typeof stateCode!=="string"||stateCode!==TIGER_2025_JURISDICTIONS[stateFips as TigerStateFips]) fail(`${kind}[${index}]: STATEFP/STUSPS/GEOID invalid`);
  const geometry=checkedGeometry(raw.geometry,`${kind}[${index}]`);
  if(kind==="state") { if(sourceDistrictCode!==null||districtCode!==null||sourceGeoid!==stateFips) fail(`${kind}[${index}]: malformed state GEOID`); return {sourceGeoid:sourceGeoid as string,sourceDistrictCode:null,stateFips:stateFips as TigerStateFips,stateCode:stateCode as string,districtCode:null,geometry}; }
  if(typeof sourceDistrictCode!=="string"||!/^[0-9]{2}$/.test(sourceDistrictCode)||typeof districtCode!=="string"||!/^(AL|[0-9]{2})$/.test(districtCode)||sourceGeoid!==`${stateFips}${sourceDistrictCode}`||districtCode!==(sourceDistrictCode==="00"||sourceDistrictCode==="98"?"AL":sourceDistrictCode)||p.cdSession!=="119"||typeof p.label!=="string") fail(`${kind}[${index}]: malformed CD119 GEOID/CDSESSN`);
  return {sourceGeoid:sourceGeoid as string,sourceDistrictCode:sourceDistrictCode as string,stateFips:stateFips as TigerStateFips,stateCode:stateCode as string,districtCode:districtCode as string,label:p.label as string,geometry};
}
function collection(value:unknown,kind:Kind):NationalTigerFeature[] { if(!record(value)) fail(`${kind}: not a FeatureCollection`); const raw=value as RecordValue; if(raw.type!=="FeatureCollection"||!Array.isArray(raw.features)) fail(`${kind}: not a FeatureCollection`); const rows=(raw.features as unknown[]).map((v:unknown,i:number)=>canonicalFeature(v,kind,i)); for(let i=1;i<rows.length;i++)if(compare(rows[i-1]!.sourceGeoid,rows[i]!.sourceGeoid)>=0)fail(`${kind}: GEOIDs must be unique bytewise ascending`); return rows; }
export function toStagingNationalTigerArtifactMetadata(row:NationalTigerFeature):StagingNationalTigerArtifactMetadata { return {srid:4326,sourceGeoid:row.sourceGeoid,sourceDistrictCode:row.sourceDistrictCode,stateFips:row.stateFips,stateCode:row.stateCode,districtCode:row.districtCode,...(row.label===undefined?{}:{label:row.label})}; }
export function nationalTigerFeatureToGeoJson(row:NationalTigerFeature):object { return {type:"Feature",properties:{...toStagingNationalTigerArtifactMetadata(row),...(row.districtCode===null?{}:{cdSession:"119"})},geometry:row.geometry}; }
export function parseNationalTigerArtifacts(cd119:unknown,states:unknown):NationalTigerArtifacts {
  const parsed={cd119:collection(cd119,"cd119"),states:collection(states,"state")}; if(parsed.cd119.length!==441||parsed.states.length!==56)fail("expected 441 CD119 and 56 state features");
  const stateSet=new Set(parsed.states.map(x=>x.stateFips)); if(stateSet.size!==56||Object.keys(TIGER_2025_JURISDICTIONS).some(x=>!stateSet.has(x as TigerStateFips)))fail("state artifact must contain exactly the 56 jurisdictions");
  for(const fips of Object.keys(TIGER_2025_JURISDICTIONS) as TigerStateFips[]){ const actual=parsed.cd119.filter(x=>x.stateFips===fips).map(x=>x.sourceDistrictCode); const required=expectedRawDistrictCodes(fips); if(actual.length!==required.length||actual.some((x,i)=>x!==required[i]))fail(`${fips}: congressional district closure does not match policy`); }
  return parsed;
}
export function normalizeRawNationalTigerCollection(value:unknown,kind:Kind):object { if(!record(value))fail(`${kind}: not a FeatureCollection`); const input=value as RecordValue; if(input.type!=="FeatureCollection"||!Array.isArray(input.features))fail(`${kind}: not a FeatureCollection`); const features=(input.features as unknown[]).map((raw:unknown,index:number)=>{if(!record(raw)||!record(raw.properties))fail(`${kind}[${index}]: invalid Feature`);const feature=raw as RecordValue; const p=feature.properties as RecordValue; if(typeof p.GEOID!=="string"||typeof p.STATEFP!=="string"||!(p.STATEFP in TIGER_2025_JURISDICTIONS))fail(`${kind}[${index}]: missing TIGER properties`); const stateFips=p.STATEFP as TigerStateFips; const stateCode=TIGER_2025_JURISDICTIONS[stateFips]; const district=kind==="cd119"?p.CD119FP:null; if(kind==="state"&&p.STUSPS!==stateCode)fail(`${kind}[${index}]: STATEFP/STUSPS invalid`); if(kind==="cd119"&&(typeof district!=="string"||p.CDSESSN!=="119"||typeof p.NAMELSAD!=="string"))fail(`${kind}[${index}]: missing CD119 properties`); return nationalTigerFeatureToGeoJson({sourceGeoid:p.GEOID as string,sourceDistrictCode:district as string|null,stateFips,stateCode,districtCode:district==="00"||district==="98"?"AL":district as string|null,...(kind==="cd119"?{label:p.NAMELSAD as string}:{}),geometry:checkedGeometry(feature.geometry,`${kind}[${index}]`)}); }).sort((a:object,b:object)=>compare((a as {properties:{sourceGeoid:string}}).properties.sourceGeoid,(b as {properties:{sourceGeoid:string}}).properties.sourceGeoid)); return {type:"FeatureCollection",features}; }
export function createNationalTigerManifest(sourceArchives:Readonly<Record<string,string>>,cd119Sha256:string,statesSha256:string,artifacts:NationalTigerArtifacts):NationalTigerArtifactManifest { parseNationalTigerArtifacts({type:"FeatureCollection",features:artifacts.cd119.map(nationalTigerFeatureToGeoJson)},{type:"FeatureCollection",features:artifacts.states.map(nationalTigerFeatureToGeoJson)}); const expected=[...Object.keys(TIGER_2025_JURISDICTIONS).map(f=>`tl_2025_${f}_cd119.zip`),"tl_2025_us_state.zip"].sort(compare); const keys=Object.keys(sourceArchives).sort(compare); if(keys.length!==57||keys.some((x,i)=>x!==expected[i])||keys.some(x=>!/^[a-f0-9]{64}$/.test(sourceArchives[x]!)))fail("source archive manifest must contain exactly 56 CD119 archives and the national state archive"); if(!/^[a-f0-9]{64}$/.test(cd119Sha256)||!/^[a-f0-9]{64}$/.test(statesSha256))fail("invalid artifact checksum"); return {schemaVersion:1,srid:4326,sourceArchives:Object.fromEntries(keys.map(k=>[k,sourceArchives[k]!])),artifacts:{cd119Sha256,statesSha256,cd119FeatureCount:441,stateFeatureCount:56}}; }
